### ISSUE TITLE
Is possible android injection with parent fragment/activity scope and child activity scope?

### ISSUE THREAD

**Issue by olegivo** [google/dagger#1008]
Hyerarchy of Android components:
- Application
    - MainActivity
        - SearchFragment
            - SearchResultsFragment
                - **SearchResultDetailFragment**
                    - **SpecificResultDetailInfoActivity** 

And according dagger components/subcomponents/modules:
- ...
- _SearchResultDetailFragmentModule_ has `@ContributesAndroidInjector` (or `AndroidInjector.Factory<? extends Activity>`)
- _SearchResultDetailFragmentComponent_ has subcomponent _SpecificResultDetailInfoActivityComponent_

Insinde _SpecificResultDetailInfoActivity.onCreate_ calling AndroidInjection.inject(SpecificResultDetailInfoActivity .this). It finding _Application_, that implements _HasActivityInjector_ (not _SearchResultDetailFragment_, that too can implenets _HasActivityInjector_!), getting AndroidInjector<Activity> and ask it to inject to this activity. 
But since InjectorFactory for _SpecificResultDetailInfoActivity_ declared in _SearchResultDetailFragmentModule_ (not in _ApplicationModule_), AndroidInjector cannot find according InjectorFactory for _SpecificResultDetailInfoActivity_.

And injection fails with error `IllegalArgumentException: No injector factory bound for Class<SpecificResultDetailInfoActivity>`

How can I solve this problem?

**Comment by olegivo** [comment]
Analogue problem will be if instead SearchResultDetailFragment will be SearchResultDetailActivity

**Comment by pushbit** [comment]
I believe I'm trying to do something similar with nesting `@ContributesAndroidInjector`.  I have an Activity that binds to a Service and I would like to inject the Service with dependencies from the Activity's module (which may be scoped to provide the same instance).

```java
    @ContributesAndroidInjector(modules = FooModule.class)
    abstract FooActivity fooActivityInjector();
```

FooModule:
```java
    @Binds/@Provides
    ...

    @ContributesAndroidInjector
    abstract FooService fooServiceInjector();
```

But it seems that the nested `@ContributesAndroidInjector` for FooService is ignored, `AndroidInjection.inject` is not able find it.  It's probably a rather rare situation and there are workarounds (I'm injecting a `MembersInjector<FooService>`), but would there be any desire to support this kind of nesting?

**Comment by ronshapiro** [comment]
There are ways you can probably configure if you want to do something a bit more custom, but the default `dagger.android` flow is to check up the chain (Fragment -> Fragment parent (if one exists) -> Activity -> Application) or (Service -> Application). If you want to shove some special information into the Application's `activityInjector()` method, by all means you can. But I don't think we're coming to come up with a default solution for everyone, so you're likely on your own for this.
