### ISSUE TITLE
Application -> Activity -> Controller

### ISSUE THREAD

**Issue by timrijckaert** [google/dagger#1016]
Hi, 

I'm just starting to grasp the idea of AndroidInjector and because I'm using `Controller`s instead of `Fragment`s I got stuck.  
However the setup should be quite similar to how it's done for `Fragment`s.

Say I have 3 dependencies each provided in their respective Modules:

1. `ApplicationDep`
2. `ActivityDep` 
3. `ControllerDep`

My `Controller` should be able to inject all 3 of them (`ApplicationDep`, `ActivityDep` and `ControllerDep`)  
My `Activity` should be able to inject `ApplicationDep` and the `ActivityDep`.  
Lastely my `Application` should solely be able to inject the `ApplicationDep`.

Currently my setup looks like this:

**AppComponent.java**
```
@Singleton
@Component(modules = {
        AppModule.class,
        ActivityBindingModule.class,

        AndroidSupportInjectionModule.class,
        ConductorInjectionModule.class
})
interface AppComponent extends AndroidInjector<App> {
    @Component.Builder
    abstract class Builder extends AndroidInjector.Builder<App> {}
}
```

_`ConductorInjectionModule` is used for injections in Controllers._ 

**ActivityBindingModule.java**
```
@Module
public abstract class ActivityBindingModule {

    @ActivityScope
    @ContributesAndroidInjector(modules = {MainActivityModule.class, ControllerBindingModule.class})
    abstract MainActivity mainActivity();
}
```

I found this similar question [here](https://github.com/google/dagger/issues/796), but for `Fragments`. That's why I'm placing the `ControllerBindingModule` here.

**ControllerBindingModule.java**
```
@Module(subcomponents = {ControllerComponent.class})
public abstract class ControllerBindingModule {
    @Binds
    @IntoMap
    @ControllerKey(MyController.class)
    abstract AndroidInjector.Factory<? extends Controller> bindHomeControllerInjectorFactory(ControllerComponent.Builder builder);
}
```

**ControllerComponent.java**
```
@ControllerScope
@Subcomponent(modules = {ControllerModule.class})
public interface ControllerComponent extends AndroidInjector<MyController> {
    @Subcomponent.Builder
    abstract class Builder extends AndroidInjector.Builder<MyController> {}
}
```

Thanks in advance.
Full code sample is available on my [GitHub](https://github.com/timrijckaert/conductor-dagger)
Tim

**Comment by ronshapiro** [comment]
This appears to be a question - please use StackOverflow with the `dagger-2` tag instead, as that is a better forum for questions.
