### ISSUE TITLE
use too hard

### ISSUE THREAD

**Issue by bwzhny** [google/dagger#1018]
can you provide a complete sample, Document is too simple, and version is update too fast, use too hard,
I find the most intact dagger.android sample is Eight months ago.

**Comment by ronshapiro** [comment]
There are a lot of blog posts out in the world - I recommend doing some searching and you can find lots of great examples!

**Comment by JonathanMerritt** [comment]
Here's one, [BoneDagger](https://github.com/JonathanMerritt/BoneDagger).
