### ISSUE TITLE
@ContributesAndroidInjector method is never used

### ISSUE THREAD

**Issue by bubenheimer** [google/dagger#1020]
In Android Studio methods annotated with `@ContributesAndroidInjector` are all flagged with:

    Method 'contributeFooInjector()' is never used

The Dagger APIs are largely designed around generating actual implementations for the various interfaces and abstract classes, which prevents these kinds of warnings. It appears different in this case. What is the best way to work around it? Can this be prevented by a change in the Dagger APIs? (Dagger 2.14.1)

**Comment by JakeWharton** [comment]
This is also true of `@Binds`

> Can this be prevented by a change in the Dagger APIs? 

No. Your IDE might have a configuration to not mark members containing certain annotations as unused though.

**Comment by tasomaniac** [comment]
In a newer version of IntelliJ and Android Studio, just Alt+Enter on the method where the warning is displayed. It will suggest you to remove this warning when the particular Annotation is used.

**Comment by bubenheimer** [comment]
Thanks, it appears I was able to disable warnings for specific annotation classes once I switched to AS 3.1.0 a short while ago.
