### ISSUE TITLE
Dependency cycle : How to inject a FragmentManager ?

### ISSUE THREAD

**Issue by sheaye** [google/dagger#1022]
My `FragmentAdapter`：
```
public class FragmentAdapter extends PagerAdapter {

    private final FragmentManager mFragmentManager;
    private List<Fragment> mFragments;

    @Inject
    public FragmentAdapter(FragmentManager fragmentManager, List<Fragment> fragments) {
        mFragmentManager = fragmentManager;
        mFragments = fragments;
    }
    ...
```
My `MainModule`:
```
@Module
public abstract class MainModule {

    @ContributesAndroidInjector
    @FragmentScoped
    abstract MainFragment mainFragment();

    ...

    @Provides
    @FragmentScoped
    static List<Fragment> provideFragmentList(HomeFragment home, NewsFragment news, MomentsFragment moments, WalletFragment wallet, PersonalFragment personal) {
        List<Fragment> fragments = new ArrayList<>();
        fragments.add(home);
        fragments.add(news);
        fragments.add(moments);
        fragments.add(wallet);
        fragments.add(personal);
        return fragments;
    }
    
    @Provides
    @FragmentScoped
    static FragmentManager provideFragmentManager(MainFragment mainFragment){
        return mainFragment.getChildFragmentManager();
    }
}
```

When I used it in my `MainFragment`:
```
public class MainFragment extends DaggerFragment {
    @Inject
    FragmentAdapter mFragmentAdapter;
}
```
I get the following error named dependency cycle:
```
Error:(25, 10) : [dagger.android.AndroidInjector.inject(T)] Found a dependency cycle:
...MainFragment is injected at
...MainModule.provideFragmentManager(mainFragment)
android.support.v4.app.FragmentManager is injected at
...FragmentAdapter.<init>(fragmentManager, …)
...FragmentAdapter is injected at
...MainFragment.mFragmentAdapter
...MainFragment is injected at
...MainActivity.mMainFragment
...MainActivity is injected at
dagger.android.AndroidInjector.inject(arg0)
```
So, could anyone tell me how to provide a FragmentManager to solve this problem? Thank you.

**Comment by ronshapiro** [comment]
This appears to be a question - please use StackOverflow with the `dagger-2` tag instead, as that is a better forum for questions.

**Comment by JonathanMerritt** [comment]
Just a thought but are you providing a FragmentManager on other scopes, ex `@ActivityScoped`?

If you end up asking on SO, post the link.

**Comment by homandiy** [comment]
I have tried to inject the FragmentManager in activity. It's working. However, after I copy the @inject FragmentManager fragmentManager into my RecyclerviewAdapter, system gives me a NPE. I can make it work with the constructor. 

How can I make @Inject FragmentManager work in the RecyclerviewAdapter?

**Comment by prasanthmurugan** [comment]
@homandiy could you please share the code on how to inject fragmentManger in dependency injection ?

**Comment by homandiy** [comment]
Are you sure? You switch fragments by fragmentTransaction.

**Comment by homandiy** [comment]
Where is your code?

**Comment by prasanthmurugan** [comment]
Thanks for the reply, In my case i used view pager in my home screen. 
so i need the fragment manger instance for pager adapter.

I solved using the below code

    @Module
    public class HomeModule {
    @Provides
    HomePageAdapter provideHomePageAdapter(@Home FragmentManager fragmentManager){
        return new HomePageAdapter(fragmentManager);
    }

    @Provides
    @Home //Qualifier for home
    FragmentManager provideFragmentManager(HomeActivity homeActivity){
        return homeActivity.getSupportFragmentManager();
    }
    }

**Comment by homandiy** [comment]
Thanks for sharing! I will try it on multiple fragments.

Homan Huang
