### ISSUE TITLE
Long file name issue

### ISSUE THREAD

**Issue by memfis19** [google/dagger#1024]
Hi, I've already read [https://github.com/google/dagger/issues/421](url), currently I'm using 2.13 dagger version but I got this error: 

/DaggerApplicationComponent$TaskPlannerActivitySubcomponentImpl$EmployeeDayViewHostFragmentSubcomponentImpl$EmployeeTaskListFragmentComponentBuilder.class (File name too long)

I am using ubuntu, with enabled encryption, can it be an issue? Or any help/advice how to fix it?

**Comment by naturalwarren** [comment]
One way you could mitigate this is breaking up your component tree by inserting vanilla components  in between subcomponents.

**Comment by memfis19** [comment]
Well, I don't think its a good idea, because it can lead to more complex structure and boilerplate code. The thing is that on other OS-s it works fine on mac os or windows and without enabled encryption. I found out that the max file name length on ubuntu with enabled encryption is 143 bytes, so possibly it can be an issue.

**Comment by memfis19** [comment]
The issue was really connected with enabled encryption, after disabling, it works.
