### ISSUE TITLE
MembersInjector doesn't get generated at the right time in multi-module gradle setup

### ISSUE THREAD

**Issue by remcomokveld** [google/dagger#1029]
I am trying to split up a project from a single gradle project to a structure with a core module, multiple feature modules and an application module composing those features.
Doing this without changing code caused dexing errors, because a MembersInjector was generated twice in two different feature modules.

I have created a sample project here which demonstrates this exception. The readme explains the issue in more detail
https://github.com/remcomokveld/DaggerDoubleMembersInjector

**Comment by tbroyer** [comment]
This is a dupe of #955 and #814

**Comment by remcomokveld** [comment]
Sorry about that, I should've searched closed issues as well
