### ISSUE TITLE
Generated Dagger components not found when referenced from a different Bazel rule

### ISSUE THREAD

**Issue by jschaf** [google/dagger#1030]
I'm having trouble using Bazel and with dagger.

```
git clone git@github.com:jschaf/bazel-dagger-example.git
cd bazel-dagger-example
bazel build //java/coffee
```

```
$ blaze build java/coffee
INFO: Analysed target //java/coffee:coffee (0 packages loaded).
INFO: Found 1 target...
ERROR: /home/jschaf/bazels/bazel-dagger-example/java/coffee/BUILD:11:1: Building java/coffee/libcoffee_lib.jar (2 source files) and running annotation processors (ComponentProcessor) failed (Exit 1)
bazel-out/k8-fastbuild/bin/java/coffee/_javac/coffee_lib/libcoffee_lib_sourcegenfiles/coffee/DaggerCoffeeApp_Coffee.java:4: error: cannot find symbol
import coffee.dripcoffee.DripCoffeeModule_ProvideHeaterFactory;
                        ^
  symbol:   class DripCoffeeModule_ProvideHeaterFactory
  location: package coffee.dripcoffee
bazel-out/k8-fastbuild/bin/java/coffee/_javac/coffee_lib/libcoffee_lib_sourcegenfiles/coffee/DaggerCoffeeApp_Coffee.java:6: error: cannot find symbol
import coffee.dripcoffee.PumpModule_ProvidePumpFactory;
                        ^
  symbol:   class PumpModule_ProvidePumpFactory
  location: package coffee.dripcoffee
```

If I move everything under 1 Bazel rule, everything works.

**Comment by tbroyer** [comment]
You need to add `generates_api = True` to `//third_party:dagger_plugin`. See https://groups.google.com/forum/#!msg/bazel-discuss/3-PtEwgTYKg/K7ZULWa3BAAJ

**Comment by ronshapiro** [comment]
Yup - this is https://github.com/simonhorlick/bazel-dagger-example/pull/1. But if you're using bazel, you really should depend on the dagger repository directory and not check in jars like in that example.

**Comment by ronshapiro** [comment]
See #871, with a fix forthcoming.

**Comment by jschaf** [comment]
Thanks all for the quick turn-around.

> But if you're using bazel, you really should depend on the dagger repository directory and not check in jars like in that example.

The problem using `http_archive` is that you need to re-define all external repositories defined by the dagger WORKSPACE file with matching names.  I've found it easier to use `new_http_archive` with my own BUILD rule for each repo so that I can control the external deps.

**Comment by ronshapiro** [comment]
> The problem using `http_archive` is that you need to re-define all external repositories defined by the dagger WORKSPACE file with matching names.  I've found it easier to use `new_http_archive` with my own BUILD rule for each repo so that I can control the external deps.

That's pretty much the MO of bazel, but do as you choose.
