### ISSUE TITLE
Ways to inject using dagger.android without creating subcomponent

### ISSUE THREAD

**Issue by guliash** [google/dagger#1032]
I often meet cases when injecting into Fragment or some other class (we wrote something like dagger.android but for [Conductor](https://github.com/bluelinelabs/Conductor)) does not need separate Subcomponent, because there is no new dependencies. Parent Subscomponent can successfully cope with injection.

I use MembersInjector and anonymous implementation of AndroidInjector.Factory<T> to avoid creating another empty Subcomponent:

```java
public class MyApplication extends Application implements HasActivityInjector {

    @Inject
    DispatchingAndroidInjector<Activity> activityInjector;

    @Override
    public void onCreate() {
        super.onCreate();

        DaggerMyApplicationComponent.create().inject(this);
    }

    @Override
    public AndroidInjector<Activity> activityInjector() {
        return activityInjector;
    }
}

@Component(modules = {AndroidSupportInjectionModule.class, MyApplicationModule.class})
public interface MyApplicationComponent {

    void inject(MyApplication myApplication);

}

@Module
public class MyApplicationModule {

    @Provides
    @IntoMap
    @ActivityKey(MainActivity.class)
    public AndroidInjector.Factory<? extends Activity> provideFactory(final MembersInjector<MainActivity> membersInjector) {
        return new AndroidInjector.Factory<MainActivity>() {
            @Override
            public AndroidInjector<MainActivity> create(MainActivity instance) {
                return new AndroidInjector<MainActivity>() {
                    @Override
                    public void inject(MainActivity instance) {
                        membersInjector.injectMembers(instance);
                    }
                };
            }
        };
    }

}

public class MainActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        AndroidInjection.inject(this);
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
    }
}

```

Is there any other way? What is the right way to do that (if there is one)? I can't use ContributesAndroidInjector because of non Android classes.

**Comment by ronshapiro** [comment]
That seems fine to me. I'm not sure why that would be more preferable than using a subcomponent, but if you find it to be less code and you're happy with it, then go for it.

You should note though that by using a `MembersInjector<T>`, Dagger is not able to inline any `Provider`s used to inject that `T`. If that's a concern, subcomponents may be the way to go.

**Comment by guliash** [comment]
Thank you for the quick response.
But factory classes for dependencies still get generated when we use subcomponents. Of course they will be removed by proguard as unused. But maybe you didn't know.

**Comment by naturalwarren** [comment]
Dagger eagerly generates factories to speed up compilation. If they're not referenced I think javac even strips them out.

**Comment by guliash** [comment]
@naturalwarren, I see. Thank you.
