### ISSUE TITLE
Error:Execution failed for task ':app:compileDebugJavaWithJavac'. > java.lang.NoClassDefFoundError: dagger/Multibindings

### ISSUE THREAD

**Issue by doruchidean** [google/dagger#1034]
Hi,

I recently updated the dagger version from 2.9 to 2.11 and the above error message occured.
I tried a few suggested solutions like Invalidate caches and restart and adding the multidex library, however the issue persisted.
However, downgrading back to 2.9 resulted in a successful build.

Might be worth mentioning, at the same time I updated the compileSdkVersion, and support libs to 26 .

**Comment by ronshapiro** [comment]
`@dagger.Multibindings` was removed - but it should only have ever been an annotation and never actually referenced anywhere in your app. Check to make sure that none of your dependencies are somehow referring to that somewhere, perhaps they are depending on an old version of Dagger?
