### ISSUE TITLE
Add support for MultiDexApplication

### ISSUE THREAD

**Issue by Seylox** [google/dagger#1035]
Please add support for MultiDexApplication in `DaggerApplication`. This would only require extending from `MultiDexApplication` instead of `Application`. Or is there a good way to use this that I'm not aware of?

**Comment by JakeWharton** [comment]
You can copy the implementation of `DaggerApplication` directly into your `Application` subclass. It's only a few lines.

**Comment by Seylox** [comment]
Thanks for your response. I hope I'm correct in assuming that a) the implementation for `DaggerApplication` is not likely to change and b) you're not going to consider supporting `MultiDexApplication`?

**Comment by JakeWharton** [comment]
I don't speak for the Dagger team, but the documentation indicates that these base classes are merely provided as a convenience around the supported mechanism and instructions for doing it yourself:

> Because `DispatchingAndroidInjector` looks up the appropriate `AndroidInjector.Factory` by the class at runtime, a base class can implement `HasActivityInjector`/`HasFragmentInjector`/etc as well as call `AndroidInjection.inject()`. All each subclass needs to do is bind a corresponding @Subcomponent. Dagger provides a few base types that do this

**Comment by ronshapiro** [comment]
@JakeWharton is right, but what is likely to be even smaller (and even less likely to change) is to keep the `DaggerApplication` base class and copy the contents of the [`MultidexApplication` implementation](https://android.googlesource.com/platform/frameworks/multidex/+/master/library/src/android/support/multidex/MultiDexApplication.java). This is a documented approach by the [`MultidexApplication` docs](https://developer.android.com/reference/android/support/multidex/MultiDexApplication.html)

**Comment by JakeWharton** [comment]
Wow that's tiny!

**Comment by Ezike** [comment]
the links you pasted are now blank. Can you check em out please @ronshapiro

**Comment by imohamedsoliman** [comment]
@Ezike from docs if you don't have the option to extend the MultidexApplication you can do this

```
class MyApplication : SomeOtherApplication() {

    override fun attachBaseContext(base: Context) {
        super.attachBaseContext(base)
        MultiDex.install(this)
    }
}
```
[Docs](https://developer.android.com/studio/build/multidex)
