### ISSUE TITLE
Is it possible for AndroidInjection to have android.support.v4.app.Fragment injection?

### ISSUE THREAD

**Issue by jutikorn** [google/dagger#1038]
I can find inject() method for Activity, **android.app.Fragment**, **Service**, **BroadcastReceiver** and **ContentProvider** but it doesn't have **android.support.v4.app.Fragment** inject method.  Is it in the roadmap to **support android.support.v4.app.Fragment** too?

**Comment by naturalwarren** [comment]
You need to use the support artifact, then inject with `AndroidSupportInjection`.

```
dependencies {
  compile 'com.google.dagger:dagger-android:2.x'
  compile 'com.google.dagger:dagger-android-support:2.x' // if you use the support libraries
  annotationProcessor 'com.google.dagger:dagger-android-processor:2.x'
}
```
