### ISSUE TITLE
warning: [unchecked] unchecked method invocation: method singletonMap in class Collections is applied to given types

### ISSUE THREAD

**Issue by jaredsburrows** [google/dagger#1039]
Can suppress `unchecked` in the generated code to prevent warnings during compilation?

## Issue:
`warning: [unchecked] unchecked method invocation: method singletonMap in class Collections is applied to given types`

## Error:
```
$ gradlew assembleDEbug

> Task :compileDebugJavaWithJavac FAILED
/Users/<>/repo/android-gif-example/build/generated/source/kapt/debug/burrows/apps/example/gif/presentation/di/component/DaggerAppComponent.java:60: warning: [unchecked] unchecked method invocation: method singletonMap in class Collections is applied to given types
            singletonMap(MainActivity.class, (Provider) mainActivitySubcomponentBuilderProvider);
                        ^
  required: K,V
  found: Class<MainActivity>,Provider
  where K,V are type-variables:
    K extends Object declared in method <K,V>singletonMap(K,V)
    V extends Object declared in method <K,V>singletonMap(K,V)
/Users/<>/repo/android-gif-example/build/generated/source/kapt/debug/burrows/apps/example/gif/presentation/di/component/DaggerAppComponent.java:60: warning: [unchecked] unchecked conversion
            singletonMap(MainActivity.class, (Provider) mainActivitySubcomponentBuilderProvider);
                                             ^
  required: V
  found:    Provider
  where V,K are type-variables:
    V extends Object declared in method <K,V>singletonMap(K,V)
    K extends Object declared in method <K,V>singletonMap(K,V)
/Users/<>/repo/android-gif-example/build/generated/source/kapt/debug/burrows/apps/example/gif/presentation/di/component/DaggerAppComponent.java:60: warning: [unchecked] unchecked conversion
            singletonMap(MainActivity.class, (Provider) mainActivitySubcomponentBuilderProvider);
                        ^
  required: Map<Class<? extends Activity>,Provider<Factory<? extends Activity>>>
  found:    Map
error: warnings found and -Werror specified
1 error
3 warnings


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 9s
17 actionable tasks: 16 executed, 1 up-to-date
```
## Temp fix:
`"-Xlint:-unchecked"`

**Comment by ronshapiro** [comment]
Shouldn't we be specifying type parameters there (https://github.com/google/dagger/blob/beeb29d6a3a3a00488c6e42fad554bd8ae917ca2/java/dagger/internal/codegen/MapBindingExpression.java#L129-L130,L134-L140)?

Can you provide a failing example?

**Comment by jaredsburrows** [comment]
@ronshapiro A failing example? The code above fails with `-Werror` or will simply produce the following warnings and not fail the build.

The specific line is: `singletonMap(MainActivity.class, (Provider) mainActivitySubcomponentBuilderProvider);`.

**Comment by ronshapiro** [comment]
I meant a small repo that exhibits the issue (that we can test+verify a fix on)

**Comment by jaredsburrows** [comment]
@ronshapiro Oh sorry, I usually add that in the description. Here are the repro steps:

1. git clone https://github.com/jaredsburrows/android-gif-example
2. cd android-gif-example
3. Comment out or remove `add("-Xlint:-unchecked")` from https://github.com/jaredsburrows/android-gif-example/blob/master/gradle/compile.gradle.kts#L16
4. graldew assembleDebug

**Comment by jaredsburrows** [comment]
Any update on this?

**Comment by ronshapiro** [comment]
I see what's happening - there's a `@Binds` method that is being requested as a provider, which causes Dagger to cast to a rawtype.

Unfortunately, I don't know of a good way to fix this without suppressing warnings over far too much code.

**Comment by ronshapiro** [comment]
Actually, we may be able to check in `MapBindingExpression` if the type is the erasure but could be the accessible type. This should also probably happen in other places where BindingExpressions are composed too.

**Comment by gildor** [comment]
@ronshapiro Any updates? I suppose that would be better to suppress warning if it's hard/impossible to fix, after all this is generated code. This cause problem with real problems detection using `-Werror` option.
Also in my case I see additional warning:
```
unchecked call to put(K,V) as a member of the raw type MapBuilder
```
for the generated code of method `getMapOfClassOfAndProviderOfFactoryOf2` that puts my dagger-android providers for activity to `MapBuilder`

**Comment by ronshapiro** [comment]
I'm leaning towards an approach like this one: https://github.com/google/dagger/issues/1248#issuecomment-417139381

**Comment by gildor** [comment]
It's little bit unfortunate that it cannot be fixed on side of dagger, but approach form your comment still works and allows use -Werror
