### ISSUE TITLE
Can't generate classes on Android since javax.annotation is not available

### ISSUE THREAD

**Issue by mpost** [google/dagger#104]
Android does not ship with the <code>javax.annotation</code> package so the generated code with <code>@Generated</code> does not compile.

One can add the dependency manually eg:

<code>compile 'javax.annotation:javax.annotation-api:1.2-b01'</code>

**Comment by JakeWharton** [comment]
Dupe of #95.

**Comment by mpost** [comment]
@JakeWharton Correct. GitHub search didn't surface that one.
