### ISSUE TITLE
Warning: dagger.android.AndroidInjector: can't find referenced class 

### ISSUE THREAD

**Issue by jaredsburrows** [google/dagger#1040]
Should we add proguard rules to the README.md?

## Error:
```
Warning: dagger.android.AndroidInjector: can't find referenced class com.google.errorprone.annotations.DoNotMock
Warning: dagger.android.AndroidInjector$Builder: can't find referenced class com.google.errorprone.annotations.DoNotMock
Warning: dagger.android.AndroidInjector$Factory: can't find referenced class com.google.errorprone.annotations.DoNotMock
Warning: dagger.android.DaggerApplication: can't find referenced class com.google.errorprone.annotations.ForOverride
Warning: dagger.android.DispatchingAndroidInjector: can't find referenced class com.google.errorprone.annotations.CanIgnoreReturnValue
Warning: dagger.android.package-info: can't find referenced class com.google.errorprone.annotations.CheckReturnValue
Warning: dagger.android.support.package-info: can't find referenced class com.google.errorprone.annotations.CheckReturnValue
```

See https://stackoverflow.com/questions/45908252/dagger-android-support-proguard-rules

**Comment by ronshapiro** [comment]
Yea, I guess we should add proguard rules to the aar?

**Comment by jaredsburrows** [comment]
Sure! Via AAR via `BuildType:consumerProguardFiles`(https://google.github.io/android-gradle-dsl/current/com.android.build.gradle.internal.dsl.BuildType.html#com.android.build.gradle.internal.dsl.BuildType:consumerProguardFiles) or add to the README because I only encountered this when using the `dagger.android` artifact.

**Comment by ronshapiro** [comment]
We use Bazel, so this is what you're looking for: https://docs.bazel.build/versions/master/be/android.html#android_library.proguard_specs

**Comment by jaredsburrows** [comment]
@ronshapiro Yes, I know you use Bazel, that is why I asked you to add Bazel rules to the `README.md` previously.

I am saying that we either need instructions to ignore those warnings via Proguard or add them to `AAR` existing. 

Are you saying that the Gradle equivalent of `consumerProguardFiles` in Bazel is `proguard_specs`?

**Comment by ronshapiro** [comment]
> I am saying that we either need instructions to ignore those warnings via Proguard or add them to `AAR` existing. 
Wherever we can do the Right Thing™️ instead of requiring users to do work on their own, the better. If aar is the way to go (and AFAICT it is) that should solve the issue for everyone.

> Are you saying that the Gradle equivalent of `consumerProguardFiles` in Bazel is `proguard_specs`?

Yup!

**Comment by gengjiawen** [comment]
@ronshapiro Any plan to release a version for this issue ?
