### ISSUE TITLE
MapKey(unwrapValue = false) don't work when building with Maven

### ISSUE THREAD

**Issue by AndreyMoiseev** [google/dagger#1043]
Dagger automatically generates annotation factory class. The generated implementation is based on Google Autovalue. It supposed to work as this:
* (1) Dagger generates source file for annotation factory
* (2) Autovalue generates source file for annotation implementation

It appears, that Maven cannot do annotation processing based on other processor output. It makes MapKey(unwrapValue = false) totally unusable with Maven. 
I would be nice to have an option to turn off automatic generation of annotation factory.

**Comment by ronshapiro** [comment]
I don't follow - can you describe the error you're seeing? Can you provide a sample maven project that exhibits this? 

What version of Dagger are you using? And do you have AutoValue on the classpath?
