### ISSUE TITLE
Most of the code in generated MembersInjector implementations is unused

### ISSUE THREAD

**Issue by vanniktech** [google/dagger#1047]
I've nailed it down to this simple example which can already describe the optimization:

```java
class Bar {
  @Inject Foo foo;

  void inject() {
    DaggerBar_ApplicationComponent.builder()
        .foo(new Foo())
        .build()
        .inject(this);
  }

  static class Foo {

  }

  @Singleton @Component interface ApplicationComponent {
    void inject(Bar bar);

    @Component.Builder interface Builder {
      @BindsInstance Builder foo(Foo foo);

      ApplicationComponent build();
    }
  }
}
```

This will correctly generate a `DaggerBar_ApplicationComponent` that is able to inject Foo. However it does so by:

```java
@Override
public void inject(Bar bar) {
  injectBar(bar);
}

private Bar injectBar(Bar instance) {
  Bar_MembersInjector.injectFoo(instance, foo);
  return instance;
}
```

`Bar_MembersInjector.injectFoo` simply does:

```java
public static void injectFoo(Object instance, Object foo) {
  ((Bar) instance).foo = (Bar.Foo) foo;
}
```

Which leaves all of the other code unused:

```java
@Generated(
  value = "dagger.internal.codegen.ComponentProcessor",
  comments = "https://google.github.io/dagger"
)
public final class Bar_MembersInjector implements MembersInjector<Bar> {
  private final Provider<Bar.Foo> fooProvider;

  public Bar_MembersInjector(Provider<Bar.Foo> fooProvider) {
    this.fooProvider = fooProvider;
  }

  public static MembersInjector<Bar> create(Provider<Bar.Foo> fooProvider) {
    return new Bar_MembersInjector(fooProvider);
  }

  @Override
  public void injectMembers(Bar instance) {
    injectFoo(instance, fooProvider.get());
  }
}
```

Will this be optimized away so that Dagger generates less code?

**Comment by ronshapiro** [comment]
Yup, Proguard should be able to detect that the contents of the class are never used.

We _could_ separate the static members injection methods into a different class, but I don't think there's enough value to do that.

We generate the `MembersInjector<T>` implementation eagerly because we don't know if we'll need it until later on. That extra code shouldn't really affect compilation much though - if you're seeing otherwise, let us know?

**Comment by vanniktech** [comment]
I know that Proguard will optimize this away. My question was whether Dagger will just choose to not generate it at all - which seems like you don't want to since you're generating those eagerly.

Can't it be figured out whether that code is needed or not and then only generate it when it's needed? It seems a bit wasteful to do more than necessary.

**Comment by ronshapiro** [comment]
The members injector may be compiled in a different compilation from the component, so compiling it early is a time saving from our analysis.

**Comment by vanniktech** [comment]
Alright that clarifies it. Thanks.
