### ISSUE TITLE
Flag when dependencies can be retrieved in different ways.

### ISSUE THREAD

**Issue by vanniktech** [google/dagger#1048]
Given the following scenario:

```java
class Bar {
  @Inject Foo foo;

  void inject() {
    DaggerBar_ApplicationComponent.create()
        .inject(this);
  }

  static class Foo {
    @Inject public Foo() {

    }
  }

  @Module static class FooModule {
    @Provides static Foo provideFoo() {
      return new Foo();
    }
  }

  @Singleton @Component(modules = FooModule.class) interface ApplicationComponent {
    void inject(Bar bar);
  }
}
```

The Foo dependency can be retrieved in two different ways.

- Just calling new Bar.Foo()
- Using the FooModule to get an instance of Foo

It's not necessary to have both ways there. I've noticed that during refactoring often you introduce this subtle filthiness. In this case Dagger seems to favor the Module over the `@Inject` on the constructor and hence uses that.

Would it be possible to flag those cases where dependencies can be retrieved in different ways?

**Comment by ronshapiro** [comment]
It's probably possible, but there are situations where people want this to be the case (this is also what Guice and other JSR 330 implementations do, IIUC), and in some contexts you can change the dependencies that you pass to the constructor.

I think this would be appropriate as an SPI (almost ready!) plugin or even an error-prone check, but the exact parameters that we'd want to warn on are probably different for different users.

**Comment by JakeWharton** [comment]
Dagger will only allow one binding per type so you can never retrieve
instances in two ways. The ability to bind a type in a module to override
an annotated-constructor is an essential feature when the type is not in
the same compilation unit.

**Comment by vanniktech** [comment]
Sounds like this could be an example for the new SPI feature to showcase it.

**Comment by ronshapiro** [comment]
I'm going to close this - writing the SPI check should be simple. Loop through bindings and check if they're unqualified and if their defining type has an `@Inject` constructor.
