### ISSUE TITLE
Is it possible to use Dagger in OSGI environment? 

### ISSUE THREAD

**Issue by yegorch** [google/dagger#106]
Hi guys, I've used dagger for android development liked it very much and intending to use it for the server-side as well. My project has a hot redeployment requirement and I wonder could I use Dagger somehow in OSGI environment. I've tried it with Apache Karaf and it's doesn't works. 
 
Could someone clarify is Dagger an OSGI ready?

**Comment by cgruber** [comment]
So... i think the question is - how do you want it to work with in OSGI.  Dagger and OSGI are entirely orthogonal.  Dagger generates classes that wire up a graph.  How you materialize that depends on when and how you call the builders.  OSGI works a little differently, so it depends entirely on where the seams in your graph are, and how you want them to stitch together. 

So... the answer is "no" or "yes" depending on what you're trying to do.   Can you clarify further what your use-cases are, please?

**Comment by cgruber** [comment]
Closing this for now - feel free to re-open it with more information.
