### ISSUE TITLE
Latest versions requires GPL 2.0? 

### ISSUE THREAD

**Issue by HongbinHuang** [google/dagger#1083]
We are trying to upgrade Dagger from 2.11 to 2.14.1 and got blocked because below two dependencies are on GPL 2.0, any way to avoid that? Thanks!

com.google.errorprone:javac-shaded@9-dev-r4023-3
org.checkerframework:checker-compat-qual@2.3.0

**Comment by tbroyer** [comment]
JavaC is the same (a fork) as the JavaC tool from OpenJDK; it does not leak into your program, and is only a build-time dependency.

Checker framework annotations are under MIT: https://github.com/typetools/checker-framework/blob/master/LICENSE.txt

**Comment by HongbinHuang** [comment]
Got it, thanks!
