### ISSUE TITLE
@ContributesAndroidInjector on two Fragments with same simple name causing error

### ISSUE THREAD

**Issue by HongbinHuang** [google/dagger#1085]
I know it's not a good practice to have two Fragments with same simple name, but dagger-android should be able to handle it.

Version: 2.14.1

Example:
```java
@Module
@FragmentScope
public abstract class FragmentBuildersModule {
    @NonNull
    @FragmentScope
    @ContributesAndroidInjector(modules = FragmentModule.class)
    abstract com.a.MyFragment aMyFragment();

    @NonNull
    @FragmentScope
    @ContributesAndroidInjector(modules = FragmentModule.class)
    abstract com.b.MyFragment bMyFragment();
}
```

Error message:

ActivityBuildersModule_ContributeLaunchActivityInjector.java:28: error: [dagger.android.AndroidInjector.inject(T)] The same map key is bound more than once for java.util.Map<java.lang.Class<? extends android.support.v4.app.Fragment>,javax.inject.Provider<dagger.android.AndroidInjector.Factory<? extends android.support.v4.app.Fragment>>>

**Comment by ronshapiro** [comment]
Can you provide a condensed sample in a github repo that we could look at?
