### ISSUE TITLE
Dagger Android with multiple levels of (Sub)Components

### ISSUE THREAD

**Issue by manuelvicnt** [google/dagger#1087]
I wonder if it's possible to have different levels of Components or Subcomponents using Dagger Android. 

The idea is to abstract common Subcomponents data out to a common Component or Subcomponent. 
Something like: `ApplicationComponent -> CommonLoginSubcomponent -> LoginActivitySubcomponent`

CommonLoginSubcomponent could be either a Subcomponent or a Component.

I tried implementing something like that and Dagger couldn't generate the Subcomponent Builder of `LoginActivitySubcomponent` from the `CommonLoginSubcomponent` that should've been used in the generated code of `ApplicationComponent` to inject the `LoginActivity` with the `LoginActivitySubcomponent`.

I assume this is not possible to do with Dagger Android right now. It seems like it only allows a level in the subcomponent hierarchy and doesn't allow having other Components including `ApplicationComponent`.

Is there any plans on implementing this solution in the future? 
Ideally, an intermediate Component or Subcomponent would also be able to support the `@IntoMap` bindings between Activities and Subcomponent Builders.

**Comment by manuelvicnt** [comment]
@jhowens89 that's definitely the type of approach I was expecting from Dagger Android. That's what I had in mind if I had to implement a custom solution. However, instead of SharedLogic, I'd group them by features: e.g. registration, login, feature1, feature2...

Thanks for commenting

**Comment by manuelvicnt** [comment]
Hi @ronshapiro 

Do you know if this is possible with the current version or if you have some plans to add support to this in future versions of Dagger Android? 

Thank you.

**Comment by arekolek** [comment]
To me, [this gtihub repo](https://github.com/ragdroid/Dahaka) looks like it implements what's described in this issue.

**Comment by ronshapiro** [comment]
Here's a snippet I recently wrote up about this: https://github.com/google/dagger/issues/1267
