### ISSUE TITLE
Bundled Android Proguard rules in 2.15 not taking effect

### ISSUE THREAD

**Issue by krage** [google/dagger#1091]
I've had `-dontwarn com.google.errorprone.annotations.*` in my project's proguard rules for a while now waiting for dagger's consumer rules to be bundled.  I saw a related PR was merged for 2.15 so I've tried building *without* that line in my project's rules and I still get the same handful of "can't find referenced class" errors pointing to that package that I was getting prior to 2.15.

**Comment by ronshapiro** [comment]
You're right, I'm not seeing those in the packaged `aar`. I'll investigate

**Comment by ronshapiro** [comment]
Apparently it's not included in the aar in Bazel...

**Comment by ronshapiro** [comment]
Here's the issue in Bazel: https://github.com/bazelbuild/bazel/issues/4467

**Comment by jaredsburrows** [comment]
@ronshapiro Was this not the correct fix, https://github.com/google/dagger/pull/1059? Or does bazel have a separate issue on their end?

**Comment by ronshapiro** [comment]
That only fixed things for Bazel users. Bazel is not (yet) actually adding it to the aar though (it uses it in its internal implementation)

**Comment by ronshapiro** [comment]
This is now in bazel, and at least working in 2.17, possibly 2.16 too.
