### ISSUE TITLE
Adding @Component.Builder + @BindsInstance shadows the parent Builder

### ISSUE THREAD

**Issue by ensonic** [google/dagger#1097]
The docs suggest this pattern:
https://google.github.io/dagger/users-guide.html#binding-instances

Lets say, I have this code:
``` java
AbcComponent component =
        DaggerAbcServer_AbcComponent.builder()
          .setGrpcModule(new GrpcModule(55052))
          .build();
```
Now I need another param and do as the above docs suggest
```java
public interface AbcComponent {
    ...

    @Component.Builder
    interface Builder {
      @BindsInstance
      Builder setFooBar(FooBar fooBar);

      AbcComponent build();
    }
  }
```
Now this shadows the DaggerAbcServer_AbcComponent.Builder(), right? Sofar it looks like I have to duplicate the setter:
```java
    @Component.Builder
    interface Builder {
      @BindsInstance
      Builder setFooBar(FooBar fooBar);

      @BindsInstance
      Builder setGrpcModule(GrpcModule grpcModule);

      AbcComponent build();
    }
```

It this is expected, it would be nice to document it atleast.

**Comment by ronshapiro** [comment]
`@BindsInstance` isn't meant for modules. We should validate that.

"shadow" isn't really the right term - the auto-generated builder API is not generated if you have a `@Component.Builder` of your own.
