### ISSUE TITLE
Document how to install Maven artifacts locally on a Mac

### ISSUE THREAD

**Issue by msridhar** [google/dagger#1098]
I made some local changes to the Dagger source and wanted to install the artifacts to my `~/.m2/repository` to try them out, but I had some difficulty.  Based on reading some scripts, I tried this:
```
./util/execute-deploy.sh install:install-file 2.15.1-LOCAL --settings=util/settings.xml
```
This correctly generated the POM files, but the installation failed with an error:
```
[ERROR] The goal you specified requires a project to execute but there is no POM in this directory (/Users/msridhar/git-repos/dagger). Please verify you invoked Maven from the correct directory. -> [Help 1]
```
This was all run after doing `bazel build //...`.  Did I do something wrong?  Happy to submit a documentation PR once I figure out how this works 😄

**Comment by ronshapiro** [comment]
Does `util/install-local-snapshot.sh` work? That's what I use on Linux, I don't think I've tried it on Mac

**Comment by msridhar** [comment]
Oh that works!  I'm pretty sure I tried that before and had some issue, but everything works fine now.  Thanks so much!
