### ISSUE TITLE
Question: Why do sole+default constructors need to be annotated with @Inject?

### ISSUE THREAD

**Issue by twentylemon** [google/dagger#1105]
I recently used dagger 2 in a project for the first time. I'm used to spring (don't hate me), so my initial setup was wrong -- I made what seems like a reasonable assumption. It wrote something like this:

```java
class NeedsInjecting {
    @Inject Dependency d;
    void init() {
        DaggerObjectGraph.builder().build().inject(this);
    }
}

class Dependency {
    // only has an implicit default constructor, but no @Inject ctor
}

@Component
class ObjectGraph {
    void inject(NeedsInjecting n);
    Dependency dependency();
}
```

In spring (if spring had the inject() method), this would work as expected, spring creates `Dependency` by invoking the default constructor. I instead get the compile time error:

`Dependency cannot be provided without an @Inject constructor or from an @Provides- or @Produces-annotated method.`

The message is clear enough, this is fixed by writing
```java
class Dependency {
    @Inject Dependency(){}
}
```

It is also mentioned on the [user guide](https://google.github.io/dagger/users-guide), which I missed on the first read through:

> If your class has @Inject-annotated fields but no @Inject-annotated constructor, Dagger will inject those fields if requested, but will not create new instances. Add a no-argument constructor with the @Inject annotation to indicate that Dagger may create instances as well.

Coming from spring (iirc, guice does the same), this requirement is odd to me -- even if I had fields which needed injecting in `Dependency`, why does dagger refuse to use the sole default constructor? Why force me to write a constructor if the language already does it for me?

I'm curious as to the motivation here. I understand for non-sole ctors, `@Inject` resolves the ambiguity. For non-default, I can see it being confusing to a reader if they don't specify `@Inject` on the fields. But for sole default constructors, there's no ambiguity, nor any readability concerns (imo).

**Comment by ronshapiro** [comment]
Dagger prefers the binding graph to be declared explicitly so that there is no confusion where bindings come from. It's true that JSR 330 does specify that default no-arg constructors do not require `@Inject` but from our experience, this causes more confusion than it saves extra characters to type.

**Comment by tbroyer** [comment]
See https://github.com/square/dagger/issues/412

**Comment by twentylemon** [comment]
The other issue contains a lot of context, thanks!
