### ISSUE TITLE
ViewModel is instantiated every configuration change if injected through DaggerActivity

### ISSUE THREAD

**Issue by avallini** [google/dagger#1107]
Tried to use android ViewModel (architecture component) with dagger and I spotted that this was instantiated every configuration change. After investigating came up that (due to how the ViewModelProviders works) this is a side effect of injecting the component before calling the super.onCreate(). Actual DaggerActivity code:

```
  @Override
  protected void onCreate(@Nullable Bundle savedInstanceState) {
    AndroidInjection.inject(this);
    super.onCreate(savedInstanceState);
  }
```
Just switching the two statements do the job:

```
  @Override
  protected void onCreate(@Nullable Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    AndroidInjection.inject(this);
  }
```
I don't see any drawback on this.

Andrea

**Comment by dmapr** [comment]
I've worked around that by injecting `Lazy<ViewModel>` instead of ViewModel.

**Comment by ashdavies** [comment]
So far I've found it more convenient to fetch the view model directly and allow Dagger to generate the provider that can be used with the architecture components factory to only generate it once, this allows your view model to contain dependencies.

**Comment by avallini** [comment]
@ashdavies That's another approach, but you can also inject the view model factory in your @Provide view model method. This way your activity would be cleaner as the activity don't need to know about the view model factory. The only things to do is to inject the view model and inherit from DaggerActivity.

@dmapr sure also injecting a provider would work around the issue.

I think that the main point here is: Is it really needed to call AndroidInjection.inject(this) before the super.onCreate? Lower level in class hierarchy don't know anything about dagger injected fields so should be safe to inject after (if I'm not missing something).

**Comment by liminal** [comment]
@avallini the reason it's there can be found here https://github.com/google/dagger/issues/598

**Comment by avallini** [comment]
Thanks @liminal !
Didn't found it before. My bad. Well, in that case I suppose that the only solution is to workaround with Lazy. Closing the issue!
