### ISSUE TITLE
Postpone module creation in DaggerAndroid

### ISSUE THREAD

**Issue by 3mph4515** [google/dagger#1108]
Hi! 
I've faced the following problem: I have ApplicationComponent which works with two modules(Module1 and Module2). Right now all dependencies provided by two modules creates on application start. But my Module2 is parameter dependent and this parameter I receive later than application start. Is it possible to postpone second module creation until I got this parameter and still keep my Module2 provided dependencies as Singleton?

**Comment by ronshapiro** [comment]
Not without either creating a subcomponent or doing something hacky. 

Can you instead inject an object which knows how to retrieve this value?

Since this is a question, I recommend continuing the conversation on StackOverflow
