### ISSUE TITLE
Error message "@Inject constructors are invalid on inner classes" should be replaced with "@Inject constructors are invalid on non-static inner classes"

### ISSUE THREAD

**Issue by pchmielowski** [google/dagger#1109]
It seems that Dagger accepts static inner class with `@Inject` annotated constructor. Error message should reflect it.

**Comment by ronshapiro** [comment]
Inner classes are by-definition non-static. I think you're getting confused between "inner" and "nested" (which I do all the time). The official docs call inner classes as non-static nested classes: https://docs.oracle.com/javase/tutorial/java/javaOO/innerclasses.html

Either way, we can provide a suggestion in the error.

**Comment by pchmielowski** [comment]
Wow, I didn't know that! Thanks for explanation!

I think a suggestion would be great, I'm pretty sure many developers are moving the classes to the separate file and don't know they can just add `static` keyword.
