### ISSUE TITLE
issue android studio com.google.auto:auto:common:8.0

### ISSUE THREAD

**Issue by Riyaz7364** [google/dagger#1115]
Error:Could not resolve all files for configuration ':app:debugAnnotationProcessorClasspath'.
> Could not resolve com.google.auto:auto-common:0.8.
  Required by:
      project :app > com.jakewharton:butterknife-compiler:8.8.1
   > Could not resolve com.google.auto:auto-common:0.8.
      > Could not parse POM https://jcenter.bintray.com/com/google/auto/auto-common/0.8/auto-common-0.8.pom
         > Could not resolve com.google.auto:auto-parent:3.
            > Could not resolve com.google.auto:auto-parent:3.
               > Could not parse POM https://jcenter.bintray.com/com/google/auto/auto-parent/3/auto-parent-3.pom
                  > Content is not allowed in prolog.
            > Could not resolve com.google.auto:auto-parent:3.
               > Could not parse POM https://jcenter.bintray.com/com/google/auto/auto-parent/3/auto-parent-3.pom
                  > Content is not allowed in prolog.
   > Could not resolve com.google.auto:auto-common:0.8.
      > Could not parse POM https://jcenter.bintray.com/com/google/auto/auto-common/0.8/auto-common-0.8.pom
         > Could not resolve com.google.auto:auto-parent:3.
            > Could not resolve com.google.auto:auto-parent:3.
               > Could not parse POM https://jcenter.bintray.com/com/google/auto/auto-parent/3/auto-parent-3.pom
                  > Content is not allowed in prolog.
            > Could not resolve com.google.auto:auto-parent:3.
               > Could not parse POM https://jcenter.bintray.com/com/google/auto/auto-parent/3/auto-parent-3.pom
                  > Content is not allowed in prolog.

**Comment by ronshapiro** [comment]
This has nothing to do with dagger. It looks like an issue with your build tool
