### ISSUE TITLE
Dagger 2 doesn't work in conjunction with AutoFactory

### ISSUE THREAD

**Issue by cypressious** [google/dagger#112]
When adding both libraries the compilation doesn't work anymore. I've also opened an [issue](https://github.com/google/auto/issues/173) on the AutoFacotry tracker but the problem seems to be more than the Dagger 1 dependency.

**Comment by cgruber** [comment]
This is a problem with autofactory, not dagger.  We're aware of it, and autofactory needs some love - which I'll probably give it shortly.  But I'll close this here, as it's more appropriate there.
