### ISSUE TITLE
Autoconverting Scoped to Unscoped Provider for a single usage

### ISSUE THREAD

**Issue by bangarharshit** [google/dagger#1125]
For the example below, we use cache only in the OkHttpClient provider. The generated code still creates providers for both Cache and OkHttpClient. 

If a provider is only used once  - either in another provider/injection, it will be great if dagger can inline that. The generated code will reduce drastically and it will be less error-prone as developers don't have to think about scopes and constantly updating them.

```java
    @Provides
    @Singleton
    Cache provideOkhttpCache(Application application) {
        return new Cache(application.getCacheDir(), CACHE_SIZE);
    }

    @Provides
    @Singleton
    OkHttpClient provideOkHttpClient(HttpLoggingInterceptor loggingInterceptor, Cache cache,
                                     Interceptor cacheOverrideInterceptor) {
        OkHttpClient.Builder builder = new OkHttpClient.Builder()
                .cache(cache)
                .addInterceptor(loggingInterceptor)
                .connectTimeout(60, TimeUnit.SECONDS)
                .readTimeout(60, TimeUnit.SECONDS)
                .writeTimeout(60, TimeUnit.SECONDS)
                .addNetworkInterceptor(cacheOverrideInterceptor);
        return builder
                .build();

    }
```

I can rewrite the code above by making cache unscoped or inlining it in `provideOkHttpClient` but that is not future safe.

**Comment by naturalwarren** [comment]
If you scope an `@Provides` Dagger has to use a Provider since creating the instance requires double checked locking guarantee thread safe initialization.

OkHttp Sidebar: If you're really concerned about excess object creation, I'd probably just inline the cache. Very unlikely that's ever going to be reused across other bindings.

**Comment by bangarharshit** [comment]
`If you scope an @Provides Dagger has to create a Provider since creating the instance requires double-checked locking in order to guarantee thread safe initialization.`
Single provide will always be thread-safe, right? Double check provider just prevents multiple instances but this will not be an issue in this case right as it is just provided once. For that matter, I think unscoped providers are always thread-safe (let me know if I am missing something). 

The intent is that dagger can decide if scoping is redundant and inline/unscope it.

`OkHttp Sidebar: If you're really concerned about excess object creation, I'd probably just inline the cache. Very unlikely that's ever going to be reused across other bindings.` Good point. My example is not good but if we want to ever reuse cache across multiple instances of OkHttp we have to take it out in a scoped provider. Chances are a user may forget to extract out the same instance and unknowingly create multiple instances of cache.

**Comment by ronshapiro** [comment]
This appears to be a question - please use StackOverflow with the `dagger-2` tag instead, as that is a better forum for questions.

It seems like you probably want to have a `private` qualifier on the binding, and then to that in two places: one to the binding that needs the unscoped instance, and another as a `@Binds @YourScope Type to(@PrivateQualifier Type t)` method.

**Comment by bangarharshit** [comment]
Not exactly. 

We use scoped bindings in most of the places since we want a single instance of an object in a scope. A lot of times the binding is injected only once (in future it can be injected multiple times). Currently, it is up to developers to start off with unscoped injection when it is injected only once and moved to scoped injection with multiple places of injection.

The issue was about if this can be offloaded to dagger and developers can use scoped injection everytime (it is still possible now but the code generated is much bigger). It can result in much lesser code generated. I can try to write a full example if it is still not clear.
