### ISSUE TITLE
Annotation processor breaks on Subcomponent with non-annotated module class

### ISSUE THREAD

**Issue by pak3nuh** [google/dagger#1127]
I know this is not a valid configuration, but the annotation processor broke with a NoSuchElementException in the middle of my build process, and it does not give any clues as to what was doing when it happened.

I have a project with multiple components and scopes, so I can't assure that the problem happens in smaller graphs.

My configuration had something like this:
`@Subcomponent(modules = SomeModule.class)
public interface SomeComponent {
...
}`
And the non-annotated module
`
public final class SomeModule {
...
}
`

I'm using Dagger 2.15

**Comment by ronshapiro** [comment]
Are you able to create a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) that exhibits this behavior?

**Comment by pak3nuh** [comment]
Hi, @ronshapiro sorry for the delay, the mail notification was in my spam folder.
I tried to reproduce the issue with a minimal example, but the compilation failed with a valid error message, not with an exception.
I will try to pinpoint the necessary conditions to reproduce the issue.

**Comment by ronshapiro** [comment]
If you see this again and can create an MCV, please comment and we can reopen :)
