### ISSUE TITLE
Dagger 2.15 documentation  with sample code

### ISSUE THREAD

**Issue by jpcodeforit** [google/dagger#1131]
Feature Request
Thanks for the library.
I have seen many threads in internet every tutorial using dagger in different way,i mean implementation will be different.I think if Google itself provide a good documentation with sample project then it would be great.Since i have seen many php frameworks(Laravel,Codeigneter ,symfony etc) which has good documentation so developer will not have much confusion in the subject .
Even current document i find it very difficult ot understand the concept

**Comment by pedrovarela86** [comment]
I have been struggling with this for a week. Today I found this [post](http://www.albertgao.xyz/2018/04/18/dependency-injection-on-android-with-dagger-android-and-kotlin/) from Albert-Gao who made a good job writing it. But still, the basic example works. No when you have job servies, inten services, services, activities, fragments and broadcast receivers, firebase and everything that android has, that's the problem.

**Comment by anticafe** [comment]
I'm agree with @codeforfungit that there are many different way to implement Dagger. For example Google seems have a good sample named [android-architecture>todo-mvp-dagger](https://github.com/googlesamples/android-architecture/tree/todo-mvp-dagger). And [vestrel00](https://github.com/vestrel00) also have an [excellent sample](https://github.com/vestrel00/android-dagger-butterknife-mvp) with detailed comment too (however his [AppComponent](https://github.com/vestrel00/android-dagger-butterknife-mvp/blob/master/app/src/main/java/com/vestrel00/daggerbutterknifemvp/AppComponent.java) implementation has a little bit different from the one from Google sample)

**Comment by ronshapiro** [comment]
There are many other issues open for documentation that are more specific than this one. Closing this in favor of them.
