### ISSUE TITLE
Warning - Configuration 'compile' is obsolete

### ISSUE THREAD

**Issue by aldovincenti** [google/dagger#1141]
Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html

**Comment by tbroyer** [comment]
See #1130

**Comment by jhasanjiv5** [comment]
"Compile" Scope for the dependencies are being taken away from Android development, so instead use "Implementation" as a scope for all the dependencies. You can change it by right click on the folder (e.g. App) then "module setting>dependencies>scope" and then sync the project.

**Comment by LordSuricato** [comment]
I have the same warning. In ""module setting>dependencies>scope"" I do not have any "compile" I only have "implementations".
How can it be fixed?

**Comment by aldovincenti** [comment]
@LordSuricato In your app projects build.gradle file, add `implementation 'com.google.dagger:dagger:2.x'` instead of `compile 'com.google.dagger:dagger:2.x'`.

**Comment by jhasanjiv5** [comment]
If the warning still persists, try to rebuilt the solution after deleting the build folder.

**Comment by LordSuricato** [comment]
As I said I do not have any "compile" I've even searched the entire project (ctrl + shift + f) and there are no occurrences. I only use "implements". It seems that it is not a problem of Dagger. It will be from some other dependency. I have also built the project from 0 several times. Sorry for the inconvenience.

**Comment by AghaAsadKhan** [comment]
The solution is to upgrade classpath com.google.gms:google-services to classpath 'com.google.gms:google-services:3.2.0' in file in build.gradle Project:

buildscript {
    repositories {
        jcenter()
        google()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.1.0'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
        classpath 'com.google.gms:google-services:3.2.0'
    }
}

allprojects {
    repositories {
        jcenter()
        google()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

**Comment by KevinMarous** [comment]
@AghaAsadKhan  Boss it's working !

**Comment by lAminl** [comment]
@aldovincenti thanks a lot :+1:

**Comment by ashnou** [comment]
thanks AghaAsadKhan it works fine

**Comment by zebbit** [comment]
thanks that works!

**Comment by subratasd** [comment]
classpath 'com.google.gms:google-services:3.2.1'    

it's working !

**Comment by wilfredonoyola** [comment]
I have had this problem

`BUILD FAILED in 1s
(node:4020) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: /Users/wilfredonoyola/workspace/statusfy/sf-ionic-1/platforms/android/gradlew: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/wilfredonoyola/workspace/statusfy/sf-ionic-1/platforms/android/CordovaLib/build.gradle' line: 40

* What went wrong:
A problem occurred evaluating project ':CordovaLib'.
> Failed to apply plugin [id 'com.android.library']
   > Minimum supported Gradle version is 4.4. Current version is 4.1. If using the gradle wrapper, try editing the distributionUrl in /Users/wilfredonoyola/workspace/statusfy/sf-ionic-1/gradle/wrapper/gradle-wrapper.properties to gradle-4.4-all.zip

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
`

Do you know the solution for this?

Thanks.

**Comment by JakeWharton** [comment]
It tells you the problem. You need to update Gradle.

**Comment by renaldysa18** [comment]
is work on me thx @AghaAsadKhan

**Comment by adriandleon** [comment]
That worked perfect @AghaAsadKhan Thanks.

**Comment by HarshaFernando** [comment]
Thanks Bro Its Work 100/100 Thank Great

**Comment by TechyTimo** [comment]
3.2.1 doesnt work for me. Do you mind sharing the ext section. Here is mine
buildscript {
 ext {
        buildToolsVersion = "27.0.3"
        minSdkVersion = 16
        compileSdkVersion = 27
        targetSdkVersion = 26
        supportLibVersion = "27.1.1"
    }

**Comment by NelGarbuzova** [comment]
What if I don't change `compile` to `implimentation` by the end of 2018. Is it will broke my app?

**Comment by JakeWharton** [comment]
No. Nothing will happen unless you also upgrade other tooling.

**Comment by justinepeterson** [comment]
Thank you this was helpfull

**Comment by jiaoheng1** [comment]
我在做 安卓推送消息  用的时阿里云  引入apply plugin: 'com.aliyun.ams.emas-services'
 在编译时 报错 Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
找不到替换comoile  怎么解决呀

**Comment by jiaoheng1** [comment]
在做  安桌推送 引用了阿里云 apply plugin: 'com.aliyun.ams.emas-services'
然后在编译时报错 Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
但是 我找不到compile在哪改   应该是依赖没解决   该怎么办呀

**Comment by interkenny** [comment]
> 在做 安桌推送 引用了阿里云 apply plugin: 'com.aliyun.ams.emas-services'
> 然后在编译时报错 Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
> It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
> 但是 我找不到compile在哪改 应该是依赖没解决 该怎么办呀

请确认SKD里边build.gradle的依赖文件设置有没有用compile,需要改成implementation
`compile 'com.aliyun.ams:alicloud-#$#$@%'`

**Comment by blondie63** [comment]
I've same warning building a Ionic 4 app, on file .../platforms/android/build.gradle i no have 'compile' 

```
dependencies {
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files

        classpath 'com.android.tools.build:gradle:3.4.1'
    }
```

what can i do to fix?:
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
Affected Modules: app

**Comment by eddskt** [comment]
Hi the solution of @AghaAsadKhan , Doenst work for me
Ionic v1
Gradle 4.1
Cordova 9.0

someone can help-me?

**Comment by m3os** [comment]
Its working ! Thanks :) @AghaAsadKhan
