### ISSUE TITLE
getting error while injecting into map for Multibinding with subcomponent.builder

### ISSUE THREAD

**Issue by nikhilsol89** [google/dagger#1142]
I am getting below error

error: java.util.Map<java.lang.Class<? extends android.app.Activity>,javax.inject.Provider<com.example.di.ActivityComponentBuilder>> cannot be provided without an @provides- or @produces-annotated method.

**Comment by charurani15** [comment]
I am getting this error in multi-module architecture application.

My core module has component and subcomponent with builder pattern implemented and MyApplication class has Map field with provider for builders.
My app module has AppMainApplication class extending from MyApplication .

I am getting this error:
Error:(12, 24) error: java.util.Map<java.lang.Class<? extends android.app.Activity>,javax.inject.Provider<multibinding.demo.com.core.di.activity.ActivityComponentBuilder>> cannot be provided without an @provides- or @produces-annotated method.
java.util.Map<java.lang.Class<? extends android.app.Activity>,javax.inject.Provider<multibinding.demo.com.core.di.activity.ActivityComponentBuilder>> is injected at
multibinding.demo.com.core.MyApplication.activityComponentBuilders
multibinding.demo.com.multibindingsubcomponentbuilderdemo.AppMainApplication is injected at
multibinding.demo.com.multibindingsubcomponentbuilderdemo.SecondComponent.inject(application)

**Comment by ronshapiro** [comment]
This appears to be a question - please use StackOverflow with the `dagger-2` tag instead, as that is a better forum for questions.
