### ISSUE TITLE
Kotlin @Binds error with covariant type parameter

### ISSUE THREAD

**Issue by fondesa** [google/dagger#1143]
Given the interface:
```kotlin
interface Example<T>
```

The implementation:
```kotlin
class ExampleImpl: Example<List<String>>
```

The module:
```kotlin
@Module
interface ExampleModule {
    @Binds
    fun provideExample(example: ExampleImpl): Example<List<String>>
}
```

The error `@Binds methods must have only one parameter whose type is assignable to the return type` is thrown at compile-time.

**Important notes**
1. it happens only with `@Binds` and not with `@Provides`
So, this works:
```kotlin
@Module
class ExampleModule {
    @Provides
    fun provideExample(example: ExampleImpl): Example<List<String>> = example
}
```

2. it happens only when `T` is used as a covariant type parameter in the implementation of `Example`.
So, this works:

```kotlin
class ExampleImpl: Example<MutableList<String>>

@Module
interface ExampleModule {
    @Binds
    fun provideExample(example: ExampleImpl): Example<MutableList<String>>
}
```

**Comment by Fondesa** [comment]
I tried with `@JvmSuppressWildcards` but it doesn't help in this case.
It's still needed using the `@Provides` annotation.

Example:

```kotlin
@Module
class ExampleModule {
    @Provides
    fun provideExample(example: ExampleImpl): Example<List<String>> = example
}

class Consumer @Inject constructor(private val example: @JvmSuppressWildcards Example<List<String>>)
```

**Comment by JakeWharton** [comment]
You might also need it on the bind. The bytecode window will show the signature of both places.

**Comment by Fondesa** [comment]
I updated my comment with further information.

**Comment by Fondesa** [comment]
My last try was the right one, simply I forgot the `@Inject` annotation on the constructor of `ExampleImpl`.
The following summary is for people who encounter the same problem.
Thanks for your help, considering that now it works, I close the issue, feel free to re-open it if needed.

### Short summary

**Interface**
```kotlin
interface Example<T>
```

**Implementation**
```kotlin
class ExampleImpl @Inject constructor() : Example<List<@JvmSuppressWildcards String>>
```

**Module**
```kotlin
@Module
interface ExampleModule {
    @Binds
    fun provideExample(example: ExampleImpl): Example<List<String>>
}
```

**Consumer**
```kotlin
class Consumer @Inject constructor(private val example: @JvmSuppressWildcards Example<List<String>>)
```

**Comment by bcorso** [comment]
Closing this since it looks like https://github.com/google/dagger/issues/1143#issuecomment-381776533 has the solution.
