### ISSUE TITLE
Android Instrumented Test Issue

### ISSUE THREAD

**Issue by Yegorisa** [google/dagger#1146]
Hi everyone,

I am having a trouble with running androidTests. When I try to run it  shows me this error 
![screen shot 2018-04-17 at 11 16 40 am](https://user-images.githubusercontent.com/21309131/38839892-defc9f96-4230-11e8-9eea-22f8b31daa86.png)
I have no idea where to look for the source of an error. Could anyone help me with this, thanks!

**Comment by ronshapiro** [comment]
This appears to be a question - please use StackOverflow with the `dagger-2` tag instead, as that is a better forum for questions.
