### ISSUE TITLE
Errors with multiple components

### ISSUE THREAD

**Issue by grignaak** [google/dagger#1147]
I'm seeing errors in the generated code when there are multiple (unrelated) components that both depend on the same classes. What happens is that some of the factories don't get generated.

I'm not seeing compile-time warnings from dagger.

----

What follows is a minimum failing example.

```
public class Main {
    @Inject
    Main(MyDependency dependency) {}

    public static void main(String... args) {
        if (args.length == 0) {
            DaggerFirstComponent.create();
        } else {
            DaggerSecondComponent.create();
        }

        System.out.println("success");
    }
}
```

```
@Singleton
public class MyDependency {
    @Inject
    public MyDependency() {}
}
```

```
@Singleton @Component
public interface FirstComponent {
    Main main();
}
```

```
@Singleton @Component
public interface SecondComponent {
    Main main();
}
```

Both components have compilation errors in their initialize method because `MyDependency_Factory`  and/or the `Main_Factory` are not generated.

```
private void initialize(final Builder builder) {
    this.myDependencyProvider = DoubleCheck.provider(MyDependency_Factory.create()); // failed line
    this.mainProvider = Main_Factory.create(myDependencyProvider); // also fails
  }
```

**Comment by ronshapiro** [comment]
Can you provide an actual repo, with everything in separate files and include a build configuration (i.e. pom.xml, build.gradle, make file, etc) that exhibits this? I can't reproduce.

**Comment by ronshapiro** [comment]
Feel free to comment again if you experience this again and we can reopen.
