### ISSUE TITLE
Error: Can't use DaggerFragment with ViewModelProviders

### ISSUE THREAD

**Issue by devensingh1727** [google/dagger#1152]
DaggerFragment does not inherit support Fragment, so we are not able to use DaggerFragment since ViewModelProviders use support Fragment.

**Comment by JakeWharton** [comment]
This is what the `dagger-android-support` artifact is for. Or you could just eschew inheritance and call `AndroidInjector.inject(this)` yourself.

**Comment by devensingh1727** [comment]
Hey Jake, 
My Bad! I found it just now. I was just searching to delete this issue but saw your comment. By the way thank you.
