### ISSUE TITLE
HasSupportFragmentInjector in multiple activity

### ISSUE THREAD

**Issue by sagarnayak** [google/dagger#1161]
I am injecting fragment from my activity. and for that, I am implementing the HasSupportFragmentInjector in the activity. but if I have two activity which implements HasSupportFragmentInjector then I am unable to build my android project.
is this a problem with dagger map or might be anything else?

**Comment by ronshapiro** [comment]
This appears to be a question - please use StackOverflow with the `dagger-2` tag instead, as that is a better forum for questions.
