### ISSUE TITLE
Update CanReleaseReferences and ReleasableReferenceManager in docs, if you're removing the feature in July 2018

### ISSUE THREAD

**Issue by edwardotis** [google/dagger#1163]
https://google.github.io/dagger/users-guide
Section: Releasable references

Guides users to use features that will be removed in 3 months. 
Please update the docs to reflect this.

https://google.github.io/dagger/api/latest/dagger/releasablereferences/CanReleaseReferences.html
and 
https://google.github.io/dagger/api/latest/dagger/releasablereferences/ReleasableReferenceManager.html

https://github.com/google/dagger/issues/1117

Also, please don't deprecate a feature without providing a recommended alternative.

**Comment by ronshapiro** [comment]
You're right, good catch. I'll take care of this.

**Comment by m4xp1** [comment]
How about we describe an alternative to remote functionality?
