### ISSUE TITLE
Binding interface and implementation without module

### ISSUE THREAD

**Issue by elevenetc** [google/dagger#1164]
There're cases when module provides only one object:
```kotlin
class BroadcastModule {
  @Provides
  open fun provideBroadcastBus(inst: BroadcastBusImpl): BroadcastBus = inst
}
```
And this seems like an overkill: create a module class to bind one implementation with interface for only one object.

Is there any plan to introduce some way to bind interface with implementation? 

For instance annotation to generate such kind of modules:
```kotlin
class BroadcastBusImpl @Inject constructor():BroadcastBus {
  //methods
}
```
```kotlin
@Implementation(BroadcastBusImpl.class)
interface BroadcastBus{
  //methods
}
```
Or even better: if there is only one implementation then use it, so no need to have annotation or module declaration. And this behaviour could be probably used to replace modules which provide multiple objects, but still have one interface and implementation.

ps I don't mean cases when interface is not needed. If it's possible to use implementation then of course there is no problem.

**Comment by riclage** [comment]
I agree this could be improved if we could get rid of the need for a module. But there's already a slightly more convenient alternative you didn't mention with `@Binds`:

```
abstract class BroadcastModule {
  @Binds
  abstract fun provideBroadcastBus(inst: BroadcastBusImpl): BroadcastBus
}
```

**Comment by Malachiasz** [comment]
Any progress on that after 2 years?

**Comment by JavierSegoviaCordoba** [comment]
Usually, the module which has the abstraction interface doesn't implement the module which has the implementation class. IMO the process should be inverted.

**Comment by bcorso** [comment]
I think this has some of the same issues mentioned in https://github.com/google/dagger/issues/2026#issuecomment-670299077 and https://github.com/google/dagger/issues/510#issuecomment-287189465 which makes the given proposal infeasible.

**Comment by JavierSegoviaCordoba** [comment]
@bcorso Square Anvil library added a new annotation, `ContributesTo`, which let autogenerate modules by using the annotation in the class instead of the interface, avoiding the boilerplate of binds modules. Can't it be ported to Dagger? I would like to mention @JakeWharton which replied in another similar issue a few days ago.

**Comment by bcorso** [comment]
It's not feasible in Dagger, but it is definitely possible in Hilt (which is more similar to Anvil). However, we've been hesitant because the APIs for this aren't great. We've had people write annotation processors on top of Hilt for this type of feature (internally) but even to handle only a subset of the use cases it ends up looking like this:

```java
// Equivalent to:  @Binds @FooQualifier Foo<Bar> bind(FooImpl impl);
@ContributesTo(
  to = Foo.class,
  typeParameter = Bar.class,
  qualifier = FooQualifier.class,
  components = ApplicationComponent.class,
)
class FooImpl extends ... {...}
```

It looks like Anvil has intentionally left the API simple -- it only handles cases where the class extends a single type that is the exact type you want to bind to. This might be fine for the majority of use cases though.

FWIW, we're not opposed to someone else writing an annotation processor on top of Hilt to do this. It would be a pretty trivial annotation processor to replicate `@ContributesTo`. For example

```java
@ContributesTo(ApplicationComponent.class)
class FooImpl implements Foo {...}
```

The annotation processor just needs to generate the module:

```java
@Module
@InstallIn(ApplicationComponent.class)
interface FooImpl_ContributesTo {
  @Binds Foo bind(FooImpl impl);
}
```

**Comment by sczerwinski** [comment]
In response to @bcorso's comment:
> FWIW, we're not opposed to someone else writing an annotation processor on top of Hilt to do this. It would be a pretty trivial annotation processor to replicate `@ContributesTo`.

It is indeed quite trivial.

However, the sources generated by one annotation processor are not picked up by another annotation processor.

I tried to generate code that could be used by either Room or by Hilt, but both `room-compiler` and `hilt-android-compiler` fail with errors, as if the generated sources didn't exist at all.

I'm not sure it's possible to do with an external annotation processor. Maybe some dedicated Gradle plugin that adds generated sources to classpath would work (like navigation safe args)?

**Comment by bcorso** [comment]
What was the code you generated?

Hilt should wait for all `@InstallIn` modules before generating its component. We don't do anything special internally, so it should be possible to do with an external annotation processor.

**Comment by sczerwinski** [comment]
The generated module was:
```kotlin
import dagger.Binds
import dagger.Module
import dagger.hilt.InstallIn
import dagger.hilt.components.SingletonComponent

@Module
@InstallIn(SingletonComponent::class)
public interface FooModule {
  @Binds
  public fun bindDiceCollectionsRepository(implementation: FooImpl): Foo
}
```

When I moved it to `src/main/java`, it worked as expected, but the one in in `build/generated/source/kaptKotlin/debug` was completely ignored.

**Comment by bcorso** [comment]
Yeah, you have to generate java source. This is a limitation of kapt, which doesn't support multiple rounds for kotlin generated sources (see [here](https://kotlinlang.org/docs/reference/kapt.html#generating-kotlin-sources)):

>Kapt can generate Kotlin sources. Just write the generated Kotlin source files to the directory specified by 
> processingEnv.options["kapt.kotlin.generated"], and these files will be compiled together with the main sources.
>
> **Note that Kapt does not support multiple rounds for the generated Kotlin files.**

**Comment by sczerwinski** [comment]
Thanks. That explains everything.

Now I need to replace all my Kotlin Poet with Java Poet to make it work 😂

**Comment by JavierSegoviaCordoba** [comment]
@sczerwinski are you going to publish it?

**Comment by sczerwinski** [comment]
@JavierSegoviaCordoba yes, but it will take a few days before it's ready. I can post a link when it's ready.

**Comment by bcorso** [comment]
Closing this since there's no action items on our side, and looks like @sczerwinski  made a nice extension that handles this.

**Comment by ansman** [comment]
FYI I released a library that does this for you using Hilt (Android only unfortunately unless Hilt starts supporting non Android projects): https://auto-dagger.ansman.se/
