### ISSUE TITLE
Independent Modules creating issues

### ISSUE THREAD

**Issue by Anmolk22** [google/dagger#1169]
Hello !!

I've created two independent components
1. Is a retrofit component for network calls
2. Is a SharedPrefrence component for storage purposes

when I am trying to inject this into a fragment. Its creating an issue:

Below is the code from the Application class

`        apiModule = DaggerApiModule.builder()
                    .retrofitInstanceProvider(new RetrofitInstanceProvider(baseUrl))
                    .build();

        storageModule = DaggerStorageModule.builder()
                    .sharedPrefrenceProvider(new SharedPrefrenceProvider(this))
                    .build();`

ApiComponent
`@Singleton
@Component(modules = {RetrofitInstanceProvider.class})
public interface ApiComponent {

    /*Injection in  Testing Fragment*/
    public void inject(TestingFragment fragment);

}`

StorageComponent
`@Singleton
@Component(modules = {SharedPrefrenceProvider.class})
public interface StorageComponent {

    /*Injection in Testing Fragment*/
    public void inject(TestingFragment fragment);
}
`

The problem is when I try to build with the above configuration the dagger modules are not getting generated the Application file

**Comment by ronshapiro** [comment]
This appears to be a question - please use StackOverflow with the `dagger-2` tag instead, as that is a better forum for questions.
