### ISSUE TITLE
use bazel build //... or  bazel test //... have error

### ISSUE THREAD

**Issue by panhs** [google/dagger#1170]
ERROR: /private/var/tmp/_bazel_ /116a499141e095849c962896d4a5df41/external/com_google_protobuf/BUILD:423:1: Traceback (most recent call last):
        File "/private/var/tmp/_bazel_ /116a499141e095849c962896d4a5df41/external/com_google_protobuf/BUILD", line 423
                cc_proto_library(name = "cc_test_protos", srcs = (L...), <4 more arguments>)
        File "/private/var/tmp/_bazel_ /116a499141e095849c962896d4a5df41/external/com_google_protobuf/protobuf.bzl", line 247, in cc_proto_library
                cc_libs += [default_runtime]
trying to mutate a frozen object
ERROR: /private/var/tmp/_bazel_ /116a499141e095849c962896d4a5df41/external/com_google_protobuf/BUILD:716:1: Traceback (most recent call last):
        File "/private/var/tmp/_bazel_ /116a499141e095849c962896d4a5df41/external/com_google_protobuf/BUILD", line 716
                py_proto_library(name = "python_specific_test_pro...", <6 more arguments>)
        File "/private/var/tmp/_bazel_ /116a499141e095849c962896d4a5df41/external/com_google_protobuf/protobuf.bzl", line 373, in py_proto_library
                py_libs += [default_runtime]
trying to mutate a frozen object
ERROR: /private/var/tmp/_bazel_ /116a499141e095849c962896d4a5df41/external/com_google_protobuf/BUILD:353:1: Target '@com_google_protobuf//:android' contains an error and its package is in error and referenced by '@com_google_protobuf//:protoc'
ERROR: /Users/ /AndroidStudioProjects/dagger/javatests/dagger/grpc/functional/server/BUILD:16:1: every rule of type proto_library implicitly depends upon the target '@com_google_protobuf//:protoc', but this target could not be found because of: Target '@com_google_protobuf//:protoc' contains an error and its package is in error
ERROR: Analysis of target '//javatests/dagger/grpc/functional/server:coffee_service_java_proto' failed; build aborted: Loading failed

**Comment by ronshapiro** [comment]
Are you using an old version of bazel, or do you need to `git pull`?

**Comment by ronshapiro** [comment]
I'm closing this issue - I'm pretty sure this is a case of bazel and/or dagger being out of date. If that's not the case, feel free to reopen.

**Comment by mickeyouyou** [comment]
are you saying I should update to newest bazel version ?
