### ISSUE TITLE
easy way to customize so provides its common base parent class

### ISSUE THREAD

**Issue by chucky86boy** [google/dagger#1178]
At the moment, I mainly use activity for a container for fragments. For many times, I don't make a module for activity subcomponent but it is used just as a subcomponent between application class and its subcomponent fragments.

When I use ContributesAndroidInjector, it automatically provides its specific class with @seedinstance but there is no way to customize so it can also @seedinstance its BaseActivity class. I hope Unless androidDagger provides some way for us to do that, we have to make unnecessary module class just to provide its BaseClass or we have to write subcomponent boilerplate code ourselves instead of using ContributesAndroidInjector

**Comment by ronshapiro** [comment]
This appears to be a question - please use StackOverflow with the `dagger-2` tag instead, as that is a better forum for questions.
