### ISSUE TITLE
Program type already present: dagger.shaded.auto.common.AnnotationValues

### ISSUE THREAD

**Issue by gmavenis** [google/dagger#1179]
Program type already present: dagger.shaded.auto.common.AnnotationValues$1$1$1
Message{kind=ERROR, text=Program type already present: dagger.shaded.auto.common.AnnotationValues$1$1$1, sources=[Unknown source file], tool name=Optional.of(D8)}

**Comment by ronshapiro** [comment]
Can you provide a small GitHub repo that exhibits this issue? Unfortunately this error alone isn't enough to diagnose the problem.

**Comment by gmavenis** [comment]
This is my sample https://github.com/gmavenis/jetpack
Pls help to config
Tks so much

**Comment by tbroyer** [comment]
`dagger-compiler` and `dagger-android-processor` dependencies need to be in `annotationProcessor` configuration, not `implementation`.

**Comment by gmavenis** [comment]
Thanks so much

**Comment by MrshaoGx** [comment]
@tbroyer  
Hi, bro;
Here is facing same error:
> Error: Program type already present: com.google.common.annotations.GwtCompatible

Seems like the dependency of gRPC conflict with dagger2's dependency. I was excluded one of 'com.google.guava', it doesn't work. I was excluded guava from gRPC, then compile success but can't find the common class at runtime, when i tried to excluded guava from dagger2, you know, unable to generate the Dagger classes... so ｄｅｓｐｅｒａｔｅ....
