### ISSUE TITLE
Android espresso tests. Mocking in constructor injection

### ISSUE THREAD

**Issue by BulatMukhutdinov** [google/dagger#1180]
Hi!
I have an activity and injected presenter through constructor injection.  Something like this
````
public class RegistrationActivity extends AppCompatActivity {

    @Inject
    RegistrationPresenter registrationPresenter;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        SampleApplication.instance.getApplicationComponent().inject(this);
}


public class RegistrationPresenter {
    @Inject
    public RegistrationPresenter{
    }
}
````
I am trying to mock a presenter and inject it in an activity. But it works only if a presenter is provided in Module. How can I mock and inject my presenter?
Thanks

**Comment by ronshapiro** [comment]
This appears to be a question - please use StackOverflow with the `dagger-2` tag instead, as that is a better forum for questions.
