### ISSUE TITLE
Support Androidx for Dagger Android support

### ISSUE THREAD

**Issue by jaredsburrows** [google/dagger#1188]
Create new dependency called: `dagger-androidx` and use the new AndroidX dependencies: https://developer.android.com/reference/androidx/appcompat/package-summary.

**Comment by tbroyer** [comment]
Duplicate of #1181 ?

**Comment by ronshapiro** [comment]
But does adding a different artifact buy us anything over having people use jetifier?

We have to rethink a few things now that artifacts are splitting up. Will we have a separate artifact for appcompatx and fragmentx? What about workx? Maybe one artifact each with optional dependencies is the way to go.

**Comment by jaredsburrows** [comment]
@ronshapiro So we can easily fix the mapping from support android to androidx via https://developer.android.com/topic/libraries/support-library/androidx-rn?

**Comment by ronshapiro** [comment]
I don't follow. Shouldn't `2.16` fix this?

**Comment by jaredsburrows** [comment]
@ronshapiro I am not sure what 2.16 brings in. The change log does not say anything about androidx.

I am just asking if I should close this ticket because the `jetifier` should be able to handle this?

**Comment by ronshapiro** [comment]
I just updated them - I think I released it a few days before I/O and didn't know if it was public yet or not.

**Comment by jaredsburrows** [comment]
@ronshapiro Thanks. I did not see that in [2.16](https://github.com/google/dagger/releases/tag/dagger-2.16). Closing.

**Comment by blackberry2016** [comment]
After migrating to androidx, the Android Studio can't resolve dagger-android and dagger-android-support clasess, like DaggerAppCompatActivity.

**Comment by hameno** [comment]
Same problem here, cannot resolve DaggerAppCompatActivity etc

**Comment by dgomolka** [comment]
Updating Android Studio and Gradle plugin to 3.2.0-beta-01 fixed the issue. It was probably related to Jetifier, not Dagger itself.

**Comment by personshelldon** [comment]
Can not use `DaggerAppCompatActivity` with `ViewModelProviders.of(FragmentActivity activity)`, Android Studio says that `DaggerAppCompatActivity` is not an instance of `FragmentActivity`

Android Studio: 3.2.0rc3
Gradle: 3.2.0rc3
Dagger: 2.17
AndroidX Arch ViewModel: 2.0.0rc2

**Comment by ebraminio** [comment]
AndroidX now is stable, any thiught on better integration with it?
