### ISSUE TITLE
Feature request: "@ContributesAndroidInjector: No injector factory bound for Class" should be asserted at compile time

### ISSUE THREAD

**Issue by gmazzo** [google/dagger#1190]
One of the biggest downsides of `dagger-android` module is that you lose full-graph validation at compile time, like the regular `dagger-compiler` that runs and yells you about no injection point for a specific class.

Would it possible to add that check? I didn't dive deep into source code, but at first sight seems to be technically possible assert the key set of the `AndroidInjector` factory against all classes that have an `@Inject` annotation.

**Comment by ronshapiro** [comment]
There's no way (to my knowledge) to scan every class file that is being compiled (or was previously compiled).
