### ISSUE TITLE
I use it in the library

### ISSUE THREAD

**Issue by ZhangKuixun** [google/dagger#1195]
I use it in the library error

> Error:Execution failed for task ':framework:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

library->build.gradle:

> dependencies {
> ...
>     // Dagger 2
>     api 'com.google.dagger:dagger:2.11'
>     annotationProcessor 'com.google.dagger:dagger-compiler:2.11'
>     api 'com.google.dagger:dagger-android-support:2.11'
>     annotationProcessor 'com.google.dagger:dagger-android-processor:2.11'
>     api 'com.google.dagger:dagger-android:2.11'
> }

library->Application:
`public abstract class BaseApp extends Application implements HasActivityInjector {
    @Inject
    DispatchingAndroidInjector<Activity> dispatchingAndroidInjector;

    @Override
    public AndroidInjector<Activity> activityInjector() {
        return dispatchingAndroidInjector;
    }

    @Override
    public void onCreate() {
        super.onCreate();
        **DaggerAppComponent**//error
                .builder()
                .application(this)
                .build()
                .inject(this);
    }
}
`

all error:

> /Users/zhangkuixun/myparject/Extraterrestrial/framework/src/main/java/com/zhixun/framework/base/BaseApp.java
> Error:(28, 9) 错误: 找不到符号
> 符号:   变量 DaggerAppComponent
> 位置: 类 BaseApp
> Error:Execution failed for task ':framework:compileDebugJavaWithJavac'.
> > Compilation failed; see the compiler error output for details.

**Comment by rinkeshjain** [comment]
@ZhangKuixun how to use in Library project since it's don't have Application Class
