### ISSUE TITLE
@MapKey example

### ISSUE THREAD

**Issue by Takhion** [google/dagger#120]
Sorry to bother, I know it's coming and everything, but could anyone give any example of how to use `@MapKey`?

**Comment by JakeWharton** [comment]
```java
@MapKey(unwrapValue = true)
@interface TestKey {
  String value();
}
```
```java
@Provides(type = MAP) @TestKey("foo") String provideFooKey() {
  return "foo value";
}

@Provides(type = MAP) @TestKey("bar") String provideBarKey() {
  return "bar value";
}
```
```java
@Inject Map<String, String> map;
```

**Comment by Takhion** [comment]
So `map` will be the "sum" of all provided `@TestKey`s in the graph?

**Comment by Takhion** [comment]
Indeed that's it! And seeing how you used `type = MAP` I [realized](https://github.com/google/dagger/blob/master/core/src/main/java/dagger/Provides.java) there's also `SET` and `SET_VALUES`... Oh my, that's useful! Thanks @JakeWharton

**Comment by gk5885** [comment]
We have these docs written and are awaiting a sync.  This should be coming very soon.  @cgruber can provide more detail.

**Comment by netdpb** [comment]
The documentation is part of the Javadoc for the latest snapshot. See [dagger.MapKey](http://google.github.io/dagger/api/latest/dagger/MapKey.html) and the standard ones in [dagger.mapkeys](http://google.github.io/dagger/api/latest/dagger/mapkeys/package-summary.html).
