### ISSUE TITLE
lateinit issue with dagger

### ISSUE THREAD

**Issue by aliiizzz** [google/dagger#1200]
I am using dagger with kotlin and encountered some strange issue with it.
I am injecting a field inside a fragment with @Inject annotation with lateinit and passing by and doing stuff, then going to app info and change permission settings, loading app and hitting back to activity where the fragment was shown and suddenly app crashes and in the stacktrace you got `kotlin.UninitializedPropertyAccessException: lateinit property presenter has not been initialized`

**Comment by nlhommet** [comment]
Uninstall the app and run the app again, it worked for me
