### ISSUE TITLE
Dagger didn't like the androidx.fragment.app.Fragment

### ISSUE THREAD

**Issue by pedrovarela86** [google/dagger#1203]
Hi, I refactored my code to AndroidX. 

It seems Dagger didn't like the fact that my fragments are "**androidx.fragment.app.Fragment**" and not  "**android.support.v4.app.Fragment**"

I receiver errors like :  

> incompatible types: Class<FirstWizardScreenFragment> cannot be converted to Class<? extends Fragment>

**Comment by JakeWharton** [comment]
Are you using 2.16?

**Comment by pedrovarela86** [comment]
2.15, wasn't sure if there were a 2.16 out there.

**Comment by pedrovarela86** [comment]
not an issue.
