### ISSUE TITLE
Hope to add support for LifecycleService

### ISSUE THREAD

**Issue by blackberry2016** [google/dagger#1208]
https://developer.android.com/reference/android/arch/lifecycle/LifecycleService

**Comment by ronshapiro** [comment]
I'm not seeing how this wouldn't work with `dagger.android`.

**Comment by newmanw** [comment]
It works, I imagine they were referring to a helper class, something like DaggerLifecycleService that users could extend as to not have to call AndroidInection.inject(this);

**Comment by JakeWharton** [comment]
I'm not sure we should be encouraging contributing to Android's inheritence problem. There's not much difference to calling a single function or extending a particular type.

**Comment by newmanw** [comment]
@JakeWharton don't disagree at all, it started with users being spoiled w/ DaggerActivity and DaggerFragment classes.

IMHO I believe this could be resolved if the docs were more clear, "Dagger Android provides a few helper classes to cover the 90% case.  If need something else use AndroidInjection.inject(...)".
