### ISSUE TITLE
Force to apply Issue Template when report issue

### ISSUE THREAD

**Issue by anticafe** [google/dagger#1209]
To avoid missing information when report issue (such as Dagger version, Gradle build script to include Dagger, source code of App.java, AppComponent.java, AppModule.java...), I think we should show [Issue Template](https://help.github.com/articles/about-issue-and-pull-request-templates/) in the beginning of the issue.

**Comment by bcorso** [comment]
Discussed with the team, and we decided to close this.

We haven't seen a big issue with this in the past, and we've just ask for more information when it's needed. Always providing the information would be nice, but its also a potentially higher barrier to filing an issue that we'd rather not introduce.
