### ISSUE TITLE
AndroidSupportInjection and AndroidInjector cause lint errors with Androidx

### ISSUE THREAD

**Issue by wezley98** [google/dagger#1211]
AndroidSupportInjection.inject(f) is causing the following lint errors:

`Cannot access class 'android.support.v4.app.Fragment'. Check your module classpath for missing or conflicting dependencies`

`Type mismatch: inferred type is androidx.fragment.app.Fragment but android.support.v4.app.Fragment! was expected`

Another lint error occurs when using this in a activity:

` override fun supportFragmentInjector(): AndroidInjector<androidx.fragment.app.Fragment> {
        return dispatchingAndroidInjector
    }
`

`Return type of 'supportFragmentInjector' is not a subtype of the return type of the overridden member 'public abstract fun supportFragmentInjector(): AndroidInjector<android.support.v4.app.Fragment!>! defined in dagger.android.support.HasSupportFragmentInjector'`

Android Studio 3.2 Beta 1

implementation 'com.google.dagger:dagger:2.16'
implementation 'com.google.dagger:dagger-android-support:2.16'
kapt 'com.google.dagger:dagger-compiler:2.16'
kapt 'com.google.dagger:dagger-android-processor:2.16'

Example Code:
```
/**
 * Helper class to automatically inject fragments if they implement [Injectable].
 */
object AppInjector {

    fun init(episodeGuideApp: EpisodeGuide) {
        DaggerAppComponent.builder().application(episodeGuideApp).build().inject(episodeGuideApp)
        episodeGuideApp.registerActivityLifecycleCallbacks(object :
            Application.ActivityLifecycleCallbacks {
            override fun onActivityCreated(activity: Activity, savedInstanceState: Bundle?) {
                handleActivity(activity)
            }

            override fun onActivityPaused(activity: Activity?) = Unit
            override fun onActivityResumed(activity: Activity?) = Unit
            override fun onActivityStarted(activity: Activity?) = Unit
            override fun onActivityDestroyed(activity: Activity?) = Unit
            override fun onActivitySaveInstanceState(activity: Activity?, outState: Bundle?) = Unit
            override fun onActivityStopped(activity: Activity?) = Unit
        })
    }

    internal fun handleActivity(activity: Activity) {
        if (activity is HasSupportFragmentInjector) {
            AndroidInjection.inject(activity)
        }
        if (activity is androidx.fragment.app.FragmentActivity) {
            activity.supportFragmentManager.registerFragmentLifecycleCallbacks(object :
                androidx.fragment.app.FragmentManager.FragmentLifecycleCallbacks() {
                override fun onFragmentCreated(
                    fm: androidx.fragment.app.FragmentManager,
                    f: androidx.fragment.app.Fragment,
                    savedInstanceState: Bundle?
                ) {
                    if (f is Injectable) {
                        AndroidSupportInjection.inject(f)
                    }
                }
            }, true)
        }
    }
}
```

**Comment by ronshapiro** [comment]
You're probably better off filing feedback with Lint/AndroidX than here.
