### ISSUE TITLE
Incorrect error message (typo) for Subcomponent.Builder constraints

### ISSUE THREAD

**Issue by NitroNbg** [google/dagger#1212]
Hey, this is quite a low priority as it's not a functional bug, just an incorrectly written error message (possibly a typo) that appears during compile time.

The error I'm referencing is caused if you're creating a custom `Subcomponent` and `Subcomponent.Builder` and do not provide `build()` method or rather the method which returns `@Subcomponent` annotated type.

The error displayed in this case is as follows:

`@Subsubcomponent.Builder methods that have no arguments must return the @Subsubcomponent type or a supertype of the @Subsubcomponent. Inherited method: build()`

Notice that it says `@Subsubcomponent` instead of `@Subcomponent`.

I'm using dagger 2.12 I apologize if this was already solved in more recent versions.

**Comment by ronshapiro** [comment]
ha, that's definitely a good bug. I'll take a look.

**Comment by ronshapiro** [comment]
This was fixed in 5dc66a3a48b9e94d2b48a32435fd8842b2dc0b95
