### ISSUE TITLE
Injecting Constructor in androidTest

### ISSUE THREAD

**Issue by herriojr** [google/dagger#1215]
Dagger Version: 2.16

I have a class included from a library who's constructor is annotated with @Inject.  For example:

```
class MyAuthenticationHandler implements AuthenticationHandler {
    @Inject
    public MyAuthenticationHandler(...) {
        ...
    }
}
```

This library is only being used with my androidTests, so in the consuming app, it is listed as an androidTest dependency.  In my application, it is is not being listed in a module (granted, if I do create a factory method in the module for it, no issues).  When I go to compile the tests, I get the following error:

```
DaggerTestApplicationComponent.java:168: error: incompatible types: Factory<AuthenticatorHandler> cannot be converted to AuthenticatorHandler_Factory
        AuthenticatorHandler_Factory.create(...);
```

It appears as though DaggerTestApplicationComponent is expecting a concrete AuthenticationHandler_Factory, however, the create method of AuthenticationHandler_Factory.create() returns a Factory<AuthenticationHandler>.

This seems to be some type of bug, albeit minor, as you can get around this by just adding a factory method for said class in a module.

Note: This seems to be due to compiling against another library which compiled with an older version of dagger.

**Comment by herriojr** [comment]
Note: I only seem to be an issue with androidTest.

**Comment by ronshapiro** [comment]
Are you able to create a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) that exhibits this behavior?

Otherwise, StackOverflow may be your best bet with an issue like this.

**Comment by herriojr** [comment]
Hi ronshanpiro, it appears to be due to a library project using a different (older) version than the app project. I would be ok closing this out as I just need to upgrade the library's version of dagger first.
