### ISSUE TITLE
AndroidInjection support for androidx Fragment

### ISSUE THREAD

**Issue by IgorB10** [google/dagger#1217]
Hello,

I'd like to add a proposal to add support for injection in fragments from an androidx module.

**Comment by JakeWharton** [comment]
This already works when using dejetifier. I don't see a reason to add support for this prior to AndroidX going stable where you'll also need dejetifier if you're still in the support library world.

**Comment by cyph3rcod3r** [comment]
My code is still not compiling even after enabling jetifier. I am trying to use HasFragmentInjector or HasSupportFragmentInjector how would I move ahead with that

**Comment by rafaz182** [comment]
change to version 2.16

**Comment by jega-ms** [comment]
please refer the android x working sample  https://github.com/jega-ms/android-dagger2-mvp-rx
