### ISSUE TITLE
SetFactory get() ordering inconsistent with javadoc.

### ISSUE THREAD

**Issue by malbanese** [google/dagger#1219]
https://github.com/google/dagger/blob/74d69fcc98fb6343231a536fda783c5eae78f89a/java/dagger/internal/SetFactory.java#L104

I'm seeing inconsistencies in the ordering of sets produces by SetFactory.

Usage Example:

**Parent Component:**
`@Multibinds
abstract fun providesIdSet(): Set<String>`

**All Components:**
`fun idSet(): Set<String>`

**Components:** 
Parent
Child (subcomponent of Parent)
Subchild (subcomponent of Child)

**Provides:**
Parent Component -> String("parent_id") into set
Child Subcomponent -> String("child_id") into set
SubChild Subcomponent -> String("sub_child_id") into set

As expected, calling idSet on each built component will return the correct set, which has been populated by the mentioned provides.

**The output is as follows:**
parent: ["parent_id"]
child: ["child_id", "parent_id"]
subchild: ["sub_child_id", "child_id", "parent_id"]

If the IDs are changed to "a,b,c" they will appear in the expected order as defined by the SetFactory.get() javadocs.

In this particular case, I'm building a chain of IDs which are associated with components and subcomponents, so its helpful for me to be able to keep track of the entire ambiguous chain.

The bug comes from a HashSet being used over a LinkedHashSet in the following method:

https://github.com/google/dagger/blob/74d69fcc98fb6343231a536fda783c5eae78f89a/java/dagger/internal/SetFactory.java#L125

https://github.com/google/dagger/blob/937027c2e7d8f50cdf96d5119d161634d7fc7d65/java/dagger/internal/DaggerCollections.java#L66

**Comment by ronshapiro** [comment]
Hm. That's javadoc on an internal type. You're right that we're not being consistent with what it's saying, but it isn't a guarantee that we make. In particular, there's no contract on the order of elements in a multibinding. 

I'm inclined to remove that comment from `SetFactory`, irrespective of whether we make it a `LinkedHashSet`. And even if we do make it linked, I wouldn't rely on the ordering since we don't guarantee it

**Comment by malbanese** [comment]
@ronshapiro Thanks for the quick reply.

Removing the comment would make sense. When mapping multiple things from within a single component into a set, I can see how set order can become un-guaranteeable. 

However, I do see some benefit to being able to have set order in the context of each subcomponent.

It would however be nice if the set order of component groupings could be guaranteed (which it seems like they already are).

I was in the process of making a merge request to use a LinkedHashSet + an ordering tests for it, however - I'll hold off until some greater decision on ordering can be made.
