### ISSUE TITLE
Dagger Android Module - Activity bound multiple times

### ISSUE THREAD

**Issue by O10** [google/dagger#1232]
I would like to create a single module for binding specific Activity instances to Activity class something like that:
```
@Module(includes = [(RxPermissionsModule::class)])
abstract class ActivityModule {

    @Binds
    abstract fun mainActivity(activity: MainActivity): Activity

    @Binds
    abstract fun streamCreation(activity: StreamCreationActivity): Activity

    @Module
    companion object {
        @JvmStatic
        @ActivityBundle
        @Provides
        fun bundle(activity: Activity): Bundle = activity.intent.extras ?: Bundle.EMPTY
    }
}
```

and then use this module in activity builders module like that:

```
@Module 
abstract class ActivityBuildersModule {

    @ActivityScope
    @ContributesAndroidInjector(modules = [ActivityModule::class, FragmentBuildersModule::class, ActivityViewModelModule::class])
    abstract fun contributeMainActivity(): MainActivity

    @ActivityScope
    @ContributesAndroidInjector(modules = [ActivityModule::class, FragmentBuildersModule::class, ActivityViewModelModule::class])
    abstract fun contributeStreamCreationActivity(): StreamCreationActivity

}
```

Now this is not possible as Dagger yelds:

>  [dagger.android.AndroidInjector.inject(T)] android.app.Activity is bound multiple times:
  public interface MainActivitySubcomponent extends AndroidInjector<MainActivity> {

Easy workaround is to create seperate module for each Activity or Fragment I want to bind to its superclass, however it also seems like an overkill in most cases. Is there any other way?

**Comment by ronshapiro** [comment]
Nope, the workaround you described is what we recommend.
