### ISSUE TITLE
Module instances and state

### ISSUE THREAD

**Issue by sophiataskova** [google/dagger#1241]
At https://google.github.io/dagger/semantics/ the docs say that it is "discouraged for modules to have state; this can lead to unpredictable behavior." Could you go into detail and/or some examples of how that can occur?

**Comment by ronshapiro** [comment]
instance state could lead to the provision of bindings being different depending on the conditions that the binding is requested (how many times it was requested before, what thread the binding is requested on, what bindings were requested before it) which are generally not what people are thinking about when they write a binding method. Generally, if you're writing a binding, your dependencies should be explicit in Dagger's graph - instance state is like an implicit dependency outside of the system.
