### ISSUE TITLE
Error in Android Example

### ISSUE THREAD

**Issue by feinstein** [google/dagger#1242]
I followed the Android guide [here](https://google.github.io/dagger/android), step by step, but I getting an error.

The tutorial doesn't says, but shows the following code on step 4:

```
@Override
  public void onCreate() {
    super.onCreate();
    DaggerYourApplicationComponent.create()
        .inject(this);
  }
```

Android Studio complains about the `inject(this)`:
> error: cannot find symbol method inject(DaggerTest_App)

Disclaimer: I am not using a `@Subcomponent` but following the pro tip instead and using a `@Module` with `@ContributesAndroidInjector`

**Comment by ronshapiro** [comment]
Can you post the rest of your code (in a repo)?

**Comment by feinstein** [comment]
Yes, I am adapting a model test app to work with Dagger, so it will won't be a full working example, just have it in mind if it looks a bit messy for the time being.

**Comment by feinstein** [comment]
@ronshapiro here: https://github.com/feinstein/GithubDemoApp.git

If you find it complicated, just let me know and I create a new project from scratch and try to reproduce it there.

שבוע טוב
:)

**Comment by feinstein** [comment]
I believe the tutorial is missing an instruction to add into the `@Component` something like a `Builder` or an `inject` method to provide the Android `Application` to Dagger, like:

```
public interface AppComponent {
    void inject(MyApp myApp);
}
```

**Comment by ronshapiro** [comment]
Ah, I just reread the docs again - I think it was intentional to keep the `YourApplicationComponent` snippet small. We figured that the `inject(this)` part would be understood as a piece you'd have to add (as it's a common Dagger pattern and is elsewhere in the docs)

**Comment by feinstein** [comment]
I tried to first make a builder to inject the Application, but it didn't work, so I made the inject method and it did the trick.... Why is that? Why the Application has to be injected after the graph has been constructed?

**Comment by ronshapiro** [comment]
How could you inject it without a graph? The graph being built is a dependency on the graph performing an injection.

**Comment by feinstein** [comment]
I still don't understand the inner workings of things, but I think my question is better suited at Stackoverflow so I moved it there:

 https://stackoverflow.com/questions/52087976/why-double-inject-an-android-application-in-dagger

Would you mind take a look at it? Thanks in advance.
