### ISSUE TITLE
Android Tutorial misses explanation for Support Fragment specific class for injection

### ISSUE THREAD

**Issue by feinstein** [google/dagger#1243]
I tried to inject a `Fragment` using `AndroidInjection.inject(this);`, but I get an error:

> error: no suitable method found for inject(RepositoryDetailFragment)
> method AndroidInjection.inject(Activity) is not applicable
> (argument mismatch; RepositoryDetailFragment cannot be converted to Activity)
> method AndroidInjection.inject(Fragment) is not applicable
> (argument mismatch; RepositoryDetailFragment cannot be converted to Fragment)
> method AndroidInjection.inject(Service) is not applicable
> (argument mismatch; RepositoryDetailFragment cannot be converted to Service)
> method AndroidInjection.inject(ContentProvider) is not applicable
> (argument mismatch; RepositoryDetailFragment cannot be converted to ContentProvider)

So I got curious and turned to the `DaggerFragment` in the Dagger Support Package to see how it works. It turns out it uses a Support Library specific class: `AndroidSupportInjection.inject(this);`.

There's no mention of this specific class into the Dagger-Android tutorial, despite several references to the Support Libraries, I think it should be included.

**Comment by ronshapiro** [comment]
We write in the docs:
> For users of the Android support library, parallel types exist in the `dagger.android.support` package. Note that while support `Fragment` users have to bind `AndroidInjector.Factory<? extends android.support.v4.app.Fragment>`, AppCompat users should continue to implement `AndroidInjector.Factory<? extends Activity>` and not `<? extends AppCompatActivity>` (or `FragmentActivity`).

Is that not enough? I suspect that people realize that support fragments != framework fragments and would need something different, and thus look to that.

**Comment by feinstein** [comment]
Well, maybe it's enough for other people, but it wasn't for me. I just thought I would have to include the same classes from another package, and not that I would need a different class name, such as `AndroidSupportInjection`

**Comment by ronshapiro** [comment]
I'd be happy to look at alternate options, but I think the docs here are sufficient.

**Comment by feinstein** [comment]
Well it would be just another line in the docs like "for support Fragments use `AndroidSupportInjection`". No big changes or anything.
