### ISSUE TITLE
Compilation issue

### ISSUE THREAD

**Issue by vega113** [google/dagger#126]
Error:(72, 5) java: cannot find symbol
      symbol:   method assert_()
      location: class dagger.internal.MapProviderFactoryTest

    Failed to execute goal on project dagger: Could not resolve dependencies for project     com.google.dagger:dagger:jar:2.0-SNAPSHOT: Could not find artifact com.google.truth:truth:jar:1.0-SNAPSHOT -

**Comment by tbroyer** [comment]
It's there: https://oss.sonatype.org/content/repositories/snapshots/com/google/truth/truth/1.0-SNAPSHOT/
and the repository is declared in the parent POM (`oss-parent`): http://search.maven.org/#artifactdetails%7Corg.sonatype.oss%7Coss-parent%7C7%7Cpom

**Comment by cgruber** [comment]
make sure you update all of your dependencies.  on the command-line, mvn -U will do it.
