### ISSUE TITLE
Is DispatchingAndroidInjector_Factory part of public API? We would like to use it for project with multiple android modules.

### ISSUE THREAD

**Issue by abdullah-chhatra** [google/dagger#1261]
To give some background, we are having a multi module android project and would like to use dagger android for activity and fragment injection. 

The android modules do contain activities and fragments that needs to be injected. The android modules may depend upon another modules. Each android module has its own dependency graph and this graph has dependency to another modules dependency graph. We are able to setup the whole graph quite well. 

But as it turns out we can not use dagger android as `AndroidInjection` requires the application class implements `HasActivityInjector` and provides `DispatchingAndroidInjector` that is generated by dagger 2. As individual android modules have their own dagger graph the `DispatchingAndroidInjector` can not have factories for activities in modules. 

To solve this we intend to just expose the injector factories from android modules to top application and build `DispatchingAndroidInjector` using `DispatchingAndroidInjector_Factory` where we combine all the injector factories from android modules.

So now the question: Is `DispatchingAndroidInjector_Factory` part of public API such that we can count on that and use it without worrying that it may suddenly disappear in some new dagger release?

**Comment by ronshapiro** [comment]
You should not expect it to remain in the API.

It's a necessary generated artifact, but Dagger changes the API of the generated factories frequently and only relies on the factory being consistent with the dagger-compiler at the same version. 

We may also decide to remove them.
