### ISSUE TITLE
Error when trying to inject a Dependency in a class that extends Volley.Request

### ISSUE THREAD

**Issue by myion8you** [google/dagger#127]
Hello I have a class that extends com.android.volley.Request and when I try to inject a dependency into that class i get the following cryptic error

    Error:com.android.volley.Request has type parameters, cannot members inject the raw type.

**Comment by sameb** [comment]
volley.Request has type parameters.  Does your subclass specify the type parameters on it?  If not, that is the problem.

**Comment by myion8you** [comment]
Im not sure I understand.  Yes, it has parameters and they all have types.

**Comment by sameb** [comment]
What is the signature of your subclass, e.g `MyRequest extends Request<Foo>` or `MyRequest<T> extends Request<T>`? 

 How are you injecting `MyRequest` or `Request` -- as `MyRequest<Foo>` / `Request<Foo>`, or just as `MyRequest` or `Request`?  If the latter, that would be the problem -- you cannot inject a raw type if the type has generics, you must inject the type with the generics.

  Is there any more output with the compile error?

**Comment by myion8you** [comment]
Ah!! Thank you very much! I didn't realize that Request was a typed class.  That fixed it

**Comment by sameb** [comment]
FYI, that is what type parameters are, and what the error message is saying.

**Comment by myion8you** [comment]
Thank you again
