### ISSUE TITLE
Providing Application Instance by Default

### ISSUE THREAD

**Issue by ninad458** [google/dagger#1270]
This is a feature request.
```
@Component(modules = [
    AndroidInjectionModule::class,
    ActivityBindingModule::class])
interface AppComponent : AndroidInjector<App>
```
```
class App : DaggerApplication() {
    override fun applicationInjector(): AndroidInjector<out App> {
        return DaggerAppComponent.builder().build()
    }
}
```
Is it possible to get the App instance by default without writing the following part:

```
@Component.Builder
    abstract class Builder {
        @BindsInstance
        internal abstract fun application(application: App): Builder

        internal abstract fun build(): AppComponent
    }
```
```
class App : DaggerApplication() {
    override fun applicationInjector(): AndroidInjector<out App> {
        return DaggerAppComponent.builder().application(this).build()
    }
}
```
Mostly because, almost every app requires application context to instantiate a lot of objects which has singleton status. 

Maybe by returning the builder to DaggerApplication

**Comment by JakeWharton** [comment]
> Is it possible to get the App instance by default

No, it's not possible.

I'm not sure this warrants special casing since you do it once and move on. But beyond that, I'm not even sure how you would do this as the instance needs to be provided to the graph somehow. The other mechanisms (aside from `@BindsInstance`) aren't going to be any less code.
