### ISSUE TITLE
apollo library - issue when use generated class from apollo

### ISSUE THREAD

**Issue by marko995** [google/dagger#1274]
Hello, i found issue. I am working on app with apollo library, and when i rebuild project, got some error:
```
> Task :app:kaptGenerateStubsDebugKotlin
/.../ui/itemdetails/ItemDetailsFragment.java:6: error: dagger.internal.codegen.ComponentProcessor was unable to process this class because not all of its dependencies could be resolved. Check for compilation errors or a circular dependency with generated code.
public final class ItemDetailsFragment extends dagger.android.support.DaggerFragment {
             ^
e: /.../ui/items/ItemsFragment.java:6: error: dagger.internal.codegen.ComponentProcessor was unable to process this class because not all of its dependencies could be resolved. Check for compilation errors or a circular dependency with generated code.
public final class ItemsFragment extends dagger.android.support.DaggerFragment {
             ^
> Task :app:kaptDebugKotlin FAILED
```

in this class, i use generated class from apollo, like GetItemQuery or SetOrderMuatation

pls fix this.

**Comment by ronshapiro** [comment]
This appears to be a question - please use StackOverflow with the `dagger-2` tag instead, as that is a better forum for questions.

**Comment by ImFikus** [comment]
Hello,
I also have the same problem.
It seems that dagger cannot generate code when dealing with classes generated by Apollo.
Since I haven't found any examples of this, I wonder if Dagger allows this to be done.
@marko995 Did you found a way to fix this issue ?
