### ISSUE TITLE
Remove usage of @androidsdk// for support library

### ISSUE THREAD

**Issue by JakeWharton** [google/dagger#1276]
These should be pulled from maven.google.com instead. The maven repo embedded inside the SDK is deprecated.

**Comment by ronshapiro** [comment]
The web of dependencies hindered me taking this on in the past.  But I agree this is useful in practice.

Part of me feels like we should only ever be compiling against these libraries but everyone should be bringing their own copy. In that case, we may be able to hack together something to not need to incorporate every transitive dependency.

**Comment by JakeWharton** [comment]
The mechanism for doing this in Bazel has changed recently to (reportedly) make it easier to handle: https://blog.bazel.build/2019/03/31/rules-jvm-external-maven.html

**Comment by Chang-Eric** [comment]
Closing this as I'm fairly sure this was fixed at some point and we get the support library from maven now.
