### ISSUE TITLE
Codegraft -- Dagger2 Android Dependency Injection Helper

### ISSUE THREAD

**Issue by laynepenney** [google/dagger#1291]
This is not an issue, but wanted to share a library I created for orchestrating Dagger2 on Android.

[Codegraft](http://evove.tech/codegraft/)

I'm not sure how much time I can contribute going forward, so I wanted to share so that maybe it can be forked and of use to others.

## Android Components & View Models

Usually wiring up android components takes a lot of boilerplate. With Codegraft, you can skip the mundane and focus on the code that really matters.

```kotlin
// View Model
@BindViewModel
class MediumViewModel
@Inject constructor(
    val client: MediumClient
) : ViewModel() {
    // TODO: Implement the ViewModel
}

// Fragment with a view model
@AndroidInject
class MediumFragment : Fragment() {
    @Inject lateinit
    var viewModels: ViewModelInstanceProvider

    private
    val viewModel: MediumViewModel by ::viewModels.delegate()

    override
    fun onCreateView(
        inflater: LayoutInflater,
        container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View {
        return inflater.inflate(R.layout.medium_fragment, container, false)
    }

    override
    fun onActivityCreated(savedInstanceState: Bundle?) {
        super.onActivityCreated(savedInstanceState)
        viewModel.apply {
            Log.d("MediumFragment", "medium view model = $this, medium client = $client}")
        }
        // TODO: Use the ViewModel
    }

    companion object {
        fun newInstance() = MediumFragment()
    }
}
```

**Comment by laynepenney** [comment]
Hey @ronshapiro, did you end up using my project, `Codegraft`, as inspiration for `Dagger Hilt`? If so, a little recognition would go a long way for my career! Thank you, sir.

**Comment by Chang-Eric** [comment]
Hey @laynepenney 

Thanks for sharing your project, though we actually didn't use it as inspiration for Hilt, sorry about that. Hilt actually comes from an internal project I started a few years earlier before this issue was submitted. It was actually a completely separate project from Dagger for a while that had enough success internally that we wanted to push it into Dagger to opensource it. Hope that clarifies things, thanks!

**Comment by laynepenney** [comment]
Thanks @Chang-Eric. I appreciate the response!
