### ISSUE TITLE
Bazel project : error loading package. Extension file not found

### ISSUE THREAD

**Issue by Kadanza** [google/dagger#1293]
I want run dagger in bazel project for android. I set up dagger https://github.com/google/dagger#installation and got error.

Error:(7, 1) error loading package '@com_google_dagger//': Extension file not found. Unable to load package for '@google_bazel_common//tools/jarjar:jarjar.bzl': The repository could not be resolved and referenced by '//app:AndroidBazelExample'

**with 
http_archive(
    name = "com_google_dagger",
    urls = ["https://github.com/google/dagger/archive/dagger-2.17.zip"],
    strip_prefix = "dagger-dagger-2.17",
)**

Error:(7, 1) no such package '@com_google_dagger//': BUILD file not found on package path and referenced by '//app:AndroidBazelExample'.

**with 
http_archive(
    name = "com_google_dagger",
    urls = ["https://github.com/google/dagger/archive/dagger-2.17.zip"]
)**

![2018-09-27 9 52 55](https://user-images.githubusercontent.com/35968229/46128503-58e48e00-c23c-11e8-86a5-f81f5acd17af.png)

**with 
http_archive(
    name = "com_google_dagger",
    urls = ["https://github.com/google/dagger/archive/dagger-2.16.zip"]
)**

My **Workspace** 

```
# Android SDK - Replace path with your SDK location
android_sdk_repository(
    name = "androidsdk",
    path = "/Users/nicecode/Library/Android/sdk",
    api_level = 28,
    build_tools_version="28.0.2"
)

# Google Maven Repository
GMAVEN_TAG = "20180723-2"
http_archive(
    name = "gmaven_rules",
    strip_prefix = "gmaven_rules-%s" % GMAVEN_TAG,
    url = "https://github.com/bazelbuild/gmaven_rules/archive/%s.tar.gz" % GMAVEN_TAG,
)
load("@gmaven_rules//:gmaven.bzl", "gmaven_rules")
gmaven_rules()

# Kotlin 
kotlin_release_version = "1.2.60"
rules_kotlin_version = "d83e2689b04941d097be7d3b85fd227434e036ea"

http_archive(
    name = "io_bazel_rules_kotlin",
    urls = ["https://github.com/bazelbuild/rules_kotlin/archive/%s.zip" % rules_kotlin_version],
    type = "zip",
    strip_prefix = "rules_kotlin-%s" % rules_kotlin_version
)

load("@io_bazel_rules_kotlin//kotlin:kotlin.bzl", "kotlin_repositories", "kt_register_toolchains")
kotlin_repositories(kotlin_release_version=kotlin_release_version)
kt_register_toolchains()


 
maven_jar(
    name = "com_squareup_retrofit2_retrofit",
    artifact = "com.squareup.retrofit2:retrofit:2.4.0",
)


load("@bazel_tools//tools/build_defs/repo:android.bzl", "aar_maven_import_external")



aar_maven_import_external(
    name = "com_android_volley_volley",
    aar_sha256 = "f2ed1f4dcf40de5489218964b43d9ce87e5c6d00dba6dbce081b8eb2768c24d2",
    artifact = "com.android.volley:volley:1.1.1",
    licenses = ["notice"],
    server_urls = ["http://repo.spring.io/libs-release/"],
)
http_archive(
    name = "com_google_dagger",
    urls = ["https://github.com/google/dagger/archive/dagger-2.17.zip"],
    strip_prefix = "dagger-dagger-2.17",
)

```

My **BUILD** 
```
load("@gmaven_rules//:defs.bzl", "gmaven_artifact")
load("@io_bazel_rules_kotlin//kotlin:kotlin.bzl", "kt_android_library")

PACKAGE = "uk.co.mcneice.bazeltest"
MANIFEST = "src/main/BazelAndroidManifest.xml"

android_binary(
    name = "AndroidBazelExample",
    custom_package = PACKAGE,
    manifest = MANIFEST,
    multidex = "native",
    dex_shards = 10,
    deps = [
        "@com_google_dagger//:dagger_with_compiler",
        "src"
    ]
)

kt_android_library(

    name = "src",
    custom_package = PACKAGE,
    manifest = MANIFEST,
    srcs = glob(["src/main/java/**"]),
    resource_files = glob(["src/main/res/**"]),
    deps = [


        "@com_android_volley_volley//aar",
        "@com_squareup_retrofit2_retrofit//jar",

        gmaven_artifact("androidx.appcompat:appcompat:aar:1.0.0-beta01"),
        gmaven_artifact("androidx.constraintlayout:constraintlayout:aar:1.1.2"),

        # The following are transitive dependencies of the above
        gmaven_artifact("androidx.annotation:annotation:1.0.0-beta01"),
        gmaven_artifact("androidx.fragment:fragment:aar:1.0.0-beta01"),
        gmaven_artifact("androidx.lifecycle:lifecycle-common:2.0.0-beta01"),
        gmaven_artifact("androidx.lifecycle:lifecycle-viewmodel:aar:2.0.0-beta01"),
        gmaven_artifact("androidx.core:core:aar:1.0.0-beta01"),
        gmaven_artifact("androidx.drawerlayout:drawerlayout:aar:1.0.0-beta01"),

        gmaven_artifact("androidx.core:core-ktx:aar:1.0.0-alpha1")

    ]
)


```

**Comment by tbroyer** [comment]
See https://github.com/google/dagger/issues/1286

**Comment by jgavris** [comment]
@tbroyer I think #1286 is unrelated. It looks like loading of transitive workspace dependencies broke in bazel 0.16 or so.

**Comment by jgavris** [comment]
@ronshapiro could you ping the appropriate bazel folks about this? I've tried bazel 0.17, 0.18rc, 0.19rc and they are all broken loading transitive workspace dependencies.

**Comment by ronshapiro** [comment]
You need all of the dependencies of Dagger also in your workspace. You can check out github.com/google/bazel-common to see if that might help, but you'd be pinning yourself to the versions we support.

**Comment by jgavris** [comment]
Could you update the readme to reflect this? https://github.com/google/dagger#bazel

**Comment by jgavris** [comment]
I started to pull that thread actually, but there are quite a lot of dependencies.

**Comment by ronshapiro** [comment]
That's just how Bazel works, unfortunately. You have to be explicit about all of your transitive dependencies.

You can try something like https://github.com/johnynek/bazel-deps if you're ok with not building Dagger from source.

**Comment by jgavris** [comment]
I would imagine there should be a function like `dagger_repositories` that should do this for you, like [rules_kotlin](https://github.com/bazelbuild/rules_kotlin/blob/master/kotlin/internal/repositories/repositories.bzl#L57)?

**Comment by ronshapiro** [comment]
That's what bazel-common is.

**Comment by jgavris** [comment]
Right...but for convenience of consumers of dagger, they should just have to call `dagger_repositories` and get all of its dependencies into the workspace. I'm just saying the readme now is incomplete, and inconsistent with how other projects integrate into the workspace.

**Comment by ronshapiro** [comment]
That approach breaks down when more projects declare methods like that, even if they're in sync.

I'd be happy to include something in the readme about Bazel common being an _option_, but many projects could have different approaches.

**Comment by jgavris** [comment]
Good point. The 'bazel way' is to build everything from source, and that's probably for internal or advanced users, but it might also be helpful to given an example of using dagger via a bazel `maven_jar` as well.

**Comment by leeschumacher** [comment]
Its been almost more than a year and this still has the bad directions in the README and no example of how to use via maven_jar?

**Comment by bcorso** [comment]
@leeschumacher can you try out the new instructions in the [README](https://github.com/google/dagger#bazel) and let me know if they work for you?

There's one correction to the README that hasn't been synced yet. Loading the Dagger repository should include a `strip_prefix`, like:

```python
# Top-level WORKSPACE file

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

DAGGER_TAG = "2.28.1"
DAGGER_SHA = "f04b1466a00a2845106801e0c5cec96841f49ea4e7d1df88dc8e4bf31523df74"
http_archive(
    name = "dagger",
    strip_prefix = "dagger-dagger-%s" % DAGGER_TAG,
    sha256 = DAGGER_SHA,
    urls = ["https://github.com/google/dagger/archive/dagger-%s.zip" % DAGGER_TAG],
)
```

This change will be updated in the README either today or early next week.

**Comment by leeschumacher** [comment]
The sha needs to
be "9e69ab2f9a47e0f74e71fe49098bea908c528aa02fa0c5995334447b310d0cdd" but
otherwise that seems to work.

**Comment by bcorso** [comment]
Thanks, not sure where I got that sha from but I'll update the readme with the correct one.
