### ISSUE TITLE
No Complete Logs when circular dependency occurred

### ISSUE THREAD

**Issue by devd360** [google/dagger#1300]
I'm in love with Dagger but Sometimes its suck too much. There are no proper logs in android logcat if something goes wrong. In the case of Circular dependency, it never shows me which file is affected.

```
/app/build/tmp/kapt3/stubs/debug/****/****/****/core/di/component/AppComponent.java:9: error: [ComponentProcessor:MiscError] dagger.internal.codegen.ComponentProcessor was unable to process this interface because not all of its dependencies could be resolved. Check for compilation errors or a circular dependency with generated code.
public abstract interface AppComponent {
                ^
```
It never shows which file is affected. I'm injecting so many dependencies in my project. Now it's so much hectic to find where I've done wrong.

**Comment by ronshapiro** [comment]
First of all, please consider writing feedback in a constructive manner. "suck too much" is not a fun statement to read as a project maintainer.

This is a build error, so it won't ever get to logcat. Not sure if that's what you meant though.

It's possible we could print the files caused in the circular dependency, but I'm not sure that's always the root of the problem. Either way, this is an error printed but AutoCommon's BasicAnnotationProcessor, so we'd have to fix it there.
