### ISSUE TITLE
Trailing newline missing in initialize methods

### ISSUE THREAD

**Issue by JakeWharton** [google/dagger#1307]
...when formatting is disabled.

Example:
```
  private void initialize(final Builder builder) {
    this.baseUrlProvider = InstanceFactory.create(builder.baseUrl);
    this.clientProvider = InstanceFactory.create(builder.client);
    this.documentationServiceProvider = DoubleCheck.provider(DacModule_DocumentationServiceFactory.create(baseUrlProvider, clientProvider));}
```
This is because it uses `CodeBlocks.joining` which only adds newlines between but not after.

The easy fix is just to append a newline.

But, we might want to do something nicer (and which probably is re-usable in more places) where we add a `prefix` and `suffix` argument (of type `String`). This call would change to `joining(blocks, "", "\n")` then.

The latter approach starts touching more code than I'm comfortable doing in the cloud IDE so filing it here in case someone else wants to attack it.

**Comment by ronshapiro** [comment]
https://github.com/square/javapoet/blob/ea7a02ee88f8a3aa9afd3a9268390f4f9fee4b59/src/main/java/com/squareup/javapoet/CodeBlock.java#L135

I've been meaning to introduce that.

**Comment by JakeWharton** [comment]
There's missing trailing newlines in a lot of places. Some of these are probably from `joining` usage:
```
  public static MembersInjector<MainActivity> create(
      Provider<SearchPresenter> searchPresenterProvider, Provider<HttpUrl> baseUrlProvider) {
    return new MainActivity_MembersInjector(searchPresenterProvider, baseUrlProvider);}

  @Override
  public void injectMembers(MainActivity instance) {
    injectSearchPresenterProvider(instance, searchPresenterProvider);
    injectBaseUrl(instance, baseUrlProvider.get());}

  public static void injectSearchPresenterProvider(MainActivity instance,
      Provider<SearchPresenter> searchPresenterProvider) {
    instance.searchPresenterProvider = searchPresenterProvider;}

  public static void injectBaseUrl(MainActivity instance, HttpUrl baseUrl) {
    instance.baseUrl = baseUrl;}
```

**Comment by PaulWoitaschek** [comment]
Also: can you just introduce a newline after brackets and semicolons?

```java
    @Override
    public NutrientsScannerComponent build() {
      if (context == null) { throw new IllegalStateException(Context.class.getCanonicalName() + " must be set"); }if (client == null) { throw new IllegalStateException(OkHttpClient.class.getCanonicalName() + " must be set"); }return new DaggerNutrientsScannerComponent(this);
    }
```

**Comment by ronshapiro** [comment]
I filed https://github.com/square/javapoet/issues/722 - if that gets closed we can address this inside of Dagger

**Comment by bcorso** [comment]
This looks fixed now.
