### ISSUE TITLE
Qualifier seems to be ignored during method injection

### ISSUE THREAD

**Issue by cypressious** [google/dagger#131]
I'm using Dagger 2 with a Kotlin project where I'm forced to use method injection for Kotlin classes. The to-be-injected class has a property like this:

```kotlin
var dayMonthFormat: DateFormat? = null
    [Inject ForDayMonth] set
```

which generated byte code looking roughly like what would be generated by this:

```Java
private DateFormat dayMonthFormat;

public final DateFormat getDayMonthFormat() { return this.dayMonthFormat; } 

@Inject
@ForDayMonth
public final void setDayMonthFormat(DateFormat param1) {
	this.dayMonthFormat = param1; 
} 
```

In my module I have a Provides method looking like this:

```Java
@Provides
@ForDayMonth
DateFormat provideDayMonthFormat() {
    return DateUtils.getDayMonthFormat(Locale.getDefault());
}
```

Now, during compilation the following error is generated:

```
error: java.text.DateFormat cannot be provided without an @Provides- or @Produces-annotated method.
        void inject(KotlinClassName kotlinClass);
             ^
      package.KotlinClassName.setDayMonthFormat(java.text.DateFormat arg0)
          [parameter: java.text.DateFormat arg0]
```

To me it looks like the qualifier annotation ```@ForDayMonth``` seems to be ignored, but I'm not sure.

**Comment by cgruber** [comment]
Hmm.  `@ForDayMonth` needs to go on the parameter of the setter, since that is the injection point, not the method itself.  It is probably something we should validate, that you're not putting qualifiers on the method itself, but on its parameters.

**Comment by cypressious** [comment]
Thanks, keep up the good work.

**Comment by cypressious** [comment]
And here is the final, working syntax:

```Kotlin
var dayMonthFormat_: DateFormat? = null
    [Inject] set([ForDayMonth] value) {
        $dayMonthFormat_ = value
    }
val dayMonthFormat: DateFormat get() = dayMonthFormat_!!
```

The second property is for accessing the dependency without the null-safe operator. Verbose doesn't even begin to describe it...

**Comment by JakeWharton** [comment]
Once KT-5720 is (eventually) fixed you'll be able to use normal constructor or field injection.

**Comment by cgruber** [comment]
Yeah - that's gross.  JSR-330 wasn't really designed with Kotlin in mind. :/

It's sad that Kotlin doesn't have a way to abbreviate the property implementation if it's default, letting you just tweak the signature.  Also, I wonder if there's some way to force the null-safety assumption.  I saw when Kotlin reversed the approach of how it handled java code w.r.t. null safety, but I didnt' dig much further.  Not being able to provide assurances about null-safety really adds to the verbosity here.

**Comment by cypressious** [comment]
Even without fixing [KT-5720 ](https://youtrack.jetbrains.com/issue/KT-5720), being able to add annotations to delegated properties (in the way, Christian pointed out) would make our lives significantly easier.
