### ISSUE TITLE
Migrate supportLib to AndroidX

### ISSUE THREAD

**Issue by audkar** [google/dagger#1313]
This is nth issue about this topic. But all previous tickets was closed because at that time AndroidX had no stable release. Now it does.

Some points:
- AndroidX has stable release.
- Android support lib is deprecated. All new features are being developed on AndroidX.
- Jetifier increase build time. In our project `dagger-android-support` is the only reason why we are forced to use Jetifier.

It wouldn't be hard to release one more artifact `dagger-androidx`. Waiting until support lib will completely disappear isn't an option :just_do_it: please :smile:

**Comment by JakeWharton** [comment]
> It wouldn't be hard to release one more artifact `dagger-androidx`.

The wrong thing is rarely hard and the right thing is rarely easy. 👎 to a monolithic androidx artifact.

See https://github.com/google/dagger/pull/1312#issuecomment-432685634

**Comment by ronshapiro** [comment]
If you really want this in the interim, you can fork the files into your own project. We will get to this, and we appreciate the patience!
