### ISSUE TITLE
BindsInstance is optional

### ISSUE THREAD

**Issue by bangarharshit** [google/dagger#1315]
If a method annotated with `BindsInstance` is not invoked, then the injected field is nullable. Why can't it be made required to invoke the method? If the method is not invoked, then it can be removed to any clutter in the first place.

**Comment by ronshapiro** [comment]
I didn't fully understand. Are you saying that today, it's not required to invoke `@BindsInstance` methods? I think that's only the case if a `@Nullable` annotation is used together with `@BindsInstance`.

Or are you proposing a feature?

**Comment by ronshapiro** [comment]
Because the value is null, or because the method was never called?

**Comment by bangarharshit** [comment]
Because the method was never called.

**Comment by ronshapiro** [comment]
That's working as intended. It's required to call all methods on a component builder unless they're for a module that has an accessible no-args constructor.

**Comment by bangarharshit** [comment]
Got it. Wish somehow injections can be marked as nullable or optional.
