### ISSUE TITLE
Module includes not working correctly

### ISSUE THREAD

**Issue by grodin** [google/dagger#132]
I think I've found a bug in the compiler, or if not, then something that needs documenting.

Given two modules

```java
@Module
class AModule {
    @Singleton @Provides SomeClass provideSomeClass() {...}
}

@Module
class BModule {
    @Singleton @Provides OtherClass provideOtherClass() {...}
}
```

then if we try to compose them into a new module

```java
@Module(includes = {AModule.class, BModule.class})
class ComposedModule { 
    @Singleton @Provides YetAnotherClass provideYetAnotherClass() {...}
}
```

and then try to write the component
```java
@Singleton @Component(modules = ComposedModule.class)
interface SomeComponent {
    SomeClass someClass();
    OtherClass otherClass();
}
```

we get a compilation error complaining about not being able to find a `@Provides` annotated method for the types `SomeClass` and `OtherClass`.

If we write the component like this:
```java
@Singleton @Component(modules = {AModule.class, BModule.class})
interface SomeComponent {
    SomeClass someClass();
    OtherClass otherClass();
}
```
everything compiles fine.

I haven't produced a minimal example of this yet, so my actual failing code looks slightly different, but really not very much. I'll try to reproduce it in a minimal example when I have a chance.

The thing I don't understand is that this is exactly how U2020 works, and I was just following that way of doing things as a start.

**Comment by JakeWharton** [comment]
U2020 uses Dagger 1

**Comment by tbroyer** [comment]
See #64

**Comment by grodin** [comment]
Sorry, should have specified I meant JakeWharton/u2020#42 as the version I'm looking at. In fact https://github.com/JakeWharton/u2020/pull/42#issuecomment-67068974 explains exactly the behiour I'm expecting and not seeing.

I'm fairly certain something else is interacting with this and causing the error, but I can't pin it down yet.

**Comment by cgruber** [comment]
I'm confused - I just cut-and-pasted all of the classes in this bug into an eclipse project running the current 2.0-SNAPSHOT, and reproduced it.  It's very subtle though. 

This fails:

```java
@Singleton @Component(modules = ComposedModule.class)
interface SomeComponent {
    SomeClass someClass();
    OtherClass otherClass();
}
```

But this works

```java
@Singleton @Component(modules = ComposedModule.class)
interface SomeComponent {
    SomeClass someClass();
    OtherClass otherClass();
    YetAnotherClass yetAnotherClass();
}
```

Digging further.

**Comment by cgruber** [comment]
Hmm.  No - after updating a fresh client with the latest snapshot, I cannot replicate this.  This class worked fine:

```java
@Singleton @Component(modules = ComposedModule.class)
interface SomeComponent {
    SomeClass someClass();
    OtherClass otherClass();
}
```

Can you please try again after a clean build, having updated all the deps to the latest snapshots?

**Comment by cgruber** [comment]
I'm going to provisionally close this as un-reproduceable, but feel free to re-open and update the bug if you find you are still having this issue with the latest snapshot and clean build, etc.

**Comment by grodin** [comment]
Just to follow up with this, upgrading to the 2.0 release has completely fixed it, so it was probably just the particular SNAPSHOT I was using.
