### ISSUE TITLE
Runtime dependency from a base class

### ISSUE THREAD

**Issue by Ethan1983** [google/dagger#1333]
I'm using Dagger Android 2.19 and my structure is an abstract base fragment and multiple concrete fragment implementations. Concrete fragments are used in a ViewPager implementation. Both abstract and concrete class have dependencies. I used corresponding modules for injecting dependencies.

@Module
abstract class AbsListFragmentModule {
    @Module
    companion object {
        @Provides
        @JvmStatic
        fun providesRuntimeDepdendency( fragment : AbsListFragment ) : SomeTypeUsingRuntimeDepedency = fragment.getRuntimeDepedency()
    }
}

This is the module corresponding to the abstract base fragment. Dagger is not able to figure out AbsListFragment and fails at compilation. Is there a way refer to the seed instance here? If not, is there any workaround?

**Comment by ronshapiro** [comment]
This appears to be a question - please use StackOverflow with the `dagger-2` tag instead, as that is a better forum for questions.
