### ISSUE TITLE
Contribute activity injector not to app module

### ISSUE THREAD

**Issue by radikpsb** [google/dagger#1336]
Hey.
I have two activities A and B. B called from A and scope of B should be inside of scope of Activity A. The problem is that I can't contribute Activity B in Actvity A's module instead of contribute it in app's module.
I can provide sample code if needed.

**Comment by ronshapiro** [comment]
This appears to be a question - please use StackOverflow with the `dagger-2` tag instead, as that is a better forum for questions.
