### ISSUE TITLE
compile-time dependency cycle checking only checks first constructor argument.

### ISSUE THREAD

**Issue by drshriveer** [google/dagger#1338]
I found an an issue where dependency cycle checking seems to only check the first argument of a constructor. Take a look at the following example in kotlin: 

```kotlin
class A @Inject constructor(arg1: AnyC, arg2: B) { ... }

class BImpl @Inject constructor(arg1: AnyD, arg2: A, ... argN: AnyClass ): B { ... }
```

`A` has a dependency on `B` and `B` has a dependency of `A`. This is a cycle, but since class `A` has `B` as the second constructor argument no issue is raised during compile time and the build succeeds even though during run time this breaks the application (when it tries to construct these objects).

On the other hand, if `A`s FIRST constructor argument is the dependency on `B` like so:

```kotlin
class A @Inject constructor(arg1: B, arg2: AnyC) { ... }

class BImpl @Inject constructor(arg1: AnyD, arg2: A, ... argN: AnyClass ): B { ... }
```

The build fails, as expected, due to detecting a dependency cycle.

**Comment by ronshapiro** [comment]
Are you able to create a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) that exhibits this behavior?
