### ISSUE TITLE
Prepare 2.0 Release

### ISSUE THREAD

**Issue by cgruber** [google/dagger#134]
Tracking bug for prepping 2.0 release and publishing to sonatype's central repo.

**Comment by dlubarov** [comment]
:+1:! We're looking forward to using dagger 2, but we want to avoid snapshot dependencies or maintaining a fork. Glad to hear that you're planning a release.

**Comment by yunussasmaz** [comment]
+1 to @dlubarov

**Comment by cgruber** [comment]
#151 is the release pull which will close this issue.
