### ISSUE TITLE
Multiple binds using same singleton

### ISSUE THREAD

**Issue by popin-peter** [google/dagger#1343]
I am running into an issue where a class annotated with `@Singleton` is actually being initialized twice, and I'm wondering what I can do to fix this problem.

Say I have two interfaces

```
interface Publisher {
  
  fun publish()

}

interface Listener {

  fun listen() : Observable<Any>

}
```

these interfaces are implemented in a class such as

```
@Singleton class Implementation : Publisher, Listener {

  init {
    log("Initializing")
  }

  override fun publish() { ... }

  override fun listen() { ... }

}
```

and injected in a module like

```
@Module
abstract class MyModule {

  @Binds
  fun bindPublisher(impl: Implementation) : Publisher

  @Binds
  fun bindListener(impl: Implementation): Listener

}

@Singleton
@Component(modules = [MyModule::class])
interface MyComponent {
 
  fun inject(...)

}
```

When I attempt to inject one `Publisher` and one `Listener`, I am seeing two logs for "Initializing" meaning that my `Implementation` class is constructed twice.

I would expect - given that my implementation is annotated as Singleton - that Dagger would construct only a single instance of it even if implementation class providing two different interfaces.

How should I go about restructuring my module to guarantee that only a single instance of my Implementation is constructed?

**Comment by ronshapiro** [comment]
Are you able to create a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) that exhibits this behavior?

**Comment by popin-peter** [comment]
This appears to be an issue specific to my implementation - my apologies. I will close this issue, as it is not a Dagger problem.
