### ISSUE TITLE
Support for Lazy injection without synchronization 

### ISSUE THREAD

**Issue by Ethan1983** [google/dagger#1347]
This is feature request to support Lazy injection without DoubleCheck synchronization overhead. Idea is similar to Kotlin Lazy's LazyThreadSafetyMode.NONE. This helps in cases when injected lazy is used (get()) only in Main thread. This serves as best of both worlds, delayed dependency creation and no DoubleCheck overhead and works well when some parts of my UI (activity) like Feedback is not used often by users.

**Comment by ronshapiro** [comment]
On face value this seems fine and probably easy to implement, but is the double checked locking actually costly? Have you done any benchmarking?

**Comment by Ethan1983** [comment]
Not much in my case. If the use site doesn't need thread safety, why bother with any overhead at all? Also offers more readability for new developers, looking at NonSynchronizedLazy<> or a better name/API to convey this meaning.

**Comment by Dunemaster** [comment]
I would go further and add an option to make any injection not synchronization .
We have components which are guaranteed to work in a single thread.

That will remove runtime overhead and reduce the size of generated code.

**Comment by ronshapiro** [comment]
I want to make sure we're not trying to prematurely optimize anything. If we can get numbers that make a strong case, let's have a discussion. Otherwise, we're just guessing.

**Comment by ashdavies** [comment]
Without a synchronised double check, you can't guarantee that it's the same instance, so you could just use `@Reusable` on the provision with a standard `Provider<T>`
