### ISSUE TITLE
Not able to inject application context to a class

### ISSUE THREAD

**Issue by nickyk2407** [google/dagger#1351]
I am not able to Inject application context in a non activity/fragment class

Below is my code:
@Singleton
@Component(modules = [AndroidSupportInjectionModule::class, ContextModule::class])
interface AppComponent {
    @Component.Builder
    interface Builder {
        @BindsInstance
        fun application(application: PickingApplication): Builder

        fun build(): AppComponent
    }

    fun inject(pickingApplication: PickingApplication)
}

@Module(includes = [AndroidInjectionModule::class])
abstract class ContextModule {

    @Binds
    @Singleton
    abstract fun bindApplication(application: PickingApplication): Context
}

I want to inject applicationContext in many classes. But I am not able to.

**Comment by ronshapiro** [comment]
This appears to be a question - please use StackOverflow with the `dagger-2` tag instead, as that is a better forum for questions.
