### ISSUE TITLE
Custom Naming annotation for generated classes

### ISSUE THREAD

**Issue by GrumpyMcGrumpface** [google/dagger#1360]
Afaik Dagger 2 does not support custom naming for generated classes. Current it's like this: 
`MyComponent` -> `DaggerMyComponent`

It would be very useful for our project to be able to decide on the target name.
Like this for examle:
```
    @Singleton  @Component @GeneratedClassName( "CoolComponent" )
   interface MyComponent {
     // component methods...
   }
```

I know this is a very niche problem, but I need it for my use case.

**Comment by ronshapiro** [comment]
There are plenty of workarounds for this and the demand is far too low. You can always define a wrapper type for your component with the exact interface you need (hey, that's what components are!) if you really do _need_ this.

**Comment by GrumpyMcGrumpface** [comment]
It's not really a cosmetic requirement. We want to be able to generate the same component class from two (or more) different component interfaces. Not at the same time, of course, but from different build targets.

**Comment by ronshapiro** [comment]
I imagine there's probably another way to achieve the same goal even with two different class names/two different main methods/application classes/what have you.
