### ISSUE TITLE
Subcomponent vs  Component dependencies

### ISSUE THREAD

**Issue by Gaket** [google/dagger#1364]
That's rather a question than a bug.

Is there a written reasoning why Subcomponents were created and if we should better use them and not dependent components?

Dagger 2 introduced Subcomponents that facilitate using the parent's dependencies without a manual exposing of required dependencies. However, trying to apply it in a multi-module project we get dependency cycles (because the subcomponent needs to know about its parent) and the generated Component class includes all the generated subcomponents classes becoming a pretty massive thing over time.

Is there any reason why we should still try to stick with Subcomponents or is it totally fine to use Component Dependencies? Is there a chance that the latter will be deprecated in the next Dagger updates?

**Comment by JakeWharton** [comment]
You seem to have answered the first part of the question yourself.

**Comment by Gaket** [comment]
Thank you. Could you please share your opinion on the second part?

**Comment by ronshapiro** [comment]
`@Module.subcomponents` was introduced in part to help break this build cycle. It allows you to inject the subcomponent builder without ever referring to the owning component. `dagger.android` takes heavy advantage of this.

You don't have to be worried about either API going away.
