### ISSUE TITLE
Dagger in multi-module white label app

### ISSUE THREAD

**Issue by rafal-adamek** [google/dagger#1368]
Not reporting any bug, just a question.

The project I'm involved in right now consists of X apps that share common base with each other (around 90% of the whole app is shared).

Our setup is pretty straightforward: all Dagger modules are set up in the common part (let's call it a library) but each app has its own single `Component` that lists all domain modules + one specific module which provides unique implementations for various configurations that differentiate the app from others. Activity specific subcomponents are defined in the library. 

This setup worked pretty well for us in the past until we decided to implement more stuff into our `debug` builds. The obvious way is to have a separate `AppComponent` for debug and release variants, but since we have X apps in the same project it makes it very hard to maintain and we need to re-declare all modules X*2 times.

If we could create a component on the library side and mark it as a dependency for the top-level app module it would be fantastic, but the problem is app-specific and library providers are interdependant.

What I'm asking is basically what kind of setup should we do to have most of the graph setup in one place (library) while providing a minimal (+1 or +2 unique app modules) for the specific app.

Perfect setup would be something like this:

App level:
- 1 release component + 1 debug component (X apps)
- 1 extra module

Library:
- Common component (subcomponent?) that uses all domain modules
- All domain modules
- Android injectors and builders

The problem here is that the common component needs to depend on configurations provided by app-level module.

I'd appreciate any help on that matter. Thank you!

**Comment by ronshapiro** [comment]
This appears to be a question - please use StackOverflow instead, as that is a better forum for questions.
