### ISSUE TITLE
Mark Producers as beta in preparation for 2.0 release

### ISSUE THREAD

**Issue by cgruber** [google/dagger#137]
Mark producers as "beta" in some way, so they can ship as an optional, experimental feature in 2.0.

------

Formerly:
Producers is slated for 2.1, so tease apart the dependency so we can release the 2.0 processor without any requirement of producers.

This might be a useful permanent state of affairs anyway, so people don't have to exclude producers in the long term.

**Comment by gk5885** [comment]
The current working plan is to just call producers "beta" and release dagger 2 with that as an optional feature.

**Comment by cgruber** [comment]
Edited.

**Comment by cgruber** [comment]
Implemented in #145
