### ISSUE TITLE
Fragment injection into AppCompatActivity androidX

### ISSUE THREAD

**Issue by Artur512** [google/dagger#1375]
Please tell me how to inject Fragment from package androidx.fragment.app.Fragment into androidx.appcompat.app.AppCompatActivity. Exists it interface HasFragmentInjector for a fragment from the new package? 2.20 version

**Comment by vaclavkindl** [comment]
**HasSupportFragmentInjector** is probably what you're looking for.

**Comment by PingerOne** [comment]
I have the same problem. dagger android and dagger android support library dont support androidx.appcompat.app.AppCompatActivity and androidx.fragment.app.Fragment. 

**please developers to support androidx.**

**Comment by PingerOne** [comment]
Im sorry. the new version 2.20 have support androidx. just implement 'com.google.dagger:dagger-android-support:2.20'. but 2.20 version have a exception 'java.util.NoSuchElementException', I'm looking for a solution.

**Comment by PingerOne** [comment]
I found a solution to Androidx support.

1. use **'com.google.dagger:dagger-android-support:2.20'** can support androidx.appcompat.app.AppCompatActivity and androidx.fragment.app.Fragment.

2. fix the error 'java.util.NoSuchElementException' link [ dagger kotlin kapt](https://stackoverflow.com/questions/53020234/cannot-find-symbol-class-databindingcomponent-caused-by-java-util-nosuchelemente)

**Comment by PingerOne** [comment]
**I solved the problem.**

This is my dependencies：

implement 'com.google.dagger:dagger:2.16'
implement 'com.google.dagger:dagger-android-support:2.16'
kapt 'com.google.dagger:dagger-compiler:2.16'
kapt 'com.google.dagger:dagger-android-processor:2.16'

![image](https://i.loli.net/2019/01/02/5c2c32ce1f6a4.png)

**Comment by mattdrzazga** [comment]
Version 2.16 is supposed to be working.
According to release notes (2.19) version 2.20 should be working to.
https://github.com/google/dagger/releases/tag/dagger-2.19

**Comment by baudouxbenjamin** [comment]
> Version 2.16 is supposed to be working.
> According to release notes (2.19) version 2.20 should be working to.
> 
> > In the next release (2.20), we will remove the old format. This will allow us to support AndroidX packages better.
> > https://github.com/google/dagger/releases/tag/dagger-2.19

it's supposed to work in 2.19 but it does not
