### ISSUE TITLE
Support to specify component/subcomponent for scope annotated constructed injected dependency

### ISSUE THREAD

**Issue by Ethan1983** [google/dagger#1376]
This is a feature request to specify component/subcomponent for scope annotated constructed injected dependency. Dagger automatically associates constructed injected dependency to a component/subcomponent based on usage of the dependency (injection at use site). This works fine for most cases except when the dependency is annotate with a scope like in the following case,

class DaggerViewModelFactory @Inject constructor(
    private val viewModelMap : Map<Class<out ViewModel>, @JvmSuppressWildcards Provider<ViewModel>> ) : ViewModelProvider.Factory {
}

abstract class AbsDaggerFragment< T : ViewModel > : DaggerFragment() {
    @Inject
    lateinit var viewModelFactory : DaggerViewModelFactory
    ...
}

DaggerViewModelFactory can be a single instance. However, applying @Singleton forces the corresponding subcomponent (FragmentSubcomponentImpl to be singleton). In some cases, this is not even possible as AppComponent could be marked as Singleton.

   Is there any way to tell Dagger to host this constructed injected DaggerViewModelFactory under AppComponent? I'm trying to avoid a module provides method and still hope to use constructor injection.

**Comment by ronshapiro** [comment]
Components can have multiple scopes. You can apply a new custom scope to
your class, and then apply the same scope to the component you wish for the
binding yo be installed.

**Comment by Ethan1983** [comment]
Thanks, that does it.
