### ISSUE TITLE
Feature request: Improve error message for unresolved dependencies.

### ISSUE THREAD

**Issue by jaychang0917** [google/dagger#1381]
Let's say a `ServiceComponent` uses `OkHttpClient` to construct `AwesomeService` and the component only exposes `AwesomeService` so `OkHttpClient` is hidden as an implementation detail. Now a client tries to request a `OkHttpClient`, the following error message is thrown:

```
error: [ComponentProcessor:MiscError] dagger.internal.codegen.ComponentProcessor was unable to process this interface because not all of its dependencies could be resolved. Check for compilation errors or a circular dependency with generated code.
```

Is it possible that the message includes a hint saying that `**OkHttpClient** cannot be resolved since it is the implementation detail of **ServiceComponent**...`? In this way the user can easily spot the issue, otherwise, it is difficult to fix the error.

**Comment by netdpb** [comment]
That error message means that some type referred to somewhere in the component or its modules cannot be found in the classpath. Typically it means that there's a circular dependency among classes generated by different annotation processors.

Do any other errors appear in the log before or after that one?

**Comment by jaychang0917** [comment]
> That error message means that some type referred to somewhere in the component or its modules cannot be found in the classpath. Typically it means that there's a circular dependency among **classes generated by different annotation processors**.
> 
> Do any other errors appear in the log before or after that one?

Oh, that is the problem. I request a class type that uses another annotation processor so the error is thrown, the error message for other type of classes are clear.

**Comment by netdpb** [comment]
This is actually an issue with `BasicAnnotationProcessor` from github.com/google/auto. I'll close this issue here.
