### ISSUE TITLE
How to pass param to ContributesAndroidInjector injected Module

### ISSUE THREAD

**Issue by theapache64** [google/dagger#1392]
I've a builder module like this

```kotlin

@Module
abstract class BuildersModule {
    
    @ContributesAndroidInjector(modules = [MainModule::class])
    abstract fun bindMainActivity(): MainActivity
}

```

and here's my `MainModule`

```java
@Module
class MainModule(val name: String) {

    @Provides
    fun provideGreetings(): String = "Hi, $name"

}
```

but am getting below error

>  BuildersModule_BindMainActivity.java:26: error: @Subcomponent.Builder is missing setters for required modules or subcomponents: [com.tp.orchid.ui.activities.main.MainModule]

Questions , 

1.  How do i pass the `name` variable to `MainModule` constructor ?  
2.  What is the recommended way to pass params to module constructor while using `dagger-android` with `ContributesAndroidInjector` ?

**Comment by tbroyer** [comment]
From https://google.github.io/dagger/android#injecting-activity-objects
> Pro-tip: If your subcomponent and its builder have no other methods or supertypes than the ones mentioned in step # 2, you can use `@ContributesAndroidInjector` to generate them for you.

Corollary: if you need a setter for a required module in your subcomponent builder, you cannot use `@ContributesAndroidInjector`.

BTW, support questions are better asked on StackOverflow, keeping this tracker for reporting bugs and requesting for enhancements.

**Comment by ronshapiro** [comment]
Correct on all accounts. Generally, instance state in modules is a bad idea, and if you can derive the value from the activity (for which we do add a binding) that is best.
