### ISSUE TITLE
How to build dagger in android? 

### ISSUE THREAD

**Issue by 73sravanthi** [google/dagger#1400]
I am trying to build dagger from source code and use a library module in my android application. I am unable to find the steps to be followed to build dagger .Where can I find the source code and the steps to be followed to build? What files should be used in my project to include dagger?

**Comment by tbroyer** [comment]
Have a look at https://github.com/google/dagger/pull/1268

**Comment by 73sravanthi** [comment]
Thanks for the reply

I have run bazel build  and got below response                                                   
INFO: Invocation ID: f8eab97c-5306-49de-bb81-3c5cb9f7f0d5
INFO: Analysed 0 targets (0 packages loaded, 0 targets configured).
INFO: Found 0 targets...
INFO: Elapsed time: 0.257s, Critical Path: 0.02s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action

Where can I find the dagger JARs or AARs to be included after building it?

**Comment by tbroyer** [comment]
That was in the linked PR:

> * You can install the Dagger libraries in your **local maven repository** by running the `./util/install-local-snapshot.sh` script.
>   * It will build the libraries and install them with a `LOCAL-SNAPSHOT` version.

The `install-local-snapshot.sh` will tell you the path to the libs, or you can use in a Gradle build:

```kotlin
repositories {
    mavenLocal();
}
dependencies {
  api("com.google.dagger:dagger:LOCAL-SNAPSHOT")
  annotationProcessor("com.google.dagger:dagger-compiler:LOCAL-SNAPSHOT")
}
```
(and similarly for the Dagger Android libs)

**Comment by adithyaam** [comment]
It seems like , @73sravanthi  is not able to find the generated JARs, There are many JAR's generated after building and which one should be used ?

**Comment by tbroyer** [comment]
Either:
* use `util/install-local-snapshot.sh` and use Dagger as usual, except from the `mavenLocal()` repository and using version `LOCAL-SNAPSHOT`. You can also use a script similar to `util/publish-snapshot-on-commit.sh` to deploy to a repository manager in your organization if you have one.
* or grab the JARs used by those scripts (which you'll actually find in `util/execute-deploy.sh`), i.e. `java/dagger/libcore.jar` (corresponding to `com.google.dagger:dagger`) and `shaded_compiler.jar` (corresponding to `com.gogle.dagger:dagger-compiler`) which you'll find in either `bazel-bin/` or `bazel-genfiles/`.

**Comment by 73sravanthi** [comment]
I have added libcore.jar and  shaded_compiler.jar to libs folder tried  building the app.
It threw compile time error for import javax.inject.Inject 

To resolve it I have added ' implementation 'javax.inject:javax.inject:1@jar'' to the build.gradle (Compile error is resolved now)

Then while running the application its throwing below error
e: java.util.ServiceConfigurationError: javax.annotation.processing.Processor: Provider dagger.internal.codegen.ComponentProcessor could not be instantiated

Tried  adding  shaded_compiler.jar as AnnotationProcessor too.But still it throws the same error

**Comment by tbroyer** [comment]
You may want to try modifying the `util/install-local-snapshot.sh` to target a specific directory (see https://maven.apache.org/plugins/maven-install-plugin/examples/specific-local-repo.html) that you'll then put into your Android project and reference as a Maven repository from Gradle (best of both worlds: files inside the project, and managed/transitive dependencies):
```gradle
repositories {
  maven { url = project.file("local-repo/").toURI() }
}
```

**Comment by 73sravanthi** [comment]
I want to use locally generated files in my  application
