### ISSUE TITLE
dagger annotations can't be imported by AS

### ISSUE THREAD

**Issue by WojciechKo** [google/dagger#141]
Today I've noticed that eg. `@Component` can't be imported automatically by Android Studio.
When I type manualy `import dagger.Component;` it works fine but AS highlights this line in red and warns `Cannot resolve symbol 'Component'`
Same thing with `@Module` and `@Provides`

I'm using Android Studio 1.2
build.gradle:  

    def daggerVersion = '2.0-SNAPSHOT'
    apt "com.google.dagger:dagger-compiler:$daggerVersion"
    compile "com.google.dagger:dagger:$daggerVersion"
    provided 'org.glassfish:javax.annotation:10.0-b28'

**Comment by artem-zinnatullin** [comment]
Try to do "clean caches and restart“ something like this available in `Menu - > File` and then re-sync Gradle

**Comment by WojciechKo** [comment]
Thanks, that helped!
