### ISSUE TITLE
Unable to access Application component methods if added through dependencies in some other component using Kotlin.

### ISSUE THREAD

**Issue by abhisshek** [google/dagger#1412]
I have created an ApplicationComponent where I have declared all the common methods which will be needed from every part of my application. When I try to access those methods using ApplicationComponent, it is getting accessed but when I add ApplicationComponent into some other Component using dependencies in Kotlin it is not getting accessed. I have opened a question regarding that on StackOverflow. Please click on this StackOverflow [link](https://stackoverflow.com/questions/54491063/getting-error-while-trying-to-access-the-method-as-cannot-be-provided-without-a) for more.

**Comment by ronshapiro** [comment]
Please use the StackOverflow question to find your answer. 

If you can reproduce this bug in a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve), you can reopen this to investigate.
