### ISSUE TITLE
Dagger not generating Proguard/R8 rules with option experimentalUseStringKeys

### ISSUE THREAD

**Issue by Thomas-Vos** [google/dagger#1415]
I'm having some issues with `experimentalUseStringKeys` on Android Studio 3.4 (beta 3). When running the app (release build with R8) it throws the following exception:

```
 java.lang.IllegalArgumentException: No injector factory bound for Class<Alb>
```

When adding the following to my Proguard rules manually the exception does not occur anymore: 

```
-identifiernamestring class dagger.android.internal.AndroidInjectionKeys {
  java.lang.String of(java.lang.String);
}
```

So it looks like that for some reason this isn't added automatically by Dagger, which is strange as I verified that a generated APK used R8 version 1.4.29. This should have support for generated proguard rules.

Android Studio version: 3.4 beta 3 (same issue in 3.3 stable)
Dagger version: 2.21

**EDIT:** Fixed Android Studio version

**Comment by ronshapiro** [comment]
Can you verify that the generated proguard rule is appearing the build outputs (it should be a resource in the jar/aar)

**Comment by Thomas-Vos** [comment]
Sorry but I am not sure where I can find that file. I'm not generating an jar/aar but an APK file instead. Could you tell me where I would need to check for the generated rule?

**Comment by Thomas-Vos** [comment]
I found this file in my project:
```
MyProject/app/build/tmp/kapt3/classes/googlePlayRelease/META-INF/proguard/dagger.android.AndroidInjectionKeys
```
With the following contents:
```
-identifiernamestring class dagger.android.internal.AndroidInjectionKeys {
  java.lang.String of(java.lang.String);
}
```
Is this what you mean or do I need to verify it in another way?

**Comment by Thomas-Vos** [comment]
I just downgraded from Android Studio "3.4 beta 3" to "3.3" (stable). The issue is still there in the stable version.

**Comment by ronshapiro** [comment]
Are you able to create a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) that exhibits this behavior? That may help to debug it.

Re verification - somewhere in the `build/` directory, there should be either the file `proguard/dagger.android.AndroidInjectionKeys` or there should be a `.jar` or .`aar` file that once unpacked, shows the `META-INF/proguard/dagger.android.AndroidInjectionKeys` file. If you create the MCVE as above, I can help with that

**Comment by Thomas-Vos** [comment]
Yes sure, see attachment for an example project. I reproduced this issue in Android Studio 3.3 stable.

I added a Fragment class which will get obfuscated by R8. Furthermore, I enabled R8 for both debug and release builds. So just run the app and it will throw an exception.

If you go to the file `app/proguard-rules.pro` and uncomment the rule I added, the app will no longer crash. Hope this helps you find the issue!

[DaggerIssue1415.zip](https://github.com/google/dagger/files/2832097/DaggerIssue1415.zip)

**Comment by ronshapiro** [comment]
I'm seeing these files generated:

```
./app/build/intermediates/javac/release/compileReleaseJavaWithJavac/classes/META-INF/proguard/dagger.android.AndroidInjectionKeys
./app/build/intermediates/javac/debug/compileDebugJavaWithJavac/classes/META-INF/proguard/dagger.android.AndroidInjectionKeys
```

I'm not sure why R8 is not picking them up.

**Comment by JakeWharton** [comment]
Maybe a bug in the toolchain only assuming it needs to carry class files as
outputs?

**Comment by ronshapiro** [comment]
I opened a bug on R8 [here](https://issuetracker.google.com/issues/124235144). Let's converge on that, and we can reopen if that ends up not being the case.
