### ISSUE TITLE
why component must specify a module?

### ISSUE THREAD

**Issue by macarthor** [google/dagger#1417]
let’s see a simple example:

```java
class SomeThing {
    private String something;

    @Inject
    SomeThing(String thing) {
        something = thing;
    }

    String getThing() {
        return something;
    }
}

@Module
class ThingModule {
    @Provides
    static String providesThing() {
        return “some_thing”;
    }
}

@Component /* (modules = {ThingModule.class}) */
interface ThingComponent {
    void injectToActivity(ThingActivity activity);
}

public class ThingActivity extends Activity {
    @Inject SomeThing something;

    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_thing);
    }
}
```

when i build this code, it gives error as follows:

```
error: [Dagger/MissingBinding] java.lang.String cannot be provided without an @Inject constructor or an @Provides-annotated method.
```

which means the ctor of `SomeThing` class cannot find the `String` source.

but in my understanding, the glue `ThingComponent` should connect `SomeThing(String)` with `String providesThing()`, because they share the same `String` class.

so my question is, why Dagger 2 cannot resolve the dependency without specifying module in component?

**Comment by JakeWharton** [comment]
What if you have two modules which both provide `String`? Which do you use?

**Comment by macarthor** [comment]
@JakeWharton aye i considered this when i have that question. why dagger could not handle the one-consumer-with-one-producer case?

**Comment by JakeWharton** [comment]
It creates an explicit link to the producer rather than an implict one prone to breakage in refactor and modularization.

**Comment by ronshapiro** [comment]
There's also no reasonable mechanism to scan the entire classpath to find every module. But as @JakeWharton said, even if it were possible, it would not be desirable.

Dagger greatly values explicit configuration, as it's very clear as applications evolve exactly what is happening.
