### ISSUE TITLE
Gradle build cannot find Module_ProvidexFactory even though it has been generated by Dagger

### ISSUE THREAD

**Issue by akvashi** [google/dagger#1421]
Our project is multimodule and we have been running into a particular issue when multiple feature-modules depend on another feature-module. 

For example: moduleB and moduleC depend on moduleA. moduleA has some interfaceA for a component (though isnt annotated with @Component )

moduleB and moduleC both have @Component interfaces which extend from the interfaceA

The initial issue is that with this the MemberInjection_Factory is created in both moduleB and moduleC but under the same package as moduleA which causes a dexMerge issue when building from command line gradle though strangely enough not from Android Studio (I don't believe any special settings are activated on either)

In order to stop this, I created a @Module (call it DagModuleA) in moduleA which defines an @Provides method for the class that needs to be created. This has worked in the past but in this case. I get an error during compile time (on both command line and Android Studio) that says:

cannot find symbol:  DagModuleA_ProvidexFactory

But I can see this file in the build generated files, and in fact, Android Studio can too so there is no warning until compile time.

This might describe two different issues, I can split them if I need to :)

**Comment by ronshapiro** [comment]
This appears to be a question - please use StackOverflow instead, as that is a better forum for questions.
