### ISSUE TITLE
is dagger2 support android componentized architecture ?

### ISSUE THREAD

**Issue by ShaunWilson** [google/dagger#1426]
Sir , our project is componentized architecture , A lot of moudules are generated by binary and then uploaded to maven for reference. There are many activities in each moudule. I tried, Process can only scan the main moudle. Is there any good way to support the Android componentized architecture?

                                                                                                                                                Best Wishes

**Comment by ronshapiro** [comment]
This appears to be a question - please use StackOverflow instead, as that is a better forum for questions.

**Comment by ShaunWilson** [comment]
okey,thanks！
