### ISSUE TITLE
Are there any other uses for @Component-Builder besides @BindsInstance and different methods names?

### ISSUE THREAD

**Issue by FlorianWalther** [google/dagger#1427]
There is not much information around about @Component-Builder. It seems to be only used to add @BindsInstance methods and maybe to change the name of Builder methods.
Anything I am missing here?

**Comment by JakeWharton** [comment]
Modules which require instances (i.e., not just abstract + static) are provided via builder methods.

**Comment by FlorianWalther** [comment]
Right, but their setter methods get auto-generated even if I don't create my own @Component.Builder definition? Are there any things I can only do with my own Component.Builder (created with the @Component.Builder annotation) besides adding @BindsInstance methods?

**Comment by JakeWharton** [comment]
While they're generated, that type is package private making it only applicable for use next to or near the definition site. When you add them to your builder definition, they can he public API and used by consumers.

**Comment by FlorianWalther** [comment]
Thank you for the explanation. Anything else worth mentioning?

**Comment by JakeWharton** [comment]
Things listed in @Component(dependencies=…) come in through them I believe.
I think that's it though.

**Comment by FlorianWalther** [comment]
Thank you very much!
