### ISSUE TITLE
Static @Provides methods in stateful modules?

### ISSUE THREAD

**Issue by FlorianWalther** [google/dagger#1430]
For this question, I leave `@BindsInstance` aside on purpose. I know that I should favor it over modules with constructor arguments. Anyways, I am interested in the following:

```
@Module
public class ThingImplModule {
    private int number;

    public ThingImplModule (int number) {
        this.number = number;
    }

    @Provides
    int provideNumber() {
        return number;
    }

    @Provides
    static Thing provideThingImpl(ThingImpl thing) {
        return thing;
    }
}
```

`Thing`, on the other hand, depends on `number` in its constructor:

 ``` 
@Inject
public ThingImpl (int number) {
    this.number = number;
}
```

My questions:
1. Is there any benefit in making `provideThingImpl` static, considering that an instance of this module has to be created anyways?
2. Is there any benefit in putting `provideThingImpl` into a separate module and turn it into an `abstract` `@Binds` method? Are there any performance optimizations from this?

**Comment by netdpb** [comment]
This is a question, and not a bug or feature request. In the future, please ask such questions on https://stackoverflow.com/questions/tagged/dagger-2.

1. Making `provideThingImpl()` static allows whole-program optimizers like ProGuard to inline the method call.

2. If you use `@Binds` there's no method call to inline at all.
