### ISSUE TITLE
java.lang.NoSuchMethodError: No static method injectMembers(Ldagger/MembersInjector;Ljava/lang/Object;)Ljava/lang/Object; in class Ldagger/internal/MembersInjectors; or its super classes (declaration of 'dagger.internal.MembersInjectors' appears in /data/app/com.vantiv.sampleapp-ph4IrMeN5gRc_AQVG-T7aw==/split_lib_dependencies_apk.apk)

### ISSUE THREAD

**Issue by hardikdhola** [google/dagger#1432]
i have used version "com.google.dagger:dagger:2.21" from "com.google.dagger:dagger:2.11"

compileSdkVersion 28
buildToolsVersion "28.0.3"
minSdkVersion 18
targetSdkVersion 28

java.lang.NoSuchMethodError: No static method injectMembers(Ldagger/MembersInjector;Ljava/lang/Object;)Ljava/lang/Object; in class Ldagger/internal/MembersInjectors; or its super classes (declaration of 'dagger.internal.MembersInjectors' appears in /data/app/com.vantiv.sampleapp-ph4IrMeN5gRc_AQVG-T7aw==/split_lib_dependencies_apk.apk)

**Comment by netdpb** [comment]
That method was removed in version 2.14 because it was unused. But if you build your app again from source, no generated code should use it.

Are there modules in your app that are already built with Dagger?

**Comment by archow** [comment]
I have the same error message as well.

minSdkVersion = 21
targetSdkVersion = 28
compileSdkVersion = 28
buildToolsVersion = '28.0.3'

I do however, have one package that uses dagger 2.19, and another that uses dagger 2.11, which does use the injectMembers method. any way to bypass this error?

**Comment by JIE-Joker** [comment]
I have the same error.When i use the version  "2.19" , it is no error.But when i use the version "2.20" and "2.21",there will throw this error.

**Comment by hardikdhola** [comment]
> Are there modules in your app that are already built with Dagger?

>> i have used follwing dependencies and "DaggerVtpDependencyBuilder.class" found from  triposmobilesdk.

- implementation(name: 'triposmobilesdk-release', ext: 'aar')
- implementation 'com.google.dagger:dagger:2.19'
- implementation 'org.apache.commons:commons-lang3:3.5'
- implementation 'commons-io:commons-io:2.5'
- implementation group: 'commons-validator', name: 'commons-validator', version: '1.6'

**Comment by JIE-Joker** [comment]
yes Joker Z 邮箱：jieaoxingzhez@gmail.com 签名由 网易邮箱大师 定制 On 03/01/2019 20:22, hardikdhola wrote: Are there modules in your app that are already built with Dagger? i have used follwing dependencies and "DaggerVtpDependencyBuilder.class" found from triposmobilesdk. implementation(name: 'triposmobilesdk-release', ext: 'aar') implementation 'com.google.dagger🗡2.19' implementation 'org.apache.commons:commons-lang3:3.5' implementation 'commons-io:commons-io:2.5' implementation group: 'commons-validator', name: 'commons-validator', version: '1.6' — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by netdpb** [comment]
Is there a reason you have more than one Dagger version in your app?

**Comment by hardikdhola** [comment]
> Is there a reason you have more than one Dagger version in your app?

i have no more than one Dagger version in my app.

**Comment by cindy-githut** [comment]
i get the same error when using 2.23..have no idea how to resolve it, tried rebuild, invalidate are restart but still the error persist 

No static method injectMembers

**Comment by DipakSharmaAgile** [comment]
**I got the same error, after increased version to latest one fixed the issue.**

**Comment by carstenhag** [comment]
Hitting the same issue while running tests right now... Using dagger 2.37.
