### ISSUE TITLE
Redundant Null Check for @BindsInstance values?

### ISSUE THREAD

**Issue by FlorianWalther** [google/dagger#1435]
Hello,
I pass these 2 values over @BindsInstance methods. It looks like it checks if they are not null 2 times. Isn't that redundant or am I missing something?

`private static final class Builder implements CarComponent.Builder {
    private Integer horsePower;

    private Integer engineCapacity;

    @Override
    public CarComponent build() {
      if (horsePower == null) {
        throw new IllegalStateException(Integer.class.getCanonicalName() + " must be set");
      }
      if (engineCapacity == null) {
        throw new IllegalStateException(Integer.class.getCanonicalName() + " must be set");
      }
      return new DaggerCarComponent(this);
    }

    @Override
    public Builder horsePower(int horsePower) {
      this.horsePower = Preconditions.checkNotNull(horsePower);
      return this;
    }

    @Override
    public Builder engineCapacity(int engineCapacity) {
      this.engineCapacity = Preconditions.checkNotNull(engineCapacity);
      return this;
    }
  }`

**Comment by JakeWharton** [comment]
Well for one there shouldn't be a null check for a primitive anyway. But in general the pattern of two checks is normal. One guards the input to ensure you don't set illegal values and the other guards creation of the object to ensure all required data is present.

**Comment by FlorianWalther** [comment]
Thank you, I didn't know that. Who is doing the mistake when it does a null check on primitives? Should it not be generated or should I somehow not pass primitives?

**Comment by ronshapiro** [comment]
We've kept that because it can function as the existence check just like a
normal object. The boxing hasn't seemed to hurt anyone as these are rarely
in tight loops

**Comment by FlorianWalther** [comment]
I see, thanks for the explanation.
