### ISSUE TITLE
Contribute to parent Map from subcomponent

### ISSUE THREAD

**Issue by matpag** [google/dagger#1440]
Hello guys, I'm trying to implement `FragmentFactory` with Dagger. 
My situation is currently described in this StackOverflow [question](https://stackoverflow.com/questions/55043890/dagger-2-how-to-bind-fragment-map-in-parent-component-from-subcomponent).

To resolve this I think I need `Subcomponents` to be able to have both a factory creating fragments per activity and a custom lifespan scope for hierarchical fragments injection. (pretty similar to what Google did in his Android IOsched app [here](https://github.com/google/iosched/blob/master/mobile/src/main/java/com/google/samples/apps/iosched/di/ActivityBindingModule.kt) and [here](https://github.com/google/iosched/blob/master/mobile/src/main/java/com/google/samples/apps/iosched/ui/schedule/ScheduleModule.kt) but with FragmentFactory added)

The problem is that I'm not able from subcomponents to contribute to the parent map of type 
`Map<Class<out Fragment>, @JvmSuppressWildcards Provider<Fragment>>`

What's the correct way to handle this case?
Thank you in advance

**Comment by ronshapiro** [comment]
Why aren't you using the APIs in http://google.github.io/dagger/android? `@ContributesAndroidInjector` should do what you need

**Comment by matpag** [comment]
If I use something like this:
```
    @FragmentScoped
    @ContributesAndroidInjector
    internal abstract fun bindLoginFragment(): LoginFragment
```
there is no Key in FragmentFactory map to provide the `LoginFragment`.

The app compiles fine but crashes at runtime because when the Fragment is created 
`Map<Class<out Fragment>, @JvmSuppressWildcards Provider<Fragment>>`
does not contains "LoginFragment::class" as key

**Comment by ronshapiro** [comment]
I'd recommend taking this to StackOverflow, which is better for questions.

**Comment by matpag** [comment]
I did, but nobody answered :(
Btw thank you for your help
