### ISSUE TITLE
Update support library dependency to AndroidX

### ISSUE THREAD

**Issue by lwasyl** [google/dagger#1444]
As more projects migrate to AndroidX, it makes less and less sense to use old support library dependencies for Dagger. As soon as all dependencies of an app are using AndroidX libraries, Jetifier can be turned off -- right now it's likely that Dagger is the only library using support libraries, thus forcing Jetifier usage.

Is there any timeline for migrating Dagger dependencies to AndroidX?

**Comment by JakeWharton** [comment]
> right now it's likely that Dagger is the only library using support libraries

Maybe for your build. In the general case this isn't remotely true.

**Comment by binhbk230** [comment]
I have many problem when migrate my project to android x, some time i can't inject dependency, hope dagger team will fix this problem ASAP

**Comment by mateuszkwiecinski** [comment]
> Is there any timeline for migrating Dagger dependencies to AndroidX?

👍

**Comment by ronshapiro** [comment]
No timeline in the near term. Jetifier still seems to be the documented way to go for libraries that want to support old versions. In the interim, you can try to jetify yourself and then cache that jetified artifact somewhere. I imagine that the build system may already do something like that anyway.
