### ISSUE TITLE
Throw if injecting Subcomponent.Builder without a provider

### ISSUE THREAD

**Issue by jroitgrund** [google/dagger#1448]
Injecting `Provider<SubcomponentInteface.Builder>` lets you build a subcomponent.
However, Dagger also lets you inject `SubcomponentInterface.Builder` directly, leading to concurrency bugs if subcomponents are created from the same partially initialized builder.

Dagger should make it impossible to inject `Subcomponentinteface.Builder` directly.

**Comment by ronshapiro** [comment]
This is something that you can write a custom plugin to support (
google.github.io/dagger/spi). It's not something that makes sense to me to
be built inside of Dagger since there are valid use cases of injecting a
simple subcomponent builder

**Comment by jroitgrund** [comment]
Do you have an example of one of these use cases? My concern is that it's easy to shoot yourself in the foot with this - being able to write a plugin to prevent it only helps if you know about the problem in the first place.

**Comment by ronshapiro** [comment]
Most of the validation inside Dagger uses the same infrastructure. You'll want to check for every dependency request edge, is the dependency request's `RequestKind` an `INSTANCE` and if so, is the source node from that edge a `Binding` who's kind is `SUBCOMPONENT_CREATOR`

**Comment by cgdecker** [comment]
FWIW [`@Subcomponent.Factory`](https://google.github.io/dagger/api/latest/dagger/Subcomponent.Factory.html), which should be in the next Dagger release, doesn't have this issue.

**Comment by ronshapiro** [comment]
I'm going to close this - @cgdecker's point is a good one, and the SPI plugin should live outside of Dagger.
