### ISSUE TITLE
Calling AndroidInjection#inject on activities/fragments that don't use dagger

### ISSUE THREAD

**Issue by linaran** [google/dagger#1451]
I'm relying on [this](https://google.github.io/dagger/android.html) tutorial to push the `AndroidInjection#inject` call into a `BaseActivity` that all other `Activities` extend but there's a problem. Some activities that extend `BaseActivity` don't inject anything and therefore I don't generate a component for them with `@ContributesAndroidInjector`.

Unfortunately due to inheritance, these activities that basically don't use Dagger, still call `AndroidInjection#inject` and that's why I get an `java.lang.IllegalArgumentException`. I've been digging around the generated code and I noticed there's a `maybeInject` method that would work nice for me here, but I can't find a way to use it. I also can't access the Map (through a method or directly) to simply check if the `Activity` supplied to the `AndroidInjection#inject` has an injector ready to be used.

I'd really like to not have to create my own version of an already existing Map just to check if I can call `AndroidInjection#inject` on the supplied parameter. The issue described for Activities may also happen for fragments.

Do you have any suggestions for my use-case? Note that I'm currently using Dagger 2.16 (in the process of migrating to higher version). I checked release notes and googled around and didn't find anything regarding this issue.

**Comment by Ethan1983** [comment]
For one, you could use a hook to disable injection. Override enableInjection to disable injection like in unit tests and cases like yours.

```
abstract class AbsTestableDaggerFragment : Fragment(), HasSupportFragmentInjector {

    @Inject
    lateinit var childFragmentInjector : DispatchingAndroidInjector<Fragment>

    protected open var enableInjection = true

    override fun onAttach(context: Context) {

        if( enableInjection ) {
            AndroidSupportInjection.inject(this)
        }

        super.onAttach(context)
    }

    override fun supportFragmentInjector(): AndroidInjector<Fragment>? {
        return childFragmentInjector
    }
}
```

**Comment by ronshapiro** [comment]
Or `BaseActivity` and `InjectedBaseActivity`, which extends `BaseActivity`.

But this isn't a forum for questions - I recommend trying StackOverflow.
