### ISSUE TITLE
Generated component won't create lambda return inner interface type properly in test variant

### ISSUE THREAD

**Issue by esial** [google/dagger#1454]
In Kotlin with gradle when `Foo.Bar` is public inner interface used like this:
```
interface FooBarComponent {
    val fooBarProvider: () -> Foo.Bar
}

@Singleton
@Component(modules = [FooBarModule::class])
interface ApplicationComponent : FooBarComponent 

@Module
class FooBarModule {
    @Provides
    @Singleton
    fun bindViewModelFactory(): () -> Foo.Bar{
        return { MyFooBar() }
    }
}
```
This works fine in application variant,
```
// generated code (more or less :>) 
 @Override
  public Function0<Foo.Bar> getFooBarProvider() {
    return bindFooBarProvider.get();
  }
```
 but when I want to add this same module to `TestComponent` with `kaptAndroidTest 'com.google.dagger:dagger-compiler:2.21' added in test variant, like this:
```
@Singleton
@Component(modules = [FooBarModule::class])
interface TestComponent : ApplicationComponent
```
I get compilation error because of generated dolar char instead dot:
```
// generated code (more or less :>) 
 @Override
  public Function0<Foo$Bar> getFooBarProvider() {
    return bindFooBarProvider.get();
  }
```

**Comment by ronshapiro** [comment]
I think this is due to this Kotlin bug:
https://youtrack.jetbrains.net/issue/KT-27936

**Comment by esial** [comment]
@ronshapiro It might be. I'm wondering why generated component class is different for test variant.

**Comment by ronshapiro** [comment]
I think the issue arises when types span multiple compilations. The androidTest compilation is separate and depends on the main compilation

**Comment by esial** [comment]
> I think the issue arises when types span multiple compilations. The androidTest compilation is separate and depends on the main compilation

@ronshapiro You're right. I found a simple workaround by creating test dedicated module providing same implementations. Yet I think that in some cases it will be painfull boilerplate.

**Comment by ronshapiro** [comment]
Let's close this issue then in favor of that Kotlin one.

😢
