### ISSUE TITLE
Faster Execution on CPUs with many cores

### ISSUE THREAD

**Issue by samzurcher** [google/dagger#1456]
We use Dagger2 in a fairly large Android application written in Kotlin. We use the dagger-compiler with kapt3. The kapt step takes unfortunately a significant amount of time in our overall build. Looking at the CPU history during the build, it is obvious that only very few CPU cores are used; meaning that the build is a lot slower than it actually could be. 

Without having in-depth knowledge of Dagger2, it seems that that at least parts of the dagger annotation processing could be done in parallel.

Questions:
1. Is there a conceptual problem in increasing the parallelism for the dagger annotation processing? 
2. Would it be possible, to add support for better parallelism? E.g. using parallelStream() in the correct places?

Thanks a lot for looking into that. I'm sure I'm not the only developer who would enjoy writing more code and less waiting :-).

**Comment by ronshapiro** [comment]
Our cursory look at this in the past has deemed it to be much harder than
ideally possible for a few reasons:
- there isn't a lot of work that can necessarily be parallelized. Most of
what we do relies on verification of earlier steps. It's possible some
binding graph validation could happen in parallel, but that's often not
nearly the slowest part of the build
- most of the underlying types that javac provides are not known to be
threadsafe, and there is a lot of mutable state in the compiler. It would
be hard to verify that concurrency would not cause problems there.

I'm open to suggestions of what could be done though. Formatting generated
code is something that @netdpb has interest in parallelizing, but I don't
think that's on his plate in the near term.

**Comment by samzurcher** [comment]
Thanks a lot for the reply and the analysis. You guys know dagger a lot better than I do (just glanced at the source today), so unfortunately no suggestions. 

Do you guys have any configurable debug output that would reveal more about the timing of the sub steps executed? If there were such a debug output, I could run it on my project and see where time really gets eaten... - maybe that could be taken as an input on what really hurts - and maybe you would see an option for improvement based on that...

**Comment by ronshapiro** [comment]
We don't have anything to currently capture that, but we could add that.
Usually hooking up a profiler is the most helpful I've found, since it
gives you much richer information than just timestamps. I think Jetbrains
has a profiler that works well with gradle builds but I'm not exactly sure.

**Comment by cgdecker** [comment]
I experimented a little with trying to parallelize some stuff in the annotation processor and found that the javac APIs used in annotation processing are not just documented to be non-threadsafe but easy to work around, they really are extremely non-threadsafe throughout. I don't think we could parallelize without first doing something like figuring out a way to make an immutable, thread-safe copy of all the data we'll actually need from those APIs as a first step then use and then using that throughout the parallelized code. But that seems like it would be a very large project, to say the least. And even then there are other roadblocks.

**Comment by ronshapiro** [comment]
Given Colin's assessment, let's close this issue as infeasible. There's much optimization work to be done to make Dagger faster in a serial manner. Let's keep pushing in that direction before we attempt any parallelism.
