### ISSUE TITLE
Worst documentation ever seen

### ISSUE THREAD

**Issue by WebTiger89** [google/dagger#1466]
Seriously guys what did you think by writing this documentation:

https://google.github.io/dagger/

I'm not wondering why all switch to Koin & Co

**Comment by JakeWharton** [comment]
Looking forward to your contributions to improve it!

**Comment by ronshapiro** [comment]
You'll be glad to know that we have new documentation on it's way.

But also I'm regularly shocked at how many people feel that it is upon them to tell us how bad our documentation is. Open Source Software is done as a service - it is your choice to use it or not. If it doesn't serve your needs, you don't need to use ad hominem attacks. 

Glad that we have many users that care to be constructive instead. It makes a better environment for all developers.
