### ISSUE TITLE
The generated Component visibility escalated to public.

### ISSUE THREAD

**Issue by TonyTangAndroid** [google/dagger#1467]
Define a default component.
`@dagger.Component
interface RootComponent {}`.

And its generated code is 

```
public final class DaggerRootComponent implements RootComponent {
  private DaggerRootComponent() {}

  public static Builder builder() {
    return new Builder();
  }

  public static RootComponent create() {
    return new Builder().build();
  }

  public static final class Builder {
    private Builder() {}

    public RootComponent build() {
      return new DaggerRootComponent();
    }
  }
}
```

Notice that the interface is non public. But the generated DaggerRootComponent is becoming public.  Is there any reason behind the scene that makes it a public?

**Comment by ronshapiro** [comment]
I don't think so. We can change this to match the definition type.

**Comment by TonyTangAndroid** [comment]
Good to know. Thank you for the awesome work.

**Comment by TonyTangAndroid** [comment]
Awesome. Thank you.
