### ISSUE TITLE
Dagger-android - DaggerAppCompatActivity to support for @LayoutRes used with ComponentActivity

### ISSUE THREAD

**Issue by Ethan1983** [google/dagger#1469]
This is applicable when FragmentFactory is used with DaggerAppCompatActivity (ComponentActivity) with @LayoutRes for content view.

ComponentActivity when used with @LayoutRes calls setContentView in its onCreate which will be supered from DaggerAppCompatActivity. setContentView on a layout using fragments (created from a custom FragmentFactory) needs for it to be set on support fragment manager which is typically injected using Dagger in concrete application class.

```
    @Inject
    lateinit var fragmentFactory : DaggerFragmentFactory

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        supportFragmentManager.fragmentFactory = fragmentFactory
    }
```

super.onCreate is the one actually injecting fragmentFactory which can be used only after that. However, setContentView() invoked in ComponentActivity's onCreate() needs for the fragmentFactory to be set in supportFragmentManager. This causes a cyclic functional dependency.

Current workaround is for app class to call setContentView explicitly. If this is not supported, at the least, DaggerAppCompatActivity should throw an unsupported exception on the constructor taking @LayoutRes

Ref: https://developer.android.com/jetpack/androidx/releases/appcompat#1.1.0-alpha04

**Comment by ronshapiro** [comment]
I'm not sure what you're referencing about `@LayoutRes`. Are you asking it to be considered an implicit qualifier?

**Comment by Ethan1983** [comment]
Nope, @LayoutRes is android feature that is meant to automate view inflation in an activity. This logic is in the base class (ComponentActivity) which will be a base for DaggerAppCompatActivity too.
View inflation logic needs FragmentFactory which is available only post dagger injection and without injection view inflation logic will use default FragmentFactory.

"_AppCompatActivity now contain a second constructor that takes a @LayoutRes int, which replaces the previous behavior of annotating your AppCompatActivity class with @ContentView. This approach works in both app and library modules._"

**Comment by JakeWharton** [comment]
`@LayoutRes` has been around forever and marks `int` parameters and return types which are meant to be used with `R.layout` as opposed to `R.id` or random values like `42`.

This new feature (that no one asked for and probably shouldn't exist) adds a second constructor to the base types in AndroidX for automatic inflation of a layout. However, since Dagger's base types are not propagating these second constructors, how are you using it?

**Comment by Ethan1983** [comment]
Yes, i meant the usage of @LayoutRes with the new constructor.

And for the impact, it does not affect the existing releases and that is why i mentioned "which will be a base for DaggerAppCompatActivity", as and when DaggerAppCompatActivity is updated to be based on latest version of AppCompatActivity (ComponentActivity) and hence the feature request to decide how it should be handled.

My projects are not affected as they use Databinding and not planning on using this constructor either. However, it will come across as not handled at a later time (when dagger-android tracks latest version) by folks using that feature with dagger injected FragmentFactory along with Navigation Jetpack.

No strong opinion on the original feature in ComponentActivity but i'm assuming DaggerAppCompatAtivity will be updated at some point to be based on latest versions (along with androidx migration).

**Comment by tadfisher** [comment]
The annotation you're looking for is `@ContentView`, and I believe it is indeed `Activity.onCreate` `Fragment.onCreateView` which checks the type annotations for a layout resource to inflate.

The solution, then, is to call `setFragmentFactory` *before* you call `super.onCreate`. Not doing so is already broken because fragments are restored in `super.onCreate` with the default factory.

**Comment by Ethan1983** [comment]
@ContentView is the one being replaced by the constructor. And reg, setting factory before super.onCreate works as long as the factory itself is not injected otherwise it is a chicken-egg problem.

_ComponentActivity now contain a second constructor that takes a @LayoutRes int, which replaces the previous behavior of annotating your AppCompatActivity class with @ContentView. This approach works in both app and library modules._

**Comment by danysantiago** [comment]
Just cleaning up old issues, closing this since it was added in:  https://github.com/google/dagger/commit/22b2726651370aaaf1c2e15d65c183d4705fb91c
