### ISSUE TITLE
Dagger2 allows component's modules to have unresolvable dependencies if they aren't used

### ISSUE THREAD

**Issue by Tagakov** [google/dagger#1472]
It's more like a question, but I was surprised today:

```
@Component(modules = [M::class])
interface C {
    fun str(): String
}

@Module
class M {
    @Provides
    fun int(unresolvable: System): Int = 42

    @Provides
    fun str() = "42"
}
```
The code above compiles and runs successfully. Which is surprising because `System` dependency can't be resolved. But it immediately fails compilation if `Int` would be requested from the component. This behavior is pretty handy but looks too tolerant. Is it intended behavior or not?

**Comment by TonyTangAndroid** [comment]
I had run into a similar issue yesterday. It seems that if the component does not expose the provided method, it doesn't conduct any check.

**Comment by trevjonez** [comment]
seems like a compiler optimization not a bug. what would it do to compile time to exhaustively verify every path through the graph (that crosses through a module provides) regardless of need?

**Comment by ronshapiro** [comment]
In 2.23, you'll be able to pass `-Adagger.fullBindingGraphValidation=error` (or `=warning`) to get this type of validation.

It does have a compile time performance hit which is why we haven't done it by default ever.

**Comment by TonyTangAndroid** [comment]
Cool. Got it. Thanks.
