### ISSUE TITLE
Dagger 2.8  problem with firebase-inappmessaging-display

### ISSUE THREAD

**Issue by javier4mar** [google/dagger#1482]
Hi ,I have a project that I user dagger 2.8, the project works perfect with firebase-messaging and firebase-core libs, but when I try to add the new  firebase-inappmessaging-display lib, when I try to compile the app, I have an error with dagger :

Cause: dagger.Provides missing element type
 
Thanks
[build.txt](https://github.com/google/dagger/files/3075337/build.txt)
[build.gradle.txt](https://github.com/google/dagger/files/3075340/build.gradle.txt)

**Comment by ronshapiro** [comment]
Please use StackOverflow for questions. Also, we recommend that you update your version of Dagger to a newer release.
