### ISSUE TITLE
Feature request: support multiple qualifiers in a binding

### ISSUE THREAD

**Issue by cesar1000** [google/dagger#1486]
We’re using qualifiers to represent orthogonal properties in some of our bindings, so it’s relatively typical that we may apply multiple qualifiers to a single binding. For example, we’d like to use `@AutoInitialized @Private Object` for a multibound set of objects that’s initialized within a graph. When doing that, Dagger currently issues the error “@Binds methods may not use more than one @Qualifier”.

[The spec](https://docs.oracle.com/javaee/6/api/javax/inject/Qualifier.html) makes no mention of a maximum of 1 qualifier. Would it make sense for Dagger to lift the restriction of one qualifier per binding?

**Comment by ronshapiro** [comment]
I think I was wrong when I mentioned that to you. `@Qualifier`'s docs don't say anything, but `@Inject`'s does:
> Qualifiers are optional, and when used with @Inject in injector-independent classes, no more than one qualifier should annotate a single field or parameter. 

We could obviously do something for `@Provides` etc, but I don't think that inconsistency is a good idea.

**Comment by cesar1000** [comment]
Hmm that's a bummer. Yeah, allowing them only with `@Provides` doesn't sound like a good idea, since bindings won't be consistently useable anyway. Thinking through it carefully, I'm not sure I can come up with strong reasons why multiple qualifiers would be strictly needed, even in generic cases where bindings are generated automatically.

In my previous example, `@AutoInitialized` does qualify the binding to modify its identity. `@Private`, however, does not behave as a qualifier, but rather as a mechanism for describing an extra trait of the binding for the consumption of the dependency injection engine. I'll look for alternative mechanisms for implementing similar behavior without the need to resort to a qualifier.

**Comment by ronshapiro** [comment]
I'm going to close this as infeasible given the `javax.inject` requirements
