### ISSUE TITLE
More details on "install the missing build tools version with the android sdkmanager tool"

### ISSUE THREAD

**Issue by cpovirk** [google/dagger#1487]
I'm trying to follow the instructions at https://github.com/google/dagger/blob/master/CONTRIBUTING.md#building-dagger-from-the-command-line

I've gotten as far as:
- download Linux tools from https://developer.android.com/studio#command-tools, unzip, and export `ANDROID_HOME` to point there
- `$ANDROID_HOME/tools/bin/sdkmanager 'platforms;android-26'`

But now, when I run `bazel test //...`, I'm seeing:

```
ERROR: /usr/local/google/home/cpovirk/clients/dagger-yellow/dagger/java/dagger/android/support/BUILD:44:1: no such package '@androidsdk//com.android.support': BUILD file not found on package path and referenced by '//java/dagger/android/support:manual-maven-deps'
ERROR: /usr/local/google/home/cpovirk/clients/dagger-yellow/dagger/java/dagger/android/support/BUILD:44:1: no such package '@androidsdk//com.android.support': BUILD file not found on package path and referenced by '//java/dagger/android/support:manual-maven-deps'
ERROR: /usr/local/google/home/cpovirk/clients/dagger-yellow/dagger/java/dagger/android/support/BUILD:44:1: no such package '@androidsdk//com.android.support': BUILD file not found on package path and referenced by '//java/dagger/android/support:manual-maven-deps'
ERROR: Analysis of target '//java/dagger/android/support:manual-maven-deps' failed; build aborted: no such package '@androidsdk//com.android.support': BUILD file not found on package path
```

Looking for the support library, I ran:
`$ANDROID_HOME/tools/bin/sdkmanager --list | grep support`

But it sounds like the the main support library isn't available that way anymore. Possibly I need to do something related to https://github.com/bazelbuild/bazel/issues/4106 and https://github.com/bazelbuild/bazel/issues/1745, but it's not clear what.

**Comment by JakeWharton** [comment]
This would be solved by https://github.com/google/dagger/issues/1276

**Comment by cpovirk** [comment]
Hmm, I just tried running Bazel again, and I got a different error (maybe because I ran `build` instead of `test`, or maybe the old server had shut down or something??):

`ERROR: /usr/local/google/home/cpovirk/.cache/bazel/_bazel_cpovirk/7cee73372ad52c17db7b6117de5a4f21/external/androidsdk/BUILD.bazel:8:1: @androidsdk//:aapt_binary: missing input file '@androidsdk//:build-tools/26.0.2/aapt'`

That one is easy to solve:

`$ANDROID_HOME/tools/bin/sdkmanager 'build-tools;26.0.2'`

Now things are working.

A couple possibilities:

- Installing `build-tools` solved the `com.android.support` problem?
- The problem had already been solved during my initial download of the command-line tools and/or installation of the platform, but Bazel had cached the failure?
- Something else that I did (like installing the full Android Studio into a separate directory that I temporarily set my `ANDROID_HOME` to point to, but I can't see how that would have "stuck") helped?
- I got confused by something else?

**Comment by JakeWharton** [comment]
Installing build-tools won't have affected the missing dependencies. That requires installing a different package.

**Comment by cpovirk** [comment]
I've experimented some more, and it looks like the other key was:

`$ANDROID_HOME/tools/bin/sdkmanager 'extras;android;m2repository`

I had thought that had been a no-op because it completed so quickly, but I think the quick completion was because I'd previously done the work with:

`$ANDROID_HOME/tools/android update sdk --no-ui --all --filter extra-android-m2repository`

I thought I had then undone the operation with `--uninstall`, but I see from my `.bash_history` that my next command was actually `--install`......

The other trick is that I needed a `bazel sync` after that command.

The further trick is that `extras;android;m2repository`, while identified as "Android Support Repository," slipped through my search because it didn't contain "support" in lowercase.

Now that I know what to do, I may try to put docs together eventually.

**Comment by cpovirk** [comment]
Quick update:

I noticed an internal script that (currently) runs `sdkmanager "build-tools;29.0.2"` and `sdkmanager "platforms;android-29"`. I don't see anything about `"extras;android;m2repository"`, but I'm not sure if that means that there's something different about our internal environment or that something has changed in the meantime.

**Comment by Chang-Eric** [comment]
Going to close this for now since I think it has been fixed, but feel free to comment back if you still run into issues.

**Comment by cpovirk** [comment]
Thanks, I no longer need to install `m2repository`. I'm going to send you a change to add some of the other details here. They're probably obvious to "real" Android users, but they might help people like me who just happen to be building the Android targets without really "using" them.

**Comment by Chang-Eric** [comment]
Thanks, any documentation fixes are appreciated. No such thing as a "real" Android user =)
