### ISSUE TITLE
support androidx

### ISSUE THREAD

**Issue by season654239** [google/dagger#1489]
when to support androidx?

**Comment by charlykno64** [comment]
I have a working project with androidx, arch components, dagger 2.22.1...
What do you mean with "support androidx"?

**Comment by trevjonez** [comment]
currently you must run the jettifier, ideally you wouldn't need jettifier as we approach the one year announcement of the androidx namespace. IIRC androidx wasn't stable until much later though so maybe saying one year isn't really fair?

**Comment by season654239** [comment]
> I have a working project with androidx, arch components, dagger 2.22.1...
> What do you mean with "support androidx"?

yes,thanks

**Comment by frmz** [comment]
Firebase from July will support androidx so a lot of apps could remove jetifier if Dagger also makes the jump, i see also #1518 was closed so which issue is tracking this now?

**Comment by frmz** [comment]
Now Firebase and Google Play Services have also migrated to AndroidX, the jetifier alone slows down my build by 30%

**Comment by JakeWharton** [comment]
How did you measure this? Since jetifier uses the Gradle artifact transform API which is cached only the first build pays a cost and the rest are free. Sounds like you have a Gradle bug and should report it to them.

**Comment by frmz** [comment]
@JakeWharton i tried to profile my build with both jetifier enabled and disabled and then compare the "transformation" task, and yes this happens on clean builds only but pipelines minutes are not free and they run at every code push
