### ISSUE TITLE
Dagger 2 and module-info.java

### ISSUE THREAD

**Issue by WitalijBukatkin** [google/dagger#1490]
Hey! I use oraclejdk 11 and module-info.java for creating module. I included Dagger 2 in gradle and wrote dagger sample. Dagger made DaggerAppComponent in generated/source/apt/main/mypackage/DaggerAppComponent.java. My Intellij idea not find this. How include generated sources in module-info.java?

**Comment by ronshapiro** [comment]
Can you elaborate more on what isn't working?

**Comment by WitalijBukatkin** [comment]
I don't access to DaggerAppComponent from my code. But this class is generated

**Comment by WitalijBukatkin** [comment]
Corrected. Everything is working
