### ISSUE TITLE
Passing @BindsInstance arguments to the subcomponent factory method

### ISSUE THREAD

**Issue by FlorianWalther** [google/dagger#1493]
When you create a getter method for a subcomponent in the parent component, you can pass modules that need arguments directly to the method.
Why is the same not possible for @BindsInstance arguments and I have to return the Builder instead?

```@Singleton
@Component(modules = ExampleModule.class)
public interface AppComponent {

    ActivityComponent.Builder getActivityComponentBuilder(*/ why not @BindsInstance arguments here ? */);
}

**Comment by cgdecker** [comment]
`ActivityComponent.Builder` in this case is just a binding like any other in your component... it can be injected or (as you're doing here) returned from an entry point. Factory methods for subcomponents on components (what you're describing) are a special case that we don't really recommend using anymore, particularly now that `@Subcomponent.Factory` exists.

Speaking of which, you can use `@Subcomponent.Factory` to get something close to what you want like this:

```
@Subcomponent(modules = ...)
interface ActivityComponent {
  ...
  @Subcomponent.Factory
  interface Factory {
    ActivityComponent create(/* @BindsInstance parameters can go here */);
  }
}

@Component(modules = ...)
interface AppComponent {
  ActivityComponent.Factory activityComponentFactory();
}

ActivityComponent c = appComponent.activityComponentFactory().create(foo, bar);
```

**Comment by FlorianWalther** [comment]
Thank you. Is there any particular reason these subcomponent factory methods never supported @BindsInstance arguments?

**Comment by ronshapiro** [comment]
We realized that the shorthand of subcomponent factory methods was subpar to just injecting the factory/builder, so we didn't bother adding `@BindsInstance` support.
