### ISSUE TITLE
Can't use "default" word as the name of the provided method

### ISSUE THREAD

**Issue by Drjacky** [google/dagger#1494]
When I use "default" as the name of a method that I want to provide it and inject it into a class, it doesn't generate and I get an error that says: blah cannot be provided without an @Provides-annotated method. For example:
> e: /Users/drjacky/sampleApp/app/build/tmp/kapt3/stubs/debug/com/sampleapp/app/di/component/AppComponent.java:8: error: [Dagger/MissingBinding] android.content.SharedPreferences cannot be provided without an @Provides-annotated method.

```
    @Provides
    fun default(context: Context): SharedPreferences =
        PreferenceManager.getDefaultSharedPreferences(context)
```
![image](https://user-images.githubusercontent.com/2296754/57009259-cbb05000-6bf5-11e9-8cce-b609628b90dc.png)

![image](https://user-images.githubusercontent.com/2296754/57009283-f13d5980-6bf5-11e9-9b62-be39ebf5fa39.png)

Dagger version: **2.22.1**
Kotlin version: **1.3.30**
Gradle Build Tools version: **3.3.2**
Android Studio version: **3.4**

**Comment by trevjonez** [comment]
default is a keyword in java so perhaps that is the cause? https://docs.oracle.com/javase/tutorial/java/nutsandbolts/_keywords.html

**Comment by Drjacky** [comment]
So the Android Studio(lint checker or I don't know some related plugin) should get improve on this, cause it can detect most of the other reserved keywords on that list, but not all of them(like `default`, `instanceof`,...).

Thanks.
