### ISSUE TITLE
Architecturing a FWK with Dagger

### ISSUE THREAD

**Issue by hectoruiz** [google/dagger#1500]
Hi,
We work on a FWK developed in a few artifacts whom every one has a Dagger module for provide their instances to the app using our FWK. All artifacts are wrapped in one artifact whose exposed to the app.

Since now we specify at this Dagger modules in the app component. Is there any option to group all this modules to don't need specify every one at app component?

The following images show what I'm talking about. The first image show how are set all Dagger modules now  and how we would like set them. For our desired configuration case we tried group the modules in other Dagger component. But we can't get a good configuration using a second Dagger component hosted at the wrapper artifact of our FWK (the first one is in the application, the AppComponent).

![image](https://user-images.githubusercontent.com/4199496/57306749-a9ca3800-70e3-11e9-888d-9af5ac6d77c6.png)

We have tried the relationship of both components with component.dependencies and subcomponent. But in both cases we have troubles in those relationships because the Appcomponent need the instances declared at Dagger Modules hosted in the WrapperComponent and the WrapperComponent need an instance declared at module hosted at AppComponent. 

![image](https://user-images.githubusercontent.com/4199496/57306944-f877d200-70e3-11e9-8e62-e10a3185afc9.png)
![image](https://user-images.githubusercontent.com/4199496/57306993-104f5600-70e4-11e9-8e0e-b667f40a275d.png)

Is there any option to have both components related to get the AppComponent without every Dagger Module specified like the first image?

Thanks in advance

**Comment by ronshapiro** [comment]
Can you use `@Module(includes = {...})` to create a single module for the app component to include?

If you want further discussion, StackOverflow is a better place than github issues if you want to ask questions.
