### ISSUE TITLE
Why do Singletons need an empty default constructor?

### ISSUE THREAD

**Issue by Isabaellchen** [google/dagger#1504]
Sorry for piling onto the empty default constructor debate, but this is something i do not understand.

I do understand that you want to make the code explicit as to where classes get initialized, but i do not understand why this has to be the case for classes that are annotated as Singletons, since there is only that one particular instance that i want to create.
If it is not too much to ask maybe someone could give an explanation to this?

**Comment by ronshapiro** [comment]
We don't make any exceptions to that rule. The more changes to it, the more
confusing it is to users for how to configure their bindings. One
consistent way regardless of scope has proven to be what most people expect
and is worth the slightly added verbosity in the uncommon case of scoped
types with no constructor arguments
