### ISSUE TITLE
No artifacts found for Dagger 2.23

### ISSUE THREAD

**Issue by matpag** [google/dagger#1512]
There are no 2.23 artifacts [here](https://mvnrepository.com/artifact/com.google.dagger/dagger) and [here](https://bintray.com/bintray/jcenter/com.google.dagger%3Adagger) 

Hope they will be published soon.

Thank you.

**Comment by ronshapiro** [comment]
This should be fixed now. Those pages are cached, but when they requery
they should find the 2.23 release

**Comment by JakeWharton** [comment]
Both of those aren't the canonical source either. The first one is a really, really slow third party index. You basically never want to use it. You want either repo1.maven.org or search.maven.org.

**Comment by matpag** [comment]
Thank you guys
