### ISSUE TITLE
@Multibinds problem with generating Map<K, Provider<V>>

### ISSUE THREAD

**Issue by shamilovstas** [google/dagger#1513]
In my class I'm trying to provide a map using multibindings:
```kotlin
@Singleton
class InjectingWorkerFactory @Inject constructor(
    private val workerFactories: Map<Class<out ListenableWorker>, @JvmSuppressWildcards Provider<ChildWorkerFactory>>
) : WorkerFactory() {

    override fun createWorker(
        appContext: Context,
        workerClassName: String,
        workerParameters: WorkerParameters
    ): ListenableWorker? {
        val foundEntry =
            workerFactories.entries.find { Class.forName(workerClassName).isAssignableFrom(it.key) }
        val factoryProvider = foundEntry?.value
        return factoryProvider?.get()?.create(appContext, workerParameters)
    }
}
```
In the main project I have several multibindings for this exact type being provided, so everything works as expected and doesn't break the compilation process:
```kotlin
    @Binds
    @IntoMap
    @WorkerKey(AnalyticsSyncWork::class)
    abstract fun bindAnalyticsSyncWorkFactory(factory: AnalyticsSyncWork.Factory): ChildWorkerFactory
```
However, my subproject doesn't declare any `@Binds` dependencies, but interacts with `InjectingWorkerFactory` as entry in the dependencies graph. Realizing, that it would break my build process, I tried to declare `@Multibinds` in my module to allow the subproject to be built.
```kotlin
    @Multibinds
    fun workerFactories(): Map<Class<out ListenableWorker>, @JvmSuppressWildcards Provider<ChildWorkerFactory>>
```
And I ended up with the following error: 
```
error: @Multibinds methods must return Map<K, V> or Set<T>
```
Assuming that the `@Multibinds` method might not allow the `Provider<ChildWorkerFactory>` to be present in the method signature, I tried to fix the `@Multibinds` declaration and came up with this version:
```kotlin
    @Multibinds
    fun workerFactories(): Map<Class<out ListenableWorker>, ChildWorkerFactory>
```
 But at this time it brought me this error: 
```
SampleAnalyticsAppComponent.java:10: error: [Dagger/MissingBinding] java.util.Map<java.lang.Class<? extends androidx.work.ListenableWorker>,javax.inject.Provider<adp.core.android.workmanager.ChildWorkerFactory>> cannot be provided without an @Provides-annotated method.
```

My expectation was that if I declare a `@Multibinds` method with the type `Map<Class<out ListenableWorker>, @JvmSuppressWildcards Provider<ChildWorkerFactory>>`, then the dependency which uses another dependency as a constructor parameter during constructor injection with the type declared in the `@Multibinds` method will be correctly processed and built by Dagger.

**Comment by bkolarov** [comment]
Did you solve your issue? Care to share if you made any progress? Thanks.

**Comment by Killer232323** [comment]
Did you solve your issue? Care to share if you made any progress? Thanks.

**Comment by httpdispatch** [comment]
I've faced the same issue as the author. Fixed that via removing `Provider` part from the `Multibinds` declaration
```
@Multibinds
fun workerFactories(): Map<Class<out ListenableWorker>, @JvmSuppressWildcards ChildWorkerFactory>
```
