### ISSUE TITLE
Dagger compiler not incremental after upgrading to 2.23

### ISSUE THREAD

**Issue by rciovati** [google/dagger#1514]
After upgrading to Dagger 2.23 we noticed that Gradle started reporting the Dagger compiler as a non-incremental annotation processor:

```
Gradle may disable incremental compilation as the following annotation processors are not incremental: dagger-compiler-2.23.jar (com.google.dagger:dagger-compiler:2.23), dagger-android-processor-2.23.jar (com.google.dagger:dagger-android-processor:2.23).
Consider setting the experimental feature flag android.enableSeparateAnnotationProcessing=true in the gradle.properties file to run annotation processing in a separate task and make compilation incremental.
```

Not sure if it's a problem but comparing the 2.23 jar with the 2.22.1 one we noticed that the Gradle configuration file is not in the top level `META-INF` folder:

```
➜  ~ find **/incremental*
dagger-compiler-2.22.1/META-INF/gradle/incremental.annotation.processors
dagger-compiler-2.23/java/dagger/internal/codegen/META-INF/gradle/incremental.annotation.processors
```

**Comment by ronshapiro** [comment]
argh. Ok, I'll try to fix this.

**Comment by ronshapiro** [comment]
`simple_jar` has always been hard to verify and get right, and it looks like one of the changes we made to make it support other bazel repositories broke this.

I'm not sure why I never used @tbroyer's https://github.com/tbroyer/gradle-incap-helper, but that should allow us to get rid of simple_jar.

**Comment by ronshapiro** [comment]
I've got a fix out internally, I hope to have this resolved and push a new version shortly

**Comment by ronshapiro** [comment]
I'm releasing 2.23.1 now. I've verified locally that the artifact has the correct META-INF file. Thanks for your patience here, and sorry again for the issue!

**Comment by ronshapiro** [comment]
2.23.1 should be available on Maven Central now.

**Comment by rciovati** [comment]
Thank you for the prompt fix!
