### ISSUE TITLE
[Android] @Singleton annotation brakes compilation

### ISSUE THREAD

**Issue by julianstokkur** [google/dagger#1517]
I was reading this blog post https://proandroiddev.com/saving-ui-state-with-viewmodel-savedstate-and-dagger-f77bcaeb8b08 which links to this repository https://github.com/Nimrodda/github-commit-browser (I used the commit 8cdb1cee63ed6181db374ccd861f875c6b3093ec), I noticed that he didn't add @Singleton annotation to the class app/src/main/java/org/codepond/commitbrowser/di/ViewModelFactory.kt so I added it and tried to compile the code, but by doing so it stopped compiling, I removed the annotation and it compiled again, I tried the same thing in a Java project of my own and the same thing happened, any idea why this could be happening?

**Comment by ronshapiro** [comment]
This appears to be a question - please use StackOverflow instead, as that is a better forum for questions.

**Comment by julianstokkur** [comment]
But wouldn't this be a Dagger bug? Adding the annotation makes the code stop compiling, so the @Singleton annotation changes how the code is generated and breaks it
