### ISSUE TITLE
DaggerFragment and DaggerAppCompatActivity androidx migration

### ISSUE THREAD

**Issue by gmartinsvrf** [google/dagger#1518]
Any plans for migrating **DaggerFragment** and **DaggerAppCompatActivity** over to **androidx**. I'm already using Fragment Navigation jetpack component but now I'm sort of lost as I am refactoring the project using dagger 2.

Thanks :)

**Comment by tbroyer** [comment]
Duplicate of #1181 ?

**Comment by gmartinsvrf** [comment]
@tbroyer yes but that's 1 year old ticket. Also, closed tickets are not helpful I guess. 

Plus, fragment navigation api is on v2.1.0 so I'm assuming that is considered stable?

**Comment by tbroyer** [comment]
#1489 then? (those are only 2 among a dozen issues that have already been opened about androidx)

**Comment by JakeWharton** [comment]
Yes let's please keep these consolidated

**Comment by gmartinsvrf** [comment]
Cool. That one is broad but works. I hope we can get that migration sooner rather than later.

Thanks guys. I really appreciate the attention!
