### ISSUE TITLE
Incremental KAPT breaks when injected fields change

### ISSUE THREAD

**Issue by consp1racy** [google/dagger#1519]
1. Have the following setup:

Kotlin 1.3.31
kapt.incremental.apt=true
Dagger 2.23.1

```
class MainActivity : Activity() {
    @Inject lateinit var classToConvert: ClassToConvert

    override fun onCreate(savedInstanceState: Bundle?) {
        DaggerActivityComponent.builder().build().injectMainActivity(this)
        super.onCreate(savedInstanceState)
    }
}

@Singleton
class ClassToConvert @Inject constructor()
```

2. Perform a clean build.
3. Switch to a branch where `ClassToConvert` class is moved to another package.
4. Run `gradlew assemble`.
5. Observe errors:

```
Compiling with JDK Java compiler API.
C:\RAMDisk\gradle\build\kotlinCacheIssue\app\generated\source\kapt\debug\com\mykotlindaggerapplication\ClassToConvert_Factory.java:6: error: cannot find symbol
public final class ClassToConvert_Factory implements Factory<ClassToConvert> {
                                                             ^
  symbol: class ClassToConvert
C:\RAMDisk\gradle\build\kotlinCacheIssue\app\generated\source\kapt\debug\com\mykotlindaggerapplication\ClassToConvert_Factory.java:10: error: cannot find symbol
  public ClassToConvert get() {
         ^
  symbol:   class ClassToConvert
  location: class ClassToConvert_Factory
C:\RAMDisk\gradle\build\kotlinCacheIssue\app\generated\source\kapt\debug\com\mykotlindaggerapplication\ClassToConvert_Factory.java:18: error: cannot find symbol
  public static ClassToConvert newInstance() {
                ^
  symbol:   class ClassToConvert
  location: class ClassToConvert_Factory
C:\RAMDisk\gradle\build\kotlinCacheIssue\app\generated\source\kapt\debug\com\mykotlindaggerapplication\ClassToConvert_Factory.java:11: error: cannot find symbol
    return new ClassToConvert();
               ^
  symbol:   class ClassToConvert
  location: class ClassToConvert_Factory
C:\RAMDisk\gradle\build\kotlinCacheIssue\app\generated\source\kapt\debug\com\mykotlindaggerapplication\ClassToConvert_Factory.java:19: error: cannot find symbol
    return new ClassToConvert();
               ^
  symbol:   class ClassToConvert
  location: class ClassToConvert_Factory
5 errors
Incremental compilation of 4 classes completed in 0.082 secs.
:app:compileDebugJavaWithJavac (Thread[Execution worker for ':' Thread 5,5,main]) completed. Took 0.098 secs.
```

The original generated factory was left over from before switching branches. The javac task tries to compile it and fails.
![image](https://user-images.githubusercontent.com/4589773/58750695-f5c78d00-8495-11e9-8d0a-cc804f22d9e2.png)

The original generated factory is removed if I move `ClassToConvert` in the IDE and have it replace references (including the ones in generated files). The generated file probably gets invalidated, Dagger picks up it's not supposed to be there and deletes it. Build succeeds.

If I move the `ClassToConvert` without touching generated files, the original factory gets left behind resulting in the above mentioned issue. This can be simulated by switching branches.

This doesn't happen when both `MainActivity` and `@Inject ClassToConvert` are in Java... and you don't use KAPT. It does happen with Java-only source files and KAPT. So we should probably report this to Jetbrains, too.

`kapt.use.worker.api` doesn't affect this.

Please find a sample project with instructions here: https://github.com/consp1racy/kotlinCacheIssue

Reported to Jatbrains here: https://youtrack.jetbrains.net/issue/KT-31742

**Comment by tbroyer** [comment]
This is indeed a bug in KAPT, not Dagger.

Fwiw, you enabled incremental KAPT but didn't enable the Dagger processor for incremental processing. That doesn't change the outcome though.

**Comment by ronshapiro** [comment]
In general, bugs in incremental compilation like this are beyond the scope of Dagger. It's always possible that we're not correctly setting originating elements, but that's one of the very few things that is necessary for Gradle's incremental compilation. 

If the Jetbrains (or honestly, it's possible it's a Gradle bug) reports back that this was in fact an issue within Dagger, let us know and we can re-investigate.
