### ISSUE TITLE
Cannot import dagger module from library module in multi module project

### ISSUE THREAD

**Issue by phm1015** [google/dagger#1527]
using 2.20 version of dagger

@Module
public class NetworkModule {
@Provides
    @NonNull
    public RxJava2CallAdapterFactory provideRxJavaCallAdapterFactory() {
        return RxJava2CallAdapterFactory.create();
    }
}

"Error "
private NetworkModule_ProvideRxJavaCallAdapterFactoryFactory
          ^
  symbol:   class NetworkModule_ProvideRxJavaCallAdapterFactoryFactory
  location: class DaggerAppComponent

but if you move the module file to  Application module it builds successfully

**Comment by ronshapiro** [comment]
Please use stackoverflow for debugging help
