### ISSUE TITLE
Annotation Processor generates code that will infinitely loop at run time instead of creating an instance of a Class with the required injected constructor params, if the constructor param is not an instance of the SubComponent or it's Builder.

### ISSUE THREAD

**Issue by mitcoding** [google/dagger#1528]
I've striped everything I could to show case the issue at hand. At it's most basic the pattern is the same as found in the official documentation here [https://dagger.dev/subcomponents#subcomponents-for-encapsulation](Subcomponents for encapsulation).

However I'm not using a Qualifer and I striped out the scoping to make sure it wasn't the scoping causing issues. 

The only other change is I did not want to break the Law of Demeter by passing in the injected Class that the component generates instead of the SubComponents Builder like the example shows or even an Instance of the SubComponent. The last two options generate the correct working code while the first Generates a DaggerComponent the has an infinite loop at run time.

Here are screen shots of files updated to pass the injected Class instance vs an instance of the SubComponent. the Left side of the compare shows the component instance version of the code and the right hand side shows the Class instance version of the code.

**The main Class:**
![Channel java](https://user-images.githubusercontent.com/13936104/59470863-04933580-8dee-11e9-852a-d90b046234a0.png)

**The SubComponent Module for injecting either an instance of the SubComponent into the Main Class Constructor or Injecting An instance of the class created by the SubComponent.**
![DatabaseConnectionSubcomponentModule java](https://user-images.githubusercontent.com/13936104/59470864-04933580-8dee-11e9-8cf7-935803c4695c.png)

**The Generated Class after the annotation processor runs comparing the code (the right hand side shows the Inifinate loop code caused by Injecting an instance of the class created by the SubComponent).**
![DaggerChannelApi java](https://user-images.githubusercontent.com/13936104/59470872-0b21ad00-8dee-11e9-8485-2633842577bb.png)

**The Complete Source Code.**
[daggerBug.zip](https://github.com/google/dagger/files/3288270/daggerBug.zip)

The Generated Code seen in the Screenshots is from Eclipse using the m2e plugin as the project is a maven project that deploys to google app engine. I'm using Dagger 2.23.1

**Comment by ronshapiro** [comment]
This appears to be a question - please use StackOverflow instead, as that is a better forum for questions.

**Comment by mitcoding** [comment]
@ronshapiro This is not a StackOverflow Question. This is a Bug because Dagger is generating Code that infinitely loops only if Sub-components are used and you don't inject the Subcomponent's builder or the class with the subcontinent annotation. I even included the exact steps needed to reproduce the bug.
