### ISSUE TITLE
kapt IllegalArgumentException Module does not define an element subcomponents()

### ISSUE THREAD

**Issue by aelmasry-grubbrr** [google/dagger#1531]
e: [kapt] An exception occurred: java.lang.IllegalArgumentException: @dagger.Module does not define an element subcomponents()
[build.gradle.txt](https://github.com/google/dagger/files/3307925/build.gradle.txt)

I dont know why it keeps throwing this error. Please help!

**Comment by ronshapiro** [comment]
This appears to be a question - please use StackOverflow instead, as that is a better forum for questions.
