### ISSUE TITLE
the dagger2 component file unable to display owner

### ISSUE THREAD

**Issue by c1105590204** [google/dagger#1543]
I use dagger2 for my android project,but it created component file(eg. DaggerDataPickComponent$com_jess_arms_di_component_AppComponent_gson.class) unable to display owner on windows system.These files cannot be deleted.log:
```
E:\project\XXmodule\build\generated\source\apt\debug\com\test\XXmodule\di\component\DaggerDataPickComponent.java:122: 错误: 写入com_jess_arms_di_component_AppComponent_gson时出错: E:\project\XXmodule\build\intermediates\javac\debug\compileDebugJavaWithJavac\classes\com\test\XXmodule\di\component\DaggerDataPickComponent$com_jess_arms_di_component_AppComponent_gson.class (拒绝访问。)
  private static class com_jess_arms_di_component_AppComponent_gson implements Provider<Gson> {
                 ^
```
what shall i do ?think's

**Comment by ronshapiro** [comment]
Are you able to create a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) that exhibits this behavior?

**Comment by c1105590204** [comment]
> Are you able to create a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) that exhibits this behavior?

Thank you
I changed my workspace and solved the problem!
