### ISSUE TITLE
dagger.android @inject Application

### ISSUE THREAD

**Issue by thegarlynch** [google/dagger#1545]
please add ability to do `@Inject Application`
inferred from `@Inject MyApplication`
after doing : 
`DaggerApplicationComponent.factory().create(this).inject(this);`

**Comment by JakeWharton** [comment]
Use a `@Binds`?

**Comment by thegarlynch** [comment]
yeah. already did that. but it feels hacky

**Comment by JakeWharton** [comment]
Why?

You can also change the factory argument type to `Application`.
