### ISSUE TITLE
Dagger component: error: cannot find symbol kotlin classes

### ISSUE THREAD

**Issue by ashraf-atef** [google/dagger#1549]
Generated component of dagger couldn't find symbol of the kotlin classes even if there is no read lines on this component

**When I convert the code to java, it runs successfully and this issue only happens in windows. It doesn't appear in mac or linix.**

Task :app:compileStagingDebugJavaWithJavac FAILED

\app\build\generated\source\kapt\stagingDebug...\DaggerAppComponent.java:49: error: cannot find symbol import com...features.Main.splash_screen.SplashActivity; ^ symbol: class SplashActivity location: package com...features.Main.splash_screen

`
@Module
abstract class SplashModule {
    @Binds
    abstract fun provideISplash(splashActivity: SplashActivity): ISplashScreen
}

class SplashActivity : BaseActivity<SplashScreenPresenter>(), ISplashScreen {

    @Inject
    lateinit var splashScreenPresenter: SplashScreenPresenter

    override fun gotoMainScreen() {
        Navigator.goToMainScreen(context)
    }

    override fun onCreateInit(savedInstanceState: Bundle?) {

    }

    override fun getLayout(): Int = R.layout.activity_splash

    override fun initPresenter(): SplashScreenPresenter = splashScreenPresenter
}

class SplashScreenPresenter @Inject constructor(view: ISplashScreen,
                                                environment: PresenterEnvironment)
    : BasePresenter<ISplashScreen>(view, environment) {

    @SuppressLint("CheckResult")
    override fun startLogic(savedInstance: Bundle?) {
        super.startLogic(savedInstance)
        Completable.timer(3, TimeUnit.SECONDS)
                .compose(getDestroyIoTransformer<Unit>())
                .subscribe { view.gotoMainScreen() }
    }
}

@Module
abstract class ActivityBuilder {
    @ContributesAndroidInjector(modules = [SplashModule::class])
    abstract fun contributeSplashActivity(): SplashActivity
}

//Gradle
apply plugin: 'com.android.library'
apply plugin: 'kotlin-platform-android'
apply plugin: 'kotlin-kapt'
apply plugin: 'kotlin-android'

 kapt {
        correctErrorTypes = true
        generateStubs = true
}

implementation "com.google.dagger:dagger:2.23.1"
implementation "com.google.dagger:dagger-android-support:2.23.1"
kapt "com.google.dagger:dagger-compiler:2.23.1"
kapt "com.google.dagger:dagger-android-processor:2.23.1"
`
[build output.txt](https://github.com/google/dagger/files/3374254/build.output.txt)

**Comment by ronshapiro** [comment]
This appears to be a question - please use StackOverflow instead, as that is a better forum for questions.

**Comment by ashraf-atef** [comment]
@ronshapiro I asked the problem on StackOverflow and no one answer me. This is the [link](https://stackoverflow.com/questions/56955853/dagger-component-error-cannot-find-symbol-kotlin-classes) of the question, could you please help me?
