### ISSUE TITLE
kapt fails with Cannot find Symbol

### ISSUE THREAD

**Issue by ashraf-atef** [google/dagger#1558]
Generated component of dagger under kapt path couldn't find symbol of the kotlin classes even if there is no read lines on this component.

**When I type these kotlin classes in java the code compiles successfully. when I run the same code in linix or mac, the code compiles successfully. I tried many devices using windows and the same Issue appears.**

I posted this question on [StackOvserflow ](https://stackoverflow.com/questions/56955853/dagger-component-error-cannot-find-symbol-kotlin-classes) as you told me in the last [issue ](https://github.com/google/dagger/issues/1549) but unfortunately with no solution.

Please If you don't see that as an issue please answer me on StackOverflow.

Android Studio 3.4.1
Build #AI-183.6156.11.34.5522156, built on May 1, 2019
JRE: 1.8.0_152-release-1343-b01 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

### App Gradle
```gradle
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'
apply plugin: 'kotlin-platform-android'
apply plugin: 'kotlin-kapt'

android {
 sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }
 kapt {
        correctErrorTypes = true
        generateStubs = true
    }

 dependencies {
        implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
        implementation "com.google.dagger:2.23.2"
        implementation "com.google.dagger:dagger-android-support:2.23.2"
        kapt "com.google.dagger:dagger-compiler:2.23.2"
        kapt "com.google.dagger:dagger-android-processor:2.23.2"
}
```

### Project Gradle
```gradle
buildscript {
    ext.kotlin_version = '1.3.41'
    dependencies {
        classpath 'com.android.tools.build:gradle:3.4.1'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}
```

```kotlin
@module
abstract class SplashModule {
@BINDS
abstract fun provideISplash(splashActivity: SplashActivity): ISplashScreen
}


class SplashActivity : BaseActivity(), ISplashScreen {
@Inject
lateinit var splashScreenPresenter: SplashScreenPresenter

override fun gotoMainScreen() {
    Navigator.goToMainScreen(context)
}

override fun onCreateInit(savedInstanceState: Bundle?) {

}
override fun getLayout(): Int = R.layout.activity_splash

override fun initPresenter(): SplashScreenPresenter = splashScreenPresenter
}


class SplashScreenPresenter @Inject constructor(view: ISplashScreen,
environment: PresenterEnvironment)
: BasePresenter(view, environment) {

@SuppressLint("CheckResult")
override fun startLogic(savedInstance: Bundle?) {
    super.startLogic(savedInstance)
    Completable.timer(3, TimeUnit.SECONDS)
            .compose(getDestroyIoTransformer<Unit>())
            .subscribe { view.gotoMainScreen() }
}
}


@module
abstract class ActivityBuilder {
@ContributesAndroidInjector(modules = [SplashModule::class])
abstract fun contributeSplashActivity(): SplashActivity
}
```

**Comment by safwanzameen10** [comment]
Hi, have you found solution to this problem ?

**Comment by danysantiago** [comment]
Can you provide us with a [reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)? If this is only an issue in Windows then it might be related to the Kotlin compiler (or kapt and the way it discovers newly generated sources) so it might be best if you report this issue to the [Kotlin](https://github.com/JetBrains/kotlin) project.
