### ISSUE TITLE
Typo in the tutorial

### ISSUE THREAD

**Issue by grivos** [google/dagger#1559]
Found a typo in the [8th chapter](https://dagger.dev/tutorial/08-user-specific-types).
Inside the class `LoginCommand` there's a method called `handleInput` which receives a `String` called `input`, but the method implementation references a variable called `username` which isn't defined.
(I'm not sure that this is the place to report issues in the dagger.dev website, but I haven't found an alternative)

**Comment by Chang-Eric** [comment]
Looks like this was fixed in https://github.com/google/dagger/commit/b0a4613e9cba2403246bd55a68ff05d62f04b01c
