### ISSUE TITLE
kapt generates different files for MapKey 

### ISSUE THREAD

**Issue by waqas117** [google/dagger#1562]
This works great with no issue 
`@Inject
   public ViewModelFactory(Map< Class<? extends ViewModel>, Provider<ViewModel>> viewModelMap){
        this.viewModelMap = viewModelMap;
    }`

But when I used same class in kotlin 
`@Inject
constructor(private val viewModelMap: Map<Class<out ViewModel>, Provider<ViewModel>>)`

Dagger generates this error 

`error: [Dagger/MissingBinding] java.util.Map<java.lang.Class<? extends androidx.lifecycle.ViewModel>,   ? extends javax.inject.Provider<androidx.lifecycle.ViewModel>>  cannot be provided without an @Provides-annotated method.`

Please see this I couldn't understand it. I this this is an issue.

**? extends javax.inject.Provider<androidx.lifecycle.ViewModel>**

**Comment by tbroyer** [comment]
Use `@JvmSuppressWildcards`; see #900

**Comment by Chang-Eric** [comment]
Closing this as @JvmSuppressWildcards is correct. Please feel free to reopen if not the case though.
