### ISSUE TITLE
dagger-gRPC doesn't work with Kotlin

### ISSUE THREAD

**Issue by asarkar** [google/dagger#1573]
The (somewhat vague) [instructions](https://dagger.dev/grpc/servers.html) for creating a gRPC server don't work with Kotlin; the annotation processor fails.
More specifically,
```
@Module
abstract class MyModule {
  @Binds
  abstract HelloServiceDefinition helloComponent(MyComponent myComponent);

  @Provides
  @ForGrpcService(HelloServiceGrpc.class)
  static List<? extends ServerInterceptor> helloInterceptors(
      AuthInterceptor authInterceptor,
      LoggingInterceptor loggingInterceptor) {
    return Arrays.asList(authInterceptor, loggingInterceptor);
  }
}
```

In Kotlin, `helloInterceptors` method goes to the `companion object` which is not recognized by the processor. I've also tried with a concrete module (not abstract) and using instance methods with `@Provides` instead of `@Binds` but no luck.

I've a working project [here](https://github.com/asarkar/kotlin/tree/master/grpc-learning) that uses Java for dagger-gRPC.

Kotlin version: 1.3.41
Dagger version: 2.24

**Comment by sessfeld** [comment]
Try to return `MutableList<out ServerInterceptor>`, I guess it has something to do with the way Kotlin deals with covariance.

```@Module
abstract class MyModule {
    @Binds
    abstract fun helloComponent(myComponent: MyComponent): HelloServiceDefinition

    @Module
    companion object {
        @JvmStatic
        @Provides
        @ForGrpcService(HelloServiceGrpc::class)
        fun helloInterceptors(
            authInterceptor: AuthInterceptor,
            loggingInterceptor: LoggingInterceptor
        ): MutableList<out ServerInterceptor> {
            return mutableListOf(authInterceptor, loggingInterceptor)
        }
    }
}

**Comment by ZacSweers** [comment]
@sessfeld I'm fairly certain you're hitting this issue: https://github.com/google/dagger/issues/900#issuecomment-337065004. Would suggest reading that thread and using the advice there for working around this
