### ISSUE TITLE
2.24 cannot inject AndroidInjector<Any> into Application class

### ISSUE THREAD

**Issue by autonomousapps** [google/dagger#1576]
AGP 3.4.2
Gradle 5.5.1
Kotlin 1.3.41
Dagger 2.24

The 2.24 release removes all the `Has{Activity,Fragment,Service,ContentProvider,BroadcastReceiver}` interfaces and replaces them with a single `HasAndroidInjector` interface. First, I don't think the docs have been updated to reflect this change. Second, I'm getting a compilation error attempting to migrate. I have the following now (simplified):

```kotlin
// MainApplication.kt
class MainApplication : MultiDexApplication(), HasAndroidInjector {

  @Inject lateinit var _androidInjector: AndroidInjector<Any>
  override fun androidInjector() = _androidInjector

  fun initDagger() {
    // Dagger cannot generate DaggerMainApplicationComponent
    mainApplicationComponent = DaggerMainApplicationComponent.builder()
      .app(this)
      .build()
    mainApplicationComponent.inject(this)
  }
}

// Also MainApplication.kt. Simplified.
@Singleton
@Component(modules = [
    AndroidInjectionModule::class
])
interface MainApplicationComponent {

    fun inject(app: MainApplication)

    @Component.Builder
    interface Builder {
        fun build(): MainApplicationComponent
        @BindsInstance fun app(app: Context): Builder
    }
}
```

The error is
```
> Task :app:kaptDebugKotlin
e: /Users/tony/workspace/myapp/app/build/tmp/kapt3/stubs/debug/com/myapp/MainApplicationComponent.java:8: error: [Dagger/MissingBinding] dagger.android.AndroidInjector<java.lang.Object> cannot be provided without an @Provides-annotated method.
public abstract interface MainApplicationComponent {
                ^
      dagger.android.AndroidInjector<java.lang.Object> is injected at
          com.myapp.MainApplication._androidInjector
      com.myapp.MainApplication is injected at
          com.myapp.MainApplicationComponent.inject(com.myapp.MainApplication)
```

The "identical" code from 2.23.x worked fine.

**Comment by Chang-Eric** [comment]
Thanks for letting us know about the docs, we should have updated those with this release. We will update those soon.

For your compilation problem, did you mean to inject DispatchingAndroidInjector instead of just AndroidInjector?

**Comment by autonomousapps** [comment]
Ah, that might indeed be the issue. Result of an intermediate refactoring
step. Will confirm later. Thanks.

**Comment by autonomousapps** [comment]
That was definitely the problem. Should I close this or re-scope it to the docs issue?

**Comment by Chang-Eric** [comment]
Great, glad to hear it worked. Re-scoping to the docs issue sounds good, but I actually just checked and it looks like at least the docs at https://dagger.dev/android have been updated. Do you know which docs are still out of date?

**Comment by autonomousapps** [comment]
That must have just happened, because when I checked early in the day yesterday, I still saw the old Has*Injectors. :) Will close issue. Thanks for being so responsive.

**Comment by Chang-Eric** [comment]
Cool, I think there may have just been a propagation delay in the release process. Thanks!
