### ISSUE TITLE
Annotations in generated code causes an extra annotation processing round

### ISSUE THREAD

**Issue by cesar1000** [google/dagger#1580]
Dagger uses the `Generated`, `SuppressWarnings` and `Override` annotations in generated code, which causes an extra round of annotation processing:

```
Round 1:
...
Round 2:
...
Round 3:
        input files: {com.twitter.test.di.app.DaggerApplicationTestObjectGraph$Scythe$Component}
        annotations: [javax.annotation.Generated, java.lang.SuppressWarnings, java.lang.Override]
        last round: false
Round 4:
        input files: {}
        annotations: []
        last round: true
```

Each round of processing does a full traversal of all trees and loads all referenced classes (and all classes in all visited packages!), which can add up to a lot of work in larger projects.

**Comment by ronshapiro** [comment]
Do you have any data to support this? javac caches a lot of this
information so I'd be a little surprised that this is causing a lot of
noticeable difference by this last round.

בתאריך יום ה׳, 1 באוג׳ 2019, 8:09, מאת Cesar Puerta ‏<
notifications@github.com>:

**Comment by cesar1000** [comment]
In our application module, I'm measuring 8.8s of processing time in Dagger's round, and 5.2s in this extra round.

**Comment by Chang-Eric** [comment]
It is unclear what the alternative is here though. Using @Generated is standard for generated code, not just Dagger, and not suppressing some warnings would create warning spam for users. This sounds like a more general problem for javac.
