### ISSUE TITLE
Scopes in multiple components

### ISSUE THREAD

**Issue by sockeqwe** [google/dagger#161]
Probably I missed something, but I thought Scopes like `@Singleton` are used to define "scoped lifecycles".

I have 1 Module:

```java
@Module public class MailModule {

  @Singleton @Provides public AccountManager providesAccountManager() {
    return new AccountManager();
  }

  @Singleton @Provides public MailProvider providesMailProvider(AccountManager accountManager) {
    return new MailProvider(accountManager);
  }
}
```

I have two different components with `@Singleton` scope:

```java
@Singleton
@Component(modules = MailModule.class)
public interface LoginComponent {

  public LoginPresenter presenter();
}


@Singleton
@Component(
    modules = MailModule.class
)
public interface MenuComponent {

  MenuPresenter presenter();

}
```
Both, `MenuPresenter` and `LoginPresenter`, have an @Inject constructor. While `MenuPresenter` expects `MailProvider` as parameter, `LoginPresenter` takes an `AccountManager`:
```java
  @Inject public MenuPresenter(MailProvider mailProvider) { ... }

  @Inject public LoginPresenter(AccountManager accountManager) { ... }
```
But every time I use the components to create a `MenuPresenter` or `LoginPresenter` I get a fresh new instance of `MailProvider` and `AccountManager`. I thought they were in the same scope and should therefore be kind of singleton (in the same scope).

Did I understand something completely wrong? Is that the desired behaviour? 

Or is the name `@Singleton` just misleading? At least in Dagger 1 it has produced real singletons

**Comment by deleet** [comment]
Ensure that you're not creating multiple instances of your `@Component` as `@Singleton` will produce a new presenter instance for each `@Component` instance.

**Comment by netdpb** [comment]
`@Singleton` means that the component will call the `@Provides` method only once _during the lifetime of that component instance._ If you create two components with the same module, each will call the method once. If you create two instances of the same component, each instance will call the method once.
