### ISSUE TITLE
dagger-spi 2.24 contains a self-reference in its dependencies. 

### ISSUE THREAD

**Issue by cgruber** [google/dagger#1611]
In the pom for dagger-spi, the following is found in the dependencies section:

```xml
<dependency>
  <groupId>com.google.dagger</groupId>
  <artifactId>dagger-spi</artifactId>
  <version>${project.version}</version>
</dependency>
```

**Comment by bcorso** [comment]
@cgruber, thanks for bringing this to our attention. 

I'm curious if you just happened to notice this, or if it manifested as some kind of breakage for you? Having a cyclic dependency with itself, I would have thought something would break, but I was able to setup an AndroidStudio app using a spi plugin with `com.google.dagger:dagger-spi:2.24` and no perceived issues.
