### ISSUE TITLE
error when rotate the phone

### ISSUE THREAD

**Issue by krongnang** [google/dagger#1618]
When the phone rotate,
App will crash with error : `lateinit property androidInjector has not been initialized`
I have inject component in activity and fragment by:
- In activity
`    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        AndroidInjection.inject(this)
        setContentView(R.layout.activity_non_tab)
        
    }`
- in Fragment
`    override fun onAttach(context: Context) {
        super.onAttach(context)
        AndroidSupportInjection.inject(this)
    }`

Logcat bellow.

![Image of Yaktocat](https://i.imgur.com/PQeHTSx.png)

**Comment by trevjonez** [comment]
your inject and super calls are out of order. give the android docs a closer look it is laid out there in a few places. https://dagger.dev/android

specifically under: When to inject

**Comment by krongnang** [comment]
> your inject and super calls are out of order. give the android docs a closer look it is laid out there in a few places. https://dagger.dev/android
> 
> specifically under: When to inject

yah, I got it. Thanks @trevjonez
