### ISSUE TITLE
Why can't I use Module Constructor Arguments with @BindsInstance-@Component.Builder is missing setters for required modules or components

### ISSUE THREAD

**Issue by saifi369** [google/dagger#1621]
I have a module for Diesel Engine
@Module
public class DieselEngineModule {
    private int mHorsePower;
    public DieselEngineModule(int horsePower) {
        this.mHorsePower = horsePower;
    }
    @Provides
    Engine provideDieselEngine(DieselEngine dieselEngine){
        return dieselEngine;
    }
    @Provides
    int provideHorsePower(){
        return mHorsePower;
    }
}
and another for Petrol Engine
@Module
public abstract class PetrolEngineModule {
    @Binds
    abstract Engine bindPetrolEngine(PetrolEngine petrolEngine);
}
I pass arguments to the Diesel engine module when I create component like, 
 DaggerCarComponent.builder().dieselEngineModule(new DieselEngineModule(300)).build();

But when I use @ComponenetBuilder for horse power, like this,

@Component(modules = {DieselEngineModule.class,WheelModule.class})
public interface CarComponent {
    Car getCar();
    void inject(MainActivity mainActivity);
    @Component.Builder
    interface Builder{
        @BindsInstance
        Builder horsePower(int horsePower);
        CarComponent build();
    }
}

It works fine for the Petrol Engine but for Diesel engine it gives this error
"@Component.Builder is missing setters for required modules or components: [com.dagger2basics.car.DieselEngineModule]"
How this is related to diesel engine. Why can't dagger use the Diesel engine module's constructor for Diesel engine's horse power and ComponentBuilder's value for Petrol engine?

**Comment by davidliu** [comment]
Simply put, because it can't. You're asking for it to somehow associate a horsepower integer to the DieselEngineModule, which is not a supported behavior.

**Comment by saifi369** [comment]
Ok. But how its connected to @BindsInstance. I mean why I have to remove constructor arguments if I want to use @BindsInstance?
