### ISSUE TITLE
HasAndroidInjector is annotated with @Beta

### ISSUE THREAD

**Issue by dvdmunckhof** [google/dagger#1622]
[Dagger 2.23](https://github.com/google/dagger/releases/tag/dagger-2.23) introduced `HasAndroidInjector`, stating it would soon replace the other `Has*Injector` interfaces. [Dagger 2.24](https://github.com/google/dagger/releases/tag/dagger-2.24) did remove those interfaces, in favor of `HasAndroidInjector`.

However, the `HasAndroidInjector` interface is still annotated with `@Beta`. According to the [documentation](https://github.com/google/dagger/blob/master/java/dagger/internal/Beta.java), that means it's _"subject to incompatible changes, or even removal, in a future release"_.

So either the stable `Has*Injector` interfaces were removed before a stable alternative was available, or it's a mistake and `HasAndroidInjector` is actually not in beta any more.

**Comment by JakeWharton** [comment]
The removed interfaces were also annotated as `@Beta`. They were not stable.

**Comment by dvdmunckhof** [comment]
Whoops, I made the wrong assumption they were stable, should've checked that...
