### ISSUE TITLE
kotlin未型变的类经过android studio make project后会变成形变的类

### ISSUE THREAD

**Issue by zhaolongqing** [google/dagger#1638]
我写了一个kt类如下:
class ViewModelProviderFactory @Inject
constructor(private val creators: Map<Class<out ViewModel>, Provider<ViewModel>>) :
    ViewModelProvider.Factory {

    override fun <T : ViewModel> create(modelClass: Class<T>) =
        (creators[modelClass]
            ?: creators.filterKeys { it.isAssignableFrom(modelClass) }.values.first()).get() as T
}
然后我点击android studio->build->make project后生成的java类如下:
```
public final class ViewModelProviderFactory_Factory implements Factory<ViewModelProviderFactory> {
  private final Provider<Map<Class<? extends ViewModel>, ? extends Provider<ViewModel>>>
      creatorsProvider;

  public ViewModelProviderFactory_Factory(
      Provider<Map<Class<? extends ViewModel>, ? extends Provider<ViewModel>>> creatorsProvider) {
    this.creatorsProvider = creatorsProvider;
  }

  @Override
  public ViewModelProviderFactory get() {
    return new ViewModelProviderFactory(creatorsProvider.get());
  }

  public static ViewModelProviderFactory_Factory create(
      Provider<Map<Class<? extends ViewModel>, ? extends Provider<ViewModel>>> creatorsProvider) {
    return new ViewModelProviderFactory_Factory(creatorsProvider);
  }

  public static ViewModelProviderFactory newInstance(
      Map<Class<? extends ViewModel>, ? extends Provider<ViewModel>> creators) {
    return new ViewModelProviderFactory(creators);
  }
}
```

以上出现了一个问题:我并没有让Provider进行任何型变操作,生成的java类意外地出现了? extexds.我想这是一个bug!因为当我试着用java写这段代码时并没生成? extends而且代码运行正常.所以这是一个bug!

**Comment by tbroyer** [comment]
You need to use `@JvmSuppressWildcard`; see https://github.com/google/dagger/issues/900#issuecomment-339663545

**Comment by zhaolongqing** [comment]
Thank you very much!
