### ISSUE TITLE
Documentation links don't work

### ISSUE THREAD

**Issue by ultraon** [google/dagger#164]
When i try to see documentation for different links:
- http://google.github.io/api/latest/dagger/Component.html;
- http://google.github.io/api/latest/dagger/Component.html#modules();
- http://google.github.io/api/latest/dagger/Subcomponent.html;
- http://google.github.io/api/latest/dagger/Component.html#component-relationships;

Server returns 404 error.

May be others links have the same issue.

**Comment by cgruber** [comment]
Where do those links occur?  These should be

http://google.github.io/dagger/api/latest/dagger/Component.html;
etc.

These links are missing /dagger/ in the beginning of the path.  Are these links somewhere in the docs?

**Comment by ultraon** [comment]
@cgruber There are on main dagger2 link http://google.github.io/dagger/

**Comment by tbroyer** [comment]
Specifically, the links at the bottom of `index.md` point to `/api/…` rather than `api/…` (like the ones in `_layouts/default.html`)
