### ISSUE TITLE
2.25 release notes points to the same commit twice

### ISSUE THREAD

**Issue by tfcporciuncula** [google/dagger#1640]
https://github.com/google/dagger/releases/tag/dagger-2.25

The two changes in the "Kotlin support" section are pointing to [this commit](https://github.com/google/dagger/commit/646e0336cdbe454baa5fe73c0af11f211a92deeb), but I believe the second one should be pointing to [this one](https://github.com/google/dagger/commit/0da21807f7353f077c5d17ab5ff59d8b0e59a963) instead.

**Comment by TWiStErRob** [comment]
@bcorso

**Comment by bcorso** [comment]
Thanks! We had to re-release so I've updated this in https://github.com/google/dagger/releases/tag/dagger-2.25.2
