### ISSUE TITLE
Kotlin object module provisions for primitive types are missing object INSTANCE in generated code

### ISSUE THREAD

**Issue by ZacSweers** [google/dagger#1648]
If I have a provision like below:

```kotlin
@Module
object MyModule {
  @Qualifier
  annotation class MyQualifier

  @MyQualifier
  @Provides
  fun provideMyBoolean(): Boolean {
    return false
  }
}
```

The resulting generated code should be accessing this provision via `MyModule.INSTANCE.provideMyBoolean()`, but `.INSTANCE` is missing and thus fails to compile.

Repro: https://github.com/ZacSweers/CatchUp/pull/195. Run `./gradlew :app:compileDebugJavaWithJavac`

**Comment by Chang-Eric** [comment]
Thanks for the report. It looks like this is actually an issue with our handling of primitive types.

**Comment by Chang-Eric** [comment]
Btw, a workaround for this is to leave @JvmStatic on just the providers of primitive types. This will be fixed in the next release.
