### ISSUE TITLE
Optionals fulfilled by subcomponents aren't used by AndroidInjectors

### ISSUE THREAD

**Issue by davidliu** [google/dagger#1649]
[Example project here.](https://github.com/davidliu/DaggerAndroidInjectors/tree/master/app/src/main/java/com/deviange/daggerandroidinjectors)

Basically I have an AppComponent, which has two `@ContributesAndroidInjector`, one for the activity, and one for the fragment, as well as a `@BindsOptionalOf`. This optional fulfilled within the `MainActivity.Module` and is ultimately injected into the GenericFragment.

However, when the GenericFragment is injected, only an `Optional.empty()` is received; the provision at the MainActivity is not used, even though the Activity is the one doing the injecting.

A workaround (and I suppose the intended way to do it) is to move the `@ContributesAndroidInjector` of the GenericFragment to the MainActivity; however, this adds to a lot boilerplate when this GenericFragment can be used in many different places. I'd like to be able to just declare the `@ContributesAndroidInjector` as early as possible, and then anyone can fill in the optional whenever it's available.

**Comment by Chang-Eric** [comment]
Yea, what you've said is the intended way to do it, and yes, I agree it can be annoying if you have a commonly used fragment. Though I think if you have a reusable FragmentModule that contains the @ContributesAndroidInjector you should be able to just include that in every activity?

**Comment by davidliu** [comment]
It's just sort of a PITA to include everywhere. Additionally, due to the way AndroidInjection is setup, there's no compile-time checking, so there's no way to ensure that the module is always set (which is a problem if it's a generic fragment that might not get specifically checked for by others on the team).

**Comment by Chang-Eric** [comment]
That's true. An alternative is you can have a single ActivityComponent that has inject methods for all of your activities. This doesn't work with @ContributesAndroidInjector but should work for using the AndroidInjection setup and manually provide into the map that DispatchingAndroidInjector uses (or use your own implementation of AndroidInjector). If you do end up going this route and using a monolithic activity and/or fragment component, you should make sure you use fastInit mode. https://dagger.dev/compiler-options

We do plan to address these issues with the new initiative that was announced at ADS2019, but unfortunately at the moment I don't have more I can add.
