### ISSUE TITLE
每次运行项目都需要clean一下 才能正常运行

### ISSUE THREAD

**Issue by Quenstin** [google/dagger#1658]
每次运行项目都需要clean一下 才能正常运行

**Comment by Chang-Eric** [comment]
From using Google Translate, I think you're asking about needing to clean your project to run normally? Can you elaborate? What files need to be cleaned and are causing problems?

**Comment by millie-mouse** [comment]
> From using Google Translate, I think you're asking about needing to clean your project to run normally? Can you elaborate? What files need to be cleaned and are causing problems?

maybe he need some help about English

**Comment by Quenstin** [comment]
Every time I finish writing code in the project, I want to run the project, but I cannot run the project directly. I need to click build->Clean project in Android studio to run the project, otherwise it will directly compile and report an error
The error information is as follows:
Program type already present: xxx.xxx.xxx.xxx.activity.newCache.CacheManageActivity2$1

**Comment by danysantiago** [comment]
Closing this for now as we don't have enough information to help.
Try creating a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) to better pin point the issue.
