### ISSUE TITLE
Frequent undetereministic build failures, works after clean

### ISSUE THREAD

**Issue by ursusursus** [google/dagger#1661]
Hi, Im running into this issue ofter for no apparent reason

```
C:\..........\di\InviteControllerComponent.java:12: error: [ComponentProcessor:MiscError] dagger.internal.codegen.ComponentProcessor was unable to process this interface because not all of its dependencies could be resolved. Check for compilation errors or a circular dependency with generated code.
public abstract interface InviteControllerComponent {
```
```
org.gradle.jvmargs=-Xmx1536m
org.gradle.parallel=true
kotlin.code.style=official
kotlin.parallel.tasks.in.project=true
kapt.include.compile.classpath=false
kapt.incremental.apt=true
kapt.use.worker.api=true

android.useAndroidX=true
android.enableJetifier=true

```
Its a multimodule project. Dagger 2.25.2

Is this a incremental apt/compilation thing? It works sometimes if I run build again, and work s everytime after clean build

**Comment by trevjonez** [comment]
I've seen similar issues in my build. I am thinking it is a kapt or Gradle issue. At least it feels like a race condition or bad invocation to me.

**Comment by bcorso** [comment]
Do you know if this is only an issue with Dagger 2.25.2, or have you seen it with previous versions of Dagger too?

**Comment by ursusursus** [comment]
Yes it was happening in previous versions too

I tried disabling the `kapt.incremental.apt=true` but still happens

**Comment by khang-tiki** [comment]
I have the same problem, it's likely because of **gradle build cache**. If I simply clean project, it still happen. Only fixed when I do `rm -rf $HOME/.gradle/caches/build-cache-*` or run gradle with `--rerun-tasks`.

**Comment by Chang-Eric** [comment]
I'm not sure there is a lot we can do without a clear repro case. I'm closing for now, but please comment if this continues being a problem.
