### ISSUE TITLE
Latest version 2.25.2 @Qualified annotation change , Doesn't work when dagger building for instrumentation tests

### ISSUE THREAD

**Issue by Anmol92verma** [google/dagger#1670]
@Qualified annotation in Kotlin properties doesn't work when used for androidTest

**Comment by danysantiago** [comment]
This is likely the same issue as #1659
 
Are you applying Dagger to your tests too via `androidTestAnnotationProcessor`?

**Comment by Anmol92verma** [comment]
Yes @danysantiago . Its the same. Fallback to field: worked for me too! 
Thanks for referencing the issue. 👍🏽
