### ISSUE TITLE
Dagger fails because of trying to access a private Class

### ISSUE THREAD

**Issue by tasomaniac** [google/dagger#1671]
Hi, 

I am having a really curious Dagger error shown below:

```

e: error: cannot access AppUpdateInfo
  class file for com.google.android.play.core.appupdate.AppUpdateInfo not found
  Consult the following stack trace for details.
  com.sun.tools.javac.code.Symbol$CompletionFailure: class file for com.google.android.play.core.appupdate.AppUpdateInfo not found
e: /Users/sdane/warehouse-companion/whc-app/src/main/java/com/wayfair/partners/whc/app/di/AppComponent.java:36: error: [ComponentProcessor:MiscError] dagger.internal.codegen.ComponentProcessor was unable to process this interface because not all of its dependencies could be resolved. Check for compilation errors or a circular dependency with generated code.
public interface AppComponent extends AndroidInjector<App> {
```

It claims that `AppUpdateInfo` is not found. This is because the dependency to Play Core library added as `implementation`. 

## Observations

- This class is only used in `AppUpdateChecker` which is provided via constructor injection but do not expose `AppUpdateInfo` class.

- `AppUpdateChecker` is bound into a multi-set injection.

```
    @Binds
    @IntoSet
    fun appUpdateChecker(appUpdateChecker: AppUpdateChecker): ActivityWorker
```

- When I made that dependency `api`, Dagger builds fine. **But** there is usage of `AppUpdateInfo` whatsoever in any of the Dagger generated classes.

**Comment by danysantiago** [comment]
My guess here is that the superficial validation done by the [`BasicAnnotationProcessor`](https://github.com/google/auto/blob/master/common/src/main/java/com/google/auto/common/BasicAnnotationProcessor.java) that Dagger's `ComponentProcessor` extends ends up finding a field or a method with a parameter of type `AppUpdateInfo` in your `AppUpdateChecker` and is unable to resolve the type it. The validation might be too aggressive for your construction injection case.

In a way this is related to #970

**Comment by tasomaniac** [comment]
Thanks. It looks similar and in fact I was watching that issue.

**Comment by Chang-Eric** [comment]
I'm going to close this since it looks like there's a related issue already mentioned above. In general too, I've created this issue https://github.com/google/dagger/issues/2208 for better handling of superficial validation, which should cover issues like this.
