### ISSUE TITLE
Android multi module project with different instances

### ISSUE THREAD

**Issue by brunoescalona** [google/dagger#1676]
Hi, 

This is not an issue but I posted on stackoverflow a question some days ago and I can't still find a solution for that. Maybe here you can guide me.

[Here](https://stackoverflow.com/questions/58750363/single-instance-for-different-scopes-with-dagger-2) you can find the issue with all the information and [here](https://github.com/brunoescalona/dagger-test) the example code.

Sorry for create an issue and thanks in advance for your help.

**Comment by danysantiago** [comment]
Looks like you answered your own SO question. Closing this issue now but feel free to comment if you had something more specific to ask.
