### ISSUE TITLE
fastInit not optimizing the elements in multibindings

### ISSUE THREAD

**Issue by chao2zhang** [google/dagger#1679]
👋 , I recently found that the fastInit does not optimize on multibindings. Below is an example:

Definition
```
@Component(modules = ViewModelModule.class)
interface ViewModelComponent {

    Map<String, Provider<ViewModel>> viewModelProviderMap();

    @Component.Factory
    interface Factory {
        ViewModelComponent newComponent(@BindsInstance String page);
    }
}

@Module
interface ViewModelModule {

    @Binds
    @IntoMap
    @StringKey("PlantList")
    ViewModel plantList(DummyViewModel plantListViewModel);
}
```

Generated the code
```
public final class DaggerViewModelComponent implements ViewModelComponent {
  private volatile Provider<DummyViewModel> dummyViewModelProvider; // Expect this to be Object dummyViewModelProvider = new MemoizedSentinel()
}
```

Since we are using quite a number of multibindings including `ViewModel`, `Fragment` etc, I believe using the MemoizedSentinel() in fastInit could reduce the app startup time even more.

**Comment by bcorso** [comment]
The difference between fastInit and non-fastInit here is not whether the provider is declared, but whether the provider is initialized lazily (i.e. when requesting the `#getDummyViewModelProvider()`) or eagerly (i.e. when initializing the component with `#initialize()`). For fastInit, it should be initialized lazily.

Or, let me know if there is some other optimization you were expecting?

(Note: MemizedSentinel is never used for providers. It's only used for scoped bindings where we use it as a synchronization lock)

**Comment by chao2zhang** [comment]
My understanding is that fastInit reduces the loading time of component initialization by preventing class loading. In this case, if `Provider<DummyViewModel>` is kept as the type of the field, would we need to load the class `DummyViewModel` when initializing the component?

**Comment by bcorso** [comment]
Yes, that's correct -- the parameter type is not class loaded because it is erased at runtime.
