### ISSUE TITLE
Could not find com.google.dagger:dagger-compiler:2.0-SNAPSHOT

### ISSUE THREAD

**Issue by gc986** [google/dagger#168]
Hello! My AndroidStudio can't find the dagger 2.0 (version 2.1 too). Logs:
>Error:Could not find com.google.dagger:dagger-compiler:2.0-SNAPSHOT.
>Searched in the following locations:
> https://jcenter.bintray.com/com/google/dagger/dagger-compiler/2.0-SNAPSHOT/maven-metadata.xml
> https://jcenter.bintray.com/com/google/dagger/dagger-compiler/2.0-SNAPSHOT/dagger-compiler-2.0-SNAPSHOT.pom
> https://jcenter.bintray.com/com/google/dagger/dagger-compiler/2.0-SNAPSHOT/dagger-compiler-2.0-SNAPSHOT.jar
> file:/home/cool/Android/Sdk/extras/android/m2repository/com/google/dagger/dagger-compiler/2.0-SNAPSHOT/maven-metadata.xml
> file:/home/cool/Android/Sdk/extras/android/m2repository/com/google/dagger/dagger-compiler/2.0-SNAPSHOT/dagger-compiler-2.0-SNAPSHOT.pom
> file:/home/cool/Android/Sdk/extras/android/m2repository/com/google/dagger/dagger-compiler/2.0-SNAPSHOT/dagger-compiler-2.0-SNAPSHOT.jar
> file:/home/cool/Android/Sdk/extras/google/m2repository/com/google/dagger/dagger-compiler/2.0-SNAPSHOT/maven-metadata.xml
> file:/home/cool/Android/Sdk/extras/google/m2repository/com/google/dagger/dagger-compiler/2.0-SNAPSHOT/dagger-compiler-2.0-SNAPSHOT.pom
> file:/home/cool/Android/Sdk/extras/google/m2repository/com/google/dagger/dagger-compiler/2.0-SNAPSHOT/dagger-compiler-2.0-SNAPSHOT.jar
>Required by:
> androidpass:app:unspecified

What to do?

**Comment by artem-zinnatullin** [comment]
> What to do?

Dagger 2.0 was released as stable version to Maven Central and should be mirrored fine via JCenter, so you can just switch to it:

```groovy
compile 'com.google.dagger:dagger:2.0' // not snapshot version
apt 'com.google.dagger:dagger-compiler:2.0' // not snapshot version
```

Also, now there is Dagger-2.1-SNAPSHOT, so if you want to use SNAPSHOT, make sure that you use SNAPSHOT of Dagger 2.1 from Maven Central, as far as I know, JCenter won't mirror snapshots from Maven Central (but I can be wrong)

**Comment by gc986** [comment]
Artem, thank you very much!

**Comment by tbroyer** [comment]
> Also, now there is Dagger-2.1-SNAPSHOT, so if you want to use SNAPSHOT, make sure that you use SNAPSHOT of Dagger 2.1 from Maven Central, as far as I know, JCenter won't mirror snapshots from Maven Central (but I can be wrong)

Technically speaking, snapshots are at Sonatype OSSRH [1], not Maven Central (Sonatype OSSRH is just one way to publish things to Central, and it also hosts snapshots)

[1] https://oss.sonatype.org/content/repositories/snapshots/

**Comment by artem-zinnatullin** [comment]
@tbroyer yep, you are right, thanks for addition

@gc986 I think you can close this issue if it's resolved
