### ISSUE TITLE
Component with more than 255 modules leads to compile error in generated component implementation

### ISSUE THREAD

**Issue by gfasser** [google/dagger#1680]
Our project contains a single component with more than 300 modules. Since dagger 2.21 all modules are listed as a method parameter in the generated component implementation, see https://github.com/google/dagger/commit/59a65353 : 

> Change component constructors and initialization methods to no longer take a single Builder argument when a Builder for the component is present, but rather to take all of their requirements as parameters in all cases.

If the component contains more than 255 modules the class no longer compiles, because a single method would need to have more than 255 parameters - which is not possible because of JVM limitations.

```
DaggerAppComponent.java:3065: error: too many parameters
public final class DaggerAppComponent implements AppComponent {
             ^
DaggerAppComponent.java:6391: error: too many parameters
  private DaggerAppComponent(AppAndroidModule appAndroidModuleParam,
          ^
DaggerAppComponent.java:6758: error: too many parameters
  private void initialize(final AppAndroidModule appAndroidModuleParam,
               ^
```

We are currently splitting the mentioned component into subcomponents to work around this issue and to profit from the advantages of having multiple components instead of the single one.

Maybe the issue should still be fixed in dagger? Or the dagger documentation / javadoc should mention this limit somewhere.

**Comment by JakeWharton** [comment]
Do all of your modules require instances (i.e., do they use instance-based `@Provider` methods)? If you switch those which are stateless to use `static` methods it should reduce the count as Dagger no longer needs to pass around instances and can reference the methods statically.

**Comment by gfasser** [comment]
Yes, good point! Currently almost all of our modules still use instance-based `@Provider` methods, without an actual need for those instances. I'll start working on those modules - thanks for the hint!

**Comment by Kurdenes21** [comment]
@JakeWharton 4 hi

**Comment by Kurdenes21** [comment]
Hi
