### ISSUE TITLE
ViewModel injection 

### ISSUE THREAD

**Issue by MSex** [google/dagger#1682]
Hi, we are working on an android project with MVVM architeture 
using `dagger.android` for DI and `androidx.lifecycle.ViewModel` to preserve data when an Activity is destroyed and a new one is constructed on a configuration change (such as screen orientation change).

We would like to use dagger to inject the dependencies of both our Activities and our ViewModels. 
For example if we have the following code:

```java
public class Activity extends AppCompatActivity {
    @Inject ListAdapter listAdapter;

    ...
}

class ListAdapter extends RecyclerView.Adapter<ViewHolder> {
    private ItemList itemList;

    @Inject
    ListAdapter(ItemList itemList) {
        this.itemList = itemList;
    }

    ...
}

public class ViewModel extends androidx.lifecycle.ViewModel {
    @Inject ItemList ItemList;

    ...
}

public class ItemList {

    @Inject
    public ItemList() {}

    ...
}
```

In this example we need:
- Build and inject `ListAdapter` into `Activity` each time an new instance of `Activity` is created.
- Inject `ItemList` into `ListAdapter` and into `ViewModel`. The `ItemList` instance injected in both should be 
the same and should survive the activity in case of a configuration change.

The usual way to solve this would be injecting the `Activity` dependencies using an subcomponent create with `@ContributesAndroidInjector` and 
and calling `AndroidInjection.inject(this)` on the `onCreate()` method of the activity. If we add an @ActivityScope scope we could make that only one 
instance of `ItemList` would be created by the component.
The problem with this approach is that a new injector is created every time a new instance of `Activity` is created and so we could not use 
a scope to preserve the `ItemList` instance across a configuration change.

Our solution was to create a scope between `@Singleton` and `@ActivityScope` we called it `@ViewModelScope`.
To do so we made the ActivitySubcompoent a subcomponent of a ViewModelSubcompoent.    

We ended up with something like:

```java 
public class Activity extends AppCompatActivity {
    ViewModel viewModel;
    @Inject ListAdapter listAdapter;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        viewModel = ViewModel.getInstance(this);
        viewModel.androidInjector().inject(this);
        ...
    }
}

public class ViewModel extends androidx.lifecycle.ViewModel implements HasAndroidInjector {
    @Inject DispatchingAndroidInjector<Object> androidInjector;
    @Inject ItemList ItemList;

    public static ViewModel getInstance(Activity activity) {
        ViewModel viewModel = ViewModelProviders.of(activity).get(ViewModel.class);
        if (viewModel.androidInjector() == null) {
            ((HasAndroidInjector) activity.getApplication()).androidInjector().inject(viewModel);
        }

        return viewModel;
    }
    ...
}

@Module
public abstract class ActivityModule {
    @ContributesAndroidInjector
    @ActivityScope
    abstract Activity bindGroupListActivity();
}

@Module
public abstract class ViewModelModule {
    @ContributesAndroidInjector(modules = {ActivityModule.class})
    @ViewModelScope
    abstract ViewModel bindViewModel();
}
```

This solution seems to work just fine and we think it could be incorporated in some way into `dagger.android`.
Do you have any thoughts on that?

**Comment by pstuempke** [comment]
This is definitely something that is missing. There would have to be a way to use constructor injection the ViewModel though.

**Comment by danysantiago** [comment]
Cleaning up a bit the issues so duping this with https://github.com/google/dagger/issues/1271 since it is asking almost for the same. We are working on making ViewModel injection easier in Dagger.
