### ISSUE TITLE
Incremental annotation processing does not recompile components that reference other modules

### ISSUE THREAD

**Issue by matejdro** [google/dagger#1684]
Not sure if this is Dagger's issue or Kotlin's issue:

1. Download 
[dagger_multimodule_incremental.zip](https://github.com/google/dagger/files/3910986/dagger_multimodule_incremental.zip)
2. Compile (`./gradlew assemble`)
3. Open `other_module/src/main/kotlin/TestClass.kt` and add anything to its constructor (for example `number: Int`)
4. Recompile  (`./gradlew assemble`)

Second compilation will fail. complaining that generated DaggerMainComponent does not reference new constructor:

```
build\generated\source\kapt\main\DaggerMainComponent.java:26: error: constructor TestClass in class TestClass cannot be applied to given types;
    return new TestClass();}
           ^
  required: int
  found: no arguments
  reason: actual and formal argument lists differ in length
1 error
```

This is with Dagger 2.25.2 and Kotlin 1.3.60

**Comment by danysantiago** [comment]
I was not able to reproduce this. =/
I get the expected missing binding error:
```
> Task :kaptKotlin FAILED
e: /usr/local/google/home/danysantiago/Downloads/dagger_multimodule_incremental/build/tmp/kapt3/stubs/main/MainComponent.java:6: error: [Dagger/MissingBinding] java.lang.Integer cannot be provided without an @Inject constructor or an @Provides-annotated method.
public abstract interface MainComponent {
                ^
      java.lang.Integer is injected at
          TestClass(number)
      TestClass is provided at
          MainComponent.provideTestClass()

FAILURE: Build failed with an exception.
```

Even when adding a `@Module` that provides the `Int`, cleaning and then following the steps:
1. `./gradlew assemble`
2. Add `number: Int` to `TestClass.kt`
3. `./gradlew assemble`

I still get a successful build.

One version that could be different between our setup is the JDK, I tried on JDK11.

**Comment by matejdro** [comment]
Huh I did more tests and it appears that problem can only be reproduced with specific build increment (I stripped `build` folders in previous zip file) and when project is in specific folder (presumably kapt stores absolute paths in its cache files).

Here is the zip file with `build` included, but I'm not sure if it is of any help to you since paths do not match: [dagger_multimodule_incremental_with_build_folder.zip](https://github.com/google/dagger/files/3915673/dagger_multimodule_incremental_with_build_folder.zip)

I assume this identifies it as kapt issue, not dagger issue? Posting to kapt source tracker will probably help.

**Comment by gavra0** [comment]
This seems to be an issue with Kotlin incremental compilation, as `TestClass.kt` from the repro project has no-args `<init>` and `TestClass.class` from the attached zip contains `<init>` that requires `java/lang/Number` as parameter. We are discussing this further at https://youtrack.jetbrains.com/issue/KT-35236.
