### ISSUE TITLE
DaggerFragment doesn't find its own FragmentInjector

### ISSUE THREAD

**Issue by agiro8747** [google/dagger#1685]
**Dagger version: 2.17**

I have a `ViewPager` with fragments in it. I call these in an activity. 
The problem is that the fragment fails with `No injector was found for com.package.MyFragment` even though the fragment itself is a subclass of `DaggerFragment`. 
I took a look at the source code and found this:
_from `AndroidSupportInjection`, line 77_

```
private static HasSupportFragmentInjector findHasFragmentInjector(Fragment fragment) {
    Fragment parentFragment = fragment;
    while ((parentFragment = parentFragment.getParentFragment()) != null) {
      if (parentFragment instanceof HasSupportFragmentInjector) {
        return (HasSupportFragmentInjector) parentFragment;
      }
    }
   ...
 }
```

Unsure if this is intentional but in the line with `while` `parentFragment` gets overwritten instantly, without using its original value (the fragment itself) so it doesn't find its own injector. 

Please take a look at this as I might be wrong but this could be a bug.

**Comment by danysantiago** [comment]
The injector for a top level fragment is the activity. Make sure your activity extends `DaggerActivity` or that it implements `HasAndroidInjector`.

**Comment by agiro8747** [comment]
Thanks for getting back to me. Yes, that is how I solved the issue. My remark is, why isn't the DaggerFragment's own injector good for it? Why does it start from its parent fragment skipping itself (even though it has an injector)?

**Comment by danysantiago** [comment]
Injectors are located in parent objects because they have a longer lifecycle. A Fragment's injector is good for injecting child fragments, meanwhile an Activity's injector is good for the Activity Fragments. To have scoped bindings shared across fragment instances the bindings needs to be in a component whose life is longer than the fragment, and that is the Activity, or the Application.
