### ISSUE TITLE
Minor correction for the Dagger tutorial

### ISSUE THREAD

**Issue by tVishal96** [google/dagger#1689]
Hi! I'm very new to this, so feel free to close this if it's in the wrong place (or if it's just incorrect).

I found a minor mistake on [this](https://dagger.dev/tutorial/04-depending-on-interface) page in the tutorial at [dagger.dev](dagger.dev).

### This is the incorrect text. (It's close to the end of the page)
And in the case of `HelloWorldModule`, it’s the parameter type of the `@Binds` method we just wrote.

### This is what I believe the correct text should be.
And in the case of **HelloWorldCommand**, it’s the parameter type of the `@Binds` method we just wrote.

Thanks for taking the time to look into this. 😄

**Comment by bcorso** [comment]
Looks like it's been fixed now.
