### ISSUE TITLE
KeyCreator not imported

### ISSUE THREAD

**Issue by gurinderu** [google/dagger#169]
When I use @Provides with map type. Dagger generate valid factory class,but without importing of generated KeyCreator class.

**Comment by gurinderu** [comment]
Also if build some objects with
@MapKey(unwrapValue = false)
@Target(value = ElementType.METHOD)
@Retention(RetentionPolicy.RUNTIME)
public @interface ClassKey {
    Class<?> value();
}

Dagger generate not valid 

    this.mapOfClassKeyAndProviderOfObjectProvider = MapProviderFactory.<ClassKey, Object>builder(2)
        .put(ClassKeyCreator.create(TestClass1), mapOfClassKeyAndProviderOfObjectContribution1)
        .put(ClassKeyCreator.create(TestClass2), mapOfClassKeyAndProviderOfObjectContribution2)
        .build();

You can see that in create method must be TestClass1.class and TestClass2.class

**Comment by gk5885** [comment]
@netdpb fixed this and is correct in 2.0.2.
