### ISSUE TITLE
error: A @Module may not contain both non-static and abstract binding methods

### ISSUE THREAD

**Issue by Zhuinden** [google/dagger#1691]
I have the following mess:

``` kotlin
@Module
abstract class MyModule {
    @PerScreen
    @ContributesAndroidInjector
    abstract fun fragment(): MyFragmentImpl

    @Binds
    @IntoMap
    @ClassKey(MyScreen::class)
    abstract fun viewModel(viewModel: MyViewModel): ViewModel

    @Provides
    @IntoMap
    @ClassKey(MyScreen::class)
    fun fragmentBuilder(): FragmentBuilder<*, *> = MyFragmentImpl.builder()
}
```

I get the following error:

**error: A `@Module` may not contain both non-static and abstract binding methods**

Clearly, the issue is having both `@Binds` and `@Provides` in the same class.

-----

I had to replace it with

``` kotlin
@Module(includes = [MyFragmentBuilderModule::class])
abstract class MyModule {
    @PerScreen
    @ContributesAndroidInjector
    abstract fun fragment(): MyFragmentImpl

    @Binds
    @IntoMap
    @ClassKey(MyScreen::class)
    abstract fun viewModel(viewModel: MyViewModel): ViewModel
}

@Module
internal class MyFragmentBuilderModule {
    @Provides
    @IntoMap
    @ClassKey(MyScreen::class)
    fun fragmentBuilder(): FragmentBuilder<*, *> = MyFragmentImpl.builder()
}
```

I feel that as `fun fragmentBuilder()` is `public`, therefore Dagger should be able to inherit that method, without me having to declare two modules instead of 1.

This limitation feels like something that Dagger *should* be able to support. 

-----------------

Though maybe I just need to add a `companion object` and a `@JvmStatic`, I'll look into that.

EDIT: That gives me

**`@Provides` methods can only be present within a `@Module` or `@ProducerModule`**

because the `companion object` is not a `@Module`. I guess that settles it.

**Comment by JakeWharton** [comment]
> Dagger should be able to inherit that method

`abstract` modules are not subclassed by Dagger. `abstract` provision methods are read at compile-time and then completely ignored at runtime. Conversely, `static` provision methods are able to be invoked without an instance of the module.

A non-`static`, non-`abstract` provision method cannot be invoked by Dagger at runtime because there is not only no instance, but there is no subclass that can be instantiated.

**Comment by Zhuinden** [comment]
Hmm, I guess that explains it.

I guess the best thing I can come up with in that case is

``` kotlin

@Module(includes = [MyFragmentBuilderModule::class])
abstract class MyModule {
    @PerScreen
    @ContributesAndroidInjector
    abstract fun fragment(): MyFragmentImpl

    @Binds
    @IntoMap
    @MapKey(MyScreen::class)
    abstract fun viewModel(viewModel: MyViewModel): ViewModel
}

@Module
internal object MyFragmentBuilderModule {
    @Provides
    @IntoMap
    @MapKey(MyScreen::class)
    @JvmStatic
    fun fragmentBuilder(): FragmentBuilder<*, *> = MyFragmentImpl.builder()
}
``` 

Not ideal, would have preferred to make the definitions in one module, but I'll have to accept it for now, then.

The plan is to kill these `Impl.builder()`s anyway.

**Comment by TWiStErRob** [comment]
For future readers: since [Dagger 2.26](https://github.com/google/dagger/releases/tag/dagger-2.26) companion objects have even better syntax (see #1646), so the code in OP becomes:

```kotlin
@Module
abstract class MyModule {
    @PerScreen
    @ContributesAndroidInjector
    abstract fun fragment(): MyFragmentImpl

    @Binds
    @IntoMap
    @ClassKey(MyScreen::class)
    abstract fun viewModel(viewModel: MyViewModel): ViewModel

    companion object { // added line
    @Provides
    @IntoMap
    @ClassKey(MyScreen::class)
    fun fragmentBuilder(): FragmentBuilder<*, *> = MyFragmentImpl.builder()
    }  // added line
}
```
