### ISSUE TITLE
Dagger issue when adding annotationProcessor “androidx.room:room-compiler:2.2.0”

### ISSUE THREAD

**Issue by rgdzh1** [google/dagger#1692]
Same question:
[https://stackoverflow.com/questions/53762070/dagger-issue-when-adding-annotationprocessor-android-arch-persistence-roomcomp](url)

Module Gradle configuration:

    api 'com.google.dagger:dagger:2.25.2'
    annotationProcessor 'com.google.dagger:dagger-compiler:2.25.2'
    api 'com.google.dagger:dagger-android:2.25.2'
    api 'com.google.dagger:dagger-android-support:2.25.2' 
    annotationProcessor 'com.google.dagger:dagger-android-processor:2.25.2'
    implementation "androidx.room:room-runtime:2.2.0"
    annotationProcessor "androidx.room:room-compiler:2.2.0"
    implementation "androidx.room:room-rxjava2:2.2.0"
    implementation 'com.github.bumptech.glide:glide:4.10.0'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.10.0'

Root Gradle configuration:

    dependencies {
        classpath 'com.android.tools.build:gradle:3.4.2'
    }

Compile installation error:
[ComponentProcessor:MiscError] dagger.internal.codegen.ComponentProcessor was unable to process this interface because not all of its dependencies could be resolved. Check for compilation errors or a circular dependency with generated code.

**Comment by danysantiago** [comment]
I think the SO link is broken. =/
Do you have a sample app that reproduces this issue?

**Comment by danysantiago** [comment]
Closing for now, please feel free to re-open if you can gather more information.
