### ISSUE TITLE
Qualifier for @Inject constructor

### ISSUE THREAD

**Issue by matejdro** [google/dagger#1697]
Just wondering, why are qualifier annotations forbidden on `@Inject` constructor?

I am using [simple-stack](https://github.com/Zhuinden/simple-stack) in my last Android app. Among other things, library allows easy scoping of various service classes per group of screens (using this with pure dagger would require creating subcomponent for every screen which is very boilerplate-y). Long story short, developer provides the library with service factory that contains `createService(key)` method. Then whenever scope of the specific screen becomes active, library creates all required services via that factory. Developer can then call `getService(key)` whenever screen with that service is active to retrieve it.

I am currently implementing it like this:

1. Every service class has `@Inject constructor`.
2. Service factory is created via multibinds that map keys of all services to their providers
3. Every service has provider method that retrieves the service via `getService(key)` method. That allows services to be directly injected into screens via dagger without manual `getService` calls. However, since this service type would now be injected twice, I had to add separate `@ScopedService` qualifier annotation to avoid conflicts.

All of this means that all services that screen needs have to be injected with `@ScopedService` qualifier to receive the scoped version. If developer makes a mistake and forgets the annotation, unscoped version from constructor injector will be used instead. At first glance, this version will work fine until user switches to dfferent screen where this unscoped service will be garbage collected, loosing all its data.

Solution to that seems simple, just slap another qualifier annotation onto `@Inject` constructor that will prevent developer from accidentally injecting it. However, this does not appear to be possible (dagger errors out when adding qualifier to inject constructor).

**Comment by Chang-Eric** [comment]
Can you clarify, is this a case where `@ScopedService` in the example is multiple qualifiers, or is there only one qualifier literally named that? You can add a scope annotation to the `@Inject` type if that is helpful. I couldn't quite tell if you were adding the qualifier just to also add a scoping annotation.

The main reason I don't think this has been done is that if you have a qualifier on the `@Inject` type then you still only have one binding, so it isn't clear that it would really be that functionally different from leaving the qualifier off. The only aspect I can think of that is changed is if you were trying to use the qualifier to protect the binding's visibility while leaving the `@Inject` type public. Usually in these cases I think it may be better to just use an interface/impl split so the impl can be private and `@Inject` and the interface can be public.

There's also a cost here that adding support for this in Dagger would diverge from Guice (and maybe other JSR330 injectors) so it could have deeper implications on projects that do Dagger/Guice interop.

**Comment by matejdro** [comment]
I implemented example here: https://github.com/matejdro/simple-stack-dagger-scoping-sample.

If you remove `@ScopedService` annotation from `app/src/main/java/com/matejdro/simple_stack_dagger_demo/features/words/WordListFragment.kt` in sample, dagger will still compile, but it will erroneously use constructor injected service instead of bound one.

Scope is not helpful because service and the class that service is injected into are usually in the same scope. I guess I could create another component and hack around to do this with scoping, but it would create a lot more boilerplate and make dagger code much less readable.

I guess interface/impl split is the only option here, yes.

**Comment by Chang-Eric** [comment]
In WordListFragment, I see 3 injections with `@ScopedService`. ActionHandler, DataProvider, and WordEventEmitter. Which of these is the binding that falls back?

ActionHandler and DataProvider are interfaces, while WordEventEmitter doesn't have an `@Inject` constructor.

Overall though, my guess is that you get this qualifier path because of the Backstack handling in providing WordController. Is it possible to make WordController not use `@Inject` and just make the `@Provides` be the unqualified binding? Then I think you wouldn't need the qualifiers everywhere.

**Comment by matejdro** [comment]
Sorry, I thought that example had this in, but it looks like it is another test project with a lot of interfaces. I've made separate branch for you that uses actual classes: https://github.com/matejdro/simple-stack-dagger-scoping-sample/tree/dagger_demo

Using `Provides` would work, but it would negate convenience of constructor injection (e.g. I would need to update manually module whenever I update constructor of the class).

**Comment by Chang-Eric** [comment]
I see, thanks for the example. It took me a while to find where the inject constructor is used and how that flows through the BackStack class.

I think one of the other reasons this wasn't supported is that `@Inject` constructors are implicit. We only figure out to go to the class to look for it when we see an unqualified type. If we made this change, we'd have to check every qualified type for a fallback. It also might be a big cognitive change for where people look for binding definitions.

I think the easiest fix for you might be to write an SPI plugin. You might be able to trigger it off your own annotation, like `@RestrictInjectionsTo("FooModule")` that then throws an error if the plain type is used anywhere. Not sure if this is important enough for this particular use case, but it could be useful if this is a widely used part of your code. Sorry I don't have anything better at the moment.

**Comment by matejdro** [comment]
Yeah, you've given me couple of ideas throughout the thread, so I might implement one of them. Thanks for your help.
