### ISSUE TITLE
Generate #create() method with arguments for module constructor arguments

### ISSUE THREAD

**Issue by talios** [google/dagger#170]
I've been playing with Dagger 2 recently ( kudos - very nice! ) and wondered if something like the following was possible, or had been considered and rejected. Given some code that normally reads like:

    GreetingComponent greeting = DaggerGreetingComponent.builder()
      .greetingModule(new GreetingModule("amrk"))
      .build();

no `create()` is generated because of the lack of a default constructor on my `GreetingModule`, however, would it be possible, in such situations generate one such that the constructor arguments are supplied, i.e.

    GreetingComponent greeting = DaggerGreetingComponent.create("amrk");

An initial thought could be something like:

    @Module
    @Singleton
    public class GreetingModule {
      private String username;
      @Inject 
      public GreetingModule(@Named("username") String username) {
        this.username = username;
      }

Here I'm reusing the `@Inject` annotation to signal that the constructor should have the arguments injected ( from the component ), and also using `@Named` ( or some other qualifier annotation ) to identify an argument as being named/reused - in this case the `#create()` method should only have one argument for `username` shared across multiple modules needing it ( maybe even generating its own synthetic module? ).

This means that you don't need expose your individual module classes to the consumer of the component.

Thoughts?

**Comment by netdpb** [comment]
In that simple example, it makes sense. But as soon as you have more than one module that takes arguments, or more complex examples, it's going to get more complicated. The generated `create()` method is going to end up with a large list of parameters, with many of the same type, and I think it'll become very easy to pass the wrong arguments and not realize it.

An alternative that I could see might be for the generated builder to have an overload for each required module that mirrors the module's public constructor parameters. That way you would have the choice of calling the current module-setting method or one that lets you skip the "new GreetingModule" part:

```java
DaggerGreetingComponent.builder()
    .greetingModule("amrk") // EQUIVALENT TO .greetingModule(new GreetingModule("amrk"))
    .build()
```

I'm not convinced that being able to avoid typing "new GreetingModule(" is worth the extra indirection, though.
