### ISSUE TITLE
MissingBinding

### ISSUE THREAD

**Issue by tzasacky** [google/dagger#1705]
I have the following error: [Dagger/MissingBinding] java.util.Set<okhttp3.Interceptor> cannot be provided without an @Provides-annotated method.

I saw the response at https://github.com/google/dagger/issues/668, but this appears to be a separate problem, as it still occurs with the @JvmSuppressWildcards, just with a slightly different message. Following is the code for the method the error is about. 

```
    @Provides
    fun provideOkHttp(networkInterceptors: Set<@JvmSuppressWildcards Interceptor>)
            : OkHttpClient =
        OkHttpClient.Builder()
            .addNetworkInterceptors(networkInterceptors)
            .readTimeout(TIMEOUT, TimeUnit.SECONDS)
            .build()
```

**Comment by arunkumar9t2** [comment]
How does `networkInterceptors` provision method look like? It also needs to to have `@JvmSuppressWildcards`.
