### ISSUE TITLE
Compile throwing NoSuchMethodError on auto-common dependency

### ISSUE THREAD

**Issue by jart** [google/dagger#171]
[javac] java.lang.NoSuchMethodError: com.google.auto.common.MoreTypes.nonObjectSuperclass(Ljavax/lang/model/util/Types;Ljavax/lang/model/util/Elements;Ljavax/lang/model/type/DeclaredType;)Lcom/google/common/base/Optional;
    [javac]     at dagger.internal.codegen.MembersInjectionBinding$Factory.forInjectedType(MembersInjectionBinding.java:227)
    [javac]     at dagger.internal.codegen.InjectProcessingStep.process(InjectProcessingStep.java:130)
    [javac]     at com.google.auto.common.BasicAnnotationProcessor.process(BasicAnnotationProcessor.java:228)
    [javac]     at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:793)
    [javac]     at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:722)
    [javac]     at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1700(JavacProcessingEnvironment.java:97)
    [javac]     at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1033)
    [javac]     at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1167)
    [javac]     at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1108)
    [javac]     at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:824)
    [javac]     at com.sun.tools.javac.main.Main.compile(Main.java:439)
    [javac]     at com.sun.tools.javac.main.Main.compile(Main.java:353)
    [javac]     at com.sun.tools.javac.main.Main.compile(Main.java:342)
    [javac]     at com.sun.tools.javac.main.Main.compile(Main.java:333)
    [javac]     at com.sun.tools.javac.Main.compile(Main.java:76)
    [javac]     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    [javac]     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    [javac]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    [javac]     at java.lang.reflect.Method.invoke(Method.java:606)
    [javac]     at org.apache.tools.ant.taskdefs.compilers.Javac13.execute(Javac13.java:56)
    [javac]     at org.apache.tools.ant.taskdefs.Javac.compile(Javac.java:1153)
    [javac]     at org.apache.tools.ant.taskdefs.Javac.execute(Javac.java:930)
    [javac]     at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
    [javac]     at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
    [javac]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    [javac]     at java.lang.reflect.Method.invoke(Method.java:606)
    [javac]     at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
    [javac]     at org.apache.tools.ant.Task.perform(Task.java:348)
    [javac]     at org.apache.tools.ant.Target.execute(Target.java:435)
    [javac]     at org.apache.tools.ant.Target.performTasks(Target.java:456)
    [javac]     at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
    [javac]     at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
    [javac]     at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
    [javac]     at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
    [javac]     at org.apache.tools.ant.Main.runBuild(Main.java:851)
    [javac]     at org.apache.tools.ant.Main.startAnt(Main.java:235)
    [javac]     at org.apache.tools.ant.launch.Launcher.run(Launcher.java:280)
    [javac]     at org.apache.tools.ant.launch.Launcher.main(Launcher.java:109)

**Comment by artem-zinnatullin** [comment]
What version of Dagger 2 do you use?

Seems that it's problem of 2.1-SNAPSHOT

**Comment by jart** [comment]
From my ivy config:

    <dependency org="com.google.dagger" name="dagger" rev="2.0"/>
    <dependency org="com.google.dagger" name="dagger-compiler" rev="2.0" conf="compile"/>
    <dependency org="com.google.auto" name="auto-common" rev="0.4"/>
    <dependency org="com.google.auto.value" name="auto-value" rev="1.0"/>
    <dependency org="com.google.auto.factory" name="auto-factory" rev="0.1-beta1"/>
    <dependency org="com.google.auto.service" name="auto-service" rev="1.0-rc2"/>

**Comment by artem-zinnatullin** [comment]
Dependencies LGTM (but I don't know why you included auto-libraries directly, I think Ivy can resolve required dependencies of dependencies from pom.xml), also in current master branch of [Google/Auto/Common](https://github.com/google/auto/tree/master/common) `MoreTypes` [has this method]( https://github.com/google/auto/blob/master/common/src/main/java/com/google/auto/common/MoreTypes.java#L712) 

Hope repository maintainers will help you

**Comment by cgruber** [comment]
I'm confused.  Auto-common shoudl have been "Shaded" into the dagger
processor.  Dagger shouldn't be calling out to auto-common at all, but have
an internal re-homed copy of MoreTypes. :/  I'll dig into this more.  Do
you have a publicly visible project in a branch I can grab to figure this
out?

**Comment by jart** [comment]
I started the whole process fresh from scratch, and got a weird new error. Any ideas?

    [javac] An annotation processor threw an uncaught exception.
    [javac] Consult the following stack trace for details.
    [javac] java.lang.NoSuchFieldError: MAP
    [javac]     at dagger.internal.codegen.ProvidesMethodValidator.validate(ProvidesMethodValidator.java:115)
    [javac]     at dagger.internal.codegen.ModuleProcessingStep.process(ModuleProcessingStep.java:79)
    [javac]     at dagger.shaded.auto.common.BasicAnnotationProcessor.process(BasicAnnotationProcessor.java:228)
    [javac]     at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:793)
    [javac]     at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:722)
    [javac]     at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1700(JavacProcessingEnvironment.java:97)
    [javac]     at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1033)
    [javac]     at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1167)
    [javac]     at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1108)
    [javac]     at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:824)
    [javac]     at com.sun.tools.javac.main.Main.compile(Main.java:439)
    [javac]     at com.sun.tools.javac.main.Main.compile(Main.java:353)
    [javac]     at com.sun.tools.javac.main.Main.compile(Main.java:342)
    [javac]     at com.sun.tools.javac.main.Main.compile(Main.java:333)
    [javac]     at com.sun.tools.javac.Main.compile(Main.java:76)
    [javac]     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    [javac]     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    [javac]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    [javac]     at java.lang.reflect.Method.invoke(Method.java:606)
    [javac]     at org.apache.tools.ant.taskdefs.compilers.Javac13.execute(Javac13.java:56)
    [javac]     at org.apache.tools.ant.taskdefs.Javac.compile(Javac.java:1153)
    [javac]     at org.apache.tools.ant.taskdefs.Javac.execute(Javac.java:930)
    [javac]     at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
    [javac]     at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
    [javac]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    [javac]     at java.lang.reflect.Method.invoke(Method.java:606)
    [javac]     at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
    [javac]     at org.apache.tools.ant.Task.perform(Task.java:348)
    [javac]     at org.apache.tools.ant.Target.execute(Target.java:435)
    [javac]     at org.apache.tools.ant.Target.performTasks(Target.java:456)
    [javac]     at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
    [javac]     at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
    [javac]     at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
    [javac]     at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
    [javac]     at org.apache.tools.ant.Main.runBuild(Main.java:851)
    [javac]     at org.apache.tools.ant.Main.startAnt(Main.java:235)
    [javac]     at org.apache.tools.ant.launch.Launcher.run(Launcher.java:280)
    [javac]     at org.apache.tools.ant.launch.Launcher.main(Launcher.java:109)

The project is internal.

**Comment by cgruber** [comment]
Do you have square's dagger core artifact in your build?  MAP isn't present
in the older dagger 1.x codebase.  That's the only way that would make
sense.

**Comment by jart** [comment]
Yes. It appears that auto factory depends on square dagger.

**Comment by cgruber** [comment]
This needs to be fixed on the auto-factory side, and I"ll whip up a CL to
do that, and release a new autofactory release you can use.

**Comment by cgruber** [comment]
I'm going to close this, as it's a bad interaction wtih auto-factory 1.0-beta1, and the fix is coming in 1.0-beta2 (to be released shortly).
