### ISSUE TITLE
Dagger SPI calls BindingGraphPlugin.visitGraph multiple times for a @Component if full binding graph validation is enabled

### ISSUE THREAD

**Issue by arunkumar9t2** [google/dagger#1711]
I am using Dagger SPI for a visualization tool and observed that if [full binding graph validation](https://dagger.dev/compiler-options.html#full-binding-graph-validation) is enabled, dagger calls `BindingGraph.visitGraph` multiple times for a single component.

Example:
```java
static class World {
    private final String name;
    @Inject
    World(String name) {
      this.name = name;
    }
    void say() {
      System.out.println("Hello world, " + name + "!");
    }
  }
  static class Hello {
    final World world;
    @Inject
    Hello(World world) {
      this.world = world;
    }
  }

  @Component
  interface SampleComponent {
    Hello hello();
    @Component.Factory
    interface Factory {
      SampleComponent create(@BindsInstance String name);
    }
  }
```

And in `BindingGraphPlugin`:

```java
@Override
public void visitGraph(BindingGraph bindingGraph, DiagnosticReporter diagnosticReporter) {
    TypeElement componentElement = bindingGraph.rootComponentNode().componentPath().currentComponent();
    System.out.println(ClassName.get(componentElement).simpleName())
}
```

In the output, I see `SampleComponent` reported two times when full validation is enabled and once if it is turned off.

Questions:
* Is this a known behavior and if there is a possibility for the graph to contain different information each time it is reported? I am currently only considering the first report.
* Could this be addressed in Dagger via the newly introduced `CompositeBindingGraphPlugin`?

**Comment by bcorso** [comment]
This is currently WAI, but we haven't really settled on the API for this yet.

The current idea is that when the full binding graph validation is enabled, we will first visit the "full" graph for all plugins, and afterwards we will visit the "pruned" graph for all plugins. Some plugins may only care about the pruned graph and some may only care about the full graph. For example, if your plugin only cares about the pruned graph you can do:

```java
@Override
public void visitGraph(BindingGraph graph, DiagnosticReporter diagnosticReporter) {
  if (graph.isFullBindingGraph()) {
    return;
  }
  // Visit the pruned graph only
}
```

**Comment by arunkumar9t2** [comment]
Thanks! I tried using `graph.isFullBindingGraph()` and it fits my needs for now. I agree it is WAI, closing this issue.
