### ISSUE TITLE
Implementation of Component uses fist defined getter

### ISSUE THREAD

**Issue by Romamok** [google/dagger#1723]
I was curious what will happen when I define 3 getters for the same class, like:
```
@Component(modules = CarProvider.class)
public interface CarComponent {

    Car getCarrrrrrr2();
    
    Car getCar();

    Car getCarrrrrrr();

    void inject(MainActivity mainActivity);
}
```

Then the Dagger-generated impl of it seems to take the first when injecting like
```
public final class DaggerCarComponent implements CarComponent {

  //... some stuff

  @Override
  public Car getCarrrrrrr2() {
    return new Car(CarProvider_GiveMeEngineFactory.giveMeEngine(carProvider), new Wheels());}

  @Override
  public Car getCar() {
    return getCarrrrrrr2();}

  @Override
  public Car getCarrrrrrr() {
    return getCarrrrrrr2();}

  @Override
  public void inject(MainActivity mainActivity) {
    injectMainActivity(mainActivity);}

  private MainActivity injectMainActivity(MainActivity instance) {
    MainActivity_MembersInjector.injectInjeteddddCar(instance, getCarrrrrrr2());
```
The interesting (?) part is:
```
MainActivity_MembersInjector.injectInjeteddddCar(instance, getCarrrrrrr2());
```
the others ```getCar()``` and ```getCarrrrrrr()``` just wraps that first method.

Is this useful somehow? Does it make sense to have more than 1 getter in ```Component```?

**Comment by tbroyer** [comment]
I suppose it can make sense if you inherit those methods from other interfaces.

```java
interface HasCar {
  Car getCar();
}
interface CanCreateCar {
  Car createCar();
}
interface CarInstantiator {
  Car newCarInstance();
}

@Component(modules = CarModule.class)
interface CarComponent extends HasCar, CanCreateCar, CarInstantiator {}
```

**Comment by bcorso** [comment]
As @tbroyer mentions, there are valid cases where you might need to get the same binding by different interfaces, so we have to allow it.

As far as Dagger is concerned these getters are all aliases of each other. It choses the first to contain the real implementation and the others as wrappers to reduce the amount code duplication in the generated code.
