### ISSUE TITLE
Illegal argument exception for bad named class

### ISSUE THREAD

**Issue by fourlastor** [google/dagger#173]
Hello, while trying something out I noticed that code generation throws an `IllegalArgumentException` if the class to inject (in my case was an activity) has a lowercase name.

For example:

```java
public class BlaActivity extends AppCompatActivity
```

will work perfectly, while

```java
public class bla extends AppCompatActivity
```

will throw the exception.

I know this shouldn't be the case (no class name should be lowercase), but there's no clear message on the exception explaining what's going on, maybe even just adding "Class name cannot be underscore" as a message would help understanding what's wrong.

**Comment by ronshapiro** [comment]
Yea, even though it's funky and non-idiomatic, this shouldn't break the codegen. If a non-idiomatic name is passed in, we can generate a non-idiomatic name to match it. I've got a fix for this internally.

**Comment by ronshapiro** [comment]
The fix should be out in the next release. Feel free to reopen if you don't see it then. Thanks for filing the bug!
