### ISSUE TITLE
Allow binding Provider<T> simular to Guice ProviderBindings for complex providing logic

### ISSUE THREAD

**Issue by Dkhusainov** [google/dagger#1730]
Currently(`2.26`) if you try to bind `Provider<T>` directly you get `@Binds methods must not return framework types` error.

Enabling provider binding would:
1. Give people more options on how they use the library depending on their use cases
2. Make dagger more interchargable with Guice
3. Make better use of downstream factory generation(if one chooses to do so)

**Comment by Chang-Eric** [comment]
Can you clarify the use case for this? Is it that you want to have your own subclass of Provider with custom memoizing logic or something?

**Comment by trevjonez** [comment]
Seems like an `@Provides` function is all you need to replace the need for this.

**Comment by Dkhusainov** [comment]
My use case is that I don't want to run dagger processoror on my submodules, only root module(which generates `@Component`). Currenlty I have to run it on modules which have `@Module`'s with `@Provides`, because dagger only generates downstream `Factory` for `@Binds`. 

`@Bind`ing `Provider<MyDependency>` myself would allow me to drop dagger processor and by extension `kapt`.

**Comment by Chang-Eric** [comment]
Thanks for the explanation. Unfortunately, I don't think this is something we're willing to support. We rely on being able to process `@Module` classes and may build new functionality that requires that in the future (including some of the new Kotlin support). So I'm going to close this as we're not willing to change that requirement.
