### ISSUE TITLE
Proguard issue: "DaggerApplication Can't find referenced class" (2.26)

### ISSUE THREAD

**Issue by mateuszkwiecinski** [google/dagger#1731]
After migrating to 2.26 I started getting Proguard (not R8) obfuscation error:
```
Warning: dagger.android.DaggerApplication: can't find referenced class com.google.errorprone.annotations.ForOverride
Warning: dagger.android.DispatchingAndroidInjector: can't find referenced class com.google.errorprone.annotations.CanIgnoreReturnValue
Warning: dagger.android.package-info: can't find referenced class com.google.errorprone.annotations.CheckReturnValue
Warning: dagger.android.support.package-info: can't find referenced class com.google.errorprone.annotations.CheckReturnValue
```

I've noticed that 2.25 publishes `proguard` file within aar artifact:
![image](https://user-images.githubusercontent.com/36954793/73634870-7f9daa80-4662-11ea-8835-600e0ba7816e.png)
but 2.26 seems to be missing it:
![image](https://user-images.githubusercontent.com/36954793/73634897-89271280-4662-11ea-812b-634f10bc6dc8.png)

So if I had to guess the output of the new `ProguardProcessor` doesn't get added to output aar?

**Comment by danysantiago** [comment]
Are you using Gradle as your build system? Which version of the Android Gradle Plugin are you on?
The `proguard.txt` rules got moved to the JAR-style location, `META-INF/proguard/dagger-android.pro` inside the `classes.jar`

**Comment by mateuszkwiecinski** [comment]
Yes I am using Gradle - version 6.1.1. Android Gradle Plugin version 3.5.3.
Is there any easy way to see which files does Proguard take into account? 🤔(similar to _Merged Manifest_ view in Android Studio)

In the meantime I'll try to prepare simple repro repository.

**Comment by mateuszkwiecinski** [comment]
I'm back with sample project that fails on 2.26 with Proguard resulting exactly the same errors.
https://github.com/mateuszkwiecinski/github_browser/compare/dagger/repro

I verified that with R8 enabled everything works well both on 2.25.4 and on 2.26. 
I disabled R8 and added few rules to make Proguard work on 2.25.4. (first commit there)
I updated dagger version to 2.26 and got the same result:
![image](https://user-images.githubusercontent.com/36954793/73693664-e52b7e80-46d6-11ea-9a32-b0111ed9518d.png)

Please let me know if such project is sufficient (I'm using custom plugins there, which can make understanding project config slightly more difficult) or should prepare simpler project setup?
Initially I encountered the issue on a project without custom config.

**Comment by BaloghTamas** [comment]
> Is there any easy way to see which files does Proguard take into account? 🤔(similar to _Merged Manifest_ view in Android Studio)

You can add `-printconfiguration "build/outputs/mapping/configuration.txt"` to your project Proguard rules. Although this would not specifically state the file's name and path included (which would be great), it would list all the commands used, with all the places that are affected by it. Quite similar to Marged Manifest view, but without IDE support.

**Comment by mateuszkwiecinski** [comment]
I reduced project configuration almost to absolute minimum: https://github.com/mateuszkwiecinski/dagger_proguard_issue/blob/master/app/build.gradle#L26

The results I've got are:
Failure on [2.26](https://github.com/mateuszkwiecinski/dagger_proguard_issue/runs/433765708?check_suite_focus=true#step:5:40) 
Success on [2.25.4](https://github.com/mateuszkwiecinski/dagger_proguard_issue/runs/433771609?check_suite_focus=true#step:5:149)
☝️ Those builds produce artifacts with configuration file, as @BaloghTamas suggested, but I couldn't find anything abnormal there 🤔

Interesting thing is that it seems to work with AGP version `4.0.0-alpha09` 🤔And accoring to working they display there
> WARNING: The option setting 'android.enableR8=false' is deprecated.null
It will be removed in a future version of the Android Gradle plugin.
You will no longer be able to disable R8

All my problems are going to be solved soon 😄

**Comment by danysantiago** [comment]
Seems like R8 will be enabled by default in AGP 4.0.0, so you can either enabled it now so that the rules get picked up correctly or add the rule yourself: `-dontwarn com.google.errorprone.annotations.**`.
