### ISSUE TITLE
Dagger Android support package not provided in the release

### ISSUE THREAD

**Issue by RoberV** [google/dagger#1749]
The release in maven of `com.google.dagger:dagger-android` is not complete.
The package `dagger.android.support` doesn't exists.
It caused problems, for example the `DaggerFragment`  is deprecated and the docs says:

> Framework fragments are deprecated in Android P; prefer dagger.android.support.DaggerFragment to use a support-library-friendly dagger.android fragment implementation.

But I can use `dagger.android.support.DaggerFragment` because it doesn't exists in the package

**Comment by dmapr** [comment]
Check the [documentation](https://dagger.dev/android.html) for dependencies? It very clearly states those dependencies are in a different artifact:

```
dependencies {
      compile 'com.google.dagger:dagger-android:2.x'
      compile 'com.google.dagger:dagger-android-support:2.x' // if you use the support libraries
      annotationProcessor 'com.google.dagger:dagger-android-processor:2.x'
}
```
