### ISSUE TITLE
Update Android examples

### ISSUE THREAD

**Issue by bryansills** [google/dagger#176]
There is currently the following paragraph in both Android examples:

> Note: The app is in transition to Dagger 2 and may not reflect recommended patterns. Before we release Dagger 2.0 it will, but until this note is removed, please do not rely on this example as a strong recommendation.

[Here](https://github.com/google/dagger/blob/master/examples/android-simple/README.md) and [here](https://github.com/google/dagger/blob/master/examples/android-activity-graphs/README.md)

It looks as though the apps have been migrated over, but since 2.0 is now out, I was hoping y'all could either update the examples for best practices or remove the warning.

Thanks!

**Comment by ronshapiro** [comment]
We've got something in https://github.com/google/dagger/tree/df43ccb63d9d21979398c753756e9a9d843f22d5/java/dagger/example/android/simple, sorry for the long delay!
