### ISSUE TITLE
Unresolved reference: DaggerAppComponent when using modularization 

### ISSUE THREAD

**Issue by ritesh-singh** [google/dagger#1767]
I am using modularization in android. 

First module1 -> 
@Module
object Module1 { }

Second module2 ->
@Module
object Module2 { }

Third module -> Here 1 and 2 are added as dependency using **implementation**
@Module(includes = [Module1::class, Module1::class])
object Module3 { }

Now, my app-module is dependent on Module3 (implementation project(':module3')). Here, I have a component which includes Modules3.

Now, when dagger kick in, it creates the factories for providers in respective generated folders in module1 and module2 and module3, but it's not able to access to the generated classes as they are exposed via implementation and thus this error Unresolved reference: DaggerAppComponent. 
Changing implementation to api in Third module for module1 and module2 works.

But, i dont want to expose through an api, as i dont want the app-module to build if any changes in those modules.

Is there any other way or I am missing something?

**Comment by bcorso** [comment]
Unfortunately, this is currently working as intended. The generated Dagger component in your app-module needs to reference the generated provider factories from module1 and module2.  Thus, if there are changes to module1 or module2 the app-module does need to be regenerated.

**Comment by ritesh-singh** [comment]
Yeah, I figured out later. Thanks @bcorso
