### ISSUE TITLE
Duplicate class dagger.android.AndroidInjection found in modules classes.jar (com.google.dagger:dagger-android:2.25.4) and jetified-dagger-android-jarimpl-2.25.4.jar (com.google.dagger:dagger-android-jarimpl:2.25.4)

### ISSUE THREAD

**Issue by rahul1083** [google/dagger#1785]

**Comment by danysantiago** [comment]
Can you provide more information about this error? What build system are you using?

Do verify you are only using one of the two flavor of support lib artifacts.
`dagger-android` & `dagger-android-support` for the newer androidx package
`dagger-android-legacy` & `dagger-android-support-legacy` for the older support package.
