### ISSUE TITLE
Will Dagger.Hilt support SavedStateHandle injection into ViewModel?

### ISSUE THREAD

**Issue by VladyslavKasprov** [google/dagger#1789]
Will Dagger.Hilt support injection of `SavedStateHandle` that is filled with activity/fragment arguments into `ViewModel`?

As far is I know this can be achieved by using a subclass of `AbstractSavedStateViewModelFactory`. In order to access activity's arguments in `SavedStateHandle` we need to pass `intent.extras ?: Bundle()` to constructor of `AbstractSavedStateViewModelFactory`. For fragments we need to pass `arguments` instead. 

`SavedStateViewModelFactory` is now the default factory used in [activities](https://developer.android.com/jetpack/androidx/releases/activity#1.1.0), [fragments](https://developer.android.com/jetpack/androidx/releases/fragment#1.2.0) and [Navigation Component](https://developer.android.com/jetpack/androidx/releases/navigation#2.2.0).

**Comment by danysantiago** [comment]
Yes - ViewModel support with Hilt will likely be an extension not within Dagger but as part of the [Lifecycle project](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-master-dev:lifecycle/lifecycle-viewmodel-hilt/src/main/java/androidx/lifecycle/hilt).
