### ISSUE TITLE
Delayed Binding to Dagger2 Graph using Annotation Processing

### ISSUE THREAD

**Issue by steffimueller** [google/dagger#179]
http://stackoverflow.com/questions/29836221/delayed-binding-to-dagger2-graph-using-annotation-processing

Is there a way to handle this with dagger2. I.e., can I programmatically add things to the dependency graph?

**Comment by confile** [comment]
+1 great question. I was searching for this answer for a while.

**Comment by gk5885** [comment]
Looks like you got an answer from SO.

**Comment by confile** [comment]
@gk5885 Which answer do you mean?
