### ISSUE TITLE
vscode: dagger generated code not detected

### ISSUE THREAD

**Issue by jeusdi** [google/dagger#1791]
I've created a gradle project. This is `build-gradle`:

    plugins {
        id 'java'
    }
    
    repositories {
        jcenter()
    }
    
    dependencies {
        implementation 'com.amazonaws:aws-lambda-java-core:1.2.0'
        implementation 'com.amazonaws:aws-lambda-java-events:2.2.7'
        implementation 'com.amazonaws:aws-java-sdk-s3:1.11.754'
        implementation 'com.amazonaws:aws-java-sdk-dynamodb:1.11.754'
    
        implementation 'org.apache.logging.log4j:log4j-api:2.13.0'
        implementation 'org.apache.logging.log4j:log4j-core:2.13.0'
        runtimeOnly 'org.apache.logging.log4j:log4j-slf4j18-impl:2.13.0'
        runtimeOnly 'com.amazonaws:aws-lambda-java-log4j2:1.1.0'
    
        implementation 'com.opencsv:opencsv:5.1'
    
        implementation 'com.google.dagger:dagger:2.27'
        annotationProcessor 'com.google.dagger:dagger-compiler:2.27'
    
        testImplementation('org.junit.jupiter:junit-jupiter:5.6.1')
    }
    
    test {
    	useJUnitPlatform()
    	testLogging {
    		events "passed", "skipped", "failed"
    	}
    }
    
    task buildZip(type: Zip) {
        from compileJava
        from processResources
        into('lib') {
            from configurations.runtimeClasspath
        }
    }
    
    build.dependsOn buildZip

As you can see I've set up dagger dependencies:

    implementation 'com.google.dagger:dagger:2.27'
    annotationProcessor 'com.google.dagger:dagger-compiler:2.27'

My component is:

    @Component(modules = DaggerTransporterModule.class)
    public interface TransporterMaker {
    
        SOCTransporter maker();
        
    }

After having performed an `gradle build`, dagger artifacts are generated:

I've took a look on generated code:

    $ tree build/classes/java/main/net/gencat/soc/lambda/config/
    build/classes/java/main/net/gencat/soc/lambda/config/
    ├── DaggerTransporterMaker$Builder.class
    ├── DaggerTransporterMaker.class
    ├── DaggerTransporterModule.class
    ├── DaggerTransporterModule_ProvideContactServiceFactory.class
    ├── DaggerTransporterModule_ProvideCSVDaoFactory.class
    ├── DaggerTransporterModule_ProvideCSVDaoFactory$InstanceHolder.class
    ├── DaggerTransporterModule_ProvideDynamoDBDaoFactory.class
    ├── DaggerTransporterModule_ProvideDynamoDBDaoFactory$InstanceHolder.class
    ├── DaggerTransporterModule_ProvideS3DaoFactory.class
    ├── DaggerTransporterModule_ProvideS3DaoFactory$InstanceHolder.class
    └── TransporterMaker.class

As you can see, dagger artifacts are generated correctly.

Nevertheless, I'm not able to use them inside vscode:

[![enter image description here][1]][1]

Gradle is running fine:

    $ gradle compileJava
    
    BUILD SUCCESSFUL in 3s
    1 actionable task: 1 executed

Any ideas?

  [1]: https://i.stack.imgur.com/l3bSd.png

**Comment by tbroyer** [comment]
I doubt it's anything to do with Dagger per se.
It's likely an issue with the [Java Language Server](https://github.com/eclipse/eclipse.jdt.ls) not properly detecting the generated sources. Might also be related to the Gradle version you're using. Possibly related: https://github.com/eclipse/buildship/issues/329 (as the Java Language Server uses Buildship to import Gradle projects), so you might actually have to apply the `com.diffplug.eclipse.apt` plugin.

**Comment by NebelNidas** [comment]
Were you able to solve this issue? I have the same problem currently
