### ISSUE TITLE
compile time error does not work in android studio 

### ISSUE THREAD

**Issue by singhboymehta** [google/dagger#1794]
Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html

**Comment by JakeWharton** [comment]
Where are you seeing `compile` in the docs?

**Comment by ronshapiro** [comment]
https://github.com/google/dagger/commit/c7b835923ff09e93cb997692d8b9bbca53a00f68#diff-04c6e90faac2675aa89e2176d2eec7d8
updated
our recommendations to migrate away from using compile. I'd update your
gradle script accordingly.
