### ISSUE TITLE
Seeing sporadic IncompatibleClassChangeError in production

### ISSUE THREAD

**Issue by felipecsl** [google/dagger#180]
We saw about 10 occurrences of this so far in production:
```
java.lang.IncompatibleClassChangeError 
Class 'com.myapp.android.DaggerAppComponent' does not implement interface 
'com.myapp.android.AppGraph' in call to 
'void com.myapp.android.AppGraph.inject(com.myapp.android.activities.AppActivity)' 
(declaration of 'java.lang.reflect.ArtMethod' appears in /system/framework/core-libart.jar)
```

This happens when we call `AppApplication.get(this).component().inject(this);` inside the activity ``onCreate()``

Our ``AppComponent`` interface extends ``AppGraph``, which has all the ``inject()`` methods

**Comment by felipecsl** [comment]
Here's how the component looks like:

```
@Singleton
@Component(modules = {AppModule.class, ImageModule.class, NetworkModule.class})
public interface AppComponent extends AppGraph {
    /**
     * An initializer that creates the graph from an application.
     */
    final class Initializer {
        static AppComponent init(AppApplication app) {
            return DaggerAppComponent.builder()
                    .appModule(new AirbnbModule(app))
                    .imageModule(new ImageModule())
                    .networkModule(new NetworkModule())
                    .build();
        }

        private Initializer() {
        } // No instances.
    }
}
```

**Comment by ronshapiro** [comment]
Are you still perceiving this? This looks to be an ART issue given that type of error. Especially since Dagger happens at the `javac` level and produces regular old source code, this should be a problem for every run of your app or none, but not something in between. Do you know what types of devices this error is experienced on?

**Comment by felipecsl** [comment]
We'renot seeing this this anymore. Closing.
