### ISSUE TITLE
Generic @Inject'd fields in an abstract superclass

### ISSUE THREAD

**Issue by steffimueller** [google/dagger#181]
http://stackoverflow.com/questions/26447360/generic-injectd-fields-in-an-abstract-superclass

Is this a dagger2 issue or is it not possible to implement?

**Comment by sameb** [comment]
Have you tried this with the 2.0 release?  I added a bunch of supports for generics, so it should either work or should fail with an error message telling you exactly what's wrong.

**Comment by gk5885** [comment]
As @sameb mentioned, we have pretty extensive generics support.  Closing this for now.  Please reopen the issue if something in the latest release (2.0.2) isn't working for you.

**Comment by confile** [comment]
thanks
