### ISSUE TITLE
Issue with classpath when using in tests

### ISSUE THREAD

**Issue by maciej-kaznowski** [google/dagger#1817]
I've got an issue with dagger in unit tests. If I create a component only in tests, then AS shows errors in the generated `Dagger*` component. The code compiles fine, runs and the test passes. Yet the classes which are defined only in tests can't be resolved when viewing the generated Dagger* classes. I have tried this on AS 3.6.2 and latest 4.0 beta.

[build.gradle](https://github.com/maciej-kaznowski/dagger-issue/blob/master/app/build.gradle)
[component](https://github.com/maciej-kaznowski/dagger-issue/blob/master/app/src/test/java/com/innercirclesoftware/daggerissue/Injection.kt)

The full project is here: https://github.com/maciej-kaznowski/dagger-issue

This is what shows  for me in AS:
https://photos.app.goo.gl/2EX94YLmL6xHGFdf6

I suspect it has to do with the `sourceSets` but no matter what I did, I couldn't get it to work errors.

**Comment by Chang-Eric** [comment]
I'm not sure this is a Dagger issue. Sounds like an Android Studio issue especially because the unresolved class `TestComponent` isn't a Dagger generated class.
