### ISSUE TITLE
Issue detected with dagger.internal.codegen.ComponentProcessor. Expected 1 originating source file when generating...

### ISSUE THREAD

**Issue by stephanenicolas** [google/dagger#1818]
We are seeing the same issue as #1761  with version 2.27 but for a `Factory` being generated:

```
[WARN] Issue detected with dagger.internal.codegen.ComponentProcessor. Expected 1 originating source file when generating .../source/kapt/debug/com/squareup/foo/Bar_Factory.java, but detected 0: [].
```
It seems to be generated because of this method in a module:
```
@SingleIn(AScope.class) @Binds
    abstract Foo provideFoo(Bar bar);
```

**Comment by ZacSweers** [comment]
@luis-cortes is right. Incremental kapt does not work if the originating element is not in the current compilation set

**Comment by ZacSweers** [comment]
It's good to do this in general anyway, as you may otherwise have multiple intermediary projects generating this factory class and result in duplicate classes

**Comment by vRallev** [comment]
I'm working on the same project as @stephanenicolas. We definitely don't run the Dagger annotation processor in all modules that contain an inject constructor. However, knowing that this is an issue it's surprising to rarely see the warning. We should see it in way more modules and constantly, but that's not the case.
