### ISSUE TITLE
Error has type parameters, cannot members inject the raw type.

### ISSUE THREAD

**Issue by BackPackerDz** [google/dagger#182]
Hi guys, please can you help me, I got this error 

Error:it.neokree.materialnavigationdrawer.MaterialNavigationDrawer has type parameters, cannot members inject the raw type. via:
      com.antonioleiva.daggerexample.app.ui.main.MainComponent.inject(com.antonioleiva.daggerexample.app.ui.main.MainActivity activity)
          [component injection method for type: com.antonioleiva.daggerexample.app.ui.main.MainActivity]

Adn I have 

compile 'com.google.dagger:dagger:2.0'
 apt 'com.google.dagger:dagger-compiler:2.0'
  provided 'org.glassfish:javax.annotation:10.0-b28'

**Comment by netdpb** [comment]
I hope you got this fixed/figured out. Closing this bug since we unfortunately didn't look at it until now. Please reopen if you're still having this problem.
