### ISSUE TITLE
Look into supporting assisted injection directly in Dagger

### ISSUE THREAD

**Issue by Chang-Eric** [google/dagger#1825]
Some context in https://github.com/google/dagger/issues/935 but it might be beneficial to have an assisted inject solution directly in Dagger so that you don't have to use generated API (like in AutoFactory). If something like https://github.com/square/assistedinject were built into Dagger, the `@Binds` wouldn't be needed either.

**Comment by filipkowicz** [comment]
love this idea ✌️ happy to help if possible

**Comment by bcorso** [comment]
Closing now that this is implemented (see https://dagger.dev/dev-guide/assisted-injection).
