### ISSUE TITLE
Boilerplate code when passing objects between scoped components

### ISSUE THREAD

**Issue by konmik** [google/dagger#183]
``` java
@Singleton
@Component(modules = AppModule.class)
public interface AppComponent {
    void inject(MainActivity x);
    SharedPreferences getSharedPreferences();
}
```

Why not just generate `getSharedPreferences` method inside of `DaggerAppComponent` and use` ((
DaggerAppComponent)appComponent).getSharedPreferences()` later?

There are too much boilerplate code, especially when passing over a big components graph. Right not I need to describe `provideSharedPreferences()`, `getSharedPreferences()` in `AppComponent`, `getSharedPreferences()` in `AuthenticatedAreaComponent`. 

Three methods just for one tiny dependency is too much. 

And I need to write additional component methods for providing a scoped objects that was generated with @Inject constructors. An @Inject constructor is a great shortcut, but it became almost useless now - I need to declare each @Singleton object in a root component.

**Comment by daverix** [comment]
I only use AppComponent for singleton stuff with get methods and then I use a component for each activity/fragment. I don't need to specify my getters more than once. I use field injection for activities and fragments and because my sub components have the app component as a dependency it just works. :-)

**Comment by konmik** [comment]
Your component graph is simple :)

I need to run activities/synchronization with different accounts and scopes at the same time on my current project.

Tried to migrate to Dagger 2 (because of clearer scopes definition) this week, got 5 times more code for the same task.

**Comment by daverix** [comment]
More code instead of reflection = better performance and error check at
compile time. :)

**Comment by konmik** [comment]
This is not because of code instead of reflection.

This is because of not generating code for a typical task.

**Comment by daverix** [comment]
So what you are saying is that if you specify component A, B, C. A depends on B, B depends on C. Component C with a getter will not be available to A because of scopes?

**Comment by konmik** [comment]
Probably they will be available. But why do I need to write them at all? I want to write less code, this is why I use dagger.

I have about 100 singletons why do I need to keep a registry of them in a component? See no reason.

**Comment by daverix** [comment]
```
public class Test {
    class Dep {

    }

    @Scope
    @interface BScope {

    }

    @Scope
    @interface CScope {

    }

    @Module
    class DepModule {
        @Provides
        public Dep provideDep() {
            return new Dep();
        }
    }

    @Singleton
    @Component(modules = DepModule.class)
    interface A {
        Dep getDep();
    }

    @BScope
    @Component(dependencies = A.class)
    interface B {

    }

    @CScope
    @Component(dependencies = B.class)
    interface C {
        Dep getDep();
    }
}
```

Doesn't work as you actually have to specify for each component:

```
Error:(48, 13) error: my.package.Test.Dep cannot be provided without an @Inject constructor or from an @Provides-annotated method.
```

I think this is by design though. You have to specify your singletons in a component, otherwise the annotation processor can't generate code for your dependencies. It needs have the dependencies specified in the component to have a starting point for the dependency graph.

**Comment by konmik** [comment]
getDep can be generated. We normally don't need it outside of generated code.

**Comment by daverix** [comment]
You can actually create a base interface like this to not having to write the interfaces over and over again...

```
public interface BaseComponent {
    A getA();
    B getB();
    C getC();
}

@Singleton @Component(modules = MyModule.class)
public interface AppComponent extends BaseComponent {

}

@ScopeB
@Component(dependencies = AppComponent.class)
public interface B extends BaseComponent {

}

@ScopeC
@Component(dependencies = B.class)
public interface C extends BaseComponent {

}
```

**Comment by konmik** [comment]
Why do I need to create 100500 interfaces if all this code can (=>should) be generated?

I don't understand your position. Are you against of generation of more code for you, or you don't believe this can be done? This can be done - a scoped dependency is already tied to a component by having the same qualifier.

Are you trying to solve my problem? Thanks, but I already reverted my code back to Dagger 1 unless this issue will be solved. Right now I do not see how Dagger 2 can help on a large component graph. Dagger 1 gain is exponential when dealing with large projects because you don't have to maintain all that lists of dependencies. Dagger 2 can do the same, no reflection is needed.

**Comment by daverix** [comment]
I tried to help, yes. I don't think it is possible to just generate it. You must specify the scopes and dependencies for those scopes in some way or another. How do you want it to work? A special component for singletons that adds methods to the component which is not in the interface but in the modules?

**Comment by konmik** [comment]
OK. :)

Dagger 2 already knows how scopes and dependencies for those scopes are defined. If a dependency have the same scope as a component, then dagger 2 should just add a line into the generated component, like this:

``` java
interface DaggerAppComponent extends AppComponent {
    SharedPreferences  getSharedPreferences(); 
}
```

When building a component, Dagger should check if a component is of `DaggerAppComponent` class and if not, then just throw an exception. Probably some additional trigger/logic is needed for cases when `AppComponent` is not of `DaggerAppComponent` class, but I see no use cases for this. Probably some may need such functionality, but I bet this case is rare.

**Comment by tbroyer** [comment]
> When building a dependent component, Dagger should check if a component is of DaggerAppComponent class and if not, then just throw an exception. Probably some additional trigger/logic is needed for cases when AppComponent is not of DaggerAppComponent class, but I see no use cases for this. Probably some may need such functionality, but I bet this case is rare.

See #110 and https://groups.google.com/d/msg/dagger-discuss/FtbWILcoqHM/GUUe792rjnAJ for some use-case.

How about you create an annotation processor that generates component interfaces from scoped binding methods in modules?
E.g. from module

```java
@Module class MyModule {
  @Provides @Singleton provideSharedPreferences() { return …; }
}
```

generate an interface:

```java
public interface MyModule_ScopedBindings {
  SharedDependencies getSharedDependencies();
}
```

that you can extend from your component:

```java
@Singleton
@Component(modules = MyModule.class)
public interface AppComponent extends MyModule_ScopedBindings {
}
```

**Comment by konmik** [comment]
Are you telling me that I should write an annotation processor to use Dagger 2? Sounds crazy. :D

**Comment by sameb** [comment]
You shouldn't need the boilerplate getter methods on components if using subcomponents.

**Comment by tbroyer** [comment]
@sameb Ah nice! The doc at https://google.github.io/dagger/ really should (briefly) mention them.

**Comment by daverix** [comment]
Yeah that was nice to know. Thanks @sameb! The sub components are described in the javadoc for the Component class. :)

**Comment by konmik** [comment]
Are you trying to tell me that there is no issue?

There IS an issue, I need to write 5 times more code because Dagger 2 forces me to declare ALL shared objects in a component interface.

**Comment by sameb** [comment]
@konmik, you shouldn't need to do that if using subcomponents.  IIUC, getting rid of the getters from the parent component interface is basically the raison d'etre for subcomponents.

**Comment by konmik** [comment]
@sameb Oh, I didn't get that "subcomponent" is a special term. 

Now I've found: http://google.github.io/dagger/api/latest/dagger/Component.html - "Subcomponents"

Thank for the info! :)
