### ISSUE TITLE
Missing @Generated annotation on generated code flags EP's RefersToDaggerCodegen bug pattern in generated code

### ISSUE THREAD

**Issue by davido** [google/dagger#1831]
It seems that Dagger is not emitting "@Generated" annotation on generated code.

As the consequence, recently added RefersToDaggerCodegen in EP is falgged on generated code itself ans preventing us to bump EP version in Bazel.

Related issues:

- https://github.com/bazelbuild/rules_kotlin/issues/321
- https://github.com/google/error-prone/issues/1599

**Comment by tbroyer** [comment]
Dagger uses auto-common's `GeneratedAnnotations` (https://github.com/google/auto/blob/auto-common-0.10/common/src/main/java/com/google/auto/common/GeneratedAnnotations.java), it will use what it finds in the classpath / modulepath, so this depends which version of Java you're using and IIRC which arguments you're passing it (e.g. if you're using `-source 8` with JDK 9+ but don't have `javax.annotation.Generated` on the classpath).
See https://github.com/google/dagger/commit/41a6755bcf331570201e57bc3603fe4d5f5b827d for when this was last changed in Dagger.

**Comment by davido** [comment]
@tbroyer, thanks for the pointer. It's embarrassing that I forgot about this missing dependency. 

Bazel is still using `--source 8` per default, but also using JDK 11 from remote JDK. So the issue is that all downstream project that use Bazel/Dagger integration would have to add javax.annotation dependency: `javax.annotation:javax.annotation-api:jar:1.3.2`.

The point is, it worked until now also with this dependency. With new EP version, it doesn't work any more.

Anyway, adding the missing dependency to `rules_kotlin` fixed that porblem:

```java
@Generated(
    value = "dagger.internal.codegen.ComponentProcessor",
    comments = "https://dagger.dev"
)
@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
```

Probably, it wouldn't hurt to emphasize this dependency on `javax.annotation:javax.annotation-api:jar:1.3.2` in Dagger documentation, until Bazel is still using `--source 8` per default.
