### ISSUE TITLE
Unable to use ContributesAndroidInjector with Fragments.

### ISSUE THREAD

**Issue by Jitendra194** [google/dagger#1848]
I've been trying to inject dependencies for my fragments using ContributesAndroidInjctor instead of creating a subcomponent but it throws an exception,

`java.lang.IllegalArgumentException: No injector factory bound for Class<LoginFragment>`

Here is what I'm trying to do,

**Component:**

```
@Component(
    dependencies = [LoginFeature.Dependencies::class],
    modules = [FeatureModule::class, AndroidInjectionModule::class]
)
interface LoginFeatureMainComponent : AndroidInjector<LoginFeatureImpl> {

    @Component.Factory
    interface Factory {
        fun create(
            @BindsInstance loginFeatureImpl: LoginFeatureImpl,
            loginFeature: LoginFeature.Dependencies
        ): LoginFeatureMainComponent
    }
}
```

**Module:**

```
@Module
abstract class FeatureModule {
    @ContributesAndroidInjector(modules = [ViewModelProviderModule::class])
    abstract fun contributeLoginFragment(): LoginFragment
}
```

**Fragment:**

```
class FragmentNew : DaggerFragment() {

    @Inject
    lateinit var viewModelProviderFactory: ViewModelProviderFactory
    private lateinit var binding: FragmentNewBinding
    private val newViewModel: NewViewModel by viewModels { viewModelProviderFactory }
    
    override fun onCreateView(
        inflater: LayoutInflater, container: ViewGroup?, savedInstanceState: Bundle?): View? 
= DataBindingUtil.inflate<FragmentNewBinding>(inflater, R.layout.fragment_new, container, false).run {
        binding = this
        viewModel = newViewModel
        lifecycleOwner = viewLifecycleOwner
        root
    }
}
```

**LoginFeatureImpl:**

```
@AutoService(LoginFeature::class)
class LoginFeatureImpl : LoginFeature {
    override fun inject(dependencies: LoginFeature.Dependencies) {
            DaggerLoginFeatureMainComponent.factory().create(this, dependencies).apply {
                inject(this@LoginFeatureImpl)
            }
}
}
```

and my **Activity** basically calls inject method in **LoginFeatureImpl**:

```
class LaunchActivity : DaggerAppCompatActivity() {
    @Inject
    lateinit var viewModelProviderFactory: ViewModelProviderFactory
    private lateinit var binding: LaunchActivityBinding
    private val viewModel: LaunchViewModel by viewModels { viewModelProviderFactory }

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        binding = DataBindingUtil.setContentView(this, R.layout.launch_activity)
        viewModel.launchLoginFragment() **// this calls inject in LoginFeatureImpl**
    }
}
```

any help regarding this issue is appreciated.

**Comment by rafid059** [comment]
You should mention that the feature module is a dynamic feature module (according to this stackoverflow [question](https://stackoverflow.com/questions/61822251/unable-to-use-contributesandroidinjector-with-fragments-when-using-dynamicfeatur) you posted)

**Comment by Zhuinden** [comment]
This is just a hunch, but I don't think map multibinding will work across dynamic feature modules, which means `@ContributesAndroidInjector` won't work either.

**Comment by davidliu** [comment]
o_O why is `@AutoService` in an android app? Isn't that for annotation processors?

In any case, `@ContributesAndroidInjector` requires everything to be visible in the current compilation module, so you wouldn't be able to add on extra injectors in a dynamic feature module. You'd have to create your own component that takes in the the main app component as a component dependency (which it seems like you were already doing).

**Comment by Chang-Eric** [comment]
Agreed that `@ContributesAndroidInjector` and other features (like subcomponents that `@ContributesAndroidInjector` uses) are not supported for dynamic feature modules. You'll have to do this manually with component dependencies. This should be a helpful guide to follow: https://developer.android.com/training/dependency-injection/dagger-multi-module#dagger-dfm
