### ISSUE TITLE
Add support for Java 8

### ISSUE THREAD

**Issue by thedrow** [google/dagger#185]
Is there a reason why the build only tests on Java 7?

**Comment by gk5885** [comment]
We should definitely ensure that we get good behavior for Java 8.  @cgruber, as a first measure, can you also ensure that our ci builds with source level 8?

**Comment by ronshapiro** [comment]
I just sent a change internally to add jdk8 for CI. We're building at Java 8 internally, and plan to add Java 8 support at Google very soon, with no issues for Java 8 perceived. If there are any issues you see with Java 8 compatibility, please open specific issues for them.
