### ISSUE TITLE
dagger-hilt doesn't support per-target custom subcomponents

### ISSUE THREAD

**Issue by davidliu** [google/dagger#1867]
Maybe I'm jumping the gun here, but it seems like dagger-hilt doesn't support per-target custom subcomponents like in `dagger-android`. Am I totally wrong and I should just wait till the docs come out? Or if true, is this something on the roadmap?

I'd be interested in seeing something where we could have an AndroidEntryPoint use `FeatureActivityComponent` rather than the generic `ActivityComponent`.

**Comment by Chang-Eric** [comment]
Just FYI, we're going to come back to this issue about Hilt after the official launch. Thanks for filing it though and sorry for the wait!
