### ISSUE TITLE
How to use @ViewModelInject on a NavGraph-scoped ViewModel? 

### ISSUE THREAD

**Issue by Zhuinden** [google/dagger#1870]
If there is only ApplicationComponent, ActivityComponent, ActivityRetainedComponent and FragmentComponent, then how do I get a NavGraph-scoped ViewModel with `@ViewModelInject` from a NavBackStackEntry?

Sounds like this would only work if there's a custom component definition and the NavBackStackEntry counts as a `@AndroidEntryPoint`, but that doesn't seem possible. Just a hunch, though, in the sample I'm looking at I'm not even sure why `@ViewModelInject` works at all, or how to get additional `@Assisted` parameters that are not the SavedStateHandle.

**Comment by Chang-Eric** [comment]
Just FYI, we're going to come back to this issue about Hilt after the official launch. Thanks for filing it though and sorry for the wait!

**Comment by Zhuinden** [comment]
It's fine, thanks for the reply and will look forward to it 🙂

**Comment by davidliu** [comment]
Behind the scenes, the `@ViewModelInject` stuff is creating the [usual multi-bind pattern component](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-master-dev:hilt/hilt-lifecycle-viewmodel/src/main/java/androidx/hilt/lifecycle/ViewModelFactoryModules.java;drc=ac34b08e85b7c0bd93a8067199811f5a6396c923;l=59) which gets injected into their version of a [AbstractSavedStateViewModelFactory](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-master-dev:hilt/hilt-lifecycle-viewmodel/src/main/java/androidx/hilt/lifecycle/ViewModelAssistedFactory.java) that the activities and fragments automatically grab.

**Comment by Zhuinden** [comment]
If the HiltActivity/HiltFragment that becomes the parent due to the bytecode transformation has its `getDefaultViewModelFactory()` overridden to return Hilt's factory then the mystery is resolved and I can close this. 😏

**Comment by davidliu** [comment]
Yeap, that's exactly what happens.

**Comment by Zhuinden** [comment]
Nice, now I understand Hilt. Cheers.
