### ISSUE TITLE
Dagger generates map size check that cannot be optimized by R8

### ISSUE THREAD

**Issue by connyduck** [google/dagger#1872]
When inspecting the optimized and decompiled code [of my app](https://github.com/tuskyapp/Tusky) for a completely different reason, I noticed this weird code (obfuscation turned off for better readability):

```Java
LinkedHashMap newLinkedHashMapWithExpectedSize = DaggerCollections.newLinkedHashMapWithExpectedSize(27);
newLinkedHashMapWithExpectedSize.put(BaseActivity.class, daggerAppComponent.baseActivitySubcomponentFactoryProvider);
...
newLinkedHashMapWithExpectedSize.put(NotificationClearBroadcastReceiver.class, daggerAppComponent.notificationClearBroadcastReceiverSubcomponentFactoryProvider);
if (newLinkedHashMapWithExpectedSize.size() != 0) {
    map = Collections.unmodifiableMap(newLinkedHashMapWithExpectedSize);
} else {
    map = Collections.emptyMap();
}
```

The check for `size() != 0` is unnecessary as the map obviously is not empty. 
The generated code by dagger looks like this
```
MapBuilder.<Class<?>, Provider<AndroidInjector.Factory<?>>>newMapBuilder(27).put(BaseActivity.class, (Provider) baseActivitySubcomponentFactoryProvider). ... .build()
```
Seems like R8 is able to strip the `MapBuilder`, but not the size check.
I think an easy fix could be checking for the size that has been passed to the constructor of the builder instead of calling `size()` (R8 will be able to optimize that), an even better one to not generate that size check at all when the size is known at compile time (R8 doesn't even need to optimize it).

**Comment by JakeWharton** [comment]
The size check isn't generated so it can't be omited. It's the body of the `build()` method of that class which has been inlined.

If the implementation is changed to use `isEmpty()` instead of `size()` then R8 has the potential to optimize the conditional away based on a non-zero number of calls to add entries, no calls to remove entries, and when the reference doesn't escape between the adds and `isEmpty()` check. 

Whether or not they'll go for such an optimization is another question. I wonder how pervasive `isEmpty()` checks are for collections declared in the same method after inlining?

**Comment by Chang-Eric** [comment]
Closing this since I don't think this is something Dagger can fix since as mentioned above it isn't in our generated code.

**Comment by JakeWharton** [comment]
I guess you could argue that a `size()` call compared to zero could also be detected by R8, but it really seems like Dagger should switch to using `isEmpty()` anyway.

The switch-based implementation is really weird. Would like to know the story behind that.

**Comment by Chang-Eric** [comment]
Oh that's our `MapBuilder`, didn't realize that. Yea I think switching to using `isEmpty()` is reasonable.

**Comment by JakeWharton** [comment]
Thanks! Since it's a one-liner I won't bother with a PR since it'll actually make things harder.

@connyduck do you want to pursue the R8 feature request? If not I am happy to.
