### ISSUE TITLE
Dagger hilt injection suggestion

### ISSUE THREAD

**Issue by Sripadmanabans** [google/dagger#1873]
I am trying to inject fragments using `FragmentFactory`. 
When the app gets killed in the background the fragments get restored before the `onCreate()` of the activity finishes.
Hilt seems to inject it before `onCreate()` but I am not sure how to set the injected `FragmentFactory` before the `super.onCreate()`. So the app crashes when it gets killed in the background.

**Comment by Chang-Eric** [comment]
Just FYI, we're going to come back to this issue about Hilt after the official launch. Thanks for filing it though and sorry for the wait!

**Comment by Sripadmanabans** [comment]
Thank you. I will close this issue so others can look at #1893 for more information.
