### ISSUE TITLE
error: cannot find symbol       return DispatchingAndroidInjector_Factory.newInstance(DaggerAppComponent.this.getMapOfClassOfAndProviderOfAndroidInjectorFactoryOf(), Collections.<String, Provider<AndroidInjector.Factory<?>>>emptyMap());}

### ISSUE THREAD

**Issue by ghozimahdi** [google/dagger#1877]
I did an update

`kapt 'com.google.dagger: dagger-compiler: 2.20'`

to version 2.25.2

Can you help me?

**Comment by bcorso** [comment]
This is probably due to the breaking API changes for dagger.android introduced in Dagger v2.24 ([see release notes](https://github.com/google/dagger/releases/tag/dagger-2.24)).

I'll close this for now. Feel free to reopen with more information if it's not the issue.
