### ISSUE TITLE
For Dagger Hilt, how to bind MainView to the MainActivity in the same way as ContributeAndInjector?

### ISSUE THREAD

**Issue by TonyTangAndroid** [google/dagger#1878]
I know Dagger Hilt had not been officially released yet. But one could not help to try it out and it feels great that so many boilerplate code could be eliminated as demonstrated in this sample [pull request](https://github.com/TonyTangAndroid/DaggerTutorial/pull/17/files). 

There is one feedback  that I would like to provide, which is that we could not refer to the activity being injected as a dependency provider, which introduces a hack way to  bind MainView to the MainActivity in the same way as ContributeAndInjector.

Here is a pull request to demonstrate what I am trying to achieve and how I managed to achieve it in a hack way. 
https://github.com/TonyTangAndroid/DaggerTutorial/pull/18/

It would be super awesome that we could enable the activity being injected as a dependency provider. 

Sorry for the potential noise here.

**Comment by hantrungkien** [comment]
@TonyTangAndroid With Hilt you don't need to do or think more, just write and use like this:

```
@Module
@InstallIn(ActivityComponent::class)
object ActivityModule {

    @Provides
    @AppNameQualifier
    fun test(activity: Activity): String = activity.getString(R.string.app_name)
}
```

**Comment by hantrungkien** [comment]
@TonyTangAndroid Have you tried this?

```
@Module
@InstallIn(ActivityComponent::class)
object ActivityModule {

    @Provides
    @AppNameQualifier
    fun provideAppName(activity: Activity): String = activity.getString(R.string.app_name)
}
```

**Comment by TonyTangAndroid** [comment]
It would not work because we need to explicitly access `MainActivity` rather than `Activity` before we are to bind the `MainActivity` to `MainView`.  If we force cast `Activity` to `MainActivity`, it will crash on other activities.

Having checked the [hilt migration](https://dagger.dev/hilt/migration-guide#daggerandroid-application) guidance, I did not found a way, neither.

**Comment by hantrungkien** [comment]
@TonyTangAndroid Currently that seems to be the limit of Hilt. But in some cases, we can provide:

```
@InstallIn(ActivityComponent::class)
@Module
object MainActivityModule {

    @Provides
    fun provideMainView(activity: Activity): MainView? {
        return activity as? MainView
    }
}

interface MainView {

    fun showMessage(message: String?)
}
```

**Comment by Chang-Eric** [comment]
Sorry of missing this earlier, but going to close it out since there's not much to do here as you are correct that this is one of the design limitations of Hilt that we chose. There's some discussion here about using casts as you've figured out which other than changing what kinds of things you bind into the graph is about the best alternative: https://dagger.dev/hilt/migration-guide#depending-on-the-specific-activity-type
