### ISSUE TITLE
Dependency “cannot be provided without an @Inject constructor” is reported instead of the same scope used in @Subcomponent

### ISSUE THREAD

**Issue by igokoro** [google/dagger#188]
I've started using Dagger 2 and faced strange issue that looks like a bug to me.

I have 3 modules, that are composed into one subcomponent, which in turn extends/pluses higher level component.

Main/root component definition:

```java
@Component(
        modules = {GlobalModule.class,
                Other1Module.class,
                Other2Module.class
        }
)
@Singleton
public interface GlobalComponent {

    // multiple injection methods for multiple activity injections like below
    SomeActivity1 inject(SomeActivity1 object);
    SomeActivity2 inject(SomeActivity2 object);
    ...

    NavigationDrawerComponent plus(NavigationDrawerModule navigationDrawerModule);

}
```

Subcomponent is pretty simple: just combination of modules and a single injection point:

```java
@Singleton
@Subcomponent(
        modules = {
                NavigationDrawerModule.class,
                NavigationListModule.class,
                SwitcherModule.class
        }
)
public interface NavigationDrawerComponent {
    NavigationDrawerFragment inject(NavigationDrawerFragment object);
}
```
First modules looks like this - it provides general fragment-level dependencies:

```java
@Module
public class NavigationDrawerModule {

    private final Activity activity;
    private final View rootView;
    private final LoaderManager loaderManager;

    public NavigationDrawerModule(Activity activity, View rootView, LoaderManager loaderManager) {
        this.activity = activity;
        this.rootView = rootView;
        this.loaderManager = loaderManager;
    }

    @Provides @Singleton EventBus provideLocalBus() {
        return EventBus.builder().build();
    }

    @Provides @Singleton View provideViewRoot() {
        return rootView;
    }

    @Provides @Singleton LoaderManager provideLoaderManager() {
        return loaderManager;
    }

    @Provides @Singleton Context provideContext() {
        return activity;
    }
}
```
Second module looks like this - it provides presenter/controller and their dependencies for a subset of UI on screen:
```java
@Module
public class SwitcherModule {

    @Provides SwitchController provideSwitcherController(SwitchControllerImpl impl) {
        return impl;
    }

    @Provides SwitcherView provideSwitcherView(SwitcherViewImpl impl) {
        return impl;
    }

}
```
Third module - another presenter/controller for a subset of UI:
```java
@Module
public class NavigationListModule {

    @Provides @Singleton NavigationListController provideNavigationListController(NavigationListControllerImpl impl) {
        return impl;
    }

    @Provides @Singleton NavigationListView provideNavigationListView(NavigationListViewImpl impl) {
        return impl;
    }
}
```
Relevant part of the fragment that is being injected:

```
@Inject SwitchController identitySwitchController;
@Inject SwitcherView identitySwitcherView;
@Inject NavigationListController navigationListController;
@Inject NavigationListView navigationListView;
```

`NavigationListControllerImpl` implements the following constructor:

```java
@Inject
public NavigationListControllerImpl(Context ctx, EventBus bus) {
    this.ctx = ctx;
    this.bus = bus;
}
```
Error I'm getting from the Dagger 2 compiler is the following:
```
error: ...sidenavigation.navigationlist.NavigationListControllerImpl cannot be provided without an @Inject constructor or from an @Provides-annotated method.
...sidenavigation.NavigationDrawerFragment.navigationListController
[injected field of type: ...sidenavigation.navigationlist.NavigationListController navigationListController]
...sidenavigation.navigationlist.NavigationListModule.provideNavigationListController(...sidenavigation.navigationlist.NavigationListControllerImpl impl)
[parameter: ...sidenavigation.navigationlist.NavigationListControllerImpl impl]
```
Error complains about missing `@Inject`-annotated constructor, but it exists! If I replace implicit `NavigationListControllerImpl` instance creation (passing via `@Provides`-method parameter) with explicit (with `new`), dagger starts complaining about the same error but now for the presenter object which is the second entry in the same module, and so on.

All this situation looks very strange and looks like a defect to me.

**Comment by igokoro** [comment]
I've also posted this issue on SO, but no luck so far: http://stackoverflow.com/questions/30260073/dagger-2-error-dependency-cannot-be-provided-without-an-inject-constructor-w

**Comment by igokoro** [comment]
To simplify the case I've merged all 3 modules into the single one - still the same issue.

**Comment by igokoro** [comment]
I've figured out the problem - `@Subcomponent` must have it's own scope. Parent `@Component` and child `@Subcomponent` can't share the same scope (`@Singleton` in my case).

So the bug is basically that  dagger-compiler shows incorrect/unrelated/misleading error message.

I believe this should be fixed - same problem with scopes is correctly reported for child-parent `@Component`s via dependency annotation property and is actually very helpful to quickly resolve the issue.

**Comment by cgruber** [comment]
Hmm.  It should be fixed.  I'll escalate this internally.

**Comment by naixx** [comment]
Stumbled upon the same issue.

**Comment by shubhamchaudhary** [comment]
Having same issue : 2.0.1

**Comment by ronshapiro** [comment]
Can you check v2.6 and see if it's still there? If so, please open a new issue with a link to a repo that we can reproduce this issue.
