### ISSUE TITLE
@UninstallModules throws an error when modules are installed through an aggregator

### ISSUE THREAD

**Issue by quiro91** [google/dagger#1890]
Given I install my modules through an aggregator as described in the Hilt docs:
```
@InstallIn(ApplicationComponent.class)
@Module(includes = {
    FooModule.class,
    BarModule.class,
    ...
})
interface AggregatorModule {}
```

When I uninstall one of these modules in an Android test as:

```
@HiltAndroidTest
@UninstallModules(
    FooModule::class,
    BarModule::class
)
class MyAndroidTest 
```
I see the error: "@UninstallModules should only include modules annotated with both @Module and @InstallIn, but found [FooModule::class, BarModule::class]"

**Comment by Chang-Eric** [comment]
If using the aggregator module approach to migration, you can only uninstall the aggregator module. If you want to uninstall just `FooModule` or `BarModule`, then you will need to complete more of the migration to where those modules are not in the aggregator anymore and are each annotated with `@InstallIn` directly.

**Comment by quiro91** [comment]
Is it maybe worth adding this to the migration doc? I guess I need to split the aggregator in two interfaces, one that aggregates the modules I never unplug and one for pluggable modules
