### ISSUE TITLE
Give Documentation for the behaviour of @ViewModelInject

### ISSUE THREAD

**Issue by thegarlynch** [google/dagger#1901]
I don't know why, but to my surprise. this works!! I use jetpack hilt ViewModelInject.
You guys need to document this. This made me wonder, do you guys know how to inject presenter for outside ViewModel ? maybe, in Fragment Directly ?

```kotlin
class Presenter @Inject constructor(private val viewModel : MyViewModel)

class MyViewModel @ViewModelInject constructor(@Assisted handle : SavedStateHandle) : ViewModel {

   @Inject lateinit var presenter : Presenter

}
```

**Comment by Chang-Eric** [comment]
That....shouldn't work...

You are almost definitely getting different instances of your ViewModel, though I'm still surprised you aren't getting a compilation error. You confirmed you are actually injecting the Presenter class?

Dagger won't validate an `@Inject` constructor unless it is used and connected to an entry point. For example, if a Bar class injected Presenter, but Bar was itself unused, Dagger would not check either Bar or Presenter.

**Comment by thegarlynch** [comment]
> Dagger won't validate an @Inject constructor unless it is used and connected to an entry point. For example, if a Bar class injected Presenter, but Bar was itself unused, Dagger would not check either Bar or Presenter.

Hmm.. i see, so there is no implicit viewmodelcomponent that i don't aware of.. it is building and compiled just fine. it even generates Presenter_Factory. but my presenter is not initialized..

**Comment by Chang-Eric** [comment]
`Presenter_Factory` being generated is expected, but I'd expect a compilation error if you tried to inject Presenter somewhere.

Actually, there's basically two issues here. One is that `@Inject` on fields is not supported with `@ViewModelInject`. We should make that an error.

The other (that I'm not sure is a bug yet) would be if you tried to inject Presenter somewhere not in the ViewModel, like as a `@Inject lateinit var presenter : Presenter` in your `@AndroidEntryPoint` activity or something. That should fail. If it doesn't, then that is a bug too.

**Comment by ichsanachmad** [comment]
> 
> 
> I don't know why, but to my surprise. this works!! I use jetpack hilt ViewModelInject.
> You guys need to document this. This made me wonder, do you guys know how to inject presenter for outside ViewModel ? maybe, in Fragment Directly ?
> 
> ```kotlin
> class Presenter @Inject constructor(private val viewModel : MyViewModel)
> 
> class MyViewModel @ViewModelInject constructor(@Assisted handle : SavedStateHandle) : ViewModel {
> 
>    @Inject lateinit var presenter : Presenter
> 
> }
> ```

it still work sir ?
