### ISSUE TITLE
GenerateComponents usage?

### ISSUE THREAD

**Issue by davidliu** [google/dagger#1905]
Seems like GenerateComponents is unused entirely in the code base. I'm guessing, based off the [code snippet in the WorkerInject javadoc](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-master-dev:hilt/hilt-common/src/main/java/androidx/hilt/work/WorkerInject.java;drc=a8974142e21b0687b1eac9cd5e4d406fec9e78b3;l=47), that this was made obsolete by the `@HiltAndroidApp` annotation. Are there any further plans to use this?

**Comment by bcorso** [comment]
Yep, we should remove this annotation. As you've guessed it was made obsolete by `@HiltAndroidApp` and we just forgot to remove it.
