### ISSUE TITLE
Hilt is not compatible with pure Java Gradle modules

### ISSUE THREAD

**Issue by dandc87** [google/dagger#1908]
Our project has a number existing Java Gradle modules which expose Dagger modules. We cannot migrate these to use Hilt because the `hilt-android` artifact is an AAR, which is incompatible. 

Could some of the Android-agnostic annotations and interfaces be extracted to a separate `hilt` jar artifact? (at least `@InstallIn`, `@AliasOf`, and the standard component interfaces)

I imagine that these are all bundled together be certain everything is on the classpath of generated code, but feel a workable subset could be extracted without too much headache?

**Comment by Chang-Eric** [comment]
This is something we're aware of/thinking of a better answer, but it is complicated by the fact that the standard component interfaces are tied to Android. I don't know that it makes sense to refer to `dagger.hilt.android.components.ApplicationComponent` from a non-Android module. And since all components are currently children of that component, making `@InstallIn` available outside of that wouldn't be helpful.

Right now the best you can do is probably just create non-Hilt modules there and then `@Modules(include)` them in a Hilt Dagger module from an Android Gradle module.

**Comment by dandc87** [comment]
That is probably the path we will follow for now.

My 2 cents is that since Hilt bills itself as the DI solution for Android, a Java-compatible base artifact would make sense for a "Java Gradle module in an Android project" use case. And since the component interfaces are only logically tied to Android (they don't require Android classes), they could be included in a jar artifact instead. And if you really want separation, it could be `hilt` and `hilt-android-components` or something.

**Comment by Chang-Eric** [comment]
@dandc87 or anyone else following this - We have a plan that I think would work to allow usage of the ApplicationComponent in non-Android modules. Does this cover your use case or do you have bindings in non-Android modules that are bound to say the ActivityComponent?

The reason I think this makes sense for us is that `@Singleton` bindings can often make sense as just a general concept, but it is kind of hard to think of something that would be `@ActivityScoped` or something but not have a dependency on Android.

**Comment by dandc87** [comment]
> Does this cover your use case [...]?

Not entirely. But it would address the majority of our existing bindings.

**Comment by julioromano** [comment]
> Does this cover your use case

Mostly. Even though we don't scope pure java stuff at the Fragment or View level, we do scope pure java stuff at the ViewModel level (i.e. ActivityRetainedComponent).

**Comment by kakai248** [comment]
`The hilt-core artifact contains the core (non-Android) Hilt APIs. Note that this artifact is only meant to be used by pure Java/Kotlin libraries within an Android application.`

Just curious: why the `within an Android application` limitation? Wouldn't `SingletonComponent` also make sense for other type of applications?

**Comment by bcorso** [comment]
> Wouldn't SingletonComponent also make sense for other type of applications?

Yep, that's actually why we did the rename from `ApplicationComponent` -> `SingletonComponent`. We'll be looking into non-Android applications eventually, but we're currently focused on getting Hilt for Android out of alpha.

**Comment by anil-k-s** [comment]
do we have any solution now. I mean how we can use Hilt in kotlin or Java module in a Android project. Should we use Dagger for kotlin or java module & Hilt for Android modules.

**Comment by JavierSegoviaCordoba** [comment]
It is possible but I can't find it in docs, but in a GitHub release should be explained.

**Comment by bcorso** [comment]
@anil-k-s see [Dagger 2.29.1 release notes](https://github.com/google/dagger/releases/tag/dagger-2.29.1).

**Comment by anil-k-s** [comment]
Hilt injection for java module only work with  @InstallIn(SingletonComponent::class) . For example I have activity in that activity I am injecting viewmodel that viewmodel depends on usecase and use case depeneds on repository. here use case is present different  java module and i am injecting it through hitcore @Inject notation. Is this right way or there is alternative.

**Comment by anil-k-s** [comment]
thanks it helps.

**Comment by ColtonIdle** [comment]
Why is this still open if it seems to be fixed? Am I missingn something?

**Comment by bcorso** [comment]
@ColtonIdle I agree this seems to be fixed. I'll close this issue.
