### ISSUE TITLE
error: cannot find symbol

### ISSUE THREAD

**Issue by GustavodeJesus** [google/dagger#1915]
error: cannot find symbol
      return DaggerMDMApplication_HiltComponents_ApplicationC.builder()
             ^
  symbol: variable DaggerMDMApplication_HiltComponents_ApplicationC
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error

**Comment by ziglee** [comment]
When I get a error exaclty like yours, I also cannot find any other useful information from the compiler/builder regarding the source of the problem.

**Comment by zakayothuku** [comment]
Hey @GustavodeJesus did you get a fix for this. Am still getting the same issue.
