### ISSUE TITLE
Wrong Code Example At Hilt EntryPoint Documentation

### ISSUE THREAD

**Issue by volkansahin45** [google/dagger#1916]
Hi,
I was looking to the Hilt documentation and I've noticed a small wrong code example.
There is a best practice code at the bottom of the EntryPoint page (https://dagger.dev/hilt/entry-points) which is this one.

`MyClassInterface myClassInterface = EntryPoints.get(applicationContext, MyClassInterface::class.java)`

But this piece of code doesn't change when I switch to the Kotlin tab and this code is not Kotlin, It should've been like this: 

`val myClassInterface = EntryPoints.get(applicationContext, MyClassInterface::class.java)`

I couldn't find the dagger.dev websites source code so I couldn't open a PR for that.

**Comment by danysantiago** [comment]
The website is in the `gh-pages` branch: https://github.com/google/dagger/blame/gh-pages/hilt/entry-points.md#L141

We'll get it fixed but feel free to send a PR if you want.
