### ISSUE TITLE
Feature request: FragmentViewComponent

### ISSUE THREAD

**Issue by CraZyLegenD** [google/dagger#1925]
FragmentComponent binds the instance of the fragment when onAttach happens

FragmentViewComponent can bind the instance right before/after super.onViewCreated(view, savedInstanceState) is called so that we can have access to viewLifecycleOwner and viewLifecycleOwnerLiveData (since users would've already had bound their data/view bindings in onCreateView) and also we can use the savedInstanceState `  FragmentViewComponentBuilder fragment(@BindsInstance Fragment fragment, @BindsInstance bundle:Bundle?);
`?

It's literally the same code with FragmentComponent and FragmentComponentBuilder just different injection places and it gives the user a benefit of not relying on using the Fragment.lifecycle but instead the Fragment.viewLifecycleOwner

if there's a scope needed it can be called FragmentViewScoped

**Comment by CraZyLegenD** [comment]
```
/**
 * Scope annotation for bindings that should exist for the life of a fragment's view.
 */
@Scope
@Retention(CLASS)
public @interface FragmentViewScoped {}
```

```
/** A Hilt component that has the lifetime of the fragment's view. */
@FragmentScoped
@DefineComponent(parent = ActivityComponent.class)
public interface FragmentViewComponent {}
```
```

/** Interface for creating a {@link FragmentViewComponent}. */
@DefineComponent.Builder
public interface FragmentViewComponentBuilder {
  FragmentViewComponentBuilder fragment(@BindsInstance Fragment fragment);
  FragmentViewComponentBuilder build();
}
```

**Comment by Chang-Eric** [comment]
Sorry, I'm not sure I quite follow the issue you're running into. I'm not that familiar with LiveData unfortunately, but are you talking about being able to use the value from getViewLifecycleOwnerLiveData() in injected objects? Is it possible to just inject `Fragment` and then call that method lazily when you need it?

**Comment by CraZyLegenD** [comment]
> Sorry, I'm not sure I quite follow the issue you're running into. I'm not that familiar with LiveData unfortunately, but are you talking about being able to use the value from getViewLifecycleOwnerLiveData() in injected objects? Is it possible to just inject `Fragment` and then call that method lazily when you need it?

That and also viewLifecycleOwner

**Comment by CraZyLegenD** [comment]
> Sorry, I'm not sure I quite follow the issue you're running into. I'm not that familiar with LiveData unfortunately, but are you talking about being able to use the value from getViewLifecycleOwnerLiveData() in injected objects? Is it possible to just inject `Fragment` and then call that method lazily when you need it?

Can't access the Fragment View's LifecycleOwner when getView() is null i.e., before onCreateView() or after onDestroyView()

Because when onAttach happens viewLifecycleOwner isn't created

**Comment by CraZyLegenD** [comment]
Since I see that this ain't gonna be supported here's the solution to those who'll wonder what I'm talking about.

```
@FragmentScoped
class LifeCycleProvider @Inject constructor(
        private val fragment:Fragment) :LifecycleObserver {

    init {

        fragment.lifecycle.addObserver(object : DefaultLifecycleObserver {
            override fun onCreate(owner: LifecycleOwner) {
                fragment.viewLifecycleOwnerLiveData.observe(fragment) { viewLifecycleOwner ->
                    viewLifecycleOwner.lifecycle.addObserver(this@LifeCycleProvider)
                }
            }
        })
    }

    @OnLifecycleEvent(Lifecycle.Event.ON_DESTROY)
    fun disposeResources() {
        debug("RESOURCES DISPOSED")
    }
}
```
