### ISSUE TITLE
Hilt - @AndroidEntryPoint doesn't work when activity extends a base class that has generic type parameter

### ISSUE THREAD

**Issue by bmohan-bushel** [google/dagger#1931]
Hello all. I have been looking at Hilt and its possible application on the template that we use at my company. We use MVP architecture, and have our templates setup to facilitate this easily with Dagger and Dagger.Android.

 As a test I've tried to convert a basic login screen application to use Hilt, based off of roughly our template structure. The problem I've run into has been with injecting our activities. We use a BaseActivity that takes the presenter class as a generic type parameter. We then inject it in the BaseActivity like so:
```kotlin
abstract class BaseActivity<T : BasePresenter> : AppCompatActivity(), IBaseView {

    @Inject
    protected lateinit var app: Application

    @Inject
    protected lateinit var presenter: T
```
The presenter is constructor injected like this:
```kotlin
class LoginPresenter @Inject constructor(private val view: ILoginView, private val service: ILoginService) : BasePresenter() {
```
And the view provided like this:
```kotlin
@Module
@InstallIn(ActivityComponent::class)
abstract class LoginModule {
    @Binds
    abstract fun provideLoginView(activity: LoginActivity): ILoginView
}
```

This setup worked previously, but even though I've seemingly been following the guidelines for Hilt, I get the following compiler error:

```
[Dagger/MissingBinding] com.bushel.bmohan.baseactivitydemo.view.login.LoginActivity cannot be provided without an @Inject constructor or an @Provides-annotated method. This type supports members injection but cannot be implicitly provided.
  public abstract static class ApplicationC implements BaseActivityDemoApp_GeneratedInjector,
                         ^
  A binding with matching key exists in component: com.bushel.bmohan.baseactivitydemo.BaseActivityDemoApp_HiltComponents.ActivityC
      com.bushel.bmohan.baseactivitydemo.view.login.LoginActivity is injected at
          com.bushel.bmohan.baseactivitydemo.view.login.LoginModule.provideLoginView(activity)
      com.bushel.bmohan.baseactivitydemo.view.login.ILoginView is injected at
          com.bushel.bmohan.baseactivitydemo.view.login.LoginPresenter(view, …)
      com.bushel.bmohan.baseactivitydemo.view.login.LoginPresenter is injected at
          com.bushel.bmohan.baseactivitydemo.mvp.BaseActivity.presenter
      com.bushel.bmohan.baseactivitydemo.view.login.LoginActivity is injected at
```

Additionally, when we remove generic type parameters from the BaseActivity, the build succeeds, albeit without the presenter, as it can't inject without that parameter.

My question is does Hilt support using @AndroidEntryPoint on activities like this? Is there some other problem I'm failing to see?

The full code can be found [here](https://github.com/bmohan-bushel/base-activity-demo/tree/hilt-rewrite). The app is functional on dev, but broken on the hilt-rewrite branch

**Comment by Chang-Eric** [comment]
I think the issue you are running to is this: https://dagger.dev/hilt/migration-guide#depending-on-the-specific-activity-type

In Hilt, you can't inject `LoginActivity` directly unless you set up a provider yourself (that likely does a cast).

My guess as to why it works when you remove the type parameter is it is now no longer injecting LoginPresenter, which probably happened to be the only usage of ILoginView. Dagger doesn't try to validate unused bindings so that is what makes the error go away.
