### ISSUE TITLE
Build Error when working with a base fragment with generic data type

### ISSUE THREAD

**Issue by dewunmi** [google/dagger#1933]
Hi Everybody, So I mentioned this yesterday on another[ issue](https://github.com/google/dagger/issues/1910#issuecomment-645286835) thread but decided to create a new thread for it cause that's about to be closed. 

My Base Fragment is set up like this 

`abstract class BaseFragment<T : ViewDataBinding> : Fragment(){}`

then I have a fragment extending it and passing in a generated binding class

```
@AndroidEntryPoint(ExampleFragment::class)
class ExampleFragment : BaseFragment<FragmentExampleBinding>()
```

building with this set up returns 

```
public final class ExampleFragment extends com.example.common.base.BaseFragment<com.example.databinding.FragmentExampleBinding> {
             ^
  @AndroidEntryPoint class expected to extend Hilt_ExampleFragment. Found: BaseFragment
  [1;31m[Hilt] Processing did not complete. See error above for details.[0m
```

**Comment by bcorso** [comment]
Your use of the annotation seems a bit off. Can you try this instead:

```
@AndroidEntryPoint(BaseFragment::class)
class ExampleFragment : Hilt_ExampleFragment<FragmentExampleBinding>()
```

**Comment by bcorso** [comment]
Closing this since there hasn't been any activity. Feel free to reopen if you think this is still an issue.
