### ISSUE TITLE
How to use DaggerAndroid in FirebaseMessagingService? I am not able to extend DaggerService(getting only one class can appear in supertype kotlin error)Service in Firebase service class. 

### ISSUE THREAD

**Issue by ryderz8** [google/dagger#1937]
I have provided the ServiceModule to the Serviceclass through ContributesAndroidInjector in the Builder.

**Comment by dmapr** [comment]
All `DaggerService` does is call `AndroidInjection.inject(this);` before calling `super.onCreate();`

**Comment by Chang-Eric** [comment]
To expand on the above, DaggerService and other classes like DaggerActivity are just convenience classes for users. The main requirement is actually based around AndroidInjection (and in other cases like for activities implementing HasAndroidInjector as needed).

**Comment by ryderz8** [comment]
Thanks, @dmapr, and @Chang-Eric for the prompt response. It worked!!!!
Can you please share some tutorial documentation for the Dagger concepts? I really want to understand it in core.

**Comment by Chang-Eric** [comment]
https://dagger.dev/dev-guide/android has the main documentation I know of. Though to be honest, I'm aware that those docs need some love.

**Comment by ryderz8** [comment]
Sorry, just stuck with another issue, i am not being able to inject viewmodel in my BottomSheetDialogFragment. (as AndroidInjection.inject(this) is not working BottomSheetDialogFragment). Any help will be highly appreciated

**Comment by dmapr** [comment]
@ryderz8 take a look at the https://github.com/google/dagger/blob/master/java/dagger/android/support/DaggerDialogFragment.java and just do the same thing in your BottomSheetDialogFragment (or create a DaggerBottomSheetDialogFragment if you plan to have many and extend that).
