### ISSUE TITLE
same error for everything

### ISSUE THREAD

**Issue by martipello** [google/dagger#1940]
currently hilt reports Did you forget to add a Dagger binding annotation (e.g. @Binds)? for almost every type of error can we have a little more info here please

**Comment by bcorso** [comment]
The [full error message](https://github.com/google/dagger/blob/bc6f9a9f8b30389e3283f4509001999aa1510e3a/java/dagger/hilt/processor/internal/aggregateddeps/AggregatedDepsProcessor.java#L149-L150) is:

> "Found unimplemented abstract methods, %s, in an abstract module, %s. Did you forget to add a Dagger binding annotation (e.g. @Binds)?"

From the error message, it should tell you which abstract methods in which abstract module aren't annotated with a Dagger annotation e.g. `@Binds`. This is typically just a mistake, so adding the proper annotation will fix it.

OTOH, if you think your usage is legitimate please provide more information describing your use case?
