### ISSUE TITLE
Hilt doc: the "SPI" acronym is unclear

### ISSUE THREAD

**Issue by LouisCAD** [google/dagger#1941]
On [this page](https://dagger.dev/hilt/monolithic), we can find that confusing sentence:
> For keeping bindings private to only code that should use them, we recommend using qualifier annotations that are protected through restricted visibility or using an SPI plugin to enforce separation of code.

as the acronym makes things obscure.

My request is to ditch acronyms like these, unless they are widely known and discoverable on Google search or equivalent (e.g. "JVM"), even to non native English speakers that make the majority of developers.

**Comment by tbroyer** [comment]
Would adding a link to https://dagger.dev/dev-guide/spi be enough? (it in turns defines the acronym by linking to Wikipedia)

**Comment by LouisCAD** [comment]
That'd be great to have the link, yes. Can it also show "Service provider interface" when hovering ("title" in html terms), or in parentheses?
