### ISSUE TITLE
existing view models break when i use hilt

### ISSUE THREAD

**Issue by martipello** [google/dagger#1943]
https://stackoverflow.com/questions/62471849/cannot-create-instance-of-viewmodel-after-using-hilt-in-android

**Comment by martipello** [comment]
seems to only be android view model thats broken

**Comment by danysantiago** [comment]
Did you try the suggestions on the SO question? Can you please create a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)?

**Comment by martipello** [comment]
Na can't be bothered I've switched them all to be standard view models and if I need the application I'll annotate it
