### ISSUE TITLE
dagger-lint check build issue

### ISSUE THREAD

**Issue by beigirad** [google/dagger#1951]
In an Android project, I'm using just `dagger` without `dagger-android` has contained `dagger-lint` by default.
I added it's the dependency to app module build.gradle according to [2.28.1 release note](https://github.com/google/dagger/releases/tag/dagger-2.28)
```
lintChecks "com.google.dagger:dagger-lint:2.28.1"
```
when I added its plugin (`apply plugin: "com.android.lint"`) this error occurred in build time:

```
Cannot add a configuration with name 'lintClassPath' as a configuration with that name already exists.
```
and when I removed its plugin occurred this one:
```
Found more than one jar in the 'lintChecks' configuration. Only one file is supported. If using a separate Gradle project, make sure compilation dependencies are using compileOnly
```

What's wrong?

**Comment by danysantiago** [comment]
Looks like you are trying to apply the Lint plugin but the Gradle module is already an android-application / android-library. In that case then add an explicit dependency to `com.google.dagger:dagger-lint-aar:2.28.1` which will contain the Lint rules in an aar and the Android Gradle Plugin will be able to merge it with the rest of the default Android rules.

**Comment by bcorso** [comment]
I'll close this out since it's been a while with no response. Feel free to reopen in @danysantiago suggestion did not fix your issues.
