### ISSUE TITLE
Hilt: Example instrumentation test using navGraphViewModels, FragmentScenario and launchFragmentInHiltContainer

### ISSUE THREAD

**Issue by wbervoets** [google/dagger#1953]
Hello,

I'm trying to write an instrumentation test using:
- navigation graph scoped viewmodel
- FragmentScenario api
- launchFragmentInHiltContainer (referenced https://developer.android.com/training/dependency-injection/hilt-testing here)
- databinding

Here is some example test code:

```
@HiltAndroidTest
class ForgotPasswordFragmentTest {

    @get:Rule
    val hiltRule = HiltAndroidRule(this)

    @Test
    fun testEmptyEmailDisablesSendButton() {
        val testNavHostController = TestNavHostController(ApplicationProvider.getApplicationContext())
        testNavHostController.setViewModelStore(ViewModelStore())
        testNavHostController.setGraph(R.navigation.navigation_graph)
        testNavHostController.setCurrentDestination(R.id.forgotPassword)

 launchFragmentInHiltContainer<ForgotPasswordFragment> {
            ForgotPasswordFragment().also {  fragment ->
                // In addition to returning a new instance of our Fragment,
                // get a callback whenever the fragment’s view is created
                // or destroyed so that we can set the NavController
                fragment.viewLifecycleOwnerLiveData.observeForever { viewLifecycleOwner ->
                    if (viewLifecycleOwner != null) { // The fragment’s view has just been created
                        Navigation.setViewNavController(fragment.requireView(), testNavHostController)
                        onView(withId(R.id.retrievePasswordButton)).check(matches(isNotEnabled()))
                    }
                }

            }
        }
```

This however always crashes with IllegalStateException: View androidx.constraintlayout.widget.ConstraintLayout{39c0d6e V.E...... ......I. 0,0-0,0} does not have a NavController set.

Looking at the stacktrace it happens when in onViewCreated() I do:

`viewBinding.viewModel = onboardingViewModel // pass in the onboarding view model`

It tries to lazily get the onboardingViewModel which is intialized as:

`private val onboardingViewModel: OnboardingViewModel by navGraphViewModels(R.id.onboarding_graph) { defaultViewModelProviderFactory }`

```
Caused by: java.lang.IllegalStateException: View androidx.constraintlayout.widget.ConstraintLayout{39c0d6e V.E...... ......I. 0,0-0,0} does not have a NavController set
        at androidx.navigation.Navigation.findNavController(Navigation.java:84)
        at androidx.navigation.fragment.NavHostFragment.findNavController(NavHostFragment.java:118)
        at androidx.navigation.fragment.FragmentKt.findNavController(Fragment.kt:29)
        at be.joyn.business.onboarding.ForgotPasswordFragment$$special$$inlined$navGraphViewModels$1.invoke(NavGraphViewModelLazy.kt:56)
        at be.joyn.business.onboarding.ForgotPasswordFragment$$special$$inlined$navGraphViewModels$1.invoke(Unknown Source:0)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at be.joyn.business.onboarding.ForgotPasswordFragment$$special$$inlined$navGraphViewModels$2.invoke(NavGraphViewModelLazy.kt:59)
        at be.joyn.business.onboarding.ForgotPasswordFragment$$special$$inlined$navGraphViewModels$2.invoke(Unknown Source:0)
        at androidx.lifecycle.ViewModelLazy.getValue(ViewModelProvider.kt:53)
        at androidx.lifecycle.ViewModelLazy.getValue(ViewModelProvider.kt:41)
        at be.joyn.business.onboarding.ForgotPasswordFragment.getOnboardingViewModel(Unknown Source:2)
        at be.joyn.business.onboarding.ForgotPasswordFragment.onViewCreated(ForgotPasswordFragment.kt:48)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:332)
```

I thought maybe it's due to databinding not having al its work done (https://codelabs.developers.google.com/codelabs/advanced-android-kotlin-training-testing-survey/#7) 
I tried using DataBindingIdlingResource.kt but monitorFragment needs a FragmentScenario as parameter which I don't have because launchFragmentInHiltContainer returns Unit

It would be really helpfull to have an example using the above technologies in https://github.com/android/architecture-samples/tree/dev-hilt

thanks

**Comment by bcorso** [comment]
Hi @wbervoets,

Sorry, I'm not sure there's much I can help with here since the error doesn't look to be coming from anything within Hilt, and I don't have any experience with nav graph. For an issue like this you might have more luck on StackOverflow.

You can also file your example feature request with the corresponding repo: https://github.com/android/architecture-samples/tree/dev-hilt

**Comment by t-kristiansen** [comment]
In `launchFragmentInHiltContainer` you will find that `fragment.action()` is called after the fragment transaction:

```
activity.supportFragmentManager
            .beginTransaction()
            .add(android.R.id.content, fragment, "")
            .commitNow()

fragment.action()
```
Disclaimer: I have never worked with fragment transactions, I'm new at this and Navigation component was already a thing when I started. But, if  I assume the transaction creates the fragment and moves to a lifecycle where the `onViewCreated `method is called, then the problem is that your observer which sets the nav controller is called after that transaction. In that transaction `onViewCreated` is called, which calls `findNavController `before it is set.

If you edit the method and move `fragment.action()` above the transaction, then it will work. At least it did for me, but depending on what code you send with your call other issues may arise, I guess. 

Anyway, I had same problem as you. But I was missing the piece you provided with the observer. So thanks!

**Comment by ajharry69** [comment]
@wbervoets You should be able to find something that helps from the following gist:

- [DataBindingIdlingResource](https://gist.github.com/ajharry69/ea683b2555f86771b9a36992837471bf)
It is a `DataBindingIdlingResource` that you can use to monitor fragment depending on databinding by providing a `Fragment` instance or `FragmentScenario`.

**Comment by wbervoets** [comment]
@ajharry69 thanks for the gist, I tried it but it does not help because the "does not have a NavController set" exception already happens in the launchFragmentInHiltContainer code at

`activity.supportFragmentManager
            .beginTransaction()
            .add(android.R.id.content, fragment, "")
            .commitNow()`

(onViewCreated() is called on the fragment and navGraphViewModels is initialized, which does not find a navcontroller)

as you can see I'm passing in a lambda that sets the navcontroller, but that is only triggered in launchFragmentInHiltContainer via fragment.action() which is invoked after the commitNow() call

**Comment by wbervoets** [comment]
Seems like https://github.com/android/architecture-samples/pull/752 is what I need to get it working

**Comment by ashley-figueira** [comment]
@wbervoets were you able to fix this? If so how? I encountered the same issue but couldnt fix it.

**Comment by wbervoets** [comment]
@ashley-figueira 

I'm currently using:

`
inline fun <reified T : Fragment> launchFragmentInHiltContainer(
    fragmentArgs: Bundle? = null,
    @StyleRes themeResId: Int = R.style.FragmentScenarioEmptyFragmentActivityTheme,
    navHostController: NavHostController? = null,
    fragmentFactory: FragmentFactory? = null,
    crossinline action: T.() -> Unit = {}
): ActivityScenario<HiltTestActivity> {
    val startActivityIntent = Intent.makeMainActivity(
        ComponentName(
            ApplicationProvider.getApplicationContext(),
            HiltTestActivity::class.java
        )
    ).putExtra(EmptyFragmentActivity.THEME_EXTRAS_BUNDLE_KEY, themeResId)

    return ActivityScenario.launch<HiltTestActivity>(startActivityIntent).onActivity { activity ->
        fragmentFactory?.let {
            activity.supportFragmentManager.fragmentFactory = it
        }
        val fragment: Fragment = activity.supportFragmentManager.fragmentFactory.instantiate(
            Preconditions.checkNotNull(T::class.java.classLoader),
            T::class.java.name
        )

        fragment.arguments = fragmentArgs

        navHostController?.let {
            fragment.viewLifecycleOwnerLiveData.observeForever { viewLifecycleOwner ->
                if (viewLifecycleOwner != null) {
                    Navigation.setViewNavController(fragment.requireView(), it)
                }
            }
        }

        activity.supportFragmentManager
            .beginTransaction()
            .add(android.R.id.content, fragment, "")
            .commitNow()

        (fragment as T).action()
    }
}
`

I'm using a Junit4 rule to pass in a TestNavHostController:

`
class TestNavHostControllerRule(
    @NavigationRes private val navigationGraph: Int,
    @IdRes private val currentDestination: Int,
    private val viewModelStore: ViewModelStore = ViewModelStore()
) :
    ExternalResource() {

    lateinit var testNavHostController: TestNavHostController
        private set

    override fun before() {
        super.before()
        // Before test
        testNavHostController = TestNavHostController(ApplicationProvider.getApplicationContext())
        testNavHostController.setViewModelStore(viewModelStore)
        testNavHostController.setGraph(navigationGraph)
        testNavHostController.setCurrentDestination(currentDestination)
    }
}
`
`// This class is used as an empty container activity that is Hilt compatible for use with fragment scenario tests
@AndroidEntryPoint
class HiltTestActivity : AppCompatActivity()`

`
val activityScenario = launchFragmentInHiltContainer<ForgotPasswordFragment>(
            navHostController = testNavHostControllerRule.testNavHostController
        )
`

Using this way allows me to launch the fragment without exceptions even when having the following construct in my fragment:

`private val onboardingViewModel: OnboardingViewModel by navGraphViewModels(
        R.id.onboarding_graph
    ) { defaultViewModelProviderFactory }`


ps: I'm using Databinding so I also need an Espresso Idling resource too

**Comment by goldy1992** [comment]
@ashley-figueira the code from @wbervoets does not work for me either. 
At the point which the fragment is added to the activity
```
 activity.supportFragmentManager
                .beginTransaction()
                .add(android.R.id.content, fragment, "")
                .commitNow()
```
the `testNavHostController` is still not set meaning the setting up of my toolbar fails. This is because the `observeForever` lambda expression is never called. Any idea why?
