### ISSUE TITLE
How to use HiltViewModelFactory in non-Android components

### ISSUE THREAD

**Issue by vincent-paing** [google/dagger#1958]
How can one go about injecting HiltViewModelFactory into non-Android components like Conductor's Controller.. etc. Currently I have this code but it doesn't work, saying HiltViewModelFactory cannot be provided.

```kotlin
@EntryPoint
  @InstallIn(ActivityComponent::class)
  interface MyClassInterface {
    fun viewModelFactory(): HiltViewModelFactory
  }

  private val viewModelStore = ViewModelStore()

  private val viewModelFactory by lazy {
    EntryPoints.get(requireContext(), MyClassInterface::class.java).viewModelFactory()
  }
```

**Comment by danysantiago** [comment]
We'll be working on a way to offer `HiltViewModelFactory` more easily for cases like this, see https://github.com/google/dagger/issues/1938.

I'll close this issue to keep the discussion in one place.
