### ISSUE TITLE
Hilt: Robolectric unit test execution from IDE fails

### ISSUE THREAD

**Issue by b-demuth** [google/dagger#1962]
When attempting to run test class SimpleTest.kt from the simpleKotlin example project or one of its methods directly from Android Studio, the expected activity super classes (Hilt_MainActivity and Hilt_SimpleTest_TestActivity) are not matched. This works fine when running the "testDebugUnitTest" gradle task.
In fact the hilt transform producing these super classes is not even executed. Forcing it to be executed before the gradle task compileDebugUnitTestSources (which is the one that Android Studio executes in this scenario) generates these classes, but they do not end up on the classpath.

I found a workaround for our project by copying these classes over to the "build/intermediates/javac/debugUnitTest/classes/" folder during our gradle build, but this is a really bad solution.
I debugged the hilt gradle plugin a little and to me it seemed hard to come up with a proper fix. I'm not even sure it can be done properly given the way that AS runs unit tests, but hopefully there is something more reasonable we can do about it..

**Comment by danysantiago** [comment]
We have more information about this issue in https://github.com/google/dagger/issues/1956#issuecomment-650336843, we'll be adding more documentation on this current limitation while a fix is being worked on.

**Comment by b-demuth** [comment]
I see. Good to know that you guys are already working on it. Do you think it can be fixed in the gradle plugin or will Android Studio need to be patched?

**Comment by danysantiago** [comment]
We _might_ probably workaround it in the plugin, but I expect a proper solution in Android Gradle Plugin and the Hilt Plugin. For now I'll close this issue to concentrate the conversation in https://github.com/google/dagger/issues/1956

**Comment by b-demuth** [comment]
Ok, fine with me.
