### ISSUE TITLE
The Hilt Android Gradle plugin is applied but no com.google.dagger:hilt-android dependency was found. Multi-Module Gradle setup

### ISSUE THREAD

**Issue by Nikola-Milovic** [google/dagger#1968]
I'll try and be informative on what I am trying to do. So the project is laid out in a manner that, 
1) App module has the gradle configuration that is implemented by the other modules via `apply from: `
2) Library base module has all of the library dependencies that will be included by other modules

So in the project .gradle file we have this setup

```
buildscript {
    apply from: 'dependancies.gradle'
    ext.deps = [

            //Hilt
            hilt: [
                    hiltAndroid               : "com.google.dagger:hilt-android:${versions.hilt}",
                    hiltAndroidCompiler       : "com.google.dagger:hilt-android-compiler:${versions.hilt}",
                    hiltLifeCycleViewModel : "androidx.hilt:hilt-lifecycle-viewmodel:${versions.hilt}",

                    // For tests
                    hiltAndroidTesting        : "com.google.dagger:hilt-android-testing:${versions.hilt}",
                    hiltAndroidCompilerTesting: "com.google.dagger:hilt-android-compiler:${versions.hilt}"
            ]
    ]


    repositories {
        google()
        jcenter()
        mavenCentral()
    }
    dependencies {
        classpath "com.android.tools.build:gradle:4.0.0"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:${versions.kotlin}"

        classpath "com.google.dagger:hilt-android-gradle-plugin:${versions.hilt}"

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

```

In the App module gradle file: 

```
apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'
apply plugin: 'dagger.hilt.android.plugin'
apply plugin: 'kotlin-kapt'


android {
//some code here
}

dependencies {
    implementation project(":library_base")
}

```

And the Library_base looks like this 

```
apply from : "$rootProject.projectDir/app/build.gradle"

dependencies {
    implementation "com.google.dagger:hilt-android:2.28-alpha"
    kapt "com.google.dagger:hilt-android-compiler:2.28-alpha"
}
```

And I get this error `The Hilt Android Gradle plugin is applied but no com.google.dagger:hilt-android dependency was found.
` 
Which is resolved by adding the same lines to the App Module instead of the Libray_base one
```
implementation "com.google.dagger:hilt-android:2.28-alpha"
kapt "com.google.dagger:hilt-android-compiler:2.28-alpha"
```

I am aware of what is happening, just wanted to bring it up, if anyone can give me input as to why this couldn't work and whether or not it should work like this. Thank you!

**Comment by goldy1992** [comment]
Looks to me like something strange is going on with `apply from : "$rootProject.projectDir/app/build.gradle"` in you library base module.

- If it's a library then do you really want to apply: `apply plugin: 'com.android.application'` from your `app/build.gradle` file?
- What happens if you declare the `apply plugin: 'dagger.hilt.android.plugin'` in your library base.
- Furthermore, it looks like your  `app.gradle` file is depending on your library base anyway ( `implementation project(":library_base")` ) so it could possibly be the result of a cyclic dependency issue.

Just a few things so think about.

**Comment by Nikola-Milovic** [comment]
Cyclic dependency it was! Sorry to post an issue with such a trivial problem
