### ISSUE TITLE
Hilt: Compile error on attempt to inject @ActivityContext as member property

### ISSUE THREAD

**Issue by jt-9** [google/dagger#1980]
I am setting Hilt as DI tool in my Kotlin Android project. The issue appears when I try to inject activity context and with qualifier standard `@ActivityContext`. Compile error message:
`This annotation is not applicable to target 'member property with backing field'`

Code sample
```
@AndroidEntryPoint
class TestActivity : AppCompatActivity() {
    @Inject
    @ApplicationContext
    lateinit var context: Context // Okay

    @Inject
    @ActivityContext  // compile error
    lateinit var activityContext: Context 
} 
```
If I annotate property with qualifier `@ApplicationContext` Hilt properly injects it
Dagger Hilt ver `2.28.1-alpha`

**Comment by danysantiago** [comment]
I think this might be occurring because [`@ActivityContext`](https://github.com/google/dagger/blob/master/java/dagger/hilt/android/qualifiers/ActivityContext.java) has no `@Target(ElementType.FIELD)`. I'll confirm that and get a fix going.

**Comment by jt-9** [comment]
Thank you, for quick reply. One more thing: compared declaration of `@ApplicationContext`
```
@Qualifier
@Target({ElementType.METHOD, ElementType.PARAMETER, ElementType.FIELD})
public @interface ApplicationContext {}
```
And `@ActivityContext`
```
@Qualifier
@Retention(RetentionPolicy.CLASS)
@Target({ElementType.TYPE, ElementType.METHOD, ElementType.PARAMETER})
public @interface ActivityContext {}
```
Indeed the `@ActivityContext` is missing `ElementType.FIELD`.
Please note, unlike in declaration of `@ActivityContext` the declaration of `@ApplicationContext` has no `@Retention(RetentionPolicy.CLASS)`, `ElementType.TYPE` should this be corrected as well?
