### ISSUE TITLE
java.lang.IllegalStateException: Given component holder class BankDetailActivity does not implement interface dagger.hilt.internal.GeneratedComponent or interface dagger.hilt.internal.GeneratedComponentManager

### ISSUE THREAD

**Issue by mochadwi** [google/dagger#1994]
I'm trying to implement Hilt inside DFM ([from official docs](https://developer.android.com/training/dependency-injection/hilt-multi-module#dfm)), here's my class:

#### BankDetailActivity.kt
```
    override fun onCreate(savedInstanceState: Bundle?) {
        DaggerWalletComponent.builder()
            .context(this)
            .appDependencies(
                EntryPointAccessors.fromApplication(
                    this,
                    DfmAppDependencies::class.java
                )
            )
            .activityDependencies(
                EntryPointAccessors.fromActivity(
                    this,
                    DfmActivityDependencies::class.java
                )
            )
            .build()
            .inject(this)

        super.onCreate(savedInstance)
  }
```

#### WalletComponent.kt
```
@Component(
    dependencies = [DfmAppDependencies::class, DfmActivityDependencies::class],
    modules = [WalletModule::class]
)
interface WalletComponent {

    fun inject(activity: BankDetailActivity)

    @Component.Builder
    interface Builder {
        fun context(@BindsInstance context: Context): Builder
        fun appDependencies(dependencies: DfmAppDependencies): Builder
        fun activityDependencies(dependencies: DfmActivityDependencies): Builder
        fun build(): WalletComponent
    }
}
```

#### WalletModule.kt
```
@InstallIn(ActivityComponent::class) // error if removed
@Module
abstract class WalletModule {
    @Binds
    abstract fun provideRepository(repo WalletDataRepository): WalletRepository
}
```

#### DfmActivityDependencies.kt
```
@EntryPoint
@InstallIn(ActivityRetainedComponent::class)
interface DfmActivityDependencies {
    fun backgroundExecutor(): CoroutineDispatcher
    fun uiExecetuor(): CoroutineScope
}

// DfmAppDependencies.kt
@EntryPoint
@InstallIn(ApplicationComponent::class)
interface DfmAppDependencies {
    fun restApiService(): RestApiService
}
```

#### NetworkModule.kt
```
@InstallIn(ApplicationComponent::class)
@Module
class NetworkModule {
    @Provides
    fun provideUserToken(@ApplicationContext context: Context): String =
        AppHelpers.getTokenUser(context)

    @Singleton
    @Provides
    fun provideRestApiService(
        @ApplicationContext context: Context,
        userToken: String
    ): RestApiService {
        return RetrofitBuilder(BuildConfig.DEBUG).buildRetrofit(
            baseUrl = BuildConfig.BASE_URL,
            token = userToken,
            chuckerInterceptor = ChuckerInterceptor(context)
        ).create(RestApiService::class.java)
    }
}
```

#### ExecutorModule.kt
```
@InstallIn(ActivityRetainedComponent::class)
@Module
class ExecutorModule {
    @Provides
    fun provideExecutor(): CoroutineDispatcher = Dispatchers.IO

    // TODO(mochadwi): 7/18/20 Provide `viewModelScope` or `Main` instead
    @Provides
    fun provideUiExecutor(): CoroutineScope = object : Closeable, CoroutineScope {
        override fun close() {
            coroutineContext.cancel()
        }

        override val coroutineContext: CoroutineContext
            get() = SupervisorJob() + Dispatchers.Main.immediate
    }
}
```

Is this currently not possible? Or if there's any examples for creating different component and modules inside DFM.

Does use "Dagger as usual" (in the official docs) means using both `dagger:2.28.3` (in DFM) and `hilt-android:2.28.3-alpha` (in base)?

**Comment by mochadwi** [comment]
Strange error thrown in IDE: `e: java.io.IOException: java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 0`

<img width="474" alt="Screen Shot 2020-07-19 at 4 39 50 AM" src="https://user-images.githubusercontent.com/7057959/87862425-0f69b380-c97a-11ea-8929-f8ce937ede4f.png">

<img width="1624" alt="Screen Shot 2020-07-19 at 4 37 43 AM" src="https://user-images.githubusercontent.com/7057959/87862450-6cfe0000-c97a-11ea-9ac5-151fc6fe8153.png">

**Comment by danysantiago** [comment]
Yes, you need to fallback to using vanilla Dagger in the DFM and unfortunately only Application level dependencies can be provided from the app Gradle module.

Specifically the entry point `DfmActivityDependencies` is not possible because its not installed in the `ApplicationComponent`

So, you'll need to:
* Remove `DfmActivityDependencies`, those dependencies will have to come from a module in the DFM component such as the `WalletModule` or you might move the modules that provide them to the `ApplicationComponent` and getters in the `DfmAppDependencies` if possible.
* Use `@DisableInstallInCheck` in the `WalletModule`, so that you are not forced to install it somewhere.

This should lead you to only using an application component entry point that is used as a component dependency in your DFM component. For dependencies that use the DFM activity context, you'll have to use vanilla Dagger modules and declare them in the DFM component.

**Comment by mochadwi** [comment]
Let me clarify your answer: 

> Currently not possible to tells component other than `ApplicationComponent` from `:base` to `:dfm`, thus `:dfm` needs to use vanilla dagger to define custom/activity scoped `Component`? CMIIW @danysantiago 

Does vanilla dagger means include a `dagger:2.28.3` (in DFM) and `hilt-android:2.28.3-alpha` (in base)?

For e.g is this correct?

**Do's**
```
// :base/build.gradle
implementation(hilt)
kapt(hilt_compiler)
```

```
// :dfm/build.gradle
implementation(dagger)
kapt(dagger_compiler)
```

**Don'ts**
```
// :base/build.gradle
api(hilt)
kapt(hilt_compiler)
```

```
// :dfm/build.gradle
kapt(hilt_compiler)
```
