### ISSUE TITLE
[Hilt] `@InstallIn modules cannot have constructors with parameters` for Kotlin module with constructor with default params

### ISSUE THREAD

**Issue by chrisbanes** [google/dagger#1997]
I had the following module, which works fine with Hilt alpha1. I've just updated to 2.28.3-alpha and I now get a build failure due to `@InstallIn modules cannot have constructors with parameters`:

```
@InstallIn(ApplicationComponent::class)
@Module
class TestDataSourceModule(
    private val traktFollowedShowsDataSource: TraktFollowedShowsDataSource = mockk(),
    private val traktEpisodeDataSource: EpisodeDataSource = mockk(),
    private val tmdbEpisodeDataSource: EpisodeDataSource = mockk(),
    private val seasonsDataSource: SeasonsEpisodesDataSource = mockk(),
    private val traktShowDataSource: ShowDataSource = SuccessFakeShowDataSource,
    private val tmdbShowDataSource: ShowDataSource = SuccessFakeShowDataSource,
    private val tmdbShowImagesDataSource: ShowImagesDataSource = SuccessFakeShowImagesDataSource
) {
    ...
}
```

I can workaround it easily enough by moving the properties out of the constructor, but it feels like this should work.

**Comment by bcorso** [comment]
Yeah, that sounds reasonable. I'll fix this.

**Comment by cgdecker** [comment]
(Reopened because the fix was rolled back)

**Comment by bcorso** [comment]
Fix was rolled forward in https://github.com/google/dagger/commit/95ba8340448c13ceab386c967a6b9cc67c7c70cd.

**Comment by ezralazuardy** [comment]
why this error still exist?

![error](https://i.imgur.com/tdYCkHW.png)

I use hilt version ```2.28.3-alpha``` btw.

**Comment by bcorso** [comment]
Hi Ezra, we haven't released a version with this fix yet. 

We'll likely have a new release out next week.

**Comment by ezralazuardy** [comment]
oh okay.. thanks. i'll wait for the next release.

**Comment by JavierSegoviaCordoba** [comment]
Can this problem be related to:

```
class MyViewModel @ViewModelInject constructor(
    private val coroutineContext: CoroutineContext = EmptyCoroutineContext
) : ViewModel() {
    ...
}

If a module provides a CoroutineContext, it should be used, if it is missing, it should use default one.

**Comment by sagarnayak** [comment]
Is this issue fixed yet ??

**Comment by bcorso** [comment]
Yes, it should be fixed since https://github.com/google/dagger/releases/tag/dagger-2.29.1
