### ISSUE TITLE
Custom ImageView doesn't display image with Hilt

### ISSUE THREAD

**Issue by DanShima** [google/dagger#1998]
We have a custom AppCompatImageView that displays images loaded with Glide in our chat app. But it doesn't work anymore after refactoring with Hilt. The images are just not displaying....there is no error or crash. The urls are fine too. When I change it to a regular ImageView, the images can display.
`@AndroidEntryPoint
class ConstrainedImageView @JvmOverloads constructor(context: Context,
                                                     attrs: AttributeSet? = null,
                                                     defStyle: Int = 0)
    : AppCompatImageView(context, attrs, defStyle) {`

I have ruled out injection issues with Glide but here is the code of the module:
`@Module
@InstallIn(ApplicationComponent::class)
class FragmentModule {
    @Provides
    fun provideGlide(@ApplicationContext context: Context): RequestManager = Glide.with(context)
    @Provides
    @IntoSet
    fun provideUploadWidgetHandler(): ChatItemHandler = UploadWidgetHandler()
    .....
}`
What could be the problem here?

**Comment by danysantiago** [comment]
I suspect an issue with default constructor parameters and Hilt transform. Which version of Hilt are you using? We added a check in the latest version to catch this. Also, can you try removing your constructor default parameters to check if it works? Something like this:
```
@AndroidEntryPoint
class ConstrainedImageView @JvmOverloads constructor(
  context: Context,
  attrs: AttributeSet?, 
  defStyle: Int
) : AppCompatImageView(context, attrs, defStyle) {
```

**Comment by DanShima** [comment]
I'm using the latest version 2.28.3-alpha and removing default parameters does not work. Could it be that it's a problem of scope? My fragmentModule is in ApplicationComponent (doesn't work in FragmentComponent yet) and the images are loaded in the ChatFragment

**Comment by DanShima** [comment]
Found the issue....I'm calling `(context as AppCompatActivity).windowManager.defaultDisplay.getMetrics(displayMetrics)` in onMeasure but the context is dagger.hilt.android.internal.managers.ViewComponentManager$FragmentContextWrapper
