### ISSUE TITLE
HILT: Turning off the @InstallIn check during migration

### ISSUE THREAD

**Issue by razza965** [google/dagger#2006]
Hello, 
I was trying to migrate my current project from Dagger to Hilt and have been referencing the document provided here: https://dagger.dev/hilt/migration-guide

As the project is quite large, we are planning on doing a phased migration for the same. Therefore, our requirement was for dagger and Hilt to work along side in different parts of the project. 
Going through the document I found this particular page which disables the @InstallIn checks for projects which are currently migrating: https://dagger.dev/hilt/compiler-options.html#disable-install-in-check

However, I am having some difficulty in understanding where should the following flag be executed: `-Adagger.hilt.disableModulesHaveInstallInCheck=true.`

I have tried adding it to our build setting and a number of other places but it doesn't seem to be working.

Therefore, just wanted to know what is the correct usage of this flag?

**Comment by bcorso** [comment]
You can probably get more help by searching on StackOverflow for how to set the compiler options for your particular build system.

As an example, for an android app built with Gradle, I think you have to add something like this to your `build.gradle` file:

```
android {
    tasks.withType(JavaCompile) {
        configure(options) {
            options.compilerArgs << '-Adagger.hilt.disableModulesHaveInstallInCheck=true'
        }
    }
}
```
