### ISSUE TITLE
Hilt: Library modules cannot find symbol for provides functions when included in application

### ISSUE THREAD

**Issue by landonp1203** [google/dagger#2008]
Kotlin version: 1.3.72
Hilt (android, compiler, and plugin) version: 2.28-alpha

We have a separate library that we share across our android apps.  I have been following the migration guide https://dagger.dev/hilt/migration-guide.  I have removed all the prior Dagger code from our application, but dagger still exists in our library and we currently cannot change that.  Thus we need to use Hilt and Dagger together.

I have used the flag `-Adagger.hilt.disableModulesHaveInstallInCheck=true` since we have a lot of modules, thus I opted for an `AgreggatedModule` with all my modules in it.

We have a module in our library called `CommunicationModule` which includes two other modules like such:
`@Module(includes = {RabbitModule.class, IdentityModule.class, HostnameModule.class})`.  Inside our `SharedFunctionsModule` inside of our app, the `CommunicationModule` is included as such: `@Module(includes = [CommunicationsModule::class])`.  This `SharedFunctionsModule` is added to the `AgreggatedModule`.

When I run a clean build, I get the following error for each provides function inside the `SharedFunctionsModule` that I can't seem to decipher what the problem is (this is just one of about 10):

```
/Users/landon/Desktop/app/build/generated/source/kapt/debug/core/DaggerApplication_HiltComponents_ApplicationC.java:560: error: cannot find symbol
          local = HostnameModule_ProvideHostProviderFactory.provideHostProvider(hostnameModule, SharedFunctionsModule_ProvideAppTypeFactory.provideAppType(sharedFunctionsModule));
                                                           ^
  symbol:   method provideHostProvider(HostnameModule,AppType)
  location: class HostnameModule_ProvideHostProviderFactory
```

The dagger equivalent of this app works perfectly fine and this issue has never cropped up, so its intriguing to see it,  but its blocking a full migration to Hilt.

**Comment by bcorso** [comment]
Hi Landon, 

Can you post the generated code for the class `HostnameModule_ProvideHostProviderFactory`? That might give a clue.

Thanks!

**Comment by landonp1203** [comment]
Thanks for the quick reply!

Here is the generated code:
```kotlin
  private IHostProvider getIHostProvider() {
    Object local = iHostProvider;
    if (local instanceof MemoizedSentinel) {
      synchronized (local) {
        local = iHostProvider;
        if (local instanceof MemoizedSentinel) {
          local = HostnameModule_ProvideHostProviderFactory.provideHostProvider(hostnameModule, SharedFunctionsModule_ProvideAppTypeFactory.provideAppType(sharedFunctionsModule));
          iHostProvider = DoubleCheck.reentrantCheck(iHostProvider, local);
        }
      }
    }
    return (IHostProvider) local;
  }
```

The whole class is actually riddled with errors, here is a screenshot:

<img width="1250" alt="Screen Shot 2020-07-29 at 2 00 45 AM" src="https://user-images.githubusercontent.com/22186474/88762663-9d465b00-d13f-11ea-8eeb-f75258189ce8.png">

**Comment by bcorso** [comment]
So typically, this happens when you forget to add the Dagger compiler (`com.google.dagger:dagger-compiler:<VERSION>`) to the Gradle library that contains the Dagger module itself.

Are these Dagger modules in a separate Gradle library? If so, can you confirm that you've added the `dagger-compiler` dependency in the `build.gradle` file for that library?

**Comment by landonp1203** [comment]
In the `SharedFunctions` library we have the compiler:

```
    (daggerVersion = 2.14.1)

    // Dagger Android
    implementation "com.google.dagger:dagger:$project.daggerVersion"
    implementation "com.google.dagger:dagger-android-support:$project.daggerVersion"
    annotationProcessor "com.google.dagger:dagger-compiler:$project.daggerVersion"
    annotationProcessor "com.google.dagger:dagger-android-processor:$project.daggerVersion"
```

We are not using `kapt` in this library since its a pure Java library.

Our application module does not have the `com.google.dagger:dagger-compiler:<VERSION>`  though since I removed it in the migration to Hilt.

**Comment by bcorso** [comment]
Thanks! A couple more questions if you don't mind:

  1. Can you check the `build` directory in the `SharedFunctions` Gradle library to see if the factory is generated?
  2. How does your main app depend on this library (e.g. is it a direct dependency or transitive? Is it `implementation` or `api`?)
  3. Are you using the same Dagger version across all Gradle libraries in your application?
  4. The Dagger version is pretty old here, is it possible to upgrade to see if this reproduces on the latest versions?

**Comment by landonp1203** [comment]
So in my curiosity, I went right for number #4 and it worked.  Upgrading `2.14.1 -> 2.28.3` did the trick.  I still call it black magic what you guys do!

However, I'd still like to give you more information to drill this down:

1. Here is the generated factory from the `2.14.1` build:
```
// Generated by Dagger (https://google.github.io/dagger).
package org.gtri.deltaxray.sharedfunctions.communications.hostname;

import dagger.internal.Factory;
import dagger.internal.Preconditions;
import javax.inject.Provider;
import org.gtri.deltaxray.sharedfunctions.identity.AppType;

public final class HostnameModule_ProvideHostProviderFactory implements Factory<IHostProvider> {
  private final HostnameModule module;

  private final Provider<AppType> appTypeProvider;

  public HostnameModule_ProvideHostProviderFactory(
      HostnameModule module, Provider<AppType> appTypeProvider) {
    this.module = module;
    this.appTypeProvider = appTypeProvider;
  }

  @Override
  public IHostProvider get() {
    return Preconditions.checkNotNull(
        module.provideHostProvider(appTypeProvider.get()),
        "Cannot return null from a non-@Nullable @Provides method");
  }

  public static HostnameModule_ProvideHostProviderFactory create(
      HostnameModule module, Provider<AppType> appTypeProvider) {
    return new HostnameModule_ProvideHostProviderFactory(module, appTypeProvider);
  }

  public static IHostProvider proxyProvideHostProvider(HostnameModule instance, AppType appType) {
    return Preconditions.checkNotNull(
        instance.provideHostProvider(appType),
        "Cannot return null from a non-@Nullable @Provides method");
  }
}
```
2. Our main app depends on it through a direct dependency using `implementation`.
3. This is the only other library that we use that actually has dagger.  The others are just pure java libraries that don't need dependency injection on their own.
4. 🎉🎉🎉🎉

Looks like a compatibility issue from my understanding, but you would definitely know better than me.

**Comment by bcorso** [comment]
Thanks for providing the extra details!

The issue is likely that the Hilt plugin enables [fastInit](https://dagger.dev/dev-guide/compiler-options#fastinit-mode) by default, but fastInit wasn't fully functional in version 2.14.1.

Either way, upgrading all of your libraries to the same version (if possible) is definitely the way to go in this case.
