### ISSUE TITLE
Dependencies should be allowed to have multiple qualifier annotations.

### ISSUE THREAD

**Issue by amb-it-ion** [google/dagger#201]
Would you consider merging a well written+tested pull request, allowing dependencies to have multiple qualifier annotations? Are there any plans that I would need to be aware of before starting?

**Comment by JakeWharton** [comment]
JSR330 forbids this.

**Comment by amb-it-ion** [comment]
That ... is unfortunate. Are annotation compositions allowed?

**Comment by JakeWharton** [comment]
You can put explicit combinations together in a specific new annotation's
members but you cannot arbitrarily define an annotation for combing any
number of annotations.

**Comment by amb-it-ion** [comment]
I had a feeling you would say that. I can see how this spec simplifies qualifiers, but it still feels inappropriately limiting. 

In any case, this issue can be closed.

**Comment by hjohn** [comment]
> JSR330 forbids this.

This is incorrect, from the JSR-330 `@Inject` docs, emphasis mine:

> A qualifier may annotate an injectable field
> or parameter and, combined with the type, identify the implementation to
> inject. Qualifiers are optional, and when used with `@Inject` in
> **injector-independent classes**, no more than one qualifier should annotate a
> single field or parameter.

This states that no more than one qualifier should annotate a single field or parameter **if** you want to remain injector-independent.  The wording was specifically changed to allow for multiple qualifiers as long as users understand that this means they might be tied to a specific injector implementation.  See discussion here, last few comments: https://code.google.com/archive/p/atinject/issues/2

**Comment by NadChel** [comment]
Shall we reopen then?
