### ISSUE TITLE
DaggerTestApplication doesn't generates

### ISSUE THREAD

**Issue by antonlazarchenko** [google/dagger#2011]
Please, help to understand why DaggerTestApplication.java doesn't generates.

I've extended my AppComponent

```

@Singleton
@Component(
    modules = {
        ListPresenterTestModule.class,
    }
)
public interface TestComponent extends AppComponent {
    void inject(ListPresenterTest presenter);
}


@Module
public class ListPresenterTestModule {

    @Provides
    ListContract.Presenter provideListPresenter(){
        return new ListPresenter();
    }
}

```

And using it at test class like this

```

public class ListPresenterTest {

    @Inject
    ListContract.Presenter presenter;

    @Before
    public void setPresenter() {
        TestComponent component = DaggerTestComponent.builder().build();
        component.inject(this);
    }

    @Test
    public void calculate() {
        assertTrue(presenter != null);
    }
}

```
Gradle

```
    //dagger
    implementation 'com.google.dagger:dagger:2.28'
    annotationProcessor 'com.google.dagger:dagger-compiler:2.28'
    api 'com.google.dagger:dagger-android:2.28'
    api 'com.google.dagger:dagger-android-support:2.28'
    annotationProcessor 'com.google.dagger:dagger-android-processor:2.28'

    //android test
    androidTestAnnotationProcessor 'com.google.dagger:dagger-compiler:2.28'
    //JUnit test
    testAnnotationProcessor 'com.google.dagger:dagger-compiler:2.28'

```

**Comment by bcorso** [comment]
Hi Anton, can you post any errors you get when compiling?

Nothing really sticks out to me in the code you posted. If you can share a minimal, reproducible, example project I can help debug further.

**Comment by antonlazarchenko** [comment]
> Hi Anton, can you post any errors you get when compiling?
> 
> Nothing really sticks out to me in the code you posted. If you can share a minimal, reproducible, example project I can help debug further.

Hi, Brad! Thanks for reply.

Compiling gives me following:
```

app\src\test\java\com\foxminded\mvp\di\TestComponent.java:21: error: [Dagger/MissingBinding] com.foxminded.mvp.ui.screen.list.ListContract.Presenter cannot be provided without an @Provides-annotated method.
public interface TestComponent extends AppComponent {
       ^
      com.foxminded.mvp.ui.screen.list.ListContract.Presenter is injected at
          com.foxminded.mvp.ui.screen.list.ListPresenterTest.presenter
      com.foxminded.mvp.ui.screen.list.ListPresenterTest is injected at
          com.foxminded.mvp.di.TestComponent.inject(com.foxminded.mvp.ui.screen.list.ListPresenterTest)
  It is also requested at:
      com.foxminded.mvp.ui.screen.list.ListFragment.presenter
  The following other entry points also depend on it:
      com.foxminded.mvp.ui.di.AppComponent.inject(com.foxminded.mvp.ui.screen.list.ListFragment) [com.foxminded.mvp.di.TestComponent]
```

Seems like I'm using dependencies in wrong way. What am I using wrongfully?

I've added not example but a part of my test project where I faced this issue.
There is android studio project. Also added project.zip.
Have a look, please 
src/test/java/com/foxminded/mvp/ui/screen/list/ListPresenterTest.java

https://drive.google.com/drive/folders/1ezu7Q4OjM7pExogEYr6eR0c9bSyXkMIX?usp=sharing

**Comment by bcorso** [comment]
From an off-thread post it sounds like the component wasn't being generated because there was a missing binding, which is WAI. 

If you need help providing the missing binding, StackOverflow will generally be a better place to answer those types of questions.

**Comment by antonlazarchenko** [comment]
Hi, Brad! Thanks for reply.
You are right.
First time using dagger this way and my mistake was that I naively used "build project" instead of "run project", because first one gives me no errors and build was successfull. Problem is solved.
Sorry for bothering.
