### ISSUE TITLE
Singleton ViewModel not being returned for different fragments

### ISSUE THREAD

**Issue by mannyvw** [google/dagger#2019]
HI 

Have two fragments referencing the same view model, but get two copies, is this a bug or am I doing something wrong ?

`
**build.gradle**
   // For injecting ViewModel
    implementation 'androidx.hilt:hilt-lifecycle-viewmodel:1.0.0-alpha02'
    // For injecting WorkManager
    implementation 'androidx.hilt:hilt-work:1.0.0-alpha02'

**SongbookViewModel**
class SongbookViewModel @ViewModelInject constructor(
    private val mediaRepository: MediaRepository
) : ViewModel() {
....

**PlaylistFragment**
@AndroidEntryPoint
class PlaylistFragment : Fragment() {
    private val songbookViewModel: SongbookViewModel by viewModels()
....

**SongbookFragment**
@AndroidEntryPoint
class SongbookFragment : Fragment() {
    private val songbookViewModel: SongbookViewModel by viewModels()
....`

Both seem to in the fragment scope, but get two copies my understanding is I should get 1 they can share ?

Thanks

**Comment by dmapr** [comment]
I don't think it's a Hilt or Dagger problem. The default view model store is bound to the fragment instance, so each fragment would get their own copy. You need to bind both view models to the same store. If one of the fragments is a parent one, try `by viewModels({parentFragment ?: this})` in the child fragment. If both fragments only have an activity in common, then you'll need to use the activity store for both.

**Comment by danysantiago** [comment]
Yup, like mentioned above try either using the view model store of the parent fragment or the activity's, for the activity one there is also a ktx extension: `by activityViewModels()`. More info here: https://developer.android.com/topic/libraries/architecture/viewmodel#sharing
