### ISSUE TITLE
Hilt: How to prevent Hilt from picking dependency from a library?

### ISSUE THREAD

**Issue by theapache64** [google/dagger#2025]
Okay, let's make this simple.

I have created a simple library called `my-network-library` with two classes in it. First one is a Hilt module called `BaseNetworkModule`

```kotlin
@Module
@InstallIn(ApplicationComponent::class)
object BaseNetworkModule {

    // Client
    @Singleton
    @Provides
    fun provideOkHttpClient(): OkHttpClient {
        return OkHttpClient.Builder()
            // my default okhttp setup goes here 
            .build()
    }
}
```
and the second one is a simple class.

```kotlin
class MyAwesomeClass {
    fun doMagic() {
        // magic code goes here
    }
}
```

Now I want to use `MyAwesomeClass` in one of my App. So I added the dependency in the app.

```groovy
implementation "com.theapache64:my-awesome-library-1.0.0"
```

I also have some network call implementation and I don't want to use `OkHttpClient` from `my-network-library`. So I've created a module in the app to get my own instance of `OkHttpClient`.

```kotlin
@Module
@InstallIn(ApplicationComponent::class)
object NetworkModule {

    @Singleton
    @Provides
    fun provideOkHttpClient(): OkHttpClient {
        return OkHttpClient.Builder()
            // CUSTOM CONFIG GOES HERE 
            .build()
    }
}
```

Now am getting below error.

> error: [Dagger/DuplicateBindings] okhttp3.OkHttpClient is bound
> multiple times:

I know it's because of the `@Provides` declared in the `my-network-library`, but I didn't specify `includes` to the `@Module` annotation to inherit dependency from `BaseNetworkModule`. The issue may be fixed using `@Qualifier` annotation, but IMO, that'd be a workaround. 

so my question is 
- Why dependency from a library module comes into the app module without using `includes` of `@Module`?
- How to tell Hilt "Do not look for @Provides in external libraries (gradle dependencies) ?" unless I mark the module with `@Module(includes = XXXModule)`

Source : https://stackoverflow.com/questions/63276876/how-to-prevent-hilt-from-picking-dependency-from-a-library

**Comment by bcorso** [comment]
Hi Shifar,

> Why dependency from a library module comes into the app module without using includes of @Module?

This behavior is WAI. All bindings, even from libraries, are merged into the same components.

Using `Modules.includes` doesn't have any special behavior. It just includes the module into the same component as the one you're attaching it to. For example, the code below is equivalent installing both `ModuleA` and `ModuleB` into the `ApplicationComponent`. Using `Module.includes` is really only needed if you don't own `ModuleB` and so can't annotate it directly with `@InstallIn`.

```
@Module(includes = ModuleB.class)
@InstallIn(ApplicationComponent.class)
interface ModuleA {}
```

> How to tell Hilt "Do not look for @provides in external libraries (gradle dependencies) ?" unless I mark the module with @Module(includes = XXXModule)

As you mentioned, if you want your external library to have it's own `OkHttpClient` then you need to mark it with a qualifier. A good rule of thumb for a library is to not bind types you don't own without using a qualifier. So in this example, you don't own `OkHttpClient`, so it's quite possible that the main app or another library will want to bind that same type and cause a conflict. Using a qualifier also allows you to prevent other apps from accidentally injecting your `OkHttpClient` by making the qualifier non-public.
