### ISSUE TITLE
Dagger  kotlin.UninitializedPropertyAccessException

### ISSUE THREAD

**Issue by sundravel** [google/dagger#2028]
I recently started practicing dagger, so that i can integrate dagger in my app

1)ViewModelFactory.kt
@AppScope
class ViewModelFactory @Inject constructor(private val creators: Map<Class<out ViewModel>, @JvmSuppressWildcards Provider<ViewModel>>) : ViewModelProvider.Factory {

    @SuppressWarnings("Unchecked")
    override fun <T : ViewModel?> create(modelClass: Class<T>): T {
        var creator = creators[modelClass]

        if (creator == null) {
            for (entry in creators) {
                if (modelClass.isAssignableFrom(entry.key)) {
                    creator = entry.value
                    break
                }
            }
        }

        if (creator == null) throw IllegalArgumentException("Unknown model class" + modelClass)

        try {
            return creator.get() as T
        } catch (e: Exception) {
            throw RuntimeException(e)
        }
    }
}

2)ViewModelkey.kt
@Documented
@Target(AnnotationTarget.FUNCTION)
@Retention(AnnotationRetention.RUNTIME)
@MapKey
internal annotation class ViewModelKey(val value: KClass<out ViewModel>)

3)ViewModelModule.kt
@Module
abstract class ViewModelModule {
    @AppScope
    @Binds
    @IntoMap
    @ViewModelKey(HomeViewModel::class)
    abstract fun bindUserViewModel(userViewModel: HomeViewModel): ViewModel

    // Factory
    @AppScope
    @Binds
    abstract fun bindViewModelFactory(vmFactory: ViewModelFactory): ViewModelProvider.Factory

}

4)ContextModule.kt

@Module
class ContextModule constructor(private val context: Context) {

    @AppScope
    @Provides
    internal fun provideCOntext():Context = context

}

5)My App Component

@AppScope
@Component(modules = [ContextModule::class,ViewModelModule::class])
interface AppComponent {
    fun inject(activity: MainActivity)
}

6)In My Fragment
class HomeFragment : Fragment() {

    private lateinit var homeViewModel: HomeViewModel

    @Inject
    lateinit var viewModelFactory: ViewModelProvider.Factory
    override fun onCreateView(
        inflater: LayoutInflater,
        container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View? {
        return inflater.inflate(R.layout.fragment_home, container, false)
    }

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)
        SampleApplication.component.inject(activity = activity as MainActivity)
        homeViewModel = ViewModelProvider(this, viewModelFactory).get(HomeViewModel::class.java)
        homeViewModel.text.observe(viewLifecycleOwner, Observer {
            text_home?.text = it
        })

    }
}

But every time when i run the app, i get the following exception
 kotlin.UninitializedPropertyAccessException: lateinit property viewModelFactory has not been initialized
        at com.example.daggersample.ui.home.HomeFragment.onViewCreated(HomeFragment.kt:33)

**Comment by dmapr** [comment]
`SampleApplication.component.inject(activity = activity as MainActivity)`

That would inject the `MainActivity`. You need to pass `this` to the inject to inject your fragment.

**Comment by sundravel** [comment]
> `SampleApplication.component.inject(activity = activity as MainActivity)`
> 
> That would inject the `MainActivity`. You need to pass `this` to the inject to inject your fragment.

but in my app component   fun inject(activity: MainActivity) for inject have passed mainactivity as parameter

so when i my pass this to inject, it shows error required MainActivity found HomeFragment

**Comment by sundravel** [comment]
> `SampleApplication.component.inject(activity = activity as MainActivity)`
> 
> That would inject the `MainActivity`. You need to pass `this` to the inject to inject your fragment.

**Comment by danysantiago** [comment]
For every field / member injected class you need to add a method to your component, in your `AppComponent` add one for your fragment:
```

**Comment by danysantiago** [comment]
The Android Docs pages has some documentation on getting your started: https://developer.android.com/training/dependency-injection/dagger-android#injecting-activities

**Comment by sundravel** [comment]
> For every field / member injected class you need to add a method to your component, in your `AppComponent` add one for your fragment:
> 
> ```
> interface AppComponent {
>   fun injectFragment(f: HomeFragment)
> }
> ```

okay thank,its working now, can you help me with one more thing,can you tell how can i pass activity context, i'm getting following exception

    java.lang.ClassCastException: com.fitsense.base.SampleApplication cannot be cast to android.app.Activity
