### ISSUE TITLE
I have a few questions about dagger hilt:

### ISSUE THREAD

**Issue by MadRatSRP** [google/dagger#2034]
1)How can i provide dependency with void return type?
For example, i want to provide as dependency this code:
if (!Places.isInitialized()) {
            Places.initialize(context, key)
        }
2)I would like to provide ViewBinding dependency - 2 questions here, does ViewBinding classes have its parent class you can inherit from? And how can i use activity as parameter for provider?
I'm trying to use it like that:
@Module
@InstallIn(ActivityComponent::class)
object ViewBindingModule {
    @Provides
    fun provideBinding(@ActivityContext activity: FragmentActivity): ActivityMapsBinding {
        return ActivityMapsBinding.inflate(activity.layoutInflater)
    }
}
But it gives me errors, maybe i'm doing something wrong
3)How can i provide mapFragment as dependency? Here its code for initialization
        mapFragment = supportFragmentManager.findFragmentById(R.id.map) as SupportMapFragment
4)I would like to pass fragment as a argument for provider, how can i do it?

Sorry for so many questions, i know its not a Stackoverflow, but i didnt find this kind of information neither in Dagger Hilt documentation, nor in articles about Dagger Hilt

**Comment by danysantiago** [comment]
1. You can't provide a dependency of type 'void', you'll need to provide a class with a method with the logic you described.
2. I'm not sure what you are trying to ask here, but the `@Module` you described seems wrong, specifically the `@ActivityContext` is a qualifier for a `Context` not for a `FragmentActivity`, maybe thats your error?
3. Have you try adding an `@Provides` method to a module?
4. Hilt has built-in bindings, `Fragment` is one of them when you install `@Module`-annotates classes in the `FragmentComponent`.

These questions are really better asked in https://stackoverflow.com/ where there is a greater community that can help you.  
Also consider the documentation available in the Android Dev website: https://developer.android.com/training/dependency-injection/hilt-android
