### ISSUE TITLE
Wrong error in @Binds attempt

### ISSUE THREAD

**Issue by dragossusi** [google/dagger#2039]
Hello,

I have had a problem that took a while to solve and didn't know what was the cause of it,

I have a modular Android project and i keep my repository interfaces in a module called `database`, for example:

`interface RecipientRepository`

The implementation of this interface is found in two modules called `dev` and `mock`.

The mock class looks like this:

```
@Singleton
class RecipientRepositoryMock @Inject constructor() : RecipientRepository
```

My android application is using flavors so i have flavors for mock and dev, so i use this in gradle:

```
    mockImplementation project(":mock")
    devImplementation project(":dev")

    //hardcoded data
    testImplementation project(":mock")
```

Our server had some problems so i had to switch to mock data on dev flavor, wrote this in my dagger module:

```
    @Binds
    abstract fun bindRecipientRepository(repository: RecipientRepositoryMock): RecipientRepository
```

Looks like Android Studio lets me autocomplete RecipientRepositoryMock and brings no error.

All seems fine but when i try to run i get this error:
```
FlavorDataModule.java:76: error: @Binds methods' parameter type must be assignable to the return type
    public abstract repository.RecipientRepository bindRecipientRepository(@org.jetbrains.annotations.NotNull()
```

I think binds should first check if the class specified as paramter exists before checking if it extends the return type, I got no clue that the class could not be found because i forgot to add my mock dependency to the application.

This is an error with Android Studio, but it may improve debugging for others.

**Comment by bcorso** [comment]
Hi Rachieru, 

Thanks for reporting! 

I'll take a look and see if there's anything we can do about it.

**Comment by bcorso** [comment]
Hmm, I couldn't reproduce this. I'm using AndroidStudio 4.0.1 and it errors with "cannot resolve symbols" when using a source that's not in the current flavor's source set.

Just to make sure we're on the same page, here's what I did. I created two flavors, `flavor1` and `flavor2`, and only defined `Foo` in `flavor1`. If I try to use `Foo` when building `flavor2Debug` or `flavor2Release` it errors.

**Comment by dragossusi** [comment]
add ```testImplementation flavor1``` and it will think it is good to use for main sources

**Comment by bcorso** [comment]
Sorry, that also results in a "cannot resolve symbol" error for me. 

If you can link to a minimum reproducing example along with your version of AndroidStudio I can look into it further.

**Comment by dragossusi** [comment]
I will try to create a sample project asap, i can;t publish the source code since is work related.

**Comment by bcorso** [comment]
I'm going to close this since its been a while without a response. Feel free to still add a repro and I'll open it back up.
