### ISSUE TITLE
Question: How does @ViewModelInject work?

### ISSUE THREAD

**Issue by dragossusi** [google/dagger#2049]
Does hilt generate a factory for every viewmodel constructor i use or does it work like an injected constructor and binded in a set?

I saw a lot of samples using injected constructors and i think it is a bad pattern to foreach a set and reflection to find if the entry is the desired ViewModel.

I am planning to migrate to Hilt only if it generates a factory for every ViewModel i annotate.

**Comment by danysantiago** [comment]
For every `@ViewModelInject` the [androidx.hilt compiler](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-master-dev:hilt/hilt-compiler/src/main/kotlin/androidx/hilt/AndroidXHiltProcessor.kt) will generate a [`ViewModelAssistedFactory`](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-master-dev:hilt/hilt-lifecycle-viewmodel/src/main/java/androidx/hilt/lifecycle/ViewModelAssistedFactory.java) along with a `@Module` installed on the `ActivityRetainedComponent` that binds the assisted view model factory into a multi-binding map that is eventually used by the [`HiltViewModelFactory`](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-master-dev:hilt/hilt-lifecycle-viewmodel/src/main/java/androidx/hilt/lifecycle/HiltViewModelFactory.java;l=48). The `HiltViewModelFactory` is used as the default view model factory for every `@AndroidEntryPoint`-annotated activity and fragment and thus creating your ViewModels using the assisted factories map.
