### ISSUE TITLE
Android Studio deleting generated Dagger component

### ISSUE THREAD

**Issue by f-carranza** [google/dagger#2060]
Hi,

when I do a rebuild generated classes are created correctly. But If I make a change in the module and launch a "Run", generated components are deleted and not generated again.

Why is occurring this?

**Comment by danysantiago** [comment]
Hey - Is this causing you some sort of error? Or are you just seeing the generated classes as missing in the IDE but things work fine? If its the latter it might be an Android Studio indexing issue. Either way it might be best to file a bug on the Studio team at https://developer.android.com/studio/report-bugs#studio-bugs
