### ISSUE TITLE
Hilt and ViewModel injection without  additional dependencies

### ISSUE THREAD

**Issue by AlexTrotsenko** [google/dagger#2063]
I like how Hilt simplifies DI in Android comparing to the plain Dagger. 
But I am wondered whether `androidx` dependencies are _required_ for _ViewModel_ injections. And what is more import - whether  separate `@ViewModelInject` annotation is required..

My current solution _(with Dagger only)_ is to inject ViewModel factory, which uses Dagger's Provider once creation of new ViewModel is requested _(with all the arguments injected by Dagger)_. The same solution working fine with Hilt as well. 

Thus following become not required anymore:
-  ` implementation 'androidx.hilt:hilt-lifecycle-viewmodel:xxx`
-  ` kapt 'androidx.hilt:hilt-compiler:1.0.0-alpha01'`
- `@ViewModelInject` instead of standard `@Inject` on ViewModel's constructor. 

Perhaps I am missing something and I would be happy to learn what are the benefits of using `androidx.hilt` approach comparing to one, which I mentioned earlier?

Some code just in case:

1. ViewModel:
```Kotlin
class MyViewModel @Inject constructor(
    private val dispatcherProvider: CoroutinesDispatcherProvider
) : ViewModel() {
    ...
}
```

2. Fragment with Injected ViewModel:

```Kotlin
@AndroidEntryPoint
class MyFragment : Fragment(R.layout.fragment_my) {
    @Inject lateinit var viewModelFactory: ViewModelByDaggerFactory<MyViewModel>
    private val viewModel: MyViewModel by viewModels() { viewModelFactory }
    ...
}
```

3. And generic dagger-based ViewModelFactory:

```Kotlin
/**
 * Create view model using Dagger dependencies graph.
 *
 * So any view model with @Inject constructor() can be used as VM type argument.
 *
 * @param VM should match type of requested view model. Otherwise Dagger compilation might fail.
 */
class ViewModelByDaggerFactory<VM : ViewModel> @Inject constructor(
    private val viewModelProvider: Provider<VM>
) : ViewModelProvider.Factory {

    private fun newViewModel(): VM = viewModelProvider.get()

    override fun <T : ViewModel> create(modelClass: Class<T>): T {
        //ViewModel as declared by generic type of ViewModelByDaggerFactory
        val newViewModel = newViewModel()

        return safeCast(modelClass, newViewModel)
    }

    /**
     * @return newViewModel itself if its class is sub-type generic T or throws otherwise.
     *
     * Note: if ViewModel generic type is not matching type of requested view model:
     * dagger compilation might fail because dagger will not be able to find class matching.
     */
    @Suppress("UNCHECKED_CAST")
    private fun <T : ViewModel> safeCast(modelClass: Class<T>, newViewModel: VM): T {
        if (modelClass.isInstance(newViewModel)) {
            return newViewModel() as T
        } else {
            throw IllegalArgumentException("Requested ViewModel type $modelClass is not matching generic type declared on ViewModelByDaggerFactory: " + newViewModel.javaClass)
        }
    }
}
```

**Comment by danysantiago** [comment]
One benefit of `androidx.hilt:hilt-lifecycle-viewmodel` is that it will also enable you to use a [`SavedStateHandle`](https://developer.android.com/reference/androidx/lifecycle/SavedStateHandle) if requested in your ViewModel constructor. We also decided for now to go with a dedicated annotation, since by using `@Inject` you make the ViewModel injectable anywhere which can be misleading since it has to be provided by the view model factory otherwise it won't be retained. By not using `@Inject` we make it so you can't accidentally inject the ViewModel directly in say a Activity's field.
