### ISSUE TITLE
Orientation change in Android Hilt Espresso testing

### ISSUE THREAD

**Issue by gdagnall** [google/dagger#2066]
I am converting older Android Espresso tests to include Hilt. All is going well, but I cannot find any info on how to change the activity orientation. 

Without Hilt, I was able to change the orientation with this Java code.

ActivityTestRule<MyActivity> mActivityRule = new ActivityTestRule<MyActivity>(MyActivity::class.java) {...};
mActivityRule.getActivity().setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_PORTRAIT);
mActivityRule.getActivity().setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE);

The new Android Hilt code looks like the following Kotlin code.

    @get:Rule
    var hiltRule = HiltAndroidRule(this)

    private lateinit var mActivityRule: ActivityScenario<MyActivity>

    @Before
    fun setUp() {
        hiltRule.inject()
        mActivityRule = ActivityScenario.launch(MyActivity::class.java)
    }

But I can't find any reference on how to change the orientation with HiltAndroidRule or ActivityScenario.

Is it possible to change the activity orientation with Hilt?

**Comment by bcorso** [comment]
AFAIK, Hilt doesn't force you to use the ActivityScenario. 

I would keep using `ActivityTestRule` if that's what you were using before. If you want to migrate to `ActivityScenario`, StackOverflow is probably a better place to ask that question.

**Comment by bcorso** [comment]
I'm going to close this for now, but let me know if https://github.com/google/dagger/issues/2066#issuecomment-682034781 didn't get you past your issue.
