### ISSUE TITLE
Enum class in List cannot be provided

### ISSUE THREAD

**Issue by skywall** [google/dagger#2067]
I'm facing the issue when I try to inject enum class instance wrapped in `List`. This is my current code:
```kotlin
// Uncomment Days class or enum class

// 1. Doesn't work
//enum class Days {
//    MO, TU, WE
//}

// 2. Works
class Days

@Module
class MyModule {
    @Provides
    fun days(): List<Days> = listOf()
}

class MyManager @Inject constructor(val days: List<Days>)

@Component(modules = [MyModule::class])
interface MyComponent {
    fun myManager(): MyManager
}

fun main() {
    val component = DaggerMyComponent.builder()
        .myModule(MyModule())
        .build()

    val manager = component.myManager()

    print(manager.days)
}
```

When I uncomment section 1. (enum class) compilation fails with the following exception:
```
/Users/skywall/Projects/kotlin/DaggerEnumIssues/build/tmp/kapt3/stubs/main/MyComponent.java:6: error: [Dagger/MissingBinding] java.util.List<? extends Days> cannot be provided without an @Provides-annotated method.
public abstract interface MyComponent {
                ^
      java.util.List<? extends Days> is injected at
          MyManager(days)
      MyManager is requested at
          MyComponent.myManager()
```
Whereas uncomment of section 2. (standard Kotlin class) works without issues. I'm not sure if it's Dagger or Kotlin compiler issue. I haven't found any documentation regarding this problem, so I decided to open a case. You can reproduce this by uncommenting a particular section (1.) in the following [project](https://github.com/skywall/dagger-enum-list-issue).

**Comment by bcorso** [comment]
From the error message, it looks like the generated java stub for `MyManager` is trying to inject `List<? extends Days>` rather than `List<Days>`. Dagger is strict about types, so it doesn't treat those two as the same. To fix, I think you would need to add `@JvmSuppressWildcards` like:

```kotlin
class MyManager @Inject constructor(val days: @JvmSuppressWildcards List<Days>)
```

See https://medium.com/androiddevelopers/dagger-in-kotlin-gotchas-and-optimizations-7446d8dfd7dc

**Comment by bcorso** [comment]
I'm going to close this assuming https://github.com/google/dagger/issues/2067#issuecomment-682729058 fixed the issue. Feel free to let me know if that's not the case.
