### ISSUE TITLE
Hilt unable to use neither @Named nor @Qualifier annotation when @Binds an interface implementation

### ISSUE THREAD

**Issue by mochadwi** [google/dagger#2074]
### Actual Dependency
```
class UserAssesmentRepositoryImpl
@Inject
constructor(
    private val token: String,
    private val caliberService: UserAssesmentRestApiInterface
) : UserAssesmentRepository { /* omitted */ } 
``` 

### Hilt
```
// CustomQualifier.kt
@Qualifier
@Retention(AnnotationRetention.BINARY)
annotation class TalentPoolType
```

```
// DynamicFormModule.kt
@InstallIn(ApplicationComponent::class)
@Module
interface DynamicFormModule {

    @get:[
              Binds 
              TalentPoolType // removing this the code gen succeed
    ]
    val UserAssesmentRepositoryImpl.bindTalentPool: UserAssesmentRepository
}
```

```
@InstallIn(ApplicationComponent::class)
@Module
class NetworkModule {
    @Provides
    fun provideUserToken(@ApplicationContext context: Context): String =
        AppHelpers.getTokenUser(context)

    @TalentPoolType // removing this the code gen succeed
    @Provides
    fun provideAssessmentService(
        @ApplicationContext context: Context,
        userToken: String
    ): UserAssesmentRestApiInterface {
        return makeRetrofit(userToken, context, BuildConfig.BASE_URL_CALIBER).create(
            UserAssesmentRestApiInterface::class.java
        )
    }
}
```

### Injected into an activity
```
// AbcActivity.kt

@AndroidEntryPoint

class AbcActivity : AppCompatActivity {
  @field:[Inject TalentPoolType] internal lateinit var repository: UserAssesmentRepository
}
```

Please CMIIW, looks like something missing in my setup

### Spec
Hilt: 2.28.3-alpha
Kotlin: 1.3.72
AGP: 4.0.1
GW: 6.5.1

### Error Log

```
error: [Dagger/MissingBinding] our.company.data.source.api.UserAssesmentRestApiInterface cannot be provided without an @Provides-annotated method.
public abstract static class SingletonC implements MyApp_GeneratedInjector,
^
our.company.data.source.api.UserAssesmentRestApiInterface is injected at
our.company.data.source.repositories.UserAssesmentRepositoryImpl(…, caliberService)
our.company.data.source.repositories.UserAssesmentRepositoryImpl is injected at
our.company.activities.main.revamp.availablejobs.timebased.di.DynamicFormModule.getBindTalentPool($this$bindTalentPool)
@our.company.activities.main.revamp.availablejobs.timebased.di.TalentPoolType our.company.data.source.repositories.UserAssesmentRepository is injected at
our.company.activities.main.revamp.availablejobs.timebased.AbcActivity.repo
our.company.activities.main.revamp.availablejobs.timebased.AbcActivity is injected at
our.company.activities.main.revamp.availablejobs.timebased.AbcActivity_GeneratedInjector.injectAbcActivity(our.company.activities.main.revamp.availablejobs.timebased.AbcActivity) [our.company.activities.MyApp_HiltComponents.SingletonC → our.company.activities.MyApp_HiltComponents.ActivityRetainedC → our.company.activities.MyApp_HiltComponents.ActivityC]
```

**Comment by bcorso** [comment]
From the error path, it looks like it's depending on the unqualified `UserAssesmentRestApiInterface`:

```
  AbcActivity 
      -> @TalentPoolType UserAssesmentRepository
          -> UserAssesmentRepositoryImpl
              -> UserAssesmentRestApiInterface
```

However, I only see the qualified type being provided, `@TalentPoolType UserAssesmentRestApiInterface`.

You would either need to change `UserAssesmentRepositoryImpl` to inject the qualified type:

```java
class UserAssesmentRepositoryImpl {
  @Inject
  UserAssesmentRepositoryImpl(
      String token,
      // Inject the qualified type here
      @TalentPoolType UserAssesmentRestApiInterface caliberService) {...}
}
```

Or you would need to provide the unqualified type, e.g. by removing the qualifier from the `@Provides`, or by adding an additional `@Binds` that binds `@TalentPoolType UserAssesmentRestApiInterface` to `UserAssesmentRestApiInterface`.

```java
@Module
@InstallIn(ApplicationComponent.class)
interface UserAssesmentRestApiInterfaceModule {
  // Bind the qualified type to the unqualified type
  @Binds
  UserAssesmentRestApiInterface bind(@TalentPoolType UserAssesmentRestApiInterface impl);
}
```

**Comment by mochadwi** [comment]
Hmm, I currently cannot understand this

> Or you would need to provide the unqualified type, e.g. by removing the qualifier from the `@Provides`, or by adding an additional `@Binds` that binds `@TalentPoolType UserAssesmentRestApiInterface` to `UserAssesmentRestApiInterface`.
> 
> ```java
> @Module
> @InstallIn(ApplicationComponent.class)
> interface UserAssesmentRestApiInterfaceModule {
>   // Bind the qualified type to the unqualified type
>   @Binds
>   UserAssesmentRestApiInterface bind(@TalentPoolType UserAssesmentRestApiInterface impl);
> }
> ```

The implementation class & return type is the same, does the dagger allows this? @bcorso

**Comment by bcorso** [comment]
Hi Mochamad,

Dagger looks at the "qualifier + type" not just the type. So from Dagger's perspective the qualified type, "`@TalentPoolType UserAssesmentRestApiInterface`", and the unqualified type, "`UserAssesmentRestApiInterface`", are completely unrelated bindings.

In particular, if you inject a `UserAssesmentRestApiInterface` Dagger has no way of knowing that you really want a `@TalentPoolType UserAssesmentRestApiInterface` unless you specifically tell it that these two things are related, e.g. using the `@Binds` that you quoted above.

Hope that helps. Let me know if it's still unclear.

**Comment by mochadwi** [comment]
That's great!
> Dagger looks at the "qualifier + type" not just the type.


CMIIW, I just have to remove `@Provides` dependency and use below approach instead?
> ```java
> @Module
> @InstallIn(ApplicationComponent.class)
> interface UserAssesmentRestApiInterfaceModule {
>   // Bind the qualified type to the unqualified type
>   @Binds
>   UserAssesmentRestApiInterface bind(@TalentPoolType UserAssesmentRestApiInterface impl);
> }
> ```

**Comment by bcorso** [comment]
Unfortunately, it's difficult to give an answer to that without having more context.

The first thing that I would try is to just remove the @TalentPoolType qualifier from the provides method because if you're just going to `@Binds` the two types it usually suggests that you don't need the qualifier.

**Comment by bcorso** [comment]
Closing this for now. If you have more information feel free to reopen this.

**Comment by mochadwi** [comment]
I've update the description now

**Comment by mochadwi** [comment]
I've update the description now.

Context, actually I want to use same retrofit service dependencies but with different base url as seen in the `NetworkModule.kt` cc @bcorso
