### ISSUE TITLE
inject context by field 

### ISSUE THREAD

**Issue by PiwiPW** [google/dagger#2084]
Hi, i can't find way to inject app context to non android class by field by @EntryPoint. Injection by constructor works ok, by by field i have null.

br
Piotr

**Comment by bcorso** [comment]
Hi Piotr,

Can you give some example code of what you're trying to do?

Also, is there a reason why you're using field injection rather than constructor injection?

**Comment by bcorso** [comment]
I'm going to close this issue since it's been a while without any update. 

Feel free to reopen this if you can provide more details.
