### ISSUE TITLE
How can I inject dependencies in a Base Fragment? 

### ISSUE THREAD

**Issue by izBasit** [google/dagger#2093]
I am trying to achieve something like this 
```
abstract class BaseFragment : Fragment() {

    @Inject
    lateinit var eventTracker: Provider<EventTracker>

    override fun onResume() {
        super.onResume()
        eventTracker.get().trackScreenInteraction(this.javaClass.simpleName)
    }
}
```

But it gives me a `kotlin.UninitializedPropertyAccessException: lateinit property eventTracker has not been initialized`

What am I doing wrong? How can I make it work?

**Comment by alexKatona** [comment]
Heloo @izBasit , what was the solution to your problem?
