### ISSUE TITLE
[Hilt] Failure in one tests causes failure in one tests

### ISSUE THREAD

**Issue by snepalnetflix** [google/dagger#2103]
Hi, we're using

- Hilt 2.28.3-alpha.
- Kotlin 1.4.10
- gradle android: 3.6.4

When we have a failure in one tests, we see the following failure in another test:

> Caused by: java.lang.IllegalStateException: The component was not created. Check that you have added the HiltAndroidRule.
> 	at dagger.hilt.internal.Preconditions.checkState(Preconditions.java:83)
> 	at dagger.hilt.android.internal.testing.TestApplicationComponentManager.generatedComponent(TestApplicationComponentManager.java:79)
> 	at com.netflix.mediaclient.HiltRobolectricNetflixApplication_Application.generatedComponent(HiltRobolectricNetflixApplication_Application.java:28)
> 	at dagger.hilt.EntryPoints.get(EntryPoints.java:46)
> 	at dagger.hilt.android.EntryPointAccessors.fromApplication(EntryPointAccessors.java:36)

This causes confusion on the team since folks aren't sure which is the true test failure.

Is there some state that's not being cleaned up?

Note, in our tests we use a custom application subclass. We OnComponentReadyRunner() to initialize the application's state using a TestRule.

**Comment by bcorso** [comment]
Hi @snepalnetflix,

> When we have a failure in one tests, we see the following failure in another test

By test, do you mean two test cases in the same test, or two completely separate tests?

> This causes confusion on the team since folks aren't sure which is the true test failure.
>
> Is there some state that's not being cleaned up?

It looks like the failure is happening when you're trying to access an entry point. Is that entry point accessed in your custom `TestRule`? 

It might be that you're trying to access the entry point too early, before the `HiltTestRule` is applied? However, it's difficult to say without seeing the code. If you have repro example we can take a look.

**Comment by Chang-Eric** [comment]
Closing this for now since it looks like we need more information.
