### ISSUE TITLE
Espresso tests with module overriding?

### ISSUE THREAD

**Issue by mjurkus** [google/dagger#212]
I'm having trouble to figure out how to "override" one of my modules in my Espresso tests.

It might be that my initial `Component` setup is wrong, but anyway. Here is what I have now.

Main main `Component` is this:
```JAVA
@PerApplicationScope
@Component(
    modules = {
        ApplicationModule.class,
        ApiModule.class,
        DataModule.class,
        FlavorApplicationModule.class,
        PreferenceModule.class,
        TrackerModule.class
    }
)
public interface FlavorApplicationComponent extends ApplicationComponent {

    FlavorActivityComponent getFlavorActivityComponent(ActivityModule module, FlavorActivityModule flavor);
}
```

I'm building my component on `MyApplication#onCreate()`. And using that to build `FlavorActivityComponent`  on `Activity#onCreate()` 

Now in my `Espresso` I wan't to override how `Api` is constructed and provided to make `IdlingResource` work.

Part of `ApiModule`
```
    @Provides
    @PerApplicationScope
    Api provideApi(@Api RestAdapter adapter) {
        return adapter.create(Api.class);
    }

    @Provides
    @PerApplicationScope
    TrackerApi provideTrackerApi(@Tracker RestAdapter adapter) {
        return adapter.create(TrackerApi.class);
    }
```

In my Espresso tests I'm building another graph that in the end should provide different `Api`. And I'm having trouble figuring out how to do that.

Any guidance is appreciated.

**Comment by svenjacobs** [comment]
The concept of module overrides unfortunately doesn't exist in Dagger 2 anymore. See #110 for possible solutions/workarounds.

**Comment by mjurkus** [comment]
After some experimentation I solved it by extending my actual components and passing different modules in a test component.
