### ISSUE TITLE
Error from  kaptDebugUnitTestKotlin

### ISSUE THREAD

**Issue by supakorn-iam** [google/dagger#2124]
when I tried to run the test file.

e: error: [Hilt]
  dagger.hilt.android.components.ApplicationComponent, expected to be annotated with @DefineComponent. Found: 
  [Hilt] Processing did not complete. See error above for details.

**Comment by bcorso** [comment]
Which version of Hilt are you using?

**Comment by supakorn-iam** [comment]
After I updated a new version. there is no error anymore thank you. @bcorso
