### ISSUE TITLE
Eclipse errors after file changes

### ISSUE THREAD

**Issue by lennartfricke** [google/dagger#2130]
After changing files in eclipse, the annotation processor throws an IllegalStateException:
```
Caused by: java.lang.IllegalStateException
	at com.google.common.base.Preconditions.checkState(Preconditions.java:492)
	at dagger.internal.codegen.statistics.DaggerStatisticsCollector.processingStopped(DaggerStatisticsCollector.java:82)
	at dagger.internal.codegen.ComponentProcessor.postRound(ComponentProcessor.java:195)
	at dagger.shaded.auto.common.BasicAnnotationProcessor.process(BasicAnnotationProcessor.java:176)
	at org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.handleProcessor(RoundDispatcher.java:142)
	... 26 more
```

And the generated factory for the class vanishes. Cleaning and rebuilding the project regenerates the files.

Eclipse: 2020-09 (4.17.0)
Eclipse-JDT: 3.18.500.v20200902-1800
Dagger: 2.28.3

**Comment by bcorso** [comment]
Hmm, that's strange. This error should be impossible since I believe it would require a processor to finish without first initializing itself. I'm tempted to say this may be an eclipse bug.

However, coincidentally, we've recently removed `DaggerStatisticsCollector` (since statistic collection is only used internally), so this should no longer be an issue. We haven't released new Dagger artifacts with those changes yet, so we'll need to wait to verify that you don't see further issues once those artifacts are available.

**Comment by lennartfricke** [comment]
I'm happy to try snapshot versions. But those show the same error as of 2020-09-25.

I'm no expert in annotationProcessing. Would it be in specification, when eclipse calls `init` on the ComponentProcessor once
and then reuses that instance for many incremental recompilation tasks, signalling that one recompilation task finishes using `processingOver`. It seems to me that `ComponentProcessor` assumes that after `processingOver`  `init` has to be called again.

**Comment by bcorso** [comment]
> I'm happy to try snapshot versions. But those show the same error as of 2020-09-25.

The change was actually pushed yesterday, 2020-10-06.  I'll try to release a new snapshot today.

> Would it be in specification, when eclipse calls init on the ComponentProcessor once
and then reuses that instance for many incremental recompilation tasks, signalling that one recompilation task finishes using processingOver. It seems to me that ComponentProcessor assumes that after processingOver init has to be called again.

Yeah, I think that was the assumption. However, I couldn't find anything in the [`Processor` javadoc](https://docs.oracle.com/javase/8/docs/api/javax/annotation/processing/Processor.html), so it could very well be that this was a bad assumption on our part.

Either way, this should be solved once we remove `DaggerStatisticsCollector`. I'll report back once we have the snapshots ready for you to verify.

Thanks!

**Comment by bcorso** [comment]
@lennartfricke, the snapshot should be available now if you want to give it a try.

**Comment by lennartfricke** [comment]
@bcorso, thank you, the error goes away.

But nonetheless when I edit java files sometimes dagger generated java files vanish and are not regenerated. But after editing the file again it reappears. I could not identify any pattern when that happens.

**Comment by Chang-Eric** [comment]
I think the last thing mentioned I think is probably https://github.com/google/dagger/issues/2082. Going to close this now since I think the main issue has been fixed.
