### ISSUE TITLE
Generic Error: < identifier > required

### ISSUE THREAD

**Issue by PagesHub** [google/dagger#2140]
Hilt![image](https://user-images.githubusercontent.com/34911458/95642331-6d6de900-0ada-11eb-8087-67a884352d97.png)
![image](https://user-images.githubusercontent.com/34911458/95642341-7c549b80-0ada-11eb-8aa8-f61c4d0baa11.png)

**Comment by bcorso** [comment]
This looks like a dupe of https://github.com/google/dagger/issues/2042.

You can't use `@AndroidEntryPoint` on a base class with type parameters. Instead annotated the subclass, for example:

```kotlin
@AndroidEntryPoint
class FooActivity : BaseActivity<FooViewBinding>() {...}

// Can't annotate this with @AndroidEntryPoint because it has type parameters
abstract class BaseActivity<VB: ViewBinding> : BaseAppCompatActivity(), BaseContract.BaseView, View.OnClickListener {...}
```

**Comment by PagesHub** [comment]
> This looks like a dupe of #2042.
> 
> You can't use `@AndroidEntryPoint` on a base class with type parameters. Instead annotated the subclass, for example:
> 
> ```kotlin
> @AndroidEntryPoint
> class FooActivity : BaseActivity<FooViewBinding>() {...}
> 
> // Can't annotate this with @AndroidEntryPoint because it has type parameters
> abstract class BaseActivity<VB: ViewBinding> : BaseAppCompatActivity(), BaseContract.BaseView, View.OnClickListener {...}
> ```
I get it, thanks.
