### ISSUE TITLE
[hilt 2.29.1-alpha] throws InstantiationException: ViewModel has no zero argument constructor on hilt 

### ISSUE THREAD

**Issue by ThanosFisherman** [google/dagger#2147]
After updating to hilt `2.29.1-alpha` I'm getting the runtime crash described in the title. Up until hilt `2.28-alpha` I had no such problems whatsoever.

I've forked a small project that happens to resemble my current project configuration and all I did was to update hilt from `2.28-alpha` to `2.29.1-alpha`  (check my latest commit)

Could you please check this out and let me know what am I missing?

https://github.com/ThanosFisherman/Android-MVVM-Hilt-RX3-KotlinDSL

**Comment by danysantiago** [comment]
You updated Hilt but you also removed the AndroidX Hilt Extension, here: https://github.com/ThanosFisherman/Android-MVVM-Hilt-RX3-KotlinDSL/commit/a63a22c17a194334987d7ce09648e16dc7e1f868#diff-8cff73265af19c059547b76aca8882cbaa3209291406f52df1dafbbc78e80c46

Try adding the AndroidX Compiler Extension back and it should work. See: https://developer.android.com/training/dependency-injection/hilt-jetpack for more info.

**Comment by liangpengfei** [comment]
In my case, the root cause is that hilt is conflicted with aspectjx plugin. I removed the aspectjx plugin, it works for me.

hilt version 2.33-beta
aspectjx version 2.0.10
