### ISSUE TITLE
Provider can be a local variable initialize() in Component??

### ISSUE THREAD

**Issue by pollux-** [google/dagger#2149]
I might be overthinking, as I was going through the Dagger Generated code for the component, I noticed that providers are being created as member variable, can this be a local variable?

 ```
 private void initialize(final CoreComponent coreComponentParam) {
    this.provideTestDaoProvider = 
  }

```

Thanks !!

**Comment by bcorso** [comment]
Hi @pollux- 

Yes, there is some room for optimization there by removing intermediate providers that are only referenced within the `initialize` method (albeit, at least some of those providers should be used to implement your component methods, so they will need to outlive the `initialize` method). 

One complication that's made me avoid this optimization in the past is that Dagger splits the `initialize` method every 100 providers (I believe this is to avoid reaching the byte limit for the method and to allow jit optimization), which means that local providers referenced across different `initialize` methods would need to be tracked and passed in as parameters to subsequent `initialize` methods.

Given that instances of these providers are going to be kept in memory anyway (by some other provider that is a member variable), I'm not sure the complexity of this change would be worth it. It might also be worth checking if this is something that Proguard can optimize away.

**Comment by pollux-** [comment]
@bcorso Nice,  good to know this Thanks. 

Should I close this one?

**Comment by bcorso** [comment]
Yes thanks, I'll go ahead and close this. In the future, if we have more evidence that this optimization is worth the complexity we can consider reopening.
