### ISSUE TITLE
Warning for Field/Constructor @Inject combination. 

### ISSUE THREAD

**Issue by chrisjenx** [google/dagger#215]
I was debating the inclusion of showing a graph validation warning/error when someone includes `@Inject Field something` and `@Inject Constructor()` in the same class. 
To me that feels like code smell (or incorrect understanding of Dagger/DI).

Is there a valid case for Field and Constructor injection? If not I think it might be prudent to flag this as a compiler error/warning. As it's likely that combination of a non-injected constructor/field annotations and Injected constructor would be really confusing to maintainers.

e.g. I think this should throw a warning:
```
class Foo
  @Inject Bar bar;
  @Inject Foo(Bar bar){
    this.bar = bar;
  }
}
```

The only use case I could think of:

```
class Foo
  @Inject Bar bar;
  @Inject Foo(Bar bar){
    this.bar = bar;
  }
  Foo(){
    SingletonObject.component().inject(this);
  }
}
```
This seems like a really bad implementation and we should discourage this.

**Comment by netdpb** [comment]
Are you concerned about any class having both constructor and field injection?

Or are you worried about a class using constructor and field injection _for the same qualified type?_

The former is perfectly reasonable. The latter may be strange, but I don't think we can assert that it's always a problem.

In your example, `Foo` assigns the constructor-injected `Bar` to the injected field, which is certainly an error. But normally fields that are set in the constructor are final, and Dagger throws an error if you annotate a final field with `@Inject`.
