### ISSUE TITLE
Feature request: Binds on return type

### ISSUE THREAD

**Issue by kirich1409** [google/dagger#2158]
Right now only one way of declare Bind in Dagger:
```java
interface Feature {
}

class FeatureImpl implements Feature {
}

@Module
interface BindsModule {

   @Binds
   Feature bindFeatureImpl_Feature(feature: FeatureImpl)
}
```
it will be better to have the possibility to declare Binds on the type, something like this:
```java
@BindsTo(FeatureImpl.class)
interface Feature {
}

class FeatureImpl implements Feature {
}
```
it will help eliminate a lot of boilerplate Binds modules

**Comment by JakeWharton** [comment]
This is a dupe of #1164 it seems.

**Comment by bcorso** [comment]
Thanks @JakeWharton for linking the dupe. Closing this since #1164 should cover it.

**Comment by ansman** [comment]
FYI I released a library that does this for you using Hilt (Android only unfortunately unless Hilt starts supporting non Android projects): https://auto-dagger.ansman.se/
