### ISSUE TITLE
i want to Inject view model inherits from Base view model class 

### ISSUE THREAD

**Issue by abdelkawi** [google/dagger#2159]
i want to use dagger hilt with my base viewmodel class like this 

Base : 
abstract class BaseViewModel():ViewModel(){
abstract fun doSth()
}

instance 
class MyViewModel():BaseViewModel(){
override fun doSth(){

}
}

in fragment 
  override val viewModel: LoginViewModel by viewModels()

it shows that error 
    java.lang.RuntimeException: Cannot create an instance of class  MyViewModel

**Comment by danysantiago** [comment]
Check out the instructions on using Hilt with ViewModels: https://developer.android.com/training/dependency-injection/hilt-jetpack#viewmodels

You want to annotate your ViewModels with `@ViewModelInject` something like this:
```
class MyViewModel @ViewModelInject constructor() : BaseViewModel() {
```

**Comment by ARRR42** [comment]
`@ViewModelInject` is deprecated, how we approach this now?

**Comment by bcorso** [comment]
@ARRR42 ViewModel support is now built into Hilt. See the new documentation: https://dagger.dev/hilt/view-model
