### ISSUE TITLE
@Binds for Generic Types

### ISSUE THREAD

**Issue by pollux-** [google/dagger#2161]
I'm using Dagger  `@Binds` to binding the interface to implementation.
I have a generic mapper which transforms one object to another.
 ```
interface DataMapper<T, R> {
     fun transform(from: T): R
 }
```
So I have a couple of Data mappers in each use case layer.
Let's I have something like this
```
class AccountDataMapper @Inject constructor():
DataMapper<Account,Result<Account>>{
override fun transform(account : Account){
}
}
```
How can I bind this? I have many mapers like Login Mapper, User mapper.
When I use the binder it's complaining that
`@Binds` method parameter type must be assignable to the return type
```
@Binds
abstract fun bindAccountMapper(mapper AccountDataMapper) : DataMapper<Account,Result<Account>>
```
Thanks in advance

**Comment by bcorso** [comment]
Which version of Dagger are you using?

I could not reproduce this with v2.29.1. Can you share the error messages?

The following works for me:

```kotlin
@Component(modules = arrayOf(MyComponent.MyModule::class))
interface MyComponent {
    @Module
    interface MyModule {
        @Binds fun bind(impl: AccountDataMapper): DataMapper<Account, Result<Account>>
    }

    fun accountDataMapper(): DataMapper<Account, Result<Account>>

    interface Account

    interface Result<T>

    interface DataMapper<T1, T2> {
        fun transform(t1: T1): T2
    }

    class AccountDataMapper @Inject constructor(): DataMapper<Account, Result<Account>> {
        override fun transform(t1: Account): Result<Account> { TODO("Not yet implemented") }
    }
}
```

**Comment by pollux-** [comment]
I'm using Dagger Version:
`dagger:2.29.1`
: error: @Binds methods' parameter type must be assignable to the return type

**Comment by bcorso** [comment]
If you copy and paste the code I linked in https://github.com/google/dagger/issues/2161#issuecomment-716795642, does that compile or do you get the same error?

**Comment by pollux-** [comment]
@bcorso  that works.

**Comment by pollux-** [comment]
I have @provider method for different Mapper in the App module, I had refactored only the Account module.  This will be included in the App component with the provider for other mappers. 

Will that cause any issues?

**Comment by bcorso** [comment]
> I have @Provider method for different Mapper in the App module, I had refactored only the Account module.

IIUC, it sounds like the issue was that you had two `DataMapper` classes and you were accidentally binding to the wrong one?

> This will be included in the App component with the provider for other mappers. Will that cause any issues?

No, it shouldn't cause any issues.

**Comment by pollux-** [comment]
@bcorso thanks 🙏  😊  .. I'm closing this ticket. I’ll  reopen if I found anything meaningful
