### ISSUE TITLE
@Inject @ActivityContext context: Context [Can compile] vs @Inject activity: YourActivity [Failed]

### ISSUE THREAD

**Issue by lester-osimdev** [google/dagger#2163]
### **Code 1**
```
class LoginCoordinatorImpl @Inject constructor(
    @ActivityContext context: Context
) : LoginCoordinator {

    private val activity: YourActivity = context as YourActivity
```
### **Code 2**
```
class LoginCoordinatorImpl @Inject constructor(
    private val activity: YourActivity
) : LoginCoordinator {

```

### **What is the difference of the two ?** 
Because the **Code 1** is working fine but the **Code 2** is failing.

Also the code above is base on the samples on the developer.android.com
```
class AnalyticsAdapter @Inject constructor(
  @ActivityContext context: Context
) { ... }

// The Activity binding is available without qualifiers.
class AnalyticsAdapter @Inject constructor(
  activity: FragmentActivity
) { ... }
```

**Comment by sjcqs** [comment]
`YourActivity` is not provided. 

`@ActivityContext Context``FragmentActivity` are provided by Dagger Hilt in the ActivityComponent.  
cf https://github.com/google/dagger/blob/90a1d2f612d4f80844e83c737e8f5c2362020c5a/java/dagger/hilt/android/internal/modules/ActivityModule.java#L31-L50
