### ISSUE TITLE
Cannot Find Symbol DaggerApp_HiltComponents_SingletonC.builder() 

### ISSUE THREAD

**Issue by zakayothuku** [google/dagger#2164]
Need help.

Am building my multi-module project with Dagger-Hilt. Am getting this error:

```
/HiltDemo/app/build/generated/source/kapt/debug/com/app/hilt/Hilt_App.java:22: error: cannot find symbol
      return DaggerApp_HiltComponents_SingletonC.builder()
             ^
  symbol: variable DaggerApp_HiltComponents_SingletonC

```
Here's the generated file with the error:

```
/**
 * A generated base class to be extended by the @dagger.hilt.android.HiltAndroidApp annotated class. If using the Gradle plugin, this is swapped as the base class via bytecode transformation.
 */
@Generated("dagger.hilt.android.processor.internal.androidentrypoint.ApplicationGenerator")
public abstract class Hilt_App extends SplitCompatApplication implements GeneratedComponentManagerHolder {
  private final ApplicationComponentManager componentManager = new ApplicationComponentManager(new ComponentSupplier() {
    @Override
    public Object get() {
      return DaggerApp_HiltComponents_SingletonC.builder()
          .applicationContextModule(new ApplicationContextModule(Hilt_App.this))
          .build();
    }
  });

  @Override
  public final ApplicationComponentManager componentManager() {
    return componentManager;
  }

  @Override
  public final Object generatedComponent() {
    return this.componentManager().generatedComponent();
  }

  @CallSuper
  @Override
  public void onCreate() {
    // This is a known unsafe cast, but is safe in the only correct use case:
    // App extends Hilt_App
    ((App_GeneratedInjector) generatedComponent()).injectApp(UnsafeCasts.<App>unsafeCast(this));
    super.onCreate();
  }
}
```

**Comment by danysantiago** [comment]
Seems like you are running into https://github.com/google/dagger/issues/1991, can you try making some of your dependencies used in the DI graph `api` instead of `implementation` to confirm that is the issue.

**Comment by zakayothuku** [comment]
Since adding `api` instead of `implementation` is not an option for us for our core module, I had to put some of the required libraries in both `app` and `core` module.

**Comment by sdzshn3** [comment]
Hey @zakayothuku , Any idea how to solve this similar issue. I have a single module app. But still getting this error no matter if i use api or implementation

**Comment by PykeChen** [comment]
I have encountered the same problem.  I tried api or implementation.

**Comment by sdzshn3** [comment]
Hey @PykeChen 
Try adding this into gradle.properties

`kapt.use.worker.api=false kapt.incremental.apt=false`

**Comment by mohmmedayman-dev** [comment]
I had the same problem and it was resolved
 when I moved the class file @HiltAndroidApp 

> To the first file without sub-files

**Comment by fethij** [comment]
My issue was associated with package where the file was located. it could happen if you move the class to different package without annotating the package in the class
