### ISSUE TITLE
When to expect Hilt in beta?

### ISSUE THREAD

**Issue by vokilam** [google/dagger#2167]
We want to try Hilt in our project, however we cannot accept dependencies in alpha stage. Could you elaborate more on Hilt roadmap, at least in terms of months or years?

Also I see two sources of hilt dependency:
- [AndroidX Release Notes](https://developer.android.com/jetpack/androidx/releases/hilt) states that the latest version is `androidx.hilt:hilt-*:1.0.0-alpha02`
- Another [official documentation page](https://developer.android.com/training/dependency-injection/hilt-android) says to use `com.google.dagger:hilt-android:2.28-alpha`

What is the preferred way?

**Comment by Chang-Eric** [comment]
So the best we can say is that we're aiming for Hilt to be in Beta on the order of months, not years. Obviously, usual caveats apply about how there's no guarantee, etc.

For the dependency question, there are actually two separate libraries so you may need both dependencies depending on what you're using. The `com.google.dagger` dependency is the Hilt library. This is required. https://dagger.dev/hilt/gradle-setup has the documentation on that. The `androidx` dependency is for the AndroidX extensions like for WorkManager. You only need this if you are using that extension. Hope that makes sense, thanks!

**Comment by snepalnetflix** [comment]
Currently using @AndroidEntryPoint without specifying super class breaks the ability to run tests in Android Studio.

Do you know if fixing that is a criteria for the Beta milestone?

**Comment by Chang-Eric** [comment]
That bug is actually something we're trying to fix in AGP, hopefully upcoming soon in a future AGP release. There isn't much we can do on the Hilt side, but we're working with that team to resolve the issue. Since there is a workaround and the fix isn't in Hilt, we aren't currently considering it to be a blocker.

**Comment by Chang-Eric** [comment]
Closing this since I think the questions have been answered.
