### ISSUE TITLE
Dagger/Hilt compilation conflict with AppBarLayout material component

### ISSUE THREAD

**Issue by amaslanka** [google/dagger#2168]
Hello,

I'm experiencing an issue with Hilt in a multi module project. Basically when we want to inject dependencies to an activity that uses `com.google.android.material.appbar.AppBarLayout`, the app cannot be compiled. The error says the following:

```
error: cannot access AppBarLayout
  class file for com.google.android.material.appbar.AppBarLayout not found
  Consult the following stack trace for details.
  com.sun.tools.javac.code.Symbol$CompletionFailure: class file for com.google.android.material.appbar.AppBarLayout not found
```

I've created an example project on which you can reproduce the issue:
1. Clone the repo: https://github.com/amaslanka/hilt-test
2. Checkout to `main` branch.
3. Open the project with Android Studio (I've tried it on 4.0 & 4.1 versions).
4. Build -> Rebuild Project.
5. The error should be thrown during the compilation (if it's not, then `Clean Project` and rebuild again).

I've found a temporary workaround for this problem. If we create a custom class that extends the `AppBarLayout` (in the example it's `com.example.core.CustomAppBarLayout`) and use it instead of the parent one, the app builds properly.
You can verify this by checking out to the `workaround` branch in the example project. The `AppBarLayout` is used in the `com.example.core.MidActivity`.
Also, when we remove from the activity the injected property called `otherString`, the error is gone.

Do you have any idea what might be the reason of this problem?

**Comment by dmapr** [comment]
In **core/build.gradle** change `implementation 'com.google.android.material:material:1.2.0-alpha01'` to `api 'com.google.android.material:material:1.2.0-alpha01'`

**Comment by amaslanka** [comment]
Thanks @dmapr for linking the other discussion. I think that either using the `api` instead of `implementation` or adding the dependency to the app's `build.gradle` is acceptable solution for now.

**Comment by bcorso** [comment]
@dmapr thanks for handing this. I'll close this out now.
