### ISSUE TITLE
Hello, how does the custom annotator in the dagger source code generate the import information of the new Java code class,

### ISSUE THREAD

**Issue by cailiming1994** [google/dagger#2179]
As follows:

**import java.sql.SQLException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;**

public class Demo {
}

**Comment by bcorso** [comment]
Dagger generates java files using [JavaPoet](https://github.com/square/javapoet). 

While building a file with JavaPoet's API, you pass in fully qualified class names and JavaPoet will then import classes that are not in the same package as the java file being generated.

**Comment by cailiming1994** [comment]
oh ! I see, Thank you for your answers！
