### ISSUE TITLE
Allow to enforce Lazy<T>

### ISSUE THREAD

**Issue by konmik** [google/dagger#218]
The problem:

I can't provide `Lazy<T>` like this: 

``` java
    @Provides
    public Lazy<DrawerLayout> provideDrawer
```

Error:(17, 10) error: android.support.v4.widget.DrawerLayout cannot be provided without an @Inject constructor or from an @Provides- or @Produces-annotated method.
xx.DocumentListFragment.drawer
[injected field of type: dagger.Lazy<android.support.v4.widget.DrawerLayout> drawer]

Because of that some users of T may try to `@Inject T dependency` instead of using `Lazy`. Dagger have no idea that the dependency does not exist at the moment of injection so it may inject null or just crash inside of a module.

Solution: allow to provide `Lazy<T>` directly.

A temporary workaround I'm using (simplified):

``` java
public interface Delayed<T> {
    T get();
}

@Provides
Delayed<DrawerLayout> provideDrawerLayout() {...}

@Inject Delayed<DrawerLayout> drawer;
```

**Comment by cgruber** [comment]
You don't "provide Lazy<T>" you provide T and inject Lazy<T>.  Are you
asking for a feature to require that only Provider<T> or Lazy<T> be bound?
But that T itself, is not directly bound?

**Comment by konmik** [comment]
Yes, I'm asking for a feature. :)

I want to provide a "promise" of T, not T itself. And I want a user of T to be enforced to access it with `Lazy<T>` because T does not exist at the moment of injection.

I know this sounds like a workaround, but we're in Android world can't control order of objects instantiation. Sometimes we need to inject a "promise" that the object will exist in the future.

We need to connect objects that are created by the system in the random order. The usual solution is using an event bus, but it is a very bad design. 

In example we have object `A` and that object `A` owns `B` and `C`. Objects are instantiated in the `A-B-C` order by the system, but sometimes they are instantiated in the `A-C-B` order.

After that instantiation I want to use `B` from `C`. If I forget to write `@Inject Lazy<B> b` and will write just `@Inject B b`, then sometimes I will inject `null`. This can cause NPEs in the future.

This is the full solution I use now to inject `B`:

``` java
public class Delayed<T> {

    public interface Factory<T> {
        T create();
    }

    private final Factory<T> factory;
    private volatile T value;

    public Delayed(Factory<T> factory) {
        this.factory = factory;
    }

    public T get() {
        if (value == null)
            value = factory.create();
        return value;
    }
}
```

I provide it like this:

``` java
    @ActivityScope
    @Provides
    public Delayed<DrawerLayout> provideDrawer() {
        return new Delayed<>(() -> findById(activity, R.id.drawer_layout));
    }
```

And use it like this:

``` java
    @Inject Delayed<DrawerLayout> drawer;
```

I know that there is something in dagger-producers that allows to

**Comment by netdpb** [comment]
I think your solution seems reasonable for your use case. If you cannot guarantee the existence of some object based on its dependency graph, then you can't reasonably provide that object in Dagger. But you can guarantee the existence of a `Delayed<B>`, so you provide that.

What exactly are A, B, and C in your example?

**Comment by konmik** [comment]
"In example we have object A and that object A owns B and C. Objects are instantiated in the A-B-C order by the system, but sometimes they are instantiated in the A-C-B order."

A is window, B and C are window parts.

**Comment by ronshapiro** [comment]
We've explicitly disallowed `@Provides Lazy<T>` since it causes a lot of confusion, and I agree with @netdpb that your `Delayed<T>` solution sounds great for your usecase.

**Comment by asthagarg2428** [comment]
I have a small doubt, 
can we use lazy constructor injection in dagger? like shown below? Does it work as expected?
```
class ABC @Inject constructor(
    private val obj: dagger.Lazy<B>){}
```

**Comment by bcorso** [comment]
Yes, see https://dagger.dev/dev-guide/#lazy-injections

**Comment by asthagarg2428** [comment]
> Yes, see https://dagger.dev/dev-guide/#lazy-injections

No, I mean does it support lazy injection in constructor also?

**Comment by bcorso** [comment]
Yes. In general, anything that you can inject in a field you can also inject into a constructor.
