### ISSUE TITLE
'validateTransitiveComponentDependencies' option is available on Hilt?

### ISSUE THREAD

**Issue by uOOOO** [google/dagger#2183]
I've tried some codes but failed with Hilt.

The dependencies were like below.

```
- app module
 + data module (implementation)
- data module
 + retrofit (implementation not api)
```

But Hilt failed to create Dagger*Application_HiltCOmpoenents_SingletonC.java because it could't find retrofit dependency.

I think Hilt tried to put all things into a class(Dagger*Application_HiltCOmpoenents_SingletonC.java).

So app module has to know about retrofit. Am I right?

**Comment by bcorso** [comment]
Yeah that sounds correct. Specifically, if the generated Dagger component in app module references the retrofit classes, then app module needs to either have a direct dependency on retrofit, or an `api` dependency on "data module" so that it has access to retrofit transitively.

**Comment by bcorso** [comment]
Also see also https://github.com/google/dagger/issues/1991#issuecomment-661245887 for more details.

**Comment by uOOOO** [comment]
Thank you for the answer. I'll keep watching #1991.
