### ISSUE TITLE
Method initialize in Component implements class is empty.

### ISSUE THREAD

**Issue by jien** [google/dagger#219]
When i use daggger2 in project,I created a component called CppComponent,but the class DaggerCppCpmponent's method initialize was empty which was built by dagger2.what was happening ?
![0f3e0cb7-b0a4-4c2c-bc53-e483b52d6545](https://cloud.githubusercontent.com/assets/2010807/9084026/f31840e0-3ba1-11e5-9a93-cb26667da5f5.png)

**Comment by netdpb** [comment]
If the component implementation has no fields to initialize, it still emits at least one `initialize()` method. In general, it emits one `initialize()` method for every _n_ bindings, but not every binding requires a field, and Dagger doesn't skip the first one if there are no fields.

This is a known bug, but low priority.

**Comment by netdpb** [comment]
This is fixed internally, and will be in a future release.
