### ISSUE TITLE
Feature request: Annotation for primary implementation

### ISSUE THREAD

**Issue by sczerwinski** [google/dagger#2195]
Having multiple implementations of the same interface, I would like to annotate one of them, for it to be used when injecting the interface.

For example:
```kotlin
interface MyInterface
class MyFirstImplementation @Inject constructor() : MyInterface
class MySecondImplementation @Inject constructor() : MyInterface

class SomeOtherClass @Inject constructor(myInterface: MyInterface)
```

I would like to point the implementation to be used by default in `SomeOtherClass`, without too much boilerplate.

### Currently:

A the moment, it is at least required to create a Module with `@Binds`-annotated functions:
```kotlin
interface MyInterface
class MyFirstImplementation @Inject constructor() : MyInterface
class MySecondImplementation @Inject constructor() : MyInterface

@Module
@InstallIn(SingletonComponent::class)
interface MyModule {
    @Binds fun bindMyImplementation(impl: MyFirstImplementation): MyInterface
}
```

### First solution (annotated implementation – Spring `@Primary` annotation):

```kotlin
interface MyInterface
@Primary class MyFirstImplementation @Inject constructor() : MyInterface
class MySecondImplementation @Inject constructor() : MyInterface
```

### Second solution (annotated interface):

```kotlin
@PrimaryImplementation(MyFirstImplementation::class) interface MyInterface
class MyFirstImplementation @Inject constructor() : MyInterface
class MySecondImplementation @Inject constructor() : MyInterface
```

### Considerations

Nice to have: point to different implementation depending on the scope:
```kotlin
interface MyInterface
@Primary(ActivityScoped) class MyFirstImplementation @Inject constructor() : MyInterface
@Primary(FragmentScoped) class MySecondImplementation @Inject constructor() : MyInterface
```

**Comment by bcorso** [comment]
This is similar to #1164.

For now, we don't have plans to add this feature directly in Hilt. However, it should be pretty straight-forward to create a custom annotation processor that does this with Hilt under the hood. See https://github.com/google/dagger/issues/1164#issuecomment-670950487.

**Comment by sczerwinski** [comment]
Thanks for pointing me to the existing issue.

Closing duplicate.
