### ISSUE TITLE
Transitive Dependencies Not Resolved Optimally

### ISSUE THREAD

**Issue by cperry-gpsw** [google/dagger#220]
Consider the following Android flavored example:

```java
@Module
public class AppModule {
  @Provides Thing provideThing() {
      return new Thing();
  }
}

@Singleton
@Component( modules = AppModule.class )
public interface AppComponent {
    void inject(App app);
}

@PerActivity
@Component( dependencies = AppComponent.class )
public interface ActivityComponent {
    void inject(MyActivity activity);
}

@PerFragment
@Component( dependencies = ActivityComponent.class )
public interface FragmentComponent {
    void inject(MyFragment fragment);
}

public class MyFragment extends Fragment {
    @Inject Thing thing;

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate();
        
        // Let's pretend we got activityComponent from somewhere
        DaggerFragmentComponent.builder()
            .activityComponent(activityComponent)
            .build()
            .inject(this);
    }
}
```

It makes sense to me that the FragmentComponent should be able to resolve (without any extra information) the `Thing` dependency being injected into the Fragment because of the dependency chain

>  Thing -> AppModule -> AppComponent -> ActivityComponent -> FragmentComponent

Since AppComponent knows about AppModule it's `inject()` method works without extra information. Since this component is part of the dependency chain we should be able to resolve the Thing being injected in the Fragment. Dagger fails to compile complaining that there is no `@Provides` specified for the Thing being injected in the Fragment, which is clearly not the case.

**Comment by JakeWharton** [comment]
Either put `Thing thing()` on your AppComponent to expose the type to dependent components or use `@Subcomponent` to factory the dependent components (thus allowing them to access the implementation details of AppComponent. This has nothing to do with optimal resolution (what does that even mean?), they simply have no way of accessing that type.

**Comment by cperry-gpsw** [comment]
I guess I should have said "with less boilerplate"?

What I'm saying is, Dagger has enough information already and that we shouldn't need to put `Thing thing()` on the AppComponent to expose it, the information is already available via the modules that are listed in the @Component declaration.

**Comment by JakeWharton** [comment]
The downstream generated code has no way of accessing the binding without declaring it on the component. It has nothing to do with what Dagger knows, it's a limitation imposed by normal type-hiding semantics of Java. The downstream components depend on the component interface _only_ and thus can only see the types it exposes.

**Comment by cperry-gpsw** [comment]
How are types being hidden? Are you saying the code generator can't process what's listed in the annotations?

>  The downstream components depend on the component interface only

This sounds like a limitation imposed only but the current implementation.

**Comment by JakeWharton** [comment]
The fact that a `Thing` exists is an implementation detail of `Dagger_AppComponent`. `Dagger_ActivityComponent` depends on `AppComponent` which does not expose `Thing`.

**Comment by cperry-gpsw** [comment]
I see what you're saying, but it seems inconsistent with the fact that we are coupling implementation details (modules) to the Components themselves (through an annotation), but not following that paradigm to it's logical conclusion.

For example:

```java
@Module
public class AppModule {
  @Provides Thing provideThing() {
      return new Thing();
  }
}

@Singleton
@Component( modules = AppModule.class )
public interface AppComponent {
    void inject(App app);
}
```

In AppComponent we do not expose a Thing. Yet if we call `inject()` on the DaggerAppComponent that's produced from the interface a `Thing` is provided given the implementation attached via the `modules` declaration. We don't have to expose it in the interface here to get one in an Application that chooses to inject via the DaggerAppComponent. So Dagger is exposing implementation details in the interface itself.

**Comment by cperry-gpsw** [comment]
Aside from my last comment, how would this look with `@Subcomponent`? There's isn't much in the way of examples for using subcomponents AFAIK.

**Comment by JakeWharton** [comment]
> So Dagger is exposing implementation details in the interface itself.

Except you just said that only DaggerAppComponent is able to do this, not the interface. The interface knows nothing about the injection requirements of the target type. Only that the generated class has to somehow figure them out and satisfy them.

**Comment by cperry-gpsw** [comment]
True, however the generated class is generated through the interface definition. That's why I'm saying there's enough information to do what I'm suggesting.

**Comment by JakeWharton** [comment]
Through what API would the downstream components access the `Thing` instance then?

**Comment by cperry-gpsw** [comment]
Through `inject(MyObject o)`. I'm expecting my example to work since it works that way for a single component anyways. I'm just asking for the same thing to be generated transitively given the dependencies listed in the component interfaces.

**Comment by JakeWharton** [comment]
How? How does it access those instances? There are no method on the component for it to obtain those types.

**Comment by cperry-gpsw** [comment]
Through the 'dependencies' listed in the `@Component()` annotations on the component interfaces.

**Comment by JakeWharton** [comment]
How does that help it get access to the `Thing` instance which is contained in the DaggerAppComponent with no API on the AppComponent for fetching it?

**Comment by JakeWharton** [comment]
Here is a complete illustration of the problem:
```java
class Thing {
}
class App {
  Thing thing;
}
interface AppComponent {
  void inject(App app);
}
class DaggerAppComponent implements AppComponent {
  Thing thing = new Thing();
  
  @Override public void inject(App app) {
    app.thing = thing;
  }
}
class Activity {
  Thing thing;
}
interface ActivityComponent {
  void inject(Activity activity);
}
class DaggerActivityComponent implements ActivityComponent {
  private final AppComponent appComponent;

  DaggerActivityComponent(AppComponent appComponent) {
    this.appComponent = appComponent;
  }

  @Override public void inject(Activity activity) {
    activity.thing = ???
  }
}
```

**Comment by JakeWharton** [comment]
Add `Thing thing()` to `AppComponent` and problem solved, the code becomes `activity.thing = appComponent.thing()`

**Comment by JakeWharton** [comment]
Use `DaggerAppComponent` as a factory for `DaggerActivityComponent` instances and problem solved, implementation-detail `Thing` can be passed along without declaring it.

**Comment by cperry-gpsw** [comment]
Let me ask another way, why does my original example not work, but something like this does?

```java
@Module
public class AppModule {
  @Provides Thing provideThing() {
      return new Thing();
  }
}

@Singleton
@Component( modules = AppModule.class )
public interface AppComponent {
    void inject(App app);
    Thing getThing();
}

@PerActivity
@Component( dependencies = AppComponent.class )
public interface ActivityComponent {
    void inject(MyActivity activity);
    Thing getThing();
}

@PerFragment
@Component( dependencies = ActivityComponent.class )
public interface FragmentComponent {
    void inject(MyFragment fragment);
    Thing getThing();
}

public class MyFragment extends Fragment {
    @Inject Thing thing;

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate();

        // Let's pretend we got activityComponent from somewhere
        DaggerFragmentComponent.builder()
            .activityComponent(activityComponent)
            .build()
            .inject(this);
    }
}
```

I've only listed the module in AppComponent. How do the other components know how to get it? It makes sense that of course they get it from the code generated from the module I listed all the way at the top of the graph in the AppComponent. I don't have to repeat the module everywhere, so it seems unnecessary to have to add a method on the interface to expose it, since it finds the implementation anyways.

**Comment by cperry-gpsw** [comment]
>  Use DaggerAppComponent as a factory for DaggerActivityComponent instances and problem solved, implementation-detail Thing can be passed along without declaring it.

I'll give that shot.

**Comment by JakeWharton** [comment]
Because the downstream components can see `Thing` and use that method to get access to its instance.

**Comment by cperry-gpsw** [comment]
I couldn't get your suggestion to work, what works is:

```java
@Singleton
@Component( modules = AppModule.class )
public interface AppComponent {
    void inject(App app);
    
    ActivityComponent plus(/** modules would go here if we had some */);
}

@PerActivity
@SubComponent
public interface ActivityComponent {
    void inject(MyActivity activity);
    
    FragmentComponent plus(/** modules would go here if we had some */);
}

@PerFragment
@SubComponent
public interface FragmentComponent {
    void inject(MyFragment fragment);
}
```

I seem to lose some of the benefits of declaring scopes doing it this way though.

**Comment by JakeWharton** [comment]
That was exactly my suggestion. I guess I forgot to use the word
subcomponent. Subcomponents are factories for dependent components which
allow propagating non-exposed bindings.

**Comment by netdpb** [comment]
@cperry-gpsw Your last example looks like the right use of subcomponents, and that's exactly what you should do.

What is it about scopes that you feel like you're losing?

**Comment by netdpb** [comment]
I'm going to close this, because subcomponents is the existing feature you're looking for,
