### ISSUE TITLE
Rewrite the SuperficialValidation currently in BasicAnnotationProcessor

### ISSUE THREAD

**Issue by Chang-Eric** [google/dagger#2208]
Superficial validation in BasicAnnotationProcessor is pretty limited in customization so it is causing problems. This happens in with it sometimes being too eager to validate things Dagger doesn't care about. Also a problem is that the error can be sometimes quite vague without a chance for Dagger to figure out more on what type was really the cause of the issue.

We should rewrite this, either as specific logic in Dagger or make customization contributions to BasicAnnotationProcessor.

**Comment by bcorso** [comment]
This will be fixed in the next release.
