### ISSUE TITLE
Error message does not specify which Component has incorrect configuration

### ISSUE THREAD

**Issue by kotucz** [google/dagger#221]
In this example are two components `RealComponent` and `MockComponent`. In the `RealComponent` dependency `App` is not satisfied properly. This results in this error message

    [...]\app\src\main\java\com\example\dagger\error\DaggerErrorMessage.java
    Error:(10, 13) error: com.example.dagger.error.DaggerErrorMessage.App cannot be provided without an @Inject constructor or from an @Provides-annotated method.

Issue: The error message does not say, where the error actually is. It should say that this error is in `RealComponent`. The `MockComponent` is ok so looking at this won't help and it is confusing. This is just simple case, but the configuration issue is harder to find in larger application.

    package com.example.dagger.error;
    
    import dagger.Component;
    import dagger.Module;
    import dagger.Provides;
    
    public class DaggerErrorMessage {
    
        interface AbstractComponent {
            App app();
        }
    
        @Component(modules = {MockModule.class})
        interface MockComponent extends AbstractComponent {
        }
    
        @Component
        interface RealComponent extends AbstractComponent {
        }
    
        @Module
        static class MockModule {
            @Provides
            App provideApp() {
                return new MockApp();
            }
        }
    
        static class App {
        }
    
        static class MockApp extends App {
        }
    
    }

**Comment by netdpb** [comment]
The "Error:(10, 13)" part of the error message is indicating that the error is on line 10, column 13 of the file DaggerErrorMessage.java. (I suspect your actual source code differs slightly from what you pasted.)

That should mean that your IDE shows an error indicator for that error directly on the offending component, and is why Dagger doesn't emit the name of the component.

There's already a lot of information in that error message, especially when the missing binding is at the end of a long chain of bindings and not directly at a component provision method.
