### ISSUE TITLE
launchFragmentInHiltContainer does not appear to work with the 1.2.0-beta02 of androidx.activity/androidx.fragment: "Cannot access 'EmptyFragmentActivity': it is internal in 'FragmentScenario'"

### ISSUE THREAD

**Issue by DamienDennehy** [google/dagger#2210]
After updating androidx.activity:activity-ktx and androidx.fragment:fragment-ktx to 1.2.0-beta02 from 1.2.0-beta01, the launchFragmentInHiltContainer code example found [here](https://github.com/android/architecture-samples/blob/dev-hilt/app/src/androidTest/java/com/example/android/architecture/blueprints/todoapp/HiltExt.kt#L38) and recommended [here](https://developer.android.com/training/dependency-injection/hilt-testing) does not appear to work.

`Cannot access 'EmptyFragmentActivity': it is internal in 'FragmentScenario'
e: /home/runner/work/libraries/test-config/src/debug/java/com/xxx/test_config/HiltExtensions.kt: (25, 42): Public-API inline function cannot access non-public-API 'public const final val THEME_EXTRAS_BUNDLE_KEY: String defined in androidx.fragment.app.testing.FragmentScenario.EmptyFragmentActivity.Companion'
Task :libraries:test-config:compileDevDebugKotlin FAILED`

**Comment by manuelvicnt** [comment]
The architecture-samples project use the stable version of `androidx.fragment:fragment-ktx:1.2.0`. As you're using a lower version, I'd suggest modifying the `launchFragmentInHiltContainer` yourself. Remove the `themeResId` param (line 40) and the `putExtra` method that sets it (line 48).

Thanks!

**Comment by ikurek** [comment]
I'm having the same issue with `activity-ktx 1.2.0-beta02` and `fragment-ktx 1.3.0-beta02`:
```
:app:compileStagingDebugAndroidTestKotlin FAILED
e: HiltExt.kt: (27, 33): Cannot access 'EmptyFragmentActivity': it is internal in 'FragmentScenario'
e: HiltExt.kt: (27, 55): Cannot access 'EmptyFragmentActivity': it is internal in 'FragmentScenario'
e: HiltExt.kt: (27, 55): Public-API inline function cannot access non-public-API 'public const final val THEME_EXTRAS_BUNDLE_KEY: String defined in androidx.fragment.app.testing.FragmentScenario.EmptyFragmentActivity.Companion'

```

**Comment by manuelvicnt** [comment]
I can replicate using `fragment-ktx 1.3.0-beta2`. As suspected, it's because `EmptyFragmentActivity` is now internal.

If you don't need to pass in your own theme, then remove `themeResId` from the parameters of the function and the `.putExtra` lines of the `startActivityIntent`.

If you need it, then use the fully qualified key that you can find in the implementation of `EmptyFragmentActivity`. i.e.
```
val startActivityIntent = Intent.makeMainActivity(
    ComponentName(
        ApplicationProvider.getApplicationContext(),
        HiltTestActivity::class.java
    )
).putExtra(
    "androidx.fragment.app.testing.FragmentScenario.EmptyFragmentActivity.THEME_EXTRAS_BUNDLE_KEY",
    themeResId
)
```

That's a nasty workaround but that's all we can do for now

**Comment by DamienDennehy** [comment]
Can confirm that worked. Appreciate the help on this.

**Comment by martinKindall** [comment]
@manuelvicnt that did the trick, thanks!

**Comment by SunnyBe** [comment]
Even after following the suggestion above I still get 
```java.lang.RuntimeException: java.lang.IllegalStateException: Hilt Fragments must be attached to an @AndroidEntryPoint Activity. Found: class androidx.fragment.app.testing.FragmentScenario$EmptyFragmentActivity```
