### ISSUE TITLE
Crash when using Hilt with minifyenable set to true

### ISSUE THREAD

**Issue by nitinmesta** [google/dagger#2219]
I am using dagger Hilt for dependency injection

implementation "com.google.dagger:hilt-android:2.28-alpha"
kapt "com.google.dagger:hilt-android-compiler:2.28-alpha"

Everything working fine in proguard disabled build. But when I enable proguard I get 

` Abort message: 'JNI DETECTED ERROR IN APPLICATION: JNI NewGlobalRef called with pending exception java.lang.ClassNotFoundException: Didn't find class "org.conscrypt.CryptoUpcalls" on path: DexPathList`

To fix this, I added below in proguard rule
-keep class org.conscrypt.*

After this change I am getting a native crash. Am I missing anything or there is a know issue of Hilt when proguard enabled.?

**Comment by danysantiago** [comment]
Are you sure this is an issue with Hilt? Did you experience the same problem without Hilt?

`org.conscrypt.CryptoUpcalls` is not a class in Hilt or Dagger and as far as I can tell its also not a class in neither of Hilt's dependencies.

**Comment by nitinmesta** [comment]
@danysantiago Even I was shocked. But funny thing is if I remove all the hilt dependencies and run with minifyenabled set to true app works without crash. Even I was unsure about this, So thought of checking if by any means hilt internally uses NativeCrypto

**Comment by nitinmesta** [comment]
@danysantiago I looked into it in more details and I see that https://github.com/firebase/firebase-android-sdk/issues/1677 It could be because I am using Firebase dependency `com.google.firebase:firebase-messaging:21.0.0 ` which internally has 
com.google.firebase:firebase-messaging:21.0.0
|    +--- androidx.collection:collection:1.0.0 -> 1.1.0 (*)
|    +--- androidx.core:core:1.0.0 -> 1.5.0-alpha05 (*)
|    +--- com.google.android.datatransport:transport-api:2.2.0
|    +--- com.google.android.datatransport:transport-backend-cct:2.2.0 -> 2.2.1
|    |    +--- androidx.annotation:annotation:1.1.0 -> 1.2.0-alpha01
|    |    +--- com.google.android.datatransport:transport-api:2.2.0
|    |    +--- com.google.android.datatransport:transport-runtime:2.2.1
|    |    |    +--- androidx.annotation:annotation:1.1.0 -> 1.2.0-alpha01
|    |    |    +--- com.google.android.datatransport:transport-api:2.2.0
|    |    |    \--- com.google.dagger:dagger:2.27 (*)
|    |    \--- com.google.firebase:firebase-encoders-json:16.1.0
|    |         \--- androidx.annotation:annotation:1.1.0 -> 1.2.0-alpha01

 "com.google.dagger:dagger:2.27"

And the hilt version dependency I am using is 'com.google.dagger:hilt-android-gradle-plugin:2.30.1-alpha' could this mismatch be an issue ? Is it known ? I am curious if there is any way to get this working with firebase library I am using. I tried resolution strategy to force 2.30.1 for all library which are using dagger. But the issue still exist.

**Comment by Chang-Eric** [comment]
I'm going to close this since this really does not seem like a Hilt issue. As far as I know, the only issue we might have with minification would be when we use a String-keyed map for things like ViewModels (in the same way dagger.android uses String-keyed maps for fragments), but those would generally cause runtime errors and be clearly related to Hilt. In those cases, we do package the necessary configs too (e.g. https://github.com/google/dagger/blob/master/java/dagger/hilt/android/lifecycle/proguard-rules.pro). My best guess is that removing Hilt shuffled things around enough that it no longer tickled the bug you're seeing, but it isn't actually a Hilt bug. Sorry we can't help more =\
