### ISSUE TITLE
Hilt: Non-public EntryPoint interfaces should be a compiler error (R8-related)

### ISSUE THREAD

**Issue by shekibobo** [google/dagger#2226]
When converting my application from Dagger to Hilt, I had to create a number of `@EntryPoint` interfaces throughout the app, in both Java and Kotlin files. In several of the Java files, I had forgotten to add the `public` keyword to the `interface` declaration. In debug builds, this worked fine with no warnings, errors, or runtime exceptions. However, our minified release builds were crashing immediately on application startup because the `EntryPoint`s that weren't declared public were inaccessible after minification.

Ideally, an `EntryPoint` should not compile if it wouldn't be accessible in a minified graph, so there should either be a compilation error (ideal), a lint warning (acceptable), or R8 shouldn't change the apparent visibility of the `EntryPoint` when it's minified (my understanding here is more vague - I don't know why this works at all when it's not minified).

**Comment by bcorso** [comment]
Hilt allows non-public entry points. Under the hood, Hilt will generate a public entry point that extends your non-public entry point like this:

```
public interface HiltWrapper_FooEntryPoint extends FooEntryPoint {}
```

and the generated Hilt component will extend the public `HiltWrapper_FooEntryPoint` rather than `FooEntryPoint` directly.

It sounds like the minifier is incorrectly removing code that is referenced from the generated Dagger component?

**Comment by shekibobo** [comment]
Yes, incorrect removal seems like what's happening.

**Comment by bcorso** [comment]
Thanks for confirming!

**Comment by abd3lraouf** [comment]
@bcorso any resolutions to this issue?

**Comment by bcorso** [comment]
AFAIK, this particular issue was with the R8 configuration not with Dagger/Hilt. 

Maybe @shekibobo can clarify if he was able to fix this and how.

**Comment by abd3lraouf** [comment]
@bcorso this is related to #3386
