### ISSUE TITLE
WorkManager: uses or overrides a deprecated API.

### ISSUE THREAD

**Issue by VincentJoshuaET** [google/dagger#2229]
```
package PACKAGENAME;

import androidx.hilt.work.WorkerAssistedFactory;
import androidx.work.ListenableWorker;
import dagger.Binds;
import dagger.Module;
import dagger.hilt.InstallIn;
import dagger.hilt.android.components.ApplicationComponent;
import dagger.hilt.codegen.OriginatingElement;
import dagger.multibindings.IntoMap;
import dagger.multibindings.StringKey;

@Module
@InstallIn(ApplicationComponent.class)
@OriginatingElement(
    topLevelClass = AwsWorker.class
)
public interface AwsWorker_HiltModule {
  @Binds
  @IntoMap
  @StringKey("PACKAGENAME.work.AwsWorker")
  WorkerAssistedFactory<? extends ListenableWorker> bind(AwsWorker_AssistedFactory factory);
}
```

**Comment by danysantiago** [comment]
The next version of the AndroidX extension will correctly emit code that uses the SingletonComponent and thus no longer using a deprecated API. This was done here https://android-review.googlesource.com/c/platform/frameworks/support/+/1364903 but has not been released, sorry.

**Comment by 3flex** [comment]
According to [this comment](https://issuetracker.google.com/issues/177649295#comment2) on the Google issue tracker a new release of AndroidX Hilt extension with the above change is scheduled for Jan 27.

**Comment by danysantiago** [comment]
Closing this since the extension has been released: https://developer.android.com/jetpack/androidx/releases/hilt#1.0.0-alpha03
