### ISSUE TITLE
transformClassesWithAndroidEntryPointForDebug somehow requires full build instead of building all the fragment, activity, or view that matters

### ISSUE THREAD

**Issue by thegarlynch** [google/dagger#2231]

**Comment by danysantiago** [comment]
The transform is [marked to be incremental](https://github.com/google/dagger/blob/master/java/dagger/hilt/android/plugin/src/main/kotlin/dagger/hilt/android/plugin/AndroidEntryPointTransform.kt#L50) and only needs [visibility into the applied project](https://github.com/google/dagger/blob/master/java/dagger/hilt/android/plugin/src/main/kotlin/dagger/hilt/android/plugin/AndroidEntryPointTransform.kt#L53) and not sub-projects. This should make it somewhat efficient and incremental. The 'old' transform pipeline has some issues and is actually being replaced in AGP 4.2. Hilt is migrating to using the new pipeline which should make things more efficient and incremental. https://github.com/google/dagger/pull/2224
