### ISSUE TITLE
Dagger hilt kapt vs annotationProcessor issues

### ISSUE THREAD

**Issue by underwindfall** [google/dagger#2255]
# Context

My `dagger-hilt` module has been coded in `java`, some classes (which contains `@AndroidEntryPoint`) I try to `inject` were written by `java`, some of them were written by kotlin.  So when I use `dagger hilt` to do the injection,  I have some erros such as 

```groovy
Execution failed for task ':app:transformClassesWithAndroidEntryPointTransformForDebug'.
> javassist.NotFoundException: 
```

BTW, I created a `template project` to reproduce this bug here is the link https://github.com/underwindfall/dagger_issue_project

### Try to use `kapt` instead of `annotationProcessor`
I noticed that I was always use `annotationProcessor` as `implementation` dependency,  at the begining of project, I thought it's just for this `"com.google.dagger:hilt-android-compiler:$hilt_version"` is only for ` Dagger Module`, since my dagger modules were coded by `Java` only , Classes like `Activity`  etc we can still keep it as `Kotlin`. 
Turns out it's not.
Try to use `kapt` instead of `annotationProcessor`  did solve the issue.

### Try to code only by java or by kotlin
 Yes the project can be compiled.

**Comment by bcorso** [comment]
Yes, annotations that need to be processed on kotlin sources need to depend on processors via `kapt`. annotations that need to be processed on java sources can depend on processors via `annotationProcessor` or `kapt`. If you have a mix of java and kotlin sources that have annotations that need to be processed then you are forced to use `kapt` to handle both java and kotlin.

However, these rules apply in general and are not something specific to Hilt.  Did you have something specific in mind that you want us to do in Hilt?

**Comment by underwindfall** [comment]
Not necessaily. However i have anther question, it's kind of off this topic. 

In `Hilt`, is there any way to rebuild the dagger tree ?

**Comment by bcorso** [comment]
I'm going to close this issue since I don't think there's anything actionable we can do on our side.

However, feel free to continue the discussion of your other question here or open an new issue.

> In Hilt, is there any way to rebuild the dagger tree ?

Can you explain what you mean by "rebuild the dagger tree"? Typically rebuilding (aka compiling) happens automatically by Gradle and is determined by which sources have changed. 

Or by "rebuild" do you mean something different like add/remove/change bindings in the Dagger graph at runtime?

**Comment by underwindfall** [comment]
> I'm going to close this issue since I don't think there's anything actionable we can do on our side.
sure go ahead.

"rebuild"  I mean add/remove/change bindings in the Dagger graph at runtime

**Comment by bcorso** [comment]
In general, Dagger 2 does not allow modifying the Dagger graph at runtime. The entire graph is determined and validated at compile time.

However, there may still be a way to do what you want. Can you give a more specific example of what you're trying to do and why you want to do it?

**Comment by underwindfall** [comment]
Sure. Here is an example.

## Introduction
I have a boolean varaiable `demoModeEnabled` in `DummyApplication`, this `demoModeEnabled` can be changed by some method. And based on this varaiable `demoModeEnabled`,  it depends on can be provided by different `Interface implementation` classes.

## Class

DummyApplication.java
```java
@HiltAndroidApp
public class DummyApplication extends Application {
    //this can be change by some method
    private boolean  demoModeEnabled;

    public boolean isDemoModeEnabled() {
        return modeEnabled;
    }

   public void setDemoModeEnabled(boolean enable) {
       this.enable = demoModeEnabled;
   }
}
```

DashboardModule.java
```java
@InstallIn(ActivityComponent.class)
@Module
public class DashboardModule {
    @NonNull
    @Provides
    DashboardContract.Interactor
    provideDashboardInteractor(@NonNull final DummyApplication application) {
          if (application.isDemoModeEnabled()) {
                 return new DashboardInteractorDemoImpl();
          } else {
                 return new DashboardInteractorImpl();
          }
    }
}
```

DashboardInteractorDemoImpl.kt

```kotlin
class DashboardInteractorDemoImpl : DashboardContract.Interactor {
}
```

DashboardInteractorImpl.kt

```kotlin
class DashboardInteractorImpl : DashboardContract.Interactor {
}
```

DashboardActivity.kt
```kotlin
classs DashboardActivity : DashboardContract.View {
 @Inject
 internal lateinit var interactor : DashboardContract.Interactor
}
```

**Comment by bcorso** [comment]
The example, seems fine as long as `demoModeEnabled` isn't changed while an instance of the `DashboardActivity` is active. 

However, if the `demoModeEnabled` value can change while `DashboardActivity` is active, it sounds like you would either need to register an observer for the change and either
  1. Update all related state in `DashboardActivity` manually,
  2. or recreate the activity when the value changes (which would inject the new, correct value).

If you're going with 1, you could do that by injecting `Provider<DashboardContract.Interactor>` and re-getting the value on each change.

Either way, it should be possible without modifying the Dagger graph at runtime.

**Comment by underwindfall** [comment]
Your comment here enlighten me to update the lastest state manually.  Thx a lot. 

>However, there may still be a way to do what you want.
Just for the curiosity, you mentioned there may a way to modify dagger at runtime. Could you introduce some how to do it ?

**Comment by bcorso** [comment]
Sorry, that statement was a bit misleading. What I meant was that there may still be a way to do what you want without modifying the Dagger graph at runtime.

In particular, while Dagger does not allow you to modify the *graph* at runtime, you can change the value provided at runtime -- for example, exactly what you are doing in `DashboardModule` by returning a different implementation depending on the `demoModeEnabled` value. Which is why I wanted a particular example, to determine exactly what you meant by "runtime" since these easily get confused.

**Comment by underwindfall** [comment]
Gotya, thanks for clarifying. Now the details of dagger-hilt looks more clear to me.
