### ISSUE TITLE
Unable to update Dagger 2 to Dagger 2.30 . Getting Execution failed for task ':app:kaptDebugKotlin'. error in build log?

### ISSUE THREAD

**Issue by RageshAntony** [google/dagger#2258]
I tried to upgrade Dagger 2 from 2.17 to 2.30 .

I got some depreciation error and I fixed them

And after building again , I got error without explanation
```

> Task :app:kaptDebugKotlin FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:kaptDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.gradle.internal.KaptExecution
   > java.lang.reflect.InvocationTargetException (no error message
I can't find what's went wrong here .

```
please help me . I am attaching stack trace here with Gradle

https://gist.github.com/RageshAntony/9ec42c77d5c02c9dd567230c0fb2322a

Gradle build tools: : 4.1.1
Gradle : 6.7.1
Kotlin : : 1.4.20
dagger : 2.30

**Comment by bcorso** [comment]
Hi @RageshAntony, I think this is #2190, which should be fixed in [Dagger v2.30.1](https://github.com/google/dagger/releases/tag/dagger-2.30.1).
