### ISSUE TITLE
Invalid Java in Hilt Testing docs

### ISSUE THREAD

**Issue by another-dave** [google/dagger#2260]
Minor one, but noticed that the Java docs for Hilt testing set-up are incorrect, under [Hilt Testing Guide: UI test setup](https://developer.android.com/training/dependency-injection/hilt-testing#java). 

The Java code snippet has:

```java
@HiltAndroidTest
public final class SettingsActivityTest {

  @Rule public hiltRule rule = new HiltAndroidRule(this);

  // UI tests here.
}
```

whereas it should be:

```java
@HiltAndroidTest
public final class SettingsActivityTest {

    @Rule
    public HiltAndroidRule rule = new HiltAndroidRule(this);

    // UI tests here.
}
```

(Apologies if this is the wrong place for documentation corrections. Just let me know if it should be on issuetracker.google.com instead and I can raise it there. If so, if you could give a pointer to _where_ it should be added so I can find it that would be great :pray:)

**Comment by Chang-Eric** [comment]
I think technically this isn't the right place since we only track docs at dagger.dev here, but @manuelvicnt should know the right place for this.

**Comment by manuelvicnt** [comment]
Thanks for filing this. Just created a PR to update the docs. Thank you!

**Comment by another-dave** [comment]
Thanks @manuelvicnt! 

For next time, is there a better place I should raise it? Looking again, is is here: [issuetracker.google.com - 'developer.android.com' component](https://issuetracker.google.com/components/192697/manage#basic)? Always feel a bit lost in the issue tracker :see_no_evil:

**Comment by manuelvicnt** [comment]
I think it should be fine to file it in the developer.android.com issue tracker component. People looking at the bugs should be able to route it to the right team/person. Thanks again :)
