### ISSUE TITLE
Couldn't inject @Binds Hilt Dependencies in WorkManager using @WorkerInject

### ISSUE THREAD

**Issue by roshanpv** [google/dagger#2270]
I tried to build the below code after following the [Hilt-WorkManager official documentation
](https://developer.android.com/training/dependency-injection/hilt-jetpack#workmanager)

**Worker class**

```
class StartJobWorker @WorkerInject constructor(
    @Assisted appContext: Context,
    @Assisted workerParams: WorkerParameters,
    private val startJobUseCase: StartJobUseCase,
) : CoroutineWorker(appContext, workerParams) {

    override suspend fun doWork(): Result {
        val jobId: Long = inputData.getLong(AppConstant.JOB_ID, 0)
        return when (val workResult: WorkResult = startJobUseCase(jobId)) {
            is WorkResult.Success<*> -> Result.success()
            is WorkResult.Failure<*> -> Result.failure()
            WorkResult.Retry -> Result.retry()
        }
    }

}
```

**Hilt Module**

```
@Module
@InstallIn(ActivityComponent::class)
abstract class UseCaseModule {

    @ActivityScoped
    @Binds
    abstract fun bindStartJobUseCase(startJobUseCaseImpl: StartJobUseCaseImpl): StartJobUseCase

}
```

**Dependency abstraction**

```
interface StartJobUseCase {
    suspend operator fun invoke(jobId: Long): WorkResult
}
Dependency Implementation

class StartJobUseCaseImpl @Inject constructor(
    private val startJobRepository: StartJobRepository
) : StartJobUseCase {

    override suspend fun invoke(jobId: Long): WorkResult {
        return startJobRepository.startJob(jobId)
    }

}
```
I got the following error message in the compilation.

`error: [Dagger/MissingBinding] com.example.domain.StartJobUseCase cannot be provided without an @Provides-annotated method.`

I could fix the issue temporarily with the following changes in **Hilt Module**
```
@InstallIn(ApplicationComponent::class)
@Module
object UseCaseModule {

    @Provides
    fun provideStartJobUseCase(startJobRepository: StartJobRepository): StartJobUseCase =
        StartJobUseCaseImpl(startJobRepository)

}
```

**Comment by dmapr** [comment]
Total shot in the dark here, but having an `ActivityScoped` dependency in the worker is suspicious to me and in your workaround you've moved the provider from installing in `ActivityComponent` to installing in `ApplicationComponent`.  Which begs the question: will `@Binds` work in the `ApplicationComponent`?

**Comment by roshanpv** [comment]
> Total shot in the dark here, but having an `ActivityScoped` dependency in the worker is suspicious to me and in your workaround you've moved the provider from installing in `ActivityComponent` to installing in `ApplicationComponent`. Which begs the question: will `@Binds` work in the `ApplicationComponent`?

You are right. ActivityScoped was part of the problem. Swapping ActivityComponent with ApplicationComponent and removing @ActivityScoped in UseCaseModule class fixed the issue. I guess all dependencies for Worker classes should be in a module installed in ApplicationComponent.
And Yes, @Binds works in the ApplicationComponent.
