### ISSUE TITLE
AssistedInject - Manually passing class annotated with @AssistedInject

### ISSUE THREAD

**Issue by mlykotom** [google/dagger#2278]
We were using [AssistedInject](https://github.com/square/AssistedInject) from square and wanted to migrate to the official feature.

There is one restriction which probably is wrong:

Let's have class with AssistedInject and some dependencies.
```kotlin

class ManuallyCreated @AssistedInject constructor(....){

   @AssistedFactory
   interface Factory{
      fun create(....) : ManuallyCreated
   }

}
```

and then inject the factory and create the object

```kotlin

class HereFactoryIsInjected @Inject constructor(
   private val manualyCreatedFactory: ManuallyCreated.Factory
){

  val manuallyCreatedInstance = manualyCreatedFactory.create(...)

}


```

and now let's have another class with `AssistedInject` which would take the manually created instance as `@Assisted`

```kotlin

class ThisClassNeedsManuallyCreated @AssistedInject constructor(
   ...,
   @Assisted manuallyCreated : ManuallyCreated
){

   @AssistedFactory
   interface Factory {
  
     fun create(manuallyCreated: ManuallyCreated): ThisClassNeedsManuallyCreated
  
   }

}

```

Which leads in compilation error:
```
Dagger does not support injecting @AssistedInject type, ManuallyCreated. Did you mean to inject its assisted factory type instead?
```

Is the restriction needed? From my perspective passing something manually shouldn't be problem?

Thanks!

**Comment by bcorso** [comment]
Yes, I think you're right. In this case we should not run that validation for the `@Assisted` parameters.

I'll put together a fix shortly.
