### ISSUE TITLE
[AssistedInject] Support Kotlin data classes 

### ISSUE THREAD

**Issue by vRallev** [google/dagger#2299]
This code compiles fine:
```kotlin
class AssistedService @AssistedInject constructor(
  val integer: Int,
  @Assisted val string: String
) 
```
This code fails:
```kotlin
data class AssistedService @AssistedInject constructor(
  val integer: Int,
  @Assisted val string: String
) 
```
The error is:
```
/path/build/tmp/kapt3/stubs/main/package/AssistedService.java:39: error: @Assisted parameters can only be used within an @AssistedInject-annotated constructor.
    java.lang.String string) {
```
This is how the the stub file looks like and the error seems to be misleading:
```java
    @dagger.assisted.AssistedInject()
    public AssistedService(int integer, @org.jetbrains.annotations.NotNull()
    @dagger.assisted.Assisted()
    java.lang.String string) {
        super();
    }
```
Please let me know if you need any further information.

**Comment by bcorso** [comment]
@vRallev thanks for the repro case!

It looks like the error is not coming from the stub's constructor, but from the `copy()` method as shown below:

```java
public final class AssistedService {
    @AssistedInject
    public AssistedService(int integer, @NotNull @Assisted String string) {...}
    
    // error: @Assisted parameters can only be used within an @AssistedInject-annotated constructor.                                                                               
    public final AssistedService copy(int integer, @NotNull @Assisted String string) {...}
}
```

I'm not sure if there is a way to work around this on the user side, but we can add a check within Dagger to allow this specific case for kotlin data classes. We should be able to confirm this is a data class from the Kotlin Metadata annotation using [`kotlinx.metadata.Flag.Class.IS_DATA`](https://github.com/JetBrains/kotlin/blob/master/libraries/kotlinx-metadata/src/kotlinx/metadata/Flag.kt#L191).

**Comment by JakeWharton** [comment]
For ours we just blanket ignore methods named "copy" and don't bother checking the metadata. But I guess if you already have it might as well...

**Comment by bcorso** [comment]
Thanks! This should be fixed by https://github.com/google/dagger/commit/208c05488bbec705a2de8f54abf3e13813343207

**Comment by vRallev** [comment]
Wow, that was quick. Looking forward to the next release.
