### ISSUE TITLE
[AssistedInject] Dagger does not support providing @AssistedFactory types - overly restrictive 

### ISSUE THREAD

**Issue by rjaylwar** [google/dagger#2301]
Sometimes the restriction of not providing `AssistedFactory` classes is overly restrictive. This is a pattern I had to expose classes from one library module to another. 

**Library B** depends on **Library A** and also the **Core Library**. **Library B** wants to add a factory class from **Library A** to the **Library B** component. 

It worked fine with [Square's AssistedInject](https://github.com/square/AssistedInject) library but now it fails. My goal is just to add an AssistedFactory class from one gradle module to the Dagger Component in another gradle module.

**error: [com.librarya.LibraryADataFetcher.InjectorFactory] Dagger does not support providing @AssistedFactory types.**

```kotlin
/**
 * Core Gradle Module
 */
@Module
object CoreDiModule {
    @JvmStatic
    @Singleton
    @Provides
    fun providesPreferences(context: Context): Preferences = Preferences.getInstance(context)
}

@Singleton
@Component(modules = [CoreDiModule::class])
interface CoreDiComponent {
    val preferences: Preferences

    @Component.Factory
    interface Factory {
        fun create(@BindsInstance context: Context): CoreContextComponent
    }
}
```

```kotlin
/**
 * Library A Gradle Module
 */
@Module
interface LibraryAModule {
    @Module
    companion object {
        @JvmStatic
        @Provides
        fun provideLibraryADao(context: Context): LibraryADao = LibraryADao(context)
    }
}

@LibraryScope
@Component(
        modules = [LibraryAModule::class],
        dependencies = [CoreDiComponent::class]
)
interface LibraryAComponent {
    @Component.Factory
    interface Factory {
        fun create(@BindsInstance coreContextComponent: CoreContextComponent): SearchComponent
    }

    val libraryADataFetcher: LibraryADataFetcher.InjectorFactory
}

/**
 * This is the class we want to expose from LibraryA to LibraryB
 */
class LibraryADataFetcher @AssistedInject constructor(
        @Assisted private val id: Int,
        private val context: Context,
        private val preferences: Preferences,
        private val dao: LibraryADao
) {
    @AssistedFactory
    interface InjectorFactory {
        fun create(id: Int): LibraryADataFetcher
    }
}
```

```kotlin
/**
 * Library B Gradle Module
 */
@LibraryScope
@Component(
        modules = [LibraryBModule::class],
        dependencies = [CoreContextComponent::class] //also dependent on LibraryAComponent
)
interface LibraryBComponent {
    @Component.Factory
    interface Factory {
        fun create(
                coreContextComponent: CoreContextComponent,
                @BindsInstance libAComponent: LibraryAComponent
        ): LibraryBComponent
    }
}

@Module
interface LibraryBModule {
    @Module
    companion object {

        /**
         * this attempts to add the factory from library A but this line throws the error
         */
        @JvmStatic
        @Provides
        fun provideLibraryADataFetcherFromLibA(
                libraryAComponent: LibraryAComponent
        ): LibraryADataFetcher.InjectorFactory = libraryAComponent.libraryADataFetcher
    }
}
```

The workaround is to just not use `@AssistedInject` and create an explicit factory class and use `@Inject` instead.

**Comment by bcorso** [comment]
Hi @rjaylwar,

It sounds like you want to share the assisted factory (`LibraryADataFetcher.InjectorFactory`) instance between `LibraryAComponent` and `LibraryBComponent`. Is that correct?

My first thought is that it sounds like `LibraryAComponent` should be a component dependency of `LibraryBComponent` rather than bound using `@BindsInstance`. 

Is there a particular reason you can't use component dependencies?

**Comment by rjaylwar** [comment]
Originally I did not do that because I had the same scope annotation on both LibraryAComponent and LibraryBComponent - `@LibraryScope` and `@Singleton` on the CoreContextComponent. That combination fails with the error **dagger depends on scoped components in a non-hierarchical scope ordering:**. 

It does seem to work component dependencies if I give a different scope to LibraryAComponent (`@LibraryScope`) and LibraryBComponent (`@AnotherLibraryScope`) so I can probably switch to doing that.

I would only mention that it does still seem odd for my original use case to fail because dagger has enough information in this function to provide the `LibraryADataFetcher.InjectorFactory` via the `@Provides` method even if it is a bit non-standard, there just seems to be a hard and fast rule to fail whenever something in a module has the `@AssistedFactory` annotation which might not always be necessary.
```kotlin
@Module
interface LibraryBModule {
    @Module
    companion object {

        /**
         * this attempts to add the factory from library A but this line throws the error
         */
        @JvmStatic
        @Provides
        fun provideLibraryADataFetcherFromLibA(
                libraryAComponent: LibraryAComponent
        ): LibraryADataFetcher.InjectorFactory = libraryAComponent.libraryADataFetcher
    }
}
```

**Comment by bcorso** [comment]
> Originally I did not do that because I had the same scope annotation on both LibraryAComponent and LibraryBComponent - @LibraryScope and @Singleton on the CoreContextComponent. That combination fails with the error dagger depends on scoped components in a non-hierarchical scope ordering:.

Using a different scope annotation for the components is good, but you can also use the compiler options to suppress that error if you need to: `-Adagger.disableInterComponentScopeValidation=none`.

> I would only mention that it does still seem odd for my original use case to fail because dagger has enough information in this function to provide the LibraryADataFetcher.InjectorFactory via the @Provides method even if it is a bit non-standard, there just seems to be a hard and fast rule to fail whenever something in a module has the @AssistedFactory annotation which might not always be necessary.

It is technically possible to make this work, but for now we'd rather not allow it. In particular, we'd like to prevent the case where someone injects an `@AssistedFactory` type but gets a completely different implementation than the one Dagger generates because that would be very confusing. While your implementation seems legitimate because you're just passing along the Dagger generated factory, in general Dagger has no way to validate that you've done it correctly.

You should also be able to work around this issue (if you really needed to) by using a separate interface that does not have the `@AssistedFactory` annotation, and binding them together with a module like:

```
@Module
interface FooFactoryModule {
  @Binds FooFactory bind(AssistedFooFactory impl);
}

@AssistedFactory
interface AssistedFooFactory extends FooFactory {}

// Inject this factory everywhere you need an AssistedFooFactory
interface FooFactory {
  Foo create(...);
}
```

Hope that helps!

**Comment by rjaylwar** [comment]
Understood. Just wanted to mention it since it was the one error I encountered when migrating from the standalone AssistedInject library. Thanks for the help.

**Comment by bcorso** [comment]
Thanks!
