### ISSUE TITLE
Replace androidx.hilt.Assisted with dagger.assisted.Assisted

### ISSUE THREAD

**Issue by VladyslavKasprov** [google/dagger#2307]
Should android.hilt.Assisted annotation be removed now that Dagger supports assisted injection and has it's own dagger.assisted.Assisted annotation?

Otherwise it might get confusing if you accidentally import wrong annotation and break the build.

**Comment by danysantiago** [comment]
Yes - The next release of androidx will have the type [deprecated](https://android-review.googlesource.com/c/platform/frameworks/support/+/1546842/7/hilt/hilt-common/src/main/java/androidx/hilt/Assisted.java) and it'll be removed in a future version.
