### ISSUE TITLE
[AssistedInject] Generated factory compilation error

### ISSUE THREAD

**Issue by stavfx** [google/dagger#2309]
Given this setup
```kotlin
@Component
interface MyComponent {
    fun factory(): MyFactory
}

@AssistedFactory
interface MyFactory {
    fun create(foo: Boolean): MyPresenter
}

class MyPresenter @AssistedInject constructor(
    @Assisted private val foo: Boolean
)
```
The following Factory implementation is created
```kotlin
@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class MyFactory_Impl implements MyFactory {
  private final MyPresenter_Factory delegateFactory;

  MyFactory_Impl(MyPresenter_Factory delegateFactory) {
    this.delegateFactory = delegateFactory;
  }

  @Override
  public MyPresenter create(boolean foo) {
    return delegateFactory.get(foo);
  }

  public static Provider<MyFactory> create(MyPresenter_Factory delegateFactory) {
    return InstanceFactory.create(new MyFactory_Impl(delegateFactory));
  }
}
```
Which yields this error in the static `create` method:
`error: incompatible types: Factory<MyFactory_Impl> cannot be converted to Provider<MyFactory>`.

This seems like a type inference issue because this can be fixed by explicitly setting the generic type of `InstanceFactory.create` like so:
`return InstanceFactory.<MyFactory>create(new MyFactory_Impl(delegateFactory));`
(or casting MyFactory_Impl, or a few other tricks).

I feel like this should work, but am I also doing something wrong?

**Comment by bcorso** [comment]
Hi @stavfx,

Thanks for reporting this. I think you're right that this is likely a type inference issue that works with java 8 but has issues with java 7. I'll look into fixing this for the next release.
