### ISSUE TITLE
Injecting component objects

### ISSUE THREAD

**Issue by juanyanezgc** [google/dagger#231]
I've tried to inject a component and I got the following error at compile time:

Error:Execution failed for task > java.lang.UnsupportedOperationException: Not yet supporting COMPONENT binding types.

Any particular reason for this not being supported? As a workaround, I've tried wrapping the component into another object and that way I'm able to inject that wrapper and indirectly inject the component.

 Is there any issues about injecting components objects I should be aware of?

**Comment by netdpb** [comment]
Can you include more of the stack trace? That looks like it's an error that is thrown when Dagger tries to report duplicate bindings.

Could it be that you have a `@Provides` method that also returns the component type?

**Comment by netdpb** [comment]
We have reproduced this internally, and will fix.

**Comment by ronshapiro** [comment]
Reopen if you're still getting this issue in Dagger 2.6, but this should be fixed.
