### ISSUE TITLE
Hilt Instrumentation testing viewModel with dependencies

### ISSUE THREAD

**Issue by alexKatona** [google/dagger#2318]
Hello, I ahve a question regarding ViewModel testing. Lets say in a large project with a lot of screen, we want to test only the viewModels and beyond to save time on CI. Ideally we create a viewModel in tests, trigger some action and expect a state which is testable.

Lets say I have a viewmodel
```
@HiltViewModel
class LoginViewModel @Inject constructor(
 // some dependencies here
 )
 ```
 
 and in tests I want to do something like

```
test{
initializeViewModelTest<LoginViewModel>{ loginViewModel ->
loginViewModel.emailTyped(email)
loginViewModel.expectStateEmited(error) // this is up to the app implementation
 }
}
```

currently I am creating a viewmodel in a way I dont really like it since it takes time to load the activity for each test
```
inline fun <reified VIEWMODEL : BaseViewModel<*>> BaseTest.initializeViewModelTest(crossinline testingBlock: VIEWMODEL.() -> Unit) {
    ActivityScenario.launch(TestActivity::class.java).use {
        it.onActivity {
            it.viewModels<VIEWMODEL>().value.let {
                runBlocking {
                    it.testingBlock() // here I can run the test above since the viewModel is properly created
                }
            }
        }
    }
}
```

Is there a better way to do this ? not sure if its an upcoming enhancement for example. It would be cool to just inject the viewModel like 
```
@Inject
lateinit var loginViewModel
```
but I get that it might not be possible

**Comment by Chang-Eric** [comment]
Unfortunately, this isn't really a method of testing we can support. Creating a view model without a backing activity would probably get into a weird place with behavior that would probably overall lead to a worse testing experience. This is similar to how if you want to test a fragment you need to create an activity (even though there are things like `FragmentScenario`, it is just creating the activity for you under the hood).
