### ISSUE TITLE
Dagger 1 and dagger 2 package name conflict

### ISSUE THREAD

**Issue by dconan** [google/dagger#232]
Hi,
i have andorid project in which one 3rd party librarie is depending on dagger 1 and my project on dagger 2. Dagger 1 and 2 have the same package names so my app is working fine but 3rd party librarie is not working because of overriding dagger 1 package by dagger 2. Changing package name of dagger 2 to "dagger2" instead of "dagger" is not an option because anotation compiler is generating classes with static package name "dagger". 
Can you provide some solution? 
Thanks. 
Dominik

**Comment by cgruber** [comment]
You should be able to exclude the dagger 1 dependency.  If your third_party library is depending on parts of the dagger 1 api that aren't in dagger 2 (e.g. ObjectGraph) then I have deep suspicions that the library is not going to be very useful to you.  

What parts of dagger 1 is the third_party library depending on?

**Comment by ronshapiro** [comment]
Looks like we haven't gotten a response, feel free to reopen if this is still an issue for you. 

p.s. you may want to check out [jarjar](https://code.google.com/p/jarjar/)
