### ISSUE TITLE
[Hilt] Java compiler complains about "[cast] redundant cast to Object" in the generated code

### ISSUE THREAD

**Issue by sergeys-opera** [google/dagger#2339]
**Steps to reproduce**:

1. Enable `javac` lint and turn warning into errors:
```
    allprojects {
        gradle.projectsEvaluated {
            tasks.withType(JavaCompile) {
                // Turn warnings into errors.
                options.compilerArgs << '-Werror'
                // Enable lint.
                options.compilerArgs << '-Xlint'
            }
        }
    }
```
2. Add `@HiltAndroidApp` annotation to your application class.
3. Compile the project.

**Expected**: compilation succeeds
**Actual**: compilation fails with an error:
```
> Task :app:compileDebugJavaWithJavac FAILED
/x/y/z/DaggerXxxApplication_HiltComponents_SingletonC.java:133: warning: [cast] redundant cast to Object
      return (Object) local;
             ^
error: warnings found and -Werror specified
1 error
1 warning

warnings found and -Werror specified
```

The generated code indeed contains a redundant class cast:
```
    private Object lifecycle() {
      Object local = lifecycle;
      if (local instanceof MemoizedSentinel) {
        synchronized (local) {
          local = lifecycle;
          if (local instanceof MemoizedSentinel) {
            local = ActivityRetainedComponentManager_Lifecycle_Factory.newInstance();
            lifecycle = DoubleCheck.reentrantCheck(lifecycle, local);
          }
        }
      }
      return (Object) local;
    }
```

**Workaround**: disable `cast` check in javac's linter:
```
options.compilerArgs << '-Xlint:-cast'
```

Hilt version: 2.31.2-alpha
Javac version: 1.8.0_275 (same for 1.11.0)

**Comment by bcorso** [comment]
@sergeys-opera thanks for reporting this! 

I was able to repro the issue. I'll see what we can do to remove the redundant cast.

**Comment by sergeys-opera** [comment]
@bcorso one simple fix is to add `@SuppressWarnings("cast")` in the generated code.

**Comment by jaredsburrows** [comment]
Any update on this?

**Comment by bcorso** [comment]
Hmm, I forgot to get back to this, but I think we don't even generate the problematic code referenced in https://github.com/google/dagger/issues/2339#issue-796950988 since around version 2.38.

Which version of Dagger are you using?

Can you show your stack trace?

**Comment by jaredsburrows** [comment]
Seems to be find now - https://github.com/jaredsburrows/android-gif-example/pull/149. Maybe we can close this?

**Comment by bcorso** [comment]
Yep, closing seems reasonable. Thanks for the ping on this issue.
