### ISSUE TITLE
Using dependency injection between modules

### ISSUE THREAD

**Issue by pablobaldez** [google/dagger#234]
The context:
- I Have two modules in my project: A and B
- The module A depends on module B
- The module B have a Dagger 2 dependency defined into my gradle file
- The module A have components that use @modules classes from Module B to provide the intances to use with dependency injection

The problem:
The Dagger 2 processor, responsible to code generation, doesn't create any classes necessaries to provide the dependencies defined on @module classes located on module B.

**Comment by Zhuinden** [comment]
You need to specify a component for your module called Module B such as Component B which has Module B as its module, specify the dependencies provided by the module in provision methods, then you should make Component A that has Module A extend from Component B, and specify Component B as a component dependency.

You essentially need to do exactly this: http://stackoverflow.com/a/31865368/2413303

**Comment by netdpb** [comment]
I don't understand what you mean when you say "module A depends on module B". Modules don't usually refer to each other in any way other than by `@Module.includes`.

Or does "module A" mean something other than a `@Module`-annotated class—like a collection of related classes?

Can you reply here with some code samples showing the problem?

**Comment by pablobaldez** [comment]
Sorry for my delay to answer. When I'm saying about module dependencies, i'm saying about Android Studio modules (app, libs, and something like this). 
But I solve my problem refactoring my project following @Zhuinden instructions

**Comment by netdpb** [comment]
OK, great! I'll close this issue then.
