### ISSUE TITLE
Give opportunity to config the provided Instances by dagger

### ISSUE THREAD

**Issue by jinweihan2020** [google/dagger#2346]
Hi, this is a feature request:
Could we have an opportunity to config the provided Instances, both from constructor and from module+provide?

**Comment by bcorso** [comment]
Hi @jinweihan2020,

Just so we're on the same page, can you give an example of what you want to do and why you want to do it?

**Comment by jinweihan2020** [comment]
@bcorso 
Hi thanks for responding!
For example, we have a lot of class Presenters like APresenter, BPresenter, CPresenter, now, we hope to do some init configuration right after the object generated.Now they are all have @Inject on constructor, so if dagger2 provides a chance to let us config the Presenters instances just after called `new`, it would make the init configuration become super clear and clean. That would be a great feature for us!
Thanks

**Comment by bcorso** [comment]
> we hope to do some init configuration right after the object generated.

It sounds like method injection will do what you want. If you annotate a method in your class with `@Inject` Dagger will call it immediately after calling your `@Inject` constructor.

```java
class APresenter {
  @Inject APresenter(...) {...}

  // This method will be called write after constructor injection
  @Inject void configure(...) {...}
}
```

Internally, Dagger will generate a getter like this:


```java
public APresenter getAPresenter() {
  APresenter instance = new APresenter(...);
  instance.configure(...);
  return instance;
}
```

**Comment by yshrsmz** [comment]
Is there any problem with calling a config function in the constructor?

**Comment by jinweihan2020** [comment]
@bcorso @yshrsmz Thanks for suggestion.
In our case, something is different, like AFeature depends on APresenter, and can we get a `Provider<AFeature>` in params of configure(), like `configure(Provider<HolderObject> feature)`? (Provider could be an WeakReference inside, HolderObject is AFeature here ..)
The reversed reference relationship is useful in my case.

**Comment by bcorso** [comment]
Ah, I see. From a static analysis perspective, a dependency chain like `AFeature -> APresenter -> Provider<AFeature>` should be fine in Dagger because `Provider`/`Lazy` can be used to break dependency cycle. However, I'm guessing the issue that you're running into is that the configuration logic calls `aFeatureProvider.get()` while constructing `APresenter`, is that right?

One way you may be able to get around this is to move the provider in the dependency chain, like `AFeature -> Provider<APresenter> -> AFeature`. For example

```java
@Singleton
class AFeature {
  Provider<APresenter> aPresenterProvider;

  @Inject
  AFeature(Provider<APresenter> aPresenterProvider) {
    // Don't call aPresenterProvider.get() here or you'll infinite loop
    this.aPresenterProvider = aPresenterProvider;
  }

  void doSomething() {
    // Calling aPresenterProvider.get() is fine here since both objects have already been constructed
    ... aPresenterProvider.get();
  }
}
```

```java
@Singleton
class APresenter {
  AFeature aFeature;

  @Inject
  APresenter(AFeature aFeature) {
    this.aFeature = aFeature;
    // Using aFeature here is fine
  }

  @Inject
  void configure() {
    // Using aFeature here is fine
  }
}
```

**Comment by bcorso** [comment]
@jinweihan2020, since there's been no response in a few days I'm going to close this. 

However, feel free to continue the conversation if the above suggestion does not meet your needs.
