### ISSUE TITLE
Ability to compose anntations

### ISSUE THREAD

**Issue by ursusursus** [google/dagger#2347]
Hi,
I have plugin framework enabled via multibinding.

I always need to attach all these annotations to make it work

```
@AppScopedInitialized
@IntoSet
@Provides
@JvmStatic
fun widgetUpdater(): Scoped...
```

This is error prone and tideous (Somebody always forgets the `@IntoSet` ). 

Would it be possible to add a custom `@MyCustomWhatever` annotation which would be a composition of those 4? (or abitrary in general) 

I tried at language level, but it seems that its not supported. Only if given framework (dagger) would provide such api. Spring seems to have `@AliasFor` https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/core/annotation/AliasFor.html

Would that be possible? It would unlock great new "scripting" ability

**Comment by bcorso** [comment]
Hi @ursusursu,

One way you can enforce your own validation is with a [Dagger SPI plugin](https://dagger.dev/dev-guide/spi). For example, if you have a particular type, like `@AppScopedInitialized Scoped...`, that should always use `@IntoSet` then you can enforce that with a [`BindingGraphPlugin`](https://dagger.dev/api/2.19/dagger/spi/BindingGraphPlugin.html).

**Comment by Chang-Eric** [comment]
Another option that we often suggest as an alternative is to write your own code generator. Especially if you are using Hilt, generating modules shouldn't be too difficult and it also gives you greater flexibility with your API.

I don't think we want to do generic aliases of annotations directly in Dagger though as it could get confusing when reading the code. I worry that Dagger is already hard for beginners to pick up and further obfuscating APIs may only worsen that.

**Comment by ursusursus** [comment]
@Chang-Eric that's however not the SPI plugin mentioned above right? I'd completely custom codegen right? SPI would be only used to make sure developer adds all the annotations, right?

**Comment by Chang-Eric** [comment]
Correct. I was suggesting an alternative where the developers writes something like

```
@BindMyCustomThing
fun widgetUpdater(): Scoped...
```

and the code generator generates a module with your code snippet.
