### ISSUE TITLE
Two components with same subcomponent: attempt to recreate a file

### ISSUE THREAD

**Issue by pyricau** [google/dagger#235]
This one was fun to repro.

TL;DR: I want both component A and component B to declare a subcomponent C that lives in a separate package. Dagger generates a  `XXX_PackageProxy` for package protected stuff that C injects, and it's generated one for each component A and B.

Here's the sample code:

In package fr.baguette:
```java
package fr.baguette;

import fr.croissant.Injected;
import dagger.Component;
import dagger.Subcomponent;
import javax.inject.Scope;

public interface Test {

  @Scope @interface Singleton {
    Class<?> value();
  }

  @Singleton(RootComponent.class) //
  @Component //
  interface RootComponent {
    LeafComponent subcomponent();
  }

  @Singleton(RootComponent2.class) //
  @Component //
  interface RootComponent2 {
    LeafComponent subcomponent();
  }

  @Singleton(LeafComponent.class) //
  @Subcomponent //
  interface LeafComponent {
    void inject(Injected injected);
  }
}
```

In package fr.croissant:

```java
package fr.croissant;

import fr.baguette.Test;
import javax.inject.Inject;

public class Injected {

  @Inject State state;

  @Test.Singleton(Test.LeafComponent.class) //
  static class State {
    @Inject State() {
    }
  }
}
```

Dagger compiler attempts to generate the following class twice, once for `DaggerTest_RootComponent` and once for `DaggerTest_RootComponent2`

```java
package fr.croissant;

import fr.croissant.Injected.State;
import javax.annotation.Generated;
import javax.inject.Provider;

@Generated("dagger.internal.codegen.ComponentProcessor")
public final class LeafComponentImpl_PackageProxy {
  public Provider<State> stateProvider;
}
```

A way to currently work around the issue is to make Injected.State public, but that's not ideal.

**Comment by pyricau** [comment]
Buuut wait, there's more!

I just hit that problem again when trying to have two sibling sub components declared in a parent component. If those two components live in the same package (and require a PackageProxy from the parent component), then we get the exception again. Sad.

**Comment by ronshapiro** [comment]
In the first case, we don't need the duplicate `PackageProxy`, correct? Each Component can create separate instances but use the same type. We can check to make sure we don't create duplicate proxies.

In the second, is this the case? If so, again we could make sure the package proxy is not duplicated, but I'm not fully sure I got the full case.

```java
package fr.baguette;

@Component
public interface RootComponent {
  LeafComponentOne first();
  LeafComponentTwo second();
  
  public static class PublicDep {
    @Inject PublicDep() {} // package-private constructor
  }
}
```

```java
package fr.croissant

@Subcomponent
public interface LeafComponentOne {
  RootComponent.PublicDep providePublicDepWithDefaultConstructor();
}
```

```java
package fr.croissant

@Subcomponent
public interface LeafComponentTwo {
  RootComponent.PublicDep providePublicDepWithDefaultConstructor();
}
```

**Comment by ronshapiro** [comment]
Just tried this with the latest snapshot and it worked.

**Comment by pyricau** [comment]
Thanks!
