### ISSUE TITLE
HiltWorkerFactory.createWorker is missing my HitlWorker class resulting in NoSuchMethodException

### ISSUE THREAD

**Issue by niqo01** [google/dagger#2356]
I am using `1.0.0-alpha03` with 
```
androidx.hilt:hilt-work
com.google.dagger:hilt-android-compiler
com.google.dagger:hilt-compiler
```

I am experiencing the following issue:
```
 java.lang.NoSuchMethodException: com.nicolasmilliard.socialcatsaws.imageupload.ImageUploadWorker.<init> [class android.content.Context, class androidx.work.WorkerParameters]
        at java.lang.Class.getConstructor0(Class.java:2332)
        at java.lang.Class.getDeclaredConstructor(Class.java:2170)
        at androidx.work.WorkerFactory.createWorkerWithDefaultFallback(WorkerFactory.java:95)
        at androidx.work.impl.WorkerWrapper.runWorker(WorkerWrapper.java:244)
        at androidx.work.impl.WorkerWrapper.run(WorkerWrapper.java:136)
        at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91)
```

While debugging I was able to identify than my app does use `HiltWorkerFactory` but it's `createWorker` method is not able to retrieve my `@HiltWorker` worker annotated class. It then delegate the creation to `androidx.work.WorkerFactory.createWorkerWithDefaultFallback()` which in turn fails to create my `HiltWorker`. 
I can confirm that my build folder contains a `ImageUploadWorker_Factory` generated class.

The test project I work on is open source.

The Worker code is available [here](https://github.com/Couchsurfing/social-cats-playground/blob/master/socialcats-aws/image-upload/android/src/main/java/ImageUploadWorker.kt)

The Android Application code is available [here](https://github.com/Couchsurfing/social-cats-playground/blob/master/socialcats-aws/frontend/android/src/main/java/com/nicolasmilliard/socialcatsaws/App.kt)

Let me know if you need anything else.

**Comment by dagerler001** [comment]
I also have encountered same problem, did  all step by step like documentations.

I spent ~1.5 hours to fix current problem and found similar problem https://issuetracker.google.com/issues/158843197#comment4
 solution what was proposed there helped me

Pls check you what you added to `build.gradle (app) `

` kapt 'androidx.hilt:hilt-compiler:1.0.0-alpha01' `

**Comment by niqo01** [comment]
I have hilt-compiler already set in both the [app](https://github.com/Couchsurfing/social-cats-playground/blob/master/socialcats-aws/frontend/android/build.gradle.kts#L40) and [library module](https://github.com/Couchsurfing/social-cats-playground/blob/master/socialcats-aws/image-upload/android/build.gradle.kts#L38)

**Comment by bembem1011** [comment]
I met same issue, when I integrate worker in dynamic module ( + hilt). When I used only hilt + worker, the app ran smoothly.

**Comment by danysantiago** [comment]
@niqo01, you want to add `kapt("androidx.hilt:hilt-compiler:_")` in the [library module (`image-upload:android`)](https://github.com/Couchsurfing/social-cats-playground/blob/master/socialcats-aws/image-upload/android/build.gradle.kts) where the Worker source is, notice the difference in the group id, there are two compiler, the AndroidX one for the Jetpack extensions, including for Workers `androidx.hilt:hilt-compiler` and Hilt's `com.google.dagger:hilt-compiler`.

Specifically in [build.gradle.kts#L38](https://github.com/Couchsurfing/social-cats-playground/blob/29e4de4e9d4d99113362341103ffe8aecbb5f446/socialcats-aws/image-upload/android/build.gradle.kts#L38) update the line to `kapt("androidx.hilt:hilt-compiler:_")`

**Comment by niqo01** [comment]
thank you @danysantiago, that was it. 
 I did not realized they were two different `hilt-compiler`..
