### ISSUE TITLE
Dagger2 or Hilt, AssistedInject not working in multimodule application

### ISSUE THREAD

**Issue by TheReprator** [google/dagger#2364]
Hi Mates,

Actually i am trying to use assistedinject in a multimodule application but getting the following error as follows,

C:\WillyWeather\ui\cityList\build\generated\source\kapt\debug\reprator\willyWeather\cityList\ui\CityListAdapterFactory_Impl.java:24: error: incompatible types: Factory<CityListAdapterFactory_Impl> cannot be converted to Provider<CityListAdapterFactory>
    return InstanceFactory.create(new CityListAdapterFactory_Impl(delegateFactory));

Repo details:  https://github.com/TheReprator/WillyWeather
Branch: hilt

It's somewhat related to , https://github.com/google/dagger/issues/2309

Regards,
Vikram Singh

**Comment by TheReprator** [comment]
Just worked after adding, 

compileOptions {
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
    }

in module build.gradle

**Comment by bcorso** [comment]
This should also be fixed at head (dupe of #2309), but you'll have to wait for the next Dagger release.
