### ISSUE TITLE
Add current stable and alpha version numbers in the Hilt official documentation website

### ISSUE THREAD

**Issue by wajahatkarim3** [google/dagger#2366]
I have observed that in the https://dagger.dev/hilt/ website, the current stable or alpha version of the library is not mentioned anywhere. It leads developers to externally search the version either from d.android.com or Github releases or maven central. 

A good example would be like as it is in the d.android.com website:

```
buildscript {
    ...
    ext.hilt_version = '2.31.2-alpha'
    dependencies {
        ...
        classpath "com.google.dagger:hilt-android-gradle-plugin:$hilt_version"
    }
}
```

**Comment by bcorso** [comment]
Thanks for the suggestion!

We've added the current dagger release to the home page(https://dagger.dev/) and we've updated the Gradle setup instructions to include the current release (https://dagger.dev/hilt/gradle-setup).
