### ISSUE TITLE
Destroying custom scoped module

### ISSUE THREAD

**Issue by beworker** [google/dagger#238]
I have following use-case. I create a custom scope (@PerActivity) which creates a single module per Android Activity. Some instances in this module are initialized with Activity instance and has to be bound to Activity lifecycle. Particularly they have to receive onDestroy() call, when Activity gets destroyed.

Would it be possible to call some kind of close() or destroy() methods on the module that it forwards this call to all created instances interested in such a callback?

If not, is there Dagger2 API allowing me to write an extension doing this? Thanks!

**Comment by adi1133** [comment]
The modules are referenced inside a component, they are free to be GC-ed when the component is not referenced anymore.

**Comment by ronshapiro** [comment]
I think this is probably custom functionality that you'll want to have yourself. You can use [`ActivityLifecycleCallbacks`](http://developer.android.com/reference/android/app/Application.ActivityLifecycleCallbacks.html) which might be able to assist. Something like this might be helpful:

```java
@Module
class ActivityModule {
  private final Activity activity;
  ActivityModule(Activity activity) { this.activity = activity; }

  @Provides FooDep provideFooDep() { return new FooDep(); }

  @Provides @PerActivity BarDep provideBarDep(FooDep foodDep) {
    return new BarDep(fooDep);
  }

  @Provides ActivityLifecycleCallbacks provideActivityLifecycleCallback(
        BarDep barDep,
        SomeOtherPerActivityDep perActivityDep) {
    return new ActivityLifecycleCallbacks() {
      @Override 
    };
}
```

**Comment by netdpb** [comment]
Closing, as this is a question that I don't think we can do anything to solve except to continue this conversation here or elsewhere.

**Comment by tir38** [comment]
Did anything ever come of this? I'm having the same questions now. I need to clean up some provided objects, not just have them be GC'd. I would really love a way for dagger to help me "release" objects. Dagger has changed a lot in the four years since this question was asked. Maybe something like this is now easier to implement. I just can't imagine more people don't have this issue.
