### ISSUE TITLE
cannot generate

### ISSUE THREAD

**Issue by an965666225** [google/dagger#2387]
I used dagger 2.19 in the project. Old files are compiled to generate files normally. The new file cannot generate dagger...component file.

**Comment by bcorso** [comment]
Hi @an965666225,

Sorry, for a more specific answer I would need to know more details about your project., but typically when Dagger sources are not generated it means that you are missing the Dagger compiler, e.g. [`com.google.dagger:dagger-compiler:2.32`](https://mvnrepository.com/artifact/com.google.dagger/dagger-compiler/2.32).

If that doesn't work for you, I would need to know more about your setup, e.g. 
What build system are you using, e.g Gradle/Maven/Bazel? 
What is the configuration for the sources that do not trigger code generation (e.g. build.gradle file if you're using Gradle).

**Comment by bcorso** [comment]
Closing this for now, but feel free to reopen or post a new issue if you have more specific details about your issue.
