### ISSUE TITLE
Migrating a dagger.android app to hilt with Instrumentation Tests

### ISSUE THREAD

**Issue by westd** [google/dagger#2389]
Hi folks

I'm trying to migrate an application that uses dagger.android @ContributesAndroidInjector on activities to hilt.

I'm following the steps in the migration guide https://dagger.dev/hilt/migration-guide.html

I have set up my application class like suggested 

```
@HiltAndroidApp
class MyApplication : HasAndroidInjector {
  @Inject lateinit var dispatchingAndroidInjector: DispatchingAndroidInjector<Object>

  override fun androidInjector() = dispatchingAndroidInjector
}
```

All works well when running the application after  I migrate my first activity to hilt and the other activities keep working.

The problem comes when trying to keep the instrumentation tests running, my tests have their own dagger component used for injection

I tried using a @CustomTestApplication application class that injects the DispatchingAndroidInjector as per the example above but I get this error:

"@CustomTestApplication does not support application classes (or super classes) with @Inject fields."

So I've been unable to keep tests running with a mixture of @ContributesAndroidInjector activities and @ AndroidEntryPoint activities

Are there any suggested solutions?

Many thanks!

**Comment by bcorso** [comment]
Rather than injecting the fields, you can try to use an entry point to get them out lazily, e.g. https://github.com/google/dagger/issues/2033#issuecomment-671578781.

For example, in your custom application class you can have something like:

```java
@EntryPoint
@InstallIn(SingletonComponent.class)
interface DispatchingAndroidInjectorEntryPoint {
  DispatchingAndroidInjector<Object> dispatchingAndroidInjector();
}

@Override
public AndroidInjector<Object> androidInjector() {
  return EntryPoints.get(this, DispatchingAndroidInjectorEntryPoint.class).dispatchingAndroidInjector();
}
```

**Comment by westd** [comment]
it works @bcorso thank you!  It might be nice to add that snippet to the migration guide also
