### ISSUE TITLE
Include the component name in "cannot be provided" error messages

### ISSUE THREAD

**Issue by vaughandroid** [google/dagger#239]
If an `@Inject` constructor or an `@Provides` method can't be found for a particular class, we get an error message like this:

````
Error:com.squareup.otto.Bus cannot be provided without an @Inject constructor or from an @Provides-annotated method.
      com.laterooms.core.search.PromotionManager.<init>(android.content.Context appContext, com.squareup.otto.Bus eventBus)
          [parameter: com.squareup.otto.Bus eventBus]
````

It would be helpful if the error message mentioned which component encountered the error - e.g. when it's a subcomponent, or a component which has been extended for testing (& is missing module dependencies).

Normally it's fairly clear from which component(s) failed to compile, but I figure clearer is better, and this ought to be a fairly trivial fix.

**Comment by kotucz** [comment]
I think I have the same problem here: #221
We have many components and it is hard to find, which one is misconfigured.

**Comment by netdpb** [comment]
Yes, closing this as a dupe of #221.
