### ISSUE TITLE
RestrictToModule should take into account Kotlin companion object 

### ISSUE THREAD

**Issue by paulferaud** [google/dagger#2393]
I have a (kotlin) module with both `@Inject` and `@Binds`. The `@Inject` should be static funtions, and the `@Binds` should be members. To do this in Kotlin, you can either declare 2 classes, or use a companion object, like so:

```
abstract class MyModule {
  @Binds
  @SomeAnnotation
  fun abstract binds(someImplementation: SomeImplementation): SomeInterface

  companion object {
    @Provides
    @JvmStatic
    @SomeOtherAnnotation
    fun provides(args: Args): SomeOtherInterface = whatever;
  }
}
```

The issue here is that if `SomeOtherAnnotation` is protected by a `RestrictToModule`, then dagger will not recognize `MyModule` as the module being installed, but `MyModule.Companion`.

This is an issue because it leaks implementation details about how the binding is being done (`@Binds` vs `@Provides`, `object MyModule { ... }` vs `abstract class MyModule { companion object { ... }}`).

For a Google internal example, see cl/358420462.

We had an existing module that implemented as `object MyModule { @Provides }`. Adding a new `@Binds` binding inside that module required changing all the referencing annotations with `@RestrictToModule`

**Comment by danysantiago** [comment]
Hey - It looks like `@RestrictToModule` needs to be updated to consider that the `companion object` of a `@Module` annotated class is part of the module itself and should allow it, even if in bytecode / KAPT stubs the enclosing class is different, that is essentially what Dagger does, it treats binding definitions in the companion object as part of the module itself. Also, the usage of `@JvmStatic` is not needed anymore.

If you have more question, please umm... contact us internally. =]
