### ISSUE TITLE
Component initialization happening in wrong order, causing crash

### ISSUE THREAD

**Issue by spierce7** [google/dagger#241]
In one of the `*_MembersInjector` class I'm seeing a NPE crash in the `injectMembers()` method, on the line: `supertypeInjector.injectMembers(instance);`.

After reviewing the generated code, I've been able to determine that supertypeInjector is null due to a bug in the initialization logic. The initialization logic has 6 steps for this component:

```Java
    private ActivityComponentImpl(ActivityModule activityModule) {  
      if (activityModule == null) {
        throw new NullPointerException();
      }
      this.activityModule = activityModule;
      initialize();
      initialize1();
      initialize2();
      initialize3();
      initialize4();
      initialize5();
    }
```

in the `initialize()` method, the `baseActivityMembersInjector` is being passed in to the creation of the `MainActivity_MembersInjector.create()` as the `supertypeInjector`. At the point that it's being passed in though, it's null. The `baseActivityMembersInjector` is not actually being initialized until `initialize4()`.

I've tinkered with it a bit, and I've been able to identify where the compiler is getting confused. I'll describe the system to you:

I have 2 components:
```Java
@Singleton
@Component
public interface ApplicationComponent {
    ActivityComponent plus(ActivityModule activityModule);
    void inject(Activity2 obj);
}
```

```Java
@Singleton
@Subcomponent
public interface ActivityComponent {
    void inject(MainActivity obj);
}
```

I have 2 Activities: `MainActivity`, and `Activity2`. Both of these activities extend `BaseActivity`. `BaseActivity`'s MembersInjector creation time is the issue. When I move `void inject(Activity2 obj);` from the `ApplicationComponent` to the `ActivityComponent`, everything works out fine and the crash doesn't happen.

This is not a complete representation of the dagger setup in my project. My dependency graph is far larger, but this should isolate the issue so that it's reproducible.

**Comment by tbroyer** [comment]
Looks like a dupe of #214

**Comment by spierce7** [comment]
Looks like you are right. Thanks!
