### ISSUE TITLE
Injecting a class with a package protected constructor that hits a different classloader will cause an execption

### ISSUE THREAD

**Issue by cogman** [google/dagger#242]
So I've hit this

https://stackoverflow.com/questions/14070215/java-lang-illegalaccesserror-tried-to-access-field-concreteentity-instance-from

In my case, the sub library is built with java 7 and the parent with java 8.  On top of that, they exist in non-related projects.  I wasn't able to reproduce the problem in a small test project, however I get the following runtime exception

java.lang.IllegalAccessError: tried to access method com.ca.transaction.dao.TransactionTypeDao.<init>(Lorg/springframework/jdbc/core/JdbcTemplate;Lcom/google/common/util/concurrent/ListeningExecutorService;)V from class com.ca.transaction.dao.TransactionTypeDao_Factory

To the best of my knowledge, this is failing because the sub library ends up getting loaded with a different class loader than the app does.

The workaround is to simply change the constructor from package protection to public, however it would be nice if something/anything could warn or stop me from walking into this blind.

**Comment by netdpb** [comment]
Since Dagger does all its analysis at compile time, I don't think it can possibly know which classloaders will be used to load anything, so it can't warn you about this.

Please reopen with more information if I'm wrong.
