### ISSUE TITLE
[BUG] Not enough information to infer type variable T

### ISSUE THREAD

**Issue by limitless-brain** [google/dagger#2451]
I was migrating a project from Dagger to Hilt, and I faced the problem after adding the dependencies.
Hilt version 2.30.1-alpha and lowers works fine, but the releases after it break the project at build time.
I didn't modify or add any line of code. I just followed Hilt setup for Gradle. 

Android Studio V4.1.2 MacBook pro intel-based
Dagger V2.23.1

Generics used in this class
```
data class Result<out T>(val status: Status, val data: T?, val message: String?) {

    var exception: Exception? = null

    constructor(status: Status, data: T?, message: String? = null, exception: Exception?) : this(
        status,
        data,
        message ?: ""
    ) {
        this.exception = exception
    }

    companion object {
        fun <T> success(data: T?): Result<T> {
            return Result(Status.SUCCESS, data, null)
        }
        ...
    }
}
```

The error occurred wherever I used the above class.
```
e: /path_to_file/File.kt: (row,col): Not enough information to infer type variable T
```

**Comment by bcorso** [comment]
Hi @limitless-brain, 

Hmm, it doesn't look like Dagger should care about this class since it's not even annotated.

Is there any other errors in the log?

Also, what is "/path_to_file/File.kt"? Is that the file containing the `Result` class?

**Comment by limitless-brain** [comment]
Hi @bcorso,
The class Result is a custom class created for emitting the api request result. As I mentioned no modifications were made to the project, and version 2.30.1 (or lower) didn’t case the problem.
There is no other errors in the log. It's only Kotlin compiler not able to infer the type variable T.

**Comment by bcorso** [comment]
Sorry, I'm unable to reproduce this locally. If you can create a sample project with the issue I can take a closer look.

**Comment by limitless-brain** [comment]
After migrating the whole project, the latest version works correctly.
Apologize, you can market as closed.

**Comment by bcorso** [comment]
Thanks for following up!
