### ISSUE TITLE
[Hilt migration] Given component holder class does not implement interface dagger.hilt.internal.GeneratedComponent 

### ISSUE THREAD

**Issue by sanginovs** [google/dagger#2459]
Hi Dagger developers, 

I am in the process of migrating our codebase to Hilt. I migrated all of the dagger components to Hilt. The components interfaces have few inject methods which i want to keep for now and remove later. Here's an example:

```
@InstallIn(ApplicationComponent::class)
@EntryPoint
interface SampleComponent {
      fun inject(trackingClass: TrackingClass)
}
```

Now, here's my tracking class:
```
class TrackingClass {
    @Inject lateinit var repo: SampleRepository
    . . .
    init {
         EntryPoints.get(this, SampleComponent::class.java).inject(this)
    }
    }
```
As you can see, I am using Hilt `EntryPoints` to access **SampleComponent** from Hilt and call its inject method so Dagger can inject dependencies to TrackingClass. However, I am getting this error when calling `EntryPoints.get(this, SampleComponent::class.java).inject(this)`:

`Given component holder class TrackingClass does not implement interface dagger.hilt.internal.GeneratedComponent or interface dagger.hilt.internal.GeneratedComponentManager`

Thanks for your help

**Comment by bcorso** [comment]
Hi @sanginovs,

The `EntryPoints` utility class expects a component or component holder instance as the first parameter. From a user perspective it's kind of opaque what constitutes a component or component holder, but it's essentially an Application, Activity, Fragment, etc., which hold the components for the `SingletonComponent`, `ActivityComponent`, `FragmentComponent`, respectively.

Thus, you're `TrackingClass` will need access to one of those instances to use `EntryPoints`.

You can also use the API friendly [`EntryPointAccessors`](https://dagger.dev/api/latest/dagger/hilt/android/EntryPointAccessors) which makes the types this more explicit.

**Comment by sanginovs** [comment]
got it. thank you
