### ISSUE TITLE
Implementing BaseViewModel with Hilt version 2.33-beta

### ISSUE THREAD

**Issue by magamal** [google/dagger#2462]
I had an issue while extending from a BaseViewModel that I had made

`abstract class BaseViewModel : ViewModel() {}
`
and The ViewModel that I am using is 

`
@HiltViewModel
class EditRetentionViewModel @Inject constructor() : BaseViewModel() {}
`

But I have this error while building

**HiltViewModel is only supported on types that subclass androidx.lifecycle.ViewModel**

I was using version **2.33-beta**
But when I decreased to version **2.31.2-alpha** the error disappeared

**Comment by danysantiago** [comment]
Hey - That check has not changed between those two versions of Hilt. Maybe there is something else going on? I tried to repro the issue but couldn't, Hilt accepted an intermediate base class fine. Maybe there is something else going on with your setup? Do you have the right import, i.e. not using pre-androidx package?

**Comment by magamal** [comment]
Hello @danysantiago You are right :D :D
