### ISSUE TITLE
Cannot create an instance of ViewModel

### ISSUE THREAD

**Issue by periva101** [google/dagger#2464]
Dagger must be compile-time safe,
 but If we use ViewModel without @AndroidEntryPoint it will compile you give Runtime time error 
Caused by: java. lang.RuntimeException: Cannot create an instance of class...

Also, the Exception message is not clear at all

**Comment by periva101** [comment]
ok fine, but that should be in the document " but sadly we can't make every situation a compiler error"

**Comment by Chang-Eric** [comment]
I don't think it is necessary to add to our documentation. Our documentation says we're a fully static, compile-time dependency injection framework, not that we guarantee all possible errors are going to be compile time errors. The compile-time aspect is that we are going to find binding graph errors (e.g. missing bindings, duplicate bindings, binding cycles, etc) at compile time for you. Accidentally misapplying our APIs (or in this case, forgetting to use our API) are a different category of issue.
