### ISSUE TITLE
If a Fragment in a project is annotated with @AndroidEnRYPoint and reused by an external SDK Activity that does not support HILT, it will run wrong，any suggestion？

### ISSUE THREAD

**Issue by byrxs5216** [google/dagger#2469]

**Comment by andrewhunter0** [comment]
So, you should use EntryPoint in you fragment, to replace AndroidEntryPoint, see [https://dagger.dev/hilt/entry-points](https://dagger.dev/hilt/entry-points)

**Comment by byrxs5216** [comment]
I need to create an entryPoint interface that provides all services Fragment needed and which is installed in the FragmentComponent, right?

**Comment by andrewhunter0** [comment]
That's nearly so.
```
@EntryPoint
@InstallIn(SingletonComponent::class)
interface YouFragmentEntryPoint {
    fun getInterface1(): IYouInterface1
    fun getInterface2(): IYouInterface2
    ......
}
```

Then you can use
 `EntryPointAccessors.fromApplication(context, YouFragmentEntryPoint::class.java).getInterface1()`
 to use in your fragment.

Of course, your should use `@Provides` or `@Binds` to tell Hilt how to create instance of 'IYouInterface1' and 'IYouInterface2'

**Comment by Chang-Eric** [comment]
You can also check out `@OptionalInject` https://dagger.dev/hilt/optional-inject which should cover this use case.
