### ISSUE TITLE
DFM - error: [Dagger/MissingBinding] @dagger.hilt.android.qualifiers.ApplicationContext android.content.Context cannot be provided without an @Provides-annotated method.

### ISSUE THREAD

**Issue by mochadwi** [google/dagger#2477]
Is it possible to use `@ApplicationContext` in DFM? or should we provide application context manually?

If yes, is there any reference you guys can point me out?

**Comment by Chang-Eric** [comment]
I'd need more details to answer the issue about `@ApplicationContext`, but you would need to do something like what is described in this section https://developer.android.com/training/dependency-injection/hilt-multi-module#dfm to handle DFM in Hilt. At that point, I believe most of the missing binding issues will be issues of propagating those bindings through the component dependencies.
