### ISSUE TITLE
[Hilt] Fragment transition is broken

### ISSUE THREAD

**Issue by anastr** [google/dagger#2481]
After updating to Hilt `2.33-beta` our transition animation is acting weird and not working correctly. I think it's because of moving to [fragment:1.3.0](https://github.com/google/dagger/commit/623d3a61e0554954a0a18351a3f425320aea2122#diff-5493ff8e9397811510e780de47c57abb70137f1afe85d1519130dc3679d60ce5R108).
By looking for a solution, I found this issue should have been fixed according to [this bug](https://issuetracker.google.com/issues/180825150). New release of fragment [1.3.1](https://developer.android.com/jetpack/androidx/releases/fragment#version_131_3) has critical lifecycle-aware bugs fixed and I think Hilt should be moved to that version.

**Comment by Chang-Eric** [comment]
Thanks for the report, we should update that dependency. In the meantime, I think you should be able to bump your own dependency on fragment to fix this.
