### ISSUE TITLE
Hilt: Binding to different implementations of the interface

### ISSUE THREAD

**Issue by sanginovs** [google/dagger#2490]
Hi there,

How can i provide different implementations of the interface using **@Binds** in Hilt. This is possible to do with Dagger however when i migrated it to Hilt, it's throwing **Duplicate Binding: Fragment bound multiple times** error. 

Dagger example:
```
abstract class SignInModule {
    @Binds
    abstract fun fragment(fragment: SignInFragment): androidx.fragment.app.Fragment
}

abstract class SignUpModule {
    @Binds
    abstract fun fragment(fragment: SignUpFragment): androidx.fragment.app.Fragment
}
```

**Comment by bcorso** [comment]
Hilt [has a binding for `Fragment`](https://github.com/google/dagger/blob/master/java/dagger/hilt/android/internal/builders/FragmentComponentBuilder.java#L27) which will be bound with the instance of the current fragment, so my guess is that you shouldn't need either of those `@Binds` methods anymore.
