### ISSUE TITLE
[Hilt] @ActivityScope Components injected into ViewModel

### ISSUE THREAD

**Issue by igorkurek** [google/dagger#2503]
# Context
We used Hilt to inject components into ViewModels, with `@ViewModelInject constructor()` annotation. Injected components were using different scopes, but some of them required `Context` or `Activity` to work, so we made them scoped to `@ActivityScope`. After updating to latest version, I've noticed that `@ViewModelInject` annotation is deprecated, and suggested solution is moving to `@HiltViewModel` annotation with `@Inject constructor()`. After doing this, Hilt fails to inject `@ActivityScope` modules into ViewModels.

# Issue
Injection of `@ActivtyScoped` modules into ViewModel annotated with `@HiltViewModel` fails:
```
error: [Dagger/IncompatiblyScopedBindings] <redacted>.App_HiltComponents.ViewModelC scoped with 
@dagger.hilt.android.scopes.ViewModelScoped may not reference bindings with different scopes:
  public abstract static class SingletonC implements App_GeneratedInjector,
  @dagger.hilt.android.scopes.ActivityScoped class <redacted>
```
As far as I understand, this is caused by `@HiltViewModel` scope not allowing to inject `@ActivityScope` components.

# Questions
1. Is this behavior intended? Injecting `@ActivityScope` modules into ViewModels was allowed in previous versions of library
2. Is there any suggested way of migration for cases like this? Any guideline on how to rewrite components that rely on Android `Context` or `Activity` so they can be injected into ViewModel?

**Comment by bcorso** [comment]
Hi @igorkurek,

1. Yes, this is the intended behavior. A ViewModel will outlive the Activity so storing `Activity` or its `Context` can
    result in memory leaks. As stated in the [official documentation](https://developer.android.com/topic/libraries/architecture/viewmodel):
     > "Caution: A ViewModel must never reference a view, Lifecycle, or any class that may hold a reference to the activity context."
    
    For example, after a configuration change, like rotation, Android will create a new instance of the `Activity` but your ViewModel will be holding onto the old `Activity` instance.
2. There's a lot of good resources in the [documentation](https://developer.android.com/topic/libraries/architecture/viewmodel), and any guidance will likely depend on exactly what you're currently storing the activity in the ViewModel for. For example, if you're just using it to grab state on the current activity to perform an action, you could pass an `Activity` or whatever you need as a method parameter. Just be sure not to store the state of those parameters permanently or it will result in the same issue.
