### ISSUE TITLE
Attribute injection for private and final field

### ISSUE THREAD

**Issue by kyatul** [google/dagger#2504]
Currently there is no provision for injecting attributes in a class having an attribute as final and private.

Can we use builders if available on class for injecting those variables ?
MapStruct is a library which is currently using the same method for creating an immutable object. [Guide reference for the feature](https://mapstruct.org/documentation/stable/reference/html/#mapping-with-builders)

Can we also have a feature same as this ? Please share if there is some limitation in taking this approach, or its feasible, or maybe I am missing something somewhere.

**Comment by bcorso** [comment]
Sorry, I don't think I understand how the builder example is related. Can you give some example code of what you want to do and how builders are related?

Also, sorry if this is obvious, but just to throw it out there, have you considered using constructor injection instead?

**Comment by kyatul** [comment]
Let me take an example to explain. I will be able to communicate my thoughts better.

Say we have a class `InjectAttributesInThis` with below structure.
``` java
class InjectAttributesInThis {
    private final AttributeA attributeA;

    private final AttributeB attributeB;

    private final AttributeC attributeC;
}
```

Below are the approaches which I am aware of injecting the dependencies and the last approach is what I am pitching if its possible.

### Approach 1 : Injecting on Attributes
We can inject using attributes, but it does not allows to mark field as private and final
``` java
class InjectAttributesInThis {
    @Inject
    AttributeA attributeA;
    
    @Inject
    AttributeB attributeB;
    
    @Inject
    AttributeC attributeC;
    
    @Inject
    public InjectAttributesInThis() {}
}
```
### Approach 2 : Injecting using a constructor
In this way we can have our attribute private and final. The same same thing which you mentioned.
```java
class InjectAttributesInThis {
    private final AttributeA attributeA;

    private final AttributeB attributeB;

    private final AttributeC attributeC;
    
    @Inject
    public InjectAttributesInThis(AttributeA attributeA, AttributeB attributeB, AttributeC attributeC) {
        this.attributeA = attributeA;
        this.attributeB = attributeB;
        this.attributeC = attributeC;
    }
}
```

### Approach 3 : Using a builder (Not available, wanted to know if a similar feature can be made in Dagger)
``` java
@Builder
class InjectAttributesInThis {
    private final AttributeA attributeA;

    private final AttributeB attributeB;

    private final AttributeC attributeC;
}
```
I have used [Lombok Builder](https://projectlombok.org/features/Builder) in above example to generate a builder, but it can be added manually.

And Dagger can generate the factory file to use builder to create object, something like below.
```java
public final class SomeModule_GetInjectAttributesInThisFactory implements Factory<InjectAttributesInThis> {
    private final Provider<AttributeA> attributeAProvider;

    private final Provider<AttributeB> attributeBProvider;

    private final Provider<AttributeC> attributeCProvider;
    
    @Override
    public InjectAttributesInThis get() {
        return InjectAttributesInThis.builder()
            .attributeA(attributeAProvider.get())
            .attributeA(attributeBProvider.get())
            .attributeA(attributeCProvider.get())
            .build();
  }
}
```

If this becomes possible then we don't have to write boilerplate code in constructor, and injecting only on attribute will suffice while keeping it private and final.
``` java
class InjectAttributesInThis {
    @Inject
    private final AttributeA attributeA;
    
    @Inject
    private final AttributeB attributeB;
    
    @Inject
    private final AttributeC attributeC;
    
    @Inject
    public InjectAttributesInThis() {}
}
```

**Comment by Chang-Eric** [comment]
I think it would be tough to do unless we want to support a particular builder like the one you linked. I'm not sure we would want to do that though since it isn't clear that there is a standard builder pattern we can rely on and any sort of custom integrations may add complexity, both in implementation and understandability of the API.

Also, the boilerplate of constructor injection is pretty standard for Java constructors in general, so this feels like less of a Dagger-specific problem. So, probably not quite what you want to hear, but I think approach 2 is the way to go for now. (Unrelated side note: in approach 2 you don't have to make the `@Inject` constructor public).

**Comment by kyatul** [comment]
Request for this feature was more of providing a better user-experience for API users of dagger, where a user can inject private fields just by an annotation, with minimum efforts, rather than writing complete constructor. Same way as spring DI  provides today.

I didn't meant it to came out as pointing issues in dagger API, I apologise if it came out so.

The builder example I used, was just for reference purpose, I am not pitching for using it.

One way of implementing it maybe we can have a custom dagger generated builder(as we do for factory) and use that, instead of any user provided builders. But yes there can be other options of implementing it.

I wanted to know about feasibility of implementing it, and any plans of dagger team to provide such feature in future.

**Comment by Chang-Eric** [comment]
Thanks for the clarification. To answer the general question of plans/priority, at a high-level, I don't think this is high on our list of things to address. Partially this is due to Kotlin solving some of this boilerplate and partially this is due to not having any great ideas for how to implement this.

The problem with a generated builder or accessing private fields in general is that you can't generate code into an existing class without accessing internal compiler APIs. I think this is what Lombok does which is why they can do it. This isn't something I want to get into for Dagger, so I don't see a good way for Dagger to do this right now even if we really wanted to.

**Comment by kyatul** [comment]
The builder can be generated separately instead of in the same file, as currently done for factory.
But yes, an auto generated constructor will be required anyway in the end for the source file accepting builder as parameter, which will require access to compiler APIs.

I understand your thought process now, and teams current priorities. Thanks for being patient and hearing me out.
Resolving this issue.

**Comment by Chang-Eric** [comment]
Of course, and thanks for the suggestion too, even if it didn't work out. We're always open to new ideas =) Closing this out now though since it seems infeasible as things are today.
