### ISSUE TITLE
Lint error for @Provides in a Kotlin companion object 

### ISSUE THREAD

**Issue by simtse** [google/dagger#2506]
Using Dagger 2.33 and in Android Studio 4.1.2, we started seeing lint errors on the `@Provides` line in Modules defined as Kotlin interfaces. This hasn't been a problem for several versions.

![image](https://user-images.githubusercontent.com/4455111/112396998-6fa9b580-8cbe-11eb-8dcf-9e5bcb1a2abd.png)

```kotlin
@Module
interface TestModule {
  
  @Binds
  fun HelperImpl.bindHelper(): Helper
  
  companion object {

    @Provides
    fun provideConfig(): String {
      return "Conig"
    }
  }

}
```

**Comment by danysantiago** [comment]
Hi - Do you know from where this Lint rule is coming from? Dagger does not have a Lint with that message, you can find Dagger's Lint errors [here](https://github.com/google/dagger/blob/master/java/dagger/lint/DaggerKotlinIssueDetector.kt#L82). However, Dagger does have a processor message just like that [here](https://github.com/google/dagger/blob/master/java/dagger/internal/codegen/validation/BindingMethodValidator.java#L176), but that is an annotation processor errors, I don't think they show up in the IDE like that, but do show as compilation errors.

**Comment by simtse** [comment]
Thanks @danysantiago I don't know where this message is coming from after looking at your two links. Normally a lint would have some feedback mechanism and ignoring but I don't see it. Let me see if I can dig a little deeper to see why it comes up for me.

**Comment by Chang-Eric** [comment]
Closing this as we don't think this is coming from Dagger.
