### ISSUE TITLE
[Hilt] Field injection in ViewModel

### ISSUE THREAD

**Issue by KristapsKrumins** [google/dagger#2507]
Hi, I have a base ViewModel class:

```
abstract class BaseViewModel : ViewModel() {
    @Inject
    @ApplicationContext
    lateinit var context: Context
}
```
Code bellow at runtime will produce an error (_lateinit property context has not been initialized_)
```
@HiltViewModel
class MyViewModel @Inject constructor() : BaseViewModel() {
   val foo = context.bar()
}
```

How can I inject common objects in abstract class ViewModel so that I don't need to inject them in every class constructor that extends from this class?
If this is not possible, would be nice to mention that in documentation.

**Comment by danysantiago** [comment]
Member injection is done **after** `init` (constructor) is done, but you are trying to initialize `foo` during construction where `context` has not been yet injected.

Try declaring a property getter:
```
val foo : Bar
  get() = context.bar()
```

Or using `lazy`:
```
val foo by lazy { context.bar() }
```

**Comment by KristapsKrumins** [comment]
Okay, will have to call custom init function in ViewModel form Fragment then. Thanks for Your time!

**Comment by Drjacky** [comment]
@danysantiago I use `by lazy` but still get the error.
The difference in my code is:
```kotlin
@HiltViewModel
open class BaseViewModel @Inject constructor() : ViewModel() {

    @Inject
    lateinit var repo: MyRepo
```
