### ISSUE TITLE
Carry annotations from assisted factory interfaces into generated implementation

### ISSUE THREAD

**Issue by stoyicker** [google/dagger#2509]
The end goal is that I want to be able to scope my factories. [Example here](https://github.com/square/InflationInject/issues/158). [I did an implementation on assistedinject](https://github.com/square/InflationInject/pull/159/files) before it got "added" to Dagger and that repository became host for a different tool, and I'll be happy to try to do it here instead. Would this be a feature welcome here?

**Comment by bcorso** [comment]
Hi @stoyicker,

What's your use case? In particular, do you have a situation where creating the assisted factory affects runtime performance or memory? If so, can you describe that use case a bit?

**Comment by stoyicker** [comment]
Nevermind, I'm realizing that I was making assumptions about how the functionality of assistedinject was added to Dagger that were not correct. For the record, the intent of this was to have the factories be handled as @Reusable, but if I don't misunderstand this is already achieved with the `InstanceFactory` wrapper.

**Comment by bcorso** [comment]
> if I don't misunderstand this is already achieved with the InstanceFactory wrapper.

Yes, if you're not using the `fastInit` option then  the assisted factory should get stored as a field in the generated component, similar to other providers, so you will get that caching for free.

If you are using `fastInit`, I don't think we have enabled that caching for assisted factories, so we'll currently create a new factory each time.

However, in either case I still wouldn't expect these factories to cause a significant runtime performance or memory issue, so if you have a use case where you think it does and you do need to use `fastInit`, then please let us know.
