### ISSUE TITLE
Dagger 2 fails to handle classes generated by other annotation processors

### ISSUE THREAD

**Issue by Alexander--** [google/dagger#252]
#### Problematic behavior 

Writing something like

    @Provides FooBar provideFoobar() {
    ...

can result in IllegalArgumentException if FooBar.java is generated by some other annotation processor (like `DaggerXXX` classes are). Reordering annotation processors is not sensible workaround and won't resolve circular dependencies between generated code.

#### Expected behavior

Dagger 2 must properly support multi-round APT compilation and check if the current round is the last before freaking out from unrecognizable type.

**Comment by tbroyer** [comment]
Apparently fixed in the upcoming 2.0.2: #249

**Comment by ronshapiro** [comment]
Can you reopen if you don't see this reflected in release 2.0.2?

**Comment by hansenji** [comment]
This is an issue again in version 2.3

**Comment by ronshapiro** [comment]
@hansenji can you provide more info? A stack trace, or a failing example?

**Comment by hansenji** [comment]
This project https://github.com/hansenji/Android-Template/tree/dagger23 is an example. I have library PocketBus that generates a file that is used in the AppModule class. 
I get a this warning
```
src/main/java/org/jdc/template/dagger/AppModule.java:17: error: cannot find symbol
import org.jdc.template.BusRegistry;
                       ^
  symbol:   class BusRegistry
  location: package org.jdc.template
```

Then the build fails with
`java.lang.NoSuchMethodError: com.google.common.collect.ImmutableSetMultimap$Builder.putAll(Ljava/lang/Iterable;)Lcom/google/common/collect/ImmutableSetMultimap$Builder;`

**Comment by tbroyer** [comment]
The `NoSuchMethodError` is #356.

**Comment by ronshapiro** [comment]
Right, that's a separate issue. For now, you can add `apt 'com.google.guava:guava:19.0'`. We should have a release soon once google-java-format releases a new version which fixes the issue @tbroyer mentioned.

**Comment by sungentim** [comment]
dagger 2.4 have the same problem,back to 2.2 is OK

**Comment by abhinandankothari** [comment]
@ronshapiro  suggested for Worked for me but @sungentim was more useful since guava was un-necessarily adding 15K methods to Dexcount

**Comment by yshrsmz** [comment]
I guess apt dependency does not contribute to dexcount
and dagger 2.5 works fine for me
