### ISSUE TITLE
Data binding errror: Error: symbol not found

### ISSUE THREAD

**Issue by andrewhunter0** [google/dagger#2528]
See my issue: https://github.com/google/dagger/issues/2460

#### I found that the real reason is because of using `apply plugin: 'kotlin-kapt'` in module `core`,  
not because of using `implementation "com.android.tools.build:gradle:4.0.1"` in `buildSrc` : https://issuetracker.google.com/issues/182682213

And if i changed `implementation` to `compileOnly "com.android.tools.build:gradle:4.0.1"`, a new problem will come: `can't find AppExtension'` when i write a plugin like this:
```
import com.android.build.gradle.AppExtension

class RegisterPlugin implements Plugin<Project> {

    @Override
    void apply(Project target) {
        def android = target.extensions.getByType(AppExtension)
        android.registerTransform(new RegisterTransform(target))
    }
}
```

See my demo: https://github.com/andrewhunter0/DataBindingError

I should remove ``apply plugin: 'kotlin-kapt'`` ? 
Before use Hilt, There was no such problem.

**Comment by danysantiago** [comment]
You should not remove `kapt`, even if that works, that is something you don't want in the long run.

The `AppExtension` cannot be found immediately because very likely your plugin is being applied first before the Android Gradle Plugin had a chance to configure and specifically add the extension you are looking for. The pattern to interface with the AGP extensions is to use lazy configurations, like this:

```
void apply(Project target) {
  target.plugins.withType(AndroidBasePlugin) {
    // Find BaseExtension (you probably want this so that the plugin is relevant for android.library too)
    // Note that this closure will only be invoked once the Android Plugin has been found and applied. 
    def android = target.extensions.getByType(BaseExtension)
    android.registerTransform(new RegisterTransform(target))
  }
}
```

**Comment by andrewhunter0** [comment]
> You should not remove `kapt`, even if that works, that is something you don't want in the long run.
> 
> The `AppExtension` cannot be found immediately because very likely your plugin is being applied first before the Android Gradle Plugin had a chance to configure and specifically add the extension you are looking for. The pattern to interface with the AGP extensions is to use lazy configurations, like this:
> 
> ```
> void apply(Project target) {
>   target.plugins.withType(AndroidBasePlugin) {
>     // Find BaseExtension (you probably want this so that the plugin is relevant for android.library too)
>     // Note that this closure will only be invoked once the Android Plugin has been found and applied. 
>     def android = target.extensions.getByType(BaseExtension)
>     android.registerTransform(new RegisterTransform(target))
>   }
> }
> ```

Thanks for your kindly response!  

See my demo and the latest commit: https://github.com/andrewhunter0/DataBindingError  

Using `implementation "com.android.tools.build:gradle:4.0.1"`  data binding error comes;  
Using `compileOnly "com.android.tools.build:gradle:4.0.1"`, new error comes: `Caused by: java.lang.NoClassDefFoundError: com/android/build/gradle/api/AndroidBasePlugin`

**Comment by danysantiago** [comment]
Something else seems odd in your setup. Also, have you try using a newer AGP version, specifically 'com.android.tools.build:gradle:4.1.3' or higher?

**Comment by andrewhunter0** [comment]
Yes, i have tried: https://issuetracker.google.com/issues/182682213#comment17

**Comment by danysantiago** [comment]
Ah, I know I keep closing these issue on you, but they are really not related to Hilt and more about your project's setup for developing a plugin. I'm sorry we are not to helpful here but the responders in https://issuetracker.google.com/182682213 are better suited to help you since they work with the Android Gradle Plugin.

**Comment by andrewhunter0** [comment]
Yes
