### ISSUE TITLE
Animation issue with Jetpack Navigation and Dagger.Hilt 2.34

### ISSUE THREAD

**Issue by lukas1** [google/dagger#2533]
Latest release of Dagger.Hilt 2.34 has introduced a bug that manifests itself during navigation.

I have created a simple project that reproduces the issue, here: https://github.com/lukas1/Hilt-Navigation-Issue/tree/master

If you change in the project the version of Dagger.Hilt to 2.33, the animation behaves as expected.

**Expected animation:**
![Correct Behaviour of Dagger.Hilt 2.33](https://raw.githubusercontent.com/lukas1/Hilt-Navigation-Issue/master/correct-2-33-behaviour.gif)

**Actual animation:**
![Incorrect Behaviour of Dagger.Hilt 2.34](https://raw.githubusercontent.com/lukas1/Hilt-Navigation-Issue/master/incorrect-2-34-behaviour.gif)

**Comment by danysantiago** [comment]
This is not related to Hilt but to its `androidx.fragment` dependency. Hilt has been trying to keep up with the bug fixes in Fragment's new state manager and is[ currently depending on version 1.3.2](https://github.com/google/dagger/commit/efcdbe129e20f493da19d07127f77f466b67609b) and its likely upgrading your fragment dependency which is likely the culprit of the issue. 

If you remove the Hilt dependency out of your sample project and depend on Fragment 1.3.2 you'll observe the same issue. I recommend you file a bug to the Navigation folks [here](https://issuetracker.google.com/issues/new?component=409828&template=1093757), they also work on Fragments.

As a workaround you can [exclude](https://docs.gradle.org/current/userguide/dependency_downgrade_and_exclude.html#sec:excluding-transitive-deps) `androidx.fragment` from Hilt's transitive deps via Gradle, with something like this:
```
implementation ("com.google.dagger:hilt-android:2.34-beta") {
    exclude group: 'androidx.fragment'
}
```

**Comment by lukas1** [comment]
Thank you, indeed your observation is correct. Therefore I'm closing this issue and will report it as advised to maintainers of navigation library.
