### ISSUE TITLE
HTTP 429 Too Many Requests

### ISSUE THREAD

**Issue by AllenVork** [google/dagger#254]
I suddenly can't access to the MarvelApi. It says "HTTP 429 Too Many Requests".How to solve it?

**Comment by JakeWharton** [comment]
You've exceeded the rate limit. Also you're issue is nowhere near the right place as this is a dependency injection library.

**Comment by AllenVork** [comment]
I just let the application be,and didn't operate anything.Next day when i used it, I couldn't retrieve anything and got the error.
Now the solution is to wait?

**Comment by cgruber** [comment]
This issue is not related to dagger 2.
