### ISSUE TITLE
AssistedInject with 2 method

### ISSUE THREAD

**Issue by alizarei95** [google/dagger#2542]
Hello
I have a class with 2 constructor parameter, first a context and second an optional string

```
class SharedPreferencesHelper @AssistedInject constructor(
    context: Context,
    @Assisted sharedPreferencesName: String? = null
) { ... }
```

Can anyone tell me how to use AssistedInject to reach this goals?
1. inject object without `sharedPreferencesName`
2. inject object with `sharedPreferencesName`

**Comment by JakeWharton** [comment]
```kotlin
class SharedPreferencesHelper @AssistedInject constructor(
  context: Context,
  @Assisted sharedPreferencesName: String?
) {
  // ...

  @AssistedFactory
  interface Factory {
    fun create() = create(null)
    fun create(name: String?): SharedPreferencesHelper
  }
}

**Comment by alizarei95** [comment]
> ```kotlin
> class SharedPreferencesHelper @AssistedInject constructor(
>   context: Context,
>   @Assisted sharedPreferencesName: String?
> ) {
>   // ...
> 
>   @AssistedFactory
>   interface Factory {
>     fun create() = create(null)
>     fun create(name: String?): SharedPreferencesHelper
>   }
> }
> ```

error: The @AssistedFactory-annotated type should contain a single abstract, non-default method but found multiple: [create(), create(java.lang.String)]

**Comment by bcorso** [comment]
@alizarei95 Try using an `abstract class` rather than an `interface` so that you can make the `create()` method non-abstract:

```kotlin
  @AssistedFactory
  abstract class Factory {
    fun create() = create(null)
    abstract fun create(name: String?): SharedPreferencesHelper
  }
```

**Comment by alizarei95** [comment]
> @alizarei95 Try using an `abstract class` rather than an `interface` so that you can make the `create()` method non-abstract:
> 
> ```kotlin
>   @AssistedFactory
>   abstract class Factory {
>     fun create() = create(null)
>     abstract fun create(name: String?): SharedPreferencesHelper
>   }
> ```

I got this error:

`error: [Dagger/MissingBinding] android.content.Context cannot be provided without an @Provides-annotated method.
`
I added provide method to module:

```
@Provides
    @Singleton
    fun provideSharedPreferencesHelper(@ApplicationContext context: Context): SharedPreferencesHelper =
        SharedPreferencesHelper(context)
```

bu now I get this error:

`error: [ir.mdade.arch_test.utils.SharedPreferencesHelper] Dagger does not support providing @AssistedInject types.`

**Comment by bcorso** [comment]
> error: [Dagger/MissingBinding] android.content.Context cannot be provided without an @Provides-annotated method.
I added provide method to module:
>
> ```kotlin
>  @Provides
>  @Singleton
>  fun provideSharedPreferencesHelper(@ApplicationContext context: Context): SharedPreferencesHelper =
>      SharedPreferencesHelper(context)

Adding a provider for `SharedPreferencesHelper` is not going to fix your missing binding error because the missing binding is for `Context`.

Can you delete that provider and post the entire error message for the missing `Context` binding? That error message should tell you where you are trying to request a `Context` from. If the `@ApplicationContext Context` binding exists, then it's likely that you just need to add the `@ApplicationContext` qualifier to that request.

**Comment by bcorso** [comment]
Closing for now. Feel free to report back with the error message if you have other questions.
