### ISSUE TITLE
Hilt Question: How to uninstall the real ViewModel and attach a Fake one?

### ISSUE THREAD

**Issue by homandiy** [google/dagger#2557]
I am using @HiltViewModel with my ViewModel. I want to test it in UI testing. 
Can I uninstall the real ViewModel and attach a Fake one?

**Comment by Chang-Eric** [comment]
Uninstalling `@HiltViewModel` types and replacing them isn't supported. This is similar to how you can't really uninstall a Hilt fragment and replace it with a fake. You can use the various testing APIs though to replace the bindings your ViewModel injects. If you really feel strongly about faking your ViewModel logic, you would need to wrap it behind an abstraction that uses the ViewModel as an implementation detail, and then fake it at that abstraction layer.

**Comment by homandiy** [comment]
Thanks, I will continue with lateinit var.
