### ISSUE TITLE
Cannot resolve symbol 'DaggerXXComponent ' 

### ISSUE THREAD

**Issue by jemshit** [google/dagger#256]
I have a `Vehicle` class, a `VehicleModule` and `VehicleComponent` for that module. I am trying to create `Vehicle` object inside MyActivity using:

```java
Vehicle vehicle;
VehicleComponent component =DaggerVehicleComponent.builder()
                .vehicleModule(new VehicleModule())
                .build();
component.inject(this);
vehicle = component.provideVehicle();
```

I can not compile code. It gives `Cannot resolve symbol 'DaggerVehicleComponent ' ` error.

My *build.gradle*:
```
    compile 'com.google.dagger:dagger:2.0.2'
    provided 'com.google.dagger:dagger-compiler:2.0.2'
    provided 'javax.annotation:jsr250-api:1.0'
```
I have tried using `provided 'org.glassfish:javax.annotation:10.0-b28'` as well. How do we create components inside Activity?

**Comment by ronshapiro** [comment]
Is your component an inner interface of your Activity? If so, the component name `DaggerMyActivity_VehicleComponent`. Also, if you have a MembersInjector (the `void inject(MyActivity activity)` method) then you don't need to also set the vehicle variable as well, its redundant.

**Comment by jemshit** [comment]
it is not inner interface.

**Comment by ronshapiro** [comment]
Aha, I missed that you have the wrong scope for the dagger compiler. Try switching `provided` to `apt` (more instructions here: https://bitbucket.org/hvisser/android-apt)

**Comment by jemshit** [comment]
Did Work :+1:
