### ISSUE TITLE
2.35 stopped supporting an additional `@HiltAndroidApp` in `/androidTest` sources

### ISSUE THREAD

**Issue by dandc87** [google/dagger#2577]
[This commit](https://github.com/google/dagger/commit/e33bb84bdff414559fa74d178e53d9e38354c468) introduced validation that now disallows both `/main` and `/androidTest` from containing `@HiltAndroidApp` roots.

We currently have this configuration to support a large suite of pre-Hilt tests. We're working on migrating everything but the change in semantics is quite a hurdle for us.

Could we get an opt-out path? Either a compiler flag or annotation like `@DisableInstallInCheck`?

**Comment by bcorso** [comment]
Hey Adam,

Sorry about this (just realized we forgot to add this to the release notes too)! 

Your use case sounds valid, and we can add a compiler flag to opt-out of this validation.

Just to make sure I understand your use case -- your `/androidTest` only contains `@HiltAndroidApp` and not both `@HiltAndroidApp` and `@HiltAndroidTest` usages, right?

**Comment by dandc87** [comment]
Correct. We are not mixing `@HiltAndroidApp` and `@HiltAndroidTest` (I believe there was already validation preventing it)

**Comment by CookieXie** [comment]
how do i add this flag.
i tried like these but dont work
![image](https://user-images.githubusercontent.com/18480772/129298718-d8675983-920a-4d84-a027-6394872ef172.png)

**Comment by Chang-Eric** [comment]
Try setting it via javacOptions. See https://github.com/google/dagger/issues/2684#issuecomment-860250964 for an example.
