### ISSUE TITLE
@Scope for new instance every time

### ISSUE THREAD

**Issue by ZakTaccardi** [google/dagger#258]
Often, I will forget to put an `@Scope` on a `@Provides` method. This is a very different scenario that shouldn't be confused with intentionally wanting to provide a new instance every time the `@Provides` method is called. 

Let's say you have a method:

`@Provides String provideString();`

This will provide a new `String` every time. However, it would be nice to have an optional annotation like: 

`@Everytime @Provides String provideString();`

This annotation wouldn't actually do anything and could be completely ignored by the compiler, but it would let others know that the original programmer's intent was for this method to provide a new instance every time. Could help with code maintenance slightly.

**Comment by ronshapiro** [comment]
Nothing stopping you doing that in your own project, but I don't think it would be fitting in the compiler unless we validated that provisions didn't mark `@Scope` and `@Everytime` at the same time.

If all you wanted was documentation, this should work:
```java
@Retention(RetentionPolicy.SOURCE)
public @interface Everytime {}
```
