### ISSUE TITLE
@CustomTestApplication with a service started in base application

### ISSUE THREAD

**Issue by namgk** [google/dagger#2585]
Hi there,

I have a custom application that has some logic in it. In essence, it starts a service in the onCreate function. The service is annotated with @AndroidEntryPoint.

This causes a problem that said "the component was not created".

I can make it work in two ways:

1. Remove the @AndroidEntryPoint annotation, which isn't desired cause I cannot inject things into this service.
2. Move the service starting code from the base application class into an Activity.

I can have a feeling of what's going on under the hood, but is there a way to start a service inside the application class? It's a long running background service that is independent from any UI activities.

Thanks.

**Comment by Chang-Eric** [comment]
https://dagger.dev/hilt/early-entry-point#background has some details about why this limitation exists. Basically, the application in tests exists through multiple test cases so it isn't clear which test components we should use for the service.

I think what you likely want to do is move the service starting code into a test rule that starts the service. You might need an `OnComponentReadyListener` for this. https://github.com/google/dagger/blob/master/java/dagger/hilt/android/testing/OnComponentReadyRunner.java#L49

**Comment by namgk** [comment]
Thanks, I resorted to a check to see if it's running tests and disabled the service starting code accordingly.
