### ISSUE TITLE
Build warning suppress

### ISSUE THREAD

**Issue by talentprince** [google/dagger#259]
Hi team, so many build warning for generic inflect, will it be solved in feature release soon, I saw one TODO(gak) for months, but still not solved.

**Comment by ronshapiro** [comment]
Can you clarify? Which warnings are you referring to? And in what
conditions do you see them? Can you reproduce in a small example?

**Comment by talentprince** [comment]
ComponentGenerator 666 line.

My app update from dagger1, and 90% of warning is like this.

```
warning: [unchecked] unchecked conversion
    this.omnitureCacheProvider = OmnitureCache_Factory.create((MembersInjector) MembersInjectors.noOp(), providesAppDataProvider);
```

**Comment by tbroyer** [comment]
This is a dupe of #199
