### ISSUE TITLE
How did the dagger team solve IDE external code reference invalid issue?

### ISSUE THREAD

**Issue by jinweihan2020** [google/dagger#2592]
I am trying to open dagger in Android Studio, and I found a lot of code can not build the index by IDE, I just wonder did your team also faced this kind of issue? If so, how do you solved it?
Example:
![image](https://user-images.githubusercontent.com/62824817/117237319-912eae80-addf-11eb-92e0-6474fd4629ef.png)
I through it is because it is unsynced, but I partially synced the file but it will sync failed.
![image](https://user-images.githubusercontent.com/62824817/117237646-3e092b80-ade0-11eb-9ed1-9a77d127c58b.png)
But when I manually re-run the command in another console, its a success.

![image](https://user-images.githubusercontent.com/62824817/117237515-fda9ad80-addf-11eb-9181-6037fe33c1f8.png)

![image](https://user-images.githubusercontent.com/62824817/117237549-0bf7c980-ade0-11eb-9ca6-e8042fe9e666.png)

So, could you please tell me how can we help IDE build the symbol index?

**Comment by JakeWharton** [comment]
Have you tried IntelliJ IDEA? Android Studio is really only for Android projects built by Gradle.

**Comment by danysantiago** [comment]
I personally use IntelliJ IDEA 2020.3 (not the latest) with the Bazel plugin, make sure to have your `ANDROID_HOME` environment variable set (to find the Android SDK) and at least JDK 8. Some of this information can be found here: https://github.com/google/dagger/blob/master/CONTRIBUTING.md#importing-the-dagger-project-in-intellijandroid-studio

But the truth is that we have other internal tools inside Google that help us work with the Dagger codebase, so we are not really aware of these unless someone reports it. Let me know if you are able to figure it out or if we need to update our instructions.

**Comment by jinweihan2020** [comment]
> Have you tried IntelliJ IDEA? Android Studio is really only for Android projects built by Gradle.

I tried IntelliJ IDEA 2020.3.4 CE today, it succeeded! the symbol indexed, I should have tried it before asking here. Thanks @JakeWharton @danysantiago a lot. Looks you don't have to update instructions for it anymore.
