### ISSUE TITLE
Failed to resolve: androidx.hilt:hilt-navigation-compose:1.0.0-alpha02

### ISSUE THREAD

**Issue by Tom-Alphero** [google/dagger#2606]
I'm trying to use alpha-02 of the hilt nav compose lib as suggested [in the docs](https://developer.android.com/jetpack/compose/libraries#hilt): 

    implementation 'androidx.hilt:hilt-navigation-compose:1.0.0-alpha02'

I have `google()` set up as a repository and other libs that depend on it (including alpha01) are fetched OK.

It's listed as the latest release in https://developer.android.com/jetpack/androidx/releases/hilt however there are no release notes for it.

**Comment by Tom-Alphero** [comment]
Note that I assume `alpha02` adds support for `hiltViewModel()` as it cannot be found in `alpha01`.

**Comment by danysantiago** [comment]
The artifact is now live: https://developer.android.com/jetpack/androidx/releases/hilt#hilt-navigation-compose-1.0.0-alpha02
