### ISSUE TITLE
update the android studio to 4.2 then has a problem

### ISSUE THREAD

**Issue by bittyshadow** [google/dagger#2608]
DaggerActivityComponent.java:13: javax.annotation.processing
import javax.annotation.processing.Generated;

env:
android studio 4.2
gradle-6.7.1
java version "1.8.0_261"
dagger version:2.35.1

**Comment by bcorso** [comment]
This sounds like a duplicate of https://github.com/google/dagger/issues/1339#issuecomment-832517081.

Can you verify if the suggestions in that thread fix your issue?

**Comment by bcorso** [comment]
Closing as a dupe of #1339
