### ISSUE TITLE
[Hilt] Upgrading from v2.33-beta to v2.34-beta+

### ISSUE THREAD

**Issue by uxcalibrekai** [google/dagger#2630]
This method has changed from

```java
  @Override
  public ViewModelProvider.Factory getDefaultViewModelProviderFactory() {
    return DefaultViewModelFactories.getFragmentFactory(fragment);
  }
```

to

```java
  @Override
  public ViewModelProvider.Factory getDefaultViewModelProviderFactory() {
    return DefaultViewModelFactories.getFragmentFactory(fragment, factory);
  }
```

This makes an error of 

```
method getFragmentFactory in class DefaultViewModelFactories cannot be applied to given types;
required: Fragment,Factory
found: Hilt_MyFragment
reason: actual and formal argument lists differ in length
```

Code snippet of Fragment

```kotlin
@AndroidEntryPoint
class MyFragment: BaseFragment() {
    private val myViewModel : MyViewModel by viewModels()
}
```

Code snippet of ViewModel

```
@HiltViewModel
class MyViewModel
@Inject constructor(myRepository: MyRepository) : ViewModel() {...}
```

If there have been any changes I'm not aware of, please let me know. 

The generated method does not autopopulate a factory but documentation does not seem to require a viewmodel factory anywhere...

**Comment by bcorso** [comment]
Hi @uxcalibrekai,

> If there have been any changes I'm not aware of, please let me know.

There were a number of changes related to ViewModel support in Hilt in v2.34.

You can read more in the [2.34 release notes](https://github.com/google/dagger/releases/tag/dagger-2.34).

> This method has changed from
> 
> ```java
>  @Override
>  public ViewModelProvider.Factory getDefaultViewModelProviderFactory() {
>    return DefaultViewModelFactories.getFragmentFactory(fragment);
>  }
> ```
>
> to
>
> ```java
>  @Override
>  public ViewModelProvider.Factory getDefaultViewModelProviderFactory() {
>    return DefaultViewModelFactories.getFragmentFactory(fragment, factory);
>  }
>```

Where is that method coming from? Is that in your own class, Hilt class, Hilt generated class?

**Comment by uxcalibrekai** [comment]
Yes, that method is coming from the Hilt generated class. 

I took a look at the release notes and I had already completed those steps a while back when it was first introduced so I don't see why the auto generated class still generates 

   return DefaultViewModelFactories.getFragmentFactory(this); 

when it should be

   return DefaultViewModelFactories.getFragmentFactory(this, factory);

I don't know where this factory should be created and thus auto generated.

**Comment by bcorso** [comment]
Hmm, it sounds like you're saying that the generated code is missing the factory parameter. 

It looks like the factory parameter was added since v2.34 in change https://github.com/google/dagger/commit/3778ee2b881b2cc1138d93b07f1ea1fc09b795bf.

If you look at [FragmentGenerator.java](https://github.com/google/dagger/blob/master/java/dagger/hilt/android/processor/internal/androidentrypoint/FragmentGenerator.java#L218) you can see that Hilt currently generates the following:

```java
@Override
public ViewModelProvider.Factory getDefaultViewModelProviderFactory() {
  return DefaultViewModelFactories.getFragmentFactory(this, super.getDefaultViewModelProviderFactory());
}
```

If that's not what's being generated for you, please double check your dependencies and confirm that you've updated the `"com.google.dagger:hilt-compiler"` dependency > 2.34, and preferably to 2.35.1.

**Comment by uxcalibrekai** [comment]
Thanks @bcorso. That was the fix.

Strange that i didn't get prompted to update the dependency. I was prompted to update the androix.hilt:hilt-compiler only.

Cheers.
