### ISSUE TITLE
Support for Kotlin typealias

### ISSUE THREAD

**Issue by rokn** [google/dagger#2647]
There is a mention in #900 about supporting Kotlin `typealias` feature instead of `@Named` or custom qualifiers.
Is there any chance that you would consider this, as it makes the code more concise which is really valuable in a Kotlin codebase. It could transform this code:
```kotlin
@Qualifier
@Retention(AnnotationRetention.RUNTIME)
annotation class RootReference

@Qualifier
@Retention(AnnotationRetention.RUNTIME)
annotation class UsersReference

class FireBaseModule {
    @Provides
    @RootReference
    open fun provideRootReference(): DatabaseReference {
        return Firebase.database(...).reference
    }

    @Provides
    @UsersReference
    open fun provideUsersReference(@RootReference rootReference: DatabaseReference): DatabaseReference {
        return rootReference.child(...)
    }
}
```

Into a much more concise version:

```kotlin
typealias RootReference = DatabaseReference
typealias UsersReference = DatabaseReference

class FireBaseModule {
    @Provides
    open fun provideRootReference(): RootReference {
        return Firebase.database(...).reference
    }

    @Provides
    open fun provideUsersReference(rootReference: RootReference): UsersReference {
        return rootReference.child(...)
    }
}

```

And it will be much more easy on constructors parameters where these things are needed.

**Comment by JakeWharton** [comment]
This is not what an "alias" is, though. An alias is a shorthand for the other thing but semantically still represents the same thing. My birth name is Jacob but people call me Jake. Despite having two aliases, I am still only one person.

You are likely searching for Kotlin's `value class` to solve this problem which actually creates a new type.

**Comment by Chang-Eric** [comment]
Closing this since I agree with Jake's assessment that Dagger should not treat these as separate types. From a usability perspective, I think a common case for using typealias is to shorten long names, and in those cases you actually don't want it to equate to a different binding.
