### ISSUE TITLE
Hilt: Inject ContentProviders just like other Android components

### ISSUE THREAD

**Issue by consp1racy** [google/dagger#2650]
### Current behavior

[See example.](https://developer.android.com/training/dependency-injection/hilt-android#not-supported)

### Expected behavior

```kotlin
@AndroidEntryPoint
class ExampleContentProvider : ContentProvider() { ... }
```

### What's needed

Note: I'm not familiar with how the codegen works, hell, I wasn't lucky enough to even use Hilt so far, so forgive inacuracies in the description.

Content providers get instantiated before `Application.onCreate` so everything needs to be ready by then. We'll need to move Dagger graph generation from generated `Application.onCreate` to `Application.attachBaseContext` and make sure that app context works correctly. I've been using the following application class:

```java
public class ProcessAwareApplication extends Application {
    public ProcessAwareApplication() {
    }

    public Context getApplicationContext() {
        return this; // This is important, read on.
    }

    public void attachBaseContext(@NonNull Context base) {
        super.attachBaseContext(base);
        this.onProcessStarted();
    }

    @CallSuper
    protected void onProcessStarted() {
        // TODO Move Dagger graph generation here.
    }
}
```

`getApplicationContext` doesn't fully work out-of-the-box this early. There's some back and forth code and the wiring is not completely set up. But we know that it's going to end up returning `this`. If we do that manually, it just works™.

See also:
* https://cs.android.com/android/platform/superproject/+/5d123b67756dffcfdebdb936ab2de2b29c799321:frameworks/base/core/java/android/app/Application.java;l=351
* https://cs.android.com/android/platform/superproject/+/5d123b67756dffcfdebdb936ab2de2b29c799321:frameworks/base/core/java/android/app/ContextImpl.java;l=355
* https://cs.android.com/android/platform/superproject/+/5d123b67756dffcfdebdb936ab2de2b29c799321:frameworks/base/core/java/android/app/ActivityThread.java;l=6683
* https://cs.android.com/android/platform/superproject/+/5d123b67756dffcfdebdb936ab2de2b29c799321:frameworks/base/core/java/android/app/LoadedApk.java;l=1238

Hilt generates a base application class which could hide all this nicely.

There's a [`ContentProvider.shutdown`](https://developer.android.com/reference/android/content/ContentProvider#shutdown()) method, which is not normally used by Android. Everything in a `ContentProvider` lives until the process dies, so it has a singleton/application scope.

### Why I don't do it

I'm not familiar with codegen or hilt. I couldn't ship this fast. Given all this info somebody else could probably do it fairly easily. And that in turn could help me get familiar, I don't think this should be a huge change code-wise.

**Comment by bcorso** [comment]
Closing this for now, but feel free to reopen if you still have questions.
