### ISSUE TITLE
Dynamic feature module can't inject from AppComponent

### ISSUE THREAD

**Issue by phongbm** [google/dagger#2658]
In :app module
```
@Singleton
@Component(modules = [AppModule::class])
interface AppComponent {
    @Component.Factory
    interface Factory {
        fun create(@BindsInstance context: Context): AppComponent
    }
}    
```
```
@Module
class AppModule {
    @Singleton
    @Provides
    fun provideA() = A()
}
```
In dynamic feature module
```
@Component(
        dependencies = [AppComponent::class],
        modules = [FeatureModule::class]
)
interface FeatureComponent{
    @Component.Factory
    interface Factory {
        fun create(appComponent: AppComponent): FeatureComponent
    }

    fun inject(fragment: HomeFragment)

}
```
```
@Module
class FeatureModule {
}
```

In HomeFragment or HomeViewModel, I can't inject object A (provided in AppModule in AppComponent).
How to resolve it?

Thanks.

**Comment by Chang-Eric** [comment]
When you use `@Component(dependencies = ...)` the bindings you want to be propagated have to exist as methods on the interface. So you'll need a method like `fun getA(): A` on the `AppComponent` interface to expose it. Only those bindings with a method on the interface are propagated, which is different from subcomponents where all bindings are propagated from parent to child.
