### ISSUE TITLE
[AssistedInject] Support injecting Provider<T> of @AssistedFactory type

### ISSUE THREAD

**Issue by ghus-raba** [google/dagger#2659]
While converting from Square's assisted inject to Daggers's we've ran into:

```
error: Dagger does not support injecting Provider<T>, Lazy<T>, Producer<T>, or Produced<T> when T is an @AssistedFactory-annotated type such as Foo
```
Why is this restriction in place? 

It can be worked around with providing a non-assisted factory, but this feels like an unnecessary boilerplate. Or is this actually wrong and can it break something?

```kotlin
class Foo @Inject constructor(@Assisted bar: String, ...) {
    
    @AssistedFactory
    interface Factory {
        fun create(bar: String)
    }

    class NonAssistedFactory @Inject constructor(private val factory: Factory) {
        fun create(bar: String) = factory.create(bar)
    }
}

class Baz @Inject constructor(
    val factory1: Provider<Foo.Factory>, // this causes error shown above
    val factory2: Provider<Foo.NonAssistedFactory> // this works fine
) {
   //...
}
```

**Comment by bcorso** [comment]
Is there a reason you need to inject `Provider<Foo.Factory>` rather than injecting `Foo.Factory` directly?

**Comment by ghus-raba** [comment]
What we have in our code is some abstract factory pattern with "factory of factories":

```kotlin
class Product1 @AssistedInject constructor(...) : AbstractProduct {
    @AssistedFactory
    interface Factory {
        fun create(arg1: Foo, arg2: Bar): Product1
    }
}

class Product2 @AssistedInject constructor(...) : AbstractProduct {
    @AssistedFactory
    interface Factory {
        fun create(arg1: Baz): Product2
    }
}

class FactoryOfFactories @Inject constructor(
    private val factory1: Provider<Product1.Factory>,
    private val factory2: Provider<Product2.Factory>,
    ...
) {
    fun getFactoryMethod(args: Bundle): () -> AbstractProduct = {
        when (args.type) {
            "Product1" -> factory1.get().create(args.arg1, args.arg2)
            "Product2" -> factory2.get().create(args.arg3)
            ...
        }
    }
}
```
Each of the factories have different constructor arguments - both assisted and provided by dagger, but only one of them is always used when calling `getFactoryMethod()`. So it seems wasteful to create all the other factories with all their dependencies, when most of them end up unused. That's why we have `Provider`s there instead and only `get()` the one that is actually used.

Or is this overthinking it and no improvement over just injecting factory directly? Thanks for feedback.

**Comment by bcorso** [comment]
> So it seems wasteful to create all the other factories with all their dependencies, when most of them end up unused. That's why we have Providers there instead and only get() the one that is actually used.
>
> Or is this overthinking it and no improvement over just injecting factory directly? Thanks for feedback.

Yeah, I don't think this will give you much improvement over just injecting the factories directly. Creating the factory doesn't actually require creating the dependencies, just a `Provider` for each dependency. In addition, this shouldn't cost you anything extra because Dagger already creates all of the providers for each binding up front anyway.

**Comment by ghus-raba** [comment]
Right, in the meantime I also already checked the generated code and see that it really uses `Provider`, so nothing is created until the factory method is called.

Thanks for explaining, closing the issue now.
