### ISSUE TITLE
Question: how does field injection work under the hood?

### ISSUE THREAD

**Issue by cxzhang2** [google/dagger#267]
I'm trying to comb through the source to answer this question but honestly it's just way over my head at this point.  Would someone be kind enough to explain to me how field injection is done without reflection?

Thanks!

**Comment by JakeWharton** [comment]
A generated class in the same package just assigns the values. The fields
are not allowed to be private or final to facilitate this.

**Comment by cxzhang2** [comment]
Got it! Thanks!
