### ISSUE TITLE
Dagger doesn't generate a Dagger~ class from a Component, when a generated source has Injected fields

### ISSUE THREAD

**Issue by DDJarod** [google/dagger#269]
We have a larger (multi-) project build with a second annotation processor in it. The processor generates a Class with injected fields. Dagger (v 2.0.2) picks the class up and generates a ~Factory and ~MembersInjector class. But it does not generate a Dagger~ class from the Component in the project, neither are there errors during compilation.

But when we use a class copied from the generated class (and classname changed for ease of use) everything still compiles and we get our Dagger~ class.

I stripped the project down to an example multi project repository to test it or give a hint on what went wrong: https://github.com/DDJarod/Dagger_2_Component_Problem

**Comment by ronshapiro** [comment]
This was fixed in 1505feb6c7da543ce82168184ab4ec21f8a169a0.

**Comment by ronshapiro** [comment]
(For the record, you can get this functionality by using the `2.1-SNAPSHOT` version instead of `2.0.2`)
