### ISSUE TITLE
Hilt Worker Inject throws NoSuchMethodException

### ISSUE THREAD

**Issue by kailunAusUnity** [google/dagger#2690]
Currently using com.google.dagger:hilt-android:2.37, compiler is  com.google.dagger:hilt-android-compiler:2.37, noticing issue after upgrading from 2.33. This error occurs when a repository or another dependency injected component, is injected into the worker, it works fine without the repository injected. This previously worked on v2.33 and I don't see any breaking changes in the changelog.

Error message:
```
E/WM-WorkerFactory: Could not instantiate com.testapp.TestApp.services.workers.TestWorker
    java.lang.NoSuchMethodException: com.testapp.TestApp.services.workers.TestWorker.<init> [class android.content.Context, class androidx.work.WorkerParameters]
        at java.lang.Class.getConstructor0(Class.java:2332)
        at java.lang.Class.getDeclaredConstructor(Class.java:2170)
        at androidx.work.WorkerFactory.createWorkerWithDefaultFallback(WorkerFactory.java:95)
        at androidx.work.impl.WorkerWrapper.runWorker(WorkerWrapper.java:244)
        at androidx.work.impl.WorkerWrapper.run(WorkerWrapper.java:136)
        at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
2021-06-14 20:04:16.894 5119-5335/com.testapp.TestApp E/WM-WorkerWrapper: Could not create Worker com.testapp.TestApp.services.workers.TestWorker
```

Worker code example: 

```
@HiltWorker
class TestWorker @AssistedInject constructor(
    @Assisted appContext: Context,
    @Assisted workerParams: WorkerParameters,
    val repository: TestRepository
) : CoroutineWorker(appContext, workerParams) {

    override suspend fun doWork(): Result = withContext(Dispatchers.IO){
        // Indicate whether the work finished successfully with the Result
        return@withContext try{
            Result.success()
        } catch (e: Exception) {
            Result.retry()
        }
    }
```

Default initializer removed 
```
<provider
            android:name="androidx.startup.InitializationProvider"
            android:authorities="${applicationId}.androidx-startup"
            android:exported="false"
            tools:node="merge">
            <!-- If you are using androidx.startup to initialize other components -->
            <meta-data
                android:name="androidx.work.impl.WorkManagerInitializer"
                android:value="androidx.startup"
                tools:node="remove" />
        </provider>

```
Application file
```
@HiltAndroidApp
class App : Application(), Configuration.Provider {

    @Inject
    lateinit var workerFactory: HiltWorkerFactory

    /**
     * Work Manager Configuration
     */
    override fun getWorkManagerConfiguration(): Configuration {
        return Configuration.Builder()
            .setWorkerFactory(workerFactory)
            .setMinimumLoggingLevel(android.util.Log.DEBUG)
            .build()
    }
}
```
Repository injection
```
@Module
@InstallIn(SingletonComponent::class)
object RepositoryModule {

    @Provides
    @Singleton
    fun provideTestRepository(
        testDao: TestDao,
        api: Api,
        appExecutors: AppExecutors
    ): TestRepository {
        return TestRepository(testDao, api, appExecutors)
    }
}
```
Viewmodel code to call worker request
```
val workRequest = PeriodicWorkRequestBuilder<TestWorker>(15, TimeUnit.MINUTES)
                            .setInitialDelay(1, TimeUnit.MINUTES)
                            .setConstraints(constraints)
                            .build()

                        WorkManager.getInstance(requireContext()).enqueueUniquePeriodicWork(Constants.Worker.WORKER, ExistingPeriodicWorkPolicy.REPLACE, workRequest )
```

**Comment by danysantiago** [comment]
Which version of WorkManager are you using? This seems very similar to https://github.com/google/dagger/issues/2601. If you are using WorkManager 2.6.0 then disabling the default initialization is different, see https://github.com/google/dagger/issues/2601#issuecomment-837816151

Other things to check:

- Is your `@HiltWorker` class in a separate Gradle module from your app module? Does the app have a direct dependency on the module where the worker is?

- If you debug the [`HiltWorkerFactory`](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:hilt/hilt-work/src/main/java/androidx/hilt/work/HiltWorkerFactory.java;l=55?q=HiltWorkerFactory&ss=androidx%2Fplatform%2Fframeworks%2Fsupport) around lines 53-55 do you see non-null `factoryProvider` for your worker? This is an indication that the Worker is in the multimap and has been picked up by the annotation processors.

**Comment by kailunAusUnity** [comment]
Hi Dany, I am using v 2.7.0-alpha04 for work, androidx.work:work-runtime-ktx:2.7.0-alpha04.

According to the documentation and using

` <provider
    android:name="androidx.startup.InitializationProvider"
    android:authorities=\"${applicationId}.androidx-startup"
    android:exported="false"
    tools:node=\"merge">
    
    <meta-data
        android:name="androidx.work.impl.WorkManagerInitializer"
        android:value="androidx.startup"
        tools:node="remove" />
 </provider>`

still garners the same error.

Disabling android.startup completely works.
` 
 <provider
    android:name="androidx.startup.InitializationProvider"
    android:authorities="${applicationId}.androidx-startup"
    tools:node="remove">
 </provider>`

Although my current project does not have any other component that utilises androidx.startup. This problem still occurs if you only need to disable workmanagerinitializer.

**Comment by danysantiago** [comment]
Ah - I think this is a bit lost in the release notes, but `WorkManagerInitializer` got moved in alpha02 and onward, and based on the code that you have you are still removing the one in the outdates package, `androidx.work.impl.WorkManagerInitializer` vs `androidx.work.WorkManagerInitializer`.

The full code to only WorkManager's initializer (without disabling all of androidx.startup) should be:
```
<provider
    android:name="androidx.startup.InitializationProvider"
    android:authorities=\"${applicationId}.androidx-startup"
    android:exported="false"
    tools:node="merge">
    <!-- If you are using androidx.startup to initialize other components -->
    <meta-data
        android:name="androidx.work.WorkManagerInitializer"
        android:value="androidx.startup"
        tools:node="remove" />
 </provider>
```

**Comment by kailunAusUnity** [comment]
Hi Dany, as I wrote above, using what you just wrote generates the error I had above. However removing it completely, there is no issue.

`<provider
    android:name="androidx.startup.InitializationProvider"
    android:authorities=\"${applicationId}.androidx-startup"
    android:exported="false"
    tools:node="merge">
    
    <meta-data
        android:name="androidx.work.WorkManagerInitializer"
        android:value="androidx.startup"
        tools:node="remove" />
 </provider>`

**Comment by vincent-paing** [comment]
I'm on work manager 2.7.1 and hilt 2.41. Seeing this issue. The only workaround is to create own factory. Seems like workerFactories is empty list in `WorkerFactoryModule`

**Comment by motorro** [comment]
@danysantiago 
- WorkManager: 2.8.0-alpha02
- Hilt: 2.41
I use custom WM initializer with entry point:
```kotlin
class WorkManagerInitializer : Initializer<WorkManager> {
    override fun create(context: Context): WorkManager {
        val entryPoint = EntryPointAccessors.fromApplication(
            context,
            WorkManagerInitializerEntryPoint::class.java
        )

        val configuration = Configuration
            .Builder()
            .setWorkerFactory(entryPoint.hiltWorkerFactory())
            .setMinimumLoggingLevel(if (BuildConfig.DEBUG) Log.DEBUG else Log.INFO)
            .build()
        WorkManager.initialize(context, configuration)
        return WorkManager.getInstance(context)
    }

    override fun dependencies(): List<Class<out Initializer<*>>> = emptyList()

    @InstallIn(SingletonComponent::class)
    @EntryPoint
    interface WorkManagerInitializerEntryPoint {
        fun hiltWorkerFactory(): HiltWorkerFactory
    }
}
```
The factory runs OK (checked with breakpoint)
However `HiltWorkFactory` `mWorkerFactories` is empty.
I have workers both in main module and sub-module. 
Niether gets created
