### ISSUE TITLE
missing new line between errors

### ISSUE THREAD

**Issue by BraisGabin** [google/dagger#2699]
If I have multiple errors when building my dependency graph I expect to have multiple errors. I do get multiple errors but between one and another there is no a new line (`\n`). The second error starts just after the second:

>/Users/brais.gabin/Workspace/.../Component.java:8: error: [Dagger/MissingBinding] @javax.inject.Named("callback") kotlin.jvm.functions.Function1<? super Result,kotlin.Unit> cannot be provided without an @Provides-annotated method.
public abstract interface Component extends dagger.android.AndroidInjector<App> {
[...]
          dagger.android.AndroidInjector.inject(T) [...Component → ...MainActivitySubcomponent]/Users/brais.gabin/Workspace/.../Component.java:8: error: [Dagger/MissingBinding] ...

Note here that the end of the first message is `MainActivitySubcomponent]` and the start of the second is `/Users/brais.gabin/Workspace/` and there is no new line between them.

Tested in 2.37 and 2.34.1

I'm using ndroid-dagger and I'm not using hilt in this configuration.

**Comment by danysantiago** [comment]
Are you viewing this error from Android Studio or the command line?

**Comment by BraisGabin** [comment]
Command line

**Comment by danysantiago** [comment]
This is odd, we don't really control most of the formatting of these messages, specially the spaces, new lines and the markers added to point to the source where the error is. Dagger and Hilt simply uses the [JDK annotation processors APIs](https://docs.oracle.com/en/java/javase/11/docs/api/java.compiler/javax/annotation/processing/Messager.html) to report errors.

Maybe this is something related to the JDK you are using? Or to the terminal?
