### ISSUE TITLE
Can I specify the order of injection？

### ISSUE THREAD

**Issue by songtao542** [google/dagger#2701]
@Inject
lateinit var application: Application

@Inject
open fun onFinishMemberInject() {
       onCreate(application)
}

I want to ensure the "onFinishMemberInject()" method be execute after the "application" field is injected.

**Comment by JakeWharton** [comment]
Per [`@Inject` documentation](https://docs.oracle.com/javaee/6/api/javax/inject/Inject.html):

> Constructors are injected first, followed by fields, and then methods.
