### ISSUE TITLE
[Hilt] - Inject classes as interfaces

### ISSUE THREAD

**Issue by iskugor** [google/dagger#2708]
Hi. Lets say I have two interfaces and two classes that implements them.

```
interface ITest1 {
    fun doSomething()
}

interface ITest2 {
    fun doSomethingElse()
}

class Test1 @Inject constructor(): ITest1 {

    override fun doSomething() {
        println("Something")
    }
}
    
class Test2 @Inject constructor(): ITest2 {

    @Inject
    lateinit var test1: ITest1

    override fun doSomethingElse() {
        test1.doSomething()
        println("Something else ")
    }
}
```

I would like to instantiate Test1 and Test2 classes in "@Provide" and "@Bind" them to interfaces:

```
@Module(includes = [DependenciesBindings::class])
@InstallIn(SingletonComponent::class)
object Dependencies {

    @Singleton
    @Provides
    fun provideTest1(): Test1 {
        return Test1()
    }

    @Singleton
    @Provides
    fun provideTest2(): Test2 {
        return Test2()
    }
}

@Module
@InstallIn(SingletonComponent::class)
internal abstract class DependenciesBindings {
    @Singleton
    @Binds
    abstract fun bindTest1(test1: Test1): ITest1

    @Singleton
    @Binds
    abstract fun bindTest2(test2: Test2): ITest2
}
```

But this crashes app:

> Caused by: kotlin.UninitializedPropertyAccessException: lateinit property test1 has not been initialized at Test2.getTest1(Test2.kt:8) at Test2.doSomethingElse(Test2.kt:11)

I would expect ITest1 to be correctly injected as Test1 is provided and then bind to ITest1 interface.

**Comment by bcorso** [comment]
You should remove the `@Provides` method in your module, `Dependencies#provideTest2()`.

Dagger will only do field injection for you if it's using the `@Inject` constructor to create your binding. In your case, Dagger is ignoring the `@Inject` constructor  for `Test2` because you've declared an `@Provides` method for it, so Dagger will create `Test2` using `Dependencies. provideTest2()`, and it's up to you to inject `Test2` manually if you want to. However, from your example, there's no reason why you should define the `@Provides` method for `Test2`, so you can just remove it.

**Comment by iskugor** [comment]
@bcorso thanks for your answer. In this particular case, there is no reason to define `@Provides` for `Test2`, but this is just a simple example that demonstrates the issue I'm having. In real world scenario, for example, I may have access key stored in database (which is located in one module) which I need to add to backend (which is defined in other module). To me, it does not have sense to inject database, the simplest way is to configure backend with a key from database once backend instantiates. Because of that, I thought it makes sense to use `@Provides` and inject database as `@Provides` function parameter and then set access key to backend via setter.
 I can think of other examples.

Do you have some recommendation how to do that in this particular case?

**Comment by bcorso** [comment]
You can inject fields using an `@Provides` method, you just need to do it yourself (e.g. using a `MembersInjector<Test2>`). However, I'm still not sure I understand your example. If you provide some code for the database example I may be able to give you better advice.

**Comment by iskugor** [comment]
Hi @bcorso sorry for late reply, last week I was on vacation.

Thanks, I'll check out `MembersInjector`.

Regarding an example, I created sample project:
https://github.com/iskugor/Test

It's simplified version of what I currently have. As you can see, constructor based dependency injection is being used and I would like to transition to Hilt without having to change a lot of things.

**Comment by bcorso** [comment]
> To me, it does not have sense to inject database, the simplest way is to configure backend with a key from database once backend instantiates. Because of that, I thought it makes sense to use @Provides and inject database as @Provides function parameter and then set access key to backend via setter.

This is the part I'm interested in. Can you show the code for `Backend`, `Database`, and the `@Provides` you are talking about? Also, where/how are you actually setting the access key once the database is created?

**Comment by iskugor** [comment]
> This is the part I'm interested in. Can you show the code for `Backend`, `Database`, and the `@Provides` you are talking about? 

What exactly are you interested in?
`Backend` just does http requests with okhttp and retrofit.
`Database` is Room database that use SqlCipher. 

I think implementation details are not so important, important part is that I need to pass access key from `Database` to `Backend` (I think relevant parts are already present in sample project).

Right now, I manually construct them, something like this:

```
class Dependencies {
    fun getDatabase(): IDatabase {
        return Database()
    }

    fun getBackend(): IBackend {
        val backend = Backend()
        backend.setAccessId(getDatabase().getAccessId())
        return backend
    }
}
```

So I would assume something similar is possible with Hilt.


Regarding `@Provides`, here is updated version of what I think should work:

```
Module(includes = [DependenciesBindings::class])
@InstallIn(SingletonComponent::class)
object Dependencies {

    @Singleton
    @Provides
    fun provideDatabase(): Database {
        return Database()
    }

    @Singleton
    @Provides
    fun provideBackend(database: IDatabase): Backend {
        val backend = Backend()
		backend.setAccessId(database.getAccessId())
        return backend
    }
}

@Module
@InstallIn(SingletonComponent::class)
internal abstract class DependenciesBindings {
    @Singleton
    @Binds
    abstract fun bindDatabase(database: Database): IDatabase

    @Singleton
    @Binds
    abstract fun bindBackend(backend: Backend): IBackend
}
```

> Also, where/how are you actually setting the access key once the database is created?

It's set in "core" module once user logs in and backend server returns it via http response (so, at start, it is null).

**Comment by iskugor** [comment]
Here is a workaround in case someone will need it:

```
@Module(/* no includes */)
@InstallIn(SingletonComponent::class)
object Dependencies {

    @Singleton
    @Provides
    fun provideTest1(test1: Test1): ITest1 {
        // manipulate test1
        return test1
    }

    @Singleton
    @Provides
    fun provideTest2(test2: Test2): ITest2 {
        // manipulate test2
        return test2
    }
}
```
