### ISSUE TITLE
Cannot inject constructor with kotlin delegation

### ISSUE THREAD

**Issue by thechizko** [google/dagger#2722]
Code sample:
`class MyClass @Inject constructor(builder: MyClassBuilder) : IMyClass by builder.build()`

Already issued by someone else.
https://stackoverflow.com/questions/58930220/dagger-construction-injection-with-kotlin-class-delegation

**Comment by Chang-Eric** [comment]
Do you have more information on the error you're getting? I just tried this out and it worked for me.

```
@Component
interface TestComponent {
  fun delegateFoo(): DelegateFoo
}

interface Foo {
  fun getNumber(): Int
}

class FooImpl @Inject constructor() : Foo {
  override fun getNumber(): Int = 9
}

class DelegateFoo @Inject constructor(foo: FooImpl) : Foo by foo
```

**Comment by thechizko** [comment]
Sorry, fixed the problem myself.
Wrong library dependency causes this.
A < B(implmentation A) < C(implementation B)
C uses A functions.
