### ISSUE TITLE
Using Hilt for dependency Injection in Android Library 

### ISSUE THREAD

**Issue by Tan108** [google/dagger#2723]
I implemented Hilt in Android library  which contains only Services, BroadcastReceivers and it run in background as remote process. Unfortunately I faced issue that providers inside hilt module returns `java.lang.StackOverflowError: stack size 8MB` but I unable to conclude about the exact issue or is Hilt inside library feasible with non hilt apps.

**Comment by Chang-Eric** [comment]
If Hilt is used in a library and that library is used in a non-Hilt app, that probably won't work but the way it won't work is that the Hilt modules are likely to just not be installed in any components. Services and such should just fail with exceptions when we can't access the Hilt component.

So I would expect it to fail, but not with a StackOverflowError. I would probably need more information to say more about what is causing your problem though.

**Comment by Tan108** [comment]
I replace Hilt with Dagger in library because I faced issue with non-hilt apps and now everything is works fine with Dagger.Thanks for your suggestion.
