### ISSUE TITLE
About enableAggregatingTask 

### ISSUE THREAD

**Issue by andrewhunter0** [google/dagger#2753]
I had seen here: https://github.com/google/dagger/issues/2695, about the problem about enableAggregatingTask which caused Hilt_MyApplication can't created.  

I have the same problem.  
And my question is:  Why the issue was closed ?: https://github.com/google/dagger/issues/2695?
I saw the modify just committed 15 days ago,
And i did not find any new version that bigger than 2.37 that released on 11 Jun,
so i can't verify whether the problem has been fixed! when the new version will be released?

**Comment by bcorso** [comment]
I've commented on #2695 with instructions on how to test it. 

Feel free to open a new issue if the problem persists with `HEAD-SNAPSHOT`.

**Comment by andrewhunter0** [comment]
Ok, Thanks~
I will try, and reply on https://github.com/google/dagger/issues/2695.
