### ISSUE TITLE
Running Hilt Tests with Custom Runner using `Before`

### ISSUE THREAD

**Issue by sylwek845** [google/dagger#2754]
Hi all, I'm using Cucumber Tests for Integration Testing, because the Cucumber uses CustomRunner which does NOT trigger JUnit Rules or Before/After methods, I'm unable to inject objects into my tests. 

The cucumber runner does provide custom Before/After annotations, so my question is, if there is any way of injecting the Hilt without using Rules? 

Thanks.

**Comment by bcorso** [comment]
Unfortunately, Hilt injection requires the use of the `HiltAndroidRule`, and thus requires JUnit.

I'm not familiar with Cucumber, but if it has a similar concept of rules, you could try wrapping the `HiltAndroidRule` and calling `HiltAndroidRule#apply(Statement, Description)` manually but that's pretty sketchy territory, so I wouldn't recommend it.
