### ISSUE TITLE
[Hilt migration] Migrating from Dagger 2 with TestApplication and custom test Component

### ISSUE THREAD

**Issue by alexfacciorusso** [google/dagger#2757]
Hi all

I am migrating a quite extensive app with many instrumented tests in it.

The way the app is structured is: 

```
// in the main sources
open class MainApp {
    open val appComponent: ApplicationComponent = DaggerApplicationComponent.factory...
}

// in the test sources
class TestApp: MainApp {
    override val appComponent: ApplicationComponent = DaggerTestApplicationComponent.factory...
}
```

and of course `TestApplicationComponent` implements `ApplicationComponent`.

The main component had a lot of sub-modules, and by following the guide on how to migrate the app by creating an aggregator entry point, everything compiles and works more than fine.

The missing piece is the TestApp, and that is the main subject of this issue. Is there a way to migrate (partially) the `TestApp` so that I simply can run the tests as they were, and in future I will migrate it to use either `CustomTestApplication` or `HiltTestApplication`?

As an initial stage of our migration, I don't need `@HiltAndroidTest` to be usable: I just need the old tests to be runnable like they were on Dagger 2.

**Comment by Chang-Eric** [comment]
I've found the easiest way to handle cases like these is to turn your MainApp into a base class. So instead of putting `@HiltAndroidApp` on your MainApp class, you do something like the following:

```
// This class basically has nothing except Hilt
@HiltAndroidApp
class HiltMainApp : MainApp {
  override fun component(): ApplicationComponent {
    return generatedComponent() as ApplicationComponent
  }
}

open class MainApp {
  abstract fun component(): ApplicationComponent

  // ...all the other logic in your MainApp you want to test...
}

class TestApp : MainApp {
  override fun component(): ApplicationComponent {
    return DaggerTestApplicationComponent...
  }
}
```
