### ISSUE TITLE
Dynamic feature module with Hilt

### ISSUE THREAD

**Issue by Ali-Rezaei** [google/dagger#2758]
I try to make my feature module as a dynamic feature module while I am using Hilt as dependency injection framework. I receive following exception :

   ```
 caused by: java.lang.ClassCastException: com.android.sample.viaplay.DaggerViaplayApplication_HiltComponents_SingletonC$ActivityRetainedCImpl$ActivityCImpl$FragmentCI cannot be cast to com.android.sample.viaplay.feature.list.ui.DashboardFragment_GeneratedInjector
            at com.android.sample.viaplay.feature.list.ui.Hilt_DashboardFragment.inject(Hilt_DashboardFragment.java:104)
            at com.android.sample.viaplay.feature.list.ui.Hilt_DashboardFragment.onAttach(Hilt_DashboardFragment.java:55)
            at androidx.fragment.app.Fragment.onAttach(Fragment.java:1783)
            at com.android.sample.viaplay.feature.list.ui.Hilt_DashboardFragment.onAttach(Hilt_DashboardFragment.java:43)
```

I have used Dagger and not Dagger-Hilt in another sample and it worked as expected.

Is it possible to use Dynamic feature module with Hilt? If yes, how can I solve above exception.

Addenda : As I understood in the following link : [Dagger Hilt doesn't work with Dynamic Feature Modules](https://github.com/google/dagger/issues/1865), Hilt uses a monolithic component system which is incompatible with DFM that loads classes dynamically. It is mentioned that you are going to get back to this issue after official launch. Is there any plan now?

**Comment by Chang-Eric** [comment]
As you found from that issue you linked, the main guidance for dynamic feature modules is at https://developer.android.com/training/dependency-injection/hilt-multi-module#dfm. 

That comment you saw about after official launch is actually something else. That was just because the issue was filed in the time period before we actually announced Hilt at all (like pre-alpha) and so it was more referring to I'll get back to responding to that issue, which the response was https://github.com/google/dagger/issues/1865#issuecomment-642169884 which is that dynamic feature modules don't really work with Hilt beyond the guidance in the guide above. At this time, we currently do not have plans for additional dynamic feature module support.

**Comment by gfpf** [comment]
Hi there,
I have a dynamic module called home that has a frag using @androidentrypoint but I'm getting this error:

java.lang.ClassCastException: DaggerGranitexApp_HiltComponents_SingletonC$FragmentCImpl cannot be cast to HomeFragment_GeneratedInjector

Can't use Hilt in dynamic modules yet?

@AndroidEntryPoint
class HomeFragment : BaseFragment<FragmentHomeBinding, HomeViewModel, Any, Any, Any>(
    layoutId = R.layout.fragment_home
), IBaseView.NavigationInitializer {

merci merci

**Comment by alirezaeiii** [comment]
You cannot use Hilt with the dynamic feature module, you need to use Dagger2 with the Dynamic feature module.

**Comment by gfpf** [comment]
Thanks for quick feedback, can you please gimme a hand to try see where is the advantages of use Hilt in a Single Activity & Multi-Modular project with dynamic features?

I have a project with:
1 - app module
1 - ui module
1 - views module
1 - api/core module
22 - dynamic modules supported by this few modules above

The classic Diamond arch:

                                          app

feat A | feat B | feat C | feat D | feat E | feat F | feat G | feat N... 

                         core | ui | view | core | test 


All DFM is working with dagger2 (I'm using Hilt in whole project) but I need to handle by hand all the viewmodel DI in frags under DFM, like dealing with how many instances will be created, handle viewmodel providers with generic factory and creating manual components, like below (brings lots of complexity to the code):

```
override fun onInitDependencyInjection() {
        val coreComponent = GranitexApp.coreComponent(requireContext())
        val appComponent = GranitexApp.appComponent(requireContext())

        coreComponent?.let { itCore ->
            appComponent?.let { itApp ->
                DaggerMosaicComponent.builder().context(requireContext()).fragment(this)
                    .coreComponent(itCore).appComponent(itApp).build().inject(this)
            }
        }
        
        viewModel = ViewModelProvider(this, viewModelFactory)[MosaicViewModel::class.java]
    }
```

All the stuffs that Hilt should do it I need to do it by hand, and 90% of my development time is under the DFM classes, where is the real advantage of use Hilt in projects like that? 

I upgrade my project from Dagger2 to Hilt without know about that, terrible decision :((

I'm still learning about DI frameworks like Dagger and Hilt and I'm far away from be a specialist in the subject but for me until now there is no advantage in using Hilt.

Maybe I miss some important conecept, or misundertood the real paper of the framework, looks like fog.

Thanks again
