### ISSUE TITLE
Unexpected note "Generating MembersInjector"

### ISSUE THREAD

**Issue by pyricau** [google/dagger#276]
This happens with the latest published snapshot (`2.1-20151113.082645-11`)

Given this code:

```
public class SomeService extends IntentService {
  @Inject Dep dep;
}
```

Dagger generates a `SomeService_MembersInjector` as expected, but also issues the following warning:

`Note: Generating a MembersInjector or Factory for android.app.IntentService. Prefer to run the dagger processor over that class instead.`

`IntentService`, the parent class of `SomeService`, is a class belonging to the Android SDK, so it has no injects. There's no need to generated a members injector / factory for it.

In fact, none is actually generated, so that note is lying.

I also can't run the dagger processor over that class instead, since it's part of the Android SDK. But even if it was mine, there would be no generated class, so this warning message would still be issued.

**Comment by netdpb** [comment]
We're aware of this issue. It's fixed internally, and will be pushed in the next snapshot.

**Comment by pyricau** [comment]
@netdpb Please let me know when that's available, at least in the OSS repo.

**Comment by pyricau** [comment]
@netdpb is this fixed now?
