### ISSUE TITLE
Remote cache miss due to incorrect @Input parameter

### ISSUE THREAD

**Issue by remcomokveld** [google/dagger#2763]
We are seeing remote build cache misses on the `com.android.build.gradle.tasks.TransformClassesWithAsmTask`. It looks like this is because `@Input` is used instead of a combination `@InputFile` and `@get:PathSensitive(PathSensitivity.RELATIVE)` in the `AndroidEntryPointClassVisitor`.

https://github.com/google/dagger/blob/ff62b195c1a00727192154a409aa4ab0b796ff07/java/dagger/hilt/android/plugin/src/main/kotlin/dagger/hilt/android/plugin/AndroidEntryPointClassVisitor.kt#L27-L30

**Comment by runningcode** [comment]
This causes a 10+ second cache miss in every module where hilt is applied. This can add a significant amount of time in multi-module projects with hundreds of modules.
