### ISSUE TITLE
Ignoring dependency cycle warnings

### ISSUE THREAD

**Issue by pyricau** [google/dagger#277]
Dependency cycles are bad, but sometimes that's how it is. It'd be nice to have a way to ignore those warnings. Dagger2 error feedback is very detailed, which is great, but in that case it just adds noise.

**Comment by netdpb** [comment]
It isn't documented, but you can suppress the cycle warnings by adding `@SuppressWarnings("dependency-cycle")` to the component, to the component provision method, or to any dependency request element in the cycle.

It's better to suppress the warning on the most specific element you can. Probably the best place is on the `Provider` or `Lazy` that you use to break the cycle.

**Comment by pyricau** [comment]
Amazing, thanks!
