### ISSUE TITLE
Duplicate errors

### ISSUE THREAD

**Issue by pyricau** [google/dagger#278]
When a binding is missing, the error might be reported several times. ie if A needs B, B is missing, and 10 bindings need A, then the error is reported 10 times.

Although accurate, it's also very noisy and doesn't help much. That problem needs to be solved only once.

I think Dagger should only report the error once. Which one? The best might be to go for the shorter one, just to make it easier to read.

**Comment by gk5885** [comment]
There are more than a few ways in which we would like to improve error message and we plan to do a lot of that work in this coming quarter.  I'm not sure that the solution will look _exactly_ like you have proposed here, but we certainly agree that the current state is noisy and difficult to parse.

**Comment by ronshapiro** [comment]
@netdpb has worked on this in recent quarters and it's much better. I think we should close this given it's been 3 years, and we should open specific issues for individual errors.
