### ISSUE TITLE
Hilt_DPApp doesn't compile

### ISSUE THREAD

**Issue by XCarbone** [google/dagger#2780]
I want to use Hilt in a module but it doesn't seem to work.

i use those dependencies : 

```
implementation "com.google.dagger:hilt-android:2.28-alpha"
kapt "com.google.dagger:hilt-android-compiler:2.28-alpha"
implementation "androidx.hilt:hilt-lifecycle-viewmodel:1.0.0-alpha02"
kapt "androidx.hilt:hilt-compiler:1.0.0-alpha02"
```

I added `@HiltAndroidApp` to my multidexApplication :` class DPApp : MultiDexApplication()` and i also set up the name in manifest and it's seem to work.

How ever i got an error in a generated file Hilt_DPApp. The class is as follow :

```
`/**
 * A generated base class to be extended by the @dagger.hilt.android.HiltAndroidApp annotated class. If using the Gradle plugin, this is swapped as the base class via bytecode transformation. */
@Generated("dagger.hilt.android.processor.internal.androidentrypoint.ApplicationGenerator")
public abstract class Hilt_DPApp extends MultiDexApplication implements GeneratedComponentManager<Object> {
  private final ApplicationComponentManager componentManager = new ApplicationComponentManager(new ComponentSupplier() {
    @Override
    public Object get() {
      return DaggerDPApp_HiltComponents_ApplicationC.builder()
          .applicationContextModule(new ApplicationContextModule(Hilt_DPApp.this))
          .build();
    }
  });

  protected final ApplicationComponentManager componentManager() {
    return componentManager;
  }

  @Override
  public final Object generatedComponent() {
    return componentManager().generatedComponent();
  }

  @CallSuper
  @Override
  public void onCreate() {
    // This is a known unsafe cast, but is safe in the only correct use case:
    // DPApp extends Hilt_DPApp
    ((DPApp_GeneratedInjector) generatedComponent()).injectDPApp(UnsafeCasts.<DPApp>unsafeCast(this));
    super.onCreate();
  }
}`
```

The error is DaggerDPApp_HiltComponents_ApplicationC can not be resolve : 
error: cannot find symbol
      return DaggerDPApp_HiltComponents_ApplicationC.builder()
             ^
  symbol: variable DaggerDPApp_HiltComponents_ApplicationC

How can i fix it ? i fond some subjects about this and it was mainly about dependencies, so i tried so update them or to remove them but i still got the same error, is there a way to solve this ?

**Comment by OlegNovosad** [comment]
I recommend you to upgrade to stable hilt version and revalidate the issue.

**Comment by danysantiago** [comment]
Please do try the latest stable version and let us know if you still have an issue. I'll close this for now, but feel free to re-open.
