### ISSUE TITLE
Hilt 2.38 @AndroidEntryPoint/@HiltAndroidApp transform doesn't run on non-test code on AGP 7+

### ISSUE THREAD

**Issue by Chang-Eric** [google/dagger#2784]
A bug in 2.38 is causing the bytecode transform to miss non-test code when running on AGP 7+. This causes the base class of those `@AndroidEntryPoint` types to remain the declared base class as opposed to the Hilt one, which means injection won't occur on these classes. This is unfortunately generally a runtime error.

A fix will be coming shortly as well as a patch release 2.38.1 to fix this.

**Comment by Chang-Eric** [comment]
Leaving this open until 2.38.1 goes out.

**Comment by Chang-Eric** [comment]
2.38.1 has been released now, so closing this.

**Comment by kevinbowie** [comment]
thank you now it works. mine now is kotlin 1.5.21 and hilt 2.38.1
