### ISSUE TITLE
EarlyComponent is not created if test contains @BindValue

### ISSUE THREAD

**Issue by ReginFell** [google/dagger#2789]
In our project we have a `Service` which is init automatically. 

```
class PushNotificationService : FirebaseMessagingService() {
    
    @EarlyEntryPoint
    @InstallIn(SingletonComponent::class)
    interface PushNotificationServiceInterface {   }

    override fun onMessageReceived(message: RemoteMessage) {
       EarlyEntryPoints.get(application, PushNotificationServiceInterface::class.java) <-- Crash here
    }
}
```

And test

```
@HiltAndroidTest
class Journey {

   @get:Rule
    val rule = RuleChain.outerRule(HiltAndroidRule(this))
        .around(ActivityScenarioRule(MainActivity::class.java))

   @BindValue val userRepository = mock<UserRepository>()

   @Test
    fun test() {
    }
}
```

And in gradle we add `kaptAndroidTest(hilt)`

In this case if we run the test we receive:
> The EarlyComponent was requested but does not exist. Check that you have annotated your test class with @HiltAndroidTest and that the processor is running over your test.

But if we remove the @BindView
```
@HiltAndroidTest
class Journey {

    @get:Rule
    val rule = RuleChain.outerRule(HiltAndroidRule(this))
        .around(ActivityScenarioRule(MainActivity::class.java))

    @Test
    fun test() {
    }
}
```

Everything works as expected and `EarlyComponent` can be retrieved.

**Comment by bcorso** [comment]
Hi @ReginFell,

Sorry, I couldn't reproduce this locally. Is it possible for you to create an example project that reproduces the issue?

(Also, on an unrelated note, you may want to read the warning about using `ActivityScenarioRule` with `@BindValue` in https://dagger.dev/hilt/testing#bind-value).

**Comment by ReginFell** [comment]
@bcorso yeah sure. 
https://github.com/ReginFell/HiltEarlyComponentIssue 

To reproduce you can run 
`com.regin.earlycomponentissue.HiltEarlyComponentIssueTest`

For me when I run the test, `PushNotificationService.onNewToken()` throws 
>  java.lang.RuntimeException: The EarlyComponent was requested but does not exist. Check that you have annotated your test class with @HiltAndroidTest and that the processor is running over your test.

**Comment by bcorso** [comment]
Thanks for the repro case! 

I was able to reproduce this issue. I'll have a fix out shortly, but you'll have to wait until the next Hilt release to get it.

Fwiw, this only happens when all of your tests have test-specific bindings (e.g. an `@BindValue`). Thus, a quick workaround is to add an empty test with no `@BindValue` in the same source set, for example:

```kotlin
// This test can be removed with the next Hilt release,
// which contains the fix for https://github.com/google/dagger/issues/2789
@HiltAndroidTest
class EmptyTest {}
```
