### ISSUE TITLE
Field injection way does not take effect, but inject-constructor way takes effect

### ISSUE THREAD

**Issue by gkj17** [google/dagger#2792]
As the description in https://stackoverflow.com/questions/68587320/how-to-generate-objects-with-the-same-type-in-hilt/68587530?noredirect=1#comment121213142_68587530

Field injection way does not take effect, but inject-constructor way takes effect

**Comment by Chang-Eric** [comment]
Hm, I tested something similar locally and it worked, so not sure what you ran into. `@Inject` fields should be set automatically if you have and use the `@Inject` constructor, so assuming you actually used the `@Inject` constructor on the class then it should be working.

I would need a stack trace or more information to help more, but my first guess is that maybe somehow your object might have been created not via Dagger or some other method and that is why the `@Inject` field wasn't being initialized.
