### ISSUE TITLE
Please add cache relocation test for `enableAggregatingTask = true`

### ISSUE THREAD

**Issue by runningcode** [google/dagger#2794]
I've noticed cache misses in several projects which are fixed by disabling `enableAggregatingTask`. Please add cache relocation tests for when this option is enabled. 

The existing `BuildCacheTest` can be expanded to cover this use case. https://github.com/google/dagger/pull/2775/files#diff-6748517e7c4360a2427fe486b2fe82ce30a53a2b0f29d2b2361de41a3bb665bd

**Comment by runningcode** [comment]
See https://github.com/google/dagger/issues/2795 for more information about the cache relocateability issue.

**Comment by danysantiago** [comment]
Added a test, closing this issue but will keep https://github.com/google/dagger/issues/2795 open to further investigate cache miss when `enableAggregatingTask = true`
