### ISSUE TITLE
[Hilt] warning: No processor claimed any of these annotations: dagger.hilt.internal.processedrootsentinel.ProcessedRootSentinel,dagger.hilt.internal.componenttreedeps.ComponentTreeDeps

### ISSUE THREAD

**Issue by sergeys-opera** [google/dagger#2796]
I'm getting a warning while compiling a project with the latest Hilt and AGP:
```
warning: No processor claimed any of these annotations: dagger.hilt.internal.processedrootsentinel.ProcessedRootSentinel,dagger.hilt.internal.componenttreedeps.ComponentTreeDeps
```
Hilt version: 2.38.1
AGP: 7.0.0
Gradle: 7.0.2

**Comment by sergeys-opera** [comment]
A simple workaround is to suppress the aforementioned warning via a compile flag: `options.compilerArgs << '-Xlint:-processing'`

**Comment by Chang-Eric** [comment]
As far as I can tell, suppressing that warning with that flag is really the only solution. We try not to claim annotations in general because it prevents other processors from potentially running over them.
