### ISSUE TITLE
@SuppressWarnings("dependency-cycle") does nothing

### ISSUE THREAD

**Issue by pyricau** [google/dagger#280]
Following up to #277 where @netdpb suggested I could use @SuppressWarnings("dependency-cycle") .

I haven't been able to make this work, with the latest snapshot.

I starting by using `@SuppressWarnings("dependency-cycle")` on some objects class, then on each of their injected dependency on the constructor, then on the return type of module provider methods. Then I added it next to all `@Component` and `@Subcomponent` annotations. Then I added it next to all component provision methods that were at the source of the warning. Still no luck.

The warnings are repeated several times in the output.

One thing to note is that those warnings are due to cycles introduced by the dev graph, but the roots are declared in a subcomponent defined in a super interface.

```
interface AppGraph {
  SubGraph subgraph():
}
@SubComponent SubGraph {
  SomeDependencyWithCycles dep();
}

@Component
interface DevGraph extends AppGraph {
}
```

**Comment by pyricau** [comment]
Ping @netdpb since you suggested that.

**Comment by ericvaldezz** [comment]
Sorry I don't know wat un doin
On Jan 18, 2016 4:56 PM, Pierre-Yves Ricau <notifications@github.com> wrote:Ping @netdpb since you suggested that.

**Comment by ronshapiro** [comment]
This warning was removed in 8f14c79b236891f1aa242306daf91fe5ef0b1fe9
