### ISSUE TITLE
Feature request: Support KSP in SPI.

### ISSUE THREAD

**Issue by Jeffset** [google/dagger#2802]
Tracking issue for the status and decision of supporting KSP types in [dagger-spi](https://dagger.dev/dev-guide/spi.html).
Are there any plans for directly supporting that? Or maybe we can provide some kind of parallel `dagger-spi-ksp` which will have similar API yet utilize KSP types?

**Comment by bcorso** [comment]
Closing. We'll keep track of this as part of #2349, since support for KSP in SPI will go hand-in-hand with support for KSP in Dagger.
