### ISSUE TITLE
kapt error while running gradlew test

### ISSUE THREAD

**Issue by salmansynavos** [google/dagger#2818]
hilt version: 2.38.1

stack trace
https://scans.gradle.com/s/d3y35e33j7uj2

**Comment by danysantiago** [comment]
There is no Hilt or Dagger package / classes shown in the stacktrace. What information makes you think this is a Dagger or Hilt issue? Can you provide us with a [reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)?

**Comment by salmansynavos** [comment]
Because If I remove hilt dependency, command runs successfully. 
BTW I resolved this issue by adding following line in gradle.properties.
`org.gradle.jvmargs= --illegal-access=permit`  

Actually issue was with kotlin compatibility
I resolved by it by following this [link](https://youtrack.jetbrains.com/issue/KT-45545)
