### ISSUE TITLE
Android Tests failing when using Hilt caused by ClassCastException

### ISSUE THREAD

**Issue by Eleftheria-99** [google/dagger#2824]
I have been writing kotlin code for android apps for quite some time, but I decided to also start writing testing code too for my apps. I have been facing some problems though with the use of Hilt. What I tried is :

`import android.app.Application
    
    open class AbstractApplication: Application()`

` @HiltAndroidApp
    class IgmeApplication : IgmeAbstractApplication() {  
    
      @Inject
      lateinit var authenticationManager: AuthenticationManager

             ....
}`

and then in the Android Test Directory:

` import dagger.hilt.android.testing.CustomTestApplication
    
    @CustomTestApplication(AbstractApplication::class)
    open class HiltTestApplication
`
`    import android.app.Application
    import android.content.Context
    import androidx.test.runner.AndroidJUnitRunner
    
    class HiltTestRunner : AndroidJUnitRunner() {
    
        override fun newApplication(
            cl: ClassLoader?,
            className: String?,
            context: Context?
        ): Application {
            return super.newApplication(cl,HiltTestApp::class.java.name, context)
        }
    }
`

my Test class :

`   @HiltAndroidTest
    class AuthenticationTest{
    
        @get:Rule
        var hiltRule = HiltAndroidRule(this)
    
        @Test
        fun useAppContext() {
            // Context of the app under test.
            val appContext = InstrumentationRegistry.getInstrumentation().targetContext
            Assert.assertEquals("com.crowdpolicy.onext.igme", appContext.packageName)
        }
    
        @Before
        fun setUp() {
            // Populate @Inject fields in test class
            hiltRule.inject()
        }
    
        @After
        fun tearDown() {
        }
    }

`
my app level gradle file :

`// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    ext.kotlin_version = "1.5.20"
    ext.google_version = '4.3.4'
    ext.timberVersion = '4.7.1'
    ext.event_bus = '3.2.0'
    ext.gson_version = '2.8.6'
    ext.retrofit2_version = '2.9.0'
    ext.datastore_version = '1.0.0-rc02'
    ext.rxkotlin_version = '3.0.1'
    ext.rxandroid_version = '3.0.0'
    ext.lifecycle_version = '2.3.1'
    ext.dagger_version = '2.37'
    ext.hilt_version = '2.37'
    ext.hilt_fragment_version = '1.0.0'
    ext.nav_version = '2.3.5'
    ext.fragment_version = '1.3.6'
    ext.androidXTestCoreVersion = '1.4.0'
    ext.espresso_version = '3.4.0'
    ext.lottie_version = '3.6.1'
    ext.facebook_version = '9.0.0'
    ext.protobuf_version = '3.15.8'
    ext.protobuf_gradle_plugin_version = '0.8.16'

    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath "com.android.tools.build:gradle:4.2.2"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath "com.google.gms:google-services:$google_version"
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.7.1'
        classpath 'com.google.firebase:perf-plugin:1.4.0'
        classpath "androidx.navigation:navigation-safe-args-gradle-plugin:$nav_version"
        classpath "com.google.dagger:hilt-android-gradle-plugin:$hilt_version"
        classpath "com.google.protobuf:protobuf-gradle-plugin:$protobuf_gradle_plugin_version"

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        jcenter() // Warning: this repository is going to shut down soon
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}`

I followed the official documentation from dagger-hilt in this page : https://dagger.dev/hilt/testing.html, but I am still getting this error :

`    Caused by: java.lang.ClassCastException: com.crowdpolicy.onext.igme.HiltTestApplication cannot be cast to android.app.Application
     at android.app.Instrumentation.newApplication(Instrumentation.java:997)
            at android.app.Instrumentation.newApplication(Instrumentation.java:982)
            at com.crowdpolicy.onext.igme.HiltTestRunner.newApplication(HiltTestRunner.kt:14)
            at android.app.LoadedApk.makeApplication(LoadedApk.java:617)`

and I do not know how to fix it, because I am really new to testing and it is the first time facing it ! line 14 in HIltTestRunner is : return super.newApplication(cl,HiltTestApp::class.java.name, context)

**Comment by danysantiago** [comment]
Hey - The instructions regarding custom test application should be able to help you: https://dagger.dev/hilt/testing.html#custom-test-application

Specifically in your `HiltTestRunner` you want to use Hilt's generated test application that extends your base, like this:
```
class HiltTestRunner : AndroidJUnitRunner() {

    override fun newApplication(
        cl: ClassLoader?,
        className: String?,
        context: Context?
    ): Application {
        return super.newApplication(cl, CustomTest_ApplicationHilt::class.java.name, context)
    }
}
```
the name of the generated class `CustomTest_ApplicationHilt` will be based on the class the annotation is placed on:
```
@CustomTestApplication(AbstractApplication::class)
object CustomTest
```
