### ISSUE TITLE
dagger-spi depends on a deleted dependency (com.google.devtools.ksp:symbol-processing-api:1.5.20-1.0.0-beta03)

### ISSUE THREAD

**Issue by perezd** [google/dagger#2830]
It exists, but if you look at the files, they are 404ing.
https://mvnrepository.com/artifact/com.google.devtools.ksp/symbol-processing-api/1.5.20-1.0.0-beta03

The dependencies for 2.38.1 point to this and should be updated:
https://mvnrepository.com/artifact/com.google.dagger/dagger-spi/2.38.1

This probably warrants a hotfix, unfortunately.

**Comment by danysantiago** [comment]
The KSP dependency is in the [Google Maven repo](https://maven.google.com/web/index.html?q=ksp#com.google.devtools.ksp:symbol-processing-api) did you try adding the repository?

This was mentioned in the release notes of 2.38: https://github.com/google/dagger/releases/tag/dagger-2.38.

Note there is an existing issue to upload KSP to maven central: https://github.com/google/dagger/issues/2779

**Comment by perezd** [comment]
derp! I missed that, thanks!
