### ISSUE TITLE
Hilt ignores Suppress class annotations when generating code

### ISSUE THREAD

**Issue by kubak89** [google/dagger#2834]
When a class is annotated with `@AndroidEntryPoint` annotation the generated class doesn't have `@Suppress` annotation the original class has.

## Steps to reproduce:

- Create an android entry point class inheriting from a deprecated class and annotate it with `@Suppress("deprecation")`, e.g.
``` Kotlin
@AndroidEntryPoint
@Suppress("deprecation")
class FooService : JobIntentService() { ... }
```
- Build project

## Expected result
Generated class retains `@Suppress` annotation and no warnings are raised during build.

## Actual result
Generated class doesn't have `@Suppress` annotation and warning is raised during the build process, e.g.
``` Java
/**
 * A generated base class to be extended by the @dagger.hilt.android.AndroidEntryPoint annotated class. If using the Gradle plugin, this is swapped as the base class via bytecode transformation.
 */
public abstract class Hilt_FooService extends JobIntentService implements GeneratedComponentManagerHolder { ... }
```
with warning produced during build:
```
/<generated sources location>/Hilt_FooService.java:4: warning: [deprecation] JobIntentService in androidx.core.app has been deprecated
import androidx.core.app.JobIntentService;
```

**Comment by kubak89** [comment]
I've also tried to use `@Suppress` annotation before `JobIntentService()` constructor call like shown below, but that also didn't help

``` Kotlin
class PushNotificationService : @Suppress("deprecation") JobIntentService() { ... }
```

**Comment by wanyingd1996** [comment]
Hi, a change supports copying the Suppress annotation will be shipped in a day or two.
