### ISSUE TITLE
[Hilt] It would be nice to have NavGraphComponent @NavGraphScoped in the Hilt.

### ISSUE THREAD

**Issue by Dimowner** [google/dagger#2836]
Problem:
I have some dependencies that need to be scoped to a navGraph. So when I finish the navGraph I want to clear all my dependencie scoped to that navGraph. 

It would be nice to have something like NavGraphComponent and @NavGraphScoped which will do it automatically.

Is there way how can I scope my dependencies to a navGraph in current version of Hilt without custom components?

**Comment by danysantiago** [comment]
You can use the `ViewModelComponent` and scope to create a ViewModel in the `NavBackStackEntry` such when navigating away the ViewModel along with its dependencies will be cleaned up.

See: https://developer.android.com/training/dependency-injection/hilt-jetpack#viewmodel-navigation

**Comment by danysantiago** [comment]
Here is more info on `ViewModelComponent`: https://medium.com/androiddevelopers/using-hilts-viewmodelcomponent-53b46515c4f4

But its away to scope dependencies within the ViewModel and then let the owner of the ViewModel (activity, fragment or nav back stack entry) control the lifecycle of it along with its injected dependencies.
