### ISSUE TITLE
[Hilt] Failed to apply plugin 'dagger.hilt.android.plugin' / AGP 7.0.x / Hilt 2.38.1

### ISSUE THREAD

**Issue by mkubiczek** [google/dagger#2847]
When trying to apply hilt gradle plugin in project using AGP 7.0.x following error is thrown

> Failed to apply plugin 'dagger.hilt.android.plugin'.
   > Extension of type 'AndroidComponentsExtension' does not exist. Currently registered extension types: [ExtraPropertiesExtension, DefaultArtifactPublicationSet, SourceSetContainer, ReportingExtension, JavaPluginExtension, JavaToolchainService, NamedDomainObjectContainer<BaseVariantOutput>, BaseAppModuleExtension, ApplicationAndroidComponentsExtension, CrashlyticsExtension, DownloadExtension, VerifyExtension, KaptExtension, KotlinAndroidProjectExtension, KotlinTestsRegistry, DetektExtension, HiltExtension]

This works when switching to APG 7.1.0-alpha02 but not with any newer ones.

**Comment by danysantiago** [comment]
I'm not able to reproduce this in a simple new Kotlin project with AGP 7.0.2, Hilt 2.38.1 and Kotlin 1.5.21.

Can you please share your build.gradle files, or a repro project?

**Comment by mkubiczek** [comment]
I found the reason. In my case I had older version of AGP set in buildSrc (for some reason this dependence was needed there). Getting rid of it fixed the issue.
