### ISSUE TITLE
Dagger in android library

### ISSUE THREAD

**Issue by slashnext1** [google/dagger#2852]
Hi i am using dagger in android library. I need to implement HasAndroidInjector in my library to inject some android components(receiver, worker etc) but this interface need to be implemented in Application class and since its library and sdk I can not use the Application class because if I use application class I am restricting the client app using my SDK to use dagger and I don't want this. Does any one has any idea about this?

**Comment by bcorso** [comment]
As you noted, using [`dagger.android`](https://dagger.dev/dev-guide/android#daggerandroid) requires some degree of setup in the `Application` class, which would push the `dagger.android` dependency to your users. Unfortunately, there's no way around that requirement with `dagger.android`, so I wouldn't recommend it for libraries.

You can use plain Dagger to define your own components and perform your own injection in your library; however, you'd still want to expose it in a way that's independent of Dagger.
