### ISSUE TITLE
Verifying null safety for provider methods from generated code

### ISSUE THREAD

**Issue by LikeTheSalad** [google/dagger#2853]
Hi!

I was wondering if it is possible to do the null check inside the generated code for a provider method, **without having to reference an external class** (Preconditions) to do so?

The reason I'm asking is because I've been having issues with using Dagger within a Gradle plugin I'm developing. In order to use said plugin in another Gradle project, I need to add it to the target project's classpath dependencies first, and for some reason, after doing so I was getting this crash when applying it:

```
Unable to find method ''java.lang.Object dagger.internal.Preconditions.checkNotNullFromProvides(java.lang.Object)''
'java.lang.Object dagger.internal.Preconditions.checkNotNullFromProvides(java.lang.Object)'
```

It seems like these kind of crashes are not uncommon, the ones that involve the lack of the "Preconditions" class at runtime, and the kind of "solutions" that people seem to come up with usually involve:

* Adding dagger as a dependency of the consumer of a library that uses dagger internally.
* Some times I've seen people talking about adding Guava too, since apparently the Preconditions make use of Guava.
* Creating "fat jars" so that there's no need for the consumer to add any other dependency.

Those options don't seem to be optimal for different reasons, the first 2 are just annoying to end users, if I develop a library, I would like to make it easy to use and it doesn't seem like suggesting users to include my library's dependencies into their projects might sound good in that sense, let alone that in the case they would actually have to add a library like Guava for example, they'll be increasing their app size by quite a lot, which might be a problem in many cases. The last option seems to take the end user set up issues away, but still leaves the app size one, plus the extra configuration needed for the developer of the library in order to put a fat jar only with Dagger's, and probably its dependencies, code together.

And after giving a thought about all of these things, I was ultimately thinking if all of this trouble is actually worth it over checking if a provided value is not null?

Based on the DRY principle, it is wrong to to duplicate code all over the place in a project and instead it is best to place the common code somewhere else and reuse it when needed, this would prevent developers from having to repeat the same fixes and improvements to the code. However, it doesn't seem to be necessary when there's no human interaction with the code, as it happens with Dagger's generated classes.

So that's why I was wondering if it could be possible to add the code that makes the null checks into the generated classes that need it? - I think it could help a lot to prevent these kinds of issues, and it shouldn't mean any sort of violation to best practices, as the generated code won't be modified by humans :)

BTW, I was able to avoid this issue by annotating all my provider methods with `@Nullable`, so that Dagger wouldn't add the "Preconditions.checkNonNullFromProvides" line. But in the end it wasn't an ideal solution because, since I'm using Kotlin, I'd then have to inject my dependencies as nullables, or wrapped in a "Provider<>", which brought a lot of issues in terms of the amount of code needed to be changed, unit tests broken and lots of questions in PRs.

I know it's a quite big chunk of text, sorry about it 😅 but thanks for taking the time to read it.

Cheers!

**Comment by bcorso** [comment]
Sorry, I don't think this is feasible.

IIUC, the issue you're describing is more about how to bundle dependencies in your Gradle plugin rather than anything specific to Dagger (as this would happen for any dependency your plugin uses, not just Dagger), and I don't think asking Dagger's generated code to avoid depending on Dagger code is an acceptable solution. Typically, you would solve your issue by 
   
  1) using something like POM file that lists the required dependencies that will be managed by your build system (e.g. Maven/Gradle), or 
  2) package your library as a fat jar that bundles all of your dependencies (as you've stated above). 

Option 1 is likely what you want.

>  it doesn't seem like suggesting users to include my library's dependencies into their projects might sound good in that sense, let alone that in the case they would actually have to add a library like Guava for example, they'll be increasing their app size by quite a lot, which might be a problem in many cases

[`Preconditions`](https://github.com/google/dagger/blob/master/java/dagger/internal/Preconditions.java) is our own class within Dagger, so pulling in Guava is not a real concern.

> Based on the DRY principle, it is wrong to to duplicate code all over the place in a project and instead it is best to place the common code somewhere else and reuse it when needed, this would prevent developers from having to repeat the same fixes and improvements to the code. However, it doesn't seem to be necessary when there's no human interaction with the code, as it happens with Dagger's generated classes.

We don't just use `Preconditions` to obey the DRY principle, it's also to reduce the size of the generated code. It may seem small individually, but when used for 1000s of bindings across an app it can add up.
