### ISSUE TITLE
Is there any plan that support DFM compilation for Hilt?

### ISSUE THREAD

**Issue by SinoReimu** [google/dagger#2856]
Hi!
    Currently Hilt collect generate all code with Application (such as ActivityCImpl、ApplicationCImpl...) but of course this class cannot access code in DFM code. Also, annotationProcessor in app module will not process the annotation in DFM. We do need to use DFM for feature delivery, should we fallback to use dagger injection?

Thanks!

**Comment by Chang-Eric** [comment]
Yea, the current guidance for DFM is to use component dependencies. You can find a guide for that here: https://developer.android.com/training/dependency-injection/hilt-multi-module#dfm
