### ISSUE TITLE
@HiltAndroidTest annotation is not @Inherited

### ISSUE THREAD

**Issue by schmecs** [google/dagger#2867]
It would be helpful to allow inheritance of the @HiltAndroidTest annotation so that developers could configure base unit test classes that include Hilt.

**Comment by Chang-Eric** [comment]
I think the main complication here is that right now we associate nested test modules and `@BindValue` calls with the specific test, so it could add extra complexity to treat those correctly if they appear in the base class.

Does it not being inherited cause a particular problem for you or is this mostly to save on annotating the child classes?

**Comment by schmecs** [comment]
I see. It would just be for the latter convenience -- we've been upgrading a large Robolectric test suite from Dagger 1 to Hilt and trying to save on boilerplate. Not actively causing any issues.

**Comment by Chang-Eric** [comment]
Thanks for the clarification. I think realistically we're unlikely to make this change due to the added complexity with test modules and the test infra, so I'm going to close this. Thanks for the suggestion though!
