### ISSUE TITLE
Make Dagger 2 not a fork of Dagger 1

### ISSUE THREAD

**Issue by gk5885** [google/dagger#291]
Apparently this causes a variety of issues and requires some intervention from GitHub directly.  This is the tracking bug.

**Comment by gk5885** [comment]
I heard back from GitHub support person.  It seems we have the option of either unforking or just leaving it a fork and enabling code search.  Does anybody have a compelling argument for one or the other?

**Comment by gk5885** [comment]
Nobody seemed to have an opinion, so I've asked them to start by just enabling search.

**Comment by gk5885** [comment]
I've been told that this has now been enabled, so I'm closing the bug.

**Comment by ronshapiro** [comment]
https://github.com/search?utf8=%E2%9C%93&q=AbstractComponentWriter&type=Code&ref=searchresults :+1:
