### ISSUE TITLE
"android:exported needs to be explicitly specified for <activity>" when targeting Android 12

### ISSUE THREAD

**Issue by ampeixoto** [google/dagger#2910]
When upgrading my codebase to target Sdk 31, the compilation of my tests started failing due to the fact that the dependency `com.google.dagger:hilt-android-testing:2.39.1` depends on `androidx.test:core-ktx:1.3.0`, which turns out is not ready to target sdk 31.

It seems that `androidx.test:core-ktx:1.4.0` [already is](https://stackoverflow.com/a/67668116).

My workaround is to declare the `androidx.test:core-ktx` library with the updated version into all modules that also depend on  `com.google.dagger:hilt-android-testing`, like:
```
testImplementation com.google.dagger:hilt-android-testing:2.39.1
testImplementation androidx.test:core-ktx:1.4.0
```
The problem with this is that I have to do it in a bunch of modules.

Is there another solution?

**Comment by danysantiago** [comment]
The more proper way to upgrade a transitive dependency is to add a constraint, see Gradle's documentation: https://docs.gradle.org/current/userguide/dependency_constraints.html

From our side we'll update Hilt's dependencies so this is eventually not needed.
