### ISSUE TITLE
[Help] @ApplicationContext not provided automatically in ViewModel?

### ISSUE THREAD

**Issue by chakflying** [google/dagger#2918]
So I'm using Hilt + Jetpack Compose, and I'm trying to access the application context in my viewModel.

**ViewModel**
```kotlin

@HiltViewModel
open class MyViewModel @Inject constructor(
    @ApplicationContext application: Context,
) : BaseViewModel() {
//  ...
```

**MainActivity.kt**
```kotlin

@AndroidEntryPoint
class MainActivity : ComponentActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
// ...

@Composable
fun MyPlaceholder(
    viewModel: MyViewModel = viewModel()
) {
// ...
```

This crash the app with
```
java.lang.InstantiationException: java.lang.Class<com....MyViewModel> has no zero argument constructor
```

So The application context is not provided automatically, and I need to add a module with `@Provides`?

hilt_version  `2.38.1`
compose_version `1.0.3`

**Comment by danysantiago** [comment]
Using `@ApplicationContext application: Context` should work.

It looks like you `@HiltViewModel` is not being picked up by Hilt and is not being added to the multibinding of injected view models. Is your `MyViewModel` in a deep gradle module and is an `implementation` dependency? Can you try enabling [`enableAggregatingTask`](https://dagger.dev/hilt/gradle-setup#aggregating-task)?

**Comment by chakflying** [comment]
I ended up trying
```kotlin
fun MyPlaceholder(
    viewModel: MyViewModel = hiltViewModel()
) {
```
and it seem to have worked. I guess if your composable is inside a `NavHost()`,  you have to use `hiltViewModel()` instead of `viewModel()`. So much for days of debugging!
