### ISSUE TITLE
Providing generic interfaces on modules

### ISSUE THREAD

**Issue by gabrielhuff** [google/dagger#2977]
Consider the following code (which works fine):

```kotlin
@Component
interface MyComponent {
    val foo: Foo
}

class Foo @Inject constructor(bar: Bar<Int>)
class Bar<T> @Inject constructor()
```

Now, say I want to make `Bar` an interface instead of a class. In this case I'd need to create a module that provides `Bar` instances and then add it to my component:

```kotlin
@Component(modules = [MyModule::class])
interface MyComponent {
    val foo: Foo
}

@Module
abstract class MyModule {
    @Binds abstract fun <T> bar(impl: BarImpl<T>): Bar<T>
}

class Foo @Inject constructor(bar: Bar<Int>)
interface Bar<T>
class BarImpl<T> @Inject constructor() : Bar<T>
```

However, the above does not work. The dagger compiler fails with:

```
error: @Binds methods may not have type parameters
    public abstract <T extends java.lang.Object>com.example.Bar<T> bar(@org.jetbrains.annotations.NotNull()
```

As seen on the first snippet,  `@Inject` allows Dagger to provide any type of `Bar<T>` (e.g. `Bar<Int>`). **Is it possible to achieve the same result with `@Binds`?** In case it's not, what's the recommended workaround?

I've tried different things: using `@Provides` instead of `@Binds`; using generic wildcards; using Java raw types. None seemed to work.

**Comment by bcorso** [comment]
This sounds like a dupe of https://github.com/google/dagger/issues/1757,  which unfortunately I haven't had time to get to.

For now, you would have to have an `@Binds` for each type:

```
@Module
abstract class MyModule {
    @Binds abstract fun barInt(impl: BarImpl<Int>): Bar<Int>

    @Binds abstract fun barString(impl: BarImpl<String>): Bar<String>
}
```

**Comment by gabrielhuff** [comment]
Yeah, definitely a dupe. The workaround makes sense, thanks for letting me know!
