### ISSUE TITLE
Gradle's incremental build feature breaks annotation processing

### ISSUE THREAD

**Issue by sockeqwe** [google/dagger#298]
Gradle has this incremental build feature to speed up build times (especially useful on android). The problem with incremental builds is that the annotation processor will only run for those classes who has been changed and not for the whole project / source files.

In other words: 
`env.getElementsAnnotatedWith(...)`  only returns annotated classes that has been changed since previous incremental build. This means that the whole project can't be evaluated and components can't be generated.

I know it's not your fault! I think that there isn't much that you can do. The only thing that comes to my mind is to add some reflection code to glue all together at runtime, but who really wants that ... 

I just have created this issue for others (mainly android developers) who struggle with this kind of issue as well. In android you can disable this incremental build feature as follows:

``` groovy
dexOptions {
    incremental false
}
```

**Comment by ronshapiro** [comment]
Even if you tried the reflection glue (and I did on a side project last week), you will have issues if you change any code that should cause dagger code to generate different output (but not the component itself). It would be great to get someone that's familiar with the incremental compilation step, but as you said, I don't know (at least with my current set of knowledge about this) what we can do, and ideally this is something that could be solved at the build level so that every annotation processor would get this support.

**Comment by sockeqwe** [comment]
The best way would definitely be scanning the whole project again on incremental builds. As far as I know annotation processing can also scan `.class` files (`RetentionPolicy.RUNTIME`), **but** you have to add them manually to `javac` when compiling. I have never done that, but it should work. So I think gradle incremental build have to add all other already compiled `.class` files to `javac` when compiling the incremental build ...

**Comment by aurae** [comment]
For me, Hannes' suggestion to disable incremental dex didn't resolve the issue, which is why I had to disable incremental builds a little higher up the compilation chain, as suggested by [this guy](http://stackoverflow.com/a/35060462/2776126).

Running Gradle with the following command line option caused Dagger's annotation processor to work properly again:
```
-Pandroid.incrementalJavaCompile=false
```

**Comment by hzsweers** [comment]
@aurae that's what Tor Norbye suggested to me as well and has worked for me. He said they're considering controlling the incremental flag for recognized processors in the future.

**Comment by gk5885** [comment]
I just talked with Tor and the next beta is going to make sure that incremental compilation is turned off for project that use Dagger, so it should at least be better in Android Studio.  We're also going to raise the issue with the Gradle folks and see what they have to say.

**Comment by arriolac** [comment]
@gk5885 Shouldn't the solution apply to all projects using annotation processing? Or is this only a dagger-specific problem?

**Comment by tbroyer** [comment]
It's not specific to Dagger, but many annotation processors are much simpler, and I think it could work with 1:1 mappings between input and output classes.
Anyway, @gk5885, if you have a link to a Gradle issue please add it here. I believe this problem has been solved in Pants where they (try to) map inputs to outputs and persist this mapping for next rounds.

**Comment by gk5885** [comment]
@arriolac, I believe that they selected some list of annotation processors that they knew to have problems.  I don't have any details, but I know that it was addressed for Dagger and some others.

@tbroyer Some people from the Android tools side of things are going to discuss it in their regular sync with the Gradle people.  I don't have any details, but they're going to report back when they talk it over.

**Comment by edisonw** [comment]
This is not a dagger-specific problem, it affects all annotation processors, some are fixable and some are not, for example, I had to do the following for an example project that I maintain: 

1. Fixable: https://github.com/edisonw/PennStation/commit/c32b43ce7952295ef53560973aaed6561a398655

2. Needs Refactoring: https://github.com/edisonw/PennStation/commit/c1fd0692d0726ff931ac1fc1fc242999e6df0a3e

**Comment by cesar1000** [comment]
Any updates on this? It doesn't look like Android Studio or Gradle are modifying their behavior when dagger is used. I am disabling incremental compilation explicitly in projects that use Dagger, but it would be nice if this would happen automatically.

**Comment by ronshapiro** [comment]
I would file those issues with the tools issue trackers, not with dagger. Not much we can do on that end.

**Comment by cesar1000** [comment]
Sure - I asked because of @gk5885's comment from February 4th that mentioned that Android Studio would fix in an upcoming beta. Recent changes to gradle seem to have make it worse, but I only have anecdotal evidence.

**Comment by ronshapiro** [comment]
The sense that I get is that http://tools.android.com/tech-docs/new-build-system/2-5-alpha-gradle-plugin will be addressing this. Either way, there is little that Dagger can do here
