### ISSUE TITLE
Using hilt in libraries

### ISSUE THREAD

**Issue by mattinger** [google/dagger#3007]
Is it possible to use the hilt gradle plugin and @AndroidEntryPoint in a library, generate and publish the .aar, and then plug it into a hilt app somewhere later on?

It's kind of unclear to me if this is even possible.  I think mostly it's the @AndroidEntryPoint that i'm unsure of.  I would hope that the annotation processor would pick up on the @InstallIn in the classpath though.  Is the same true for @AndroidEntryPoint

**Comment by danysantiago** [comment]
Yes - `@AndroidEntryPoint` in essence generates an `@EntryPoint` with a `@InstallIn` that will get picked up at the root where `@HiltAndroidApp` is and thus will enable injection of library fragments and activities annotated with `@AndroidEntryPoint`.
