### ISSUE TITLE
While enable R8 for release build, hilt inject wrong type for member variable - HILT-2.40.1

### ISSUE THREAD

**Issue by ray26** [google/dagger#3062]
In debug build, there is no problem for my app. But when isMinifyEnabled = true, I have got an ClassCastException, View after unlocking the apk, I saw @inject got a wrong type
This is the dex file type
![image](https://user-images.githubusercontent.com/6435613/142967787-240b4141-8c2f-4f9e-a360-ea8f131b07ec.png)
I have got a CurrentDevicAdapter
But in the source file, it should be DeviceInfoAdapter
![image](https://user-images.githubusercontent.com/6435613/142967852-10331783-0d7f-4c4c-8155-05a6f3589f2e.png)
I have no idea why this problem will occur
I have checkd the mid product for hilt in outputs folder, it is the right type
![image](https://user-images.githubusercontent.com/6435613/142967955-e266bbdc-ba94-4604-a90b-0511c2a749e9.png)

**Comment by ray26** [comment]
I just resolve it by adding @Keep annotation for the right adapter

**Comment by danysantiago** [comment]
Glad you were able to solve the issue but if you think this is still an issue you should file a bug to the R8 / Proguard team here: https://issuetracker.google.com/issues?q=componentid:326788. R8 has optimizations to merge interfaces and reduce classes so it might be related to that.

**Comment by ray26** [comment]
> https://issuetracker.google.com/issues?q=componentid:326788

Got it, I will report this to R8 team
