### ISSUE TITLE
[Bug] Naming conflict when dependency is named "Create"

### ISSUE THREAD

**Issue by richarddd** [google/dagger#3069]
Dagger generates invalid code when an injected dependency is named "Create.java" or "Create.kt"

```java
  public static ExampleComponent create() {
    return new Builder().build();
  }

  private Create create() {
    return new Create(ExampleModule_ProvideExampleDependencyFactory.provideExampleDependency(exampleModule));
  }
```

`'create()' is already defined ...`

The private method should be renamed to something other than our dependencies to avoid the name conflict.

Reproducable repo here:
https://github.com/richarddd/dagger-name-conflict

It could be sovled by postfixing the method with a hash value like `hex(fletcher32(canonicalName))` or by adding a dagger prefix. Examples:

```java
private Create daggerCreateCreateDependency() {...}
```

```java
private Create createb886c8a7() {...}
```

**Comment by JakeWharton** [comment]
Using NameAllocator for the method names would solve it as well.
