### ISSUE TITLE
savedStateHandler is empty when I use hiltNavGraphViewModels

### ISSUE THREAD

**Issue by haniyehkhaksar** [google/dagger#3101]
in migration to hilt, first I used viewModels() to delegate my viewModels and it was ok with savedStateHandle, I got my args. but then since I have fragments inside navGraph, I decided to change delegation way and start using hiltNavGraphViewModels(), now savedStateHandle is empty.

**Comment by danysantiago** [comment]
Can you please provide more details? Specifically a sample project that reproduces the issue. See https://stackoverflow.com/help/minimal-reproducible-example for more info.

**Comment by bcorso** [comment]
Closing this, but feel free to reopen if you are still having this issue and have more information you can provide.
