### ISSUE TITLE
Any way to make the factory impl class not final

### ISSUE THREAD

**Issue by doukai** [google/dagger#3112]
hi,
any idea about make the facotry impl class not final,
because I want to extends the generated class in my own annotation processor
any config can do it?
thanks~

**Comment by JakeWharton** [comment]
Why not use composition and implement the original interface but delegate to the generated implementation?

**Comment by doukai** [comment]
> Why not use composition and implement the original interface but delegate to the generated implementation?

good idea,i'll try this way,thanks

**Comment by bcorso** [comment]
@doukai, the generated factories are not really intended for you to call. 

If you don't mind sharing, what are trying to do with them?

Also, which generated factories in particular are you talking about (Dagger generates factories in a couple different cases).

**Comment by doukai** [comment]
> @doukai, the generated factories are not really intended for you to call.
> 
> If you don't mind sharing, what are trying to do with them?
> 
> Also, which generated factories in particular are you talking about (Dagger generates factories in a couple different cases).

I‘m trying to develop configuration file injection ```@ConfigProperty``` and static slicing code generation ```@Aspect``` based on DaggerXXX Component, my original idea is  extends DaggerXXX Component in own annotation processor

**Comment by bcorso** [comment]
Ah, so by "factory impl class" you were referring to the DaggerXXComponent class, that should be fine. Just wanted to make sure you weren't referencing our `_Factory` classes we generate for `@Inject`/`@Provides`, which you shouldn't reference directly.
