### ISSUE TITLE
Are there any nested injection supporting?

### ISSUE THREAD

**Issue by OlegDokuka** [google/dagger#315]
So, I`m beginner with Dagger 2, and I would like to resolve all injection in my nested class. 

For example 

``` java
public class MainActivity extends AppCompatActivity {
    @Inject
    Set<ViewFactory> viewFactoryList; // here set contains several elements
    @Inject
    DefaultRecyclerViewAdapterSupport test;
}

//nested class
@EBean
public class DefaultRecyclerViewAdapterSupport<T extends View & BindView<Observable>> extends RecyclerViewAdapterSupportObservable<Observable, T> {
    @Inject
    Set<ViewFactory> viewFactoryList; // here set is null
//... another code  here
}
```

After injection no decencies resolved in the nested class.

If we try analyze generated source, we can find that nested class looks like 

``` java
@Generated("dagger.internal.codegen.ComponentProcessor")
public final class DefaultModule_ProvideDefaultRecyclerViewAdapterSupportFactory implements Factory<DefaultRecyclerViewAdapterSupport> {
  private final DefaultModule module;

  public DefaultModule_ProvideDefaultRecyclerViewAdapterSupportFactory(DefaultModule module) {  
    assert module != null;
    this.module = module;
  }

  @Override
  public DefaultRecyclerViewAdapterSupport get() {  
    DefaultRecyclerViewAdapterSupport provided = module.provideDefaultRecyclerViewAdapterSupport();
    if (provided == null) {
      throw new NullPointerException("Cannot return null from a non-@Nullable @Provides method");
    }
    return provided;
  }

  public static Factory<DefaultRecyclerViewAdapterSupport> create(DefaultModule module) {  
    return new DefaultModule_ProvideDefaultRecyclerViewAdapterSupportFactory(module);
  }
}

```

and main activity `#injectMembers(..)` looks like
``` java
  @Override
  public void injectMembers(MainActivity instance) {  
    if (instance == null) {
      throw new NullPointerException("Cannot inject members into a null reference");
    }
    supertypeInjector.injectMembers(instance);
    instance.test = testProvider.get();
    instance.viewFactoryList = viewFactoryListProvider.get();
  }

```

So, why the same features has not implemented in `DefaultModule_ProvideDefaultRecyclerViewAdapterSupportFactory#get()`?

Will in the future supports of this feature?

**Comment by OlegDokuka** [comment]
Fixed, my leak of knowledge

**Comment by OlegDokuka** [comment]
Hi guys, still have issue with nested/recursive injection. Can someone guide me, how to make work nested injection. 

My DefaultComponent.class looks like

```
@PerActivity
@Component(modules = {DefaultModule.class, EntityConverterModule.class, WebServiceModule.class})
public interface DefaultComponent {
    void inject(MainActivity activity);
    void inject(ItemListActivity activity);

    DefaultRecyclerViewAdapterSupport adapter();

    EntityPoolService entityPoolService();
}
``` 
And memberInjectors for `entityPoolService` and `adapter` also have generated, but never have never used

**Comment by gk5885** [comment]
I'm not following exactly what your question is here.  You've mentioned a few types here and there, but then ask some questions about other types that weren't included in the sample code that you've provided.  I think that you're going to need to revisit this question and clarify exactly what your questions are and make sure to include the relevant source.

Rather than doing that here, post your question on http://stackoverflow.com/questions/tagged/dagger-2 since that is a much better platform for iterating on questions and answers.  I'm closing this issue, but feel free to post the link to your SO question when you have it.
