### ISSUE TITLE
Anonymous classes increasing memory leak exposure

### ISSUE THREAD

**Issue by pyricau** [google/dagger#316]
The generated component classes contain code that looks like this:

``` java
  private void initialize1(final Builder builder) {
    this.userProvider =
        new dagger.internal.Factory<User>() {
          private final UserDependency userDependency = builder.userDependency;

          @Override
          public User get() {
            User provided = userDependency.user();
            if (provided == null) {
              throw new NullPointerException(
                  "Cannot return null from a non-@Nullable component method");
            }
            return provided;
          }
        };
```

In this example, the `Factory<User>` anonymous class only needs access to `builder`, which is a method argument. However, because it's an anonymous class, it has an unused strong reference to the component.

So this means that if anything keeps that `Provider<User>`  around, the whole component can't be GCed.

This bug brought to you by [LeakCanary](https://github.com/square/leakcanary) :) .

**Comment by gk5885** [comment]
Yeah, that was definitely something we were aware of when we first made these anonymous inner classes.  Any indication that this is actually causing anybody problems or just something noticed by the tool?

**Comment by ronshapiro** [comment]
This should be avoided by Proguard, correct? But if you're not using proguard our code should ideally still be semantically the same even if if isn't as optimal. 

When we enable Java 8 support lambdas will fix this but obviously not help Android users.

**Comment by pyricau** [comment]
@gk5885 It caused me trouble, but that might actually be good trouble: we break the build when we detect that a component is leaking. I was converting a D1 ObjectGraph to a D2 component. Some OkHttp idle connections were leaking a custom hostname verifier which leaked some providers. Switching to D2 means we were now leaking the entire component instead of just a provider, therefore breaking our build. Easily resolved though, by evicting idle connections in between tests.

**Comment by pyricau** [comment]
AFAIK this is still happening. This is an issue because it turns a small leak of one binding into the leak of an entire component.

I don't see how Proguard or lambdas would fix this. The issue is that those generated providers hold references to the entire component instead of holding only a reference to the fields of that component that they're using.

**Comment by ronshapiro** [comment]
@pyricau I believe that this latest change should address what you were asking for. Can you confirm?

**Comment by ronshapiro** [comment]
Confirmed offline with @pyricau that the referenced commit fixes the issue
