### ISSUE TITLE
Poor/confusing error message when type parameter type inaccessible

### ISSUE THREAD

**Issue by pettermahlen** [google/dagger#3163]
Given the following situation: 

1. A library (`:library`) defining the type `Foo<T>`  in one Gradle project.
2. Another Gradle project (`:module`) with:
   1. an (incorrect) 'implementation' dependency on the library, 
   2. a class `Bar`
   2. a module that provides a `Foo<String>` and a `Bar` that depends on the `Foo<String>`. 
3. A third Gradle project (`:main`) that defines a Component that includes the module above.

When the Dagger annotation processor processes `main`, it generates this highly confusing error message:

```
error: [Dagger/MissingBinding] foo.Foo<java.lang.String> cannot be provided without an @Provides-annotated method.
public abstract interface SomeComponent {
                ^
      foo.Foo<java.lang.String> is injected at
          SomeModule.provideBar(foo)
      Bar is requested at
          SomeComponent.bar()
```

That's in spite of the fact that there is in fact such a provider method right next to the place flagged as an error. Repro in https://github.com/pettermahlen/dagger-repro.

A better message would be to state that the `Foo` class cannot be loaded.

Note that this works fine without the type parameter on `Foo` - the method is generated by the processor, and the compiler flags it as not compilable.

**Comment by bcorso** [comment]
Thanks @pettermahlen for the repro case. 

I'm currently working on improving our validation for type resolution and to give a better error message for unresolvable types and it should cover this case as well.

It does require quite a bit of changes on our side, but I'm expecting to have something out within the next couple of weeks.

**Comment by bcorso** [comment]
This is fixed at [`HEAD`]() and should be in the next release.

The new error message will be something like this:

```
error: ComponentProcessingStep was unable to process 'MyComponent' because 'Foo' could not be resolved.
  
  Dependency trace:
      => element (CLASS): Bar
      => element (CONSTRUCTOR): Bar(Foo<java.lang.String>)
      => type (EXECUTABLE constructor): (Foo<java.lang.String>)void
      => type (ERROR parameter type): Foo<java.lang.String>
  
If type 'Foo' is a generated type, check above for compilation errors that may have prevented the type from being generated. Otherwise, ensure that type 'Foo' is on your classpath.
```

**Comment by pettermahlen** [comment]
Awesome, thanks!
