### ISSUE TITLE
What does this mean in documentation?

### ISSUE THREAD

**Issue by bhargavms** [google/dagger#317]
This one returns a Thermosiphon whenever a Pump is required:

```
@Provides static Pump providePump(Thermosiphon pump) {
  return pump;
}

```

This method is just returning whatever was passed into it, I dont understand whats going here at all

**Comment by tbroyer** [comment]
If a class has a dependency on a `Pump`, Dagger needs to know how to provide such a dependency (in the example `Pump` is an interface, but it could be an abstract class too).
Dagger won't scan the classpath looking for classes that happen to implement the interface (and what would it do if there are more than one?), you have to tell it what to do.

The `@Provides` annotation and `Pump` return-type tell Dagger that whenever it needs to provide a `Pump`, it should call this method. To call it though, it first has to provide it a `Thermosiphon` as argument. A `Thermosiphon` instance can be created directly though (it has an `@Inject` constructor, which BTW also declares a dependency on a `Heater`), so Dagger creates a `Thermosiphon` (providing it a `Heater` to its constructor), passes it to `providePump`, and it now has a `Pump` that it can inject whenever it needs to.

Dagger doesn't know what happens within the method, and in this case the method just happens to do a _cast_ from `Thermosiphon` to `Pump`. Dagger doesn't know, and doesn't care.

BTW, for support questions, please use StackOverflow or the [dagger-discuss](https://groups.google.com/forum/#!forum/dagger-discuss) forum.

**Comment by gk5885** [comment]
Thanks, for the good answer @tbroyer.
