### ISSUE TITLE
Poor/confusing error message with multibinds

### ISSUE THREAD

**Issue by pettermahlen** [google/dagger#3173]
Given this code (it's unnecessarily complicated, but I don't have time to pare it down right now):

```
@Component(
    modules = [
        SomeModule::class,
    ]
)
@Singleton
interface SomeComponent {
    fun set(): ReferenceTwo
}
```

```
@Module
class SomeModule {
    @Provides
    fun provideHi(foos: Set<@JvmSuppressWildcards Foo>) = Hi()

    @Provides
    fun provideBaz(hi: Hi) = Baz()

    @Provides
    fun provideReferenceOne(baz: Baz) = ReferenceOne()

    @Provides
    fun provideReferenceTwo(referenceOne: ReferenceOne) = ReferenceTwo()

    @Provides
    @ElementsIntoSet
    fun primeFooSet() = setOf<Foo>()

    @Provides
    @IntoSet
    fun provideBar(baz: Baz): Foo = Bar()
}

open class Foo

class Bar : Foo()

class Baz()

class Hi()

class ReferenceOne
class ReferenceTwo
```

Compiling gives the following message:
```
SomeComponent.java:10: error: [Dagger/DependencyCycle] Found a dependency cycle:
public abstract interface SomeComponent {
                ^
      Baz is injected at
          SomeModule.provideBar(baz)
      java.util.Set<Foo> is injected at
          SomeModule.provideHi(foos)
      Hi is injected at
          SomeModule.provideBaz(hi)
      Baz is injected at
          SomeModule.provideReferenceOne(baz)
      ReferenceOne is injected at
          SomeModule.provideReferenceTwo(referenceOne)
      ReferenceTwo is requested at
          SomeComponent.set()
```

There are two problems with this:
1. The message makes it look like the two 'references' are part of the cycle - the cyclic bit isn't clearly marked as such.
2. The connection between `Bar` and the `Set<Foo>` is not shown, making it harder to figure out what is happening. I'm not sure if this also happens in the same way without the `primeFooSet` method.

**Comment by bcorso** [comment]
Hi @pettermahlen,

Thanks for the feedback!

> 1. The message makes it look like the two 'references' are part of the cycle - the cyclic bit isn't clearly marked as such.

Dagger typically includes the entry point with the cycle because it's often useful to know why/how Dagger depends on the cycle. For example, if you read the error message backwards you get a dependency trace that looks like the one below where the first part tells you how/why you depend on `Baz` and the second part shows the cycle:

```

      SomeComponent.set() -> ReferenceTwo -> ReferenceOne -> Baz -> Hi -> Set<Foo> -> Baz
      ^                                                 ^    ^                          ^
      |__________________ Entry Point __________________|    |_________ Cycle __________|
```

Would it help to somehow distinguish between these two better?

> 2. The connection between Bar and the Set<Foo> is not shown, making it harder to figure out what is happening.

I don't think there's much we can do here. Dagger doesn't know about `Bar` at all because Dagger only has access to method signatures, not the body.

```
    @Provides
    @IntoSet
    fun provideBar(baz: Baz): Foo {
      return Bar() // Dagger doesn't have this information during processing.
    }
```

**Comment by pettermahlen** [comment]
Regarding 1: yes, I understand that - it would be awesome if the error message somehow more clearly pointed out which part was the cycle. The real case I'm looking at is actually worse (not quite sure why), because it doesn't even reference the 'provideBar' method, so there's no situation where you clearly depend on the exact same thing in the whole 'injection trace'. 

So something like how you separate the cycle from the entry point in your diagram above would be great. Maybe something along the lines of: 
```
     Baz is injected at                                      <---- cycle start 
          SomeModule.provideBar(baz)
      java.util.Set<Foo> is injected at
          SomeModule.provideHi(foos)
      Hi is injected at
          SomeModule.provideBaz(hi)
      Baz is injected at                                     <---- cycle end
          SomeModule.provideReferenceOne(baz)
      ReferenceOne is injected at
          SomeModule.provideReferenceTwo(referenceOne)
      ReferenceTwo is requested at
          SomeComponent.set()                                <---- injection entry point
```

Probably it's easier to make it readable for longer class names through having the arrows+labels to the left, but that was more whitespace-formatting for when when writing this. :P 

Regarding the second, what I was trying to say is that the cycle diagram actually looks something like:

```
      SomeComponent.set() -> ReferenceTwo -> ReferenceOne -> Baz -> Hi -> Set<Foo> -> Bar -> Baz
      ^                                                 ^    ^                                ^
      |__________________ Entry Point __________________|    |_________ Cycle ________________|
```

So the Set of Foos is a problem only because it contains a `Bar`, which it seems to me that Dagger surely knows about since it has created the set in the first place? Of course, that information may not be available at the point the error is detected. Just wanted to clarify what I meant.

**Comment by bcorso** [comment]
> it would be awesome if the error message somehow more clearly pointed out which part was the cycle. The real case I'm looking at is actually worse (not quite sure why), because it doesn't even reference the 'provideBar' method, so there's no situation where you clearly depend on the exact same thing in the whole 'injection trace'.

So in your real error message, does the cycle start and end on the same key (similiar to `Baz` in this example)?

Basically, I'm trying to understand if the issue is finding the start and end of the cycle in the error message, or if it's more that once you've found the cycle it's difficult to understand it.

For example, would it help if we clarified what key the cycle is for upfront and specifically called out multibindings? Something like the error below (new information in `[]` brackets):

```
      [Detected cycle: Baz]

      Baz is injected at [multibinding contribution]
          SomeModule.provideBar(baz)
      java.util.Set<Foo> [multibinding] is injected at
          SomeModule.provideHi(foos)
      Hi is injected at
          SomeModule.provideBaz(hi)
      Baz is injected at
          SomeModule.provideReferenceOne(baz)
      ReferenceOne is injected at
          SomeModule.provideReferenceTwo(referenceOne)
      ReferenceTwo is requested at
          SomeComponent.set()
```

> So the Set of Foos is a problem only because it contains a Bar, which it seems to me that Dagger surely knows about since it has created the set in the first place? Of course, that information may not be available at the point the error is detected.

To clarify, Dagger reports these errors at compile time, which is why we don't have the information about Bar (the set isn't actually created until runtime).

**Comment by pettermahlen** [comment]
Unfortunately, the real error is gone now, I fixed it. But from memory, unlike in this example, I never found the same key repeated twice in that injection trace. So I had to manually draw it up on paper to see it. Maybe the key was there and I didn't see it listed despite spending a lot of time searching for it.

I think I had both the problems you're mentioning: finding the cycle was the bigger one, and that was made harder by the fact that I also didn't understand it.

Maybe, now that I look at your example, I see what the problem is: in my stack trace, it may have been the `Bar` that was externally referenced/outside the cycle. It seems to me that the reason why `Baz` is mentioned a second time is that it's externally referenced by `ReferenceOne`, and that might be making it harder to understand where the cycle is and where the external reference chain starts. 

I don't think that highlighting the 'cyclic key' would have helped me, now that I think about it - any key could be chosen as the 'cyclic key', and that doesn't really matter. The thing that would have helped is a clearer separation between the cycle and the reference chain in the output. The 'multibinding contribution' output would also help. Maybe something like:

```
==== cycle start ====
      Baz is injected at [multibinding contribution]
          SomeModule.provideBar(baz)
      java.util.Set<Foo> [multibinding] is injected at
          SomeModule.provideHi(foos)
      Hi is injected at
          SomeModule.provideBaz(hi)
==== cycle end ====
      Baz is injected at
          SomeModule.provideReferenceOne(baz)
      ReferenceOne is injected at
          SomeModule.provideReferenceTwo(referenceOne)
      ReferenceTwo is requested at
          SomeComponent.set()
```

**Comment by bcorso** [comment]
Thanks, for clarifying!

I talked to the team and we agree this seems like a reasonable request. The best way to format the code is still unclear, but we'll try to do something to separate the actual cycle from the entry point in this case.

**Comment by pettermahlen** [comment]
Sounds awesome, thanks!
