### ISSUE TITLE
Generic type on `@AndroidEntryPoint` Activity has been erased with minify enabled

### ISSUE THREAD

**Issue by Goooler** [google/dagger#3192]
See https://issuetracker.google.com/issues/216194181.

AGP 7.1 below with R8 full mode enabled or AGP 7.1 above with R8 compatibility mode will both trigger this issue.

**Comment by danysantiago** [comment]
Dupe of https://github.com/google/dagger/issues/3094 which is already fixed but the fix has not been released.

**Comment by Goooler** [comment]
Thx again.
