### ISSUE TITLE
Injecting into views from service is not working

### ISSUE THREAD

**Issue by amarkovits** [google/dagger#3205]
Hello

In my app I have a singleton that I want to inject in a certain view. This works great if the view is part of the activity/fragment/view tree but if the view is not part of an activity but of a service(the service has the entry point annotation, the service is used for creating a custom keyboard) then I get this exception:

` Caused by: java.lang.ClassCastException: Cannot cast my.app.DaggerApplication_HiltComponents_SingletonC$ServiceCImpl to dagger.hilt.android.internal.managers.ViewComponentManager$ViewComponentBuilderEntryPoint
        at java.lang.Class.cast(Class.java:2446)
        at dagger.hilt.EntryPoints.get(EntryPoints.java:57)
        at dagger.hilt.EntryPoints.get(EntryPoints.java:59)
        at dagger.hilt.android.internal.managers.ViewComponentManager.createComponent(ViewComponentManager.java:93)
        at dagger.hilt.android.internal.managers.ViewComponentManager.generatedComponent(ViewComponentManager.java:77)`

This is my module:

```
@Module
@InstallIn(SingletonComponent::class)
object GlobalUIStateHandlerModule {

    @Provides
    fun provideGlobalUIStateHandler(): GlobalUIStateHandler {
        return MyGlobalUIStateHandler()
    }
}
```

Is there a way to configure hilt so I have a singleton that I can inject in view in both my main app and in the third party keyboard I provide?

**Comment by groakley** [comment]
Currently there is no way to do this with `@AndroidEntryPoint`. Instead, you could work around this by using a regular `@EntryPoint` in the Service to manually set the view's dependencies.

**Comment by groakley** [comment]
When you use the View from a Service, is there also an intermediate Fragment that holds that view? Or do you create the View from the Service directly?

**Comment by amarkovits** [comment]
> When you use the View from a Service, is there also an intermediate Fragment that holds that view? Or do you create the View from the Service directly?

The view is created directly from the Service. There are no fragments.

**Comment by groakley** [comment]
Were you able to workaround this using an `@EntryPoint`? This should work so long as you only need to pass singleton dependencies to the View.

We're hesitant to create another path in the [component hierarchy](https://dagger.dev/hilt/components) directly from Singleton->View, as it introduces a fair bit complexity without providing a lot of value, especially given the relatively simple workaround using an `@EntryPoint`.

**Comment by amarkovits** [comment]
@groakley I've made it work with `@EntryPoint`. 
Added this to my view:

```
    @EntryPoint
    @InstallIn(SingletonComponent::class)
    interface DependencyProvider {
        fun getGlobalUIStateHandler(): GlobalUIStateHandler
    }

    val globalUIStateHandler = EntryPointAccessors.fromApplication(context, DependencyProvider::class.java).getGlobalUIStateHandler()
```

It works fine in this case, and I can provide alternate implementation for tests so good enough for now.

**Comment by frhnfrq** [comment]
@groakley Hi, how can I achieve this for ViewModels? I want to inject the ViewModel in my View which is attached to a Service.
