### ISSUE TITLE
Which Java versions are supported?

### ISSUE THREAD

**Issue by hleibenko-attentive** [google/dagger#3207]
Hi, sorry for the question in issues, but I spent a relatively big chunk of time investigating this and haven't found an answer. 
The closes I got is I found the ["Avoid using java 11 in this situation -- it works with java 8."](https://github.com/google/dagger/issues/2144#issuecomment-733931468) recommendation in #2144

Is Java 17 supported / recommended?

**Comment by bcorso** [comment]
The quote from #2144 was specifically for users hitting that particular issue when using DataBinding with Dagger in java 11 -- in general you shouldn't have any issues using Dagger with java 11.

> Is Java 17 supported / recommended?

Dagger is most thoroughly tested in java 11 and below, and is meant to support all its feature. You should still be able to use Dagger in versions above java 11, but using Dagger with new features might not be supported yet (e.g. https://github.com/google/dagger/issues/2106).

**Comment by hleibenko-attentive** [comment]
thanks for the quick reply
