### ISSUE TITLE
Mockity.spy Fails upon upgrading dagger to 2.38

### ISSUE THREAD

**Issue by prasadsn** [google/dagger#3210]
Here is the error thrown on calling Mocikity.spy() on activity upon upgrading dagger from 2.27 to 2.38
Unable to create mock instance of type 'XXXActivity'
org.mockito.exceptions.base.MockitoException: Unable to create mock instance of type 'XXXActivity'

**Comment by bcorso** [comment]
Hi @prasadsn, Dagger itself doesn't have anything to do with activities so I'm not sure how it's related. Are you using Hilt?

**Comment by bcorso** [comment]
Closing this. Feel free to reopen if you have more details about how this is related to Dagger.
