### ISSUE TITLE
Dagger uses wrong instance in generated code when in constructor parameters are named like "xxxProvider, xxx"

### ISSUE THREAD

**Issue by novemberox** [google/dagger#323]
For class with constructor like this:
```
    @Inject
    public UserRoleService(UserApiProvider userProvider, User user)
```
dagger would generate code like this:

```
  public UserRoleService_Factory(Provider<UserApiProvider> userProvider, Provider<User> userProvider1) {  
    assert userProvider != null;
    this.userProvider = userProvider;
    assert userProvider1 != null;
    this.userProvider1 = userProvider1;
  }

  @Override
  public UserRoleService get() {  
    return new UserRoleService(userProvider.get(), userProvider.get());
  }
```
In get method we see that dagger uses `userProvider` twice instead of using `userProvider` and then `userProvider1`. If only I had changed constructor to `UserRoleService(UserApiProvider userApiProvider, User user) ` it would generate other variable names and would work.

**Comment by ronshapiro** [comment]
Can you test this out with `dagger-2.6` and reopen if this is still an issue? I believe we fixed this.
