### ISSUE TITLE
Lifecycle support for scopes (like ActivityRetainedLifecycle) or Lifecycle injection. 

### ISSUE THREAD

**Issue by yschimke** [google/dagger#3233]
I've found ActivityRetainedLifecycle to be immensely useful for cleaning up things holding actual resources.  A client of a bound service for example.

I'm wondering why it isn't supported for other scopes with obvious lifecycle - Application, Activity, Service (not sure this is as easy given the extra work for lifecycle-service).

Is it to avoid patterns of doing expensive work on shutdown, or it's expected that items in defined scopes are accessed only by clients aware of that lifecycle, and should put that explicitly in their onStop method?

Would it make sense to inject lifecycle instances with an annotation?

Is there another workaround here, like downcasting the ApplicationContext or ActivityContext and grabbing the lifecycle off that?

**Comment by yschimke** [comment]
@Chang-Eric Thanks, what is the situation for ServiceScoped?

**Comment by Chang-Eric** [comment]
I think you can use https://developer.android.com/reference/androidx/lifecycle/LifecycleService for services.

**Comment by yschimke** [comment]
@Chang-Eric yep - I guess that is my question, do I need to manually call the lifecycle events from the Service (breaking DI?), or can the Service get passed into the provide function and I should cast it to a LifecycleService?

**Comment by Chang-Eric** [comment]
Ah, you can inject `Service` into a provide function, but then would need to cast it to get the lifecycle.

**Comment by yschimke** [comment]
Thanks, I now understand this section of the docs https://developer.android.com/training/dependency-injection/hilt-android#component-default
