### ISSUE TITLE
MultiBindings not working on nested Generic Set<Class<T>>

### ISSUE THREAD

**Issue by cemore2048** [google/dagger#3244]
This might be Kotlin specific but figured I'd take a shot here. This works

```kotlin
interface Module {
    @IntoSet
    @Provides
    fun asomset(): Foo = Foo()
}

class Example @Inject constructor(var exampleSet: Set<@JvmSuppressWildcards Foo>) {}
```

This does not

```kotlin
interface Module {
    @IntoSet
    @Provides
    fun asomset(): Class<out Activity> = LoginActivity::class.java
}

class Example @Inject constructor(var exampleSet: Set<@JvmSuppressWildcards <Class<@JvmSuppressWildcards Activity>>)
```

For the one that does not, I get the error: Dagger bindings missing. need to @Provide
It's related to somehow @JvmSuppressWildcards not handling a nested generic in the Set<Class<T>>.
Anyone know how to get around this? Have also tried suppressing the wildcard in the Class as well, but that didn't seem to work

**Comment by bcorso** [comment]
Looking at the generated java stub for `Module` and `Example` classes should show you exactly what types Dagger is seeing, and help you identify exactly where you need to add `@JvmSuppressWildcards` (if at all).

Feel free to post the java stubs here if you need help.

**Comment by bcorso** [comment]
fwiw, I'm also surprised you didn't get a compiler error for your provides method, since I think you need `Class<out Activity>` rather than `Class<Activity>`.

Using `out` makes things compile for me:

```kotlin
@Component(modules = [MyModule::class])
interface MyComponent {
    fun example(): Example
}

class Example @Inject constructor(var exampleSet: Set<@JvmSuppressWildcards Class<out Foo>>)

@Module
object MyModule {
    @IntoSet
    @Provides
    fun asomset(): Class<out Foo> = FooImpl::class.java
}

class FooImpl: Foo() {}

open class Foo {}
```

**Comment by cemore2048** [comment]
Thanks @bcorso that's my bad on the example. I'm working with a much bigger app and didn't translate it correctly. In this dummy example it seems to compile fine.

However, in my larger app I'm getting.

```[Dagger/MissingBinding] java.util.Set<java.lang.Class<? extends android.app.Activity>>```

Where it's still using the wildcard on the `Activity`. Which led me to think there was something up with the multibindings.

I guess maybe there's something up with something else in my larger project setup.
