### ISSUE TITLE
Inject interfaces directly

### ISSUE THREAD

**Issue by geftimov** [google/dagger#3258]
Hello there,
This is maybe not a feature request but just a question if it's possible.

Given we have an interface
```kotlin
interface AccountRepository {
    suspend fun getAccount(): Account
}
```
and implementation
```kotlin
class AccountRepositoryImpl @Inject constructor(): AccountRepository {
    ...
}
```
To be able to use the interface you need to have a module that `@Provides` or `@Binds` the implementation to the interface, like :
```kotlin
@Provides
fun provideAccountRepository(repository: AccountRepositoryImpl): AccountRepository = repository
```
I did work for some time with Spring where the interface will be injected automatically.
I guess they use reflection to find if there is an implementation for this injected interface.
And if there is more than one implementation a compilation error will occur - which is perfect.

If we have this functionality our modules will be empty and working with dagger will be easier.
Can this be done in dagger?

**Comment by bcorso** [comment]
IIUC, you're asking for a feature where you request the interface, e.g. 

```
class Foo @Inject constructor(AccountRepository accountRepository) {...}
```

and then Dagger automatically passes in a `AccountRepositoryImpl` instance here without a module defining an `@Provides`/`@Binds` method?

Unfortunately, this is not possible. Dagger uses an isolating processor so all of its dependency must be reachable from the `@Component`-annotated interface. For example, using a module allows Dagger to reach the module through the component annotation (`@Component.modules = AccountRepositoryImplModule.class`), and then it can reach the `AccountRepositoryImpl` through the `@Binds` method.  This isn't the case with the approach you're requesting, which would cause issues with incremental processing.

In addition, even if Dagger was not an isolating processor this approach would require inspecting every class in the classpath to see if it has an `@Inject`-annotated constructor and extends the `AccountRepository` interface, which would be extremely inefficient.
