### ISSUE TITLE
@IntoMap and @StringKey don't work on Kotlin, because of kotlin's own collection classes

### ISSUE THREAD

**Issue by GoldenMine0502** [google/dagger#3263]
(not work)
`
private val downloaders: Map<String, MapDownloader>
`

(work)
`
private val downloaders: java.util.Map<String, MapDownloader>
`

**Comment by bcorso** [comment]
I'm not able to reproduce this. 

The Java stubs generated by `kapt` should replace the kotlin `Map` with `java.util.Map`, so it should just work.

Can you share the full error message and a more complete usage of how you're trying to use the map with Dagger?

**Comment by GoldenMine0502** [comment]
https://github.com/GoldenMine0502/osumapcollector2
simple crawler using selenium

I use dagger 2.4.1 and kotlin 1.3.72

D:\Develop\Project\Utility\osumapcollector2\build\tmp\kapt3\stubs\main\kr\goldenmine\downloader\MapDownloaderRouterFactory.java:8: error: [Dagger/MissingBinding] java.util.Map<java.lang.String,? extends kr.goldenmine.downloader.MapDownloader> cannot be provided without an @Provides-annotated method.
public abstract interface MapDownloaderRouterFactory {
                ^
      java.util.Map<java.lang.String,? extends kr.goldenmine.downloader.MapDownloader> is injected at
          kr.goldenmine.downloader.MapDownloaderRouter(downloaders)
      kr.goldenmine.downloader.MapDownloaderRouter is requested at
          kr.goldenmine.downloader.MapDownloaderRouterFactory.router()

**Comment by GoldenMine0502** [comment]
please refer the class MapDownloaderRouter in the package kr.goldenmine.downloader

**Comment by tbroyer** [comment]
The problem that Dagger binds `Map<String, MapDownloader>` but you're _expecting_ `Map<String, ? extends MapDownloader>` due to how Kotlin handles generics.
See https://github.com/google/dagger/issues/2586

Adding `@JvmSuppressWildcards` fixes compilation:
```diff
diff --git a/src/main/kotlin/kr/goldenmine/downloader/MapDownloaderRouter.kt b/src/main/kotlin/kr/goldenmine/downloader/MapDownloaderRouter.kt
index 596f2bd..ba157e8 100644
--- a/src/main/kotlin/kr/goldenmine/downloader/MapDownloaderRouter.kt
+++ b/src/main/kotlin/kr/goldenmine/downloader/MapDownloaderRouter.kt
@@ -4,7 +4,7 @@ import javax.inject.Inject
 
 @Suppress("PLATFORM_CLASS_MAPPED_TO_KOTLIN")
 class MapDownloaderRouter @Inject constructor(
-    private val downloaders: Map<String, MapDownloader>
+    private val downloaders: Map<String, @JvmSuppressWildcards MapDownloader>
     ){
 
     operator fun get(key: String): MapDownloader? = downloaders[key]
```

**Comment by GoldenMine0502** [comment]
oh.. nice solution. thanks a lot.
