### ISSUE TITLE
Testing with Periodic Work Requests

### ISSUE THREAD

**Issue by St4B** [google/dagger#3270]
I have defined an Application class like that:
```kotlin
@HiltAndroidApp
class App : Application(), Configuration.Provider {

    @Inject
    lateinit var workerFactory: HiltWorkerFactory
    
    override fun getWorkManagerConfiguration(): Configuration = Configuration.Builder()
        .setWorkerFactory(workerFactory)
        .build()
}
```
In my application, we start some periodic work requests during the app startup. The problem is that I get the following error on Android tests execution: `WorkManager is not initialized properly.` which probably is expected as I use `HiltTestApplication`. I've tried to create a custom test app like that:
```kotlin
@HiltAndroidApp
class App

open class BaseApp : Application(), Configuration.Provider {

    @Inject
    lateinit var workerFactory: HiltWorkerFactory
    
    override fun getWorkManagerConfiguration(): Configuration = Configuration.Builder()
        .setWorkerFactory(workerFactory)
        .build()
}

@CustomTestApplication(BaseApp::class)
class TestApp
```
But I get the following error: ` @CustomTestApplication does not support application classes (or super classes) with @Inject fields.`
Is there some limitation? How to overcome this issue?

**Comment by bcorso** [comment]
Hi @St4B,

We don't allow field injection in a test application because it's too easy to get leaks. In particular the test application lifetime is not congruent with the lifetime of the `SingletonComponent` used for each test case (you can read more about that [here](https://dagger.dev/hilt/early-entry-point)).

In this case you'll need to use an `@EntryPoint` (or likely [`@EarlyEntryPoint`](https://dagger.dev/hilt/early-entry-point)) instead. For example,

```kotlin
open class BaseApp : Application(), Configuration.Provider {
  @EarlyEntryPoint
  @InstallIn(SingletonComponent::class)
  interface HiltWorkerFactoryEntryPoint {
    fun workerFactory(): HiltWorkerFactory
  }
    
  override fun getWorkManagerConfiguration(): Configuration { 
    return Configuration.Builder()
        .setWorkerFactory(EarlyEntryPoints.get(this, HiltWorkerFactoryEntryPoint::class).workerFactory())
        .build()
  }
}
```

**Comment by St4B** [comment]
Thank you! This seems to solve my problem 😄
