### ISSUE TITLE
Updating from 2.30.1 to 2.40.5 issue

### ISSUE THREAD

**Issue by yehia2030** [google/dagger#3285]
When i update my project to the newest version i got this issue while build my app

    import dagger.internal.MemoizedSentinel;
                      ^
    symbol:   class MemoizedSentinel
    location: package dagger.internal

    error: cannot find symbol
          if (local instanceof MemoizedSentinel) {
                               ^
    symbol:   class MemoizedSentinel
    location: class ActivityRetainedCImpl

    error: reentrantCheck(Object,Object) has private access in DoubleCheck
            lifecycle = DoubleCheck.reentrantCheck(lifecycle, local);
                                   ^

i'm using jetpack compose

**Comment by bcorso** [comment]
Hi @yehia2030, can you double check that you've updated all of your artifacts to the same version?

It sounds like you've likely updated `com.google.dagger:dagger` to the new version but there's a `com.google.dagger:dagger-compiler` that's still at the old version.

**Comment by yehia2030** [comment]
@bcorso thank you so much it worked now 👍
