### ISSUE TITLE
NPE due to superclass member injector, because code generating in wrong order. Same as #214

### ISSUE THREAD

**Issue by ar-g** [google/dagger#329]
This issue seems to be a duplicate of #214, but nobody responds there for four days, so I decided to open a new issue.
Bug remains when injecting parent class in components with different scopes and using subcomponents like
``` java
@PerActivity @Subcomponent public interface ActivityScopeComponent {
  void inject(Child1 child1);
}
@Singleton @Component public interface AppTestComponent {
  ActivityScopeComponent plus();

  void inject(Child2 userHolder);
}
```
then it produce generated code like in this [gist](https://gist.github.com/ar-g/41f18a951ca216b4a57c#file-dagger2_code_generation_issue_daggerapptestcomponent-java-L64) and therefore NPE.

I created gist with detailed [example](https://gist.github.com/ar-g/9319c1da7c768538aa6b)

Before I exposed dependencies from other scopes. But now it's too much of them. Subcomponents seem the only right solution.

**Comment by vytautasgimbutas** [comment]
:+1:

**Comment by jaredzhang** [comment]
+1

**Comment by candyss9185** [comment]
+1

**Comment by ronshapiro** [comment]
#214 was fixed, so I'm going to close this.
