### ISSUE TITLE
error: cannot find symbol DaggerDefault_HiltComponents_SingletonC

### ISSUE THREAD

**Issue by kevinetore** [google/dagger#3291]
With version `2.41` the error mentioned [here](https://github.com/google/dagger/issues/3162) still exists. 

**Database providers**

```
@Module
@InstallIn(SingletonComponent::class)
class TestDatabaseModule {
    @Provides
    @Named("test_some_db")
    fun provideInMemoryDb(@ApplicationContext context: Context) =
        Room
            .inMemoryDatabaseBuilder(
                context, SomeDatabase::class.java
            )
            .allowMainThreadQueries()
            .build()
}
```

And

```
@Module
@InstallIn(SingletonComponent::class)
object DatabaseModule {
    @Provides
    @Singleton
    fun provideSomeDatabase(app: Application): SomeDatabase {
        return Room.databaseBuilder(
            app,
            SomeDatabase::class.java,
            SomeDatabase.DATABASE_NAME
        ).build()
    }
}
```

**Test example**

```
@UninstallModules(DatabaseModule::class)
@HiltAndroidTest
class SomeDatabaseTest {
    @get:Rule
    var hiltAndroidRule = HiltAndroidRule(this)

    @Before
    fun setUp() {
        hiltAndroidRule.inject()
    }

    @Inject
    @Named("test_some_db")
    lateinit var mDatabase: SomeDatabase

    ...
}
```

**Stacktrace**

```
/app/build/generated/hilt/component_sources/debugUnitTest/SomeDatabaseTest_TestComponentDataSupplier.java:8: error: cannot find symbol
import dagger.hilt.android.internal.testing.root.DaggerSomeDatabaseTest_HiltComponents_SingletonC;
                                                ^
  symbol:   class DaggerSomeDatabaseTest_HiltComponents_SingletonC
  location: package dagger.hilt.android.internal.testing.root
```

I've also tried to use `@TestInstallIn(components = SingletonComponent.class, replaces = DatabaseModule.class)` within `TestDatabaseModule`. Is there any other information I can provide?

**Comment by bcorso** [comment]
Hi @kevinetore, sorry for the delay.

Unfortunately I couldn't repro this with just the code snippets you provided.

The stack trace you posted also unfortunately doesn't tell us much. In most cases that error is accompanied by other errors which say more about _why_ the component wasn't generated. If you can find anything else in the error messages that you can share that would help.

Of course, if you're able to reproduce this in a sample app that you can share with us we can also take a deeper look for you.

**Comment by richanshah** [comment]
@kevinetore  what is the resolution step for the issue? can u guide me
