### ISSUE TITLE
Generated factory should not need to cast if dependency type is in the same package

### ISSUE THREAD

**Issue by h908714124** [google/dagger#3297]
For example in `BindsMethodValidator_Factory` the following code is generated:

```java
public static BindsMethodValidator newInstance(
    DaggerTypes types,
    BindsTypeChecker bindsTypeChecker,
    Object dependencyRequestValidator,
    DaggerSuperficialValidation superficialValidation,
    InjectionAnnotations injectionAnnotations) {
  return new BindsMethodValidator(
      types,
      bindsTypeChecker,
      (DependencyRequestValidator) dependencyRequestValidator,
      superficialValidation,
      injectionAnnotations);
}
```
It seems like if we change the type of `dependencyRequestValidator` from `Object` to `DependencyRequestValidator` here, the code would still compile and the cast could be dropped, which would make the generated code much "prettier". We can get this pretty result by changing the visibility of class `DependencyRequestValidator` to `public`. But of course, we don't want to make this validator public just to avoid a cast in generated code.

At a glance, it looks like `InstanceCastPolicy.CAST_IF_NOT_PUBLIC` will insert a cast for any type that is not `public`. By considering that some non-public types, like `BindsMethodValidator` and `DependencyRequestValidator`, live in the same package, it should be possible to avoid some of these casts. Would it be possible to add, for example, a new InstanceCastPolicy `CAST_IF_NOT_PUBLIC_AND_NOT_IN_SAME_PACKAGE`?

**Comment by bcorso** [comment]
> It seems like if we change the type of dependencyRequestValidator from Object to DependencyRequestValidator here, the code would still compile and the cast could be dropped

I think the issue is that `BindsMethodValidator_Factory.newInstance(...)` is used by the generated component which may live in a different package. 

In particular, we may have to pass the `DependencyRequestValidator` parameter in as an `Object` in the generated component, e.g.

```java
@Generated
final class DaggerMyComponent extends MyComponent {
  // Calling Provider.get() on this returns Object.
  // We can't use Provider<DependencyRequestValidator> since it's not accessible to this package
  Provider dependencyRequestValidatorProvider;

  ...BindsMethodValidator_Factory.newInstance(..., dependencyRequestValidatorProvider.get(),...);
}
```

**Comment by h908714124** [comment]
`BindsMethodValidator_Factory.newInstance` is not used by the generated component. So there are some cases where the generated component does not use `newInstance`. But even when it does, the generated component could also be in the same package. I guess we don't have this information about the component(s) when generating the factory, right?

**Comment by bcorso** [comment]
> But I guess we don't have this information about the component(s) when generating the factory, right?

Yes, that's correct. Whether or not `newInstance` is called (and by which package it is called from) depends on a lot of factors that are only known when we are generating the component, so when we're generating the factory we have to use `Object` because we don't have that information yet.

**Comment by h908714124** [comment]
Would it be possible to delay generating the factory until the last component processing step has finished, to make this information available?

**Comment by bcorso** [comment]
We actually want to avoid that if possible. For example, if your `@Inject` constructor class is in a separate library Dagger will generate the factory when building that library. This can be a lot better for build times since those generated classes can be cached and/or built in parallel rather than trying to generate all of your factories when we generate the component. Generating the factories with the generated component can also lead to 1-version violations where we try to generate the same factory class multiple times (e.g. if you may have multiple components that each try to generate the same factory with the same class name).

I think the cast in the generated code are likely a small price to pay to avoid those issues.

**Comment by h908714124** [comment]
Thank you for the explanation.
