### ISSUE TITLE
TypeNotPresentException: Type <error> not present - After Deleting Module Class and Forgetting to Remove it from Subcomponent Annotation Reference

### ISSUE THREAD

**Issue by rluick15** [google/dagger#330]
```
@ActivityScope
@Subcomponent(modules = {TestModule1.class, TestModule2.class})
public interface MainActivityComponent {

//code here
}
```

The exception was thrown after I deleted the TestModule2 class but forgot to delete the reference in the above subcomponent annotation. The full exception is as follows:

```
Error:Execution failed for task ':flagshipapp:compileItalyStagingJavaWithJavac'.
> java.lang.TypeNotPresentException: Type <error> not present
```

It was not clear at all what was happening based upon this message and clicking on the exception did not take you to the issue. Something to indicate that TestModule2.class no longer exists and needs to be removed would help out here.

**Comment by ronshapiro** [comment]
Can you reproduce this? I tried but couldn't

```java
@Component
interface C {
  S sub();
}

@Subcomponent(modules = {M1.class, M2.class})
interface S {
  Object o();
}

@Module class M1 {
  @Provides Object provideO() { return new O(); }
}
```

```
Playground.java:16: error: cannot find symbol
@Subcomponent(modules = {M1.class, M2.class})
                                   ^
  symbol: class M2

Playground.java:17: error: dagger.internal.codegen.ComponentProcessor was unable to process this interface because not all of its dependencies could be resolved. Check for compilation errors or a circular dependency with generated code.
interface S {
^
Playground.java:12: error: dagger.internal.codegen.ComponentProcessor was unable to process this interface because not all of its dependencies could be resolved. Check for compilation errors or a circular dependency with generated code.
interface C {
^
```

**Comment by rluick15** [comment]
Yeah, this is happening to me every time. Maybe try running the code with the 2nd module a few times and then remove it. I had TestModule2 in use for a while and then merged it into TestModule1. My hunch is that the code was already generated and maybe that blocked the correct error from being displayed or caused some issues in the background. It's hard to say as the error message didn't point anywhere.

**Comment by ronshapiro** [comment]
This sounds like a gradle/build system issue, not a Dagger one.
