### ISSUE TITLE
Assisted injection - generating parameterized Factories

### ISSUE THREAD

**Issue by kotucz** [google/dagger#331]
In our application we have quite a lot of classes, that have some `@Inject` annotated dependencies 
(mostly field dependencies), while having some create-time parameters that are compulsory.
For example class `Foo` has a compulsory non-injected constructor parameter `param` and field dependency (and also constructor and method injected dependencies).

``` java
class Foo {
    @Inject FieldDependency fieldDependency;

    Foo(InitDependency initDependency, @Assisted Param param) {
        /* ... */
    }

    @Inject
    void injectMethodDependency(MethodDependency methodDependency) {
        /* ... */
    }
}
```

For creation of `Foo` instance the `FooFactory` is needed:

``` java
interface FooFactory {
    Foo createFoo(Param param);
}
```

We could use [AutoFactory](https://github.com/google/auto/blob/master/factory/README.md) to generate `FooFactory` implementation, but it forces all dependencies to be passed as constructor parameters together with create-time parameters. It does not support field and method injections, which would be useful.

Using `MembersInjector<Foo>` from Dagger 2 the generated factory implementation class could look like below - it would also supports all kinds of Dagger 2 injections.

``` java
public class FooFactoryImpl implements FooFactory {
    @Inject MembersInjector<Foo> fooMembersInjector;
    @Inject Provider<InitDependency> initDependencyProvider;

    @Inject
    FooFactoryImpl() {
    }

    @Override
    public Foo createFoo(Param param) {
        final Foo instance = new Foo(initDependencyProvider.get(), param);
        fooMembersInjector.injectMembers(instance);
        return instance;
    }
}
```

Could something like this be automatically generated by Dagger 2 or AutoFactory (or other library)?

**Comment by ronshapiro** [comment]
Can you use [`@AutoFactory.extending`](https://github.com/google/auto/blob/73452e4ad81220a25e4eaaad2a6036ff76aadbfe/factory/src/main/java/com/google/auto/factory/AutoFactory.java#L58) to solve this?
