### ISSUE TITLE
[Hilt]: Unable to make hilt and dagger work together

### ISSUE THREAD

**Issue by jayashankar987** [google/dagger#3334]
I have been trying to integrate a new library module developed in Hilt inside a multi-module project which was developed on top of DaggerV2 _(migrating the existing project right now is not something which we are looking at right now)_ and found that when adding `@HiltAndroidApp` inside Application class, the app fails to build

Though the Android Developer website confirms that Hilt and Dagger co-exist.
we are facing integration issues when trying to build with hilt dependencies.

### root/build.gradle.kts
```
classpath("com.google.dagger:hilt-android-gradle-plugin:2.41")
classpath("androidx.navigation:navigation-safe-args-gradle-plugin:2.4.1")
```

### app/build.gradle.kts
```
plugins { ......
id("dagger.hilt.android.plugin")
}
implementation("com.google.dagger:hilt-android:2.41")
kapt("com.google.dagger:hilt-android-compiler:2.41")
```

### Dagger Dependencies added inside app module Gradle file
```
// Dagger 2
implementation(Deps.Dagger.dagger)
annotationProcessor(Deps.Dagger.compiler)
kapt(Deps.Dagger.compiler)
kapt(Deps.Dagger.processor)
object Dagger {
    const val dagger = "com.google.dagger:dagger:${Versions.dagger}"
    const val compiler = "com.google.dagger:dagger-compiler:${Versions.dagger}"
    const val processor = "com.google.dagger:dagger-android-processor:${Versions.dagger}"
    const val android = "com.google.dagger:dagger-android:${Versions.dagger}"
}
const val dagger = "2.41"
```

### BaseApplication.kt
```
@HiltAndroidApp
class MyApplication : Application()
```

### Below is the error am facing when trying to build the project
```
Error Observed During Build Time:
/Users/jayashankar/workspace/ela/app/build/tmp/kapt3/stubs/LogDebug/com/*****/***/***/MyApplication.java:6: error: incompatible types:
 NonExistentClass cannot be converted to Annotation
@error.NonExistentClass()
Execution failed for task ':app:kaptByJusLogDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.gradle.internal.KaptWithoutKotlincTask$KaptExecutionWorkAction
   > java.lang.reflect.InvocationTargetException (no error message)
```

Note: If `@HiltAndroidApp` is removed the project compiles successfully but could not initiate hilt components in new library module

**Comment by bcorso** [comment]
@jayashankar987 that is a `kapt` error and it usually happens when you forget the import for an annotation. Can you check that you have actually imported the `HiltAndroidApp` annotation in your source file?

**Comment by jayashankar987** [comment]
Thank you @bcorso, seems import was missing when trying to add the `HiltAndroidApp` annotation
