### ISSUE TITLE
Proposal: new experimental mode `-Adagger.autoComponents` to avoid casts in factories

### ISSUE THREAD

**Issue by h908714124** [google/dagger#3335]
Currently the generated component instantiates every binding directly from the component's package. Non-public types are treated as `Object` and casted down in factories.

This casting pattern works, but seems hacky and there should be a better way. Casting breaks type safety and should be avoided. It could lead to problems in the future. For instance, what if Java adds types that do not extend from `Object`?

In order to address this, I propose a new experimental mode `-Adagger.autoComponents`. In this mode, no casts are generated in factories, and every factory has the same visibility as the type it creates. For each `@Component` annotation, a new component-like class is generated in every package that contains bindings that are used by the component, and is different from the package of the base component. The Auto-components' class names must be chosen carefully, to avoid naming conflicts.

The Auto-components' job is to provide factory methods for all public bindings in its package that depend (directly or transitively) on a non-public binding in the same package. Any parameters of these factory methods have `public` types. An Auto-component is always `public` and can be used like a factory from the other components. Then the instantiation of package-private types is handled exclusively by their local Auto-component, and there is no more need for casts.

**Comment by h908714124** [comment]
The following example shows how casts are currently used in the generated code.

Package `com.example.main`:
```java
@Component
public interface MainComponent {
    MainDependency mainDependency();
    @Component.Factory
    interface Factory {
        MainComponent create();
    }
}
```

Package `com.example.sub`:
```java
public class MainDependency {
    @Inject
    MainDependency(TransitiveDependency dependency) {
    }
}

// not public
class TransitiveDependency {
    @Inject
    TransitiveDependency() {
    }
}
```

Then the generated class `DaggerMainComponent` contains the following method:

```java
@Override
public MainDependency mainDependency() {
  return MainDependency_Factory.newInstance(TransitiveDependency_Factory.newInstance());
}
```

Thus `TransitiveDependency_Factory` is used in `DaggerMainComponent`, even though the type it creates is not visible from `com.example.main`. This works because the parameter of `MainDependency_Factory.newInstance` has type `Object`, and is cast down to `TransitiveDependency`.

```java
public static MainDependency newInstance(Object dependency) {
  return new MainDependency((TransitiveDependency) dependency);
}
```

**Comment by h908714124** [comment]
In the new mode, a new class `DaggerMainComponent_AutoComponent` (name tbd) would be generated in package `com.example.sub`. It would contain a public method `mainDependency`:

```java
// in DaggerMainComponent_AutoComponent
public MainDependency mainDependency() {
    return new MainDependency(new TransitiveDependency());
}
```

In `DaggerMainComponent`, the `mainDependency` method would look like this:

```java
// in DaggerMainComponent
@Override
public MainDependency mainDependency() {
    return DaggerMainComponent_AutoComponent.create().mainDependency();
}
```

Method `MainDependency_Factory.newInstance` is now only used from within its package. Thus its parameter can have the correct type.

```java
// MainDependency_Factory
static MainDependency newInstance(TransitiveDependency dependency) {
    return new MainDependency(dependency);
}
```

**Comment by Chang-Eric** [comment]
> This casting pattern works, but seems hacky and there should be a better way. Casting breaks type safety and should be avoided. It could lead to problems in the future. For instance, what if Java adds types that do not extend from Object?

Are there more concrete reasons for pursuing something like this? Adding a new generated code mode is something that comes with a fair amount of maintenance burden, so we generally aren't keen to add new modes without good cause. While casts aren't great, with generated code we can generally make them safe (Hilt has to do a fair amount of this already) and I don't feel like the possibility of Java adding types that don't extend Object is worth adding this extra complexity.

**Comment by Chang-Eric** [comment]
> but with valhalla around the corner, I think it would be worthwile to explore.

Sorry I haven't actually had a chance to look into Valhalla, but is there a planned change you know about that will cause problems with the current code?

**Comment by h908714124** [comment]
From what I've heard, they're adding ability to define your own primitive types, and auto-boxing won't work for these. So casting these to Object may not work like it does for `int` and friends.

**Comment by JakeWharton** [comment]
That is something which can be addressed in the later previews of when valhalla is shipping in a few years. Considering how many times the proposal and implementation has changed in the last ~8 years, making speculative changes today does not seem wise.

**Comment by h908714124** [comment]
OK but removing cast is a always good idea, regardless of Valhalla.

**Comment by JakeWharton** [comment]
In regular code, sure. In generated code it matters less. If it doesn't affect the performance once C2 kicks in then it's not really hurting anything. The annotation processor guarantees safety and the generated code is effectively implementation detail.

**Comment by h908714124** [comment]
> The guiding principle is to generate code that mimics the code that a user might have hand-written to ensure that dependency injection is as simple, traceable and performant as it can be.

**Comment by Chang-Eric** [comment]
I can update the docs to be clearer, but that's more like an aspiration and guide when it doesn't make other compromises. We are straying more and more from that though as we find out that the code a user might have hand-written is not performant or runs into visibility issues like this one (where the user would probably just modify the visibility since they are writing the code).

**Comment by h908714124** [comment]
What I meant to say is that the generated code does not look like what I would have written by hand. And no, I would not make some types public, because I would not attempt to write the entire wiring logic in a single class.

If readability is not a primary goal anymore, then yes I think the docs should indeed be updated. Otherwise it can be frustrating to read the code and find out that you don't understand it. Another thing that's quite confusing is the way singleton scope (or scopes in general) are implemented. Many people who are familiar with DI frameworks like Spring would expect there to be a `Map<Class<?>, Object>` somewhere. But that's nowhere to be found, instead you have these nested providers and DoubleChecks, which is way harder to grok.

**Comment by JakeWharton** [comment]
That's because those DI libraries are just sugar on top of a service locator. Dagger 1 was like that. Dagger 2 is much more like manually-written DI scaled to massive application.

Note that even in Dagger 1, Spring, Guice, etc. you absolutely will find double-checked locking wrappers around factories when scoping is in use.

**Comment by Chang-Eric** [comment]
We have multiple goals of which readability is one. We aren't going to single-mindedly pursue it to the detriment of other goals like performance and usability though. It is unfortunate that the code didn't match what you were expecting to find but everyone is going to go in with different expectations.

I don't think we're going to reach much of an agreement here, and it looks like there isn't any strong reason to change our code generation at the moment, so I'm going to close this now.
