### ISSUE TITLE
Is there way I can use Dagger without Maven or Gradle build system?

### ISSUE THREAD

**Issue by wonsuc** [google/dagger#3344]
The project I'm currently participated in doesn't use Maven or Gradle, and only importing 3rd party libraries with JAR files.  

Is there any way I can configure to import Dagger without Maven or Gradle?  

I'm currently using IntelliJ.

**Comment by JakeWharton** [comment]
You can follow the instructions at https://www.jetbrains.com/help/idea/annotation-processors-support.html. Just remember you need to resolve all of the transitive dependencies of both the runtime and the annotation processor.

**Comment by wonsuc** [comment]
@JakeWharton Thanks, Jake.
