### ISSUE TITLE
Performance regressions in Dagger 2.40.1 and 2.41

### ISSUE THREAD

**Issue by cesar1000** [google/dagger#3368]
We noticed a significant regression in Dagger processing time in our application module when switching to Dagger 2.40.1 from Dagger 2.40. Here are some records of time spent in Dagger while compiling the same build on both versions:

* Dagger 2.40: 34.232s, 38.512s
* Dagger 2.40.1: 1m 0.669s, 1m 4.612s, 57.968s, 57.025s

Comparing profiles of both builds, it looks like 2.40.1 spends a huge amount of time in `JavacElement.getAllAnnotations()`, with a particular hot spot in the `getAnnotatedAnnotations()` call in `Scopes.scopeOf()`. The issue was likely introduced [here](https://github.com/google/dagger/commit/43299985736bb1a5ea7ae8ec67f89773658fa21d#diff-effd9377199379334077dfd236d3e6af3d9121fb30d654144014fc9f9df9c8deL68-R63), since `AnnotationMirrors.getAnnotatedAnnotations()` operates on a cached list of annotations, while `getAnnotatedAnnotations()` creates one from scratch.

Also, the upgrade from Dagger 2.40.5 to Dagger 2.41 contains a similar a similar regression:

* Dagger 2.40.5: 56.491s, 59.669s
* Dagger 2.41: 1m 30.598s, 1m 17.915s

This second regression seems to share the root cause, with the new hot spot in the `InjectionAnnotations. hasScopeAnnotation()` call in `InjectionAnnotations.getScopes()`. This also ends up in `JavacElement.getAllAnnotations()`, so I'd expect a solution to the issue above to deal with this one as well.

**Comment by bcorso** [comment]
Thanks Cesar for reporting this!

I'll start by adding a cache in `JavacElement` for its set of `JavacAnnotation` instances. We can likely also speed things up by storing that cache as a `Map<ClassName, JavacAnnotation>` so that subsequent calls to `getAnnotation(ClassName)` and `hasAnnotation(ClassName)` become `O(1)` rather than `O(N)`.

Btw, does the profile tell you which part of `JavacElement.getAllAnnotations` is the issue? In particular, I'm wondering if it's `unwrapRepeatedAnnotationsFromContainer` that's taking the majority of the time or something else.

**Comment by cesar1000** [comment]
Yeah, adding a cache is great. I'm not sure that a map is worthwhile though, since `getAllAnnotations` requires a list of values, when can't be obtained in constant time from the map. Also, annotation lookups are likely to be fast enough even with a list, since most elements use a really small number of annotations anyway.

As for the cost of `Javac.getAllAnnotations`, it's indeed `unwrapRepeatedAnnotationsFromContainer` taking most of the time:

![image](https://user-images.githubusercontent.com/2517200/165438935-432a277f-06d9-4f91-a98a-15976b53f4d5.png)

Does that make sense though? I'd expect this method to bail out early for most annotations.

**Comment by bcorso** [comment]
> Does that make sense though? I'd expect this method to bail out early for most annotations.

This may be the same issue I fixed here https://github.com/androidx/androidx/commit/e833d85bd9d4af715f2f60183709f0b53a68be00.

Although I upstreamed that fix a few months back in XProcessing, I don't think our shaded jar was updated within Dagger yet. Let me update our shaded jar tomorrow. Once that's submitted you can try out the HEAD snapshots to test out whether that fixes this regression for you.

**Comment by bcorso** [comment]
Thanks @cesar1000 for verifying the new HEAD snapshots with https://github.com/androidx/androidx/commit/e833d85bd9d4af715f2f60183709f0b53a68be00 fixes the issue.

For now, I'm going to go ahead and close this issue, as I believe adding the cache shouldn't be necessary anymore. We can reopen if we find evidence of the contrary.

**Comment by cesar1000** [comment]
Excellent, thanks, Brad!
