### ISSUE TITLE
The warning message for Component.Factory seems incorrect unless I'm doing something wrong

### ISSUE THREAD

**Issue by azabost** [google/dagger#3371]
Hi. I'm trying to reuse the Dagger's component in instrumented tests to obtain a reference to an injectable instance that would allow me to clear the app's data between some test runs.

I exposed `AppComponent` in `App` like this:

```kotlin
class App : DaggerApplication() {

    @Inject
    @VisibleForTesting
    lateinit var appComponent: AppComponent

    override fun applicationInjector(): AndroidInjector<out DaggerApplication> {
        return DaggerAppComponent.factory().create(this)
    }
}
```

and I added `getLogout()` method in `AppComponent`:

```kotlin
@Singleton
@Component(modules = [LogoutModule::class]) // LogoutModule is a @Module interface with a single @Binds method
interface AppComponent : AndroidInjector<App> {
    @Component.Factory
    interface Factory : AndroidInjector.Factory<App>

    fun getLogout(): Logout
}
```

so that in the instrumented tests I can do something like this:

```kotlin
ApplicationProvider.getApplicationContext<App>().appComponent.getLogout().logout()
```

However, with that setup, Dagger gives me the following warning:

```
warning: [dagger.android.AndroidInjector.Factory.create(T)] com.example.AppComponent.Factory.create() returns dagger.android.AndroidInjector<com.example.App>, but com.example.AppComponent declares additional component method(s): getLogout(). In order to provide type-safe access to these methods, override create() to return com.example.AppComponent
    public static abstract interface Factory extends dagger.android.AndroidInjector.Factory<com.example.App> {
                           ^
```

It seems like it wants me to change the `AppComponent.Factory` to this:

```kotlin
@Component.Factory
interface Factory : AndroidInjector.Factory<App> {
    override fun create(instance: App): AppComponent // explicitly specified subtype
}
```

but if I do it, the build fails with the following error:

```
error: @Component.Factory method has parameters for modules or components that aren't required: [org.jetbrains.annotations.NotNull com.example.App instance] - com.example.AppComponent.Factory
    public static abstract interface Factory extends dagger.android.AndroidInjector.Factory<com.example.App> {
                           ^
```

So either I'm doing something wrong or Dagger can't really work that way and the recommendation it gives in the warning is wrong and misleading. If the latter is the case then I think it's a bug that should be fixed. However, I would actually prefer it to support that use case instead, unless you have a better idea of how I could re-use `AppComponent` in instrumented tests to get/inject something I might need there.

Just to be clear: I'm not trying to substitute any dependencies for testing purposes. I want to access the same dependency (`Logout`) that is normally used by the production code.

I tried this in versions `2.37` and `2.41` and their behaviour was the same.

**Comment by bcorso** [comment]
Hi @azabost,

It's complaining because you need to add `@BindsInstance` to your method parameter:

```kotlin
    override fun create(@BindsInstance instance: App): AppComponent
```

**Comment by azabost** [comment]
Thanks a lot, @bcorso. Adding `@BindsInstance` resolved my problem.
