### ISSUE TITLE
Missing 2.1-SNAPSHOT from maven repo

### ISSUE THREAD

**Issue by mrsasha** [google/dagger#338]
Hi guys,

could you put the missing 2.1-SNAPSHOT version in the repo again? Apparently there's no way to force the substitute during annotation processing (or at least I haven't found any), and gradle doesn't tell me which library fails:
```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:apt'.
   > Could not find com.google.dagger:dagger-compiler:2.1-SNAPSHOT.
     Searched in the following locations:
	 ...
     Required by:
         sharethemealandroid:app:unspecified
```

**Comment by tbroyer** [comment]
> Apparently there's no way to force the substitute during annotation processing (or at least I haven't found any)

What do you mean by _force the substitute_?

Can't you update to use 2.1?

**Comment by JakeWharton** [comment]
Releasing a proper version deletes snapshots automatically.

**Comment by mrsasha** [comment]
Well, the problem is that some of the external libraries use it during annotation processing, and apparently there's no way to substitute them at that point. I'm currently using this in my gradle file, but still get the error above:

```configurations.all {
        resolutionStrategy {
            force 'com.google.dagger:dagger:2.1'
            force 'com.google.dagger:dagger-compiler:2.1'
            force 'com.google.dagger:dagger-producer:2.1'

            dependencySubstitution {
                substitute module('com.google.dagger:dagger-compiler:2.1-SNAPSHOT') with module('com.google.dagger:dagger-compiler:2.1')
            }
        }
	}```

**Comment by mrsasha** [comment]
Also, as a side note, I thought that the idea of dependency injection is exactly not to have to update to the new version as soon as it's out and not to have the broken builds. Deleting the snapshot releases means that everybody in the world would need to update immediately. Maybe just point to the new release instead of deleting the snapshot from the repo completely?

**Comment by ronshapiro** [comment]
You shouldn't be depending on a SNAPSHOT in your build for this reason. It's not deterministic and it makes your builds non hermetic. 

You should be able to update everything to `2.1` and have the correct functionality.

You touch on a larger issue, which is that we haven't been releasing minor builds so frequently (2.0.2 was released in October-ish) which means that in order to have been getting the bug fixes/optimizations the snapshot was "necessary". But if you ever need to use a snapshot in your build beyond just testing, it's a good idea to copy that snapshot somewhere where you have control (ex. your code's repo, a private maven server, etc). 

Moving forward, one of our goals is to have much more frequent releases so that you don't have to consider pulling in a SNAPSHOT at all. I hope that helps you out in the future.

**Comment by tbroyer** [comment]
@mrsacha You may want to ask on StackOverflow why your configuration above is not taken in to account.
If you have it on your _root_ `build.gradle`, make sure it's within a `subprojects` or `allprojects` script block so it applies to the `app` project; or move it to your `app/build.gradle`.

**Comment by hamen** [comment]
How can I force a third-party library to not use SNAPSHOT? Is there a way to find out which library is using it and use Gradle to force it to a specific version? Thanks.

**Comment by JakeWharton** [comment]
It's not this project or Google that's deleting them, that's just how
Sonatype, the proxy to Maven central and host of the snapshots repo, works.

**Comment by tbroyer** [comment]
@hamen Forcing: declare the dependency yourself, or use a`resolutionStrategy`'s `force` like @mrsasha above; finding: `./gradlew dependencies` (or `./gradlew app:dependencies` for a typical Android project)

**Comment by mrsasha** [comment]
ok, so I found a workaround for this and a way to prevent this error if you use libraries that are outside of your control. It might be useful to other people who encounter the same problem.

**THE WORKAROUND**: we cannot control external repo content, but what we CAN do is put the missing libraries in the local repo used for support libraries, usually here: '~/Library/Android/sdk/extras/google/m2repository/com/google/`. How to do this? When seeing the above referenced error:
```
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugCompile'.
  > Could not find com.google.dagger:dagger:2.1-SNAPSHOT.
    Searched in the following locations:
```
this 'searched in the following locations' also mentions local repo - it will have file and not http URL - with a list of files he failed to find, like this:
```
file:~/Library/Android/sdk/extras/google/m2repository/com/google/dagger/dagger/2.1-SNAPSHOT/maven-metadata.xml
        file:~/Library/Android/sdk/extras/google/m2repository/com/google/dagger/dagger/2.1-SNAPSHOT/dagger-2.1-SNAPSHOT.pom
        file:~/Library/Android/sdk/extras/google/m2repository/com/google/dagger/dagger/2.1-SNAPSHOT/dagger-2.1-SNAPSHOT.jar
```

Now you can go and download the relevant files you want to use from jcenter.com or any other repo (I used the 2.1 release version), rename them as SNAPSHOT files, and put them in the above referenced folders. Gradle will now find them and you don't have to look for the offending library (at least not immediately).

**HOW TO PREVENT** (for obvious reasons, you can do this only when you've fixed the problem):

- enable offline builds in Android Studio (`File -> Settings -> Build, Execution, Deployment -> Build Tools -> Gradle -> Offline work option`)
**OR**
- use `gradle build -g ./gradle-libs` to put cached libraries in your local folder `./gradle-libs` and then build using `gradle assemble --offline -g ./gradle-libs`; refresh the libraries only when you update gradle file, but make a backup of the cached libs folder in case something goes wrong.

**Comment by ronshapiro** [comment]
I wouldn't recommend putting it there, it probably makes more sense to just install it locally in the default maven repo (`~.m2/repository`). You can:

```sh
git clone https://github.com/google/dagger
git checkout LAST_COMMIT_AT_2.1-SNAPSHOT
mvn install
```

But I would highly recommend submitting issues to your upstream library maintainers and just get them to update to 2.1. It's an easy upgrade and will solve issues for all of their clients.

**Comment by mrsasha** [comment]
Yes, once it's fixed then it's trivial to do `gradle app:dependencies` to find which library uses which version and then submit an issue or a fix.
