### ISSUE TITLE
Support for MapStruct implementation

### ISSUE THREAD

**Issue by wonsuc** [google/dagger#3397]
[MapStruct](https://github.com/mapstruct) supports several [DI solutions](https://mapstruct.org/documentation/dev/reference/html/#using-dependency-injection).  

However [`MapStruct` only adds a constructor if there is at least one dependency used. If there are no dependencies then no constructor is created and thus it can't be injected.](https://github.com/mapstruct/mapstruct/issues/1617)  

With this limitation, it's hard to use `Dagger` for `MapStruct`'s mapper class.  

There is a [PR](https://github.com/mapstruct/mapstruct/issues/1617) for `Dagger` support but still in progress.  

I wonder if `Dagger` deverlopers can support for complete implementation with `MapStruct` framework.

**Comment by bcorso** [comment]
@wonsuc unfortunately, fixing the bug in MapStruct is not something that our team will be able to devote resources to, but it sounds like they are [accepting PRs from community members](https://github.com/mapstruct/mapstruct/issues/1617#issuecomment-500362762) , so you should feel free to give it a shot yourself.

In the meantime, you should be able use Dagger's `@Provides` methods to provide the binding to workaround the bug in MapStruct, as mentioned in https://github.com/mapstruct/mapstruct/issues/1617#issuecomment-614080824.
