### ISSUE TITLE
Cannot import 2.1-SNAPSHOT

### ISSUE THREAD

**Issue by vekexasia** [google/dagger#340]
Hello there,

is there something going on with the snapshosts repo? gradle complains about it :(

https://oss.sonatype.org/content/repositories/snapshots/com/google/dagger/

Does not contain any further "dagger" folder

**Comment by JakeWharton** [comment]
Dupe of #338.

**Comment by JakeWharton** [comment]
TL;DR: Use 2.1 release version.
