### ISSUE TITLE
Kotlin 1.7.0 - A failure occurred while executing org.jetbrains.kotlin.gradle.internal.KaptWithoutKotlincTask$KaptExecutionWorkAction

### ISSUE THREAD

**Issue by Drjacky** [google/dagger#3425]
> Execution failed for task ':presentation:kaptDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.gradle.internal.KaptWithoutKotlincTask$KaptExecutionWorkAction
   > java.lang.reflect.InvocationTargetException (no error message)

Hilt: 2.40.1
AGP: 7.2.1
Kotlin: 1.7.0

https://scans.gradle.com/s/mhx6s3m7orxpe

And Hilt: 2.42:
> Execution failed for task ':app:hiltAggregateDepsDebug'.
> A failure occurred while executing dagger.hilt.android.plugin.task.AggregateDepsTask$WorkerAction
   > com.squareup.javapoet.ClassName.canonicalName()Ljava/lang/String;

**Comment by Drjacky** [comment]
This helped: https://github.com/google/dagger/issues/3068#issuecomment-999118496

**Comment by BraisGabin** [comment]
Related with #3383. I add this comment because this is the first result in google but the issue that fixed my error is in that other issue.

**Comment by ZacSweers** [comment]
@BraisGabin I don't think that's related at all as this is a gradle build classpath issue
