### ISSUE TITLE
Question: KSP Processor Priority

### ISSUE THREAD

**Issue by tamimattafi** [google/dagger#3465]
Hello! Thank you first this awesome API!
However, I'm trying to generate some code that is going to be used by other processors to generate other code. Here's a link to the processor: https://github.com/tamimattafi/android-room-compound

Everything works fine if you clean and rebuild the project, but sometimes when you try to run the app, other annotation processors try to generate their code by mine isn't generate yet, and it gives me unresolved symbol exception. Is there a way to give my processor more priority? So it always runs first, before any other processors?

**Comment by bcorso** [comment]
Hi @tamimattafi, this question would be better on something like stackoverflow since it's not specifically related to Dagger. However, feel free to link the question here after you post it and I can respond there.

**Comment by tamimattafi** [comment]
Hello! I'm so sorry, I thought I wrote this issue on ksp repository, please forgive my mistake.
Here's a link to a new issue: https://github.com/google/ksp/issues/1043
