### ISSUE TITLE
Unsupported metadata version when using Hilt 2.42 with Kotlin 1.7.10

### ISSUE THREAD

**Issue by EliottLujan** [google/dagger#3470]
``` 
> Task hiltJavaCompileDebug
error: [Hilt]
  Unsupported metadata version. Check that your Kotlin version is >= 1.0: java.lang.IllegalStateException: Unsupported metadata version. Check that your Kotlin version is >= 1.0
        at dagger.internal.codegen.kotlin.KotlinMetadata.metadataOf(KotlinMetadata.java:206)
        at dagger.internal.codegen.kotlin.KotlinMetadata.from(KotlinMetadata.java:187)
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
```

Versions
- Dagger Hilt 2.42
- Kotlin 1.7.0 or 1.7.10
- Gradle 7.5

I'm guessing this is because Dagger 2.42 still uses [kotlinx-metadata-jvm:0.4.2](https://github.com/google/dagger/blob/7f6e91bece5e7e4cca6c25a88abb255830c38a6b/WORKSPACE#L268) which is for Kotlin 1.6 and upgrating to [kotlinx-metadata-jvm:0.5.0](https://github.com/JetBrains/kotlin/blob/master/libraries/kotlinx-metadata/jvm/ChangeLog.md#050) which is for Kotlin 1.7 should do the trick ?

**Comment by pacsinta** [comment]
For me the hilt version 2.42 is working with kotlin version 1.7.0.

My project gradle is:
```
buildscript {
    ext {
        compose_version = '1.3.0-alpha01'
    }

    dependencies {
        classpath 'com.google.dagger:hilt-android-gradle-plugin:2.42'
    }
}// Top-level build file where you can add configuration options common to all sub-projects/modules.
plugins {
    id 'com.android.application' version '7.4.0-alpha08' apply false
    id 'com.android.library' version '7.4.0-alpha08' apply false
    id 'org.jetbrains.kotlin.android' version '1.7.0' apply false
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

```

My app dependencies are:
```
//hilt
implementation 'com.google.dagger:hilt-android:2.42'
implementation 'androidx.hilt:hilt-navigation-compose:1.0.0'
kapt 'com.google.dagger:hilt-compiler:2.42'
kapt "androidx.hilt:hilt-compiler:1.0.0"
```

**Comment by danysantiago** [comment]
@EliottLujan, you might be having a different issue than just an old metadata-jvm, since [0.4.2](https://github.com/JetBrains/kotlin/blob/master/libraries/kotlinx-metadata/jvm/ChangeLog.md#040) supports Kotlin 1.7.

**Comment by EliottLujan** [comment]
After checking again I noticed that all of our dependencies were using dagger 2.42 except for the Hilt plugin which was still on version 2.41..

It worked when bumping it to 2.42. Sorry for the inconvenience and the false issue 😖 

Thank you for answering this fast, I'm closing the issue

**Comment by Areeb786123** [comment]
I reduced my kotlin version 1.90 to 1.8.0 and room version to 2.5.6 it works for me
