### ISSUE TITLE
Dagger generates code with wrong parameter names for member injection

### ISSUE THREAD

**Issue by vRallev** [google/dagger#3476]
This issue is very similar to #3401. The bug for subcomponents is resolved, but there's still an issue with member injection. The generated code for member injection looks like this:
```java
    @Override
    public void inject(Abc abc) {
      injectAbc(arg0);
    }
```
I've updated the sample here: https://github.com/vRallev/anvil/tree/ralf/dagger-bug Notice that the branch is `ralf/dagger-bug`. You should be able to reproduce the bug by running `./gradlew test`. This issue happens with Dagger 2.43 and the latest snapshot.

**Comment by taehwandev** [comment]
동일한 이슈가 발생한다. custom class에서 inject하는 경우이다.

```
public void inject(CustomClass instance) {
 injectCustomClass(arg0);
}
```

**Comment by bcorso** [comment]
Thanks for the repro! I should have a fix out today and we can do a 2.43.1 release next week.

**Comment by vRallev** [comment]
That would be wonderful. Thanks!

**Comment by chrisjenx** [comment]
The funny thing is I wasn't having an issue until 2.43, so had to downgrade to 2.42, I'll wait until 2.43.1 and try again. Thanks for the quick fixes y'all

**Comment by vRallev** [comment]
The fix works. Thanks!
