### ISSUE TITLE
Using multiple keys with Map Multibindings

### ISSUE THREAD

**Issue by DirajHS** [google/dagger#3507]
I am trying to create an architecture to handle UI events and map it to classes which can handle them. In this case, multiple events can be handled by a single event handler and this is where I am trying to bind multiple types of the events to the same instance of the class. The setup roughly look like this:
* Event:
```kotlin
sealed interface Event {
 //Different types of events
}
```
* Map key annotation:
```kotlin
@Retention
@MapKey(unwrapValue = true)
annotation class EventHandlerClassKey(val value: Array<KClass<out Event>>)
```
* Bindings module:
```kotlin
@Module
@InstallIn(ViewModelComponent::class)
abstract class ProducersModule {
  @Binds
  @IntoMap
  @EventHandlerClassKey(values = [Event.SaveOffer::class, Event.RemoveOffer::class})
  abstract fun bindOffersEventHandler(offerProducer: OfferProducer):  Producer
 
  //Trying to map other events similarly
}
```
With this setup, if I try to build, I am getting the following error:
```shell
Caused by: java.lang.IllegalArgumentException: com.example.qualifiers.EventHandlerClassKey.value cannot be an array
	at dagger.internal.codegen.binding.MapKeys$1.visitArray(MapKeys.java:122)
	at dagger.internal.codegen.binding.MapKeys$1.visitArray(MapKeys.java:117)
```
I see a similar issue [#701](https://github.com/google/dagger/issues/701) which is already closed, but couldn't find any documentation on how to support multiple keys for Map multi binding. 
Is this the right way to do it?

**Comment by bcorso** [comment]
For array values, you'll need `unwrapValue = false`.

See https://dagger.dev/dev-guide/multibindings#complex-map-keys and the section below for how to use it.

**Comment by DirajHS** [comment]
> For array values, you'll need `unwrapValue = false`.
> 
> See https://dagger.dev/dev-guide/multibindings#complex-map-keys and the section below for how to use it.

Thanks, this worked. I had initially tried it but was facing some errors. After adding the annotations dependency correctly, it worked.

**Comment by VincentRong** [comment]
@DirajHS Hi, ran into similar issue and then use `unwrapValue = false`, but still failed in error
@AutoAnnotation is a necessary dependency if @MapKey(unwrapValue = true)
, couldn't figure out how to solve it in Kotlin.
Wondering how you solve the issue? thanks!

**Comment by DirajHS** [comment]
Have you added the [AutoValue](https://github.com/google/auto#subprojects) dependency correctly? That should resolve the annotation error
