### ISSUE TITLE
Improper method injection in case of method overrides

### ISSUE THREAD

**Issue by stephanenicolas** [google/dagger#351]
In the simple example, if you change Thermosiphon to use method injection : 

``` java
class Thermosiphon implements Pump {
  private Heater heater;

  @Inject
  public Thermosiphon() {
  }


  @Inject
  void setHeater(Heater heater) {
    this.heater = heater;
  }

  @Override public void pump() {
    if (heater.isHot()) {
      System.out.println("=> => pumping => =>");
    }
  }
}
```

and then extend it : 

``` java
class Thermosiphon2 extends Thermosiphon{

  @Inject
  public Thermosiphon2() {
  }

  @Inject
  void setHeater(Heater heater) {
    super.setHeater(heater);
  }
}
```

then both generated member injector for both classes will call setHeater, which is incorrect. In Thermosiphon2 instances, the Thermosiphon.setHeater method should never be called, it has been overriden. Indeed to be more precise, the injected overridden method is being called twice. This used to work in Guice..

**Comment by gk5885** [comment]
With what version are you having this issue?

**Comment by ronshapiro** [comment]
Feel free to reopen this if you're still experiencing it in `2.10`. Please also include your build system.
