### ISSUE TITLE
Hilt depend on fragment 1.5.0 which is incompatible with lint 30.4.0-alpha09

### ISSUE THREAD

**Issue by ColtonIdle** [google/dagger#3519]
I updated to latest hilt and latest alpha lint and lint fails due to an issue in fragments 1.5.0. I don't use fragments and saw that it was coming from hilt.

```
+--- com.google.dagger:hilt-android:2.43.2
|    +--- androidx.fragment:fragment:1.5.0
```

Explicitly depending on androidx.fragment:fragment:1.5.1 (note 1.5.1 not 1.5.0) fixes the issue. I'm assuming you will update at some point, but just leaving this here as a heads up. Thanks

**Comment by kuanyingchou** [comment]
I updated fragment to 1.5.1 and it will be shipped in the next release. Thanks for reporting!
