### ISSUE TITLE
How to fix issue @JvmDefault with version dagger 2.43.2

### ISSUE THREAD

**Issue by longquangpham90** [google/dagger#3520]
I have update new version dagger 2.43.2
IDE version:

> Android Studio Chipmunk | 2021.2.1 Patch 2
Build #AI-212.5712.43.2112.8815526, built on July 10, 2022
Runtime version: 11.0.12+0-b1504.28-7817840 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.0.1
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 12
Registry: external.system.auto.import.disabled=true
Non-Bundled Plugins: com.vladsch.PluginDevelopersToolbox (1.2.0), com.intellij.marketplace (212.5712.51), com.robohorse.robopojogenerator (2.3.6), com.github.beansoft.reatnative.idea.free (2022.1.1), org.jetbrains.kotlin (212-1.7.10-release-333-AS5457.46), cn.mycommons.serializednamegen (0.8), com.nbadal.ktlint (0.10.0), cn.vove7.ide.plugin.eventbus_navigator (1.2.3), zielu.gittoolbox (212.9.7), com.developerphil.adbidea (1.6.6), com.jetbrains.kmm (0.3.3(212-1.7.0-RC-release-217-IJ)-104)

But we have issue
`Inheritance from an interface with '@JvmDefault' members is only allowed with -Xjvm-default option`
Pls suggest solution for me fixbug its
Thanks

**Comment by bcorso** [comment]
Hi @longquangpham90, 

Can you post the entire stacktrace? (I'm interested in the part that pointed you to Dagger).

From the error message it sounds like the solution is to enable the `jvm-default` option. From a quick search, it looks like it can be enabled using (not tested):

```groovy
kotlinOptions {
    freeCompilerArgs = ['-Xjvm-default=enable']
}
```
