### ISSUE TITLE
`dagger-android-processor` still always enables formatting

### ISSUE THREAD

**Issue by ZacSweers** [google/dagger#3531]
[This line](https://github.com/google/dagger/blob/b5990a0641a7860b760aa9055b90a99d06186af6/java/dagger/android/processor/AndroidProcessor.java#L59) does not respect the value of the formatting compiler option.

I can take a shot at a PR if you're open to it

**Comment by ZacSweers** [comment]
Went ahead and made one in #3532

**Comment by Chang-Eric** [comment]
Thanks, I'll go ahead and patch in your PR and submit it. Unfortunately, our tooling is complex enough that it is easiest to just do it this way rather than have you actually submit the PR. You should be credited as the original author on the commit though. Thanks!

**Comment by Chang-Eric** [comment]
Just updating for clarification, we actually decided to go another route and remove the formatting entirely since we don't format in Hilt and so adding a flag doesn't really feel worth it.
