### ISSUE TITLE
Hilt: Inherited fragment class not generated

### ISSUE THREAD

**Issue by baudouxbenjamin** [google/dagger#3533]
Hi,

I've the following inheritance chain:

ZipCodeFragment:
```kotlin
class ZipCodeFragment : BaseUserOnboardingFragment(R.layout.user_onboarding_zip_code_fragment) { 
    // code
}
```

BaseUserOnboardingFragment:
```kotlin
abstract class BaseUserOnboardingFragment(@LayoutRes layoutRes: Int = 0) : BaseFragment(layoutRes) { 
    // code
}
```

BaseFragment
```kotlin
abstract class BaseFragment : Fragment, ErrorListener { 

    constructor() : super()
    constructor(@LayoutRes layoutRes: Int) : super(layoutRes)
}
```

Following the steps described [here](https://dagger.dev/hilt/gradle-setup#why-use-the-plugin), I've annotated my `ZipCodeFragment` as follow:

```kotlin
@AndroidEntryPoint(BaseUserOnboardingFragment::class)
class ZipCodeFragment : Hilt_ZipCodeFragment(R.layout.user_onboarding_zip_code_fragment) { 
    // code
}
```
When compiling, I got the following error as if the Hilt class is not properly generated:

```
error: [Hilt]
public final class ZipCodeFragment {
             ^
  @AndroidEntryPoint class expected to extend Hilt_ZipCodeFragment. Found: Object
  [Hilt] Processing did not complete. See error above for details.
```
What am I missing?

**Comment by bcorso** [comment]
> @AndroidEntryPoint class expected to extend Hilt_ZipCodeFragment. Found: Object

The fact that the error message says "`Found: Object`" rather than the actual super class usually indicates that you need to enable [`correctErrorTypes`](https://kotlinlang.org/docs/kapt.html#non-existent-type-correction) (also see https://dagger.dev/hilt/gradle-setup#using-hilt-with-kotlin):

```groovy
kapt {
 correctErrorTypes true
}
```

**Comment by baudouxbenjamin** [comment]
I've found the issue: `abstract class BaseUserOnboardingFragment(@LayoutRes layoutRes: Int = 0)` has a default constructor parameter which is not supported yet.
