### ISSUE TITLE
Gradle sync failed by following reasons

### ISSUE THREAD

**Issue by sanjanat** [google/dagger#355]
Error:Could not find com.google.dagger:dagger-compiler:2.0-SNAPSHOT.
Searched in the following locations:
    file:/C:/Users/userDownloads/android-studio-ide-143.2609919-windows/android-studio/gradle/m2repository/com/google/dagger/dagger-compiler/2.0-SNAPSHOT/maven-metadata.xml
    file:/C:/Users/user/Downloads/android-studio-ide-143.2609919-windows/android-studio/gradle/m2repository/com/google/dagger/dagger-compiler/2.0-SNAPSHOT/dagger-compiler-2.0-SNAPSHOT.pom
    file:/C:/Users/user/Downloads/android-studio-ide-143.2609919-windows/android-studio/gradle/m2repository/com/google/dagger/dagger-compiler/2.0-SNAPSHOT/dagger-compiler-2.0-SNAPSHOT.jar
    https://jcenter.bintray.com/com/google/dagger/dagger-compiler/2.0-SNAPSHOT/maven-metadata.xml
    https://jcenter.bintray.com/com/google/dagger/dagger-compiler/2.0-SNAPSHOT/dagger-compiler-2.0-SNAPSHOT.pom
    https://jcenter.bintray.com/com/google/dagger/dagger-compiler/2.0-SNAPSHOT/dagger-compiler-2.0-SNAPSHOT.jar
    https://repo1.maven.org/maven2/com/google/dagger/dagger-compiler/2.0-SNAPSHOT/maven-metadata.xml
    https://repo1.maven.org/maven2/com/google/dagger/dagger-compiler/2.0-SNAPSHOT/dagger-compiler-2.0-SNAPSHOT.pom
    https://repo1.maven.org/maven2/com/google/dagger/dagger-compiler/2.0-SNAPSHOT/dagger-compiler-2.0-SNAPSHOT.jar
    https://oss.sonatype.org/content/repositories/snapshots/com/google/dagger/dagger-compiler/2.0-SNAPSHOT/maven-metadata.xml
    https://oss.sonatype.org/content/repositories/snapshots/com/google/dagger/dagger-compiler/2.0-SNAPSHOT/dagger-compiler-2.0-SNAPSHOT.pom
    https://oss.sonatype.org/content/repositories/snapshots/com/google/dagger/dagger-compiler/2.0-SNAPSHOT/dagger-compiler-2.0-SNAPSHOT.jar
    file:/D:/Android Installation/Android/Android Lollipop SDK-Eclipse Juno-ADT 23.0.4/android-sdk/extras/android/m2repository/com/google/dagger/dagger-compiler/2.0-SNAPSHOT/maven-metadata.xml
    file:/D:/Android Installation/Android/Android Lollipop SDK-Eclipse Juno-ADT 23.0.4/android-sdk/extras/android/m2repository/com/google/dagger/dagger-compiler/2.0-SNAPSHOT/dagger-compiler-2.0-SNAPSHOT.pom
    file:/D:/Android Installation/Android/Android Lollipop SDK-Eclipse Juno-ADT 23.0.4/android-sdk/extras/android/m2repository/com/google/dagger/dagger-compiler/2.0-SNAPSHOT/dagger-compiler-2.0-SNAPSHOT.jar
    file:/D:/Android Installation/Android/Android Lollipop SDK-Eclipse Juno-ADT 23.0.4/android-sdk/extras/google/m2repository/com/google/dagger/dagger-compiler/2.0-SNAPSHOT/maven-metadata.xml
    file:/D:/Android Installation/Android/Android Lollipop SDK-Eclipse Juno-ADT 23.0.4/android-sdk/extras/google/m2repository/com/google/dagger/dagger-compiler/2.0-SNAPSHOT/dagger-compiler-2.0-SNAPSHOT.pom
    file:/D:/Android Installation/Android/Android Lollipop SDK-Eclipse Juno-ADT 23.0.4/android-sdk/extras/google/m2repository/com/google/dagger/dagger-compiler/2.0-SNAPSHOT/dagger-compiler-2.0-SNAPSHOT.jar
Required by:
    DaggerDemoApplication:app:unspecified

**Comment by JakeWharton** [comment]
Snapshots are automatically removed by Sonatype when a release is made.
Switch to version 2.2 which is the latest.

**Comment by sanjanat** [comment]
I tried but stilll error is shown like below:

Error:Could not find com.google.dagger:dagger-compiler:2.2-SNAPSHOT.
Searched in the following locations:
    file:/C:/Users/Downloads/android-studio-ide-143.2609919-windows/android-studio/gradle/m2repository/com/google/dagger/dagger-compiler/2.2-SNAPSHOT/maven-metadata.xml
    file:/C:/Users//Downloads/android-studio-ide-143.2609919-windows/android-studio/gradle/m2repository/com/google/dagger/dagger-compiler/2.2-SNAPSHOT/dagger-compiler-2.2-SNAPSHOT.pom
    file:/C:/Users/Downloads/android-studio-ide-143.2609919-windows/android-studio/gradle/m2repository/com/google/dagger/dagger-compiler/2.2-SNAPSHOT/dagger-compiler-2.2-SNAPSHOT.jar
    https://jcenter.bintray.com/com/google/dagger/dagger-compiler/2.2-SNAPSHOT/maven-metadata.xml
    https://jcenter.bintray.com/com/google/dagger/dagger-compiler/2.2-SNAPSHOT/dagger-compiler-2.2-SNAPSHOT.pom
    https://jcenter.bintray.com/com/google/dagger/dagger-compiler/2.2-SNAPSHOT/dagger-compiler-2.2-SNAPSHOT.jar
    https://repo1.maven.org/maven2/com/google/dagger/dagger-compiler/2.2-SNAPSHOT/maven-metadata.xml
    https://repo1.maven.org/maven2/com/google/dagger/dagger-compiler/2.2-SNAPSHOT/dagger-compiler-2.2-SNAPSHOT.pom
    https://repo1.maven.org/maven2/com/google/dagger/dagger-compiler/2.2-SNAPSHOT/dagger-compiler-2.2-SNAPSHOT.jar
    https://oss.sonatype.org/content/repositories/snapshots/com/google/dagger/dagger-compiler/2.2-SNAPSHOT/maven-metadata.xml
    https://oss.sonatype.org/content/repositories/snapshots/com/google/dagger/dagger-compiler/2.2-SNAPSHOT/dagger-compiler-2.2-SNAPSHOT.pom
    https://oss.sonatype.org/content/repositories/snapshots/com/google/dagger/dagger-compiler/2.2-SNAPSHOT/dagger-compiler-2.2-SNAPSHOT.jar
    file:/D:/Android Installation/Android/Android Lollipop SDK-Eclipse Juno-ADT 23.0.4/android-sdk/extras/android/m2repository/com/google/dagger/dagger-compiler/2.2-SNAPSHOT/maven-metadata.xml
    file:/D:/Android Installation/Android/Android Lollipop SDK-Eclipse Juno-ADT 23.0.4/android-sdk/extras/android/m2repository/com/google/dagger/dagger-compiler/2.2-SNAPSHOT/dagger-compiler-2.2-SNAPSHOT.pom
    file:/D:/Android Installation/Android/Android Lollipop SDK-Eclipse Juno-ADT 23.0.4/android-sdk/extras/android/m2repository/com/google/dagger/dagger-compiler/2.2-SNAPSHOT/dagger-compiler-2.2-SNAPSHOT.jar
    file:/D:/Android Installation/Android/Android Lollipop SDK-Eclipse Juno-ADT 23.0.4/android-sdk/extras/google/m2repository/com/google/dagger/dagger-compiler/2.2-SNAPSHOT/maven-metadata.xml
    file:/D:/Android Installation/Android/Android Lollipop SDK-Eclipse Juno-ADT 23.0.4/android-sdk/extras/google/m2repository/com/google/dagger/dagger-compiler/2.2-SNAPSHOT/dagger-compiler-2.2-SNAPSHOT.pom
    file:/D:/Android Installation/Android/Android Lollipop SDK-Eclipse Juno-ADT 23.0.4/android-sdk/extras/google/m2repository/com/google/dagger/dagger-compiler/2.2-SNAPSHOT/dagger-compiler-2.2-SNAPSHOT.jar
Required by:
    DaggerDemoApplication:app:unspecified

**Comment by sanjanat** [comment]
Gradle App is as follows
apply plugin: 'com.android.application'
apply plugin: 'com.neenbedankt.android-apt'

android {
    compileSdkVersion 23
    buildToolsVersion "23.0.3"

    defaultConfig {
        applicationId "com.example.sanjanat.daggerdemoapplication"
        minSdkVersion 10
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:23.2.1'
    compile 'com.android.support:design:23.2.1'

    compile 'com.google.dagger:dagger:2.2-SNAPSHOT'
    apt 'com.google.dagger:dagger-compiler:2.2-SNAPSHOT'
    provided 'org.glassfish:javax.annotation:10.0-b28'
}

**Comment by tbroyer** [comment]
Use `2.2`, not `2.2-SNAPSHOT`

**Comment by ronshapiro** [comment]
Yes, unless you have a reason to test a bugfix that hasn't yet been released, don't use snapshots. [Here you can find](http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.google.dagger%22) the latest version. 2.3 should be released shortly
