### ISSUE TITLE
is dagger can't support kotlin 1.5 any more?

### ISSUE THREAD

**Issue by zhangkevd** [google/dagger#3551]
i find 2.43.2 use kotlin 1.7.0, but my project use 1.5.32.
i search log and find 2.41 use 1.5.32
Is this an upgrade too fast? Is this necessary?

**Comment by danysantiago** [comment]
Not to be dismissive but I would spin this differently and say its Kotlin 1.5.32 thats not compatible with 1.7.

Dagger is an annotation processor and it sometimes has to read Kotlin's`@Metadata` and to do that we use a library Jetbrains provide [kotlinx-metadata-jvm](https://github.com/JetBrains/kotlin/blob/master/libraries/kotlinx-metadata/jvm/ReadMe.md). We need to keep that dependency updated as new Kotlin versions might add more information to the metadata and we want to be able to keep reading it or else bad things happen. Updating that dependency usually ends up updating our Kotlin dependencies sometimes past a point where old compiler versions (like 1.5.32) can no longer read the Kotlin module information, that's when you get that error that's something like '_Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is X, expected version is Y_'.

So Kotlin puts us in an odd position, we either update our Kotlin versions so we can support newer versions, or we don't so we can keep compatibility with older versions. Either way it seems a group of users (those that update vs those that don't) will be affected so I think it is best to keep moving forward and update. Note that this can happen with any other library, its not specific to Dagger.
