### ISSUE TITLE
HIlt Fragment unit tests are not working for multi module

### ISSUE THREAD

**Issue by srinivaasang1** [google/dagger#3552]
When running unit tests either using roboelectric for activity or viewmodels unit tests are running fine. But when we use launchFragmentInHiltContainer the dependencies are not injected. Am sure the dependencies are fine cause the application runs fine and viewmodel tests also works fine, but only when running fragment unit tests the dependencies are not injected and throws a compilation error. All guidelines to setup hilt test are followed properly as mentioned in here [Testing guide](https://developer.android.com/training/dependency-injection/hilt-testing). Want to know is there any known issue in Hilt in running fragment unit tests for multi module apps.
`error: cannot find symbol
import dagger.hilt.android.internal.testing.root.DaggerDefault_HiltComponents_SingletonC;
                                                ^
  symbol:   class DaggerDefault_HiltComponents_SingletonC
  location: package dagger.hilt.android.internal.testing.root`

**Comment by Chang-Eric** [comment]
Running fragment tests should work for multi-module apps, though it is a little hard to say what problem you're running into without more information. It seems kind of weird that switching to use `launchFragmentInHiltContainer` would lead to a compilation error as well unless some other build deps are changing. Are you able to create a repro?
