### ISSUE TITLE
When is the next release? Is there an estimated time?

### ISSUE THREAD

**Issue by xiahl33** [google/dagger#3558]

**Comment by bcorso** [comment]
Hi @xiahl33 what is the particular feature/bug fix you're waiting on?

It does take some time/coordination on our part to release, so typically we'll likely wait until we have a larger number of smaller fixes or a smaller number of particularly important/urgent fixes. However, if there's something you're waiting on in particular we can try to schedule a release.

**Comment by xiahl33** [comment]
> Hi @xiahl33 what is the particular feature/bug fix you're waiting on?
> 
> It does take some time/coordination on our part to release, so typically we'll likely wait until we have a larger number of smaller fixes or a smaller number of particularly important/urgent fixes. However, if there's something you're waiting on in particular we can try to schedule a release.

Hey @bcorso, thanks for reply! I'm waiting on the fix of validation issue in this commit https://github.com/google/dagger/commit/1d74d1fd394fe570ca3dcf7f1eb84caf391dca8f. We will greatly appreciate it if you can schedule a release.

**Comment by bcorso** [comment]
Ah okay. If you don't mind, can you try out the [`HEAD-SNAPSHOT`](https://dagger.dev/dev-guide/versions#head-snapshot-setup) to confirm that the issue is fixed at `master`. If things look good then I'll schedule a release.

**Comment by xiahl33** [comment]
> Ah okay. If you don't mind, can you try out the [`HEAD-SNAPSHOT`](https://dagger.dev/dev-guide/versions#head-snapshot-setup) to confirm that the issue is fixed at `master`. If things look good then I'll schedule a release.

thanks a lot! I will test it and let you know here.

**Comment by xiahl33** [comment]
Hey @bcorso, that issue was flaky in our code. I've test 25 times in my local and it seems fixed. Could you please schedule a release recently?

**Comment by bcorso** [comment]
okay, thanks! We'll try for a release this week.
