### ISSUE TITLE
how does “hiltAnnotationProcessor” work？

### ISSUE THREAD

**Issue by zhangkevd** [google/dagger#3572]
when i read the HiltGradlePlugin.kt ，find line 384

`
   compileTask.options.apply {
        annotationProcessorPath = project.configurations.create(
          "hiltAnnotationProcessor${variant.name.capitalize()}"
        ).also { config ->
          config.isCanBeConsumed = false
          config.isCanBeResolved = true
         .....
        }
      }
`

when i change the code like "hiltAnnotationProcessor${variant.name.capitalize()}" to  "xxxAnnotationProcessor${variant.name.capitalize()}" , it will not work .

but I searched the code and found nowhere to use it
what did I miss?

**Comment by danysantiago** [comment]
How exactly is it not working? Ideally, to make configs work with a different name you need to make sure the attributes to transform to them are set too, see https://github.com/google/dagger/blob/master/java/dagger/hilt/android/plugin/main/src/main/kotlin/dagger/hilt/android/plugin/HiltGradlePlugin.kt#L97

I'll close this one now, and I am sorry but we don't have enough bandwidth to support modifications of a fork of the project, it might be best to ask in https://stackoverflow.com as there is a bigger audience of developers that might have time to help.
