### ISSUE TITLE
@Inject constructor plus scope annotation can't provide local singleton

### ISSUE THREAD

**Issue by Piasy** [google/dagger#358]
I have a dependency class which has a @Inject constructor:

```java
public class DemoDirectInjectDependency {
    private final Context mContext;

    @ActivityScope
    @Inject
    public DemoDirectInjectDependency(Context context) {
        mContext = context;
        Timber.d("new DemoDirectInjectDependency");
    }
}
```

Although I annotate it with `@ActivityScope`, it will be created multiple times when I inject it into multiple places.

The generated inject code looks like below:

```java
    this.demoDirectInjectDependencyProvider =
        DemoDirectInjectDependency_Factory.create(provideContextProvider);
```

We can see the provider is not a `ScopedProvider`. 

Full code could be [found here](https://github.com/Piasy/AndroidPlayground/tree/e24245875153f62c25254fa1991b5a6523423bed/Dagger2ScopeInstanceDemo).

Of course I could create a `@Provide` method in a `@Module` class, which could utilize the scope annotation. I just wonder could dagger2 utilize the scope annotation at constructor and create a `ScopedProvider` to provide this dependency?

**Comment by tbroyer** [comment]
Scope annotations should be on the class, not the constructor: https://docs.oracle.com/javaee/7/api/javax/inject/Scope.html

Maybe Dagger 2 could warn about it though.

**Comment by Piasy** [comment]
@tbroyer Well, I mean the self defined `@ActivityScope` annotation, not `@Scope`.

**Comment by tbroyer** [comment]
@Piasy Of course. `@Scope` only applies to annotation types; I too meant your `@ActivityScope` annotation; the documentation of scope annotations is in the `@Scope` javadoc though, hence the link.

**Comment by Piasy** [comment]
Oh yes my mistake. But through [my experiment project](https://github.com/Piasy/AndroidPlayground/tree/e24245875153f62c25254fa1991b5a6523423bed/Dagger2ScopeInstanceDemo), I find out that my custom scope annotation must be on the `@Provides` method, otherwise (on the `@Module` class), the generated code won't use `ScopedProvider` to provide the dependency, hence no scoped singleton.

**Comment by tbroyer** [comment]
In JSR330, scope annotations only appear on classes:

> A scope annotation applies to a class containing an injectable constructor and governs how the injector reuses instances of the type.

But this is not enforced, to allow for other usage, such as configuration:

> A scope annotation: […] may have restricted usage if annotated with `@Target`. While this specification covers applying scopes to classes only, some injector configurations might use scope annotations in other places (on factory method results for example).

Dagger uses scope annotations in configuration in 2 places: the `@Component`, and the `@Provides` methods. On an injectable class though, the annotation follows the JSR330 rule and must be on the class.

**Comment by Piasy** [comment]
So that means dagger2 won't support `@Inject` constructor plus scope annotation to provide 'local singleton'?

**Comment by tbroyer** [comment]
All I'm saying is that you have to put your `@ActivityScope` on the `DemoDirectInjectDependency` **class**, not its constructor.

**Comment by Piasy** [comment]
Got it! When I put the `@ActivityScope` on the `DemoDirectInjectDependency` class, dagger2 use `ScopedProvider` to provide the `DemoDirectInjectDependency` instance.

Thanks!

**Comment by netdpb** [comment]
An upcoming version of Dagger 2 will report a compile-time error if you put a scope annotation on an `@Inject` constructor.

**Comment by yousufshawon** [comment]
Suppose i have build a component in ActivityA and used a `CustomScope` on a Class `MyClass` for a ActivityA . Now if  ActivityB also needs `MyClass` then how i do that? I have already added a `CustomScope` on a Class `MyClass` ?
