### ISSUE TITLE
Fields in View injected twice

### ISSUE THREAD

**Issue by Aorlinn** [google/dagger#3588]
I have a view using field injection. I create the view inside another view by using a custom EntryPoint. I found out, that the fields inside the injected view are injected once during base class constructor, and once after creating the instance, but before the EntryPoint returns it. This leads to problems, as I am configuring the fields within the constructor and using it at a later state.

I try to give a simple code example:

```
@AndroidEntryPoint
public class InjectedView extends View
{
	@Inject
	protected Object mInstance;
	protected final Object mInstanceBackup;

	@Inject
	public InjectedView (@ActivityContext Context context)
	{
		super(context);
		mInstanceBackup = mInstance;
	}

	public void compare()
	{
		if(mInstance != mInstanceBackup)
		{
			throw new RuntimeExeption("Not the same");
		}
	}
}

@AndroidEntryPoint
public class Container extends ViewGroup
{
	public void method()
	{
		InjectedView view = EntryPointAccessors.fromView(this, InjectedViewCreator.class).create();
		view.compare();
	}
}

@EntryPoint
@InstallIn(ViewComponent.class)
public interface InjectedViewCreator
{
	InjectedView create();
}
```

Now when you call Container.method() it should throw an exception. I didn't test the example so I'm not sure if there is a specific configuration missing. But I used a field modification breakpoint on my mInstance field and saw that the field is modified within Hilt before the EntryPoint returns the injected view, so I'm sure it's not overwritten in my code.

I used Hilt version 2.43.2 and some random versions earlier, it's always the same problem.

**Comment by bcorso** [comment]
You shouldn't use constructor injection with `@AndroidEntryPoint`. 

Remove `@Inject` from your constructor, and instead of using an entry point to create the view you should just call the constructor manually, e.g. the `Container` would look like this:

```java
@AndroidEntryPoint
public class Container extends ViewGroup {
  @Inject @ActivityContext Context context;

  public void method() {
    InjectedView view = new InjectedView(context);
    view.compare();
  }
}
```

**Comment by Aorlinn** [comment]
What's the reason better not to use constructor injection with `@AndroidEntryPoint`?
The reason why I use it that way is that, I have an (abstract) base view and use the EntryPoint to "return the base type". But need to be able to reconfigure the effectively returned implementing type.
How can I achieve that without constructor injection?

**Comment by bcorso** [comment]
> The reason why I use it that way is that, I have an (abstract) base view and use the EntryPoint to "return the base type". But need to be able to reconfigure the effectively returned implementing type.

Can you give an example? I'm not sure I understand how the `@Inject` constructor is helping you "reconfigure the effectively returned implementing type".

**Comment by Aorlinn** [comment]
I have a library where I define some views (`Container` and `InjectedView` of the example are included in that library). `InjectedView`is a an abstract type. In each app which uses the library, I create a class extending `InjectedView` (let's call it ImplementingView) which is returned in the Container when calling the `EntryPointAccessor`. Of course the library does not know ImplementingView, so I use `@Binds` to particularly return the according ImplementingView in the accessor.

**Comment by bcorso** [comment]
> Of course the library does not know `ImplementingView`, so I use `@Binds` to particularly return the according `ImplementingView` in the accessor.

If you want to do this via DI, you can just replace your `@Binds` with an `@Provides` method:

```java
@Module
@InstallIn(ActivityComponent.class)
interface InjectedViewModule {
  @Provides
  static InjectedView provideInjectedView(@ActivityContext Context context) {
    return new ImplementingView(context);
  }
}
```

Also, another minor note is that the more conventional way to create the binding would be to inject a `Provider<InjectedView>` rather than using an `EntryPoint`, e.g.:

```java
@AndroidEntryPoint
public class Container extends ViewGroup {
  @Inject Provider<InjectedView> injectedViewProvider;

  public void method() {
    InjectedView view = injectedViewProvider.get();
  }
}
```

**Comment by Aorlinn** [comment]
Ok, I see. Everything worked fine that way, thanks.
