### ISSUE TITLE
@Inject invalid

### ISSUE THREAD

**Issue by henjue** [google/dagger#359]
In inject, the DaggerApiComponent method should call AuthViewModel_MembersInjector instead of.InjectMembers (model) (MembersInjectors.<ViewModel>noOp);

![1](https://cloud.githubusercontent.com/assets/1314740/14491066/36e7c138-01a9-11e6-8578-ab31d148cc3e.png)
![2](https://cloud.githubusercontent.com/assets/1314740/14491067/372585f4-01a9-11e6-8920-18286c07a780.png)
![3](https://cloud.githubusercontent.com/assets/1314740/14491068/3748f6a6-01a9-11e6-9dd4-5ececb1ddd6c.png)
![4](https://cloud.githubusercontent.com/assets/1314740/14491071/374e029a-01a9-11e6-876d-5dd72a376cd2.png)
![5](https://cloud.githubusercontent.com/assets/1314740/14491070/3749cda6-01a9-11e6-9770-c4b9c698f78b.png)
![6](https://cloud.githubusercontent.com/assets/1314740/14491072/374e0056-01a9-11e6-8057-724407283fbf.png)
![7](https://cloud.githubusercontent.com/assets/1314740/14491069/3749be24-01a9-11e6-8217-7b8933703db0.png)
![8](https://cloud.githubusercontent.com/assets/1314740/14491073/377032ac-01a9-11e6-8c96-0a04cc0bf419.png)

**Comment by bjdupuis** [comment]
Unless I'm misunderstanding your intent, your complaint seems to be that you expect the subclass `AuthViewModel` to get injected by calling the superclass `ViewModel`'s inject method. That's not the way Dagger 2 performs injections, though, so your expectation is incorrect in this case.

**Comment by henjue** [comment]
yes,Later I connected through the Google related information to this is not supported
