### ISSUE TITLE
Add feature: Automatic or Specific Binding

### ISSUE THREAD

**Issue by n0vah** [google/dagger#3590]
Add ability to specify type of interface which should be used as a type for class declaration. It will decrease amount of redundant `bind` methods in module. It's especially useful if we prefer to usually work with abstraction instead of implementation, and we have only one implementation of abstraction.

For example
we have abstraction
`interface DeviceManager`
and we have implementation
`class DeviceManagerImpl @Inject constructor() : DeviceManager`

So currently we need also declare `bind` method in module
```
@Module
@InstallIn(SingletonComponent::class)
abstract class BindModule {

    @Binds
    abstract fun bindDeviceManager(mapper: DeviceManagerImpl): DeviceManager
```
and we need to repeat this action every time

For a reference here how it works in [Koin Annotations](https://insert-koin.io/docs/reference/koin-annotations/definitions#automatic-or-specific-binding)

**Comment by JakeWharton** [comment]
See #2158, #1164, probably others. There's also many issues about automatic provisioning into multibindings such as #2026, #510, etc.

**Comment by ansman** [comment]
FYI I released a library that does this for you using Hilt (Android only unfortunately unless Hilt starts supporting non Android projects): https://auto-dagger.ansman.se/
