### ISSUE TITLE
FR: Modern lifecycle abstractions bindings

### ISSUE THREAD

**Issue by yschimke** [google/dagger#3606]
I can access the LifecycleService, LifecycleOwner, lifecycleScope for a Service like so.

```
    @ServiceScoped
    @Provides
    fun serviceCoroutineScope(
        service: Service
    ): CoroutineScope {
        return (service as LifecycleOwner).lifecycleScope
    }
```

But I can't for ViewModel.  It would be nice if these modern lifecycle abstractions were exposed for ViewModelScoped also.

```
    @ViewModelScoped
    @Provides
    fun providesCoroutineScope(
        viewModel: ViewModel
    ): CoroutineScope = viewModel.viewModelScope
```

**Comment by Chang-Eric** [comment]
This is actually why we recently added the `ViewModelLifecycle` binding. There are some complications with getting the actual ViewModel instance into the graph due to the fact that it is constructor injected. You can use the `ViewModelLifecycle` to make your own CoroutineScope though like:

```kotlin
@Module
@InstallIn(ViewModelComponent::class)
object VMCoroutineModule {
    @Provides
    @ViewModelScoped
    @ViewModelCoroutineScope
    fun provideScope(lifecycle: ViewModelLifecycle): CoroutineScope {
        val context = SupervisorJob() + Dispatchers.Main.immediate
        lifecycle.addOnClearedListener {
            context.cancel()
        }
        return CoroutineScope(context)
    }
}
 
@Qualifier
annotation class ViewModelCoroutineScope
```

**Comment by yschimke** [comment]
What about just providing the lifecyclescope and maybe lifecycle owner? 

If it can make a good reference impl along these lines is it something you would accept?

There are a ton of subtleties to mess up in that example alone.

**Comment by Chang-Eric** [comment]
I don't think we actually have a real LifecycleOwner because ViewModel isn't one. I'd rather not add the CoroutineScope because we're trying to keep Hilt to really just stuff around DI.
