### ISSUE TITLE
Dagger 2.3 breaks Android Data Binding

### ISSUE THREAD

**Issue by toadzky** [google/dagger#361]
When using Dagger 2.3, compilation fails with the following error:

```
error: package com.example.project.databinding does not exist
```

Switching the Dagger to version 2.2 compiles fine with the same source.

**Comment by tbroyer** [comment]
Are you sure there are no other errors? Could it be #356?

**Comment by toadzky** [comment]
Looks it was the same issue as #356. I added the `apt 'com.google.guava:guava:19.0'` and it works

**Comment by ronshapiro** [comment]
Dagger 2.4 has been released and should have this issue fixed.

**Comment by toadzky** [comment]
awesome. thanks.
