### ISSUE TITLE
FileTooBigException - Project not compiling after Dagger version update

### ISSUE THREAD

**Issue by amitsri20** [google/dagger#3614]
I have upgraded my project **Dagger version from 2.29.1 to 2.44**, but after the upgrade I am not able to compile the code.

This is the error I am getting:

> e: org.jetbrains.kotlin.util.KotlinFrontEndException: Front-end Internal error: Failed to analyze declaration SomeContractImpl
File being compiled: (97,1) in FILE_NAME.kt
The root cause org.jetbrains.kotlin.com.intellij.openapi.util.io.FileTooBigException was thrown at: org.jetbrains.kotlin.com.intellij.openapi.util.io.FileUtil.loadFileBytes(FileUtil.java:201)

> Caused by: org.jetbrains.kotlin.com.intellij.openapi.util.io.FileTooBigException: Attempt to load 'PROJECT_PATH/DaggeAppComponent.java' in memory buffer, file length is 24808949 bytes.

I have tired setting custom editor properties with these values (in KB), but it could not fix the issue:

> idea.max.content.load.filesize=30000  
idea.max.intellisense.filesize=35000  
idea.max.vcs.loaded.size.kb=30000

Can't share the my project code since it belongs to an organisation but projects App Component class is quite big containing lot of modules which might be a reason for a big file after annotation processing.

Please suggest what can be done to fix this?

**Comment by bcorso** [comment]
If you have a before and after of the two components you could look at what the size difference is and what exactly changed between the two versions. If you find something egregious we can look into it; however, my guess is that your file was probably just close to the limit before and the upgrade slightly pushed it over the limit. 

As for the actual error, that's a limit with Intellij so you'd have to file a bug with them to see if there's a way to increase the limit.

**Comment by amitsri20** [comment]
hey @bcorso thanks for the suggestion, raised it on JetBrains issue tracker too, https://youtrack.jetbrains.com/issue/IDEA-304944/FileTooBigException-Project-not-compiling-after-Dagger-version-update

**Comment by amitsri20** [comment]
To fix this error, a possible workaround is to use this in `gradle.properties` 

    kotlin.daemon.jvmargs=-Didea.max.content.load.filesize=300000 -Didea.max.intellisense.filesize=300000


Note: *300000 here will be equivalent to 30 MB.*

**Comment by AZKZero** [comment]
The issue still persists in dagger 2.52, 

`The root cause org.jetbrains.kotlin.com.intellij.openapi.util.io.FileTooBigException was thrown at: org.jetbrains.kotlin.com.intellij.openapi.util.io.FileUtil.loadFileBytes(FileUtil.java:211)`

**Comment by amitsri20** [comment]
@AZKZero I don’t think we can say issue is with dagger specifically, it might be due to size of your dependency graph which which depends on your project.
