### ISSUE TITLE
Dagger is generating incorrect type for injected @Composable function

### ISSUE THREAD

**Issue by atzarul** [google/dagger#3635]
I'm trying to inject the composable function that represents the UI for a screen. The scenario is simple. We have a no arg composable function:

```
@Composable
fun composable() {
}

@Module
class InjectComposable {
   @Provides
   fun provideComposable(): @Composable () -> Unit = { composable() } // Function refs are not supported for composable functions
}
```

The return type for `provideComposable()` in the generated code is `Function0<Unit>`, but the injection site expects `Function2<Composer, Int, Unit>`.

**Comment by JakeWharton** [comment]
Are you running the Compose compiler in the module which exposes the provider?

**Comment by JakeWharton** [comment]
Since Dagger generates Java and the Compose compiler will not transform references in Java code I suspect this to be impossible.

**Comment by Chang-Eric** [comment]
Agree with @JakeWharton above that this is likely to be impossible to fix. As a workaround you would need to define an interface with that `@Composable` function and bind that instead.
