### ISSUE TITLE
how inject MyApplication in @SingletonComponent

### ISSUE THREAD

**Issue by CROCDC** [google/dagger#3650]
Hello, how are you? I wanted to ask you how you think I should solve this problem, since hilt does not allow the MyApplication class to be directly injected, I solved it by making a provide of it. I wanted to know if this solution seems correct to you

@Singleton
@Provides
fun provideRepo(application:MyApplication): Repository = Repository(application)

@Singleton
@Provides
fun provideMyApplication(@ApplicationContext context: Context): MyApplication = context as MyApplication

@NBole

**Comment by kuanyingchou** [comment]
Hi @CROCDC , I think it works but does your Repository really need to depend on MyApplication? It may also cause dependency issues once Repository and MyApplication are in different modules.

**Comment by CROCDC** [comment]
If it works I had already tried it, currently my repo needs MyApplication, but it is true that this does not comply with good practices, since I am generating a dependency between two layers that should not be known
