### ISSUE TITLE
Examples for unit testing pipeline code?

### ISSUE THREAD

**Issue by red8888** [google/dagger#3669]
I haven't found any examples of how this is suppose to work, but maybe its obvious and I'm not looking hard enough.

I know I can run the pipelines locally, but can I run pipelines locally and mock out all the actual commands? So I can test the logic without actually doing a deployment?

Is the solution to just factor your code in a way where you can unit test its components? Is there an "integration" test suite or whatever you'd call it where I can do a full pipeline run locally but do some mocking so I get a test thats closer to an actual pipeline run- without actually doing a deploy?

**Comment by JakeWharton** [comment]
Wrong Dagger: https://github.com/dagger/dagger

**Comment by red8888** [comment]
> Wrong Dagger: https://github.com/dagger/dagger

Gah sorry!
