### ISSUE TITLE
Inexplicable error in the execution of tests by Github actions

### ISSUE THREAD

**Issue by VahidGarousi** [google/dagger#3681]
* What went wrong:
java.lang.UnsupportedClassVersionError: dagger/hilt/android/plugin/HiltGradlePlugin has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
> dagger/hilt/android/plugin/HiltGradlePlugin has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

![Screenshot 2022-12-31 104432](https://user-images.githubusercontent.com/19606714/210128696-497a202e-5741-475b-a459-9e592615375b.png)

**Comment by kuanyingchou** [comment]
Hi, @VahidGarousi , it seems that you're on JDK 8. Hilt requires JDK 11 from [2.43](https://github.com/google/dagger/releases/tag/dagger-2.43).
