### ISSUE TITLE
SavedStateHandle's creation is different from SavedStateViewModelFactory

### ISSUE THREAD

**Issue by AlanChiou** [google/dagger#3682]
Hi Googler,

In `SavedStateViewModelFactory`(from androidx.lifecycle:lifecycle-viewmodel-savedstate),
it creates a `SavedStateHandle` for a `ViewModel` when there is a constructor with `SavedStateHandle`.
https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:lifecycle/lifecycle-viewmodel-savedstate/src/main/java/androidx/lifecycle/SavedStateViewModelFactory.kt;l=127?q=SavedStateViewModelFactory
```kotlin
private val ANDROID_VIEWMODEL_SIGNATURE = listOf<Class<*>>(
    Application::class.java,
    SavedStateHandle::class.java
)
private val VIEWMODEL_SIGNATURE = listOf<Class<*>>(SavedStateHandle::class.java)
```
```kotlin
val constructor: Constructor<T>? = if (isAndroidViewModel && application != null) {
    findMatchingConstructor(modelClass, ANDROID_VIEWMODEL_SIGNATURE)
} else {
    findMatchingConstructor(modelClass, VIEWMODEL_SIGNATURE)
}
// doesn't need SavedStateHandle
if (constructor == null) {
    return factory.create(modelClass, extras)
}
```

But I found Hilt always creates a `SavedStateHandle` for each `ViewModel` in `HiltViewModelFactory`.
https://github.com/google/dagger/blob/b5990a0641a7860b760aa9055b90a99d06186af6/java/dagger/hilt/android/lifecycle/HiltViewModelFactory.java#L75

The reason is `AbstractSavedStateViewModelFactory` extended by `HiltViewModelFactory` doesn't handle the same case by default.
And if the `ViewModel` is in the `Fragment` scope, the `SavedStateHandle` puts `Fragment`'s arguments into itself first.

What happened in my App:
- A Fragment `A` with argument set `B`.
- In Fragment `A`, it had 4 Fragment-scoped ViewModels without `SavedStateHandle` in their constructor.
- So there were 4 `SavedStateHandle`s with argument set `B`.
- When my app pushed  Fragment `A` 2x times, and then maked the Activity stop, like opening another Activity, Recent App or Launcher.
- `2x Fragment A` X `4 SavedStateHandles` X `argument set B` 

TransactionTooLargeException happened when the Activity saved its state before stopping.
Actually, all SavedStateHandles are unused in the case.

Could you have a look on it?

My current solution:
Use the original way to implement `ViewModel`s and inject dependencies from Hilt via `EntryPoints`.
And Hilt will use `SavedStateViewModelFactory` to create these `ViewModel`s.
```kotlin
class ViewModel(
  application: Application
) : AndroidViewModel(application) {

  private val repository: Repository

  init {
    val entryPoint = application.viewModelEntryPoint()
    repository = entryPoint.repository()
  }
}
```

**Comment by Chang-Eric** [comment]
Unfortunately, because we provide the `SavedStateHandle` as a binding, I don't think we can avoid creating it. However, when you create your ViewModel, you can use the [`DEFAULT_ARGS_KEY`](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:lifecycle/lifecycle-viewmodel-savedstate/src/main/java/androidx/lifecycle/SavedStateHandleSupport.kt;l=220;drc=66494e2d6810347e6a3b41ec3f2665e598f108f0) CreationExtras key to change the default arguments to an empty bundle which I think should solve your issue.

**Comment by AlanChiou** [comment]
Yes, it could remove the `Fragment` arguments from `SavedStateHandle`, but there still are unused `SavedStateHandle`s.

Example
```kotlin
@AndroidEntryPoint
class FooFragment {
  private val viewModel: BarViewModel by viewModels(extrasProducer = {
      MutableCreationExtras(this.defaultViewModelCreationExtras).apply {
          // Remove default Fragment arguments in SavedStateHandle
          set(DEFAULT_ARGS_KEY, Bundle.EMPTY)
      }
  })
}
```

**Comment by Chang-Eric** [comment]
Yea, I'm not sure there's a good way for us to remove the SavedStateHandles as we made those bindings. Do the empty SavedStateHandles still cause you issues?

**Comment by AlanChiou** [comment]
After testing, 
the way makes `SavedStateHandle` empty works well.

**Comment by Chang-Eric** [comment]
Thanks, glad it worked out. That empty bundle is a little annoying, but probably about the best we can do without significant changes to the API.
