### ISSUE TITLE
Dagger 2 issue with sub-component and a component with a dependency component

### ISSUE THREAD

**Issue by renjithk** [google/dagger#369]
I'm working on Dagger 2 and met with a dependency injection issue. I'll give you an idea into the problem. I've an ApplicationComponent as shown below.

```@Singleton
@Component(modules = {AppModule.class, MySubComponent.class})
public interface ApplicationComponent {
   void inject(Application app);
   List<Integer> pattern;
   MySubComponent subcomponent();
}
```

As you can see, I've a sub-component defined in the above component.

```
ApplicationComponent comp = DaggerApplicationComponent.builder()
                .appModule(new ApplicationModule())
                .mySubModule(new MySubModule())
                .build(); 
```

This is how I created application component instance.

Here's the sub-component

```@Singleton
@Subcomponent(modules = MySubModule.class)
public interface MySubComponent {
   void inject(AClass obj);

   INeedThis ineedthis(); 
}

@Module
public class MySubComponent {
   @Provides
   @Singleton
   INeedThis provideINeedThis() {
      return new INeedThis();
   }
}
```
I then created another component, LoginComponent with ApplicationComponent as a dependency

```@Scope
@Retention(RetentionPolicy.RUNTIME)
public @interface PerActivity{}

@PerActivity
@Component(dependencies = ApplicationComponent.class, modules = LoginModule.class)
public interface LoginComponent {
    void inject(FirstActivity activity);
}
```
I created LoginComponent instance as below.

```
LoginComponent comp = DaggerLoginComponent.builder().loginModule(new LoginModule().applicationComponent(appComponentObject).build(); 
```
The issue happens when I inject INeedThis object in FirstActivity. My assumption is since LoginComponent has a dependency of ApplicationComponent which has a sub-component MySubComponent, INeedThis object should be injected. But in reality, it fails to do so and I get the following error.

```
INeedThis cannot be provided without an @Provides- or @Produces- annotated methods.
```
I read many posts on sub-components on dagger 2. However, they didn't work as expected. Is there anything I'm missing?

**Comment by netdpb** [comment]
Because `INeedThis` is provided in a subcomponent, not in `ApplicationComponent`, you can't get one directly from `ApplicationComponent`. Instead you need to create the subcomponent instance and get it from there:

```
DaggerApplicationComponent.create().subcomponent().ineedthis();
```

Bindings that are installed into `ApplicationComponent` cannot see bindings in `MySubComponent`. Instead it's the other way around: bindings in a subcomponent can depend on bindings in a parent component.
