### ISSUE TITLE
Using @TestInstallIn in multi-module app

### ISSUE THREAD

**Issue by sarimmehdi** [google/dagger#3692]
Hello. My issue is very complicated and I am not sure if I am setting everything up incorrectly. I will do my best to explain the multi-module scenario I want testing to be done:

I have a module called **splash_presentation** that depends on **coreui**. Inside **coreui**, I have defined a Kotlin class that holds two abstract classes responsible for providing the real implementation of an interface and the fake implementation of the same interface:

```
@Module
@InstallIn(FragmentComponent::class)
abstract class CoreUiModule {

    @Binds
    @FragmentScoped
    abstract fun bindSplashTimer(
        actualSplashTimer: ActualSplashTimer
    ): SplashTimer
}

@Module
@TestInstallIn(
    components = [FragmentComponent::class],
    replaces = [CoreUiModule::class]
)
abstract class TestCoreUiModule {

    @Binds
    @FragmentScoped
    abstract fun bindSplashTimer(
        testSplashTimer: TestSplashTimer
    ): SplashTimer
}
```
So, in the above example, **ActualSplashTimer** is the implementation of the **SplashTimer** interface and that is the one used in the production version of the app. Whereas, the **TestSplashTimer** is used for testing. This works fine and I am able to use SplashTimer in the production version of the app as well as in a UI test I have written

Now, I am encountering a problem where I have a real and fake version of a repository interface. The repository interface itself is injected into two separate feature modules.

My feature module login_data contains a file with code similar to the one I just posted:

```
@Module
@InstallIn(ViewModelComponent::class)
abstract class UserRepositoryModule {

    @Binds
    @ViewModelScoped
    abstract fun bindUserRepository(
        repositoryImpl: UserRepositoryImpl
    ): UserRepository
}

@Module
@TestInstallIn(
    components = [ViewModelComponent::class],
    replaces = [UserRepositoryModule::class]
)
abstract class TestUserRepositoryModule {

    @Binds
    @ViewModelScoped
    abstract fun bindUserRepository(
        repositoryImpl: UserRepositoryTest
    ): UserRepository
}
```
This UserRepository is then injected into usecases into another module called **login_domain**. Here is how it is used in **login_domain** (**login_data** contains **login_domain** as a Gradle dependency as the latter only contains the interface, whereas the former is responsible for actually implementing the interface):

```
@Module
@InstallIn(ViewModelComponent::class)
object LoginDomainModule {

    @Provides
    @ViewModelScoped
    fun provideLoginScreenUseCases(
        userRepository: UserRepository
    ): LogInScreenUseCases {
        return LogInScreenUseCases(
            logInWithEmailAddressPasswordUseCase = LogInWithEmailAddressPasswordUseCase(userRepository)
        )
    }
```
This whole setup compiles just fine and I am able to run the app. But when I try to run an instrumented test using this setup, I get a **Dagger/Missing Binding** error. It seems that the implementation of **userRepository** is just not being injected into **provideLoginScreenUseCases**. On the other hand, the **SplashTimer interface** injection works just fine both in the production version AND in the instrumented test. I have a feeling that **TestInstllIn** doesn't work that well when the dependency being replaced is getting injected into another module located inside a different feature module.

**Comment by bcorso** [comment]
@sarimmehdi typically this happens if the [Hilt Gradle plugin](https://dagger.dev/hilt/gradle-setup#hilt-gradle-plugin) is missing from one of the Gradle modules in your multi-module project. Can you check that you've applied the plugin to all of your Gradle modules (especially, `login_data` and `login_domain` in this case).

**Comment by sarimmehdi** [comment]
I solved the issue by marking all the test modules with Singleton and SingletonComponent. It appears only that annotation works with HiltTestActivity

**Comment by sarimmehdi** [comment]
I am closing this issue because my main problem is related to instrumented tests only being injected when the dependencies are marked as Singletons. I'll open a new issue with this

**Comment by MathRoda** [comment]
Hey @sarimmehdi. I'm facing the exact same issue that you facing, I've question when you replaced the annotations in TestModules did it look like this?

@Module
@TestInstallIn(
    components = [SingletonComponent::class],
    replaces = [AuthenticationModule::class]
)
internal object FakeAuthenticationModule {
    @Provides
    @Singleton
    fun provideAuthentication(
        authentication: Authentication
    ): Authentication = authentication
}

also where did not need to use a fake replacement for the provided object did inject the same prod code?
