### ISSUE TITLE
Any way to add annotation arguments at runtime for UninstallModules?

### ISSUE THREAD

**Issue by sarimmehdi** [google/dagger#3703]
Here is what I was doing previously:
```
@UninstallModules(value = [
    LoginDataModule::class,
    OnboardingDataModule::class,
    LoginDataModuleUserLoggedIn::class,
    OnboardingDataModuleOnboardingSlidesViewed::class
])
@RunWith(JUnitParamsRunner::class)
class LoginScreenFragmentTest {
```
As expected, this works fine but the problem is that our codebase is growing and that would mean adding more and more modules to the **@UninstallModules** annotation and also carefully selecting the classes to put inside the value array based on the test class we are going to run. I tried to deal with this by creating a base array and then adding classes to it based on the test that will be annotated with the **@UninstallModules** annotation.
```
fun addModulesToUninstall(modulesToUninstall: Array<out KClass<*>>): Array<out KClass<*>> {
    var uninstalledModules = arrayOf(
        LoginDataModule::class,
        OnboardingDataModule::class
    )
    for (moduleToUninstall in modulesToUninstall) {
        uninstalledModules += moduleToUninstall
    }
    return uninstalledModules
}
```
Then, the new annotation becomes:
```
@UninstallModules(value = addModulesToUninstall([LoginDataModuleUserLoggedIn::class, OnboardingDataModuleOnboardingSlidesViewed::class]))
@RunWith(JUnitParamsRunner::class)
class LoginScreenFragmentTest {
```
But I get a red squiggly line under addModulesToUninstall with the following error warning:
`An annotation argument must be a compile-time constant`

Any way around this? I was thinking of a solution where a select list of modules is uninstalled every time we try to run a test (annotating such modules with **@UninstallTest** for example) and then, inside **@UninstallModules** I only provide the name of those classes that I just want to be uninstalled for that specific test. Would something like that

**Comment by bcorso** [comment]
> I was thinking of a solution where a select list of modules is uninstalled every time we try to run a test (annotating such modules with @UninstallTest for example) and then, inside @UninstallModules I only provide the name of those classes that I just want to be uninstalled for that specific test.

You should be able to do this with a combination of [`@TestInstallIn`](https://dagger.dev/hilt/testing#testinstallin) and [`@UninstallModules`](https://dagger.dev/hilt/testing#uninstall-modules). `@TestInstallIn` is meant to replace modules for every test and `@UninstallModules` is meant to replace a module for a single test.

**Comment by sarimmehdi** [comment]
Thanks for your answer. I tried creating an interface and annotating that with the @HiltAndroidTest and @UninstallModules annotations. Then, I implement that using my test class but, even though it compiles and runs, I get an error saying that the test needs to have the @HiltAndroidTest annotation on it.

```
@HiltAndroidTest
@UninstallModules(value = [
    LoginDataModule::class,
    OnboardingDataModule::class
])
interface DefaultUninstallModule

// ...

class LoginScreenFragmentTest: DefaultUninstallModule {

    @get:Rule
    var hiltRule = HiltAndroidRule(this)
// ...
```
If I move the @HiltAndroidTest annotation to LoginScreenFragmentTest, I get a compile-time error about duplicate bindings.

**Comment by bcorso** [comment]
@sarimmehdi did you try using `@TestInstallIn` as mentioned in https://github.com/google/dagger/issues/3703#issuecomment-1385908343?

**Comment by sarimmehdi** [comment]
@bcorso of course but for some modules, I need to pick and choose, and that requires writing down a long list of modules to uninstall for a specific test to make sure only the required module is injected. For example:

```
// LoginDataModule.kt which injects this dependency only in the production app
@Module
@InstallIn(ViewModelComponent::class)
object LoginDataModule {

    @Provides
    @ViewModelScoped
    @Named(MicrodronesUserRepositoryImpl.USER_SHARED_PREFERENCES)
    fun provideSharedPreferences(@ApplicationContext context: Context): SharedPreferences {
        return context.getSharedPreferences(MicrodronesUserRepositoryImpl.USER_SHARED_PREFERENCES, Context.MODE_PRIVATE)
    }
}

// LoginDataModule.kt in a separate gradle module but this 
// one is responsible for injecting it into tests only. Depending 
// upon the test, I might need LoginDataModuleUserLoggedIn 
// or LoginDataModuleUserNotLoggedIn

@Module
@InstallIn(ViewModelComponent::class)
object LoginDataModuleUserLoggedIn {

    @Provides
    @ViewModelScoped
    fun provideMicrodronesUserRepository(): MicrodronesUserRepository {
        return MicrodronesUserRepositoryTest(true, MicrodronesUserRepositoryTest.email)
    }
}

@Module
@InstallIn(ViewModelComponent::class)
object LoginDataModuleUserNotLoggedIn {

    @Provides
    @ViewModelScoped
    fun provideMicrodronesUserRepository(): MicrodronesUserRepository {
        return MicrodronesUserRepositoryTest(false, "")
    }
}
```
And then my @UninstallModule for LoginScreenFragmentTestUserNotLoggedIn looks like the one below:

```
@HiltAndroidTest
@UninstallModules(value = [
    LoginDataModule::class,
    OnboardingDataModule::class,
    LoginDataModuleUserLoggedIn::class,
    OnboardingDataModuleOnboardingSlidesViewed::class
])
@RunWith(JUnitParamsRunner::class)
class LoginScreenFragmentTestUserNotLoggedIn {
```
And, similarly, the LoginScreenFragmentTestUserLoggedIn looks like:

```
@HiltAndroidTest
@UninstallModules(value = [
    LoginDataModule::class,
    OnboardingDataModule::class,
    LoginDataModuleUserNotLoggedIn::class,
    OnboardingDataModuleOnboardingSlidesViewed::class
])
@RunWith(JUnitParamsRunner::class)
class LoginScreenFragmentTestUserNotLoggedIn {
```

**Comment by bcorso** [comment]
Thanks for the clarification. FWIW, we have talked about supporting this use-case better; however, it's likely not going to happen soon due to lack of time/priority. 

However, one option that may help is to use `@TestInstallIn` to define a default value that works for most tests and then use a [Dagger's optional binding](https://dagger.dev/dev-guide/#optional-bindings) to customize particular tests. This works well if the majority of your tests use the default binding and only a hand-full need to customize. It probably won't work so well if it's like 50-50.

**Example:**

Production module:

```
// Provides a UserRepository in production
@Module
@InstallIn(ViewModelComponent.class)
interface UserRepositoryModule {
  @Provides
  @ViewModelScoped
  UserRepository provideUserRepository() { ... }
}
```

Test module:

```
// Provides the default UserRepository for tests but can be overridden using `@CustomImpl UserRepository`.
@TestInstallIn(
    components = ViewModelComponent.class,
    replaces = UserRepositoryModule.class
)
@Module
interface TestUserRepositoryModule {

  // Defines an optional binding to allow tests to provide a custom implementation
  @BindsOptionalOf 
  @CustomImpl
  UserRepository customUserRepository();

  @Provides
  @ViewModelScoped
  UserRepository provideUserRepository(@CustomImpl Optional<UserRepository> customImpl) {
    return customImpl.isPresent()
        ? customImpl.get()
        : new UserRepositoryTest(false, "");
  }
}
```

Overriding in test:

```
@HiltAndroidTest
@RunWith(JUnitParamsRunner::class)
class LoginScreenFragmentTestUserLoggedIn {

  // Override the default UserRepository with a logged in user
  @Module
  @InstallIn(ViewModelComponent.class)
  interface UserRepositoryModule {
    @Provides
    @ViewModelScoped
    @CustomImpl
    UserRepository provideUserRepository() { 
      return new UserRepositoryTest(true, UserRepositoryTest.email)
    }
  }
}
```
