### ISSUE TITLE
FR: TestComponent in Hilt

### ISSUE THREAD

**Issue by stevie-patreon** [google/dagger#3721]
Feature request for a new subcomponent below `SingletonComponent` that is the root component used for injecting each test class.

My use case is that we have this dependency (User) that is provided in `ActivityComponent` and `ViewModelComponent`. I want to make it available for injection into tests, and allow tests to field inject classes that depend on it. However, I don't really want to add a binding for it to `SingletonComponent` in tests, since I'd have to override my activity and view model modules to avoid a duplicate binding.

So it would be nice to have some e.g. `TestComponent` that we can install modules and entry points for in the unit test code path, rather than having tests be injected directly from `SingletonComponent`.

**Comment by bcorso** [comment]
> However, I don't really want to add a binding for it to SingletonComponent in tests, since I'd have to override my activity and view model modules to avoid a duplicate binding.

[`@TestInstallIn`](https://dagger.dev/hilt/testing#testinstallin) allows you to replace your prod module and install the test module in a different component. Would this work for you?

**Comment by stevie-patreon** [comment]
It could work, but then I'd be replacing the activity and view model modules. I want to keep my tests as realistic as possible so I'm hesitant to do that, but otherwise the only way I have to get bindings is create an activity in my test and expose the dep. I can give a more detailed code example of what I mean if that's helpful

**Comment by bcorso** [comment]
> I want to keep my tests as realistic as possible so I'm hesitant to do that, but otherwise the only way I have to get bindings is create an activity in my test and expose the dep.

Yes, this is the [recommended approach](https://dagger.dev/hilt/testing#accessing-activitycomponent-bindings) for getting activity-level bindings into your test, especially if any of those bindings actually rely on the activity as a dependency, as you said to keep the test as realistic as possible. The approach with `@TestInstallIn` is more for replacing a binding with a fake where your fake doesn't actually have any activity-level dependencies so it's fine to put in the `SingletonComponent`.

However, I'm still not sure I really understand your `TestComponent` request though, or how it would be any more realistic than installing your binding in the `SingletonComponent`, so feel free to give a more detailed example of what you mean.

**Comment by stevie-patreon** [comment]
For the use case in our app, it's the user metadata that's the binding in question. Let's say it's a parcelable that's an extra in activity intents.

So, in activities, we have our module:

```kotlin
@InstallIn(ActivityComponent::class)
@Module
object ActivityUserModule {
    @Provides
    fun provideUser(activity: Activity): User {
        return activity.intent.getParcelableExtra("user", User::class.java)!!
    }
}
```

so we can have classes that depend on `User` and inject them into activities.

```kotlin
class MyUserDep @Inject constructor(user: User)
```

You can't inject `User` in the singleton component of the app, since it could change and login happens, etc. But it can be constant for a test. We have an annotation `@InstallUser` that will add a user to the database for the test.

I'd like to be able to inject the `User` into the test body, and also be able to inject dependencies that depend on `User`.

### Option A: Test Activity

As mentioned above, we could use a test activity:

```kotlin
@InstallUser
@HiltAndroidTest
@RunWith(RobolectricTestRunner::class)
@Config(application = HiltTestApplication::class)
class MyTest {
    @get:Rule
    val rule = MyAppRule(this)

    private lateinit var userDep: MyUserDep

    @Before
    fun setUp() {
        rule.inject()
        Robolectric.buildActivity(TestActivity::class.java, intentWithUser()).setUp().get().also {
            userDep = it.userDep
        }
    }

    @AndroidEntryPoint
    class TestActivity : AppCompatActivity() {
        @Inject
        lateinit var userDep: MyUserDep
    }
}
```

But this is annoying to repeat for each test. Also, the dep doesn't really need the activity, just the user.

### Option B: Singleton module

```kotlin
@TestInstallIn(
    components = [SingletonComponent::class],
    replaces = [ActivityUserModule::class]
)
@Module
object TestUserModule {
    @Provides
    fun provideUser(): User {
        return userForTest()
    }
}
```

Now our test can inject it directly:
```kotlin
@InstallUser
@HiltAndroidTest
@RunWith(RobolectricTestRunner::class)
@Config(application = HiltTestApplication::class)
class MyTest {
    @get:Rule
    val rule = MyAppRule(this)

    @Inject
    lateinit var userDep: MyUserDep
}
```

But the logic in `ActivityUserModule` is untested now. If it was more complex, this could be potentially problematic.

### FR / Option C: TestComponent

In my proposal, fields in tests would be injectable from a new `TestComponent` that lives under `SingletonComponent`, rather than directly from `SingletonComponent`.

Then we can do

```kotlin
@InstallIn(TestComponent::class)
@Module
object TestUserModule {
    @Provides
    fun provideUser(): User {
        return userForTest()
    }
}
```

And we'll still be able to inject `MyUserDep` directly into our test body. However, if it's injected into activities within our test, then `ActivityUserModule` will still be used to obtain it there.

### Conclusion

Maybe this isn't that big a deal and we should just go the `TestInstallIn` route and minimize the size/complexity of the activity module being replaced, but this seemed like a nice feature to me.

**Comment by Chang-Eric** [comment]
Hey Stevie, sorry I just finally got around to reading through this.

I think I understand what you want, which is you want one definition of the `User` binding for injecting into the test for just like the test helpers of getting and setting up the fake user, but you want the real production binding for `User` in the Activity/Fragment, and you don't want those to conflict, right?

I feel like in this case, the answer is maybe simpler than the above suggestions, which is to simply use another key, e.g. bind something like `@TestUser User` in the `SingletonComponent`. That's because these represent actually two different concepts. One is the user set up in the test and one is the user the activity sees. Often these should be the same, but I think they are actually distinct and could diverge in some circumstances (implying they should be separate bindings). For example, if you are testing an error case like when the user in the activity intent is malformed, I could see these diverging since the activity's user would be an invalid user (since it wasn't propagated correctly) while the test might still have a valid user set up.

Does that make sense?

**Comment by stevie-patreon** [comment]
That makes sense, but the problem lies where we want to inject classes that themselves depend on `User`. Injecting `@TestUser User` works to get the user in the test, but not any downstream classes.

The approach we went with was to use the `@TestInstallIn` module override and simply minimize the logic in the production user module. The logic for extracting the user in activities and viewmodels was moved into separate helpers that were themselves testable in isolation

**Comment by Chang-Eric** [comment]
Hm, but those downstream classes are necessarily test classes (since production code is using the Activity module definition), right? Also, in the proposed TestComponent (which I think is a leaf component in your proposal), any downstream classes would be installed in the TestComponent so they know they are test code, so they'd all be able to depend on a `@TestUser User` binding?

**Comment by Chang-Eric** [comment]
Closing this for now, but happy to discuss more later if you want.
