### ISSUE TITLE
Unnecessary @SuppressWarnings("unchecked") on #initialize() in generated components

### ISSUE THREAD

**Issue by Grimshanker** [google/dagger#375]
Fairly trivial issue but irritating for our eclipse developers. We are using Dagger 2.4. Each generated component adds the SuppressWarnings annotation even though it may not be required. This results in an eclipse warning indicating the annotation is unnecessary.

`
@SuppressWarnings("unchecked")
private void initialize(final Builder builder) {
...
}`

**Comment by tbroyer** [comment]
FWIW, that was introduced as a fix for #199; and there's a TODO in the code to fix this side-effect: https://github.com/google/dagger/blob/567d615e7d053dde25a96be194d925e82a822881/compiler/src/main/java/dagger/internal/codegen/AbstractComponentWriter.java#L737-L741

**Comment by Grimshanker** [comment]
Apologies I should have found that in the code. Is the cleanup task mentioned tracked in another issue, or is there any kind of eta on it being done? As I said not a high priority for me.

**Comment by ronshapiro** [comment]
We don't have any plans to fix this, for the same reason Greg gave in https://github.com/google/dagger/issues/700#issuecomment-294893177.
