### ISSUE TITLE
XElements#getInternalName throws IllegalArgumentException: Unsupported nesting kind.

### ISSUE THREAD

**Issue by mustafaberkaymutlu** [google/dagger#3753]
Hello,

After I update my project from 2.44.2 to 2.45, I couldn't do a successful build. 
I debugged and saw [XElements#getInternalName function](https://github.com/google/dagger/blob/master/java/dagger/internal/codegen/xprocessing/XElements.java#L515) throws the exception:

<img width="1070" alt="Screenshot 2023-02-22 at 10 31 44" src="https://user-images.githubusercontent.com/1329010/220579608-65f70690-ef2e-47fb-a849-27806739559c.png">

`element` points to this part of my code:

```kotlin
@AndroidEntryPoint
class MyFragment : Fragment {
    
    private val drawerListener: DrawerLayout.SimpleDrawerListener by lazy(LazyThreadSafetyMode.NONE) {
        getDrawerListener()
    }

    // ...

    private fun getDrawerListener() = object : DrawerLayout.SimpleDrawerListener() {
        override fun onDrawerOpened(drawerView: View) {
            super.onDrawerOpened(drawerView)
            // ...
        }

        override fun onDrawerClosed(drawerView: View) {
            super.onDrawerClosed(drawerView)
            // ...
        }
    }
}
```

I could resolve it by changing my code to this:

```kotlin
@AndroidEntryPoint
class MyFragment : Fragment {
    
    private val drawerListener: DrawerLayout.SimpleDrawerListener by lazy(LazyThreadSafetyMode.NONE) {
        createDrawerListener()
    }

    // ...

    private fun createDrawerListener(): DrawerLayout.SimpleDrawerListener {
        return object : DrawerLayout.SimpleDrawerListener() {
            override fun onDrawerOpened(drawerView: View) {
                super.onDrawerOpened(drawerView)
                // ...
            }

            override fun onDrawerClosed(drawerView: View) {
                super.onDrawerClosed(drawerView)
                // ...
            }
        }
    }
}
```

Some actions I can think of:
- if this issue is something that Dagger can recover from, maybe we can recover instead of throwing an exception. I saw in the [previous versions](https://github.com/google/dagger/blob/b5990a0641a7860b760aa9055b90a99d06186af6/java/dagger/internal/codegen/langmodel/DaggerElements.java#L378-L401) we had a try-catch there, maybe we can bring that back
- if Dagger can't recover from the issue, we can consider showing a more meaningful message by including a reference to the source code, so that it would be easier for people to find the cause and fix it.

Thanks in advance for your help and for developing Dagger!
Mustafa.

**Comment by danysantiago** [comment]
I can send a fix for this, we had to deal with this too in Room: https://android-review.git.corp.google.com/c/platform/frameworks/support/+/2170650.

**Comment by manuelvicnt** [comment]
That's an internal link I believe :D people can access that PR at [r.android.com/2170650](https://r.android.com/2170650)

**Comment by kenneth-leong-gt** [comment]
i am still getting this issue on dagger version 2.46.1. Has this fix been released?
