### ISSUE TITLE
Injected SavedStateHandle and NavHostController.previousBackEntry.savedStateHandle are different instances

### ISSUE THREAD

**Issue by backpapp** [google/dagger#3789]
Hi,

Getting arguments passed to a compose screen from the viewModel is straightforward :

```
     
@HiltViewModel
class Screen1ViewModel @Inject constructor(
    private val savedStateHandle: SavedStateHandle
)

private val args = savedStateHandle.get<String>(ARGS)
```

But now we are in a case where we would like to return a result from Screen2 to Screen1

```
@Composable
fun Screen2(navController:  NavController) {
      Button(onClick = { 
           navController.previousBackStackEntry.savedStateHandle?.set(ARGS2, true) 
           navController.popBackStack()
      }
}
```
I was expecting to retrieve ARGS2 from Screen1 using the SavedStateHandle injected in Screen1ViewModel but this savedStateHandle doesn't contain it. 

If we go to the navigation compose code though : 

```
composable("SCREEN1/{$ARGS}") {
                val viewModel = hiltViewModel<Screen1ViewModel>()
                 val args2 = it.savedStateHandle.get<Boolean>(ARGS2) <-- it's present in this savedStateHandle
                inflateScreen(viewModel = viewModel) {
                    Screen1(viewModel)
                }
            }

```

So the savedStateHandle we get from the composable navigation is different from the one injected in VM which is definitely not something I was expecting.

Am I missing something ? 

Sorry in advance, I'm pretty sure this is not the first time this has been raised but I couldn't find anything about it.

**Comment by danysantiago** [comment]
Do you observe the same issue without `@HiltViewModel` ? i.e. a vanilla `ViewModel` with a `SavedStateHandle` in its constructor only and using the Compose API `viewModel()`.

I suspect this is not a Hilt issue and it relates more to how `SavedStateHandle` instances are keyed by their host, which is usually a `ViewModel` or in this case the a [`ViewModel` in the `NavBackStackEntry` such that it exposes a `SavedStateHandle`](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:navigation/navigation-common/src/main/java/androidx/navigation/NavBackStackEntry.kt;l=135). In other words, those two instances of `SavedStateHandle` are not the same.

**Comment by backpapp** [comment]
HI @danysantiago 

I did the test and you're right, it's not related to Hilt 

```
composable(TEST_1) {
                val viewModel = viewModel<Test1ViewModel>()
                BodyTest1(viewModel = viewModel, navController)
            }
            composable(TEST_2) {
                BodyTest2(navController)
            }
```

```
@Composable
fun BodyTest1(viewModel: Test1ViewModel, navController: NavController) {
    LifeCycleSubscriber(
        onResume = viewModel::onResume
    )
    Button(onClick = { navController.navigate(TEST_2) }) {
        Text("test")
    }
}
```

```
class Test1ViewModel(private val savedStateHandle: SavedStateHandle) : ViewModel() {

    fun onResume() {
        Log.d("test", (savedStateHandle.get<Boolean>("result") ?: false).toString()) <-- Always false here
    }

}
```

```
@Composable
fun BodyTest2(navController: NavController) {
    Button(onClick = {
        navController.previousBackStackEntry?.savedStateHandle?.set("result", true)
        navController.popBackStack()
    }) {
        Text("test2")
    }
}
```

Thanks !
