### ISSUE TITLE
How do I use EntryPoints with a View?

### ISSUE THREAD

**Issue by wesalvaro** [google/dagger#3802]
I have a `NestedScrollView` that is attached to a `Fragment` that is attached to a Hilt `Activity` in a Hilt `Application`.

I'm converting the `Fragment` to Hilt.

My `NestedScrollView` currently has this logic in its `CoordinatorLayout.Behavior`:

```kotlin
val currentFocus = (context as Activity).currentFocus
```

This no longer works after migrating the `Fragment` to Hilt as the context changed to a `dagger.hilt.android.internal.managers.ViewComponentManager$FragmentContextWrapper`. What's the recommended way to get my `Activity` back out? I've tried using `EntryPoints` (for the `View`, `Fragment`, and `Activity` `Components` using the `NestedScrollView` and its `Context`) to no avail. I feel like this should be easy but I'm coming up with nothing. I'm currently relying on this kludge:

```kotlin
private val Context.activityContext: Activity
  get() =
    when (this) {
      is Activity -> this
      is ContextWrapper -> baseContext.activityContext
      else -> error("Was neither an activity nor a wrapper.")
    }

private val View.activityContext: Activity
  get() = context.activityContext
```

And updating my code to:

```kotlin
val currentFocus = activityContext.currentFocus
```

The above snippet is [explicitly frowned upon by Android KTX owners](https://github.com/android/android-ktx/issues/363). I would have expected Hilt to take care of the resolution of a `Component` or `EntryPoint` somehow using the `NestedScrollView` instance or its `context` (now the `FragmentContextWrapper`). I can't find anything in the docs; what am I missing?

**Comment by Chang-Eric** [comment]
Unwrapping ContextWrappers is the correct thing to do here. I can't speak for the response on the linked issue, but my understanding of that response is that the main objection has to do with assuming all Views are attached through an Activity. If in your code though you know that a particular View is always used in an Activity, then unwrapping the Context would be the way to do it.

**Comment by wesalvaro** [comment]
Thanks for your response!

Is there a reason that this type of functionality isn't a part of Hilt except through [a `static` method on a class not meant for use outside of Hilt internals](https://dagger.dev/api/latest/dagger/hilt/android/internal/managers/FragmentComponentManager.html#findActivity(android.content.Context))?

It seems like this code will be repeated a lot and like my original version, perhaps needlessly omit `tailrec`...
```kotlin
private tailrec fun Context.requireActivity(): Activity {
  return when (this) {
    is Activity -> this
    is ContextWrapper -> baseContext.requireActivity()
    else -> error("Was neither an activity nor a wrapper.")
  }
}
```

**Comment by Chang-Eric** [comment]
This functionality isn't specific to Hilt, it is just what you need to do in Android. Note that in a View you shouldn't assume the `Context` is the Activity anyway as there can be other wrappers like `ContextThemeWrapper` involved.
