### ISSUE TITLE
Dagger breaks incremental compilation in Maven

### ISSUE THREAD

**Issue by marquiswang** [google/dagger#3820]
I have a reproducing example here: https://github.com/marquiswang/incremental-compile-dagger-test

Long story short, if you use `mvn compile` on a project with Dagger, touch the `@Inject`ed files, then do `mvn compile` again, then it will not correctly compile the Dagger-generated factory methods. You need to do a `mvn clean compile`.

**Comment by marquiswang** [comment]
I am pretty sure that this is because of how `maven-compiler-plugin` and `javac` interact with Dagger.

`maven-compiler-plugin` will, if it detects that a file has changed, delete compiled class files and recompile every class in the module. However, it does not delete `target/generated-sources/annotations/`. It calls javac on the `Foo.java`.

Dagger chooses not to re-generate the `Foo_Factory.java` file, presumably because it already exists.

`javac` detects that no new files were created by annotation processing, so it doesn't compile anything. According to https://docs.oracle.com/en/java/javase/17/docs/specs/man/javac.html#annotation-processing , javac only compiles "newly generated source files", so it doesn't compile the existing `Foo_Factory.java`.

A workaround in `maven-compiler-plugin` would be to delete `target/generated-sources/annotations` if it needs to compile things.

But I think we can also fix this by having Dagger at least update the modified timestamp for `Foo_Factory.java`, even if it doesn't want to re-generate it.

**Comment by bcorso** [comment]
> But I think we can also fix this by having Dagger at least update the modified timestamp for Foo_Factory.java, even if it doesn't want to re-generate it.

Unfortunately, we don't have that level of control -- annotation processors can't modify existing files they can only create new ones. 

This seems like an issue with `maven-compiler-plugin`, so I'm going to close this because I don't think there's anything we can do on the Dagger side.

**Comment by marquiswang** [comment]
Got it, thanks!
