### ISSUE TITLE
dagger-android and slow first creation of DispatchingAndroidInjector

### ISSUE THREAD

**Issue by nitinsethi86** [google/dagger#3827]
I am working on speeding up the app launches. I am seeing that the very first creation of a ~1400 entries (This is a legacy project !) map of DispatchingAndroidInjector takes more than 2 seconds. 
My theory is that each entry in the map results in the corresponding class load and that results in dex file IO. Can anyone confirm the reason of this slowness.   I am looking to reduce this latency and trying to determine if reducing the map size will speed up the cold starts.

```java
@Inject
DispatchingAndroidInjector(
    Map<Class<?>, Provider<AndroidInjector.Factory<?>>> injectorFactoriesWithClassKeys,
    Map<String, Provider<AndroidInjector.Factory<?>>> injectorFactoriesWithStringKeys) {
  this.injectorFactories = merge(injectorFactoriesWithClassKeys, injectorFactoriesWithStringKeys);
}
```

**Comment by jeff-bowman** [comment]
FWIW, I've answered [this question's mirror on StackOverflow](https://stackoverflow.com/a/75981519/1426891): As in issue #1064, the use of `-Adagger.android.experimentalUseStringKeys` will help avoid the startup classloading.

From the [commit](https://github.com/google/dagger/commit/3a089646fb70fb5a193a731c4909d6ccaeeaadd3):

> **Add an option to use string keys for dagger.android and allow the keys to be obfuscated**
>
> This is enabled by default internally, where proguard understands `-identifiernamestring`, but disabled externally where it doesn't (and where R8 is not yet the standard). It can be enabled with the `-Adagger.android.experimentalUseStringKeys` flag for users that don't use proguard. This way we can guarantee that any project without modification will continue to work when proguarded.
> 
> This solves an issue where classloading of every Activity/Fragment/Service injector that's a child of the root component is forced into application startup. [...]

If using obfuscation (Proguard/R8/AppReduce), make sure to read the documentation on [AndroidProcessor.java](https://github.com/google/dagger/blob/de1c9d960a27755fc078d045f3cb10dd98da783a/java/dagger/android/processor/AndroidProcessor.java#L40-L48) so R8 can rewrite the class name strings appropriately. I've left some other alternatives in the SO answer.
