### ISSUE TITLE
Better error messages for invalid Component methods

### ISSUE THREAD

**Issue by WhosNickDoglio** [google/dagger#3834]
I'm playing around with Dagger after reading some docs and just wanted to see what would happen adding methods to a `@Component` that are neither provision or member injection methods.

With a method that has zero parameter and doesn't return anything I get an unhelpful error at compile time

```
Execution failed for task ':kaptKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.gradle.internal.KaptWithoutKotlincTask$KaptExecutionWorkAction
   > java.lang.reflect.InvocationTargetException (no error message)
```

However if I run it with `--stacktrace` I can see something more helpful: `component method cannot be void: badMethod()`, it would be nice if this was surfaced in the initial error message.

With a method with multiple arguments that doesn't return something I get a much more helpful error message: `This method isn't a valid provision method, members injection method or subcomponent factory method. Dagger cannot implement this method` but it would be nice if it could either link to docs about what is a valid method or explain it as part of the error message.

**Comment by danysantiago** [comment]
The `InvocationTargetException` hidding the Dagger exception message is a long standing issue in KAPT as Dagger does contain helpful error messages, but are hidden in KAPT's big stacktrace, where as the error message does surface correctly with `javac`. I'd suggest filling an issue in https://youtrack.jetbrains.com/issues/KT or checking if there is already a reported one.

**Comment by WhosNickDoglio** [comment]
Oh fascinating! Since this is a KAPT issue I'm assuming when Dagger supports KSP it will better surface this error messages?
