### ISSUE TITLE
Request: ability to hide a constructor-injected class

### ISSUE THREAD

**Issue by cxzhang2** [google/dagger#384]
Example use case:

The class, constructor-injected:
```
PresenterImpl implements PresenterInterface{
    @Inject
    PresenterImpl( ... )
}
```

The module:
`@Binds abstract PresenterInterface bindsPresenter(PresenterImpl impl);`

Would be nice to have the option to "hide" PresenterImpl so an @Inject PresenterImpl results in a compile-time error.

**Comment by netdpb** [comment]
You can make `PresenterImpl` nonpublic, so that only `PresenterInterface` is accessible outside that package.

**Comment by ronshapiro** [comment]
So far we've shied away from having a dagger feature which controls accessibility in favor of the java language features to do so (including using `@Qualifier`s which have controlled accessibility). Doing this would definitely go against JSR 330, so I don't think there's a good recommendation here for `@Inject` constructors.
