### ISSUE TITLE
Compiling with jack

### ISSUE THREAD

**Issue by AlokBansal8** [google/dagger#386]
I used to use android-apt gradle plugin for using dagger. With Jack there are some issues with android-apt. Is there a way to use dagger with jack?

**Comment by JakeWharton** [comment]
N preview 3's tools provides a `compileApt` configuration for use.

**Comment by AlokBansal8** [comment]
@JakeWharton Using `buildToolsVersion '24rc3'`
Added following lines in module level dependencies
`def dagger_version = "2.4"`
`compileApt "com.google.dagger:dagger-compiler:${dagger_version}"`
`compile "com.google.dagger:dagger:${dagger_version}"`

Still getting the following error message
`Error:(77, 0) Gradle DSL method not found: 'compileApt()'`

**Comment by JakeWharton** [comment]
Maybe it's not called that. Consult the docs and videos from I/O. It's
nothing specific to Dagger though.

**Comment by williamwebb** [comment]
The new configuration is `annotationProcessor`, it is described [here](http://tools.android.com/tech-docs/jackandjill).

**Comment by JakeWharton** [comment]
:+1: thanks

**Comment by AlokBansal8** [comment]
@williamwebb @JakeWharton Thanks.
