### ISSUE TITLE
Class too large

### ISSUE THREAD

**Issue by bharatdodeja** [google/dagger#3861]
We have hit the issue "Class too large" after solving the issue "[Max parameter limit 255](https://github.com/google/dagger/issues/1680)" & "Too many Constants".

```
A failure occurred while executing com.android.build.gradle.internal.tasks.JacocoTask$InstrumentDirAction
> Unable to instrument file with Jacoco: /Users/./Documents/././app/build/intermediates/javac/./classes/com/././di/DaggerApplicationComponent.class
  > Error while instrumenting SerializableChange(file=/Users/./Documents/././app/build/intermediates/javac/xxxSecureDebugProguard/classes/com/././di/DaggerApplicationComponent.class, fileStatus=CHANGED, normalizedPath=com/././di/DaggerApplicationComponent.class).
    > Class too large: com/././di/DaggerApplicationComponent
```

We have resolved "[Max parameter limit 255](https://github.com/google/dagger/issues/1680)" by making module classes as abstract classes/interfaces and replacing `@Provides` with `@Binds`.

I have searched through the internet but didn't find this issue, may be out product has too many modules and providers!

Though, this issue seems to more related the way dagger architecture has been designed than the dagger itself, any tips would be helpful.

**Comment by bcorso** [comment]
Dagger will automatically partition your component classes into multiple shards to avoid many of the limits set by the [JVM spec](https://docs.oracle.com/javase/specs/jvms/se7/html/jvms-4.html#jvms-4.11), however, it's not clear which one you're hit based on your error message. Without something to reproduce your issue you would need to dig into it yourself and figure out which limit you're hitting.

I'm not even confident this is a JVM spec limit you're hitting. Based on a quick search, the only other related issue I found was also with Jacoco, so I think the error may be thrown by Jacoco or one of its dependencies.

**Comment by bharatdodeja** [comment]
Thanks @bcorso for the response. 

We have hit `Class too large: com/././di/DaggerApplicationComponent`, you are right it seems to have the limitation for Jacoco rather than dagger.

I will continue inspecting the different solutions, e.g. adding `DaggerApplicationComponent` to the Jacoco exclusions.

**Comment by bcorso** [comment]
I'll close this for now. Feel free to reopen if you have more information that indicates this is something that can be fixed in Dagger.
