### ISSUE TITLE
Unresolved reference: registerForActivityResult in DaggerFragment

### ISSUE THREAD

**Issue by hungnt93** [google/dagger#3866]
My Android Studio always errors for some methods in DaggerFragment.
But actually, it can be built and compiled successfully:

- DaggerFragment {
registerForActivityResult()
requireView()
parentFragmentManager

Does DaggerFragment dependencies on the latest Android API?

**Comment by Chang-Eric** [comment]
I don't think our dependencies should matter since it'll really depend on what version of the Android libraries you pull into your project. This seems like more of a question for Android Studio, so I'm going to close this for now.
