### ISSUE TITLE
Request: Add plugin support for other DI libraries like ButterKnife and Dart

### ISSUE THREAD

**Issue by alphamu** [google/dagger#388]
Currently, if we want to use Dagger with ButterKnife and [Dart&Henson](https://github.com/f2prateek/dart), this requires us to inject the activity or class into each of these frameworks individually. It would be nice if it were possible to register these frameworks with Dart and have it pass our class to these frameworks as well.

**Comment by ronshapiro** [comment]
This is definitely outside of the scope of a dependency injector, if you want to write a custom processor to do this, that sounds more reasonable.
