### ISSUE TITLE
Multibindings site documentation to use dependencies

### ISSUE THREAD

**Issue by ersin-ertan** [google/dagger#389]
Using the dependencies within the [multibinding](http://google.github.io/dagger/multibindings.html) site documentation example(s), would provide a definitive use case. The "C" would show that object local members or methods could be included within the provide method as well.

``` java
@Module
class MyModuleA {
  @Provides @IntoSet
  static String provideOneString(DepA depA, DepB depB) {
//    return "ABC"; current documentation
      return depA.getCharA + depB.getCharB + "C"; // proposed change
  }
}
```

**Comment by ronshapiro** [comment]
Sounds reasonable to me - can you send a PR?
