### ISSUE TITLE
Update kotlinx.metadata to 0.6.1

### ISSUE THREAD

**Issue by lwasyl** [google/dagger#3893]
Release: https://github.com/JetBrains/kotlin/blob/master/libraries/kotlinx-metadata/jvm/ChangeLog.md#061

Right now testing K2 in projects using Dagger might be tricky (or impossible) if Dagger accesses classes from other modules that were built with K2, as it can't read classes metadata. 

See https://youtrack.jetbrains.com/issue/KT-58898 for context, the issue talks about android projects but I think it's not Android specific at all

**Comment by Chang-Eric** [comment]
Thanks for filing this. Just to let you know, this will probably take a bit longer than you might expect because there are some internal dependencies we need to coordinate with for this version bump.

**Comment by lwasyl** [comment]
Sure, I'll just point out that the 0.6.1 release was specifically published to help users test the K2 compiler and, if the release notes are correct, doesn't require any code migration. So hopefully the effort to bump it is relatively small :slightly_smiling_face:

**Comment by Chang-Eric** [comment]
Thanks for the note! The complications mostly have to do with our internal build systems and how our code gets pushed out/what versions are available to us to use. So that's what I meant by it will take longer than you might expect for a change like this.

**Comment by ZacSweers** [comment]
0.6.2 should be used 👍

**Comment by danysantiago** [comment]
Sorry for the delay, the dependency was updated in https://github.com/google/dagger/commit/7b16dfda5195ce4e713c53b8a6db3da76896a510 and the change will be available in the next release.

**Comment by sandwwraith** [comment]
Hi! Does Dagger shadow or bundle otherwise kotlinx-metadata-jvm dependency? Judging by #3951 and https://youtrack.jetbrains.com/issue/KT-58898, forcing kotlinx-metadata version in Gradle buildscript doesn't help. When this new Dagger release will be available?

**Comment by TWiStErRob** [comment]
@sandwwraith 2.47 is released, quoting this as fixed.
