### ISSUE TITLE
Cannot use @Binds @IntoMap with a class that has default arguments in the constructor.

### ISSUE THREAD

**Issue by vishalratna-microsoft** [google/dagger#3895]
I have a class
```
@Inject
class SomeClass(a : Int = 2) : SomeInterface {

}

```
and there are multiple implementations of `SomeInterface` like the above example.
I want to use multi-binding , but binding does not work.
```
@Binds
@IntoMap
fun binds(someClass: SomeClass) : SomeInterface
```
I understand that dagger will not know which JVM constructor to pick so, I worked around it by using @Provides @IntoMap
I am using dagger 2.39

Is there a plan to support these kinds of use-cases?

**Comment by bcorso** [comment]
> I want to use multi-binding , but binding does not work.

What exactly didn't work? Can you post the error message?

Just looking at the example it looks like you're missing the annotation for the map key (https://dagger.dev/dev-guide/multibindings#map-multibindings):

> "To contribute an entry to a multibound map, add a method to a module that returns the value and is annotated with [@IntoMap](https://dagger.dev/api/latest/dagger/multibindings/IntoMap.html) and with another custom annotation that specifies the map key for that entry."

**Comment by Chang-Eric** [comment]
In general, using default arguments within Dagger bindings like `@Inject` constructors or `@Provides` methods is not supported. Assuming you want a dependency to be optional, you should instead set up an optional binding with `@BindsOptionalOf` and inject an `Optional<Foo>`.
