### ISSUE TITLE
How to implement Another component in dynamic feature

### ISSUE THREAD

**Issue by harismiftahulhudha** [google/dagger#3903]
i have class in app module

AppApplication
```
public class AppApplication extends DaggerApplication {
@NonNull
    @Override
    protected AndroidInjector<? extends DaggerApplication> applicationInjector() {
        return AppComponent.builder().create(this);
    }
}
```
App Component
```
Singleton
@Component(modules = {AndroidSupportInjectionModule.class,
        AppModule.class,
        DomainModule.class,
        NetworkModule.class,
        FragmentBuilder.class,
        ActivityBuilder.class})
public interface AppComponent extends AndroidInjector<AppApplication > {

    @Component.Builder
    abstract class Builder extends AndroidInjector.Builder<AppApplication > {
    }
}
```

the problem is when im trying to create another component in feature module
```
@ActivityScope
@Component(modules = {AndroidSupportInjectionModule.class,
       FeatureActivityBuilder.class}, dependencies = AppComponent .class)
public interface FeatureComponent {
    @Component.Builder
    interface Builder {
        Builder appComponent(AppComponent component);
        FeatureComponent build();
    }
}
```
in FeatureActivityBuilder
```
@Module
abstract class FeatureActivityBuilder{

    @ContributesAndroidInjector(modules = TransactionModule.class)
    abstract InitTransactionPFActivity contributeInitTransactionPFActivity();
}

```
in my FeatureActivity has extend `DaggerAppCompatActivity`. with that i cannot initialize FeatureComponent in FeatureActivity
and i got error `java.lang.IllegalArgumentException: No injector factory bound for Class`

how to solve this problem

**Comment by Chang-Eric** [comment]
With `dagger.android`, the application is used to find an injector for the activity. `@ContribuesAndroidInjector` helps you make this injector, so the module that has that should be in installed in the component that injects your application (in your case `AppComponent`), not the component that injects your activity.

This of course probably doesn't really work out for you if you are using dynamic features though, so you probably have to not use `dagger.android` at all and just do injection manually yourself. `dagger.android` doesn't really support dynamic feature modules.
