### ISSUE TITLE
Error after upgrading Android Studio

### ISSUE THREAD

**Issue by pavelpoley** [google/dagger#3948]
Just updated to the new Android Studio version - Flamingo and my project does not compile anymore, with error:

`error: cannot find symbol import package_name.DaggerAppComponent`

`Cause: class clojure.lang.Reflector cannot access class com.sun.tools.javac.processing.JavacRoundEnvironment (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.processing to unnamed module @6e60612a`

I just update Android without any code changes or gradle changes.

Clean, invalidate cache restart does not help.

Dagger version 2.45 - Gradle version 7.42

Tried multiple new Android studio versions, and reverted back to Electric Eel, also I have checked on 2 machines and this issue only on one of them for the same project.

Weird issue.

**Comment by danysantiago** [comment]
Can you please share the full stacktrace? This doesn't seem related to Dagger, as far as I know Dagger has no usages of `clojure.lang.Reflector`.
