### ISSUE TITLE
build error：no such package '@bazel_tools//third_party/java/jdk/langtools'

### ISSUE THREAD

**Issue by vitaviva** [google/dagger#3966]
I encountered a build error when building project. I don't quite understand the useage of Bazel, and Is there anyone who can give me some guidance? thanks！

ERROR: /Users/bytedance/dev/github/dagger/java/dagger/internal/codegen/javac/BUILD:43:12: no such package '@bazel_tools//third_party/java/jdk/langtools': BUILD file not found in directory 'third_party/java/jdk/langtools' of external repository @bazel_tools. 

![image](https://github.com/google/dagger/assets/6120268/400a71b5-0c01-4845-9186-a561c83cffe7)

**Comment by bcorso** [comment]
Sounds like the version of Bazel you are using no longer has [`@bazel_tools/third_party/java/jdk/langtools`](https://github.com/bazelbuild/bazel/blob/5.4.1/third_party/java/jdk/langtools/BUILD). Looking at the Bazel repository, it looks like this directory was removed in Bazel 6.0+.

Dagger is still on Bazel 5.3.2. So one option is to downgrade to that version as well. We can also look into upgrading Bazel on our side, but it will likely be a bit lower priority for us.
