### ISSUE TITLE
Dependency cycle error when injecting Provider<Lazy<T>>.

### ISSUE THREAD

**Issue by 6bangs** [google/dagger#402]
Contrived example:

```java
class A {
  @Inject B b;
}

class B {
  @Inject Provider<Lazy<A>> a;
  public void doSomething() {
    a.get().get();
  }
}
```

A dependency cycle error will be raised instead of a warning. This is a really weird case, but it does come up in practice: specifying that a `Lazy<T>` dependency is `@Provided` in an `@AutoFactory` will result in the generation of a `Provider<Lazy<T>>` (which of course results in the dependency cycle error).

Discovered with Dagger 2.4.

**Comment by netdpb** [comment]
Fixed internally.
