### ISSUE TITLE
Measured Performance regression from 2.46.1 to 2.47.

### ISSUE THREAD

**Issue by rcgonzalezf** [google/dagger#4029]
In our repository we were trying to update to 2.47 to isolate a kapt issue we're looking at incremental builds and while measuring performance we noticed an important performance regression, I tried runs with all the versions to compare and was able to pinpoint the performance regression from 2.46.7 to 2.47 using Gradle profiler. Attaching a table with the information:

#### AssembleDebug
| Metric | Base(s) | Experiment(s)  | Delta(%) |
  |--|--|--|--|
| Min | XXX | YYY  | $${\color{red}3.01}$$ | 
| Max | XXX | YYY  | $${\color{red}3.15}$$ | 
| Mean | XXX | YYY | $${\color{red}3.19}$$ | 
| P90 | XXX | YYY  | $${\color{red}3.19}$$ | 
| P75 | XXX | YYY | $${\color{red}3.41}$$ | 
| P50 | XXX | YYY | $${\color{red}3.34}$$ | 
| Median | XXX | YYY | $${\color{red}3.34}$$ | 
| P25 | XXX | YYY | $${\color{red}3.22}$$ | 
| Std. Dev. | XXX | YYY |  | 
##### Base 2.46.1 vs Experiment 2.47

I couldn't provide exact numbers. 
Other build tool versions ares:
- JDK 17 and Kotlin 1.8.21 with kapt. 
- AGP 8.1.0
- Gradle 8.0.2 

I'll try to work in a sample project and update the issue to provide a repro project.

**Comment by bcorso** [comment]
Thanks for the info!

Unfortunately, I'm not sure there's much we can do with this at the moment unless you're able to narrow it down to something specific. While 3% isn't insignificant, I imagine it's not much higher than the std. dev (though hard to say without all of the numbers in your table)? Narrowing down the version still gives a large window of changes (62 commits between 2.46.1 and 2.47) so it's hard to say where the issue could be or if it's a single commit that caused the regression or multiple commits causing incremental regressions.

> I'll try to work in a sample project and update the issue to provide a repro project.

Sounds good.

**Comment by rcgonzalezf** [comment]
Yeah, I know isn't super actionable. I started checking at this changeset to see if I can provide more data:
https://github.com/google/dagger/compare/dagger-2.46...google:dagger:dagger-2.47

For now, I'm trying to get a repro project to publish it.
Thanks for the quick reply

**Comment by rcgonzalezf** [comment]
I'll close this ticket since after reviewing the 2.48.1 release, this is back on track. There was an OutOfMemory issue when an incorrect graph dependency (with cycles) was added to the project, and instead of having an actionable error message it was failing with an OOM. Preventing us to migrate to more recent version but that has also been fixed and improved in 2.48.1 🚀 . Thanks a lot!
 
 #### Assemble[dagger 2.48.1] to [dagger 2.44.1]. 
| Metric | Base(s) | Experiment(s) | Delta(s) | Delta(%) |
|--|--|--|--|--|
| Min | 414.39 | 401.32 | $${\color{green}-13.07}$$ | $${\color{green}-3.15}$$ | 
| Max | 425.74 | 411.25 | $${\color{green}-14.49}$$ | $${\color{green}-3.4}$$ | 
| Mean | 418.43 | 406.13 | $${\color{green}-12.3}$$ | $${\color{green}-2.94}$$ | 
| P90 | 422.64 | 408.31 | $${\color{green}-14.33}$$ | $${\color{green}-3.39}$$ | 
| P75 | 419.16 | 407.36 | $${\color{green}-11.8}$$ | $${\color{green}-2.82}$$ | 
| P50 | 418.1 | 406.89 | $${\color{green}-11.21}$$ | $${\color{green}-2.68}$$ | 
| Median | 418.1 | 406.89 | $${\color{green}-11.21}$$ | $${\color{green}-2.68}$$ | 
| P25 | 416.03 | 405.11 | $${\color{green}-10.92}$$ | $${\color{green}-2.62}$$ | 
| Std. Dev. | 3.52 | 2.92 | | | 
##### Branch [robertflores/ntvarch/19605-dagger-2.48.1[487]](https://github.corp.ebay.com/eBayMobile/andr_core/commit/85251a1e183e01d7f742076fe4379752bedf52e6) to [robertflores/ntvarch/19605-dagger-2.48.1-control[486]](https://github.corp.ebay.com/eBayMobile/andr_core/commit/null) comparison.
