### ISSUE TITLE
Hilt incompatible with Kotlin to 1.9

### ISSUE THREAD

**Issue by santiwanti** [google/dagger#4035]
Updating Kotlin to 1.9 causes a build error when using Hilt 2.44

> error: [Hilt] Unsupported metadata version. Check that your Kotlin version is >= 1.0: java.lang.IllegalStateException: Unsupported metadata version. Check that your Kotlin version is >= 1.0 at dagger.internal.codegen.kotlin.KotlinMetadata.metadataOf(KotlinMetadata.java:206) at dagger.internal.codegen.kotlin.KotlinMetadata.from(KotlinMetadata.java:186) at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133) ...

**Comment by danysantiago** [comment]
You'll need to update hilt to 2.46 or higher where the kotlinx-metadata-jvm is updated to support newer Kotlin versions.

**Comment by Lonexera** [comment]
Hi!
I'm having the same build error trying to update to Kotlin 1.9.10. I've already updated Hilt version to 2.48

**Comment by aDarkRider** [comment]
I have increased the version from 2.44 to 2.46 but it is not syncing with this version.

**Comment by Frosch2010** [comment]
I have the same problem with the newest version.

**Comment by Chang-Eric** [comment]
@Frosch2010 do you have more details you can share? E.g. stacktrace and versions

**Comment by Frosch2010** [comment]
@Chang-Eric thanks for your response. I fixed it now. I figured out that I used different versions. I used 2.44 for the Gradle plugin and the newest version in the dependencies. Now are both the same and it works.

**Comment by EmmxReach** [comment]
Thank y so much!! I had the same problem, but now Its working now!

**Comment by khalidpro1997** [comment]
thanks

**Comment by tapark** [comment]
very good 👍

**Comment by AmeerHamza112** [comment]
if your kotlin version is 1.9.22 set your hilt version to 2.46 and it will work fine .

**Comment by maulik22995** [comment]
This also worked for me if you set everything to latest :

`composeOptions {
        kotlinCompilerExtensionVersion = "1.5.9"
    }`

check out kotlin compatibility with kotlin compiler : https://developer.android.com/jetpack/androidx/releases/compose-kotlin#pre-release_kotlin_compatibility
    
kotlin is 1.9.0 set hilt version to 2.46 and it is working.

**Comment by Shamteshi** [comment]
Project level build.gradle file: 

id("com.google.dagger.hilt.android") version "2.50" apply false

App level build.gradle file:

implementation("com.google.dagger:hilt-android:2.50")
kapt("com.google.dagger:hilt-android-compiler:2.50")

Notice that the versions are the same for both the project and app level build.gradle files.

**Comment by Shamteshi** [comment]
Gradle plugin:

id("com.google.dagger.hilt.android") version "2.50" apply false

Dependency:

implementation("com.google.dagger:hilt-android:2.50")
kapt("com.google.dagger:hilt-android-compiler:2.50")

Notice that the versions are the same for both the plugin and dependencies.

**Comment by brianBk** [comment]
Just update everything to latest for hilt and Kotlin (1.9 and above) and it will work fine.
hilt = "2.51.1"
hiltCompiler = "2.51.1"
kotlin = "1.9.23"

**Comment by shivvrat12** [comment]
id("com.google.dagger.hilt.android") version "2.51.1" apply false

    composeOptions {
        kotlinCompilerExtensionVersion = "1.5.13"
    }
[versions]
agp = "8.4.2"
hiltAndroidCompiler = "2.51.1"
hiltAndroid = "2.51.1"
kotlin = "1.9.23"

Still facing the same issue damn hilt setup sometime is so irritating

**Comment by k1zlt** [comment]
Thank you)

**Comment by CesarYupa** [comment]
plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.jetbrains.kotlin.android)

    id("kotlin-kapt")
    id("com.google.dagger.hilt.android")
}

android {
    namespace = "com.yupa"
    compileSdk = 34

    defaultConfig {
        applicationId = "com.yupa"
        minSdk = 24
        targetSdk = 34
        versionCode = 1
        versionName = "1.0"

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
        vectorDrawables {
            useSupportLibrary = true
        }
    }

    buildTypes {
        release {
            isMinifyEnabled = false
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
        }
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = "17"
    }
    buildFeatures {
        compose = true
    }
    composeOptions {
        kotlinCompilerExtensionVersion = "1.5.1"
    }
    packaging {
        resources {
            excludes += "/META-INF/{AL2.0,LGPL2.1}"
        }
    }
}

dependencies {

    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.lifecycle.runtime.ktx)
    implementation(libs.androidx.activity.compose)
    implementation(platform(libs.androidx.compose.bom))
    implementation(libs.androidx.ui)
    implementation(libs.androidx.ui.graphics)
    implementation(libs.androidx.ui.tooling.preview)
    implementation(libs.androidx.material3)
    implementation(libs.androidx.runtime.livedata)

    implementation("com.squareup.retrofit2:retrofit:2.11.0")
    implementation("com.squareup.retrofit2:converter-gson:2.11.0")

    implementation("com.google.dagger:hilt-android:2.52")
    kapt("com.google.dagger:hilt-android-compiler:2.52")

    testImplementation(libs.junit)
    androidTestImplementation(libs.androidx.junit)
    androidTestImplementation(libs.androidx.espresso.core)
    androidTestImplementation(platform(libs.androidx.compose.bom))
    androidTestImplementation(libs.androidx.ui.test.junit4)
    debugImplementation(libs.androidx.ui.tooling)
    debugImplementation(libs.androidx.ui.test.manifest)
}

kapt {
    correctErrorTypes = true
}

**Comment by CesarYupa** [comment]
plugins {
    alias(libs.plugins.android.application) apply false
    alias(libs.plugins.jetbrains.kotlin.android) apply false

    id("com.google.dagger.hilt.android") version "2.52" apply false
}
