### ISSUE TITLE
[KSP] dagger-android support

### ISSUE THREAD

**Issue by dniHze** [google/dagger#4044]
Congrats on the release of the first KSP milestone! 

Just a quick question. Are there any plans to make `dagger-android` compiler compatible with KSP moving forward?

Thank you!

**Comment by trevjonez** [comment]
At the very least the "implicit module inclusion" behavior that enables `dagger-android` to work should be made a general behavior before discontinuing full support for `dagger-android`

That would unlock quite a bit of innovation while giving those that want to avoid hilt a path forward.

**Comment by dniHze** [comment]
TBH, I would be just happy getting a statement on it in the roadmap. We were thinking on replacing it with either vanilla Dagger or with Hilt. Not sure if it worth the effort for us to fork it and updating it support to updated compiler API.

**Comment by bcorso** [comment]
Yes, we will add KSP support for `dagger-android` now that Dagger and Hilt have been supported (see https://github.com/google/dagger/issues/2349#issuecomment-1331251151).

I don't anticipate this being a large amount of work, but it may still take a few weeks due to prioritization.

**Comment by nitinsethi86** [comment]
I tried mixing dagger-android usage with kapt and main dagger usage with ksp. It does not compile. Is it expected? 

I see a compile time error with just usage of ksp for plain dagger. 

@ContributesAndroidInjector was used, but dagger.android.processor.AndroidProcessor was not found on the processor path

**Comment by bcorso** [comment]
Yes, unfortunately you won't be able to mix `kapt` dagger-android and `ksp` dagger in the same Gradle module because the dagger processor requires access to files generated by the dagger-android compiler.

**Comment by Wrywulf** [comment]
@bcorso Out of curiosity, will this issue be the one tracking the development of KSP support for dagger-android, or is there another?

**Comment by bcorso** [comment]
Yep, this is the one.

**Comment by bcorso** [comment]
Also, fwiw, we do have someone actively working on this now. We'll update this ticket when it's ready.

**Comment by wanyingd1996** [comment]
#4134

**Comment by trietbui85** [comment]
@wanyingd1996 Do you know when will the Dagger 2.48.2 with `dagger-android` support be released?

**Comment by bcorso** [comment]
@trietbui85 the [Dagger 2.49 release](https://github.com/google/dagger/releases/tag/dagger-2.49) is now out.
