### ISSUE TITLE
Duplicate binding but no binding defined in component

### ISSUE THREAD

**Issue by macabrus** [google/dagger#4056]
How to inject ParentScoped dep into ChildScoped dep in same module?
use case is that i want to group stuff together by functionality in modules throughout cross-cutting concerns components from different level of scoping. Is there an alternative way of doing it without requiring me to split into module-per-scope?

```java
@Module
static class SharedModule {
    private int aCount;
    private int bCount;

    @Provides @ParentScoped @Named("a")
    String a() {
        return "a " + aCount++;
    }

    @Provides @ChildScoped @Named("b")
    String b(@Named("a") String a) {
        return "b " + bCount++ + "(with " + a + ")";
    }
}

@ParentScoped
@Component(modules = {SharedModule.class})
interface ParentScope {
    @Named("a") String a();
}

@ChildScoped
@Component(modules = {SharedModule.class},
    dependencies = ParentScope.class)
interface ChildScope {
    @Named("b") String b();
}
```

is there a simple explanation why is String a being bound multiple times? I didn't bind it anywhere in ChildScope.

the error is:
```
java: [Dagger/DuplicateBindings] @javax.inject.Named("a") java.lang.String is bound multiple times:
          @Named("a") String a.TestSharedModule.ParentScope.a()
          @Provides @Named("a") String a.TestSharedModule.SharedModule.a()
      @javax.inject.Named("a") java.lang.String is injected at
          a.TestSharedModule.SharedModule.b(a)
      @javax.inject.Named("b") java.lang.String is requested at
          a.TestSharedModule.ChildScope.b()
```

**Comment by bcorso** [comment]
> i want to group stuff together by functionality in modules throughout cross-cutting concerns components from different level of scoping. Is there an alternative way of doing it without requiring me to split into module-per-scope?

No, you will need to split the provides methods into two separate modules.

> is there a simple explanation why is String a being bound multiple times? I didn't bind it anywhere in ChildScope.

It's bound once via the `@Component.modules = SharedModule.class` and again via the `@Component.dependencies = ParentScope.class`.

**Comment by macabrus** [comment]
Why is it bound by `@Component.modules` in ChildScope if the `@Provides @ParentScoped` has different scope from the component? Doesn't docs say providers cant have differently scoped providers in them? It should probably try to use binding from parent if scope doesn't match, no?

**Comment by bcorso** [comment]
> Why is it bound by `@Component.modules` in ChildScope if the `@Provides @ParentScoped` has different scope from the component?

By adding a module to `@Component.modules()` it means every provider in that module is installed in that component. There's no way to tell Dagger to only install certain `@Provides` methods and not others.

> Doesn't docs say components cant have differently scoped providers in them?

That's correct. Normally, if you try to install a module in a component and one of its `@Provides` methods has the wrong scope you Dagger will report an error about it. I think the only reason you aren't seeing that here is because Dagger checks for duplicate bindings first, so it's reporting that error instead.

**Comment by macabrus** [comment]
Thanks for the insightful comment. Appreciate it. I'll use separate modules then 😁
