### ISSUE TITLE
[KSP][Android] WorkManagers cannot be created when using Hilt + KSP 

### ISSUE THREAD

**Issue by SimoneBari-BS** [google/dagger#4058]
Hello!

We recently tried to switch from KAPT to KSP using the [latest release](https://github.com/google/dagger/releases/tag/dagger-2.48), but run into an issue preventing us from switching. 

In particular, it seems that, using KSP, custom `WorkManager`s annotated with `@HiltWorker` are not processed correctly and cannot be instantiated at runtime, due to the following error:

```kotlin
Could not instantiate com.example.workmanager.DummyWorkManager
java.lang.NoSuchMethodException: com.example.workmanager.DummyWorkManager.<init> [class android.content.Context, class androidx.work.WorkerParameters]
	at java.lang.Class.getConstructor0(Class.java:2363)
	at java.lang.Class.getDeclaredConstructor(Class.java:2201)
	at androidx.work.WorkerFactory.createWorkerWithDefaultFallback(WorkerFactory.java:95)
	at androidx.work.impl.WorkerWrapper.runWorker(WorkerWrapper.java:243)
	at androidx.work.impl.WorkerWrapper.run(WorkerWrapper.java:145)
	at androidx.work.impl.utils.SerialExecutorImpl$Task.run(SerialExecutorImpl.java:96)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
```

This doesn't happen when using KAPT.

I have prepared a simple repo to reproduce the issue: https://github.com/SimoneBari-BS/HiltKSPWorkerManager.

Any help in fixing this issue is appreciated!

**Comment by kuanyingchou** [comment]
You need to update your hilt-common, hilt-compiler, and hilt-work to [1.1.0-alpha01](https://developer.android.com/jetpack/androidx/releases/hilt#hilt-common_hilt-compiler_hilt-work_version_11_2).

**Comment by G00fY2** [comment]
@kuanyingchou Maybe worth mentioning in the latest release notes.

**Comment by JohannesPtaszyk** [comment]
Seems like Room also has to be on 2.6.0-alpha for everything to work, if using room :)

**Comment by javimar** [comment]
I am getting the error for the combo KSP /WorkManager annotated with @HiltWorker. However, KSP seems to be working OK with Room 2.5.2.

**Comment by Raulsc9** [comment]
> You need to update your hilt-common, hilt-compiler, and hilt-work to [1.1.0-alpha01](https://developer.android.com/jetpack/androidx/releases/hilt#hilt-common_hilt-compiler_hilt-work_version_11_2).

I have the same problem as [SimoneBari-BS](https://github.com/SimoneBari-BS) and it is not solved by upgrading to "androidx.hilt:hilt-work:1.1.0-alpha01".

These are my dependencies relative to hilt;

//Dagger - Hilt
    implementation "com.google.dagger:hilt-android:2.48"
    ksp "com.google.dagger:hilt-compiler:2.48"
    implementation 'androidx.hilt:hilt-work:1.1.0-alpha01'

Best regards

**Comment by kuanyingchou** [comment]
Hi, @Raulsc9 , it looks like you're missing `ksp "androidx.hilt:hilt-compiler:1.1.0-alpha01"`.

**Comment by Raulsc9** [comment]
Thanks for your reply, but when I add that line, now I get error in the [@Insert, @Upsert, @Update, @Delete] annotations of Room, when I try to compile. 

`[ksp] C:/path_project.kt:27: Methods annotated with [@Insert, @Upsert, @Update, @Delete] shouldn't declare nullable parameters (com.example.models.MyFile).`

Currently my hilt and room dependencies are like this;

```
//Room
    implementation "androidx.room:room-runtime:2.6.0-rc01"
    ksp "androidx.room.room:room-compiler:2.6.0-rc01"
    implementation "androidx.room.room:room-ktx:2.6.0-rc01"

//Dagger - Hilt
    implementation "com.google.dagger:hilt-android:2.48" //Dagger - Hilt:2.48
    ksp "com.google.dagger:hilt-compiler:2.48" ksp "com.google.dagger:hilt-compiler:2.48"
    ksp "androidx.hilt:hilt-compiler:1.1.0-alpha01" ksp "androidx.hilt:hilt-compiler:1.1.0-alpha01"
    implementation 'androidx.hilt:hilt-work:1.1.0-alpha01'
```

I've tried removing this line;
` ksp "com.google.dagger:hilt-compiler:2.48"`

But then I get this error;
`The Hilt Android Gradle plugin is applied but no com.google.dagger:hilt-compiler dependency was found.`

Everything was working fine before I migrated to KSP. A more detailed explanation would be appreciated, best regards!

**Comment by kuanyingchou** [comment]
Hi, @Raulsc9 , it looks like the Room error is working as intended since 2.6.0-alpha01: 

https://issuetracker.google.com/issues/68198444

Sorry about the naming but `com.google.dagger:hilt-compiler` and `androidx.hilt:hilt-compiler` are different things. You'll need both for hilt-work to work.

**Comment by adonese** [comment]
have the same error as @Raul's and still not solved -- using hilt versions 2.48.1 and room version of 2.6.0-alpha03

**Comment by Sutirth** [comment]
I am using hilt version: 2.49, Work manager = 2.9.0. Trying to use this in multi module project facing the crash on lateinit workerFactory. Anybody has any recommendation or solution for the same?

**Comment by AhmedKhattab01** [comment]
@Sutirth hey did you find any solution ?

**Comment by Sutirth** [comment]
@AhmedKhattab01 I have downgraded the work manager to 2.7.0 and everything seems to be working fine

**Comment by taleroangel** [comment]
I'm having the same issue with WorkManager 2.9.0, downgrading to 2.8.0 fixes the problem.

When using the 2.8.0 version the overriden method on the Configuration.Provider is called getWorkManagerConfiguration. in version 2.9.0 it is an overriden variable override val workManagerConfiguration

**Comment by kuanyingchou** [comment]
Hi, @taleroangel , Hilt doesn't do WorkManager initialization so this is more of a WorkManager issue. Since `Configuration.Provider` got rewritten in Kotlin in 2.9.0, so instead of a downgrade I think you can just update your Kotlin implementation and override the val instead.

**Comment by anonym24** [comment]
I have updated everything to the latest version and still have this issue - `androidxWork = "2.10.0", hilt = "2.53.1", androidxWork = "2.10.0", hiltExt = "1.2.0", kotlin = "2.0.21", ksp = "2.0.21-1.0.26"`

**Comment by anonym24** [comment]
You have to add both compilers:

    ksp(libs.hilt.compiler)
    ksp(libs.hilt.ext.compiler)


libs.versions.toml:

    hilt = "2.53.1"
    hiltExt = "1.2.0"
    
    hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }
    hilt-ext-compiler = { group = "androidx.hilt", name = "hilt-compiler", version.ref = "hiltExt" }
