### ISSUE TITLE
Problem with APT exploring for DAG in modules besides model where there currently is a dagger compiler

### ISSUE THREAD

**Issue by patrykpoborca** [google/dagger#406]
Basically, something I've noticed, if you have a android-library module with base classes for your activities or w.e. you wish. There will be an issue in compiling when you subclass those base classes. 

So what appears to be happening... is that to be safe, the processor puts the providers in the module's namespace to be able to access package private fields and expose them publicly for the dagger components to be able to inject in their own dependency's modules (in cases of package private @inject declarations) Is there a reason for this? It looks to me as you could easily write this to generate the provider factories in the dagger compiler's module if it knows that all provider methods are public...

https://github.com/PatryksPlaygrounds/DaggerBehaviour

logs:

```
Executing tasks: [clean, :app:generateDebugSources, :app:generateDebugAndroidTestSources, :app:mockableAndroidJar, :app:prepareDebugUnitTestDependencies, :app:compileDebugSources, :app:compileDebugAndroidTestSources, :app:compileDebugUnitTestSources, :othermodule:generateDebugSources, :othermodule:generateDebugAndroidTestSources, :othermodule:mockableAndroidJar, :othermodule:prepareDebugUnitTestDependencies, :othermodule:compileDebugSources, :othermodule:compileDebugAndroidTestSources, :othermodule:compileDebugUnitTestSources]

Configuration on demand is an incubating feature.
Incremental java compilation is an incubating feature.
:clean
:app:clean
:othermodule:clean
:app:preBuild UP-TO-DATE
:app:preDebugBuild UP-TO-DATE
:app:checkDebugManifest
:app:preReleaseBuild UP-TO-DATE
:othermodule:preBuild UP-TO-DATE
:othermodule:preReleaseBuild UP-TO-DATE
:othermodule:checkReleaseManifest
:othermodule:preDebugAndroidTestBuild UP-TO-DATE
:othermodule:preDebugBuild UP-TO-DATE
:othermodule:preDebugUnitTestBuild UP-TO-DATE
:othermodule:preReleaseUnitTestBuild UP-TO-DATE
:othermodule:prepareComAndroidSupportAnimatedVectorDrawable2400Library
:othermodule:prepareComAndroidSupportAppcompatV72400Library
:othermodule:prepareComAndroidSupportSupportV42400Library
:othermodule:prepareComAndroidSupportSupportVectorDrawable2400Library
:othermodule:prepareReleaseDependencies
:othermodule:compileReleaseAidl
:othermodule:compileReleaseNdk UP-TO-DATE
:othermodule:compileLint
:othermodule:copyReleaseLint UP-TO-DATE
:othermodule:compileReleaseRenderscript
:othermodule:generateReleaseBuildConfig
:othermodule:generateReleaseResValues
:othermodule:generateReleaseResources
:othermodule:mergeReleaseResources
:othermodule:processReleaseManifest
:othermodule:processReleaseResources
:othermodule:generateReleaseSources
:othermodule:incrementalReleaseJavaCompilationSafeguard
:othermodule:compileReleaseJavaWithJavac
:othermodule:compileReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).

Note: /Users/patrykpoborca/Documents/consulting/plagrounds/othermodule/src/main/java/patrykpoborca/io/othermodule/BaseClassTwo.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

:othermodule:extractReleaseAnnotations
:othermodule:mergeReleaseShaders
:othermodule:compileReleaseShaders
:othermodule:generateReleaseAssets
:othermodule:mergeReleaseAssets
:othermodule:mergeReleaseProguardFiles UP-TO-DATE
:othermodule:packageReleaseRenderscript UP-TO-DATE
:othermodule:packageReleaseResources
:othermodule:processReleaseJavaRes UP-TO-DATE
:othermodule:transformResourcesWithMergeJavaResForRelease
:othermodule:transformClassesAndResourcesWithSyncLibJarsForRelease
:othermodule:mergeReleaseJniLibFolders
:othermodule:transformNative_libsWithMergeJniLibsForRelease
:othermodule:transformNative_libsWithSyncJniLibsForRelease
:othermodule:bundleRelease
:app:prepareComAndroidSupportAnimatedVectorDrawable2400Library
:app:prepareComAndroidSupportAppcompatV72400Library
:app:prepareComAndroidSupportConstraintConstraintLayout100Alpha3Library
:app:prepareComAndroidSupportSupportV42400Library
:app:prepareComAndroidSupportSupportVectorDrawable2400Library
:app:preparePlagroundsOthermoduleUnspecifiedLibrary
:app:prepareDebugDependencies
:app:compileDebugAidl
:app:compileDebugRenderscript
:app:generateDebugBuildConfig
:app:generateDebugResValues
:app:generateDebugResources
:app:mergeDebugResources
:app:processDebugManifest
:app:processDebugResources
:app:generateDebugSources
:app:preDebugAndroidTestBuild UP-TO-DATE
:app:prepareComAndroidSupportTestEspressoEspressoCore222Library
:app:prepareComAndroidSupportTestEspressoEspressoIdlingResource222Library
:app:prepareComAndroidSupportTestExposedInstrumentationApiPublish05Library
:app:prepareComAndroidSupportTestRules05Library
:app:prepareComAndroidSupportTestRunner05Library
:app:prepareDebugAndroidTestDependencies
:app:compileDebugAndroidTestAidl
:app:processDebugAndroidTestManifest
:app:compileDebugAndroidTestRenderscript
:app:generateDebugAndroidTestBuildConfig
:app:generateDebugAndroidTestResValues
:app:generateDebugAndroidTestResources
:app:mergeDebugAndroidTestResources
:app:processDebugAndroidTestResources
:app:generateDebugAndroidTestSources
:app:mockableAndroidJar
:app:preDebugUnitTestBuild UP-TO-DATE
:app:prepareDebugUnitTestDependencies
:app:incrementalDebugJavaCompilationSafeguard
:app:compileDebugJavaWithJavac
Note: Generating a MembersInjector for patrykpoborca.io.othermodule.BaseActivity. Prefer to run the dagger processor over that class instead.
/Users/patrykpoborca/Documents/consulting/plagrounds/app/build/generated/source/apt/debug/patrykpoborca/io/plagrounds/DaggerActivityComponent.java:13: error: cannot find symbol
import patrykpoborca.io.othermodule.activitylevel.ActivityModule_ProvidesBaseActivityFactory;
                                                 ^
  symbol:   class ActivityModule_ProvidesBaseActivityFactory
  location: package patrykpoborca.io.othermodule.activitylevel
1 error

 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

```

Thanks!

**Comment by netdpb** [comment]
That is in fact the reason factory classes and `MembersInjector` classes are in the module's or class's package. Otherwise all `@Provides` methods and `@Inject` constructors, methods, and fields would have to be public.

Your example appears to be running Proguard on the library jar, which seems like it's too early. Shouldn't Proguard run only on the whole APK?

**Comment by netdpb** [comment]
Hmm.

*   `ActivityModule.providesBaseActivity()` provides a raw `BaseActivity`.
*   `SubclassOfBaseClassTwo` constructor-injects a raw `BaseActivity`.
*   `MainActivity` extends `BaseActivity<SubclassOfBaseClassTwo>`, and therefore members-injects a `SubclassOfBaseTwo`.
*   `ActivityComponent` has a members-injection method for `MainActivity` and a provision method for raw `BaseActivity`.

This should all work. Even if you don't apply Dagger to othermodule, Dagger should still generate the factory on demand (and give you that "Note: Generating a factory for ActivityModule.providesBaseActivity()" warning) into the right package, just as it does with the `MembersInjector`.

Can you rerun with --info or --debug as gradle suggests?

**Comment by patrykpoborca** [comment]
Here is [`--debug`](https://gist.githubusercontent.com/patrykpoborca/0917881a92bb77957b3bdf03b681e4c2/raw/4222523a1145994e3a0809535c3e4bad56c8a7b9/log.txt) and here is the [`--stacktrace`](https://gist.github.com/patrykpoborca/30fa5c53f0cbe760e576509d5fbfb68f) and here is [`--info`](https://gist.github.com/patrykpoborca/eacc30253038ea4ae4c09835431afe73)

Can APT write into the generated files of a library module that doesn't have that APT running though? And if not, is there a way to get around it?

**Comment by netdpb** [comment]
It doesn't write to the generated files of the library module. It just writes into the correct package in the current compilation's jar.

**Comment by netdpb** [comment]
In the `--info`, I see this error message pop up a lot:

> file or directory '/Users/patrykpoborca/Documents/consulting/plagrounds/app/src/debug/java', not found

What does that mean?

**Comment by netdpb** [comment]
In the `--debug` log, I don't see where any of the `othermodule` files are being compiled at all.

**Comment by netdpb** [comment]
I just realized (thanks, @gk5885) that Dagger expects to run over any class with `dagger` annotations, including `@Module`. It will process `javax.inject` annotations like `@Inject` in other jars "lazily" because those jars may not have any dependency on Dagger.

So it is by design that in your example, you have to run the Dagger processor over the `@Module` classes in `othermodule` in order to use that module in a component.
