### ISSUE TITLE
[KSP][Android] Delete a hilt view model breaks incremental compilation in ksp

### ISSUE THREAD

**Issue by ZhaohuaZeng-at** [google/dagger#4060]
Hi team, 

Congrats on the KSP release!
After migrating to KSP, I found that there is an issue related to `@HiltViewModel` in my Android project. If I delete the view model, the incremental compilation will break in KSP, with the following message:
```
/Users/zhaohua.zeng/AndroidStudioProjects/testhiltviewmodel/app/build/generated/ksp/debug/java/com/example/testhiltviewmodel/ProfileScreenViewModel_HiltModules_KeyModule_ProvideFactory.java:34: error: package ProfileScreenViewModel_HiltModules does not exist
    return Preconditions.checkNotNullFromProvides(ProfileScreenViewModel_HiltModules.KeyModule.provide());
```

I also created a simple repository to demonstrate this issue: https://github.com/ZhaohuaZeng-at/dagger-demo-viewmodel-bug-ksp
Overview of the repo branches:
- [main](https://github.com/ZhaohuaZeng-at/dagger-demo-viewmodel-bug-ksp): use KSP for dagger and hilt. Has one hilt view model `ProfileScreenViewModel`
- [remove_viewmodel](https://github.com/ZhaohuaZeng-at/dagger-demo-viewmodel-bug-ksp/tree/remove_viewmodel): In this branch, I remove the `ProfileScreenViewModel`
- [kapt](https://github.com/ZhaohuaZeng-at/dagger-demo-viewmodel-bug-ksp/tree/kapt): Use Kapt instead for dagger and hilt.
- [kapt-remove-viewmodel](https://github.com/ZhaohuaZeng-at/dagger-demo-viewmodel-bug-ksp/tree/kapt-remove-viewmodel): Same as the remove_viewmodel branch but use kapt

Here is the steps to reproduce:
1. build project in main branch via "run app"
2. `git checkout remove_viewmodel`, build project incrementally via "run app"
3. see the compilation fails.

If I do a clean build in `remove_viewmodel`, build can succeed, but this is annoying.
This error is not reproducible with the `kapt` and `kapt-remove-viewmodel` branches.

**Comment by ansman** [comment]
I saw this too when I deleted an `@AutoBind` annotated object (this annotation is provided by [auto-dagger](https://github.com/ansman/auto-dagger))

**Comment by bcorso** [comment]
This looks like an issue in KSP. I've filed a bug here: https://github.com/google/ksp/issues/1554.
