### ISSUE TITLE
Possible incorrect lenience with generic types

### ISSUE THREAD

**Issue by ZacSweers** [google/dagger#4065]
I was working on a lint and questioning if I understood `PsiType.isAssignableFrom` correctly.

The lint is to validate that a dagger `@Binds` function is correctly binding compatible types. For example, it will show a lint error in the IDE if someone tries to bind a `String` to an `Int`. Obviously Dagger checks this at compile-time, but a lint is nice to get instant feedback in the IDE.

There's a complex case I ran into though that has me wondering

Given these types

```kotlin
sealed interface ItemDetail {
  object DetailTypeA : ItemDetail
}

interface ItemMapper<T : ItemDetail>

class DetailTypeAItemMapper : ItemMapper<ItemDetail.DetailTypeA>
```

We have a bind function like so

```kotlin
@Module
interface SomeModule {
  @Binds fun validComplexBinding(real: DetailTypeAItemMapper): ItemMapper<ItemDetail>
}
```

The lint check correctly reports the return type as not assignable from the bound instance. Dagger's compiler however accepts it as valid, and presumably in generated code does an unsafe cast that happens to work at runtime due to erased generics.

I wanted to raise this up as a possible issue, as I think Dagger maybe incorrectly allowing this and the lint check (via PSI) is correctly pointing out that `DetailTypeAItemMapper` isn't a subtype of `ItemMapper<ItemDetail>` because generics are invariant by default.

**Comment by bcorso** [comment]
Thanks @ZacSweers, are you using Dagger's KSP processor, KAPT processor, or do both processors exhibit the behavior?

**Comment by ZacSweers** [comment]
This is with kapt

**Comment by bcorso** [comment]
Hmm, I wasn't able to reproduce this.

I get the following (expected) error:

```
error: @Binds methods' parameter type must be assignable to the return type
    public abstract ItemMapper<ItemDetail> validComplexBinding(@org.jetbrains.annotations.NotNull()
```

**Comment by ZacSweers** [comment]
Thanks! Seems maybe this is actually an anvil issue then, and it's slipping by because dagger trusts the generated factory has already done the validation when component processing happens
