### ISSUE TITLE
Cause: dagger.spi.BindingGraphPlugin: dagger.hilt.android.processor.internal.viewmodel.ViewModelValidationPlugin not a subtype

### ISSUE THREAD

**Issue by thepranjalgupta** [google/dagger#4072]
Cause: dagger.spi.BindingGraphPlugin: dagger.hilt.android.processor.internal.viewmodel.ViewModelValidationPlugin not a subtype

**Comment by Chang-Eric** [comment]
There's not a lot of info to go off of here, but my guess is that you have version skew between your Hilt version and your Dagger version. Hilt and Dagger should always be run at the same version.

**Comment by Antimonit** [comment]
We don't use dagger directly but I can confirm this was caused by inconsistent versions of Hilt defined in multiple Gradle Version Catalogs.

The problem was gone once I properly updated all definitions from `2.44` to `2.48`.

**Comment by Antimonit** [comment]
@Chang-Eric I am sorry, by 'we' I meant the company **I** work for. @thepranjalgupta and I are not colleagues.

**Comment by Chang-Eric** [comment]
Ah got it, well, I still think that is likely the cause so I think closing is fine. @thepranjalgupta feel free to comment if this doesn't seem to be the issue.

**Comment by karthickramanathan95** [comment]
@Antimonit  how did you fix the issue, I don't see any workaround here and closed.

**Comment by bcorso** [comment]
See https://github.com/google/dagger/issues/4072#issuecomment-1737002031

> We don't use dagger directly but I can confirm this was caused by inconsistent versions of Hilt defined in multiple Gradle Version Catalogs.
> 
> The problem was gone once I properly updated all definitions from `2.44` to `2.48`.

Basically, you just need to make sure all Dagger and Hilt dependencies are using the same version.

**Comment by karthickramanathan95** [comment]
We are not using dagger, only hilt we are using

**Comment by bcorso** [comment]
Okay, then you need to make sure all of your Hilt dependencies are on the same version (including the Hilt Gradle plugin).

**Comment by Antimonit** [comment]
@karthickramanathan95 Make sure that any/all of the following dependencies use the same version:

```kt
implementation("com.google.dagger:hilt-android:2.48")
ksp("com.google.dagger:hilt-android-compiler:2.48")
testImplementation("com.google.dagger:hilt-android-testing:2.48")

// you probably use only one of the following
classpath { implementation("com.google.dagger:hilt-android-gradle-plugin:2.48") }
plugins { id("com.google.dagger.hilt.android") version "2.48" }
plugins { id("dagger.hilt.android.plugin") version "2.48" }
```

Using Gradle [Version Catalogs](https://docs.gradle.org/current/userguide/platforms.html#sub:version-catalog) is a sane way to keep versions aligned and centralized. Just don't make the same mistake as we did—defining the hilt version in two separate catalogs and updating only one of them 🙄

**Comment by karthickramanathan95** [comment]
Thanks @Antimonit Our project has 30+ modules, some use old version and some new, that's the problem. Redirect all modules to use from libs.toml fixed the issue.

**Comment by tensory** [comment]
@Chang-Eric I am seeing the same error that @thepranjalgupta reported. The project is using Gradle version catalogs. I've confirmed that all of the Hilt dependencies are on `2.48.1`. We are using the Hilt Android Gradle plugin, so I only had to change one catalog version number. Do you have any suggestions beyond aligning the dependency versions?

The context for this is that before I updated the Dagger version, I got the same error as here https://github.com/google/dagger/issues/3356. I need to do DI with Hilt in a startup initializer. The project assembles and runs fine, but the error occurs in the androidTest task. I had the project on Dagger 2.45. I tried updating Dagger to 2.48.1 and using the ```@EarlyEntryPoint``` annotation for the entry point. Having done this, I no longer get the error from https://github.com/google/dagger/issues/3356, but  the new error is the same one reported in this thread.

**Comment by kummo001** [comment]
> @karthickramanathan95 Make sure that any/all of the following dependencies use the same version:
> 
> ```kotlin
> implementation("com.google.dagger:hilt-android:2.48")
> ksp("com.google.dagger:hilt-android-compiler:2.48")
> testImplementation("com.google.dagger:hilt-android-testing:2.48")
> 
> // you probably use only one of the following
> classpath { implementation("com.google.dagger:hilt-android-gradle-plugin:2.48") }
> plugins { id("com.google.dagger.hilt.android") version "2.48" }
> plugins { id("dagger.hilt.android.plugin") version "2.48" }
> ```
> 
> Using Gradle [Version Catalogs](https://docs.gradle.org/current/userguide/platforms.html#sub:version-catalog) is a sane way to keep versions aligned and centralized. Just don't make the same mistake as we did—defining the hilt version in two separate catalogs and updating only one of them 🙄

Thank, this fix my problem, I declare inconsistent hilt version in my module
