### ISSUE TITLE
DelegateFactory cannot be converted to MembersInjector

### ISSUE THREAD

**Issue by Servus7** [google/dagger#408]
Following error occurred after updating to google play services 1.9.2:
`error: incompatible types: DelegateFactory cannot be converted to MembersInjector<Mod`
Going back to 1.9.0 solved the error.

**Comment by Servus7** [comment]
Going back solved it only for one build. Now the error is back.

**Comment by Servus7** [comment]
This is the generated codeblock where errors are reported:
```
this.modelRegistryMembersInjector = new DelegateFactory();

this.modelRegistryProvider =
    DoubleCheck.provider(
        ModelRegistry_Factory.create(modelRegistryMembersInjector, getApplicationProvider));

this.getGsonProvider =
    DoubleCheck.provider(
        CustomerModule_GetGsonFactory.create(builder.customerModule, modelRegistryProvider));

DelegateFactory modelRegistryMembersInjectorDelegate =
    (DelegateFactory) modelRegistryMembersInjector;

this.modelRegistryMembersInjector =
    ModelRegistry_MembersInjector.create(
        getExecutorServiceProvider,
        eventBusProvider,
        locationHandlerProvider,
        getGsonProvider,
        userProvider,
        getETagStoreProvider);
modelRegistryMembersInjectorDelegate.setDelegatedProvider(modelRegistryMembersInjector);```

**Comment by ronshapiro** [comment]
Can you please provide a sample project which contains just this? 

Greg, it looks like a reassignment is happening for `modelRegistryMembersInjector`. Know what that might be?

**Comment by Servus7** [comment]
Sorry i can't. We currently removed dagger from our projects.

The problem ocurres after removing an class inject from the component interface. This class was in the first line and contains only one inject. Moving the class to the bottom position of the component also leads to the error.
Having this dummy inject not in first place produces the incorrect dagger file.
