### ISSUE TITLE
ActivityRetainedScoped and "Don't keep activities"

### ISSUE THREAD

**Issue by svyatoslavpavlov** [google/dagger#4084]
Currently i'm working with enabled developer option "Don't keep activities" and injected class with @ActivityRetainedScoped recreates every time after activity restoration.
Since annotation called ActivityRetainedScoped, i expect that class will be same (like with Singleton)

Correct me, if i wrong?

```
@ActivityRetainedScoped
class MapController @Inject constructor() {
...
}
```

```
@AndroidEntryPoint
class MainActivity : AppCompatActivity() {

    @Inject
    lateinit var mapController: MapController
...
}
```

**Comment by Chang-Eric** [comment]
The "retained" of ActivityRetainedScope refers to being retained across configuration changes. When you use "Don't keep activities" you are telling the system to destroy your process as soon as your app goes into the background. This means even your singletons will be created new since your process was destroyed.

**Comment by svyatoslavpavlov** [comment]
> The "retained" of ActivityRetainedScope refers to being retained across configuration changes. When you use "Don't keep activities" you are telling the system to destroy your process as soon as your app goes into the background. This means even your singletons will be created new since your process was destroyed.

No, just checked
you sad about background process limitation option, not about "Don't keep activities"
if i enable "Don't keep activities" singletons are same
if i restrict background processes - yes, singletons are recreated

**Comment by Chang-Eric** [comment]
Okay, I guess I didn't realize "Don't keep activities" doesn't kill the process, but in any case, ActivityRetainedScoped is for the lifetime of the activity through configuration changes. It is defined as going away when your activity is destroyed, so if you tell the system to destroy your activity, the component is going to be destroyed and you'll get new instances when you restart the activity.

It is essentially the same as the lifetime of a ViewModel owned by the activity.
