### ISSUE TITLE
[Hilt] Can you have two ViewModels using @BindValue in an instrumented test?

### ISSUE THREAD

**Issue by techartist** [google/dagger#4104]
can you have two viewmodels be replaced by @BindValue in an instrumented test?  I have an activityViewModel and a viewModel.

`

```
@HiltAndroidTest
class TourActivityUat {
```

    private val context: Context
        get() = ApplicationProvider.getApplicationContext()

    val targetContext: Context = 
    InstrumentationRegistry.getInstrumentation().targetContext

    @get:Rule(order = 0)
    var hiltRule = HiltAndroidRule(this)

    @get:Rule(order = 1)
    val setupRepoRule = SetupRepoRule(context)

    @get:Rule(order = 2)
    val activityScenarioRule = ActivityScenarioRule<TourActivity>(
        TourActivity.createIntent(
        context
        )
    )

    @Mock
    private val userDataRepo: UserDataRepo = mock()

    private val authTokenRepo: AuthTokenData = mock()
    private val tokenRepo = TokenRepository(cookieJar = ClearableCookieJarTest(context))

    @BindValue
    val viewModel = TourViewModel(
        userDataRepo = userDataRepo,
        scheduler = Schedulers.computation()
    )

    @BindValue
    val userInactivityViewModel = UserInactivityViewModel(
        authTokenData = authTokenRepo,
        scheduler = Schedulers.computation(),
        tokenRepo = tokenRepo
    )

    @Before
    fun setup() {

        val notificationsResponse = NotificationResponse.test(
            messages = 4,
           documents = 0
        )
        whenever(userDataRepo.notifications).doReturn(
            Observable.just(
            notificationsResponse
        ))

        whenever(userDataRepo.relationshipIds).doReturn(Single.just(listOf(1L)))

        whenever(userDataRepo
            .fetchNotifications(any())).doReturn(Completable.complete())

        whenever(userDataRepo.firstName).doReturn(Single.just("Kristy"))

        hiltRule.inject()
        context.saveTourVisitedStatus(false)
    }
    //Tests
`}`
`

When I run the tests, I get java.lang.IllegalStateException: The component was not created. Check that you have added the HiltAndroidRule.

**Comment by techartist** [comment]
Actually you can.  I've done it.

**Comment by Chang-Eric** [comment]
While you technically can replace them, it isn't something we really recommend. For Android components like that, we usually recommend replacing the bindings the ViewModel uses with things like `@BindValue` rather than the ViewModel itself. This is similar to how you wouldn't replace a whole Activity or Fragment, but would replace individual bindings.
