### ISSUE TITLE
Dagger won't generate my Test Component

### ISSUE THREAD

**Issue by rotemsloo** [google/dagger#411]
Hey , 
I have a AppComponent in production (app\src\main\java\di\) :

@Singleton
@Component({SomeModules.class})
public interface AppComponent

and I'm trying to make a TestComponent in test (app\src\test\java\di\)
@Singleton
    @Component
    public interface TestAppComponent extends AppComponent 

but for some reason I can't see DaggerTestAppComponent generated.

this is app's build.gradle : 

apt 'com.google.dagger:dagger-compiler:2.5'
provided 'javax.annotation:jsr250-api:1.0'
compile 'com.google.dagger:dagger:2.5'

**Comment by tbroyer** [comment]
Assuming you're using either `android-apt` or `net.ltgt.apt` Gradle plugins, you need to add `dagger-compiler` to the `testApt` configuration; the `testApt` configuration does not extend the `apt` configuration, so you need to add `dagger-compiler` in both in your case.

**Comment by rotemsloo** [comment]
Thanks , 
Actually adding testCompile 'com.google.dagger:dagger:2.5' to my separated tests gradle make things work.
Thanks again
