### ISSUE TITLE
Fatal Exception: java.lang.IllegalAccessError

### ISSUE THREAD

**Issue by wahyupermadie** [google/dagger#4117]
Hi Friends, Currently I still using Dagger 2.28.3 and Kotlin 1.6.21, I have an issue related to "maybe" the modifier. In this case, I migrated my dagger module from Java to Kotlin. 
For example, I have an activity called `MainActivity.java` (com.example.test)
```
public class MainActivity extends ScreenActivity implements CollectorView 
```
and I have a `ViewModel` called `MainActivityViewMode.java` (com.example.test)
```
public class MainActivityViewModel  {

    private final Activity activity;

    public MainActivityViewModel(Activity activity) {
        this.activity = activity;
    }
}
```
CollectorView.java (com.example.test)
```
interface CollectorView {

    @UiThread
    void isLoading(boolean isLoading);

}
```
Dagger Module (com.example.test.di)
```
        @ScreenScope
        @Provides
        fun provideViewModel(
            screen: MainActivity,
        ): MainActivityViewMode = MainActivityViewModel(screen)

```

And I got this error during the Runtime
```
java.lang.IllegalAccessError: Illegal
class access: 'com.example.test.di.MainScreenComponent$MainScreenModule'
attempting to access 'com.example.test.CollectorView'
(declaration of 'com.example.test.di.MainScreenComponent$MainScreenModule'
appears in /data/app/~~Y6fB3SCCupGoXZNyieSbVg==/com.example.test-RhKR2YXIPtH2adpWyaAi_Q==/base.apk!classes25.dex)
```

I can fix this by adding `public` into the `CollecterView.java`
```
public interface CollectorView {

    @UiThread
    void isLoading(boolean isLoading);

}
```

I'm just curious why this cannot be detected during compile times and why it worked in the Java module before. This is the first time got an issue like this with Dagger, I have faced an issue related to modifiers but in Kotlin it will show an error during compile time or even show in Android Studio itself. But this case happened during runtime.

**Comment by bcorso** [comment]
I think this is a question more for the Kotlin team/experts. Whether or not Kotlin fails at compile time or runtime is not something Dagger can control.

**Comment by wahyupermadie** [comment]
Hi @bcorso thanks for you reply, let me ask with kotlin team. Thanks
