### ISSUE TITLE
Add functionality equivalent to Guice's ProvisionListener

### ISSUE THREAD

**Issue by ddimtirov** [google/dagger#413]
Currently I am using experimentally `AspectJ` to intercept the `Factory.get()` method for each component. Would be nice if Dagger provided a direct hook.

My actual use case is to collect all managed objects and automatically hook them up in a larger framework (i.e. if a managed object implements `Command` interface, add it automatically to the command registry, if it implements `NotificationAware`, subscribe it to notifications).

In a previous iteration I tried to use multibindings for the same, but that had the drawback that each object needed to be explicitly added to the multibindings collection, rather than automatically added on instantiation, based on implemented interfaces.

**Comment by ddimtirov** [comment]
I am currently imagining an API along these lines:

```
lifecycleAware = new HookupListener(framework)
foobar = DaggerComponent.builder().withProvisionListener(listener).build().getFoobar() 
// at this point the listener has captured the Dagger created objects implementing lifecycle interfaces

lifecycleAware.hookup()

//... do stuff

lifecycleAware.unhook()
foobar.dispose()
```

Let me know if that sounds OK, or if there is a better way to achieve this.
I may try to hack the `FactoryGenerator` and submit a patch.

**Comment by ronshapiro** [comment]
Closing for the same reasons mentioned in #427.
