### ISSUE TITLE
Dagger 2 web site has cosmetic issues in Safari.

### ISSUE THREAD

**Issue by tonycosentini** [google/dagger#415]
In my browser (using Safari 9.0.3 on OS X), the Dagger 2 website looks like this:
![screen shot 2016-07-23 at 2 33 28 pm](https://cloud.githubusercontent.com/assets/23467/17080398/6f0a02c8-50e2-11e6-8ab1-2a136309bb8b.png)

I'm not sure what it's supposed to look like, but the word Dagger is invisible and the Resources text does not link to anything.

**Comment by cgruber** [comment]
@gak - is this maybe some sort of configuration issue with the bower
components or something?

FWIW, I can reproduce it... though Dagger isn't invisible... it's just
white, and the background is a light enoguh gray that it's nearly the
case.  If you select the page content, it becomes slightly more visible.
Even in this screen shot you can just slightly see it.

c.

**Comment by tonycosentini** [comment]
Yeah - it's still kind of visible. If I recall correctly, the entire header used to be blue.

**Comment by ronshapiro** [comment]
This isn't so high priority, but it would be nice to fix it. Looks like polymer might just not work well on Safari?

**Comment by gk5885** [comment]
@cgdecker was working on some updates to our project pages.  Any news on that?

**Comment by cgdecker** [comment]
No news at the moment, unfortunately.

**Comment by ronshapiro** [comment]
@tonycosentini is this still the case?

**Comment by tonycosentini** [comment]
Nope, it looks correct now. I'm not sure what changed, but looks good now 👍🏻
