### ISSUE TITLE
Hilt with JAVA 19 results in "Unsupported class file major version 63" error

### ISSUE THREAD

**Issue by promanowicz** [google/dagger#4155]
kotlin 1.9.20
gradle 8.4
android gradle plugin 8.1.4
compose compiler 1.5.4
hilt android gradle plugin 2.48.1
hilt android 2.48.1
hilt navigation compose 1.1.0
hilt android compiler 2.48.1
compose bom 2023.10.01

Compose compiler 1.5.4 suggest using jvmTarget 19 with compose 1.5.4
https://developer.android.com/jetpack/androidx/releases/compose-compiler

This setup with latest hilt dependencies result in "Unsupported class file major version 63" error coming from hiltAggregateDepsDebug task.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':hiltAggregateDepsDebug'.

Caused by: org.gradle.workers.internal.DefaultWorkerExecutor$WorkExecutionException: A failure occurred while executing dagger.hilt.android.plugin.task.AggregateDepsTask$WorkerAction
Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 63

Using ksp (1.9.20-1.0.14) instead of kapt results in the same error.

Lowering Java version to 17 solves the problem.

**Comment by kuanyingchou** [comment]
Hi, @promanowicz , thanks for reporting! I think it's because the version of [the asm library](https://asm.ow2.io/versions.html) we use in Hilt Gradle Plugin is too old. I'll try to update it.

**Comment by kuanyingchou** [comment]
I've [updated the library](https://github.com/google/dagger/commit/4c75892b6ef9d66f2b0cdb3f0af789d9193e5c64) and it will be included in the next release.
