### ISSUE TITLE
Can't add Hilt to a multiplatform project

### ISSUE THREAD

**Issue by mylesbennett** [google/dagger#4163]
This was first raised [here](https://youtrack.jetbrains.com/issue/KT-63782) when I was trying to add Hilt to a multiplatform project using the traditional kapt annotation processor. I switched to the latest KSP arrangement and now have a new error on build:
```
[ksp] /composeApp/src/androidMain/kotlin/com/bpp/example/MainActivity.kt:12: [Hilt] Expected @AndroidEntryPoint to have a value. Did you forget to apply the Gradle Plugin? (com.google.dagger.hilt.android)
See https://dagger.dev/hilt/gradle-setup.html
[1;31m[Hilt] Processing did not complete. See error above for details. [0m
```
[Here](https://github.com/mylesbennett/Compose-Multiplatform-Hilt-Kapt-type-mismatch) is a repo demonstrating the problem.

**Comment by kuanyingchou** [comment]
Hi, @mylesbennett , thanks for reporting. This looks similar to this one: https://github.com/google/dagger/issues/4130. Could you give [the latest snapshot](https://dagger.dev/dev-guide/versions.html) a try?

**Comment by mylesbennett** [comment]
Hi @kuanyingchou, Thanks for your quick reply.

I tried the snapshot arrangement - still the same error.

It's possible there was something lost in my translating the Groovy instructions to Kotlin DSL/ Version Catalogs.
Also the instructions were for Dagger, but the resolution strategy _seemed_ to pick up the snapshots for Hilt as well. At least, that was what the download report suggested on build.

Here is my attempt:
https://github.com/mylesbennett/Compose-Multiplatform-Hilt-Kapt-type-mismatch/tree/dagger-snapshot

**Comment by kuanyingchou** [comment]
Hi, @mylesbennett , you also need to move Hilt to "HEAD-SNAPSHOT" in your `libs.versions.toml`, and add `maven("https://oss.sonatype.org/content/repositories/snapshots") to both repositories in your `settings.gradle.kts`.

**Comment by mylesbennett** [comment]
I did that - but somehow the changes didn't get pushed.
That's been rectified now. Please could you take another look.
