### ISSUE TITLE
Dagger should not allow injection into Kotlin protected fields

### ISSUE THREAD

**Issue by mwswartwout** [google/dagger#4170]
Currently, Dagger can inject into Kotlin protected fields. I believe this is because the Kotlin protected field gets translated into a Java protected field, which escalates the visibility. 

In Kotlin, internal should be the minimum visibility for injected fields. I discovered this while working on cl/578269246. Internal bug is b/314160777.

**Comment by prattpratt** [comment]
May I ask why injecting protected fields should be disallowed?

**Comment by erfansn** [comment]
@prattpratt because, you cannot access to them outside of class

**Comment by prattpratt** [comment]
> @prattpratt because, you cannot access to them outside of class

And imo this is good. Because I want that such fields be injectable but can not be accessed outside the class. This was so handy. Don't get why this was disallowed. This is sad, will use old version for a while.
