### ISSUE TITLE
Dagger 2 generates uncompilable code when a dependency is called Provider

### ISSUE THREAD

**Issue by vanniktech** [google/dagger#418]
I have a module which looks like that:

```java
@Provides
@NonNull
public SomeClass provideSomeClass(@NonNull final IDataStoreProvider dataStoreProvider, @NonNull final DataStore dataStore) {
    return new SomeClass(dataStoreProvider, dataStore;
}
```

After Dagger runs through it generates code like this in `MyModule_ProvideSomeClassFactory`:

```java
private final Provider<IDataStoreProvider> dataStoreProvider;
private final Provider<DataStore> dataStoreProvider;
```

Which obviously won't compile since the variable names are duplicated.

**Comment by vanniktech** [comment]
As a workaround it seems like renaming the variable `dataStoreProvider` to something other than `dataStoreProvider` works. Still it'd be nice if Dagger could detect such things and then generate a different name.

**Comment by tbroyer** [comment]
@ronshapiro Now that Dagger has moved to using JavaPoet for codegen, maybe it could use [`NameAllocator`(https://square.github.io/javapoet/1.x/javapoet/com/squareup/javapoet/NameAllocator.html) to prevent those collisions?

**Comment by vanniktech** [comment]
@tbroyer yup sounds like a good idea. I'm also using that one in another project

**Comment by ronshapiro** [comment]
This should be fixed in ab482f981e0a55b30a1371f5d5b6e859af9e4b98 (which will be released shortly in `2.6`).

**Comment by ronshapiro** [comment]
Just released `2.6`, should hit maven servers soon (I think they say an hour?)

**Comment by vanniktech** [comment]
I'd say usually it's less than an hour. Anyway thanks for the fix 👍

**Comment by ronshapiro** [comment]
Can you reopen if this is still an issue.
