### ISSUE TITLE
Getting `Unexpected annotation value: TransformedVisibilityMarker` error during unit test

### ISSUE THREAD

**Issue by kenshin171** [google/dagger#4214]
Somehow after upgrading to version 2.50 i am getting the below error when compiling for UnitTests. It seems to stem from the hilt gradle plugin, and i cannot seem to find anything on the web on the annotation `TransformedVisibilityMarker`. The weird thing is after i encounter this issue, even after i downgrade back to dagger 2.48, this issue still comes up which puzzles me.

I tried reverting my other dependency changes including KSP(1.9.22 to 1.9.21) and robolectic, but the same issue stills comes up.
I am at a lost. 

```
Execution failed for task ':app:hiltAggregateDepsSingpassStgDebugUnitTest'.
> A failure occurred while executing dagger.hilt.android.plugin.task.AggregateDepsTask$WorkerAction
   > Unexpected annotation value: TransformedVisibilityMarker
```

**Comment by wanyingd1996** [comment]
It is suggesting there is an Unexpected annotation value, not an annotation, can you verify you didn't accidentally included this symbol in your code repository? This value isn't coming from dagger or hilt. If not, can you provide a minimal repo?

**Comment by kenshin171** [comment]
I did a search on this string `TransformedVisibilityMarker ` from my entire code base and did not find it at all. The only thing i can think of is Android Studio, somehow my CI/CD device which is on Android studio `Giraffe Patch 2` is working but my local device which is `Hedgehog patch 1` exhibits this issue.

**Comment by wanyingd1996** [comment]
We can't debug further unless we are able to repro this error, from what you have described, it sounds like it is some configuration or dependency issue, which it unlikely caused by hilt. can you provide a small repro so that we can debug on our side?

**Comment by soochun-deali** [comment]
@kenshin171 
I'm experiencing the same issue. Are you using Dexguard? I encountered this problem after updating Dexguard version

**Comment by kenshin171** [comment]
Hi yes, sorry, this is a Dexguard issue it seems, upgradeing dexguard to versuin 9.5.2 fixes this. this issue can be close, apologies.
