### ISSUE TITLE
[Hilt] onCreate() in my Application doesn't called on Instrument test

### ISSUE THREAD

**Issue by Jaehwa-Noh** [google/dagger#4265]
My application class use ```@Inject``` and do some logic in onCreate() to add data in database.

• SearchFlightApplication.kt
```Kotlin
@HiltAndroidApp
class SearchFlightApplication : Application() {
    @Inject
    lateinit var airportsRepository: AirportsRepository

    @Inject
    lateinit var airportsFtsRepository: AirportsFtsRepository

    @Inject
    @ApplicationScope
    lateinit var applicationScope: CoroutineScope

    override fun onCreate() {
        super.onCreate()
        applicationScope.launch {
            airportsFtsRepository.deleteAndInsertAll(
                airportsRepository.getAllAirportsEntities().map { airportEntity ->
                    airportEntity.asFtsEntity()
                }
            )
        }
    }
}
```

I made my own TestRunner as mentioned in hilt documentation.

• SearchFlightTestRunner.kt
```Kotlin
class SearchFlightTestRunner : AndroidJUnitRunner() {
    override fun newApplication(
        cl: ClassLoader?,
        className: String?,
        context: Context?
    ): Application {
        return super.newApplication(cl, HiltTestApplication::class.java.getName(), context)
    }
}
```

The test is this.

• NavigationTest.kt
```Kotlin
@HiltAndroidTest
class NavigationTest {
    @get:Rule(order = 0)
    val hiltRule = HiltAndroidRule(this)

    @get:Rule(order = 1)
    val composeTestRule = createAndroidComposeRule<MainActivity>()

    @Before
    fun setUp() = hiltRule.inject()

    @Test
    fun whenSearchHAM_ShowSuggestions() {
        composeTestRule.apply {
            onNodeWithContentDescription("Search").apply {
                performClick()
                performTextInput("HAM")
                performImeAction()
            }
            
            /**
             * There are two "HAM" on the screen.
             * One is in the search bar
             * Another is in the suggestions.
             */
            onAllNodesWithText("HAM").assertCountEquals(2)
        }
    }
}
```

But the test is failed because database is empty. It is by the onCreate() function in application not called.
What can I do to call onCreate() in Application to run the business logic?
Do I need a mock database?

You can see the project in my [github](https://github.com/Jaehwa-Noh/Project-Flight-Search-App/tree/compose-flight-search-app)

**Comment by wanyingd1996** [comment]
Hi, did you try adding logs to onCreate to verify onCreate was indeed not called? launch is an asynchronous call, so it may not get to run after the test finishes if you don't have some idling or blocking mechanism to make sure the launched task was executed.

**Comment by Jaehwa-Noh** [comment]
Yes, I tested it with log and no onCreate called. I think we replace the Application to HiltTestApplication. It seemed to brought this situation.

**Comment by wanyingd1996** [comment]
Right, @HiltAndroidTest will generate a test application for you. So @HiltAndroidApp one will be unused. I think [@CustomTestApplication](https://developer.android.com/training/dependency-injection/hilt-testing#custom-application) may help you

**Comment by Jaehwa-Noh** [comment]
I just solve this to implement in ```@Before``` function.
```Kotlin
@Before
    fun setUp() {
        hiltRule.inject()
        runTest {
            airportsFtsRepository.deleteAndInsertAll(
                airportFtsEntitiesTestData
            )
        }
    }
```
Thank you to stay with me.
