### ISSUE TITLE
[Dagger-Hilt] Can't get viewModel in composable by Hilt

### ISSUE THREAD

**Issue by Anatoly4444** [google/dagger#4279]
Hilt can't provide View Model by factory using viewModel() function in composable function. Every time I got:

`Caused by: java.lang.NoSuchMethodException: com.example.myapplication.HomeViewModel.<init> `

My ViewModel class
`@HiltViewModel
class HomeViewModel @Inject constructor(val testClass: TestClass) : ViewModel() {
    fun test() {
        testClass.test()
    }
}`

Composable:
`@SuppressLint("UnusedMaterial3ScaffoldPaddingParameter")
@Composable
fun HomeScreen(
    modifier: Modifier = Modifier,
    viewModel: HomeViewModel = viewModel()
) {
   Button(onClick = { /*TODO*/ }) {

   }
}`

**Comment by danysantiago** [comment]
This should work and is mentioned in the Compose + Hilt docs: https://developer.android.com/develop/ui/compose/libraries#hilt

Please double check your setup, that the Activity or Fragment are annotated with `@AndroidEntryPoint`. That your runtime and annotation processor dependencies are in the module and that the Hilt Gradle plugin is applied.

**Comment by ygq-future** [comment]
Have you solved it?

**Comment by Anatoly4444** [comment]
@ygq-future yes. I added a call of hiltViewModel() instead of viewModel()

**Comment by ygq-future** [comment]
@Anatoly4444 I might need some help because I'm also using hiltViewModel(), but it's still an error

```
@Singleton
@Provides
fun provideUserApi(retrofit: Retrofit): UserApi = retrofit.create(UserApi::class.java)

@HiltViewModel
class LoginViewModel @Inject constructor(
    private val userApi: UserApi,
) : ViewModel() {

}

@Composable
fun LoginScreen(
    modifier: Modifier = Modifier,
    viewModel: LoginViewModel = hiltViewModel(),
) {
}
```

```
Caused by: java.lang.NoSuchMethodException: top.sheepyu.todolist.ui.pages.login.LoginViewModel.<init> []
at java.lang.Class.getConstructor0(Class.java:3325)
at java.lang.Class.getDeclaredConstructor(Class.java:3063)
at androidx.lifecycle.viewmodel.internal.JvmViewModelProviders.createViewModel(JvmViewModelProviders.kt:38)
```

**Comment by Anatoly4444** [comment]
@ygq-future try to check dependencies in documentation. I used these:

implementation("com.google.dagger:hilt-android:2.51.1")  
kapt("com.google.dagger:hilt-android-compiler:2.51.1")  
implementation("androidx.hilt:hilt-navigation-compose:1.2.0")

**Comment by ygq-future** [comment]
@Anatoly4444 Thank you very much, because the version of "com.google.dagger:hilt-android" is 2.51.1, but the version of "com.google.dagger: hilt-Android-compiler "is 2.49, Changed to 2.51.1 after the solution, I did not expect such a small version of such a big difference
