### ISSUE TITLE
Using TestContainer.com 

### ISSUE THREAD

**Issue by JCzz** [google/dagger#4297]
Hi there

Maybe the question reveals that I am still new in Dagger world.
Question: Does it make sense to use testcontainer.com together with dagger? If not why not?

Thanks in advance
Regards
Christian

**Comment by danysantiago** [comment]
Hey, unfortunately we are unfamiliar with 'Testcontainers' and can't provide much guidance. You will have to reach out to a forum more familiar with those tools. Do let us know if you encounter a Dagger / Hilt specific issue.

**Comment by JCzz** [comment]
Sory the link was wrong, it is with an "s": https://testcontainers.com
