### ISSUE TITLE
[KSP2] Dagger and Hilt incompatibility with KSP2

### ISSUE THREAD

**Issue by SimonMarquis** [google/dagger#4303]
Original issue reported on KSP https://github.com/google/ksp/issues/1841

KSP tasks are failing because of a Hilt error when building with Kotlin 2.0.0-RC1 and KSP2 enabled:

- [SimonMarquis/QrCode](https://github.com/SimonMarquis/QrCode/actions/runs/8402466283/job/23011880037?pr=102#step:6:53)
  ```
  > Task :app:kspDebugKotlin
  e: [ksp*** [Hilt*** Class java.lang.Object is not annotated with @AssistedFactory.
  [Hilt*** Processing did not complete. See error above for details.
  e: [ksp*** [Hilt*** Expected @AndroidEntryPoint to have a value. Did you forget to apply the Gradle Plugin? (com.google.dagger.hilt.android)
  See https://dagger.dev/hilt/gradle-setup.html
  [Hilt*** Processing did not complete. See error above for details.
  e: [ksp*** [Hilt*** Expected @AndroidEntryPoint to have a value. Did you forget to apply the Gradle Plugin? (com.google.dagger.hilt.android)
  See https://dagger.dev/hilt/gradle-setup.html
  [Hilt*** Processing did not complete. See error above for details.
  e: [ksp*** [Hilt*** Expected @HiltAndroidApp to have a value. Did you forget to apply the Gradle Plugin? (com.google.dagger.hilt.android)
  See https://dagger.dev/hilt/gradle-setup.html
  ```
- [android/nowinandroid](https://github.com/SimonMarquis/nowinandroid/actions/runs/8710451298/job/23892392500?pr=23#step:17:247)
  ```
  > Task :ui-test-hilt-manifest:kspDemoDebugKotlin FAILED
  e: [ksp] [Hilt] Expected @AndroidEntryPoint to have a value. Did you forget to apply the Gradle Plugin? (com.google.dagger.hilt.android)
  See https://dagger.dev/hilt/gradle-setup.html
  [Hilt] Processing did not complete. See error above for details.
  
  > Task :core:analytics:kspDemoDebugKotlin FAILED
  e: [ksp] java.lang.NullPointerException: null cannot be cast to non-null type androidx.room.compiler.processing.XType
  ```
  This stacktrace also contains an error referenced in this KSP issue:
  - https://github.com/google/ksp/issues/1788

**Comment by danysantiago** [comment]
Dagger / HIlt currently does not support KSP2 as we are still working through the various [breaking changes](https://www.google.com/url?q=https://android-developers.googleblog.com/2023/12/ksp2-preview-kotlin-k2-standalone.html&sa=D&source=buganizer&usg=AOvVaw3k2twHPsGaFXn6SZ6nEH8X) in the APIs. Moreover, the underlying processing library used by Dagger and Hilt (called XProcessing) needs to also be migrated, tracking issue is https://issuetracker.google.com/314151707

**Comment by G00fY2** [comment]
@danysantiago I assume that you are aware of this, but for transparency reasons I wanted to point out that KSP1 will [not be supported with Kotlin 2.1](https://github.com/google/ksp/blob/main/docs/ksp2.md#ksp1-deprecation-schedule): 

> KSP1 will not support Kotlin 2.1. Please plan transitioning from KSP1 to KSP2 during Kotlin 2.0.

Referring to the Kotlin [documentation](https://kotlinlang.org/docs/releases.html) we can expect Kotlin 2.1 at the end of the year (Nov/Dec 2024).

> Language releases (2.x.0) that bring major changes in the language and include tooling updates. Released once in 6 months.

**Comment by ber4444** [comment]
It also prevents using the latest Open JDK (22) as that is only compatible with Kotlin 2.0

**Comment by G00fY2** [comment]
@ber4444 Seems like you are mixing up things. KSP2 is still in beta and not used by default, no matter if you use Kotlin 1.x or Kotlin 2.0. This will only change once Kotlin 2.1 will be released (see https://github.com/google/dagger/issues/4303#issuecomment-2124897316).

Just take a look at the [KSP1 Deprecation Schedule](https://github.com/google/ksp/blob/main/docs/ksp2.md#ksp1-deprecation-schedule).
