### ISSUE TITLE
Inherited component methods with covariant return types are not guaranteed to be generated correctly

### ISSUE THREAD

**Issue by ronshapiro** [google/dagger#431]
If a component inherits methods with the same signature from multiple parent types and they each have a covariant return type, the component type is valid, but javac gives us different members. We implement the first one we see, and we ignore all subsequent methods with the same signature (in AbstractComponentWriter). This behavior is undefined, and we should probably inspect the return types and expose the type which satisfies all of the methods.

Consider:

```
@Module
class M {
  @Provides Number number () {
    return 1.2;
  }

  @Provides int i () {
    return 5;
  }
}

interface One {
  Number number();
}

interface Two {
  Integer number();
}

@Component(modules = M.class)
interface Three extends One, Two {}
```

Here, `DaggerThree.number()` will return `Number` since `One` comes first, but if we swap the order of the declaration of `Three`'s interfaces: 

``` java
@Component(modules = M.class)
interface Three extends One, Two {}
```

we generate a component which compiles, with `DaggerThree.number()` returning `Integer`.

We don't need to worry about a nonlinear relationship between multiple methods, since `javac` will require `Three` to redefine the method.

**Comment by ronshapiro** [comment]
Related to #429

**Comment by ronshapiro** [comment]
I think @netdpb fixed this recently, but I can't find the commit for it.

**Comment by netdpb** [comment]
This was fixed by https://github.com/google/dagger/commit/51d049ff958f97bceba324882c478cb1a10f6e15.
