### ISSUE TITLE
how to manually generate module

### ISSUE THREAD

**Issue by sombriks** [google/dagger#4314]
i understand that dagger has a code generation step
how do i call it from command line?

i am exploring alternative build tools and unable to use maven or gradle plugins

**Comment by wanyingd1996** [comment]
Hi, dagger generates classes with Javac [AnnotationProcessor](https://docs.oracle.com/javase/8/docs/api/javax/annotation/processing/Processor.html) or [KotlinSymbolProcessing](https://kotlinlang.org/docs/ksp-overview.html). I think your question is how to specify annotation processors from command line, this question may be out of our scope. I did some search, and it seems you may use `--processor-path` or` -processorpath` option for javac compiler, reference https://tomgregory.com/gradle/annotation-processors-in-gradle-with-the-annotationprocessor-dependency-configuration/#understanding-annotation-processing-with-javac.
