### ISSUE TITLE
Explain how to add dagger jar files manually to the android project

### ISSUE THREAD

**Issue by 73sravanthi** [google/dagger#4315]
I am trying to add dagger jars generated from source code instead of fetching from maven repo.
Added the jar files for dagger folder and added below lines to the build.gradle file  where dagger dependency is needed

    implementation files('libs/libcore.jar')
    annotationProcessor files('libs/libprocessor.jar')
    implementation group: 'javax.inject', name: 'javax.inject', version: '1'

However unable to build the project. Could anyone help what files has to be added and where exactly we need to added

Getting below error while compiling the project
Unable to load class 'androidx.room.compiler.processing.javac.JavacBasicAnnotationProcessor'
androidx.room.compiler.processing.javac.JavacBasicAnnotationProcessor

**JvmTarget version used = 17**
**Gradle - 8**

Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)

**Comment by 73sravanthi** [comment]
Tried adding the snapshot versions as well. Getting same error. Let me know if I am missing any other jar. Any help is appreciated.

**Comment by danysantiago** [comment]
If you are building Dagger from source and depending on it via file (referencing the jar files) then you also need to manually depend on all other dependencies that Dagger rely on, this is usually done by Gradle when depending via maven coordinates. For a list of Dagger dependencies, see the [POM file](https://search.maven.org/artifact/com.google.dagger/dagger-compiler/2.51.1/jar).
