### ISSUE TITLE
[Error] : java.lang.ClassNotFoundException: Didn't find class "com.myproject.MainApplication" on path: DexPathList

### ISSUE THREAD

**Issue by Shahbaz898414** [google/dagger#4372]
## What happened?
After success fully BUILD android app is not opening

## Error  
java.lang.RuntimeException: Unable to instantiate application com.myproject.MainApplication package com.myproject: java.lang.ClassNotFoundException: Didn't find class "com.myproject.MainApplication" on path: DexPathList[[zip file "/data/app/~~rwa_38OpgJaxfLl0ID3iPw==/com.myproject-_fC4zDSrXuJrtHVA4b1Ruw==/base.apk"],nativeLibraryDirectories=[/data/app/~~rwa_38OpgJaxfLl0ID3iPw==/com.myproject-_fC4zDSrXuJrtHVA4b1Ruw==/lib/x86_64, /data/app/~~rwa_38OpgJaxfLl0ID3iPw==/com.myproject-_fC4zDSrXuJrtHVA4b1Ruw==/base.apk!/lib/x86_64, /system/lib64, /system_ext/lib64]]

## ScreenShot
![image](https://github.com/user-attachments/assets/e1cdb882-5217-4b5a-a238-ff76e90f7649)

**Comment by danysantiago** [comment]
Can you please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)? Why do you suspect this is an issue with Dagger or Hilt?
