### ISSUE TITLE
SomeClass$LazyClassKeyProviders.class generated by Dagger/Hilt is not deterministic

### ISSUE THREAD

**Issue by hungvietnguyen** [google/dagger#4398]
*(This issue was first reported at https://issuetracker.google.com/359616078)*

### Steps to Reproduce (adapted from the above)

1. `git clone https://github.com/cdsap/CpuExperiment`
2. `git checkout reproducing_issue_dex`
3. Run
```
ANDROID_HOME=/path/to/Android/Sdk ./gradlew clean :app:hiltJavaCompileDemoDebug --no-scan --no-build-cache
```
4. Copy the generated class file to `Build1_*.class`: 
```
cp 'app/build/intermediates/hilt/component_classes/demoDebug/com/google/samples/apps/nowinandroid/DaggerNiaApplication_HiltComponents_SingletonC$ActivityCImpl$LazyClassKeyProvider.class' ~/Desktop/Build1_DaggerNiaApplication_HiltComponents_SingletonC$ActivityCImpl$LazyClassKeyProvider.class
```
5. Run step 3 again
6. Copy the generated class file to `Build2_*.class`:
```
cp 'app/build/intermediates/hilt/component_classes/demoDebug/com/google/samples/apps/nowinandroid/DaggerNiaApplication_HiltComponents_SingletonC$ActivityCImpl$LazyClassKeyProvider.class' ~/Desktop/Build2_DaggerNiaApplication_HiltComponents_SingletonC$ActivityCImpl$LazyClassKeyProvider.class
```
7. Compare the generated class files from the 2 builds, the result shows that they're **different** (which is not expected): 
```
diff '~/Desktop/Build1_DaggerNiaApplication_HiltComponents_SingletonC.class' '~/Build2_DaggerNiaApplication_HiltComponents_SingletonC.class' 
Binary files ~/Desktop/Build1_DaggerNiaApplication_HiltComponents_SingletonC.class and ~/Desktop/Build2_DaggerNiaApplication_HiltComponents_SingletonC.class differ
```

### Potential Root Cause

This type of issue is usually caused by the use of non-order-preserving collections such as `HashMap` and `HashSet`, as found in [LazyClassKeyProviders](https://github.com/google/dagger/blob/c69189e046a7e4d8276238aef831f526465254f0/java/dagger/internal/codegen/writing/LazyClassKeyProviders.java#L41-L42). It might be good to audit the entire codebase to remove those usages.

**Comment by LiushuiXiaoxia** [comment]
When will the fix for this issue be released? 
v2.52.1 ?
