### ISSUE TITLE
Add Link to FAQ in sidebar for documentation how-to use @Binds instead of @Provides

### ISSUE THREAD

**Issue by vorburger** [google/dagger#441]
Helo, is [@Binds](https://google.github.io/dagger/api/latest/dagger/Binds.html) supposed to work in the latest released 2.6 already? Or only in HEAD-SNAPSHOT?

If it's supposed to work, then I'm too dumb to figure out the usage, and perhaps the [User's Guide](http://google.github.io/dagger/users-guide.html) could have a few lines to clarify its usage? Currently @Binds is undocumented in the UG. I'd even contributed those lines - if I could get it to work.

So according to the JavaDoc, "(...) @Binds abstract Random bindRandom(SecureRandom secureRandom); @Binds methods are a drop-in replacement for Provides methods that simply return an injected parameter. Prefer @Binds because the generated implementation is likely to be more efficient."

So I'm replacing something like:

```
@Module class Wiring {
    @Provides GreetService greetService() {
        return new TestGreetService();
    }
}
```

with:

```
abstract @Module class Wiring {
    abstract @Binds GreetService greetService(TestGreetService impl)
}
```

but, as far as I understand from what I can tell, the abstract @Module Wiring seems to make Dagger not generate its Wiring_GreetServiceFactory.java class anymore (or generate it wrong with the get() contained module.greetService() which doesn't compile; but I think that's just a left-over from before changing it over; after it clean, it's simply not there). And so then you get "GreetService cannot be provided without an @Provides-annotated method."

What am I not getting?

**Comment by ronshapiro** [comment]
`Wiring_GreetServiceFactory` is no longer necessary with a @Binds method since we can delegate to the `TestGreetService_Factory`. 

I wonder if something is going wonky with where you are placing your annotations. They should come before `abstract`, and it's possible if you're using Java 8 that this would actually cause them to be interpreted as type annotations instead of method annotations

**Comment by vorburger** [comment]
@ronshapiro Tx for prompt reply. I must have had some other issue (unclear) - because it works now! Even WITH the annoations places after abstract, as type annotations (this is on Java 8). So.. really sorry for the bother, case closed!

Would a contribution with a line to the User's Guide re. @Binds be welcome?

**Comment by ronshapiro** [comment]
Gah - it looks like our FAQ is not available on the sidebar. Here's a link, I'll make sure to add it.

Does this have what you're looking for? http://google.github.io/dagger/faq

@gk5885 we may still want to add info about `@Binds` somewhere

**Comment by vorburger** [comment]
@ronshapiro ah that FAQ is useful - never seen (found) it! ;-)

**Comment by ronshapiro** [comment]
@gk5885 is going to add some docs to the users guide and the sidebar fix will come soon. thanks for reporting!
