### ISSUE TITLE
Feature Request: Support Multibinding Transforms

### ISSUE THREAD

**Issue by eliptus-google** [google/dagger#4425]
Given a multibinding `Map<Key, Foo>`, allow generating `Map<Key, Bar>`, where `Bar` takes `Foo` as an injected (or "assisted") dependency.

**Comment by Chang-Eric** [comment]
This would also add a ton of possible bindings in weird ways if say you wanted to allow a `Bar` -> `Baz` -> `Foo` as you could have a whole chain of bindings that don't work except in this multibinding usage. I could see a lot of weird things also happening with cycles or inclusion of other maps.
