### ISSUE TITLE
Is Hilt uses alpha version of Dagger’s KSP support under the hood?

### ISSUE THREAD

**Issue by Tooto** [google/dagger#4429]
In official Dagger [documentation](https://dagger.dev/dev-guide/ksp.html) said:

> Warning: Dagger’s KSP support is currently in alpha.

In Hilt [release notes](https://developer.android.com/jetpack/androidx/releases/hilt) said: 

> Add KSP support to androidx.hilt.

So, my question is: is Hilt uses alpha version of Dagger’s KSP support under the hood?

**Comment by kuanyingchou** [comment]
Hi, @Tooto , sorry for the confusion but yes, the KSP support for both Dagger and Hilt are still in alpha. For the reason please see https://github.com/google/dagger/issues/2349#issuecomment-2329852274.

The Hilt release note you linked only refers to the AndroidX part of Hilt, which contains integrations with other AndroidX libraries like WorkManager and Compose. For overall KSP support for both Dagger and Hilt please follow [the Dagger KSP page](https://dagger.dev/dev-guide/ksp.html) or [Dagger release notes](https://github.com/google/dagger/releases).
