### ISSUE TITLE
NoSuchMethodError on compileDevelopmentDebugJavaWithJavac

### ISSUE THREAD

**Issue by kdaypossible** [google/dagger#446]
This build error is created when compiling with 2.6, but not 2.2. 
Execution failed for task ':cnn:compileDevelopmentDebugJavaWithJavac'.
> java.lang.NoSuchMethodError: com.google.common.collect.FluentIterable.append(Ljava/lang/Iterable;)Lcom/google/common/collect/FluentIterable;

This issue seems similar to https://github.com/google/dagger/issues/356 and the same solution works for this error too. Include guava explicitly with the apt plugin.

The other annotation processor in the project in this case is realm 2.1.3.

**Comment by ronshapiro** [comment]
Did you check to make sure the gradle versions are up to date with what's referenced there?

There's not much we can do here, guava has a stable API, and the other annotation processors should make sure to update.

**Comment by kdaypossible** [comment]
Yes. I'm using grade plugin 2.1.3, realm 1.2.0, gradle 2.14.1. So I'll check realm's repo to see what guava version they're using then.

**Comment by kdaypossible** [comment]
It actually seems like an issue with databinding. I followed up with the realm team and they don't actually use guava. But I did forget to mention earlier that databinding is enabled. You can check out the dependencies graphs in this issue: https://github.com/realm/realm-java/issues/3344

**Comment by rakshitsoni02** [comment]
facing same issue, My build fails after apply plugin: 'realm-android' in app level gradle file . 

error: cannot find symbol class DaggerApplicationComponent any suggestions will be helpful
