### ISSUE TITLE
@Qualifiers Ignored if @Inject is on secondary constructor

### ISSUE THREAD

**Issue by undermark5** [google/dagger#4485]
When using a secondary constructor that is annotated with `@Inject` Hilt behaves as expected with no specified qualifier, however, as soon as you try to add a qualifier to the type, this is completely ignored. I'd expect that the qualifier on the type is respected when it comes to the secondary constructor. Also, since Dagger/Hilt complains about qualifiers on constructors, it's impossible to have both a secondary constructor annotated with inject and a qualifier (without having to manually create a `@Provides` function in a module).

This is an issue both with KSP and KAPT.

**Comment by Chang-Eric** [comment]
Dagger doesn't support qualifiers on `@Inject` types in general. If you want to bind a qualified type, you have to use an `@Module`.

I'm not sure if you were implying that qualifiers worked when `@Inject` is on the primary constructor. However, if you are seeing that, I think that is a bug that we probably need to look into.

**Comment by undermark5** [comment]
Ah, that would explain it. No, I'm not seeing that behavior with primary constructors. We've got some secondary code generation running that is providing some of that benefit already, which is where I got confused. That's good to know though.
