### ISSUE TITLE
No dependencies reported for generated source after 2.53 and Kotlin 2.1.0 update

### ISSUE THREAD

**Issue by G00fY2** [google/dagger#4526]
After we updated to Dagger 2.53 and Kotlin 2.1.0 we now see a lot of similar warnings already reported in the past: https://github.com/google/dagger/issues/4182.

There is also already a new bug in the issue tracker: https://issuetracker.google.com/issues/381887333

Since we did not see any errors with Kotlin 2.0.21 and Dagger 2.52 I think this is not caused by our dependency or project setup.

This warning is shown only for every androidx.lifecycle.**ViewModel** and no other classes in our project:
```
w: [ksp] No dependencies reported for generated source

MyViewModel_HiltModules_KeyModule_Provide_LazyMapKey.java which willprevent incremental compilation.

MyViewModel_ViewModel_HiltModules_BindsModule_Binds_LazyMapKey.java which willprevent incremental compilation.
```

- AGP: 8.7.3
- Gradle: 8.11.1
- Dagger: 2.53
- Kotlin: 2.1.0
- AndroidX lifecycle-viewmodel-ktx 2.8.7

**Comment by jrodbx** [comment]
Also seeing this with Dagger 2.53 and Kotlin 2.0.21, so looks like this might be isolated to the Dagger 2.53 release?

**Comment by bcorso** [comment]
Thanks for reporting this!

I think the issue is that the new [`LazyMapKeyProxyGenerator`](https://github.com/google/dagger/blob/master/java/dagger/internal/codegen/writing/LazyMapKeyProxyGenerator.java) does not add an originating element.

I'll fix this and release a 2.53.1 update.

**Comment by lassem** [comment]
I had a feeling the room link for the issue tracking was misleading! Oh well 👍🏻

**Comment by akingyin1987** [comment]
When will the next version be released?

**Comment by bcorso** [comment]
I plan on doing a release today.
