### ISSUE TITLE
Cannot find symbol `_LazyMapKey` in 2.53

### ISSUE THREAD

**Issue by bddckr** [google/dagger#4530]
In version `2.52` I had no issues, but updating to `2.53` gives issues when `@LazyClassKey` is used:

```
/something/build/generated/source/kapt/debugAndroidTest/something/DaggerSomethingComponent.java:41: error: cannot find symbol
import something.SomethingElse_Module_ProvideType_LazyMapKey;
                                       ^
  symbol:   class SomethingElse_Module_ProvideType_LazyMapKey
```

The `SomethingElse_Module` is generated by my own code generator via Anvil.

```kotlin
// Generated by Anvil.
// https://github.com/square/anvil
@file:Suppress(
  "DEPRECATION",
  "OPT_IN_USAGE",
  "OPT_IN_USAGE_ERROR",
)

package something

import com.squareup.anvil.annotations.ContributesTo
import dagger.Module
import dagger.Provides
import dagger.multibindings.IntoMap
import dagger.multibindings.IntoSet
import dagger.multibindings.LazyClassKey
import dagger.multibindings.StringKey
import kotlin.String
import kotlin.Suppress
import kotlinx.serialization.modules.SerializersModule
import kotlinx.serialization.modules.polymorphic
import kotlinx.serialization.modules.subclass

@Module
@ContributesTo(AppScope::class)
public object SomethingElse_Module {
  @Provides
  @IntoMap
  @LazyClassKey(SomethingElse::class)
  public fun provideType(): String =
      "SomethingElse"
}
```

Note that I had to rename/hide some sensitive details here. Hopefully it still makes sense.

If this looks like an issue with Anvil instead I'll open an issue there. But to me this looks like an issue in the latest Dagger version (especially, but not only due to it reproducing in the new Dagger release only).

**Comment by bcorso** [comment]
This looks like an Anvil issue.

Anvil uses its own Kotlin plugin to generate factory classes for modules -- i.e. it attempts to replace Dagger's annotation processor and handle code generation itself. In Dagger 2.53 there's an additional generated class for `LazyClassKey` in modules, so I suspect the issue is that Anvil doesn't yet generate this class.

**Comment by bddckr** [comment]
Thanks a lot for the help!

**Comment by bcorso** [comment]
@nitinsethimicrosoft can you provide a repro of this?

If not, can you look at the library/module where `@LazyClassKey` is used and verify the following:
  1. the `build.gradle` dependencies contains the updated dagger dependency (`com.google.dagger:dagger-compiler:2.55`).
  2. the `build` directory contains the expected generated file, e.g. `..._LazyMapKey`

**Comment by nitinsethi86** [comment]
@bcorso The bindings were in Kotlin files with kapt not being applied. When I applied kapt, the build was successful. 
It seems that the latest version doesn't ignore incorrect configuration (which is great!). Thanks for the pointers.
