### ISSUE TITLE
Android Lint flags `SyntheticAccessor` for `return InstanceHolder.INSTANCE` statement in _Factory.java

### ISSUE THREAD

**Issue by TWiStErRob** [google/dagger#4544]
Dagger 2.53.1

Source code:
```kotlin
@Singleton
class StaticDataSource @Inject constructor() {
}
```

Android Lint:
```
StaticDataSource_Factory.java:32: Error: Access to private field INSTANCE of class InstanceHolder requires synthetic accessor [SyntheticAccessor]
      return InstanceHolder.INSTANCE;
                            ~~~~~~~~

     Explanation for issues of type "SyntheticAccessor":
     A private inner class which is accessed from the outer class will force the
     compiler to insert a synthetic accessor; this means that you are causing
     extra overhead. This is not important in small projects, but is important
     for large apps running up against the 64K method handle limit, and
     especially for libraries where you want to make sure your library is as
     small as possible for the cases where your library is used in an app
     running up against the 64K limit.

  1 errors, 0 warnings
```

I think the `PRIVATE` for the `INSTANCE` field should be default visible here?

https://github.com/google/dagger/blob/d33c3e732e3899132f7e62080668802dc88d941a/java/dagger/internal/codegen/writing/FactoryGenerator.java#L160-L173

**Comment by bcorso** [comment]
Yeah, the field doesn't actually need to be `private`, I can remove that modifier. 

Fwiw, I was actually planning to remove the `private` anyway for the purposes of generating kotlin sources since it'll be a kotlinc error if the outer class tries to access a `private` property.

**Comment by bcorso** [comment]
> A private inner class which is accessed from the outer class will force the compiler to insert a synthetic accessor; this means that you are causing extra overhead.

I also wonder if this is a false positive since the class is `static`. I don't mind making the change anyway, but just curious.

**Comment by JakeWharton** [comment]
Whether `static` or inner, access to private resources across nested types will always create a synthetic accessor. This is because neiter the bytecode nor VM has the concept of nesting, since it was introduced to the language after-the-fact in Java 1.1. This was remedied in Java 11 when the bytecode was changed to explicitly model nesting, and the VM was updated to enforced nesting boundaries at runtime as part of regular access control.

Example: https://java.godbolt.org/z/GzEsGdsns

(Change to `--release 11` to see the accessor disappear with nestmates!)

**Comment by bcorso** [comment]
Ah, thanks for the explanation and context!

**Comment by bcorso** [comment]
@TWiStErRob it seems there's probably a lot more we could do here, e.g. there's a number of these private field interactions in the generated component implementations (especially in fastInit mode between the component and its SwitchingProvider classes) where we could remove the `private` modifier as well. I'm happy to take a look at those if you think it would improve things for you. 

However, just for my own understanding, from Jake's comment in https://github.com/google/dagger/issues/4544#issuecomment-2555686059 it sounds like another option is to just target Java 11 or higher. I'm guessing that's not an option in your case, or am I misunderstanding things?

**Comment by TWiStErRob** [comment]
Will double-check the target version that's what I understood too. I'm not sure if we use fastinit either. I'm in EU, just starting work again.

**Comment by TWiStErRob** [comment]
So, we set `kotlin { jvmToolchain(17) }`, which as far as I know sets the java toolchain/source/target too. Validated this with `tasks.withType<JavaCompile>().configureEach { doFirst { println(targetCompatibility) } }` and checking the `.class` file version.

I think the problem here is that [`SyntheticAccessor` lint detector](https://cs.android.com/android-studio/platform/tools/base/+/mirror-goog-studio-main:lint/libs/lint-checks/src/main/java/com/android/tools/lint/checks/SyntheticAccessorDetector.kt;l=51?q=SyntheticAccessor&sq=) is not aware of target version.

Am I reading this right, @JakeWharton?

**Comment by JakeWharton** [comment]
Dalvik bytecode and ART do not support nestmates, so D8 (or R8) will desugar them into synthetic accessor methods.

**Comment by TWiStErRob** [comment]
So I guess that means Dagger generated code needs changes.

For now we just added this as a workaround:
```xml
<lint>
    <issue id="SyntheticAccessor">
        <!-- Dagger generates java code that uses private accesses: https://github.com/google/dagger/issues/4544 -->
        <ignore path="**/generated/**/*.java" />
    </issue>
</lint>
```

**Comment by JakeWharton** [comment]
Although I will say it's less of a problem today than it was a decade ago. Android API 21 and newer support native multidex and that's considered old, so needing to fit within a single dex is less of an issue today.

Additionally, many more people are using R8 than were using ProGuard a decade ago and it will inline synthetic accessors away (provided it can successfully escalate the visibility of the backing field or method).

That being said, it's one thing to ignore a handful of synthetic accessors that get generated in hand written code, and it's another thing to produce them in generated code in potentially hundreds of instances.
