### ISSUE TITLE
Regression from Dagger 1: cannot bind modules unknown at compile-time

### ISSUE THREAD

**Issue by ogregoire** [google/dagger#474]
In Dagger 1, I had an `ObjectGraph` to which I could add Modules as I discovered them. In Dagger 2 (2.7), it's not possible anymore.

Dagger 1 working example:

**DaggerModule.java**

    public interface DaggerModule { }

**MyModule.java**

    @com.google.auto.service.AutoService(DaggerModule.class)
    @dagger.Module(injects = MyApp.class)
    public class MyModule implements DaggerModule {
      @dagger.Provides String hello() { return "hello"; }
    }

**MyApp.java**

    import com.google.common.collect.ImmutableList;
    import java.util.ServiceLoader;

    public class MyApp {
      @javax.inject.Inject String hello;
      public void sayHello() { System.out.println(hello); }
      public static void main(String[] args) {
        dagger.ObjectGraph.create(ImmutableList.copyOf(ServiceLoader.load(DaggerModule.class)).toArray())
            .get(MyApp.class)
            .sayHello();
      }
    }

Now, if I try with Dagger 2, I can't get anything working:

**DaggerModule.java**

    public interface DaggerModule { }

**MyModule.java**

    @com.google.auto.service.AutoService(DaggerModule.class)
    @dagger.Module
    public class MyModule implements DaggerModule {
      @dagger.Provides String hello() { return "hello"; }
    }

**MyApp.java**

    import com.google.common.collect.ImmutableList;
    import java.util.ServiceLoader;

    @dagger.Component
    public interface MyApp {
      public static void main(String[] args) {
        ImmutableList<DaggerModule> modules = ImmutableList.copyOf(ServiceLoader.load(DaggerModule.class));
        DaggerMyApp.builder()
            // Can't add any of the modules
            .build();
      }
    }

Is there anything I'm actually missing? Because to me, it seems I just can't make a custom plugin library anymore. I had to work hard to make it work in Dagger 1 and was happy when I discovered the `@IntoSet` annotation which removed that pain rather easily. But I got into another caveat, which seems without solution to me.

**Comment by ronshapiro** [comment]
This is Working As Intended. Dagger 2 takes advantage of full compile-time static analysis to build the graph. What you're doing isn't safe - there's no guarantee that you don't do something like:

```java
public class MyModule implements DaggerModule {
  @dagger.Provides String hello() { return "hello"; }
  @dagger.Provides String world() { return "world"; }
}
```

Which would result in a duplicate binding error at runtime.

**Comment by ogregoire** [comment]
@ronshapiro So? I don't need training wheels on my bike: I can ride it without falling... Why do you want I have those training wheels?

**Comment by ronshapiro** [comment]
So why not use Guice or Dagger 1?

**Comment by ogregoire** [comment]
Guice is too heavy and slow and relies on reflection which I avoid for this project. [Dagger 1 is deprecated and recommends switching to Dagger 2](https://github.com/square/dagger/).

**Comment by ronshapiro** [comment]
I think this is probably better served as a question on stackoverflow of what you're trying to do. You should also probably look at http://google.github.io/dagger/testing#option-2-separate-component-configurations

**Comment by ogregoire** [comment]
@ronshapiro [Done](http://stackoverflow.com/questions/39794112/how-do-i-add-an-unknown-amount-of-modules-in-dagger-2), thanks.
