### ISSUE TITLE
Component Builder callback after its built

### ISSUE THREAD

**Issue by ZakTaccardi** [google/dagger#475]
I would like some type of callback for internal use (within the builder itself) when a dagger sub/component is built. Maybe a `postBuild(Component component)` that is called automatically during the `.build()` method.

For example, I have a `DataLayerComponent`. When it is built (`.build()` is called on it),  I want to statically set the component as a variable in a `DataLayer` class.

Currently I can create an alternate method that wraps `build()` to achieve this, but it's a little messy. Because an example is worth a 1000 words:

       /**
         * use {@link #construct()} instead
         */
        @Deprecated
        public abstract DataLayerComponent build();

        public DataLayerComponent construct() {
            DataLayerComponent component = build();
            DataLayer.set(component);
            return component;
        }

**Comment by gk5885** [comment]
Especially given that you could make build() non-public, I think what you have is actually pretty good. Your use case seems pretty niche otherwise, so I don't think I'd be in favor of adding this generally.

**Comment by ZakTaccardi** [comment]
Didn't consider making `protected build()`, definitely agree!

**Comment by gk5885** [comment]
Also, given your specific example, I'd consider buildAndRegister or something for the method name to better convey the distinction at the call site.
