### ISSUE TITLE
Dagger2 : Cannot find symbol @Autofactory classes

### ISSUE THREAD

**Issue by jag4364u** [google/dagger#477]
I started my project to migrate from dagger 1 to dagger 2 . However, all my @Autofactory classes which worked in dagger1 are showing errors like "Cannot find symbol MyclassFactory" all over my project even though those classes are already genearted. Is it a known issue that dagger 2 will not work with Autofactory? Basically i am trying to inject AutoFactory classes object using @Inject (Field injection).  
Please look at this issue.
http://stackoverflow.com/questions/39909450/dagger2-cannot-find-symbol-autofactory-classes

**Comment by ronshapiro** [comment]
see my answer on your SO post
