### ISSUE TITLE
Is there a specific lint api for Dagger2

### ISSUE THREAD

**Issue by droidekas** [google/dagger#494]
I searched quite a bit, but did not come across any. If someone could point me in a direction for implementation.I could try my hand at this

**Comment by ronshapiro** [comment]
Can you elaborate about what you want to be linting?

**Comment by droidekas** [comment]
While Dagger compile time errors work well when they are alone. They do not output anything when you integrate other annotation processors (Databinding). This makes solving errors a nightmare. It could be as simple as missing providers or incorrect dependencies but Dagger does not provide those outputs. The final output of `compileDebugJavaWithJavac` will always indicate Databinding errors.

I would like someway to separate the different annotation processors and hence get logical errors. This is what I would want to lint, Or if you think there is a better approach instead of lint ,I'd like to try that too.

**Comment by ronshapiro** [comment]
This might be what you're looking for: https://github.com/google/dagger/issues/306#issuecomment-180283287

Doing something like linting will be very challenging - you'll essentially be trying to reimplement a lot of the dagger processor when you see an issue, but with less information.

**Comment by droidekas** [comment]
This does help,thanks a lot!
