### ISSUE TITLE
Document how to apply the Dagger Error Prone refactorings

### ISSUE THREAD

**Issue by DmitriyZaitsev** [google/dagger#501]
Hi there,

@gk5885 [said](https://youtu.be/iwjXqRlEevg?t=1320) you'll have great instructions of how we can do some automated refactorings to move from the old style provides-methods to binds-methods.
Do these instructions exist anywhere?

**Comment by gk5885** [comment]
Sort of.  The refactoring can be done using [Error Prone](https://github.com/google/error-prone).  The [`UseBinds`](http://errorprone.info/bugpattern/UseBinds) check is the one that you're asking about and it is already available as part of that project.

The tricky part is creating and applying the patch.  [This commit](https://github.com/google/error-prone/commit/de639a1ef4d962b984741ed346f0519c85eb6122) added a `-XepPatch` flag to do just that, but I believe that it is currently experimental and undocumented.  That said, it looks like it's part of the `2.0.14`, so you could give it a try.

Anyway, I have a TODO to document that process as soon as it is fully supported by Error Prone, so this can just become the tracking bug for that.

**Comment by gk5885** [comment]
cc: @eaftan, @cushon, @nglorioso

**Comment by DmitriyZaitsev** [comment]
Thanks Greg.
Well, the feature is really very experimental. `UseBinds` check works but not like a charm. Somehow it skips many modules and even doesn't warn, so it should be improved.

**Comment by eaftan** [comment]
@DmitriyZaitsev Can you file a bug in https://github.com/google/error-prone/issues with your experience around UseBinds?  Specifically what modules is it skipping and how it should be improved, and repro instructions if possible.

**Comment by alouanemed** [comment]
Hey, Any updates to the doc for this ?

**Comment by ronshapiro** [comment]
I think this is something that we should punt over to ErrorProne.
