### ISSUE TITLE
[Question] Passing injected dependencies to Activity

### ISSUE THREAD

**Issue by luispereira** [google/dagger#503]
I'm trying to create some tests of an activity which has some injections (Presented and one other object). 
I already made some mock DaggerInjection for my Test class e.g.:

Testing Activity class
```
    @Inject DialogManagerMock mDialogManager;
    @Inject CertificatePresenterMock mPresenter;

 @Rule
    public ActivityTestRule<CertificateActivity> mActivityTestRule = new ActivityTestRule<CertificateActivity>(CertificateActivity.class)

   (...)
    @Before
    public void init() {
        CertificateComponentTest activityComponent = DaggerCertificateComponentTest.builder()
                .appComponent(SecureNetApplication.getInstance())
                .certificateModuleTest(new CertificateModuleTest())
                .build();
        activityComponent.inject(this);
    }
```

My question is, if there is a way to pass the injected mocked objects to the activity?
Does dagger allows this somehow? Or is there other solution for this?

**Comment by frogermcs** [comment]
@luispereira please take a look at my article: https://medium.com/azimolabs/activities-subcomponents-multibinding-in-dagger-2-85d6053d6a95#.w77ttr45a . At the end there is paraghraph **Example of use case — instrumentation tests mocking** I believe it can help you with mock injection.

**Comment by gk5885** [comment]
Please post questions to [StackOverflow](http://stackoverflow.com/questions/tagged/dagger-2).  It's a better tool for asking, answering and discovering questions and solutions.
