### ISSUE TITLE
Double Checked Locking on @Singleton Providers 

### ISSUE THREAD

**Issue by naturalwarren** [google/dagger#506]
I watched a talk with Ron Shapiro & David P (https://youtu.be/wCvXe2LsN5o?t=20m50s) which prompted me to remove scopes on my Providers that are backed by constant/final fields. This removed DoubleChecked Providers in my generated components.

Annotating these Providers however seems useful to denote that something is backed by Singleton. But annotating with `@Singleton` results in my generated component producing DoubleChecked Providers. All the Dagger examples on the web use `@Singleton`.

Why are DoubleChecked Providers generated for the `@Singleton` scope from JSR-330? I'd be happy to make a pull request if DoubleChecked locking is in fact not required for `@Singleton` Providers.

**Comment by JakeWharton** [comment]
If two threads request the object concurrently it would violate the scoping
without DCL.

**Comment by ronshapiro** [comment]
Our point was: Scope what should be scoped for _correctness_. If you have a constant, scoping it has no effect at all.

I was initially working on an error (if you use Error Prone) for cases when you return a constant from a `@Provides` method, but got some pushback on it. We could go the opposite direction, i.e. have a special annotation which allows you to use scopes as documentation, but allows Dagger to avoid the DCL. The idea is something like this:

```java
@Provides
@ActivityScope @Constant
Activity provideActivity() {
  return this.activity; // set final via constructor
}
```

The one caveat is that we'd need Error Prone to enforce the fact that the method is in fact returning a constant, and currently with maven/gradle we have no way of enforcing that Error Prone is being used. I'm no so comfortable releasing a feature that could easily be misused (without Error Prone).

**Comment by naturalwarren** [comment]
Thanks Ron and Jake.

**Comment by hzsweers** [comment]
@ronshapiro would it be possible to have that be a compiler arg and opt-in?

**Comment by gk5885** [comment]
@hzsweers, no.  This type of check requires that you see the full AST, not just the level provided by the element API.  We wouldn't be able to implement such a check without prodding at the implementation details of the compiler in which you happen to be running.

Plus, the power of Error Prone is that it gives you a mechanism for applying fixes automatically.  Emitting a warning or something from the annotation processor would actually be a poorer experience IMO.

**Comment by hzsweers** [comment]
Fair enough
