### ISSUE TITLE
Dagger does not work with Jack

### ISSUE THREAD

**Issue by Dev-Tony** [google/dagger#507]
I tries to make Java8 work with Jack tool.

But I found an exception:
```
Execution failed for task ':app:transformJackWithJackForDebug'.
> com.android.jack.ir.JNodeInternalError: java.lang.Exception: java.lang.NoSuchMethodError: com.google.common.base.CharMatcher.whitespace()Lcom/google/common/base/CharMatcher;
```

gradle config
``` 
    // dagger 2
    compile 'com.google.dagger:dagger:2.6'
    annotationProcessor 'com.google.dagger:dagger-compiler:2.6'
    // auto-value
    compile 'com.google.auto.value:auto-value:1.2'
    annotationProcessor 'com.google.auto.value:auto-value:1.2'
```

dependecy:
```
./gradlew app:dependencies --configuration=annotationProcessor
:app:dependencies

------------------------------------------------------------
Project :app
------------------------------------------------------------

annotationProcessor - Classpath for the annotation processor for 'main'.
+--- com.google.dagger:dagger-compiler:2.6
|    +--- com.google.dagger:dagger:2.6
|    |    \--- javax.inject:javax.inject:1
|    +--- com.google.dagger:dagger-producers:2.6
|    |    +--- com.google.dagger:dagger:2.6 (*)
|    |    \--- com.google.guava:guava:19.0
|    \--- com.google.guava:guava:19.0
\--- com.google.auto.value:auto-value:1.2

(*) - dependencies omitted (listed previously)
```

I have created a project on github: [jack-dagger-crash](https://github.com/Dev-Tony/jack-dagger-crash)

**Comment by gk5885** [comment]
`CharMatcher.whitespace()` was added in Guava 19.  It does seem that you have that as a dependency, but I wonder if an old version is somehow sneaking onto the classpath.  Can you show the same tree for your classpath?

**Comment by ronshapiro** [comment]
What version of the android build tools are you using? Try upgrading, because users have had issues with that before.

**Comment by gabrielittner** [comment]
Sounds like this issue which will be Fixed in Version 2.3 of the android
gradle plugin https://code.google.com/p/android/issues/detail?id=213471

**Comment by Dev-Tony** [comment]
Hi I have created a project on GitHub, you can try it and push your changes if you have an solution. Thanks.
https://github.com/Dev-Tony/jack-dagger-crash

**Comment by Dev-Tony** [comment]
@gabrielittner yes, you are right. It is a bug of gradle plugin.
It works with  'com.android.tools.build:gradle:2.3.0-alpha2'
