### ISSUE TITLE
Why do need "dagger-android" artifact?

### ISSUE THREAD

**Issue by johnkil** [google/dagger#512]
Changelog for Dagger 2.8 has next line "Our first release of the dagger-android artifact". Why do need this artifact?

**Comment by ronshapiro** [comment]
It's not a requirement for usage of dagger on Android. it's got the beginnings of some Android specific classes that aren't applicable if your target platform is something besides an Android device

**Comment by johnkil** [comment]
@ronshapiro thanks for the answer :smiley:
