### ISSUE TITLE
Incorrect constructor in example in User Guide

### ISSUE THREAD

**Issue by varunvats** [google/dagger#518]
In the [Subcomponents](http://google.github.io/dagger/subcomponents.html) page under the section **Subcomponents for encapsulation**, the constructor for `DatabaseImplModule` is labelled `DatabaseModule` instead of `DatabaseImplModule`. The relevant snippet is pasted below:

```java
@Module
class DatabaseImplModule {
    DatabaseModule(int concurrencyLevel) {}  // should be DatabaseImplModule
    @Provides DatabaseConnectionPool provideDatabaseConnectionPool() {}
    @Provides DatabaseSchema provideDatabaseSchema() {}
}
```

**Comment by ronshapiro** [comment]
I'm not sure when, but this was fixed at some point. Thanks for reporting it!
