### ISSUE TITLE
Dagger2 does not generate a builder setter for a module if it is abstract

### ISSUE THREAD

**Issue by j-baker** [google/dagger#521]
We're just testing Dagger 2.7, and we're seeing that Dagger is able to generate a builder for which we have no setter method for a few of our modules.

So, we have

```
public static final class Builder {
    private MyModule myModule;

    public MyComponent build() {
         if (myModule == null) {
            throw new IllegalStateException(MyModule.class.getCanonicalName() + " must be set");
        }
    }
}
```

(with extra modules omitted).

Obviously this means that you can never actually construct the Dagger component.

The only difference from our point of view between the modules that have builder methods written and the modules that do not is that the modules that are omitted are abstract classes.

**Comment by ronshapiro** [comment]
Can you post a sample that exhibits this?

**Comment by ronshapiro** [comment]
I'm closing this, but feel free to reopen if you have more information.

**Comment by 4ndro1d** [comment]
We had a similar issue and the problem was that the @Peovides method was not static. I took the advise from here:
https://stackoverflow.com/q/44075860/1177083
