### ISSUE TITLE
Dagger 2 doesn't implement some of the component methods in Android project with custom annotation processor

### ISSUE THREAD

**Issue by jhutarek** [google/dagger#524]
Hi,

we've encountered a strange problem which I haven't seen anywhere:

- We have a huge Android project where we inject presenters to our fragments using field injection. The corresponding component interface `MyFeatureComponent` has methods like `void inject(MyFeatureFragment fragment);` and the fragment is injected in its `onViewCreated()` callback like this: `MainApplication.get().getInjector().inject(this);` - nothing unusual here.
- Thanks to MVP, our fragments are very dumb, so we generate some of their boilerplate with our custom annotation processor: We write abstract base fragment and the processor generates implementation which (among others) creates this line: `@Inject MyPresenter presenter;` and also the `...inject(this)` call.
- And then it gets very strange: __for *some* of the fragments, Dagger doesn't generate `inject` method implementation__ (specified in `MyFeatureComponent` interface from which `MainComponent` inherits) in DaggerMainComponent, so the build fails with standard "class is not abstract and does not implement...." message. No errors from Dagger or our processor (our fragment class implementation is always generated correctly). However, Dagger *generates* members injector for the fragment, so in some way, it knows about the fragment implementation our annotation processor generated.
- __If we write the whole fragment (including the field and the inject call) manually, Dagger always generates inject() implementation.__
- __Or, if we move the `void inject(MyFeatureFragment fragment);` method up to `MainComponent`, Dagger also generates the implementation correctly.__
- Our project is very huge and we haven't been able to find out why some of the inject() methods are generated and others are not, it seems completely random, but the non-generated methods are the same in each build. In some cases, Dagger doesn't even implement `inject()` for hand-written fragments if there are other generated fragments in the same package.
- Tried to switch off incremental compilation, no change.
- __Minimal working example here:__ [dagger-sample-repo.zip](https://github.com/google/dagger/files/643294/dagger-sample-repo.zip)
- We are quite sure our annotation processor is OK regarding initialization, file writting, processing rounds etc. 

Our annotation processor is written entirely in Kotlin and parts of the app use Kotlin as well. Tried with Dagger 2.6 thru 2.8.

We're at our wits end here and have no better theory than that something is wrong with Dagger. Any ideas please? Thank you very much!

**Comment by ronshapiro** [comment]
There's a lot here and I'm not sure where to begin. But there are a lot of issues with `kapt` and Dagger, and it's not something that we explicitly support, so I don't know what we can do to help. 

Have you checked out the new `dagger.android` code in `2.10`? That might help out. Feel free to reopen or file a new issue if you want to follow up here.

**Comment by jhutarek** [comment]
After further investigation, I managed to greatly reduce the minimal working sample (no Kotlin, tiny annotation processor etc.), can you take a look at this? https://github.com/google/dagger/issues/665 Thanks!

**Comment by ronshapiro** [comment]
Ok we can continue discussing in the new bug
