### ISSUE TITLE
Feature Request: Overriding bindings from included modules

### ISSUE THREAD

**Issue by cesar1000** [google/dagger#525]
I am setting up a Dagger graph to support the needs of a deep hierarchy of classes. Each class has its own dagger graphs that may be extended by subclasses. In some cases, I may want a subclass to replace a binding altogether with a different implementation.

These are the options I understand I currently have in Dagger 2:

* Use inheritance to extend base class modules and replace the implementation of the providers. This is generally undesirable, since it forces all implementations to take the same set of dependencies (as defined by the arguments to the provider method).
* Break off bindings that I intend to override to a separate module, and rewrite this module in all subclasses that need to override any one of the dependencies. This is hard to maintain and likely to cause duplication (although using `@Binds` would alleviate the problem).

Ideally, I would like to be able to do something like this:

```
@Module
class BaseClassModule {
    @Provides
    String provideString() { ... }
}

@Module(includes = BaseClassModule.class)
class SubclassModule {
    @Provides(override = true)
    String provideString(String fromThisString) { ... }
}
```

The override would be local to the module, and only prevent the binding in the included module(s) to be considered. This may also be used to deal with conflicting bindings from multiple included modules (in the style of C++ dealing with conflicting method implementations when using multiple inheritance).

Does Dagger currently offer an alternative solution to this problem? Or is this something we may expect to see in a future release?

**Comment by gk5885** [comment]
Within Google, overriding modules has been identified as an anti-pattern.  It is an expedient way to solve a certain class of problems, but when applied at scale, has resulted in binding graphs that were _very_ difficult to reason about and maintain.  It hasn't been completely ruled out as a feature, but there are also pretty reasonable alternatives that have historically avoided the confusion and ambiguity that you can get from overrides: https://google.github.io/dagger/testing.html

**Comment by cesar1000** [comment]
Thanks for the pointer! I've been using a similar classification of providers when laying out my modules, and I find it's generally quite effective. In particular, I have separate graphs for production and test, and replace modules as needed.

I find the technique breaks down a bit when using graphs in a hierarchy of classes. If I were to add a new replaceable module to the graph of a base class, I would need to track down all derived components (for all subclasses), and add the module to all of them. In highly configurable hierarchies most objects can be replaced, which leads to an explosion of modules on each component. Managing components becomes really hard, since the distinction between components is not obvious by just looking at their definition. This is one case where declaring that you want to inherit all modules but replace a couple of bindings expresses intent in a clearer way.

While overrides can be confusing when abused, they do have some good qualities: they provide a dagger-friendly means of replacing bindings (and certainly less restrictive and more idiomatic than method override) and, as a side benefit, can be used to resolve a conflict when a single binding is provided by multiple included modules.

There's an additional motivation concerning how I design my graphs. Because modules are only additive, I need to break down my modules preemptively into mini-modules that can be overridden. This also invites thinking about your modules in terms of how they may be used in any potential component. The resulting modules are hard to reuse. Ideally, I would like to be able to design my modules in isolation and distribute providers into them based only on functional concerns.

**Comment by cesar1000** [comment]
Closing, since upon reflection I feel that there's no need for dagger to provide this feature, and an automatic generation of the dagger definitions from a higher level set of abstractions supporting overrides sounds like a perfectly viable option.

**Comment by donkeytronkilla** [comment]
> Closing, since upon reflection I feel that there's no need for dagger to provide this feature, and an automatic generation of the dagger definitions from a higher level set of abstractions supporting overrides sounds like a perfectly viable option.

Anything ever come of those higher level set of abstractions? 😀
