### ISSUE TITLE
Feature Request: component introspection based on a base class/interface

### ISSUE THREAD

**Issue by cesar1000** [google/dagger#526]
I'm working on setting up the graph architecture in my application (Twitter for Android), and I ran into the problem of cleaning up scoped bindings when a Dagger component is discarded.

Let's say that I inject a user database from a scoped Dagger component. Dagger takes care of creating an instance of my database when first requested, and injecting it to all clients of the dependency. No one client owns the database object itself, so the responsibility of closing it when discarding the component is not clearly assigned. Extracting from the component all references that require cleanup, however, poses several issues:

* Exposing all bindings that require cleanup through provision methods in the component is undesirable, since it forces me to publish bindings that should remain private. Also, it's error-prone, since it requires me to write the cleanup code to call each method explicitly.
* Getting an object for cleanup would create it if it was uninitialized.

I have addressed the first issue by providing objects that require cleanup to a multibound set, and putting a bunch of lint rules in place to detect omissions. This works, but it's clunky and verbose. I don't have a good solution for the second problem.

Taking a step back, it seems to me that this is a particular case of the larger problem of extracting objects from a component based on properties like base classes or implemented interfaces. Ideally, I would like to be able to declare such a multibinding as this:

```
@Multibindings
interface MyMultibindings {
    @NotNull
    @InstancesOf(type = Closeable.class, transitive = false, onlyIfInitialized = true)
    Set<Closeable> closeables();
}
```

I threw in a couple of flags that would make this feature more generally useful:

* transitive, for configuring whether the multibinding should include nesting scopes.
* onlyIfInitialized, to select all providers or only those in the initialized state.

Incidentally, this would be particularly useful if Dagger's scoped providers would expose the functionality to query and update their state, since that may be used to release providers on demand while doing the proper cleanup (which doesn't seem to be available in the Releasable References API).

Would this make sense in the overall design of Dagger? Do you have an alternative solution for this kind of problem?

**Comment by cesar1000** [comment]
Ah, also this may help address the issue described in #385.

**Comment by ronshapiro** [comment]
Firstly, we're working on an API to make it easier to your own additional static analysis on the graph. Hopefully that'll help to make sure people don't slip up (and that your checks are accurate).

We're discussing the idea of providing features for closing resources within Dagger. To help me understand: do you want to group bindings that you want closed all at once, or do you want this at the individual binding level?

There are definitely some manual ways of doing this:

```java
@Provides @ActivityScope @Task1
Closer provideCloser() { return new com.google.common.io.Closer(); }

@Provides @ActivityScope @Task2
Closer provideCloser() { return new com.google.common.io.Closer(); }

@Provides
Database provideDb(@Task1 Closer closer) {
  return closer.register(new Database());
}
```

Is that similar to what you were thinking about?

**Comment by gk5885** [comment]
This isn't the first time that something like this has been requested.  Though, this is a more general FR than most -- everybody seems to want `Closable` in particular.  I'm a little bit skeptical that this is something that we want to provide as a general feature, but the use case is certainly sound enough.

As @ronshapiro pointed out, you can certainly do this managing the resources externally, but I think you could also get this done at the individual type level with method injection:

```java
@Inject void registerCloser(Closer closer) {
  closer.register(this);
}
```

**Comment by ronshapiro** [comment]
Note that you almost definitely want to scope the Closer since you want to be able to get the same one across injection sites.

**Comment by gk5885** [comment]
Oh, also, people have had success with having objects with a startup/shutdown lifecycle implement something like Guava's [`com.google.common.util.concurrent.Service`](https://github.com/google/guava/wiki/ServiceExplained) and collecting them in a set mulitbinding.  Then you can just manage them explicitly.

**Comment by cesar1000** [comment]
Ah, good to hear about the API for static analysis. That will be easier than writing ad hoc Lint rules :)

Your proposal of using Closer does address the concerns about instantiating objects unnecessarily or publishing them outside of the graph. However, it doesn't remove the boilerplate (and it's error prone until the static analysis API is available!) and it's inflexible, since it's forcing me to encode the intended use of my objects in the graph, by collecting them in a closer or, for that matter, in a mutable set.

Using Guava's Service in a set multibinding is pretty much the same thing as I'm doing already: manually providing into a set objects that are already available in the graph. Your comment, however, does highlight another application of the sort of generic set multibindings I propose: extracting all instances of Service for generic manipulation. #385 expresses a similar need.

I used object release as an example of the more general problem of extracting scoped instances or scoped providers from the graph based on a property of the binding (like a base class or annotation). You can apply a similar technique for acquiring plugins, and even build a feature like the Releaseable References API without direct Dagger support.

Finally, I find it extremely powerful that Dagger may give me out-of-the-box a set of all objects within a scope that meet a certain condition. I could use that, for example, to guarantee statically that all my closeable objects are cleaned up when a scope is dismissed which, in turn, removes the potential for leaks altogether.

**Comment by facboy** [comment]
i think this is implicit in the above comments, but one problem with the current multibinding approach is that might instantiate previously uninstantiated (lazy) objects only to close them again.

**Comment by cesar1000** [comment]
Closing since, in hindsight, injecting `Closer` or similar event notifier explicitly does sound like a better option.
