### ISSUE TITLE
Compiler should include module name in error message for multiple methods with same name annotated with @Provides

### ISSUE THREAD

**Issue by burntcookie90** [google/dagger#530]
If you have a module with multiple methods of the same name annotated with `@Provides` the error message in 2.8 is as follows: `Cannot have more than one @Provides method with the same name in a single module`. This should also output the module name for easy locating of the error.

**Comment by ronshapiro** [comment]
@burntcookie90 I think you mentioned on slack that this was probably a kotlin issue that the compiler wasn't displaying the offending line? Feel free to reopen if that's not the case.
