### ISSUE TITLE
Quick Guava Question

### ISSUE THREAD

**Issue by naturalwarren** [google/dagger#537]
Hey team,

I noticed dagger was updated to guava 20-rc1. Why did we do this?

I compile my app against android built tools 25.1 which depends on guava 17 and pulling in the latest version of dagger breaks lint for me because guava classes can't be found. I'm not in a position where I can update lint at the moment so I've compiled dagger against guava 19 as a workaround.

Thoughts?

**Comment by JakeWharton** [comment]
File a bug on http://b.android.com? Version 17 is two and a half years out of date.

**Comment by naturalwarren** [comment]
Does anyone know if compiling against 19 is safe in my own fork? 
- Dagger tests all pass
- App tests all pass
- App works fine

Was there something particular gained by updating to 20-rc?
