### ISSUE TITLE
Snapshot publishing is broken on Travis

### ISSUE THREAD

**Issue by JakeWharton** [google/dagger#541]
[ERROR] Failed to execute goal on project dagger-android: Could not resolve dependencies for project com.google.dagger:dagger-android:aar:HEAD-SNAPSHOT: The following artifacts could not be resolved: com.android.support:support-compat:jar:24.2.0, com.android.support:support-compat_internal_impl-24.2.0.jar:jar:24.2.0, com.android.support:support-core-ui:jar:24.2.0, com.android.support:support-core-ui_internal_impl-24.2.0.jar:jar:24.2.0, com.android.support:support-fragment:jar:24.2.0, com.android.support:support-fragment_internal_impl-24.2.0.jar:jar:24.2.0, com.android.support:support-media-compat:jar:24.2.0, com.android.support:support-media-compat_internal_impl-24.2.0.jar:jar:24.2.0, com.android.support:support-core-utils:jar:24.2.0, com.android.support:support-core-utils_internal_impl-24.2.0.jar:jar:24.2.0, com.android.support:support-v4:jar:24.2.0: Could not find artifact com.android.support:support-compat:jar:24.2.0 at specified path /home/travis/build/google/dagger/android/target/unpacked-libs/cas_support-compat_24.2.0/classes.jar -> [Help 1]

**Comment by ronshapiro** [comment]
#691 is a similar issue, but with bazel. I should have a fix soon. Gonna continue on that bug.
