### ISSUE TITLE
Annotation  @Produces is not available anymore?

### ISSUE THREAD

**Issue by lovejjfg** [google/dagger#542]
When I forgot to add @Inject constructor I got this message:

>cannot be provided without an @Inject constructor or from an @Provides- or @Produces-annotated method.

I am confused the last `@Produces` is still available? or should update this message?

**Comment by JakeWharton** [comment]
`@Produces` is in the `dagger-producers` artifact which is optional.

**Comment by chenjunqi** [comment]
@JakeWharton  I want to use `android.databinding.ObservableField<T>` but i don't known which artifact to choose.
