### ISSUE TITLE
Generating a Provider for ... Prefer to run the dagger processor over that class instead.

### ISSUE THREAD

**Issue by MikeMitterer** [google/dagger#543]
My class looks like this: (JobsService is in an external jar)

 ```java
    @Inject
    public JobsService(final Provider<MobiAdAuth> mobiAdAuthProvider,
                       @JobsUrl final URIBuilder uriBuilderForJobs) {
```

My module:
```java
    @Provides
    @Singleton
    MobiAdAuth provideMobiAdAuth() {
        return new MobiAdAuthBuilder().build();
    }

    @Provides
    @JobsUrl
    URIBuilder provideJobsUrl(final ServiceFile4WebApp serviceFile) {
        return forServer(serviceFile).path("/api/v1/jobs");
    }
```

Dagger gives me:
`Note: Generating a Provider for at.mikemitterer.mobiad.library.services.JobsService. Prefer to run the dagger processor over that class instead.`

An now??? It's not clear why Dagger gives me this "note" - Isn't that Dagger purpose to generate such things for me?

**Comment by tbroyer** [comment]
Thé message says that the processor should run  "over that class", i.e. while compiling it (technically, JavaC also allows processing already-compiled classes, but few build tools let you do that, at least easily).

This means you should ideally run Dagger when building that other JAR. Then when building the project Dagger will find the provider class it had generated (and is packaged in the JAR alongside the `JobsService` class) and won't have to generate it, thus won't emit that message.

**Comment by MikeMitterer** [comment]
Thanks! Ideally one could turn off this message. My other JAR is based on Guice and I stay with Guice on the Desktop-side. So generating the Dagger classes for this JAR is not an option. It's a bit annoying to see these "Notes" every time I compile the Android part.

**Comment by ronshapiro** [comment]
This was turned off by default in 72aa9653252c348e07f79030c49ce921a72ea9e1
