### ISSUE TITLE
Provide an example with subcomponents

### ISSUE THREAD

**Issue by caipivara** [google/dagger#546]
Will be cool to have it

**Comment by gk5885** [comment]
Absolutely.

**Comment by naturalwarren** [comment]
I could help with this if someone want to help review.

cc @ronshapiro

**Comment by Kilnn** [comment]
How to use  Subcomponent and Module(subcomponents = ***) ? I need an example too.

**Comment by ronshapiro** [comment]
https://google.github.io/dagger/subcomponents should have all of this

**Comment by bnvinay92** [comment]
Removing the `subcomponents` attribute from the `@Module` annotation does not break anything. I can still declare Subcomponent builders in my parent component. What is the usecase of this attribute?
