### ISSUE TITLE
Inherit scope annotations through interface inheritence

### ISSUE THREAD

**Issue by pyricau** [google/dagger#554]
Today, when we reuse code that requires scoping in distinct components, we do something like this:

```java
@CoffeePumpThing.SharedScope
public class CoffeePumpThing {
  @Scope public @interface SharedScope {
  }
}

public CoffeePumpView {

  public interface Injector {
    void inject(CoffeePumpView view);
  }

  @Inject CoffeePumpThing thing;

  public void injectAllTheThings() {
    Injector injector = ...
    injector.inject(this);
  }
}

@CoffeePumpThing.SharedScope
@Component
public interface KitchenComponent extends CoffeePumpView.Injector {
}
```

It's super common in our Android apps to associate a specific injector interface & scope to a component, for views + presenters that are reused throughout the app. 

It's also common to add one without the other by mistake.

Suggestion: inherit scoping annotations from parent interfaces.

So here, the example becomes:

```java
@CoffeePumpThing.SharedScope
public class CoffeePumpThing {
  @Scope public @interface SharedScope {
  }
}

public CoffeePumpView {

  // vvvvv We added the scoping annotation here vvvvv
  @CoffeePumpThing.SharedScope
  public interface Injector {
    void inject(CoffeePumpView view);
  }

  @Inject CoffeePumpThing thing;

  public void injectAllTheThings() {
    Injector injector = ...
    injector.inject(this);
  }
}

// vvvvv No more scoping annotation here vvvvv
@Component
public interface KitchenComponent extends CoffeePumpView.Injector {
}
```

Thoughts?

**Comment by ronshapiro** [comment]
Do we not honor [`@Inherited`](https://docs.oracle.com/javase/7/docs/api/java/lang/annotation/Inherited.html)

**Comment by ronshapiro** [comment]
Update: we don't.

Here's where we get scopes: https://github.com/google/dagger/blob/bb2d3a9f142f91156cfa39d5d5894ade0e146c4c/compiler/src/main/java/dagger/internal/codegen/InjectionAnnotations.java#L61

Which delegates here: 
https://github.com/google/auto/blob/86068645b5ddf624640c30272d9a3cf92938f967/common/src/main/java/com/google/auto/common/AnnotationMirrors.java#L139

I'm surprised that Java gives two different APIs, `getAnnotationMirrors` and `getAllAnnotationMirrors` for seemingly the same idea. Annotation processor writers shouldn't have to think about whether they want to honor `@Inherited`.

@eamonnmcmanus @gk5885 @netdpb do you think we should have APIs in auto-common to make this easier?

**Comment by Chang-Eric** [comment]
I think `@Inherited` would only be for annotations, so wouldn't apply to this case? With that said, in general, I think we're unlikely to make this change since I think it has the potential to make things more confusing overall with it being difficult to easily see what scopes a component supports. I think this could get especially bad with kind of cascading mistakes, where say someone incorrectly marks their interface with a scope annotation, it wouldn't be an error immediately and may silently suppress future errors with bindings using the wrong scope (since they are now supported in the component).
