### ISSUE TITLE
Subcomponents documentation: non-Module setter in Builder?

### ISSUE THREAD

**Issue by edudobay** [google/dagger#559]
There's a snippet from the [Subcomponents](https://google.github.io/dagger/subcomponents.html) ([source](https://github.com/google/dagger/blame/gh-pages/subcomponents.md)) documentation page in which a Subcomponent.Builder seemingly has a non-@Module setter (the one for `data`):

```java
@Singleton
class RequestRouter {
  @Inject RequestRouter(
      Provider<RequestComponent.Builder> requestComponentProvider) {}

  void dataReceived(Data data) {
    RequestComponent requestComponent =
        requestComponentProvider.get()
            .data(data)
            .build();
    requestComponent.requestHandler()
        .writeResponse(200, "hello, world");
  }
}
```

I wondered if I'm missing something or if this was a documentation mistake and it should have been a Module in place of this `Data` class. If it was not a mistake, my next question would be “what does Dagger do with this `data` object”.

I've set up a minimal example [in a repo](https://github.com/edudobay/dagger-subcomponent-failing-example). It does not compile:

```
(...)/src/main/java/RequestComponent.java:9: error: @Subcomponent.Builder has setters 
for modules or subcomponents that aren't required:
[RequestComponent.Builder RequestComponent.Builder.data(Data)]
  interface Builder {
  ^
```

**Comment by naturalwarren** [comment]
Seems that should either be removed or the Subcomponent Builder should have a `@BindsInstance` annotated method named data.

**Comment by bmeike** [comment]
The documentation discussed in this issue still appears to be wrong.  The subcomponent builder still needs a `@BindsInstance` annotated method, for `data` or the code won't compile.

**Comment by roded** [comment]
Even after adding the `@BindsInstance` annotated method for `data` and attempting in inject it into `RequestHandler`'s constructor, dagger reports the following:
`error: [Dagger/MissingBinding] my.package.Data cannot be provided without an @Inject constructor or an @Provides-annotated method.`

Is this an issue or am I doing something incorrectly?
