### ISSUE TITLE
Document which version introduces a given feature in the user's guide

### ISSUE THREAD

**Issue by GaryHendrick** [google/dagger#561]
I note that the user guide is ahead of the current highest release, 2.8, at https://mvnrepository.com/artifact/com.google.dagger/dagger

Perhaps documentation should be marked out to indicate features which aren't available outside of the github repo.  Looks like a great feature, can't wait to use it

**Comment by gk5885** [comment]
Yeah, for better or worse, our docs are just always at head.  I don't think we want to start doing versioned docs, but noting which version introduces a feature is certainly a good idea.

**Comment by ronshapiro** [comment]
Because we release very frequently, and encourage people to always upgrade, I don't know if there's much to do here. Our Javadocs do also list when a feature is added.
