### ISSUE TITLE
Please consider adding Dagger 2 library to AppBrain for usage statistics

### ISSUE THREAD

**Issue by drawers** [google/dagger#565]
AppBrain is a tool that allows you to see the usage statistics (percent installs/percent apps) of a given development library. There is recently a [StackOverflow question][1] about whether Dagger 2 is actually used in any "production ready" apps. Clearly it is, but it would be useful to get statistics. I imagine it would help your own team too :) Unfortunately, it doesn't really seem appropriate for someone outside your team to add it without your permission. 

The link is below:
http://www.appbrain.com/stats/libraries/suggest?tag=android_utility

[1]:https://stackoverflow.com/questions/41895802/beside-testing-why-do-we-need-dagger-2

**Comment by JakeWharton** [comment]
http://www.appbrain.com/stats/libraries/details/dagger/dagger. Since Dagger 2 uses the same package name it's already picked up.

**Comment by drawers** [comment]
Thanks I'll close the issue
