### ISSUE TITLE
Injection to generic base class whose generic param is generated by Android's data binding fails

### ISSUE THREAD

**Issue by fullkomnun** [google/dagger#572]
I encountered an issue when using an abstract generic base class 
with a single type parameter that is bound to extend ViewDataBinding.
When extending this base class and defining the concrete generated 
data binding class and trying to inject into the subclass
(when the base class has any kind of injections) dagger fails to generate the MembersInjector 
for the base class since it cannot find the symbol for the generated data binding class.
build config: dagger 2.8, android-gradle-plugin 2.2.3, gradle 3.2.1, build-tools 25.0.2.
Also tried to use the latest android-gradle-plugin(2.3.0-beta2) and gradle(3.3).
Tried to use android gradle plugin's annotation processing support 
available since version 2.2.0 and the good old android-apt plugin.

```java
public abstract class BindableBaseController<B extends ViewDataBinding> extends BaseController {
  @Inject void setupLeakCanary(LeakCanaryProxy leakCanaryProxy) {
    addLifecycleListener(new LeakCanaryControllerLifecycleListener(leakCanaryProxy));
  }
  ...
}

public final class LoginController extends BindableBaseController<LoginControllerBinding> {
  @Override protected void injectDependencies() {
    ComponentFinder.<LoginActivityComponent>findActivityComponent(getActivity()).plus(
        new LoginControllerModule()).inject(this);
  }
  ...
}
```
the error:
"Note: Generating a MembersInjector for ***.login.LoginController. Prefer to run the dagger processor over that class instead.
Error:(23, 46) error: cannot find symbol class LoginControllerBinding
where B is a type-variable:
B extends ViewDataBinding declared in class BindableBaseController_MembersInjector"

the generated members injector:
```java
@Generated(
  value = "dagger.internal.codegen.ComponentProcessor",
  comments = "https://google.github.io/dagger"
)
public final class BindableBaseController_MembersInjector<B extends ViewDataBinding>
    implements MembersInjector<BindableBaseController<LoginControllerBinding>> {
  private final Provider<LeakCanaryProxy> leakCanaryProxyProvider;

  public BindableBaseController_MembersInjector(Provider<LeakCanaryProxy> leakCanaryProxyProvider) {
    assert leakCanaryProxyProvider != null;
    this.leakCanaryProxyProvider = leakCanaryProxyProvider;
  }

  public static <B extends ViewDataBinding>
      MembersInjector<BindableBaseController<LoginControllerBinding>> create(
          Provider<LeakCanaryProxy> leakCanaryProxyProvider) {
    return new BindableBaseController_MembersInjector<B>(leakCanaryProxyProvider);
  }

  @Override
  public void injectMembers(BindableBaseController<LoginControllerBinding> instance) {
    if (instance == null) {
      throw new NullPointerException("Cannot inject members into a null reference");
    }
    ((BaseController) instance).setupLeakCanary(leakCanaryProxyProvider.get());
  }
}
```

Is there any way to make sure the generated data binding class is generated and available to use by dagger's generated code?

**Comment by restor1** [comment]
Can anyone please take a look at this issue?

**Comment by ronshapiro** [comment]
It's hard to tell without looking at the rest of the javac output, but usually people that get databinding errors have either (1) issues with the data-binding code or (2) issues with the other parts of their dagger code, and an error for one causes errors in the other.
