### ISSUE TITLE
Generated component not implementing parent interface inject() method

### ISSUE THREAD

**Issue by riclage** [google/dagger#573]
I have a setup as follows. On my parent Android module (i.e., a library), I have:
```
public interface ParentActivityComponent {

    void inject(ParentActivity parentActivity);
}
```
Then, on the application module:

```
@PerActivity @Subcomponent(modules = ActivityModule.class)
public interface MainActivityComponent
    extends ParentActivityComponent {
}
```

When I do the above, the project build fails to build with gradle complaining with the following errors for a bunch of unrelated activities and fragments where I use data binding and inject dependencies:
 * Error:(9, 75) error: cannot find symbol class Activity...Binding
 * Error:cannot access Activity...Binding
 * Error:(18, 8) error: dagger.internal.codegen.ComponentProcessor was unable to process this class because not all of its dependencies could be resolved. Check for compilation errors or a circular dependency with generated code.

If, however, I add the method `void inject(ParentActivity parentActivity);` **also** to `MainActivityComponent` (still **keeping** it on `ParentActivityComponent` so that the `ParentActivity` can still call `inject()`), then the project builds successfully and everything works.

I'm not sure what's wrong. I tried cleaning the cache, building all, and moving components around. The setup above **also works** if both components are in the **same** Android application module.

**Comment by naturalwarren** [comment]
What component is your subcomponent installed into? I see absolutely nothing wrong with what you've written. In my codebase I have classes annotated `@Subcomponent` extending ParentComponents all over the place.

**Comment by riclage** [comment]
Thanks. I have a `ParentAppComponent` on my parent library module as follows:

```
public interface ParentAppComponent {

    ParentActivityComponent plus(ActivityModule activityModule);

}
```

Then on the application module:

```
@Singleton @Component(modules = {
    //my app modules
}) public interface MainAppComponent extends ParentAppComponent {

    void inject(App app);
}
```

**Comment by ronshapiro** [comment]
Looks like you need to have `MainAppComponent` override the `plus` method to return `MainActivityComponent`. Otherwise Dagger doesn't know which one you want.
