### ISSUE TITLE
about com.neenbedankt.android-apt

### ISSUE THREAD

**Issue by softboy99** [google/dagger#576]
Hi,
for the latest android studio 2.3 beta3, if we want to use dagger2, do we still need plugin:"com.neenbedankt.android-apt"? or just "compile 'com.google.dagger:dagger:2.x'
  annotationProcessor 'com.google.dagger:dagger-compiler:2.x'"?

**Comment by JakeWharton** [comment]
The version of Android Studio is of no consequence. If you are using
version 2.2 of the Android Gradle plugin (or newer) then you can use
annotationProcessor and do not need the apt plugin.

**Comment by Taranmeet** [comment]
I am trying to use 2.14.1 on Android Studio 3.0.1 and keep getting compile time error Could not resolve com.squareup:javapoet:1.8.0
My app.gradle has following dependencies
```
    implementation 'com.google.dagger:dagger:2.14.1'
    annotationProcessor 'com.google.dagger:dagger-compiler:2.14.1'

    implementation 'com.google.dagger:dagger-android:2.14.1'
    implementation 'com.google.dagger:dagger-android-support:2.14.1'
    annotationProcessor 'com.google.dagger:dagger-android-processor:2.14.1'
```
