### ISSUE TITLE
Inner-Class Component Generated Code Naming

### ISSUE THREAD

**Issue by JakeWharton** [google/dagger#58]
```java
public class Foo {
  @Component
  public class Bar {}
}
```
produces `Dagger_Foo$Bar`. AutoValue produces names in the form `Dagger_Foo_Bar` which seems much more desirable.

**Comment by Ch3D** [comment]
+1
This issue stops me from migration to Kotlin

**Comment by Lakedaemon** [comment]
+1
I'm a kotlin developer. This issues stops me from migrating to dagger. :)

**Comment by artem-zinnatullin** [comment]
I am using Dagger 2 with Kotlin without any problems:

Components and Modules in Java, injecting like this (Android):

```java
public class App extends Application {

    private DIGraph mDIGraph;

    /**
     * Returns application object from context
     * @param context to get application object
     * @return application object
     */
    public static App get(Context context) {
        return (App) context.getApplicationContext();
    }

    @Override public void onCreate() {
        super.onCreate();

        mDIGraph = Dagger_DIGraph.builder()
                // creating modules
                .build();
    }

    @NonNull public DIGraph getDIGraph() {
        return mDIGraph;
    }
}
```

```kotlin
class SomeFragment : Fragment {

    var someVar: SomeType? = null
        [Inject] set
    
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        App.get(getActivity()).getDIGraph().inject(this)

        // we can work with injected someVar
    }
}
```

**Comment by mboudraa** [comment]
+1

**Comment by asm0dey** [comment]
:+1:

**Comment by steindekker** [comment]
+1

**Comment by leomindez** [comment]
+1

**Comment by cgruber** [comment]
Dagger does Dagger_OuterClass_Foo for components.  It will ultimately reject $$ for generated types, but this may not happen in time for 2.0.  I'm marking this as a 2.1 issue.

**Comment by cgruber** [comment]
Fixed in #150

**Comment by thomasbiddle** [comment]
@cgruber When will this be available in the Maven repository? Or is there another way to include this

**Comment by thomasbiddle** [comment]
@cgruber Also - quick clarification. This will also fix the issue regarding the prefixes having changed from the 2.0-SNAPSHOT? They used to be Dagger_xxxx And now it's just Daggerxxxx from what I'm hearing

**Comment by cgruber** [comment]
Dagger 2.0 has been released, and the names are, for @Component Foo you get
DaggerFoo, and for @Component Bar.Blah (nested) you get DaggerBar_Blah as
the implementation types for components.
