### ISSUE TITLE
Dagger2 build with jack & jill, Some wrong!

### ISSUE THREAD

**Issue by YuriZheng** [google/dagger#580]
Hi:
    I use the dagger2 in my project.
User.java
`    public class User {
 
    private String name;
 
    @Inject
    public User() {
 
    }
 
    public String getName() {
        return name;
    }
 
    public void setName(String name) {
        this.name = name;
    }
}`

MyComponent.java
`@Component(modules = MyModule.class)
 public interface MyComponent {
 
    void injectMain(MainActivity activity);
 
}`

    MyModule.java
`@Module
public class MyModule {
 
    @Provides
    User provideUser() {
        return new User();
    }
 
}`

MainActivity.java
    `public class MainActivity extends AppCompatActivity {
 
    @Inject
    User mUser;
 
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
 
        DaggerMyComponent.builder()
                .myModule(new MyModule())
                .build()
                .injectMain(this);
 
        mUser.setName("1212121212");
 
        System.out.println("NNN: " + mUser.getName());
    }
}`

## And then very strange question came, I run the first time, print the information printed correctly, and then I just add a space in the code casually, run again on the wrong:

![image](https://cloud.githubusercontent.com/assets/7332122/22967841/07302e8e-f3a3-11e6-89ad-e3a948d380c3.png)

   I suspect that the compiler is the problem, I use the jack & jill compiler + JAVA8, the following is my gradle file
project gradle file:
`buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.2.3'
        classpath 'com.google.guava:guava:20.0'
 
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}
 
allprojects {
    repositories {
        jcenter()
    }
}
 
task clean(type: Delete) {
    delete rootProject.buildDir
}`

module gradle file:
`apply plugin: 'com.android.application'
 
android {
    compileSdkVersion 25
    buildToolsVersion "25.0.0"
 
    defaultConfig {
        applicationId "xxxxxx.daggerdemo"
        minSdkVersion 21
        targetSdkVersion 25
        versionCode 1
        versionName "1.0"
 
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
 
        jackOptions {
            enabled true
        }
 
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
 
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
 
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:appcompat-v7:25.0.1'
    testCompile 'junit:junit:4.12'
 
    // Dagger
    annotationProcessor 'com.google.dagger:dagger-compiler:2.8'
    provided 'org.glassfish:javax.annotation:10.0-b28'
    compile 'com.google.dagger:dagger:2.8'
}`

    Reported that the class can not find the wrong, but in the build folder I can find these class below

![image](https://cloud.githubusercontent.com/assets/7332122/22967902/4da51c94-f3a3-11e6-9de8-8bb37283226c.png)

    This question plagued for a few days, ask for help, thank very much!

**Comment by naturalwarren** [comment]
I've never run Dagger with Jack and don't know much about it but this caught my eye:

"Jack does not generate intermediate class files when compiling an app, tools that depend on these files do not currently work with Jack."

Does compiling only fail the first time?

**Comment by ronshapiro** [comment]
Does it work if you turn jack off?

Do you need jack for your build?

**Comment by YuriZheng** [comment]
Turn jack off？ I have not tried it yet.
The most strange thing is the first run was successful, and then I just add a space in the code casually, run again on the wrong.
Compiling is only successful for the first time!
I can find the classes automatic generated in my build folder. 
So i very puzzled.

**Comment by YuriZheng** [comment]
@ronshapiro 
Is there no solution?

**Comment by ronshapiro** [comment]
Jack has a number of issues and inconsistencies with javac. We don't have a good way of testing it, so we only test against plain javac. Unless you have a need for jack, I recommend disabling it

**Comment by YuriZheng** [comment]
All right

**Comment by YuriZheng** [comment]
@ronshapiro 
I changed apt compiled and compiled successfully !
But I still hope that you can adapt to the jack & jill compiler .
Tks!!!
