### ISSUE TITLE
API Improvement: Remove Component Builder.create() when @BindsInstance Used

### ISSUE THREAD

**Issue by naturalwarren** [google/dagger#584]
I'd be interested in submitting a PR for this if it's deemed a good idea:

At the moment `create()` is generated when a `Component.Builder` is defined and uses `@BindsInstance`. Calling `create()` results in an `IllegalStateException`. Let's just omit create altogether in this scenario?

**Comment by ronshapiro** [comment]
This is definitely a bug, I'd be happy to review a PR for this. Thanks!

**Comment by naturalwarren** [comment]
Awesome, will have something for you by the end of the week.

**Comment by ronshapiro** [comment]
This was fixed in d4f1015
