### ISSUE TITLE
Suspicious "Scoped provider was invoked recursively returning different results"

### ISSUE THREAD

**Issue by fablue** [google/dagger#585]
Hello, 
i am getting very suspicious Exception thrown in the PlayStore's Pre-Launch test. I cannot reproduce this on any real device or emulator at home and there is nor recursion as far is i understood the whole code. 
I posted with some code examples on StackOverflow for additional information:
[http://stackoverflow.com/questions/42328759/dagger-scoped-provider-was-invoked-recursively-returning-different-results](url)
I cant explain why this is happening and i am very desperate at the moment. 
Thanks for any suggestion :)

Used Dagger 2.5 and Dagger 2.9

**Comment by ronshapiro** [comment]
You probably have a dependency cycle with a `Provider<>` or `Lazy<>` which gets called recursively. Have you looked for any cycles in your code?
