### ISSUE TITLE
`dagger-android` 2.10-rc1 aar is missing AndroidManifest.xml

### ISSUE THREAD

**Issue by jupitervn** [google/dagger#589]
The aar package for `dagger-android` module is missing AndroidManifest.xml that will generate the following error 
```
Error:Execution failed for task ':app:processDebugManifest'.
> com.android.manifmerger.ManifestMerger2$MergeFailureException: java.io.FileNotFoundException: /.../app/build/intermediates/exploded-aar/com.google.dagger/dagger-android/2.10-rc1/AndroidManifest.xml (No such file or directory)
```

Current fix now is manually adding `AndroidManifest.xml` from this repo to 'build/intermediates/exploded-aar/` path but this file will be deleted if a clean build is performed.

**Comment by OleksandrKucherenko** [comment]
+1, can be resolved by setting in gradle dependency to 2.9

**Comment by ronshapiro** [comment]
Thanks for pointing this out. I'll make another release candidate shortly.

**Comment by ronshapiro** [comment]
I submitted a fix and it should be in rc2. Thanks for the report!

**Comment by abs-paradigm** [comment]
@ronshapiro Hi, I have the same problem with another lib, can you share what was the fix?

**Comment by ronshapiro** [comment]
This was an issue with our bazel-deploy system - I imagine it's not the same issue. We were shipping a jar when really we meant to be shipping an aar
