### ISSUE TITLE
Spurious reference to DaggerApplication in documentation

### ISSUE THREAD

**Issue by bubenheimer** [google/dagger#592]
The Dagger Android documentation at [https://google.github.io/dagger/android.html] references a DaggerApplication class. That class does not exist (or is it a reference to a future addition?)

**Comment by liminal** [comment]
The current documentation unfortunately includes stuff that's been said to arrive in the next release

**Comment by ronshapiro** [comment]
Ah, sorry about that. We're just working through a kink, I expect it out soon.

**Comment by maomaobug** [comment]
I read the doc today and feel exciting to have these new features, until I find it can not be integrated to my newly created project now, even I had the following lines in my `build.gradle` file.

> `compile 'com.google.dagger:dagger-android:2.9'`

Can't wait to use it!

**Comment by JohNan** [comment]
Still can't find `DaggerApplication` and the `create` method `Dagger<YourApp>Component.create()` seems not to be generated either.

**Comment by ronshapiro** [comment]
This was added in 5b28029b509dde5f4fd88247b6464a990bf0ebce and will be in the next release. Sorry for the confusion!
