### ISSUE TITLE
Obscure error message when one Module extends another one and the visibility of the provide method does not match the with target injection

### ISSUE THREAD

**Issue by vanniktech** [google/dagger#596]
Given I have a Module `A` in my root package which provides an Integer, injecting this Integer within the same package works perfectly. The moment I create a new Module `B` in a subpackage and pull the provides method into Module `B` with a package private modifier and let Module `A` extend from `B` I get this obscure error message:

```
void inject(SomeActivity someActivity);
   ^
  java.lang.Integer is injected at
      com.vanniktech.daggerplayground.SomeActivity.integer
  com.vanniktech.daggerplayground.SomeActivity is injected at
      com.vanniktech.daggerplayground.ApplicationComponent.inject(someActivity)
```

The fix is to go and add the `public` modifier to the provides method of Module `B`.

In my opinion the error message should be more detailed and explain that the visibility of the provides method in Module `B` should be promoted.

A super small sample of this error can be found [here](https://github.com/vanniktech/dagger-playground/pull/1).

If I put the public modifier on the method in Module `B`, I've noticed though that IntelliJ suggests me to lower the visiblity as the only usage of this method is in the `B_ProvideIntegerFactory` class which is public and in the same class. Is it possible that package private might actually be enough for dagger and there's a bug in the error message generating part of Dagger?

**Comment by naturalwarren** [comment]
Why are you extending modules? I can't think of a good use case for doing so.

**Comment by vanniktech** [comment]
I've got an abstract ActivityModule where I provide things that I need in every activity.

**Comment by tbroyer** [comment]
You should probably use `@Module(includes=)` rather than `extends`.

**Comment by ronshapiro** [comment]
@gk5885 @eamonnmcmanus do you know why this might be? Is an inaccessible member not returned from `elements.getAllMembers()`?

**Comment by ronshapiro** [comment]
Ah, yes, that's what the JLS states:

> Only members of a class that are declared protected or public are inherited by subclasses declared in a package other than the one in which the class is declared.

https://docs.oracle.com/javase/specs/jls/se7/html/jls-8.html#jls-8.2
