### ISSUE TITLE
Make class implementations of Subcomponents static if they do not reference the parent component

### ISSUE THREAD

**Issue by vanniktech** [google/dagger#601]
Having an `ImprintActivityComponent` which is a subcomponent of `ApplicationComponent` which does not reference anything from the parent yields to the following generated implementation that could be made static:

```java
private final class ImprintActivityComponentImpl implements ImprintActivityComponent {
 private Provider<ActionBarHelper> provideActionBarHelperProvider;

 private MembersInjector<ImprintActivity> imprintActivityMembersInjector;

 private ImprintActivityComponentImpl(ImprintActivityComponentBuilder builder) {
   assert builder != null;
   initialize(builder);
 }

 @SuppressWarnings("unchecked")
 private void initialize(final ImprintActivityComponentBuilder builder) {

   this.provideActionBarHelperProvider =
       DoubleCheck.provider(
           ActivityModule_ProvideActionBarHelperFactory.create(builder.imprintActivityModule));

   this.imprintActivityMembersInjector =
       ImprintActivity_MembersInjector.create(provideActionBarHelperProvider);
 }

 @Override
 public void injectMembers(ImprintActivity arg0) {
   imprintActivityMembersInjector.injectMembers(arg0);
 }
}
```

**Comment by tasomaniac** [comment]
If you don't depend on anything from your `ApplicationComponent`, why are you using `Subcomponent`. You can just use `@Component` annotation on your `ImprintActivityComponent` interface and your concern will be automatically resolved.

**Comment by vanniktech** [comment]
True. I have one subcomponent per Activity though throughout my app and I'd like to be consistent. Plus this way it's easier for me to change things and inject something from the parent if I ever need too. Plus the cost of making those classes static should not be much.

**Comment by ronshapiro** [comment]
@Subcomponents don't know their parent component, and may sometimes be used in a context where they use the parent's bindings and other times not. I think this is reasonable, just not a super high priority.

**Comment by vanniktech** [comment]
Gentle bump. Is there any timeline for this?

**Comment by ronshapiro** [comment]
We're exploring this, but it's significantly more complicated than it probably seems. It's a very large project that we're scoping out

**Comment by ronshapiro** [comment]
I'm going to claim this as infeasible. I don't think the work required to make it happen is justified for such a small benefit.
