### ISSUE TITLE
Android processor NCDFE fails when android-support artifact not used.

### ISSUE THREAD

**Issue by JakeWharton** [google/dagger#608]
```
java.lang.NoClassDefFoundError: dagger/android/support/FragmentKey
        at dagger.android.processor.AndroidMapKeyValidator.<clinit>(AndroidMapKeyValidator.java:56)
        at dagger.android.processor.AndroidProcessor.initSteps(AndroidProcessor.java:33)
        at com.google.auto.common.BasicAnnotationProcessor.init(BasicAnnotationProcessor.java:119)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment$ProcessorState.<init>(JavacProcessingEnvironment.java:539)
```
I assume this is because the processor explicitly depends on the jar of the aar. As such the deployed pom does have a dependency on `com.google.dagger:android-support` but that dependency is on the jar (not that an aar dependency would even work...). When your favorite build system resolves this artifact it sees the dependency but when it looks up the pom it sees that it has a `<type>` of aar and not jar and so it silently fails (at least with Gradle).

Not sure how you want to fix this. As far as I can guess the best way is to figure out how to get Bazel to let you build the two 'android' artifacts as Android libraries but package and deploy only the resulting jar and not a full aar. They contain no resources and the manifests are empty so there's no point in them being an aar anyway.

This is what Butter Knife does with its artifact that needs to link against Android but also be a dependency of the processor.

**Comment by ronshapiro** [comment]
Bazel has a implicit jar output for all `android_library`s so that shouldn't be an issue. I guess the question is if we ever have plans to add resources/manifest items. We should think through it @gk5885.

It's annoying that Gradle doesn't know how to handle this. I wonder if we should file a bug there?

I thought I had this case handled (but maybe that's on an unsubmitted change), but there are a bunch of solutions here, one of them is doing a `Class.forName` too and checking if it exists.

**Comment by ronshapiro** [comment]
Wait, and this works for when `dagger-android` is being compiled because there is support for that? Presumably it would also fail (if it were possible to trigger) if that was missing too?

**Comment by JakeWharton** [comment]
Yeah unfortunately `BasicAnnotationProcessor` was designed under the assumption that you'd always be able to access the annotation `Class` instead of, say, just the FQCN. If you assume the annotation will never be on the same classpath and use the FQCN and `AnnotationMirror`s only then it could be doable.

**Comment by ronshapiro** [comment]
Another option is to publish the jar with a classifier? That way the default usage is to pick up aar and then things like the processor can specify the classifier to get the jar?
