### ISSUE TITLE
Artifacts built without variable debug info?

### ISSUE THREAD

**Issue by bubenheimer** [google/dagger#611]
It looks like at least some of the artifacts of Dagger 2.10RC2 are built without debug info for variables. When I did some debugging today I had no variable information available when debugging into some of the Android-related Dagger artifact classes.

**Comment by ronshapiro** [comment]
Can you give an example? 

```sh
wget https://oss.sonatype.org/content/repositories/public/com/google/dagger/dagger-android/2.10-rc2/dagger-android-2.10-rc2.aar
unzip dagger-android-2.10-rc2.aar
javap -v -c -cp classes.jar dagger.android.DaggerActivity
```

Gives me this output: https://gist.github.com/ronshapiro/ca611bb4bb710c785f5f1a43a83508cc

Here's a Fieldref that looks to be as intended: https://gist.github.com/ronshapiro/ca611bb4bb710c785f5f1a43a83508cc#file-daggeractivity-javap-L13

**Comment by bubenheimer** [comment]
Is the intention to enable debugging into the Dagger artifacts with local variable information available? This needs the appropriate `-g` option to `javac` - https://docs.oracle.com/javase/8/docs/technotes/tools/windows/javac.html

Right now I don't see local variables/parameters when debugging in Android Studio. For example, in `DaggerActivity.onCreate(Bundle savedInstanceState)` I don't see the value of `savedInstanceState`. Same with `Preconditions.checkNotNull(T reference, String errorMessage)`.

**Comment by hameno** [comment]
I second this, I just tried to debug the AndroidInjection class and could not get any parameter or variable values in the debugger.

**Comment by ronshapiro** [comment]
Don't IDEs typically pick up the `-src.jar` for this reason instead of compiling the variable names into the jar?

**Comment by ronshapiro** [comment]
Our maven build seems to have included this. I see:

```
    LocalVariableTable:
      Start  Length  Slot  Name   Signature
         43      58     3 currentInstance   Ljava/lang/Object;
          0     115     0  this   Ldagger/internal/DoubleCheck;
          5     110     1 result   Ljava/lang/Object;
```

when running `javap` on `dagger.internal.DoubleCheck`.

I'm still curious about the source jar though, I thought IDEs typically used that.

**Comment by bubenheimer** [comment]
Maybe Android Studio does not, or it's a bug. I got the impression that IntelliJ IDEA may have an option to debug without variable names in the jar, but I don't see that option in AS. It did pick up the source, I can see all the right variable names.
