### ISSUE TITLE
Use Dagger2 with compact3 profile

### ISSUE THREAD

**Issue by rishabhtulsian** [google/dagger#620]
I decided to use Dagger2 for a system with a small footprint Java SE with the [compact3](https://blogs.oracle.com/jtc/entry/a_first_look_at_compact) profile, because functionalities like 'reflection' were not available. I am not able to compile my jar successfully.

I can see that the code is generated but since the generated classes are marked with the `javax.annotation.Generated` the build fails with this error 

> Generated is not available in profile 'compact3'

Can I somehow disable the annotation of the classes with the `Generated` annotation?

**Comment by ronshapiro** [comment]
Can you include a dependency on compile 'org.glassfish:javax.annotation:10.0-b28'?

It's a source-level annotation, so it shouldn't have any impact on runtime size.

**Comment by rishabhtulsian** [comment]
I tried that, it still didn't fix the error.

**Comment by ronshapiro** [comment]
This line should be taking care of not emitting `@Generated`: https://github.com/google/dagger/blob/af3195cf96e003293985fd25ca907688d5e2f87b/compiler/src/main/java/dagger/internal/codegen/SourceFileGenerator.java#L54

What version of the compiler are you using?

**Comment by rishabhtulsian** [comment]
I am using java 1.8 but the build uses the [compact3](https://blogs.oracle.com/jtc/entry/a_first_look_at_compact) profile which uses a subset of classes.

**Comment by ronshapiro** [comment]
Can you provide a sample project that exhibits this?

**Comment by ronshapiro** [comment]
I'm going to close this. You should always build with a full JDK. There are other issues about how we'll deal with `@Generated` in Java 9, we can continue the conversation there.
