### ISSUE TITLE
API Improvement: Component.Builder.build()

### ISSUE THREAD

**Issue by naturalwarren** [google/dagger#624]
I'd be interested in submitting a PR for this if it's deemed a good idea:

In the generated builder shown below you can call `build()` even if you haven't provided an instance of `mainActivityModule`. This causes an `IllegalStateException` to be thrown at Runtime. We could prevent this at compile time by not allowing `build()` to be called until `mainActivityModule()` is called.

```
  public static final class Builder {
    private MainActivity.MainActivityModule mainActivityModule;

    private Builder() {}

    public MainActivity.MainActivityComponent build() {
      if (mainActivityModule == null) {
        throw new IllegalStateException(
            MainActivity.MainActivityModule.class.getCanonicalName() + " must be set");
      }
      return new DaggerMainActivity_MainActivityComponent(this);
    }

    public Builder mainActivityModule(MainActivity.MainActivityModule mainActivityModule) {
      this.mainActivityModule = Preconditions.checkNotNull(mainActivityModule);
      return this;
    }
  }
```

**Comment by ronshapiro** [comment]
I think this becomes complicated when you have more than one method to call on the builder. I think ErrorProne enforcement is the right idea here. @jakewharton and I have discussed it, I just haven't gotten to it yet

**Comment by naturalwarren** [comment]
Sounds good. Closing out this issue.
