### ISSUE TITLE
Same injects both in subcomponent and parent component with same dependencies type.

### ISSUE THREAD

**Issue by guliash** [google/dagger#629]
Suppose we have next Dagger2 configuration:
```
@Component(modules = ModuleA.class)
public interface ComponentA {
    void inject(MainActivity activity);
    ComponentB plus();
}

@Module
public class ModuleA {
    @Provides
    public String string() {
        return "A";
    }
}


@Subcomponent(modules = ModuleB.class)
public interface ComponentB {
    void inject(MainActivity activity);
}

@Module
public class ModuleB {
    @Provides
    public String string() {
        return "B";
    }
}


public class MainActivity extends AppCompatActivity {

    @Inject
    String string;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        DaggerComponentA.create().plus().inject(this);

        System.out.println(string); //A
    }
}
```

Wouldn't it be better if Dagger2 threw an exception instead of injection "A"? If we remove inject from ComponentA the code will not compile, because "String is bound multiple times".
Is it a bug or a feature?

P.S. Full code available [here](https://github.com/guliash/DaggerExamples/tree/dagger629)

**Comment by Tagakov** [comment]
This seems like an error prone behavior, can anybody explain it or point to documentation?

**Comment by ronshapiro** [comment]
This is definitely a bug. There should be a different members injector created for each level, and we should also resolve the duplicate binding earlier on.

I'm not sure how to fix this right now, but we should definitely address it.

**Comment by naturalwarren** [comment]
I can help out here if you like @ronshapiro. Let me know :)

**Comment by ronshapiro** [comment]
Please!

**Comment by Tagakov** [comment]
Thank you @ronshapiro  and @naturalwarren !

**Comment by supotuco** [comment]
@naturalwarren what is the status of this issue?

**Comment by naturalwarren** [comment]
At the moment I'm not aware of any updates; fixing this required a large change to how dependencies are resolved.

**Comment by ronshapiro** [comment]
This is now correctly reported as an error.
