### ISSUE TITLE
Improve error message when constructor declaration has "throws"

### ISSUE THREAD

**Issue by bubenheimer** [google/dagger#631]
Given the following:

    class TestClass {
        @Inject
        TestClass() throws Exception {}
    }

The compiler does not seem to like the `throws` clause, but generates a misleading error (the problem is harder to spot when the constructor has a lot of parameters):

`TestClass cannot be provided without an @Inject constructor or from an @Provides- or @Produces-annotated method.`

**Comment by ronshapiro** [comment]
I'm not able to reproduce this. If someone can, let's reopen.

**Comment by bubenheimer** [comment]
I see that there is an additional, clear error in Dagger 2.21. Not sure if I missed it before or if it did not show up back then:

    error: Dagger does not support checked exceptions on @Inject constructors
