### ISSUE TITLE
Generated code has rawtypes warning with DelegateFactory

### ISSUE THREAD

**Issue by vminc** [google/dagger#634]
Example:

warning: [rawtypes] found raw type: DelegateFactory
    this.myControllerProvider = new DelegateFactory();
                                                          ^
  missing type arguments for generic class DelegateFactory<T>
  where T is a type-variable:
    T extends Object declared in class DelegateFactory

**Comment by JakeWharton** [comment]
How about 2.10-rc4?

**Comment by vminc** [comment]
Just verified that the warnings still exist in 2.10-rc4

**Comment by ronshapiro** [comment]
Can you post an example? This isn't enough data. Also, what compiler are you using? Javac? Eclipse?

**Comment by ronshapiro** [comment]
Looks like this code should have a type parameter (and cast to the raw type with a `@suppresswarnings` when necessary): https://github.com/google/dagger/blob/master/compiler/src/main/java/dagger/internal/codegen/AbstractComponentWriter.java#L1032

**Comment by vminc** [comment]
This is the relevant part of my example. Looks like there is    @SuppressWarnings("unchecked") but not one for rawtypes.

```
public final class DaggerDesktopComponent implements DesktopComponent {
   ...
   @SuppressWarnings("unchecked")
  private void initialize(final Builder builder) {
       ...
       this.playerControllerProvider = new DelegateFactory();
       ...
  }
}
```
