### ISSUE TITLE
Question : How to use DaggerAppCompatActivity ?

### ISSUE THREAD

**Issue by UsherBaby** [google/dagger#639]
Could you take a look at my codes [link to codes](https://github.com/UsherBaby/dagger2-question/tree/master/src)
+++++++++++++++++++++++++++++++++++
Version 2.10-rc4
+++++++++++++++++++++++++++++++++++

Error:(11, 8) error: [dagger.android.AndroidInjector.inject(T)] java.util.Map<java.lang.Class<? extends android.support.v4.app.Fragment>,javax.inject.Provider<dagger.android.AndroidInjector.Factory<? extends android.support.v4.app.Fragment>>> cannot be provided without an @Provides-annotated method.
java.util.Map<java.lang.Class<? extends android.support.v4.app.Fragment>,javax.inject.Provider<dagger.android.AndroidInjector.Factory<? extends android.support.v4.app.Fragment>>> is injected at
dagger.android.DispatchingAndroidInjector.<init>(injectorFactories)
dagger.android.DispatchingAndroidInjector<android.support.v4.app.Fragment> is injected at
dagger.android.support.DaggerAppCompatActivity.supportFragmentInjector
com.example.demo.TodoActivity is injected at
dagger.android.AndroidInjector.inject(arg0)

**Comment by ronshapiro** [comment]
Please review the docs: google.github.io/dagger/android

**Comment by UsherBaby** [comment]
@ronshapiro Thanks ! I have found what the problem is .
