### ISSUE TITLE
Update dependency of guava from 21.0-rc1 to 21.0.

### ISSUE THREAD

**Issue by TonyTangAndroid** [google/dagger#643]
[Guava 21.0](https://mvnrepository.com/artifact/com.google.guava/guava/21.0
) has been officially released. But the [workspace](https://github.com/google/dagger/blob/cdff29ba11c92921fc44b9c57dda30a19c016fd6/WORKSPACE) is still using 21.0-rc1.

Should it be updated to 21.0?

**Comment by ronshapiro** [comment]
Just fixed this internally, it will be in the next sync out
