### ISSUE TITLE
Dagger 2.10 with Proguard

### ISSUE THREAD

**Issue by PavelSynek** [google/dagger#645]
After updating Dagger to 2.10, I get following Proguard warning
`Warning: dagger.android.DispatchingAndroidInjector: can't find referenced class com.google.errorprone.annotations.CanIgnoreReturnValue
`

The annotation is used [here](https://github.com/google/dagger/blob/master/java/dagger/android/DispatchingAndroidInjector.java#L66).
I could ignore the warning in proguard rules, but I don't think this annotation from `com.google.errorprone.annotations` should be used outside of codegen package.

**Comment by ronshapiro** [comment]
That annotation is intentional there, it's used by ErrorProne. ErrorProne annotations have no use at runtime, so it's fine to ignore them in Proguard.

**Comment by rakshakhegde** [comment]
Even I got the same issue. Please show how to ignore only that errorprone annotation?

**Comment by ronshapiro** [comment]
`-dontwarn com.google.errorprone.annotations.*`

**Comment by PaulWoitaschek** [comment]
Can you add consumer proguard rules for dagger?
