### ISSUE TITLE
Allow fake DispatchingAndroidInjector implementations

### ISSUE THREAD

**Issue by vaughandroid** [google/dagger#648]
My motivation for this is to make it possible to inject different test doubles into Activities on a per-test basis. I'm going to talk about Activities here, but I think Fragments/etc have similar issues which could be resolved the same way.

My particular use case is UI tests - these are more fine-grained than functional/end-to-end integration tests (some people might consider them unit tests). I am familiar with the guidance on testing but the usual suggested approaches all have issues:

* Manual injection isn't an option because for various reasons - not least of which,  if we're calling `AndroidInjection.inject(this)` at the start of `onCreate()` then it determines what is injected - at least for the duration of `onCreate()`.
* Creating separate Component configurations for each test requires creating a complete object graph in each instance. This can involve a lot of boilerplate which quickly results in hard-to-read tests.

Injecting a stub DispatchingAndroidInjector into the Application class would enable injection of the Activity/Activities being tested to be done manually. I can achieve this myself by proxying the call to `AndroidInjection.inject(this)` and stubbing the proxy, but it would be nice if this were supported out of the box.

**Comment by liminal** [comment]
Why would you need to create a complete object graph for every test? All you need is a component that can inject the activity under test and allow for dispatchingActivityInjector to be set in the Application object

**Comment by vaughandroid** [comment]
@liminal I think you're right, but it's still a comparatively indirect process that brings with it some boilerplate. Along with the Component you'd need at least one Module.

I feel my suggestion would allow for a reasonable approximation of manual injection into Android classes, with essentially zero impact on production code.

On mobile at the moment, but I'll try to throw together a gist later to clarify what I mean and compare the two approaches. It's possible I'm missing something and there's already a simpler way of doing what I want to achieve.

**Comment by vaughandroid** [comment]
OK, [here's](https://gist.github.com/vaughandroid/3c3c260fc7fcb64a628a55712a87736c) a gist showing @liminal's suggested technique:  It isn't as bad as I first feared, but there's still a bit of boilerplate and some fairly unintuitive faffing around with generics required.

[Here's](https://gist.github.com/vaughandroid/9aae0dd45469d088ff37cfea5072b999) a gist showing how easy it could be if DispatchingAndroidInjector were mockable. Just create a manual stub to inject the Activity, and you're done.

**Comment by ronshapiro** [comment]
I have a change that's being submitted now and I believe that it should also handle this.

The gist is that `HasDispatching*Injector` is being renamed to `Has*Injector`, and those methods can return `AndroidInjector<T>` instead of `DispatchingAndroidInjector<T>`. `DispatchingAndroidInjector` will now implement `AndroidInjector` (it already has the same API).

That means that you could always create your own implementation of `AndroidInjector` (or mock it if you so choose).

**Comment by gk5885** [comment]
To claify, while @ronshapiro's change does make it technically possible to use a *mock* here, please don't.  (In fact, we should probably throw `@DoNotMock` on this.)

@vaughandroid's gist uses a fake, which I think is a great solution, but we should discourage mocking in the mockito/easymock sense.

**Comment by vaughandroid** [comment]
Awesome, thanks guys. Definitely good to close this once @ronshapiro's commit gets merged in.
And sorry about the mock/fake confusion - I'm a bit mortified since I blogged about that very thing a few months back!
