### ISSUE TITLE
Share .bazelproject to setup IntelliJ

### ISSUE THREAD

**Issue by tbroyer** [google/dagger#649]
I had to battle a bit to get a functional IntelliJ IDEA project with https://ij.bazel.build (and apparently the plugin is not compatible with Android Studio 2.3). Sharing `.bazelproject` would help. Some doc pointing to bazel.build and the IDE plugins too.

**Comment by ronshapiro** [comment]
That's a great idea. Thanks for reporting!

**Comment by hzsweers** [comment]
any update on this one?

**Comment by ronshapiro** [comment]
I just tried to do this and succeeded with the following `.bazelproject`:

```
directories:
  .

targets:
  //...:all

android_sdk_platform: android-25
```

Is that helpful to post? That's just what was given to me, without any modifications.

**Comment by tbroyer** [comment]
Sure, defaults look good nowadays.

**Comment by jenisonleo** [comment]
Hi can someone update the solution for this issue
