### ISSUE TITLE
Android Stduio 2.3  Error:Failed to resolve: annotationProcessor

### ISSUE THREAD

**Issue by doublechina** [google/dagger#650]
gradle  configuration
dependencies {
  compile 'com.google.dagger:dagger:2.x'
  annotationProcessor 'com.google.dagger:dagger-compiler:2.x'
}

Error:Failed to resolve: annotationProcessor
"openFile:E:/AndroidDeveloper/AndroidProject/git/Call/Automatic/Auto/build.gradle"

**Comment by JakeWharton** [comment]
What version of the Android Gradle plugin are you using? Use 2.3.0.

**Comment by doublechina** [comment]
I use  Android Stduio 2.3 and the Android Gradle plugin  3.3

**Comment by JakeWharton** [comment]
3.3 is the version of Gradle, not the version of the Android Gradle plugin. It should be in the root build.gradle file.

**Comment by doublechina** [comment]
This is my  root build.gradle file

buildscript {
    repositories {
        jcenter()
//        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.3.0'

    }
}

allprojects {
    repositories {
        jcenter()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

**Comment by JakeWharton** [comment]
You need to replace "2.x" with "2.10" in the dependency declaration. Totally missed that...

**Comment by doublechina** [comment]
This is my dagge demo 
https://github.com/doublechina/Call

I tested  2.0-2.10

 Error:Failed to resolve: annotationProcessor

**Comment by doublechina** [comment]
I need add apt?

apply plugin: 'com.neenbedankt.android-apt'

classpath 'com.neenbedankt.gradle.plugins:android-apt:1.8'

 // Dagger dependencies
   apt "com.google.dagger:dagger-compiler:$rootProject.daggerVersion"
   provided 'org.glassfish:javax.annotation:10.0-b28'
   compile "com.google.dagger:dagger:$rootProject.daggerVersion"

**Comment by JakeWharton** [comment]
No

**Comment by piotrek1543** [comment]
@doublechina that's definately not Butterknife issue. You commented line:

         classpath 'com.android.tools.build:gradle:2.3.0'

in `build.gradle` of `CommonLib`.

Uncommenting this line gives you the right error, which is:

> Error:(10, 0) Cannot change dependencies of configuration ':CommonLib:classpath' after it has been resolved.
> <a href="openFile:/home/primesoft.local/ekert/Desktop/Call/CommonLib/build.gradle">Open File</a>

and it says that your present Gradle files configurations is wrong. Maybe you're missing any module in `settings.gradle` or you used wrong name for it.

Please read: http://stackoverflow.com/questions/29077374/gradle-fails-to-resolve-dependencies-in-android-studio 

Hope it will help

P. S. @JakeWharton issue to close as not related to project.

**Comment by doublechina** [comment]
Thank  you
