### ISSUE TITLE
HasDispatchingActivityInjector class not exist in v2.10 of dagger 

### ISSUE THREAD

**Issue by FaridBeiranvand** [google/dagger#660]
hi.i want to use HasDispatchingActivityInjector class of Dagger based on documentation.but i cant found "HasDispatchingActivityInjector" class in Dagger.i used Gradle for implement Dagger:
```
    compile 'com.google.dagger:dagger:2.10'
    annotationProcessor 'com.google.dagger:dagger-compiler:2.10'
```
HasDispatchingActivityInjector is beta version? or my Gradle Implemention is incorrect?please help me.thanks

**Comment by oldergod** [comment]
You would want to add those

```gradle
  compile 'com.google.dagger:dagger-android:2.10'
  compile 'com.google.dagger:dagger-android-support:2.10'
```

**Comment by ronshapiro** [comment]
Also `annotationProcessor 'com.google.dagger:dagger-android-processor:2.10'`. Does someone want to send a PR to update the docs?

**Comment by FaridBeiranvand** [comment]
@oldergod And @ronshapiro thanks a lot

**Comment by oldergod** [comment]
@ronshapiro #663

**Comment by IgorGanapolsky** [comment]
I am still getting an error:
> cannot find symbol class HasDispatchingActivityInjector 

Even with dagger 2.14.1

**Comment by ronshapiro** [comment]
It was renamed to `HasActivityInjector`

**Comment by ImaginativeShohag** [comment]
Again it was renamed to `HasAndroidInjector`
