### ISSUE TITLE
how to install Install AndroidInjectionModule in my application component

### ISSUE THREAD

**Issue by FaridBeiranvand** [google/dagger#662]
hi.based on documentation, for use dagger we should install AndroidInjectionModule in Application Component.but i dont Know how to install it in my component.please help me.thanks

**Comment by Nimrodda** [comment]
It refers to your app component. You need to list it as one of the modules in `@Component(modules = { AndroidInjectionModule.class }). For example:

```
@Component(modules = { AndroidInjectionModule.class, AppModule.class })
public interface AppComponent {
    void inject(App app);
}
```

**Comment by oldergod** [comment]
You would want to add those

```gradle
  compile 'com.google.dagger:dagger-android:2.10'
  compile 'com.google.dagger:dagger-android-support:2.10'
```

**Comment by FaridBeiranvand** [comment]
@Nimrodda And @oldergod Thanks a lot.
