### ISSUE TITLE
Missing `allclasses-frame.html` for api/latest/

### ISSUE THREAD

**Issue by oldergod** [google/dagger#667]
I am not sure how you generate those files but this gives a 404 here.

![image](https://cloud.githubusercontent.com/assets/1767669/24383053/62a6fbe6-1395-11e7-92c0-9e0fa947bc59.png)

**Comment by oldergod** [comment]
@ronshapiro  It does not seem to have been fixed: https://google.github.io/dagger/api/latest/

**Comment by tbroyer** [comment]
Javadoc publishing fails. The line
```
unzip ../bazel-genfiles/user-docs.jar -d api/latest
```
fails because the script has `cd`'d to `$HOME/gh-pages`, so `../bazel-genfiles/user-docs.jar` can't be found. It should probably use `$(dirname $0)/bazel-genfiles/user-docs.jar` or similar (maybe using `$TRAVIS_BUILD_DIR`?)

**Comment by ronshapiro** [comment]
Oh shoot, bazel-genfiles needs to be replaced with bazel-bin now that we
are using Skylark.

**Comment by tbroyer** [comment]
The `../` was already in error before the move to skylark though: https://travis-ci.org/google/dagger/builds/222089220#L5581

**Comment by ronshapiro** [comment]
Build 766 was with the `../` though. I just tried this locally and it seems to pass.

**Comment by ronshapiro** [comment]
Ah, I missed the `cd $HOME` part.

**Comment by ronshapiro** [comment]
Ok, this should *actually* be fixed now. I verified on the gh-pages site, and here's the commit: https://github.com/google/dagger/commit/769009e1c9c7bbc6608d31ed262e2c05b7cb0615

Thanks everyone!
