### ISSUE TITLE
errors with dagger compiler and kapt

### ISSUE THREAD

**Issue by flaquir4** [google/dagger#675]
Hi,

I'm tying to add multibindings in mi kotlin proyect but I have problems with dagger compiler. 
I have the following snippet in mi Module 

   ```
    @Singleton
    @ElementsIntoSet
    @Provides
    fun providesQueries(foo: Foo): Set<Foo>{
        val queries = LinkedHashSet<Foo>()
        queries.add(foo)
        return queries
    }

```
But dagger says that cannot provide java.util.Set<? extends Foo>
Te strange thing comes when i remove the Dagger compiler from my gradle.build and the app works fine and dagger injects well the Set.

**Comment by JakeWharton** [comment]
Switching to `MutableSet` or adding `@JvmSuppressWildcard` should correct that.

**Comment by flaquir4** [comment]
Thanks for the reply, it solved my error. But can you explain me why this solve the error please?

**Comment by JakeWharton** [comment]
Dagger doesn't work with sets that have variance in their type. By using one of those two options you change the bytecode that Kotlin emits so that it emits `Set<Foo>` instead of `Set<? extends Foo>` allowing it to work.

**Comment by tbroyer** [comment]
Note that this is a dupe of #668 from a few days ago.
