### ISSUE TITLE
Android dependencies.

### ISSUE THREAD

**Issue by ldulcic** [google/dagger#680]
Could you please write explicitly in README that we need to include lines below in `build.gradle` in order to use `dagger.android`:
```
annotationProcessor 'com.google.dagger:dagger-android-processor:2.x'
compile 'com.google.dagger:dagger-android:2.x'
compile 'com.google.dagger:dagger-android-support:2.x' //for support version
``` 
This isn't obvious from the docs, I got an impression that `dagger.android` is contained in standard dagger version.

Thanks in advance!

**Comment by JonathanMerritt** [comment]
[https://github.com/google/dagger/pull/663](Update the README's installation steps for `dagger.android`)
