### ISSUE TITLE
Android component templates in repo

### ISSUE THREAD

**Issue by trevjonez** [google/dagger#682]
I whipped up a bunch of file template for idea / android studio yesterday that help with the bit of boilerplate required to use the new android module types.

Assuming an activity class named `SomeActivity` you can use the `ActivityComponent` or `ActivityComponentKt` template and enter `SomeActivityComponent`.

The resulting class looks like this:
```java
package com.example;

import android.app.Activity;

import dagger.Binds;
import dagger.Module;
import dagger.Subcomponent;
import dagger.android.ActivityKey;
import dagger.android.AndroidInjector;
import dagger.multibindings.IntoMap;

@Subcomponent
public interface SomeActivityComponent extends AndroidInjector<SomeActivity> {
    @Subcomponent.Builder
    abstract class Builder extends AndroidInjector.Builder<SomeActivity> {
    }

    @Module(subcomponents = SomeActivityComponent.class)
    abstract class BindingModule {
        @Binds
        @IntoMap
        @ActivityKey(SomeActivity.class)
        abstract AndroidInjector.Factory<? extends Activity> someActivityComponentBuilder(Builder impl);
    }
}
```

Would you be willing to include the templates in the repo? 

My biggest concern is difference in tastes. I imagine some people might not love the nested module although being mostly boiler plate and highly related it made sense to have it nested allowing for a consistent scheme in a project.

I have templates for the 5 main platform types all setup in both kotlin and java

**Comment by ronshapiro** [comment]
We should have a new API dropping very shortly that should make templates like this not necessary (and easier for refactoring). Stay tuned!
