### ISSUE TITLE
Cannot open the repository in android studio

### ISSUE THREAD

**Issue by johnpatrow** [google/dagger#683]
How can i view examples and the project at my local machine after opening the project it says framework is detected?

**Comment by johnpatrow** [comment]
Does this even open in android studio ? is any other IDE is required to open the repository cloned at local machine?

**Comment by JakeWharton** [comment]
You can open it in IntelliJ with the Bazel plugin installed. Import mostly just works, although #649 should help in the future.

**Comment by ronshapiro** [comment]
When we add #649 that I'll make sure to document how to get started
