### ISSUE TITLE
Support for Map Multibindings "contribute several elements at one time" like @ElementsIntoSet

### ISSUE THREAD

**Issue by hrgdavor** [google/dagger#687]
I have just started to test out Dagger2 on some sample projects and have noticed lack of support for Map similar to @ElementsIntoSet.
I got around this by defining a simple Pair class

```java
public static class Pair<K, V>{
	private K left;
	private V right;
	
	public Pair(K left, V right) {
		super();
		this.left = left;
		this.right = right;
	}
	
	public K getKey() {
		return left;
	}
	
	public V getValue() {
		return right;
	}
}
```
Then I was able to contribute multiple map bindings at once. (sometimes I prefer just create some of  classes directly without using injection)
```java
@Provides @ElementsIntoSet
Set<Pair<String, TaskFactory>> taskFactoriesContrib2(){
	 Set<Pair<String, TaskFactory>> ret = new HashSet<>(); 
	 ret.add(new Pair<>("var",  new VarTaskFactory(watchBuild,true)));
	 ret.add(new Pair<>("sass", new SassTaskFactory(watchBuild, json)));
	 ret.add(new Pair<>("copy", new CopyTaskFactory(watchBuild, json)));
	 //.....
	;
	return ret;
}
```
Because this is verbose I decided to add a helper class PairSet<K,V> and move Pair into it
```java
public class PairSet<K,V> extends HashSet <PairSet.Pair<K,V>>{	

	public PairSet<K,V> put(K left, V right){
		add(new Pair<K,V>(left, right));
		return this;
	}

	public Map<K,V> toMap(){
		return toMap(this);
	}

	public static final <K,V> Map<K,V> toMap(Collection<Pair<K,V>> pairs){
		return toMap(new HashMap<>(), pairs);
	}

	public static final <K,V> Map<K,V> toMap(Map<K, V> mapToFill, Collection<Pair<K,V>> pairs){
		for(Pair<K,V> p:pairs) mapToFill.put(p.getKey(), p.getValue());
		return mapToFill;
	}
}
```

This enabled me to have simpler code

```java
@Provides @ElementsIntoSet
Set<Pair<String, TaskFactory>> taskFactoriesContrib(){

	return new PairSet<String, TaskFactory>() 
	.put("var",  new VarTaskFactory(watchBuild,true))
	.put("sass", new SassTaskFactory(watchBuild, json))
	.put("copy", new CopyTaskFactory(watchBuild, json))
	;
}

```

It would be nice if Dagger would integrate Pair class directly and Map multibinding would also pickup from @IntoSet and @ElementsIntoSet where set is declared as Set<Pair<K,V>>. 

I am ok with my workarround for what I need, but it would be nice to have in Dagger directly.

**Comment by ronshapiro** [comment]
You have hardcoded the keys - why not just use regular map bindings? 

Doing exactly what you are doing is precisly what we recommend in https://google.github.io/dagger/multibindings#maps-whose-keys-are-not-known-at-compile-time

**Comment by hrgdavor** [comment]
The reason for not using regular map binding is that I would have to have a contirib method for each task I want to add, and there is no equivalent to adding multiple bindings in one contribution metohd like there is for Set: @ElementsIntoSet.

I had for example 10 different task factories that have maybe 3 deps in total to inject into the contrib method. I would have to repeat contribution declaration 10 times. It is just verbose and cumbersome.

And if my class accepts Map<String, TaskFactory> I also have to create a @provides method

```java
@Provides 
public Map<String, TaskFactory> provideReportMap(Set<Pair<String, TaskFactory>> pairs){
	HashMap<String, ReportProvider> map = new HashMap<>();
	for(Pair<String, ReportProvider> p:pairs) map.put(p.getKey(),p.getValue());
	return map;
}
```
I have made a bit leaner with my own utility.

```java
@Provides 
public Map<String, TaskFactory> provideReportMap(Set<Pair<String, TaskFactory>> pairs){
	return PairSet.toMap(pairs);
}
```
And finally, if I choose this approach, I can not combine it with regular Map binding, so I just decide That Map binding is useless and it is better for me to do all with @IntoSet and @ElementsIntoSet because it is more flexible and nicer to use.

I just want to have cleaner code. Maybe the effort to add this is big related to other things you have on the roadmap. 

I am perplexed why would you refuse to think about having equivalent to @ElementsIntoSet for map bindings ? I just makes them inferior to use in the current state.

**Comment by InvisibleGit** [comment]
This is proving to be very needed feature.

Different from OP, but here's an example from Android world.

We split suite of applications into library and app modules. Common functionality, including Activities and their ViewModels from Android Architectural Components are put inside a library (say LoginActivity or HelpActivity). We need to merge `@IntoMap`'s with `@ActivityKey`s and `@ViewModelKey`s (custom mapkey) into app module's Dagger graph. Currently the only way is to redefine them in each app module.

As of now we can export Maps of Activities and ViewModels from library, but we don't have the way to merge them in apps module Dagger graph.

Having something like `@EntriesIntoMap` would make redefining those objects (Activities, ViewModels, Services, Fragments) obsolete. Something like
```
@Provides
@EntriesIntoMap
static Map<Class<? extends ViewModel>, Provider<ViewModel>> getViewModelsFromCommonLibrary() {
    commonLibraryDaggerGraphWrapper.getViewModels();
}
```

and likewise for Activities, Fragments, Services, ...

The same would be useful for the rest of the Java ecosystem, like merging Dagger graphs from other .jars

@ronshapiro, please reconsider this...
