### ISSUE TITLE
Allow @ElementIntoSet using parameters instead of returning new set

### ISSUE THREAD

**Issue by hrgdavor** [google/dagger#688]
It would be nice to declare the set as parameter so it does not need to be created in the contribution.

Example in general would be something like this
```java
@Provides @ElementsIntoSet @TaskNameQualifier
void taskNamesContrib(Set<String> set, DepA a, DepB b){
	set.add"var1");
	set.add"var2");
	set.add"var3");
}
```

An exmaple related to #687 would then look like this

```java
@Provides @ElementsIntoSet 
void taskFactoriesContrib2(PairSet<String, TaskFactory> set, WatchBuild watchBuild, JsonMapper json){
	set.put("var",  new VarTaskFactory(watchBuild,true))
	.put("sass", new SassTaskFactory(watchBuild, json))
	.put("copy", new CopyTaskFactory(watchBuild, json))
	;
}
```

A more restrictive interface could be used to avoid abuse/errors.

**Comment by ronshapiro** [comment]
Is the goal to save a few allocations? This seems like a micro optimization to me.

**Comment by hrgdavor** [comment]
It is not about micro optimization, it is about quality of life and cleaner code. But the fact it is even a bit more optimized is a plus :). How the code reads. I am testing Dagger2 by converting an existing project based on TapestryIOC. Comming from another IOC, of course makes me miss some patterns I was used have.

I think it is too early for me to try do it, but I am wondering if you accept patches ?

**Comment by ronshapiro** [comment]
We do, but this isn't something that really makes sense as a widespread dagger feature. If you want this for your own readability, you can just request a new set for each method. Qualifiers should make this pretty simple.

**Comment by hrgdavor** [comment]
Qualifiers have nothing to do with this. I can see that this changes only a little bit for the user and might be complicated to implement. Coming from a different DI, the suggested approach just sounds logical to me when reading a module (maybe just because I got used to it).

 - declare a method that contributes to a Set
 - declare the Set as one of parameters along with other deps
 - later DI calls your method to tell you to put some stuff into the set 

well, at least somebody else might try similar idea and see this rejected request. I can agree that it is not worth the effort implementing as it does not bring a significant enough benefit.

**Comment by TWiStErRob** [comment]
@hrgdavor Your three steps just above sounds like you can do without any new annotations. A simple scoped `@Provides` to create the `Set` should be sufficient to satisfy `taskNamesContrib`'s signature which then would mutate that `Set`. Although I'm not sure if there's a guarantee that mutating `@Provides` methods would be called before injecting it to the user.

**Comment by hrgdavor** [comment]
So much time has passed since this ticket. If you could write an example based on my example. I don't understand your proposal exactly.
