### ISSUE TITLE
Question about Android component hierarchy 

### ISSUE THREAD

**Issue by AndroidGuyDD** [google/dagger#693]
Following the example of the new Dagger 2.10 Android tooling, I wrote a simple application with activity scoping and fragment scoping. I use both HasActivityInjector and HasFragmentInjector
- Activity subcomponents are registered in the application component and
- Fragment subcomponents are registered in a respective activity component 

So far this works fine. But I've following requirement that can't seem to realise so far:
All my activities (and depending subcomponents with their dependencies like presenters and fragments) want to have an injection from an instance, that needs an activity. 
Concrete example would be an AppRouter class that is provided once per Activity and used for generating navigation intents. 

Since this class is common for all activities, it doesn't make sense to provide it in each activity module. Hence I need kind of a BaseModule that provides such common dependencies on the activity level and receiving an activity. But even if I supply such a module to each subcomponent declaration, how do I provide the needed (base type) activity, because I have only the specific activity for this subgraph.  

I tried to come up with a BaseActivity subcomponent, from which all other activities are subcomponents. Therefore creating another layer of hierarchy. But it doesn't work. 

Any insights or suggestions what would be a better approach?

**Comment by JonathanMerritt** [comment]
Your instance is provided automatically.

Reference:
[Dagger 2 Github Issue: 615](https://github.com/google/dagger/issues/615)
[SO Question: Referencing the Activity inside its module](http://stackoverflow.com/posts/43010226/edit)

**Comment by AndroidGuyDD** [comment]
@JonathanMerritt as I mentioned I know we have the specific activity at our disposal. My presenters for example are working exactly like it is described in your reference.

Maybe it gets more clear if post my example and how it works right now (I found a solution but not sure if it's the most elegant one)

    @PerActivity
    class AppRouter<out T : Activity>
        @Inject constructor(val activity: T) {
         ....
         // the class that gets any of my activities as dependency
     }

This class is then injected where it's needed:
    class MainActivity : AppCompatActivity(), MainPresenterContract {

        @Inject
        lateinit var presenter: MainPresenter

        @Inject
        lateinit var appRouter: AppRouter<MainActivity>

or for example in a presenter:

    class SomePresenter 
        @Inject constructor( 
            val appRouter: AppRouter<SomeActivity>,
            val viewContract: SomeViewContract)

This works because I typed the AppRouter class but I was looking for a dagger only way in where I simply declare my AppRouter without generics.

    @PerActivity
    class AppRouter
        @Inject constructor(val activity: Activity) {

**Comment by JonathanMerritt** [comment]
Sorry. I'm a horrible glance reader sometimes.

Not at all familiar with kotlin(Assuming that's the lang...). I am afraid I don't totally understand.

Can you not just have each activity provide a base? Then use that in your appRouter? Possibly creating a base router that has concrete abstractions that you can constructor inject. To avoid needing to type each one.

Idk though, like I said, I'm not sure I understand what you're issue is. Sorry.

**Comment by JonathanMerritt** [comment]
For example: @Binds abstract BaseActivity activity(MainActivity activity);

As long as each activity provides that, then you'll have it for any app objects that need it.

**Comment by AndroidGuyDD** [comment]
Your last suggestion might work. I'll try that. 
Yet it still feels a little verbose to write that into each module.

**Comment by JonathanMerritt** [comment]
Yeah, though considering how much modules and components contained before dagger.android. I'm pretty happy with it. And it seems they have some good stuff coming for 2.11.

Let me know if it works, and more importantly if you figure out another more preferred way.

**Comment by AndroidGuyDD** [comment]
@Binds abstract Activity activity(YourActivityFromSubComponent activity);
This did the trick and I prefer it over the generic approach. Thanks again. One just has to remember to put it into every new Module. 
Some base module could help, but this would need to be typed in order to accept the specific activity. Modules however can't be typed so I'll just close this issue for now.
