### ISSUE TITLE
Static provides method from kotlin module throws error.

### ISSUE THREAD

**Issue by trevjonez** [google/dagger#699]
Given the following module:

```kotlin
@Module
abstract class SomeModule {

    companion object {
        @Provides
        @JvmStatic
        fun specificClickEvent(viewController: SomeViewController): Observable<Click<ViewData>> {
            return viewController.clickEvents
        }
    }
}
```

When decompiled into java it looks something like this:
```java
@Module
public abstract class SomeModule {
    public static final SomeModule.Companion Companion = new SomeModule.Companion();

    @Provides
    @JvmStatic
    @NonNull
    public static final Observable specificClickEvent(@NonNull SomeViewController viewController) {
        //checkNotNull viewController
        return Companion.specificClickEvent(viewController);
    }

    public static final class Companion {
        @Provides
        @JvmStatic
        @NonNull
        public final Observable specificClickEvent(@NonNull SomeViewController viewController) {
            //checkNotNull viewController
            return viewController.getClickEvents();
        }
    }
}
```

Which results in an error being thrown by dagger to the following effect:
`Error:@Provides methods can only be present within a @Module or @ProducerModule`

The work around is to add `@Module` to the companion object which will never be directly used as a module since it is just an implementation detail of the the outer module. 

So the question is, would it be acceptable for dagger to check if the layout of the containing class matches that of the kotlin companion object(via naming + Metadata annotation) and not error or should there be a feature request filed with the kotlinlang issue tracker to add specific annotation targeting for `@JvmStatic` methods thus allowing the user to configure where `@Provides` is placed in the output bytecode?

**Comment by JakeWharton** [comment]
This doesn't seem like Dagger's problem. An easy workaround is to annotate the companion object with `@Module` and then add it as an `includes = ` on the enclosing class's `@Module` declaration.

Additionally, Kotlin is considering allowing declaring static methods directly on classes which you can vote for in the recent [Kotlin developer survey][1].

 [1]: https://docs.google.com/forms/d/e/1FAIpQLSdnCgBonEV5pwN8L903BzdYb9Baf0dpwsJ5YrKnxLveiLFkEQ/viewform

**Comment by JakeWharton** [comment]
Also a companion object can't be identified by name since you can name it whatever you want.
```kotlin
class Foo {
  companion object Bar {
  }
}
```

**Comment by trevjonez** [comment]
based on the decompiled code there shouldn't be any reason to manually include the companion as a module since the actual static method is annotated correctly and is just a synthetic to the companion instance method. I would expect dagger to throw an error due to providing the same type twice, although it didn't when I just added the companion as an included module although the modules were not yet added to any component. Once you add them to a component you then have to start adding component builder methods to provide the companion object to create the component. Most likely due to the private default constructor on the companion object. Not sure what that is about, but unrelated to this. 

Really this is a kotlin/java interop issue, I was just hoping for a quicker fix than a language level change.

So closing as not a dagger problem and just use the workaround of annotating companion object class with `@Module` until we can get some better fix from kotlinlang.
