### ISSUE TITLE
@ContributesAndroidInjector doesn't work with gradle build system

### ISSUE THREAD

**Issue by kibao** [google/dagger#703]
During `:app:compileDebugJavaWithJavac` task, following exception is thrown:

```
:app:compileDebugJavaWithJavac
/app/build/generated/source/apt/debug/pl/kibao/contributesandroidinjector/ContributesAndroidInjectorModule_ContributeMainActivityInjector.java:21: 
error: @dagger.android.ActivityKey methods should bind dagger.android.AndroidInjector.Factory<? extends android.app.Activity>, 
not dagger.android.AndroidInjector.Factory<? extends android.app.Activity>. 
See https://google.github.io/dagger/android
  abstract AndroidInjector.Factory<? extends Activity> bindAndroidInjectorFactory(
                                                       ^
1 error
```

Generated class:

```
package pl.kibao.contributesandroidinjector;

import android.app.Activity;
import dagger.Binds;
import dagger.Module;
import dagger.Subcomponent;
import dagger.android.ActivityKey;
import dagger.android.AndroidInjector;
import dagger.multibindings.IntoMap;

@Module(
  subcomponents =
      ContributesAndroidInjectorModule_ContributeMainActivityInjector.MainActivitySubcomponent.class
)
public abstract class ContributesAndroidInjectorModule_ContributeMainActivityInjector {
  private ContributesAndroidInjectorModule_ContributeMainActivityInjector() {}

  @Binds
  @IntoMap
  @ActivityKey(MainActivity.class)
  abstract AndroidInjector.Factory<? extends Activity> bindAndroidInjectorFactory(
      MainActivitySubcomponent.Builder builder);

  @Subcomponent(modules = MainModule.class)
  public interface MainActivitySubcomponent extends AndroidInjector<MainActivity> {
    @Subcomponent.Builder
    abstract class Builder extends AndroidInjector.Builder<MainActivity> {}
  }
}
```

I've created separate app with the same code, then replace `@ContributesAndroidInjector` with the generated class and that worked. That is why I think the problem is related to integration with gradle build system.

Example project: https://github.com/kibao/dagger-contributes-android-injector
Travis build: https://travis-ci.org/kibao/dagger-contributes-android-injector/builds/223293977#L1756

**Comment by ronshapiro** [comment]
Hm, that is in fact bizarre. I don't immediately see what's going on, I'll try and investigate more

**Comment by pushbit** [comment]
I've run into the same issue, but with `ContentProvider`.  The error message is not entirely helpful. :)

error: @dagger.android.ContentProviderKey methods should bind dagger.android.AndroidInjector.Factory<? extends android.content.ContentProvider>, not dagger.android.AndroidInjector.Factory<? extends android.content.ContentProvider>.

```java
  abstract AndroidInjector.Factory<? extends ContentProvider> bindAndroidInjectorFactory(
                                                              ^
```

**Comment by tbroyer** [comment]
@ronshapiro Any reason for using `MoreTypes.equivalence()` rather than `types.isSameType()` in https://github.com/google/dagger/blob/bb2d3a9f142f91156cfa39d5d5894ade0e146c4c/java/dagger/android/processor/AndroidMapKeyValidator.java#L107 ?

**Comment by tbroyer** [comment]
Oh, oops, I see that [`isSameType` explicitly returns `false` for wildcards](https://docs.oracle.com/javase/8/docs/api/javax/lang/model/util/Types.html#isSameType-javax.lang.model.type.TypeMirror-javax.lang.model.type.TypeMirror-).
I'm not sure `MoreTypes.equivalence()` is appropriately tested (test seems to only compare things to themselves, so the `Objects.equal()` optimization would return `true` and the equivalence wouldn't be actually tested; also compile-testing won't allow comparing type mirrors between processor rounds). So this might (or might not) be a bug in auto-common's `MoreTypes.equivalence()`.

**Comment by ronshapiro** [comment]
The issue is not necessarily in `MoreTypes.equivalence()` but rather that we retained an instance to the `TypeMirror`'s for framework types, and then used those across rounds. Then, `TypeElement.equals()` (which `MoreTypes.equivalence()` uses) is no longer stable. The wildcard part is fine, but the framework type is what isn't matching

**Comment by ronshapiro** [comment]
The latest snapshot should have a fix for this. It'll be live in ~15 minutes, can you check if it is in fact working then?

**Comment by Sroka** [comment]
I am not the original reporter but had the same problem and it is now fixed with latest snapshot. Thank you
