### ISSUE TITLE
Dagger2 does not generate components in Test

### ISSUE THREAD

**Issue by shonshampain** [google/dagger#706]
Issue is described here:
http://stackoverflow.com/questions/43545400/dagger2-does-not-generate-components-in-test

Clone project here:
https://bitbucket.org/shonshampain/robodagger

In summary:
I was of the understanding that I could create a TestModule and TestComponent,
but nothing I'm doing will cause Dagger2 to generate the DaggerTestComponent files.

Please help - I'm not implying this is a bug, I'm almost certain it's user error.
Thank you in advance.

**Comment by ronshapiro** [comment]
Please do not post questions here if they are not bugs

**Comment by shonshampain** [comment]
@ronshapiro I wasn't ruling out the possibility it was a bug. I was being polite.

**Comment by 515580096** [comment]
use  testApt "com.google.dagger:dagger-compiler:${daggerVersion}"

**Comment by Abdelsattar** [comment]
just add this testAnnotationProcessor 'com.google.dagger:dagger-compiler:${daggerVersion}'

**Comment by hilmanshini** [comment]
> just add this testAnnotationProcessor 'com.google.dagger:dagger-compiler:${daggerVersion}'

still doesnt work
