### ISSUE TITLE
Dealing with context in Dagger 2

### ISSUE THREAD

**Issue by jpgpuyo** [google/dagger#713]
Hello,

Without Dagger 2, when I need application context or activity context, usually we use one of this three options:
1. Pass context in every method I need
2. Store application context
3. Store WeakReference to context 

With Dagger 2, usually we are storing application context in ApplicationModule, and activity Context in ActivityModule.

Should we be careful with memory leaks when using Dagger 2, or the custom scopes provided by Dagger 2 are avoiding this kind of problems?
Is it necessary nullify Dagger 2 components when activity is destroyed?

Thank you,
Joaquim

**Comment by JakeWharton** [comment]
Treat the scoped instances of these components the same way you would the objects inside of them.

**Comment by jpgpuyo** [comment]
Ok, thank you!
