### ISSUE TITLE
DaggerApplication needs easy option to skip injection

### ISSUE THREAD

**Issue by bubenheimer** [google/dagger#714]
As far as I can tell, `DaggerApplication` in 2.11-rc1 is missing an easy way to skip injection of an Application class for a process. This could be achieved by making `DaggerApplication.setInjected()` `protected`, so that it can be called from a child class, or by giving special significance to a `null` return value from the `applicationInjector()` method.

Being forced to inject causes problems for multi-process apps, e.g. some random app with LeakCanary added. LeakCanary runs in a secondary process, and will use the same Application class as the main app process. If the Application class uses dependency injection for some fields in the main process, this wouldn't commonly be desirable for a third-party helper process like LeakCanary. The Application class shouldn't really do anything in the LeakCanary process, and certainly not waste time building an object graph.

**Comment by ronshapiro** [comment]
LeakCanary shouldn't be run in release builds, so this isn't a huge deal in development.

The use of `DaggerApplication` is by no-means mandated either. It should be pretty simple to have an application type which has the functionality you want.

**Comment by bubenheimer** [comment]
Obviously, LeakCanary is just as an easy-to-grasp example. And the need to work around not injecting into the Application object for a second process is not limited to release builds, as it's not just a potential performance problem, but also a potential code correctness issue.

It's a potential problem whenever you have a multi-process Android app. Would seem trivial to make `setInjected()` protected to cover those cases. Why would you mandate code duplication as the better alternative? Just because you are not facing the problem doesn't mean that it does not exist for others.

**Comment by ronshapiro** [comment]
The `Dagger*` classes were all designed to be extremely simple so that anyone that has complex hierarchies could reimplement them themselves. This is especially true for Activities and Fragments, but also all other types.

**Comment by ronshapiro** [comment]
Another option is to have two component implementations, and have `applicationInjector()` return conditionally, based on the process.

**Comment by bubenheimer** [comment]
Right now an app crashes when returning `null` from `applicationInjector()`. This could be turned into sensible behavior, meaning "do not inject".

I am already returning two different objects, depending on which of my two regular processes I am in. However, when the third process, LeakCanary, kicks in, I cannot inject anything, because the process is not under my control, etc. To manually build a custom AndroidInjector for this case is cumbersome, because I have to take special care of injecting the package-private `setInjected()` method. If I let Dagger build an injector for me, I'd have to invent a special object graph where the I make the injected objects nullable. So, much easier to duplicate the DaggerApplication class and add two lines to handle `null` sensibly, but it's ridiculous that you are forcing me to do this.

**Comment by ronshapiro** [comment]
Sorry if I'm not understanding, but does this solve your needs?

```java
@Component(modules = AndroidInjectionModule.class)
interface EmptyComponent extends AndroidInjector<MyApp> {}
```

>I am already returning two different objects, depending on which of my two regular processes I am in. However, when the third process, LeakCanary, kicks in, I cannot inject anything, because the process is not under my control, etc.

I didn't understand that. Are you able to detect which process you are in (main, your background process, and leakcanary) or not?

**Comment by bubenheimer** [comment]
Thanks, I'll try it out, that would be a decent solution if it works. I'll have to do a bunch of additional refactoring first to mold my Application class into the needed DaggerApplication shape, but I'll post an update. There are seven injected fields on my Application class that I need there for various reasons, so I'd have to "under-inject" (instead of my current approach of simply not injecting at all), and I don't know if that is possible. I could reduce the seven fields to one custom object, but I'm not sure if I want to go there.

I am able to detect which process I am in. When I detect that I'm in the LeakCanary process, I right now simply return from `onCreate()` right away, without doing any injecting or other work, because I have no business messing with the process. When I am in one of my "own" two processes then I build one of two different object graphs, depending on which process it is. I have two different object graphs a.k.a. component hierarchies for the two regular processes.

**Comment by bubenheimer** [comment]
The simple `EmptyComponent` solution does not work because it does not provide the objects that I need for the seven injected fields on my Application class. I could create custom providers for them, but that's too much work when compared to the alternative of simply not injecting at all.

**Comment by bubenheimer** [comment]
I ultimately eclipsed the issue by removing the injected fields from my Application class and exposing the objects on the components instead, plus using the `EmptyComponent` sample code for the `LeakCanary` process. I find the alternative of essentially duplicating and customizing the `DaggerApplication` class an undesirable approach because providing the `dagger.android.*` classes implicitly establishes standard patterns, and any duplication or deviation from the patterns impacts maintainability. In the particular case of the `DaggerApplication` class we are looking at a relatively sizable chunk of code, which aggravates the concern.
