### ISSUE TITLE
External (non-dagger) components

### ISSUE THREAD

**Issue by ZakTaccardi** [google/dagger#722]
Is it possible to use external, custom components - aka components created without dagger?

Certain language features of Kotlin, like the `lazy` delegate, make it *real* easy to wire up your own DI code. A big advantage of this is reduced build time via a reduction of annotation processing.

Suggestion: something like: 

```
@ExternalComponent
interface PaymentsComponent {
    Payments getPayments();
}

@Component(dependencies = PaymentsComponent.class)
interface DataLayerComponent {
    Payments getPayments();
}
```

An `@ExternalComponent` would be a component that the developer him/herself would be responsible for constructing.

**Comment by ronshapiro** [comment]
@Component.dependencies works with any type - it doesn't have to be a `@Component` itself. If this isn't working for you, reopen and post some more details of what you're seeing?

**Comment by ZakTaccardi** [comment]
Sounds like my use case is perfectly supported - great!
