### ISSUE TITLE
dagger-android causing seemingly unrelated dependency conflict

### ISSUE THREAD

**Issue by kdxvc** [google/dagger#725]
Hello,
I have just started a new project using Android Studio. I began by adding dependencies into my gradle file. Everything was working until I added `compile 'com.google.dagger:dagger-android:2.11-rc1'` and am now getting the error 

`Error:Conflict with dependency 'com.google.code.findbugs:jsr305' in project ':app'. Resolved versions for app (3.0.2) and test app (2.0.1) differ. See http://g.co/androidstudio/app-test-app-conflict for details.`

I have tried explicitly adding 3.0.2 of findbugs in my dependencies, but that has not helped.
 
The full build.gradle file is below:

apply plugin: 'com.android.application'

    android {
        compileSdkVersion 25
        buildToolsVersion "25.0.2"
        defaultConfig {
            applicationId "com.example.x"
            minSdkVersion 21
            targetSdkVersion 25
            versionCode 1
            versionName "1.0"
            testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        }
        buildTypes {
            release {
                minifyEnabled false
                proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            }
        }
    }

    dependencies {
        compile fileTree(include: ['*.jar'], dir: 'libs')
        androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
            exclude group: 'com.android.support', module: 'support-annotations'
        })

        compile 'com.google.code.findbugs:jsr305:3.0.2'

        compile 'com.google.dagger:dagger-compiler:2.11-rc1'
        compile 'com.google.dagger:dagger-android:2.11-rc1'
        compile 'com.google.dagger:dagger:2.11-rc1'

        // everything below should(?) be unrelated
        compile 'com.jakewharton:butterknife:8.5.1'
        compile 'com.android.support:appcompat-v7:25.3.1'
        compile 'com.jakewharton.timber:timber:4.5.1'
        compile 'io.reactivex.rxjava2:rxandroid:2.0.1'
        compile 'io.reactivex.rxjava2:rxjava:2.1.0'
        compile 'com.jakewharton.threetenabp:threetenabp:1.0.5'
        compile 'com.android.support.constraint:constraint-layout:1.0.2'
        compile 'com.android.support:design:25.3.1'
        testCompile 'junit:junit:4.12'

    }

**Comment by tbroyer** [comment]
The error says `compile` is using `3.0.2` but `androidTestCompile` is using `2.0.1`, so your `3.0.2` dependency should be added to `androidTestCompile`, not `compile`.

**Comment by kdxvc** [comment]
Ah, I had tried that, but was being tripped up because it needs to be added to *both* compile and androidTestCompile. Thanks for looking into it. It's all sorted now.
