### ISSUE TITLE
Add DaggerDialogFragment

### ISSUE THREAD

**Issue by UsherBaby** [google/dagger#728]
Any plan to add DaggerDialogFragment and DaggerBottomSheetDialogFragment ?

**Comment by ronshapiro** [comment]
I think we should probably add DialogFragment, but we need to be careful of adding implementations of every type of fragment ever. The implementations are simple enough

**Comment by ronshapiro** [comment]
Do you want to send a PR for DaggerDialogFragment?

**Comment by ashdavies** [comment]
I had to create one in a couple of my projects, has anybody submitted a PR already?

If not I might do so, should a `DialogFragment` be able to provide injectors for child fragments? or would it be considered the "end of the line" per se?
