### ISSUE TITLE
Injecting Dependencies From Base Class

### ISSUE THREAD

**Issue by f2prateek** [google/dagger#73]
In Dagger 1, you could call `inject` from a base class and have all dependencies satisfied for subclasses:

```java
class BaseActivity extends Activity {
  @Inject Foo foo;
  
  public void onCreate(Bundle savedInstanceState) {
    objectGraph().inject(this);
  }
}

class MainActivity extends BaseActivity {
  @Inject Bar bar;
  
  @Override void onCreate(Bundle savedInstanceState) {
    super.onCreate();
    // both foo and bar will be available here
  }
}
```

This has changes in Dagger 2; injecting from a base class will only satisfy the base class's dependencies, not it's subclasses's.

```java
class BaseActivity extends Activity {
  @Inject Foo foo;
  
  public void onCreate(Bundle savedInstanceState) {
    component().inject(this);
  }
}

class MainActivity extends BaseActivity {
  @Inject Bar bar;
  
  @Override void onCreate(Bundle savedInstanceState) {
    super.onCreate();
    // only foo is available here, not bar
  }
}
```

Is there a recommended pattern for injecting dependencies from a base class, rather than calling inject in each of the subclasses?

**Comment by svenjacobs** [comment]
Performing the dependency injection in an abstract base class of `Activity`, `Fragment`, etc. seems to be a common pattern in Android development with Dagger 1 because it's very handy. I'm using it, too.

How this can be achieved with Dagger 2 respectively alternative patterns should be clearly documented in a (migration) guide.

**Comment by svenjacobs** [comment]
Maybe injecting dependencies in a base class would work if a component supports generics? See #65.

**Comment by tbroyer** [comment]
FYI, I've just pushed out a 1.0-SNAPSHOT of [Bullet •](https://github.com/tbroyer/bullet) to the Sonatype OSS repository, so you can make @JakeWharton's example above work (well, it should work, I haven't tested):

```java
abstract class BaseThing {
  @Inject String foo;

  void doIt() {
    // Wrap the Component into the generated ObjectGraph:
    new Bullet_BaseComponent(Dagger_BaseComponent.create()).inject(this);
  }
}

class RealThing extends BaseThing {
  @Inject CharSequence bar;
}

@Module
class BaseModule {
  @Provides String provideString() { return "String!"; }
  @Provides CharSequence provideCharSequence() { return "CharSeq!"; }
}

@Component(modules = BaseModule.class)
interface BaseComponent {
  // You don't need to include a method for BaseThing here, only your concrete subclasses.
  void inject(RealThing realThing);
}

public class BaseExample {
  public static void main(String... args) {
    RealThing realThing = new RealThing();
    realThing.doIt();
    System.out.println("String? => " + realThing.foo);
    System.out.println("CharSeq? => " + realThing.bar);
  }
}
```

**Comment by cgruber** [comment]
This is less an issue, and more a discussion - I'm not sure where to go from here, but I'm going to close the issue for now, and if there's a feature request and/or further relevant discussion, it can be reopened. Given that #102 seems to be related, maybe further discussion can happen there.

**Comment by the4thfloor** [comment]
@JakeWharton your [example](https://github.com/google/dagger/issues/73#issuecomment-63278265) does not work for me.

The `DaggerBaseComponent.create().inject(this)` call in `BaseThing` uses the `inject(BaseThing baseThing)`method and not the `inject(RealThing realThing)` so `realThing.bar` is `null`.

I fixed it with a `doIt()`method in `RealThing`.

But I have another question.

How does the code look like if `RealThing` want's to add it's own dependencies? If I create a RealComponent / Modul the `BaseThing` injection doesn't work.

**Comment by the4thfloor** [comment]
I found a way to do it: http://stackoverflow.com/a/30467657/1016472

**Comment by mcfongtw** [comment]
Tried the example posted by @JakeWharton, and member in SubClass was not injected. However, as I explore more in the generated code, that could possibly be done via the following:
`
abstract class BaseThing {
    @Inject
    String foo;

    public BaseThing() {
        this(DaggerBaseComponent.create());
    }

    public BaseThing(BaseComponent component) {
        component.inject(this);
    }
}
class RealThing extends BaseThing {
    @Inject CharSequence bar;

    public RealThing() {
        this(DaggerBaseComponent.create());
    }

    public RealThing(BaseComponent component) {
        component.inject(this);
    }
}

@Module
class BaseModule {
    @Provides
    String provideString() { return "String!"; }
    @Provides CharSequence provideCharSequence() { return "CharSeq!"; }
}

@Component(modules = BaseModule.class)
interface BaseComponent {
    void inject(BaseThing baseThing);
    void inject(RealThing realThing);
}

public class BaseExample {
    public static void main(String... args) {
        RealThing realThing = new RealThing();

        System.out.println("String? => " + realThing.foo);
        System.out.println("CharSeq? => " + realThing.bar);
    }
}
`
This way, `bar` is injected properly.

**Comment by vinhnemo** [comment]
`@Singleton
@Component(modules = {ABC.class})
public interface BaseComponent<T extends Base> {
    void inject(T handler);
}
`
I tried to do something like this but compiled error. Any approach for this? Thanks

**Comment by bcorso** [comment]
@vinhnemo Dagger's job is to generate an implementation of your interface, but Dagger has no idea what `T` is so there's no way for Dagger to know how to "inject" `T`.

You probably want to start a new issue since this seems like a different question, and please add more details about what you're actually trying to accomplish.
