### ISSUE TITLE
@Inject with inheritance

### ISSUE THREAD

**Issue by FrantisekGazo** [google/dagger#731]
Hi,

when you have a class `A`.
```Java
class A {
  @Inject String field1;
}
```
and a class `B` that extends from `A`.
```Java
class B extends A {
  @Inject String field2;
}
```

then the generated `_MembersInjector` classes inject all fields, including the inherited fields.
 
```Java
class A_MembersInjector implements MembersInjector<A> {
  //...
  @Override
  public void injectMembers(A instance) {
    if (instance == null) {
      throw new NullPointerException("Cannot inject members into a null reference");
    }
    instance.field1 = field1Provider.get();
  }
  //...
}
```

```Java
class B_MembersInjector implements MembersInjector<B> {
  //...
  @Override
  public void injectMembers(B instance) {
    if (instance == null) {
      throw new NullPointerException("Cannot inject members into a null reference");
    }
    ((A) instance).field1 = field1Provider.get();
    instance.field2 = field2Provider.get();
  }
  //...
}
```

This means that you cannot inject the superclass `A`.
If you injected in both classes, the `field1Provider.get()` would result in a different instance during each injection.

Would it be possible to change the generated `_MembersInjector` class to inject only fields declared in the class for which it is generated? Or change it so that it would inject only fields that are not initialized yet?

Thanks

**Comment by ronshapiro** [comment]
Why do you need this functionality? Generally it's best to inject in the class that has all the information needed (usually the subclass)

**Comment by FrantisekGazo** [comment]
I'm working on a MVP library that uses dagger2 for injection of presenters and I am using bytecode weaving, so I that I can wrap some code in MembersInjector. Originally I thought that dagger will inject only declared fields, but then I found out that it injects also inherited fields. I modified my library to do it the same way.
So it's ok, you can close this issue.
