### ISSUE TITLE
Dagger & Jersey hk2 clash

### ISSUE THREAD

**Issue by omarkammoun** [google/dagger#733]
Hello,

Thank you for you work, i'am a big fan of dagger2.

I'am want to add Dagger to a new Jersey Application, but it's clashes with hk2.

Is there any clue for a proper solution to use dagger2 with a jersey application (like the one with Guice) ?

Delete all annotation after processing since they are useless at run-time ?
Use dagger with alternative annotations, not the JSR 300 ?
...

Thanks and Regards
Omar

**Comment by ronshapiro** [comment]
None of us are Jersey/hk2 users. Can you add some more info about what you're experiencing?

**Comment by Zhuinden** [comment]
@omarkammoun what is your dependency scope for dagger, dagger-compiler and the jsr annotations?

**Comment by ronshapiro** [comment]
Please feel free to follow up if you have more info, but i'm going to close this as we don't have enough information to be able to understand the issue.
