### ISSUE TITLE
Compilation issue -> Coffemaker Example, mvn 3, java 7, dagger 2.11-rc2, 2.10, 2.9, HEAD-SNAPSHOT

### ISSUE THREAD

**Issue by numerouno979** [google/dagger#745]
**Preface:**
I was trying to set up my development env with eclipse(Luna), maven(3.3), java(1.7) and dagger (2.9 or 2.10).
Followed the documentation as mentioned [here](https://github.com/google/dagger) .
But started running into compilation issues.

Asked for help, and got a prompt response to try 2.11-rc2, (https://github.com/google/dagger/issues/593).
But the issue persisted .

So instead of trying my code, decided to compile and run the 'CoffeMaker' example available [here](https://github.com/google/dagger/tree/master/examples). 
 But the issue still persists.

Below are more details about the env and the errors faced.

**NOTE** : 
I have used HEAD-SNAPSHOT from sonatype for coffeMaker example. 
For reference,  I have checked in my fork [here](https://github.com/numerouno979/dagger/tree/coffeMaker-compilation-issue)
List of changes done from master are
1)  .project, .classpath and .factorypath files : cheked in for reference
2) pom.xml : added repository entry for sonatype

Details of the commit are available [here](https://github.com/numerouno979/dagger/commit/c816b755099e64e810b899babbe6edb627802fb3) and [here](https://github.com/numerouno979/dagger/commit/62a8ce721c3d8177c23fbec0b41872b6c9025038)

It will be really helpful if you can have a look and let me know what went wrong.
**Thanks in advance**   

--------------------------------------------

**Error / Exception Details:** 
-> While building from eclipse, getting below error 
           Errors running builder 'Java Builder' on project 'simple'.
           dagger/internal/codegen/ComponentProcessor : Unsupported major.minor version 52.0

-> While building through command line (mvn clean compile), no error is produced, but no classes are generated either. The generated artifact is also empty.

**Env Details:**
- OS name: "linux", version: "4.4.0-77-generic", arch: "amd64", family: "unix"
- Eclipse Version: Luna Service Release 2 (4.4.2)
- Java : 1.7.0_55, vendor: Oracle Corporation
- Maven : 3.3.9

**Comment by tbroyer** [comment]
Dagger requires a JDK 1.8 since 2.8. You can target a Java 7 runtime, but the compiler must be Java 8-compatible.

**Comment by numerouno979** [comment]
Worked like charm.
I did not see this information in the documentation anywhere.

Thanks alot @tbroyer .
