### ISSUE TITLE
Links to Java Docs Out of Date

### ISSUE THREAD

**Issue by AndrewReitz** [google/dagger#749]
On the README and Website, there are links to the Javadocs which take you to the docs for dagger 2.0. I believe since 2.10 is the latest release it would make the most sense for the docs to link to these rather than 2.0 since a lot has changed in these 10 minor releases. 

I can update and submit a PR, just wanted to check if there was a specific reason for linking to 2.0 instead of the newer docs.

**Comment by ronshapiro** [comment]
I've updated our release process to update this but forgot to update this bug. Thanks for bringing up this issue!
