### ISSUE TITLE
Compatibility with Guava 22.0-android

### ISSUE THREAD

**Issue by pushbit** [google/dagger#753]
It seems that Dagger 2.11 is not compatible with Guava 22.0-android due to the loss of methods like `SetMultimap.forEach`.  When compiling an Android project with both libraries I'm receiving the following error.  Will there be an effort to stay compatible with the new *-android line of Guava releases?

```
Error:Execution failed for task ':app:compileDebugJavaWithJavac'.
> java.lang.NoSuchMethodError: com.google.common.collect.SetMultimap.forEach(Ljava/util/function/BiConsumer;)V
```

**Comment by ronshapiro** [comment]
The annotation processor classpath should be separate from the compile time classpath. I presume you're getting this error because you have a `compile` dep on guava-android; if so, can you add an `annotationProcessor 'com.google.guava:guava:22.0` dep too? If that fixes it, we should update our docs

**Comment by pushbit** [comment]
That does fix it, thanks.

**Comment by tbroyer** [comment]
I think you could also set [`android.defaultConfig.javaCompileOptions.annotationProcessorOptions.includeCompileClasspath`](https://google.github.io/android-gradle-dsl/current/com.android.build.gradle.internal.dsl.AnnotationProcessorOptions.html#com.android.build.gradle.internal.dsl.AnnotationProcessorOptions:includeCompileClasspath) to `false`.

**Comment by pushbit** [comment]
Yes, that works as well.  And it looks like it may be the default option starting in Android Studio/Gradle plugin 3.0.

**Comment by hameno** [comment]
Any idea how to fix this error when using kapt? including guava as kapt "dependency" does not work.

**Comment by hameno** [comment]
Apparently my usage of ```resolutionStrategy.force "com.google.guava:guava:22.0-android"```
 caused the issue for me.

**Comment by galcyurio** [comment]
In my case. 
I followed solution by suggested @ronshapiro .
I added ````annotationProcessor 'com.google.guava:guava:22.0```` too. but It doesn't solved my error.

So I was curious the ````SetMultimap.forEach```` and I searched javadoc but It was only exist in non android guava.

````java
  /**
   * Performs the given action for all key-value pairs contained in this multimap. If an ordering is
   * specified by the {@code Multimap} implementation, actions will be performed in the order of
   * iteration of {@link #entries()}. Exceptions thrown by the action are relayed to the caller.
   *
   * <p>To loop over all keys and their associated value collections, write
   * {@code Multimaps.asMap(multimap).forEach((key, valueCollection) -> action())}.
   *
   * @since 21.0
   */
  default void forEach(BiConsumer<? super K, ? super V> action) {
    checkNotNull(action);
    entries().forEach(entry -> action.accept(entry.getKey(), entry.getValue()));
  }
````

So I modified guava version ````23.0-android```` to ````23.0````.
It was worked.

But It still exsits problem in older than java8 android versions...

**Comment by JakeWharton** [comment]
The processor runs at build time on your computer JVM and doesn't have
anything to do with the Android versions the app runs on. The annotation
processor should not be using the -android version of Guava.

**Comment by galcyurio** [comment]
Thanks. @JakeWharton 
I just added same version before...
silly my brain...

````
guavaVersion = '23.0-android'
````
````
compile "com.google.guava:guava:$rootProject.guavaVersion"
annotationProcessor "com.google.guava:guava:$rootProject.guavaVersion"
````

And I fixed the problem as below.
````
guavaVersion = '23.0'
````
````
compile "com.google.guava:guava:$rootProject.guavaVersion-android"
annotationProcessor "com.google.guava:guava:$rootProject.guavaVersion"
````

**Comment by JakeWharton** [comment]
Yep. That looks great.
