### ISSUE TITLE
Add release notes for 2.11

### ISSUE THREAD

**Issue by Mauin** [google/dagger#754]
In the releases section of this repository the latest release is `Dagger 2.11-rc2`. In JCenter however v2.11 final is already available.

Would be good to also get the release notes for the final version of 2.11 in the GitHub repository.

**Comment by PaulWoitaschek** [comment]
I'm also confused and check this page regularly. Was that release on purpose?

**Comment by renclav** [comment]
agreed

**Comment by ronshapiro** [comment]
Just addedf
