### ISSUE TITLE
Preserve AndroidInjectors<T> across configuration changes

### ISSUE THREAD

**Issue by emmano** [google/dagger#756]
I have been playing around with the `dagger.android` package and realized that each call to `AndroidInjection.inject()` recreates `@Subcomponents` implementations generated by `@ContributesAndroidInjector`. The documentation suggests to call `AndroidInjection.inject()` before `super.onCreate()` of `Activities`, hence providing new instances of the dependencies for the `Activity` in question every time there is a configuration change. This happens even if the `Subcomponents` are scoped since there is no way (that I could find) to get a hold of the `Subcomponent` generated by dagger to manually save it during configuration changes. It is not strange to want to retain dependencies inside Android components during configuration changes. For example, `ViewModels` of  the architecture components library are retained automatically. Presenters are also  good candidates for this.

It looks like retaining dependencies across configuration changes could be supported by modifying the `DispatchingAndroidInjector` to store previously created `AndroidInjectors` in something like a `Map<Class, AndroidInjector<T>>` instead of creating a new one every time `AndroidInjection.inject()` is called. The `AndroidInjector` (the `SubcomponentImpl` in this case) created the first time should to be able to be reused for subsequent injections for the same type of `Activity` subclass.

I created a custom `DispatchingAndroidInjector` that does exactly that and everything seemed to work fine.

Here is a snippet of the interesting code inside `maybeInject()` of `DispatchingAndroidInjector`:

```
AndroidInjector<T> injector = injectorMap.get(instance.getClass());
            if (injector == null){
                injector =
                        checkNotNull(
                                factory.create(instance),
                                "%s.create(I) should not return null.",
                                factory.getClass().getCanonicalName());
                injectorMap.put(instance.getClass(), injector);
            }
            injector.inject(instance);

```
 Would it  be safe to use this approach? Am I missing something here? Can this create memory leaks in some way? If useful is this worth a pull request?

**Comment by JakeWharton** [comment]
This is not safe as the graph contains a binding to the activity instance.
If you want something retained across activities it should live in a higher
scope.

**Comment by emmano** [comment]
That is exactly what I was trying to achieve. Using `@ContributesAndroidInjector` with a custom `@PerActivity` scope to achieve this. The documentation says that you can just do something like this to achieve scoping: 

```
@ActivityScope
@ContributesAndroidInjector(modules = { /* modules to install into the subcomponent */ })
abstract YourActivity contributeYourActivityInjector();
```

The issue is that every time `AndroidInjection.inject()` gets called the Subcomponent generated by the framework gets recreated. Sorry if I am not getting something.

**Comment by ronshapiro** [comment]
This is the same issue as #721. 

There have been some approaches suggested by having a component in between the Singleton level and the Activity level that caches any bindings that should survive configuration change. That's not Dagger's space (from a framework perspective) as many people architect those decisions in widely different ways. There are definitely ways to do this if you want to write some extra code to cache those components.
