### ISSUE TITLE
How can I deal with NoClassDefFoundError while I use Kotlin with Dagger2

### ISSUE THREAD

**Issue by CrazyClownSola** [google/dagger#758]
Hi All:
    who can help me to deal with the problom 
    I want to use Dagger2 with Kotlin
    and when I use annotation @MapKey
   like this 
`
@MapKey(unwrapValue = false)
annotation class SubMapKey(val type: Int, val index: Int)
`
  then build it
 error like this
`Caused by: java.lang.NoClassDefFoundError: com/google/auto/value/AutoAnnotation`
Its means @MapKye use library google/auto
but this library is used for java
how can I deal with this ?
(Ps: I'm so sorry for my bad english)

**Comment by ronshapiro** [comment]
To use `@MapKey(unwrapValue = false)`, you need to add a dependency to https://github.com/google/auto/tree/master/value

**Comment by CrazyClownSola** [comment]
@ronshapiro thanks for response,
but I write this annotation,but alse error with 
`Caused by: java.lang.NoClassDefFoundError: com/google/auto/value/AutoAnnotation`
this problem is [google/auto](https://github.com/google/auto/tree/master/value) can not use in Kotlin
