### ISSUE TITLE
Named dependencies with Kotlin

### ISSUE THREAD

**Issue by vicpinm** [google/dagger#761]
There seems to be an incompatibility with Dagger and Kotlin when using named dependencies. I have prepared an example here: https://github.com/vicpinm/DaggerKotlinTest.

To sum up, I have this module:

    @Module
    class AppModule {

    @Provides @Singleton @Named("test1") fun provider1(): TestObject {
        return TestObject()
    }

    @Provides @Singleton @Named("test2") fun provider2(): TestObject {
        return TestObject()
    }
}

And this component:

    @Singleton
    @Component(modules = arrayOf(AppModule::class))
    interface AppComponent {
         fun inject(mainActivity: MainActivity)
    }

My activity use this component to inject a TestObject instance with:

    @Inject @Named("test1") lateinit var test: TestObject

And I get this error when I execute the project:

TestObject cannot be provided without an @Inject constructor or from an @Provides- or @Produces-annotated method.

The same example seems to work fine in Java.

**Comment by trevjonez** [comment]
If you will inspect the decompiled output you will see that the annotations
don't get applied to the field as expected. Just qualify the named
annotation to fix it. `@field:Named(...)`

**Comment by vicpinm** [comment]
Thanks a lot, its working fine with that.

**Comment by jeffreydelooff** [comment]
What if they are used as parameters to a different dependency such as in the example below:

`@Provides
    @Singleton
    fun okHttpClient(
        @Named("apiInterceptors") apiInterceptors: List<Interceptor>,
        @Named("networkInterceptors") networkInterceptors: List<Interceptor>
    ): OkHttpClient
    {
        return createOkHttpClient(apiInterceptors, networkInterceptors)
    }`
?
With kotlin 1.1.2-4 and dagger 2.11 there still seems to be an incompatibility.

**Comment by tbroyer** [comment]
This is likely #668 here, not related to `@Named`

**Comment by nukatron** [comment]
How about if I inject via the constructor?. 
Do you have any suggestion?. 
Because I can't do it right now.

Thanks.

**Comment by TonyHaddad91** [comment]
What if my module class is written in java but I'm using Kapt, any idea how to solve this?

**Comment by ronshapiro** [comment]
If you end up finding this issue, instead of filling a new one or commenting on an existing one, please use StackOverflow for these types of questions related to Kotlin + annotation processing/kapt
