### ISSUE TITLE
Injection behaviour inconsistent

### ISSUE THREAD

**Issue by bl1b** [google/dagger#763]
tl;dr
Injection of dependency-graph critical objects fails on siblings (cannot inject Activity/Context (nor anything else depending on Activity/Context) into Fragment) which is correct. _\@Provides_ from the same _\@Module_ other than Activity-related succeeds.
----
_BuildModule.java_
```java
@Module
abstract class BuildModule() {
     @ContributesInjector(modules = {ActivityModule.class})
     abstract MyActivity contributeActivity();

     @ContributesInjector(modules = {FragmentModule.class})
     abstract MyFragment contributeFragment();
}
```
_ActivityModule.java_
```java
@Module
abstract class ActivityModule() {
     @Provides
     Context provideContext(MyActivity activity) {
          return activity;
     }

     @Provides
     SomeOtherClass provideOtherClass() {
          return otherInstance;
     }
}
```
_FragmentModule.java_
```java
@Module(includes={ActivityModule.class})
abstract class FragmentModule {
     // some other stuff
}
```
_MyFragment.java_
```java
public class MyFragment extends DaggerFragment {
     @Inject
     SomeOtherClass provideOtherClass; // <--- works

     @Inject
     Context someContext; // <--- doesn't work
}
```
Is that intended behaviour? (let alone the fact that it doesn't make any sense to inject a context into a fragment; this is just for simplicity)

**Comment by ronshapiro** [comment]
Why don't you make the fragment subcomponent a child of the activity subcomponent? If that doesn't help, please try asking on StackOverflow
