### ISSUE TITLE
@Binds doesn't fail when return type isn't assignable from the param type.

### ISSUE THREAD

**Issue by JakeWharton** [google/dagger#769]
I erroneously generated
```java
@Binds
abstract Foo bindFooFactory(GeneratedFooFactory factory);
```
where `GeneratedFooFactory` is:
```java
class GeneratedFooFactory implements Foo.Factory {}
```
Dagger compiled this happily but later failed with a "Foo.Factory cannot be provided without..." error.

It didn't take long to trace down the problem, but I would have expected this when dagger was processing the module (which was in an upstream module) with something like "GeneratedFooFactory cannot be assigned to Foo.".

Using 2.11

**Comment by ronshapiro** [comment]
Hrm, this should be validated here: https://github.com/google/dagger/blob/792adb3fb98a5ea54e421d5f7bec0b38473fa6ad/java/dagger/internal/codegen/BindsMethodValidator.java#L106

Was this in the same compilation? Perhaps both errors were printed but we didn't halt compilation early enough?

**Comment by JakeWharton** [comment]
I should be able to easily repro.

The only interesting part about compilation was that another annotation processor generated the offending module.

**Comment by JakeWharton** [comment]
I believe the module was compiled in one compilation unit and then another consumed it into a component. Trying to repro now...

**Comment by JakeWharton** [comment]
This happens when you don't run the processor over the module when it comes from a library. If you run the processor in the library it fails with the correct assignment check.
