### ISSUE TITLE
Injecting into different maps

### ISSUE THREAD

**Issue by jamesladd** [google/dagger#775]
Dagger is fantastic.

I inject values into a map in my module which is simple. However, how do I inject into a different map in the same module? 

Each of the maps I want to inject take String keys - how can I tell one set of strings to inject into map x with another set of strings to inject map y?

**Comment by jamesladd** [comment]
This is not the same as #701

**Comment by ronshapiro** [comment]
You can use [qualifiers](http://docs.oracle.com/javaee/6/api/javax/inject/Qualifier.html), or have different return types so that you have different map values, hence different maps.
