### ISSUE TITLE
Multibinding doesn't support injecting Map<Class<? extends Foo>, Provider<? extends Foo>>

### ISSUE THREAD

**Issue by cypressious** [google/dagger#776]
When using `@Bind @IntoMap` I am able to inject a `Map<Class<? extends Foo>, Provider<Foo>>` but not a `Map<Class<? extends Foo>, Provider<? extends Foo>>` (note the second wildcard).

I think it should be safe (from a type system POV) to support the latter as well.

See related StackOverflow issues https://stackoverflow.com/questions/44164395/dagger-2-how-to-inject-mapclass-extends-foo-provider-extends-foo/44165488#44165488 and https://stackoverflow.com/questions/44638878/binding-into-map-with-kclass-type/44639432#44639432

**Comment by ronshapiro** [comment]
This has been reported before. Dagger never injects types that are assignable, only the exact type. If it did, we would also have to do it for non-wildcard assignability too, which would be very surprising
