### ISSUE TITLE
dagger.android.DaggerFragment not injecting

### ISSUE THREAD

**Issue by loki666** [google/dagger#777]
DaggerFragment (not support) should @Override void onAttach (Activity activity)

onAttach(Context context) is only called in API 23+

**Comment by JonathanMerritt** [comment]
Have you tried dagger.android.support.DaggerFragment?

**Comment by loki666** [comment]
Yes and it works great for support Fragment.
But for framework Fragment it doesn't works before API23.

**Comment by JonathanMerritt** [comment]
Sorry, read the question too quickly, even deleted the reply in hopes you'd
not have to answer it.

**Comment by loki666** [comment]
https://www.youtube.com/watch?v=-6jmcfbI4n8

still not fixed ?

**Comment by mrkostua** [comment]
`android.app.Fragment` is deprecated in Android P as `DaggerFragment` so it is best to use `DaggerFragment` from support library.
