### ISSUE TITLE
can't display full error log in kotlin

### ISSUE THREAD

**Issue by a1018875550** [google/dagger#778]
I'm use dagger2(v2.11) in kotlin(v1.1.2-5) ,but when I meet error,I don't know how do to
![image](https://user-images.githubusercontent.com/8246218/27324291-5a97f9bc-55d7-11e7-93b7-0239595a0dfb.png)

**Comment by tbroyer** [comment]
“See complete output in console”

Have you looked there?

(BTW, for support questions, I believe the project maintainers would prefer that you use StackOverflow)

**Comment by a1018875550** [comment]
thanks
