### ISSUE TITLE
Cannot resolve symbol 'Dagger_...'

### ISSUE THREAD

**Issue by egor-n** [google/dagger#78]
Android Studio 0.9.3
Gradle 2.1
Gradle Plugin 0.14.2

Is it supposed to be this way? It's red, but compiles with no problem.

![Screeshot](http://i.imgur.com/5pw7ZBD.png)

**Comment by jemshit** [comment]
Now struggling on IntelliJ :/ Added apt plugin, enabled annotation processor, marked generated folder as source. But i can't really see any generated file

**Comment by liminal** [comment]
These are very old instructions. You should not be using apt-plugin today, the functionality is built into the android build plugin (using the keyword annotationProcessor instead of apt in dependencies)

**Comment by jemshit** [comment]
@liminal i am not talking about android, i am using dagger for pure java project on IntelliJ

**Comment by tbroyer** [comment]
@jemshit Assuming `net.ltgt.apt` plugin, make sure you also apply `net.ltgt.apt-idea`. I also suggest delegating build/run actions to Gradle in IntelliJ (beware, this is a global setting, not actually per-project) so you don't even have to configure annotation processing in IntelliJ; you should then set `idea.module.apt.addAptDependencies = false`. See https://github.com/tbroyer/gradle-apt-plugin#intellij-idea, come discuss at https://github.com/tbroyer/gradle-apt-plugin/issues if you still have issues (though please review previous issues, particularly those labelled as `invalid` or `question`)
