### ISSUE TITLE
Android inject all dagger dependencies in class which is also a dependency in a module

### ISSUE THREAD

**Issue by zahid-ali-shah** [google/dagger#780]
I have few modules and main component. One module has a class, I want to inject all dependencies (from all modules) in that class but I don't how know can I do that.

I want something similar to LoginActivity where i used  `AndroidInjection.inject(this);`

In following code I can inject application, gson, Retrofit to MyManager here but how to inject Utils & SharedPreferences (or possibly more) which are in AppModule.

Recently I updated dagger to v2.11, in previous version my code was working as I injected MyManager in NetComponent like this

    ((MyApp) application).getNetComponent().inject(this);

**NetComponent**

    @Singleton
    @Component(modules={AndroidInjectionModule.class, AppModule.class, LoginActivityModule.class, MyModule.class})
    public interface NetComponent {
    
        @Component.Builder
        interface Builder {
            @BindsInstance
            Builder application(Application application);
            @BindsInstance
            Builder helper(DatabaseHelper helper);
            NetComponent build();
        }
        void inject(MyApp myApp);
    }

**AppModule**

    @Module
    public abstract class AppModule {
    
        @Provides
        @Singleton
        Context provideContext(Application application) {
            return application;
        }
    
        @Provides
        @Singleton
        static SharedPreferences providesSharedPreferences(Application application) {
            return PreferenceManager.getDefaultSharedPreferences(application);
        }
    
        @Provides
        @Singleton
        static Utils providesUtils(Application application, SharedPreferences sharedPreferences) {
            return new Utils(application, sharedPreferences);
        }
    }

**MyModule**

    @Module
    public abstract class MyModule {
    
        @Provides
        @Singleton
        static Cache provideGson(Application application) {
            //login to return gson object
            return gson;
        }
    
        @Provides
        @Singleton
        OkHttpClient provideOkHttpClient() {
            HttpLoggingInterceptor logging = new HttpLoggingInterceptor();
            logging.setLevel(HttpLoggingInterceptor.Level.BODY);
            return new OkHttpClient.Builder()
                    .addInterceptor(logging)
                    .build();
        }
    
        @Provides
        @Singleton
        static Retrofit provideRetrofit(Gson gson, OkHttpClient okHttpClient) {
            return new Retrofit.Builder()
                    .addConverterFactory(GsonConverterFactory.create(gson))
                    .baseUrl(CONSTANTS.BASE_URL)
                    .client(okHttpClient)
                    .build();
        }
    
        @Provides
        @Singleton
        static RetrofitManager provideMyManager() {
            //I can inject application, gson, Retrofit to MyManager here
            // but how to inject Utils & SharedPreferences (can be more                       
            //objects) which are in AppModule.
            return new MyManager();
        }
    }

Code in `LoginActivitySubcomponent` and `LoginActivityModule` is standard as per documentation

**Comment by ronshapiro** [comment]
Your question isn't clear to me, but this is better suited as a post on StackOverflow
