### ISSUE TITLE
Scoping with multiple component dependancies

### ISSUE THREAD

**Issue by Byakko** [google/dagger#782]
Our app's current architecture involves multiple libraries, independently compiled into AAR's and assembled where needed.  Each such library contains its own dagger modules and component, and may itself depend on one or more other libraries.  These libraries are built in their own android studio project and also include a sample application.

Thus, we have a need for injection at both the application and the library level, with the ability to chain dagger dependencies and inject from wherever needed.

We have actually achieved all this, and it works great, with one notable issue:  it doesn't appear to be possible to provide scoping within the libraries (which are in turn used for component dependencies in other modules), particularly when multiple dependencies are present.  This is a huge limitation!  Even something as simple as a "once per application / singleton" scoping doesn't appear to be possible.

My query may actually be similar to https://github.com/google/dagger/issues/636 .  Its response of "components are an application's responsibility; libraries should only provide modules" doesn't seem reasonable to me - there is nothing wrong with wanting libraries to be fully functional, self-reliant, and to provide the things they are built for.  Proper handling of scoping from multiple dependencies would be a great feature to have.

**Comment by ronshapiro** [comment]
I think #1075 is identical (IIUC) and is more concise. I'm going to close this for now.
