### ISSUE TITLE
dagger-grpc Docs

### ISSUE THREAD

**Issue by 51systems** [google/dagger#784]
I notice that `dagger-grpc-server` and `dagger-grpc-server-processor` packages are up on maven central. Are there any docs or example projects to check out to learn more about their usage?

Thanks!

**Comment by ronshapiro** [comment]
https://google.github.io/dagger/grpc/

**Comment by ronshapiro** [comment]
Do you want to send a PR to add it to the sidebar?

**Comment by sgammon** [comment]
Would it be possible to add an example of mounting multiple gRPC services on a single `NettyServerBuilder`, or perhaps how to customize the server builder with crypto? Asking for a friend :)

**Comment by ronshapiro** [comment]
@sgammon Our grpc integration isn't something we're so focused on so I don't think we'll get to that. Perhaps this is a better request for the grpc team/project itself?
