### ISSUE TITLE
Don't assume "instance" is the name of the instance being injected when generating MembersInjectors

### ISSUE THREAD

**Issue by ronshapiro** [google/dagger#785]
In `MembersInjectorGenerator` we have some instances of code that assumes that the name of the injected instance will be named `instance`. Instead of relying on that implicit guarantee, we should pass the value through a `UniqueNameSet` and use the returned value to make sure they never collide.

**Comment by ronshapiro** [comment]
Doing this will also allow us to have more descriptive type names (e.g. `MembersInjector<Foo.Builder>` could use `fooBuilder` instead of just `instance`).

**Comment by tbroyer** [comment]
Rather than `UniqueNameSet` you mean [`NameAllocator`](https://square.github.io/javapoet/1.x/javapoet/com/squareup/javapoet/NameAllocator.html) right? 😉
