### ISSUE TITLE
Turn off Logcat during Android Fragment injection

### ISSUE THREAD

**Issue by ktchernov** [google/dagger#790]
When using either `AndroidInjector` or `AndroidSupportInjector`, every time a Fragment is injected, the following is logged via Log.d:

```
An injector for %s was found in %s
```

It would be great if this was either not logged or if there was a way to disable it.

**Comment by ronshapiro** [comment]
Fixed in https://github.com/google/dagger/commit/c19f0c2c5c47557186bc0314c6bf27e736df98c1
