### ISSUE TITLE
The error code cannot be located.

### ISSUE THREAD

**Issue by yubaokang** [google/dagger#792]
When I am in the project use Butterknife and Dagger2 at the same time, if the control id can not find in the layout file, compile time will prompt a pile of dagger automatically generated file can't find the mistake - > symbol errors, but did not locate the real code errors.
![error_file](https://user-images.githubusercontent.com/7115700/27744732-43725a60-5df3-11e7-8878-50cc2f06ef6a.png)
![inkedinkedh5drgs1_smk1wpud98 mon3_li](https://user-images.githubusercontent.com/7115700/27744752-5c6fc3e0-5df3-11e7-8515-1be761575dd5.jpg)

**Comment by ronshapiro** [comment]
Duplicate issue of #306.
