### ISSUE TITLE
Resolve '*is bound multiple times' with scope specific @Named() annotation?

### ISSUE THREAD

**Issue by JonathanMerritt** [google/dagger#793]
I have a minimal example here:
```
interface Number {}

  class One implements Number {
    @Inject OneObject object;
    @dagger.Module abstract class Module {
      @OneScope @Binds Number number(One one);
    }
  }

  @OneScope class OneObject {
   @Inject OneObject(Number number) {}
  }

  class Two implements Number {
    @Inject TwoObject object;
    @dagger.Module abstract class Module {
      @TwoScope @Binds Number number(Two two);
    }
  }

  @TwoScope class TwoObject {
    @Inject TwoObject(Number number) {}
  }
```

This will cause the titles exception. And can be fixed by adding a simple `@Named("One or Two")` annotation for the ins and outs. Causing a little bit of repetitiveness.  

So I was wondering since the scopes and names can/will be identical, is this a possible use case that the library can provide a solution for? 

I understand this is something the named annotation will fix, just curious if it something you've looked into or not. So no real rush.

Thanks.

**Comment by ronshapiro** [comment]
Scopes and qualifiers are intentionally separate concepts. You wouldn't always want one to imply the other either, so the extra few characters is not boilerplate IMO, it helps create much clearer code.

**Comment by JonathanMerritt** [comment]
@ronshapiro That's totally fair. Thanks for the response.

Also just in case I wasn't clear or I'm not fully understanding your answer, I didn't mean to replace either annotation, only that when a conflict arises, if the scopes are unique then automatically add the qualifier.

No clue on how that would need to be done however. Lol. Only a thought. Thanks again.

**Comment by ronshapiro** [comment]
I'm sure we *could* do that, but that would definitely be confusing to explain as a feature.

**Comment by JonathanMerritt** [comment]
I could barely get it across and I thought of it, I completely hear what you're saying.

Probably best to be done on some sort of custom graph anyway. Appreciate the time.
