### ISSUE TITLE
Allow Fragments to depend on Activity Subcomponents when using ContributesAndroidInjector

### ISSUE THREAD

**Issue by ktchernov** [google/dagger#796]
Consider the below example:

```

@Module
abstract class BuildersModule {
    @ActivityScope
    @ContributesAndroidInjector(modules = ModuleA.class)
    abstract ActivityA contributeActivity();

    @ActivityScope
    @ContributesAndroidInjector
    abstract FragmentA contributeFragmentA();

    @ActivityScope
    @ContributesAndroidInjector(modules = ModuleB.class)
    abstract FragmentB contributeFragmentB();
}

```

The two Fragments are children of ActivityA. We don't have an easy means of sharing Activity-scoped bindings between the Activity and the Fragments because all the generated subcomponents hang off ApplicationComponent.

It would be great if we could : 1) share ActivityA's component with FragmentA 2) Specify FragmentB's component as a Subcomponent of ActivityA's component.

**Comment by ronshapiro** [comment]
You can put the `@ContributesAndroidInjector` methods in their own module, and then do  `@ContributesAndroidInjector(modules = FragmentBModule.class)`

**Comment by ktchernov** [comment]
That still generates the Fragment components as subcomponents of `ApplicationComponent` rather than `ActivityAComponent` - which means there isn't an easy way to share `@ActivityScope`d objects between thew activity and two fragments.

**Comment by PhilGlass** [comment]
```java
@Module abstract class FragmentsModule {
    @ContributesAndroidInjector
    abstract FragmentA contributeFragmentA();

    @ContributesAndroidInjector(modules = ModuleB.class)
    abstract FragmentB contributeFragmentB();
}
```

```java
@Module abstract class ActivityModule {
    @ContributesAndroidInjector(modules = ModuleA.class, FragmentsModule.class)
    abstract ActivityA contributeActivityA();
}
```

If you structure your modules like this (with `ActivityModule` installed in your `ApplicationComponent`), the generated fragment injectors will be subcomponents of your activity component & will have access to bindings declared in `ModuleA`.

**Comment by ktchernov** [comment]
Thank you, that works. I wonder if there should be an example in the docs (or elsewhere) that demos how to accomplish this behaviour? It's not immediately obvious and I suspect it's a common set up.

**Comment by vestrel00** [comment]
This article provides a complete guide to using Dagger.Android (2.11) dependency injection framework with support for @singleton, @peractivity , @perfragment, and @perchildfragment scopes: https://proandroiddev.com/how-to-android-dagger-2-10-2-11-butterknife-mvp-part-1-eb0f6b970fd

You can take a look at this gist for a quick overview: https://gist.github.com/vestrel00/64be913f954989fe52c674247e093218

**Comment by ohjames** [comment]
The fragment can outlive the activity no? So if the fragment component is a subcomponent of the view's and the fragment injects a value scoped from the activity then the activity is destroyed its component reference will be kept alive?

**Comment by athornz** [comment]
Does the above approach still work? I've tried to implement it and dagger complains that it can't find an android injector for the fragments.

Are there any extra steps needed to get this to work?

**Comment by Eipeks** [comment]
@PhilGlass you're a life saver. 
Spent hours trying to figure this out.

**Comment by RevoltEnergy** [comment]
> ```java
> @Module abstract class FragmentsModule {
>     @ContributesAndroidInjector
>     abstract FragmentA contributeFragmentA();
> 
>     @ContributesAndroidInjector(modules = ModuleB.class)
>     abstract FragmentB contributeFragmentB();
> }
> ```
> 
> ```java
> @Module abstract class ActivityModule {
>     @ContributesAndroidInjector(modules = ModuleA.class, FragmentsModule.class)
>     abstract ActivityA contributeActivityA();
> }
> ```
> 
> If you structure your modules like this (with `ActivityModule` installed in your `ApplicationComponent`), the generated fragment injectors will be subcomponents of your activity component & will have access to bindings declared in `ModuleA`.

hi! I tried to implement this approach but faced the problem which I described in this [question](https://stackoverflow.com/questions/57486921/dagger-2-injecting-fragment-into-activity-error-dagger-missingbinding) and the additional context in the comments to it.. please help me to understand the reason of that issue. thanks

**Comment by fondesa** [comment]
@athornz Yes, it does, you need to implement `HasAndroidInjector` in your `Activity` if it doesn't extend `DaggerActivity`.
