### ISSUE TITLE
dagger.android not work with kotlin

### ISSUE THREAD

**Issue by fantasyRqg** [google/dagger#797]
use the java code write dagger part ,every thing is ok. But use kotlin can not compile
 is there any workaround for this error ?
`@ContributesAndroidInjector` report `compilation errors or a circular dependency`

```

    compileSdkVersion 26
    buildToolsVersion "26.0.0"
    ext.kotlin_version = '1.1.3'
    classpath 'com.android.tools.build:gradle:3.0.0-alpha5'

```

here is code for[ dagger.android](https://google.github.io/dagger//android.html)

```kotlin

@Module(subcomponents = arrayOf(MainActivitySubComponent::class))
abstract class MainActivityModule {

    @Binds
    @IntoMap
    @ActivityKey(MainActivity::class)
     abstract fun bindMainActivityInjectorFactory(builder: MainActivitySubComponent.Builder): AndroidInjector.Factory<Activity>
    
    @Binds
    abstract fun bindMainPresenter(mainPresenterImpl: MainPresenterImpl): MainContract.Presenter

    @Binds
    abstract fun bindMainView(mainActivity: MainActivity): MainContract.View

}

@Subcomponent
interface MainActivitySubComponent : AndroidInjector<MainActivity> {
    @Subcomponent.Builder
    abstract class Builder : AndroidInjector.Builder<MainActivity>()
}

@Singleton
@Component(modules = arrayOf(AppModule::class/*,AndroidInjectionModule::class*/, MainActivityModule::class))
interface AppComponent {
    fun inject(app: App)
}


class App : Application(), HasActivityInjector {
    @Inject lateinit var dispatchingActivityInjector: DispatchingAndroidInjector<Activity>

    override fun activityInjector(): AndroidInjector<Activity> {
        return dispatchingActivityInjector
    }


    val component: AppComponent by lazy {
        DaggerAppComponent.builder()
                .appModule(AppModule(this))
                .build()
    }

    override fun onCreate() {
        super.onCreate()
        component.inject(this)
    }
}
```
report error like this

```

e: /Users/rqg/StudioProjects/Open163Tv/app/build/tmp/kapt3/stubs/debug/rqg/fantasy/open163/tv/di/module/MainActivityModule.java:11: error: @Binds methods must have only one parameter whose type is assignable to the return type
e: 

e:     public abstract dagger.android.AndroidInjector.Factory<android.app.Activity> bindMainActivityInjectorFactory(@org.jetbrains.annotations.NotNull()
e:                                                                                  ^
e: /Users/rqg/StudioProjects/Open163Tv/app/build/tmp/kapt3/stubs/debug/rqg/fantasy/open163/tv/di/component/AppComponent.java:4: error: rqg.fantasy.open163.tv.di.module.MainActivityModule has errors
e: 

e: @dagger.Component(modules = {rqg.fantasy.open163.tv.di.module.AppModule.class, rqg.fantasy.open163.tv.di.module.MainActivityModule.class})
e: ^

```

**Comment by tbroyer** [comment]
I think you need to declare `bindMainActivityInjectorFactory`'s return type as `AndroidInjector.Factory<out Activity>` to get the Kotlin equivalent to Java's `AndroidInjector.Factory<? extends Activity>`. See https://kotlinlang.org/docs/reference/generics.html#use-site-variance-type-projections

**Comment by fantasyRqg** [comment]
@tbroyer I tried with `<out Activity >`, compiler gives me another error `rqg.fantasy.open163.tv.business.main.MainActivity cannot be provided without an @Inject constructor or from an @Provides-annotated method. This type supports members injection but cannot be implicitly provided.`
I modify `bindMainView` to `@Binds abstract fun bindMainView(mainActivity: @JvmSuppressWildcards MainActivity): MainContract.View`

with or without `@JvmSuppressWildcards` graph cannot get MainActivity instance

**Comment by fantasyRqg** [comment]
@tbroyer Do you know how to debug dagger2 ? I want to kwon what class type Dagger2 hold when it build graph

**Comment by tbroyer** [comment]
I don't know the details of `dagger.android`, but shouldn't your bind methods for presenter and view be in the subcomponent? (in a module used by the subcomponent)

To debug an annotation processor, you need to debug the compiler; in your case probably debug the Gradle process.

**Comment by fantasyRqg** [comment]
I implement upon class graph pure java , work fine. So I thought maybe  type cast problem between kotlin and java.

**Comment by ronshapiro** [comment]
This forum isn't for questions.

Like @tbroyer said, your issue is likely with the generics, and with how your modules are organized. If you have more questions, please post on StackOverflow.

**Comment by fantasyRqg** [comment]
Finally fix this problem , problem is caused by scope.  @ronshapiro 
project is [here](https://github.com/fantasyRqg/Open163Tv)
