### ISSUE TITLE
Kind of enhancement. Annotation naming etymology.

### ISSUE THREAD

**Issue by paolop** [google/dagger#803]
Hi all,
I know this is not  the appropriate place for this kind of questions. Sorry for that.

I'm curious about the annotations naming etymology. I'm a quite new Dagger2 user and I'm wondering why names such as @Module or @Component are used. I performed a quick search with no results.
These names seem to me not very meaningless/memorable (surely my ignorance), but from a learner perspective I would have expected something more actionable. For example a @Module is meant to provide dependencies to a certain @Component and a name like @Provider or the like IMHO would be semantically more appropriate. To a lesser extent, the @Component annotation too could have had a meaningful name. If I'm not wrong a component defines the DAG of dependencies (or part of it) so I would have expected some name closer to DAG terminology (no idea here :)).

I will be grateful if someone could clarify this, and sorry again if this could seem a dumb argument. Surely I'm missing some background knowledge.

Paolo

**Comment by JakeWharton** [comment]
Module came from Dagger 1 which came from Guice which is older than when I
started paying attention to such things.

Component was debated by a bunch of people in and around the project and we
couldn't come up with anything better. In Dagger 1 it's called an
ObjectGraph. In Guice it's called an Injector.

**Comment by tbroyer** [comment]
In GIN (Guice for GWT), where [it looks almost the same](https://github.com/tbroyer/gwt-maven-archetypes/commit/667955ca5243f480a2cc106c324d12c0ed6a783b#diff-d521da1045ea04ae1fd7dd0e1938945f), it's called a _Ginjector_.

**Comment by paolop** [comment]
@JakeWharton @tbroyer thanks for the clarification. 
Naming is very hard, and from the outside the annotation names may sound not appropriate, but I'm sure devs working on it have their good reasons. 
Just my two cents: module -> "provider" or "DepProvider" (for dependencies provider) and component -> "DagComponent"  or, more closer to DAG terminology, "DagDepRegion" (for DAG dependencies region).
Maybe it is not really a problem related to the names of the annotations (it is only a matter of time and practice), but it's simply related to the docs. Docs could stress more the relationships between Dagger and DAGs given that 90% of users have a CS background. 
A simple statement somewhere explaining the analogy with DAGs IMO would help. Something like: "A @Module (i.e., a set of dependencies == vertices of the DAG) @Provides some dependencies to a @Component (i.e., a region of a DAG or the DAG itself)". A class diagram accompanying the coffeemaker example would also help to visualize the core concepts that now at first sight can seem a little abstract. I know Dagger is more complex than that but I think this would help users grasp core concepts quickly.
