### ISSUE TITLE
How to release something in a instance who's reference hold by component?

### ISSUE THREAD

**Issue by Kilnn** [google/dagger#805]
I have a EcgDataRepository cache some data like this " List<EcgEntity> caches ". 
Now i want release the cache when Application#onTrimMemory(int) is triggered. May be i can use MyComponent#provideEcgDataRepository() to get this instance, but i don't want do this , because the EcgDataRepository only create in few activities,  it might not be  instantiated when onTrimMemory(int) is  triggered.
So, how can i fix it?

**Comment by ronshapiro** [comment]
The code in the `dagger.releasablereferences` and `dagger.android` packages has a great solution for this. Check out the documentation on Releasable References for more.

**Comment by Kilnn** [comment]
@ronshapiro oh, thanks
