### ISSUE TITLE
Documentation URL broken - https://google.github.io/dagger//2.11/

### ISSUE THREAD

**Issue by jaredsburrows** [google/dagger#806]
1. Go to https://google.github.io/dagger/
2. Click on "2.11 Javadoc" -> fails to resolve https://google.github.io/dagger//2.11/

**Comment by NightlyNexus** [comment]
looks like most of the links on the side bar have a double slash.

**Comment by linuxuser586** [comment]
I created a fix in https://github.com/google/dagger/pull/812

**Comment by ronshapiro** [comment]
This was fixed recently
