### ISSUE TITLE
Android Studio 3.0 Canary 6 rebuild causes ClassNotFound for the DaggerComponent

### ISSUE THREAD

**Issue by Mordag** [google/dagger#811]
Pre-Android Studio 3.0 it was possible to rebuild the project but the IDE would still recognize the old DaggerComponent classes. Starting with Android Studio 3.0 Canary 6 this is not working anymore somehow. Every time I want to rebuild the project, I have to remove any references to the DaggerComponent (in my project called "DaggerAppComponent"). Is that intended, an issue created by Android Studio or am I missing something? Addition to the latest Android Studio preview I am using the latest version of Kotlin (1.1.3-2).

**Comment by mttmllns** [comment]
Seeing this as well.

**Comment by gk5885** [comment]
Sounds like an issue that you should file with Android Studio.

**Comment by Mordag** [comment]
I've created an issue here: https://issuetracker.google.com/issues/63711609

**Comment by hoanghiephui** [comment]
Yes, I also like you

**Comment by Mordag** [comment]
I was able to fix the bug, take a look here: https://issuetracker.google.com/issues/63711609#comment4
This issue caused by Kotlin.

**Comment by PrathameshKesarkar** [comment]
I am getting this issue on AS 2.3.2 and this is happening on every single Project . I am able to import the class but when I try to build . It is showing Component not found

**Comment by asbadve** [comment]
having same issue.
