### ISSUE TITLE
Issue with @Named on nested Subcomponent

### ISSUE THREAD

**Issue by edsonduarte1990** [google/dagger#813]
I've managed to build a scheme using nested subcomponents and its working great but when I try to get some @Named property from one of the upper subcomponents, dagger complains saying that it cannot be provided without an @Provides-method even thought it provides some other properties from the same parent...  sorry if this seems vague but I'm not sure of what is the issue here.

**Comment by JakeWharton** [comment]
Csn you provide a failing test or sample that reproduces what you're seeing?

**Comment by edsonduarte1990** [comment]
sorry, it seems that I've misunderstood some concepts because when I try to put some small sample together everything goes wrong... I'm trying to have two singleton-scoped classes that manage two nested sub-scopes:

```java
@Singleton // also tried other scopes
class MySubScopeManager {

    @Inject Context context; // comes from root component
    @Inject Integer i; // comes from subcomponent
    @Inject @Named("subcomponent") String s; // comes from subcomponent

    private MySubcomponent component;

    @Inject
    MySubScopeManager(MySubcomponent.Builder builder) {
        component = builder.build();
        component.inject(this);
    }
}
```

```java
@Singleton // also tried other scopes
class MySubSubScopeManager {

    @Inject Context context; // comes from root component
//    @Inject Integer integer1; // should come from subcomponent
//    @Inject @Named("subsubcomponent") Integer integer2; // should come from subsubcomponent
//    @Inject @Named("subcomponent") String string1; // should come from subcomponent
//    @Inject String string2; // should come from subsubcomponent

    private MySubSubcomponent component;

    @Inject
    MySubSubScopeManager(MySubSubcomponent.Builder builder) {
        component = builder.build();
        component.inject(this);
    }
}
```

whenever I try to uncomment one of the above lines dagger complains about the @provides-methods...

**Comment by ronshapiro** [comment]
Try putting this in a scope that is applied on your subcomponent. If that doesn't help, please try stackoverflow for this question.
