### ISSUE TITLE
Duplicate entry: xxx_MembersInjector.class in Android app

### ISSUE THREAD

**Issue by NamekMaster** [google/dagger#814]
I use dagger2 and dagger-android in my app. I have a BaseFragment in a base module, and some xxxFragment extends this BaseFragment in other modules. When I try to compile my code, I found there are 3 BaseFragment_MembersInjector.class in the same package in those modules, and I got an error : duplicate entry BaseFragment_MembersInjector.class.
How can I resolve this problem?

**Comment by tbroyer** [comment]
Are you compile the "base module" with Dagger annotation processor too?
IIUC, this would generate the `BaseFragment_MembersInjector` in that base module, and when compiling other modules, the Dagger processor won't have to generate it as it'll find it in the classpath already.

IIUC, in previous versions of Dagger you would have had a warning telling you that you should have compiled your base module with the Dagger processor, and that Dagger would then generate some class that it shouldn't have to, when compiling the other modules.

**Comment by NamekMaster** [comment]
There is MyDaggerFragment_MembersInjector generated in my base module because I copied MyDaggerFragment from dagger-android and my BaseFragment extends this class, maybe I should move those @Inject codes to that BaseFragment?

**Comment by ronshapiro** [comment]
This is a build issue. I'd recommend checking StackOverflow or your build system's issue tracker

**Comment by anlijiu** [comment]
@NamekMaster  Hi, I met exactly same problem , do you resolve it ?
