### ISSUE TITLE
How to create and inject nested fragments in dagger 2.11

### ISSUE THREAD

**Issue by Axrorxoja** [google/dagger#817]
Hi, I'm use last 2.11 version dagger, and how to connect nested fragment subcomponent their father fragment subcomponents

**Comment by vestrel00** [comment]
This article provides a complete guide to using Dagger.Android (2.11) dependency injection framework with support for @Singleton, @PerActivity , @PerFragment, and @PerChildFragment scopes: https://proandroiddev.com/how-to-android-dagger-2-10-2-11-butterknife-mvp-part-1-eb0f6b970fd

You can take a look at this gist for a quick overview: https://gist.github.com/vestrel00/64be913f954989fe52c674247e093218

**Comment by rodriigomedeiros** [comment]
@vestrel00 using your "framework", how do I add fragments in the stack? For example: Fragment1 -> Fragment2 -> Fragment3

**Comment by vestrel00** [comment]
@rodriigomedeiros, I answered it in https://github.com/vestrel00/android-dagger-butterknife-mvp/issues/53#issuecomment-332291364
