### ISSUE TITLE
DaggerInjector not found when using Android 2.3 with gradle:2.5.0-alpha-preview-02

### ISSUE THREAD

**Issue by Muddz** [google/dagger#823]
In my `App.class` I have this in `onCreate()`

     injector = DaggerInjector
                .builder()
                .appModule(new AppModule(this))
                .build();

Which usually works but in `Android Studio 2.3 Canary 8` with Gradle version: `2.5.0-alpha-preview-02` the `DaggerInjector` class is never found. If I use `Gradle 2.3.3` then everything work (also in Android 2.3)

**My stackstrace says:** 

    Error:(8, 47) error: cannot find symbol class DaggerInjector
    Error:(45, 20) error: cannot find symbol variable DaggerInjector

**Comment by ronshapiro** [comment]
Please ask questions on StackOverflow

**Comment by Muddz** [comment]
@ronshapiro I have: https://stackoverflow.com/questions/45413860/daggerinjector-not-found-when-using-android-2-3-with-gradle2-5-0-alpha-preview
