### ISSUE TITLE
Component creation in Kotlin not compiling

### ISSUE THREAD

**Issue by NightlyNexus** [google/dagger#825]
I have a class like:
```kotlin
class NotifiqueApplication : Application() {
  @Inject lateinit var str: String
  override fun onCreate() {
    super.onCreate()
    //DaggerAppComponent.create().inject(this)
  }
}
```
This compiles fine, and the DaggerAppComponent is generated.
Then, uncommenting the above commented line, compiling Kotlin fails with DaggerAppComponent as unresolved, not generated.

I can upload the tiny reproducible sample app if it's not clear.
I don't think I need kapt for this.

**Comment by artem-zinnatullin** [comment]
Kapt is required for this code to give Dagger way to analyze @Inject in
your NotifiqueApplication class.

DaggerAppComponent is generated because you've probably written it in Java.

Please try adding kapt!

**Comment by NightlyNexus** [comment]
I can `@Inject` fields and constructors in other Kotlin classes fine when the above class is in Java.
Dumb question: what makes this case special?

**Comment by ronshapiro** [comment]
Can you move this over to StackOverflow? This seems to be more of a question than a bug
