### ISSUE TITLE
ActivitySubcomponentImpl can be static

### ISSUE THREAD

**Issue by NightlyNexus** [google/dagger#826]
I have an AppComponent with a module with a method `@ContributesAndroidInjector abstract MyActivity contributeMyActivity();`

The generated DaggerAppComponent has an inner class MyActivitySubcomponentImpl that can be static and doesn't need a reference to DaggerAppComponent.
Error Prone is warning about it.

Not a big deal, since I can disable warnings in generated code, so close it if it's not worth changing.

**Comment by vanniktech** [comment]
Possible duplicate of #601

**Comment by NightlyNexus** [comment]
oops, yes it is. i did search but missed it, sorry!
