### ISSUE TITLE
Add ability to elide empty module that only declares subcomponents.

### ISSUE THREAD

**Issue by NightlyNexus** [google/dagger#827]
Sometimes (rarely?), you have an empty module that only serves to declare subcomponents.
```java
@AppComponent(modules = AppComponent.Module.class)
interface AppComponent {
  // AppComponent.Builder ...

  @dagger.Module(subcomponents = MySubcomponent.class) abstract class Module { }
}
```
[A tiny, complete example](https://gist.github.com/NightlyNexus/82c8138816c6b4db9afd7785f3396f47)

It would be nice to add a way not to have to create this unused class.

But, I don't know if there's any other place to declare these subcomponents without duplicating APIs and being confusing.
This might be a rare use case and not worth effort.

**Comment by ronshapiro** [comment]
So far we've been of the opinion that this simple module is fine and not worth aliasing on component definitions. It's nice because it allows for composition of declared subcomponents too :)
