### ISSUE TITLE
Missing Dagger Android Processor gives cryptic error message.

### ISSUE THREAD

**Issue by digitalbuddha** [google/dagger#828]
I forgot to include 
`annotationProcessor 'com.google.dagger:dagger-android-processor:2.11'` and then spent 4 hours trying to figure out where my circular dependency was. It would be beneficial to have a better error message when the new processor is missing and `@ContributesAndroidInjector` doesn't properly generate the appropriate classes

    Error:(29, 8) error: dagger.internal.codegen.ComponentProcessor was unable to process this interface because not all of its dependencies could be resolved. Check for compilation errors or a circular dependency with generated code.

**Comment by ronshapiro** [comment]
I spent a little time thinking about how to present a good error here. I'm not sure yet, because where we check for `@CAI` is pretty far from where we get a `Messager`.

**Comment by ronshapiro** [comment]
This might be a good location: https://github.com/google/dagger/blob/e05f921812772eba98ef3b4a1ab6b301f3b25e26/java/dagger/internal/codegen/ModuleValidator.java#L143
