### ISSUE TITLE
Question: Could @Provides be applied to a default method?

### ISSUE THREAD

**Issue by JonathanMerritt** [google/dagger#833]
I have an interface `@Module`.

`
@Module public interface MyModule<T> {
  @Binds Object object(T t);
}
`

This allows me to use generics. and works great for `@Binds`. 

However when I attempt to have a default method, with `@Provides`. It fails at runtime, directing to the provides factory in question. It looks half complete, and asks for an instance of `MyModule` that never gets set.

I realize this is "Off label" in lot of ways so don't worry about a long explanation, nothing or a simple no will be plenty for me. Just curious if this is at all possible to achieve?

However if anyone is interested and needs more information, let me know. Just didn't want to clutter the question if it's a non starter etc...

Jon.

**Comment by ronshapiro** [comment]
`default` methods are abstract, which is probably where Dagger is getting tripped up. 

Can you explain more about why you want to use default methods though? That sounds like a smell. You can use `static` methods in an interface if you're using Java 8

**Comment by JonathanMerritt** [comment]
> Can you explain more about why you want to use default methods though? That sounds like a smell. You can use static methods in an interface if you're using Java 8

I had absolutely no idea that you could use `static` methods in an interface. The only reason I thought to use `default`s was because I thought it was the only way.

I've attempted to do it with `static`s, unfortunately it doesn't seem to work. Fails on compile though.

This is a bare example of what I'm trying..

```
@Module public interface ActivityModule<A extends Activity> {
  @Binds Activity activity(A activity);
  
  @Provides static Bundle provideBundle(Activity activity) {
    return activity.getIntent().getExtras();
  }
}
```

The specific activities `@Module` implements this. Avoiding the need to add an extra activity module, that would need to be declared for each activity as well.

Thanks for the response. And it's unbelievable I didn't already know about using `static` methods, but I'm very glad to know it now.

**Comment by ronshapiro** [comment]
What error are you getting on compilation? 

Another option is to just have a `@BindsInstance` method on the builder which binds `YourActivity` to `Activity` and always reuse the same activity module. then you don't need generics either.

**Comment by JonathanMerritt** [comment]
> What error are you getting on compilation?

`Error: ...Bundle cannot be provided without an @Provides-annotated method...`

It does create a `Factory` however.

> Another option is to just have a @BindsInstance method on the builder which binds YourActivity to Activity and always reuse the same activity module. then you don't need generics either.

I'm using `@ContributesAndroidInjector`. So my activities don't have builders or anything but a module.

The module will implement my interface module(Which only `@Binds` it's base), and also `includes` another module for anything it needs to provide(Intent extras..).

This way activity modules only need to have things specific to them, or if they have nothing to provide, their module is essentially a single line.

Example:

```
@Module(includes = ActivityModule.class) 
abstract class MainActivityModule implements BaseActivityModule<MainActivity> {
}
```

My hope was to somehow move the provides module into the interface module or vice versa.
