### ISSUE TITLE
@ClassKey multibinding in Module with package-private visibility breaks compile when Component in other package includes it

### ISSUE THREAD

**Issue by jnlopar** [google/dagger#836]
It looks like the processor is making the provider method for the multibinding in the component itself with references to individual `ClassKey` keys and is not taking into account visibility of the classes referenced. Internal cl/164618904 demonstrates a working and broken example with the `@ClassKey(Foo.class)` in the module public and package-private respectively.

Steps to repo:

1) Make a module which provides an `@IntoMap @ClassKey(Something.class)` multibinding, where `Something` is package-private to the module.
2) Make a component in a different package including the module which exposing the multibound map. I demonstrated with a very simple `Map<Class<?>, String>` map.
3) Try to build it. :(

**Comment by ronshapiro** [comment]
Great find! I just created internal cl/164780502 to cover this

**Comment by vanniktech** [comment]
#596 might also be related to this and could potentially get fixed with this.

**Comment by ronshapiro** [comment]
Nope, that's totally different.
