### ISSUE TITLE
DaggerApplication's use of covariant injector methods makes testing harder

### ISSUE THREAD

**Issue by nborodikhin** [google/dagger#839]
Injectors for both platforms and support components implemented by `DaggerApplication` classes all return specific type `DispatchingAndroidInjector<T>` instead of `AndroidInjector<T>`.

Dagger does not make use of this narrower return type, so there is no real benefit from returning covariant type instead of the base one.

On the other hand, as `DispatchingAndroidInjector` is a final class, there is no easy way to subclass real application and provide mock implementation of just activity injector.  Normally, there should not be need of that anyway, but while working on legacy code you might have a indirect dependencies on concrete application type.

Example:
* `FooApplication` has some application-wide state
* `FooActivity` uses some utility methods, providing them an context
* utility methods access the global state, casting application context to `FooApplication`
I know in ideal world there should be no such deeply hidden dependencies, but I'm taking one step at a time.

```
@RunWith(RobolectricTestRunner::class)
@Config(application = FooActivityTest.App::class)
class FootActivityTest {
    class App : FooApplication() {
        lateinit var injector: FooActivity_MembersInjector

        override fun activityInjector(): AndroidInjector<Activity> = AndroidInjector {
            activity -> if (activity is Test_FooActivity) {
                    injector.injectMembers(activity)
                }
        }
        ...
    }

    @Before
    fun setupMocks() {
        val injector = FooActivity_MembersInjector(...)
        (RuntimeEnvironment.application as App).injector = injector
    }
   ...
}
```

**Comment by ronshapiro** [comment]
This is by design. If you need to have more control over DaggerApplication, we recommend creating your own type and using DaggerApplication as a guide for what you should do. It's intentionally simple so that you can take what you need/ignore what you don't.
