### ISSUE TITLE
java.lang.NoClassDefFoundError: dagger/Provides

### ISSUE THREAD

**Issue by ljackChen001** [google/dagger#843]
Android Studio 3.0 Beta 2   Used Dagger2 2.11 Appeared  
Error:Execution failed for task ':arms:compileDebugJavaWithJavac'.
> java.lang.NoClassDefFoundError: dagger/Provides

it's normal  in Android Studio 2.3.3 but  not normal at Android Studio 3.0 。Please help me to solve this problem
![qq 20170816131707](https://user-images.githubusercontent.com/13534229/29348302-43c28a1a-8285-11e7-919a-53e95dbcb542.png)

**Comment by ronshapiro** [comment]
File a bug for Android Studio or ask on StackOverflow please. This isn't a dagger bug

**Comment by xiaobailong24** [comment]
The same error with me:
https://stackoverflow.com/questions/45905863/as3-java-lang-noclassdeffounderror-dagger-provides

**Comment by xiaobailong24** [comment]
@ljackChen001 
Got solution from: 
https://developer.android.com/studio/build/gradle-plugin-3-0-0-migration.html

**Comment by Saturdaycong** [comment]
I had the same problem,hava you solved it yet?thank you
