### ISSUE TITLE
Not able to inject fragment/activity with @ContributesAndroidInjector 

### ISSUE THREAD

**Issue by Chrylo** [google/dagger#844]
Hey guys, I wanted to use @ContributesAndroidInjector for most of our fragments/activites. Before this, we used the "normal" way with components etc.:

```
@Binds
@IntoMap
@FragmentKey
...
```

A fragment module has the following provides method:

```
 @Provides
 static DataChangedCallback provideDataChangedCallback(MyFragment myFragment)
 {
     return new DataChangedCallback(Fragment);
 }
```

When using the @ContributesAndroidInjector way, the parameter MyFragment cannot be injected. This works when using the "not pro tip" from: https://google.github.io/dagger/android

Basic structure is the same as in this tutorial: https://proandroiddev.com/dagger-2-android-modules-e168821cfc57

This is useful when the fragment implements an interface which is given to a provided dependency.

**Comment by ronshapiro** [comment]
Please post all questions on StackOverflow
