### ISSUE TITLE
Specifying dependency components should be optional when creating a component builder

### ISSUE THREAD

**Issue by ansman** [google/dagger#845]
Often I want to inject something dynamic in my component and then I use `@BindsInstance` but it's pretty annoying having to a method for each dependency component as well as a build method.

Here is an example:
```java
@Component(dependencies = SingletonComponent.class, modules = SomeModule.class)
public interface SomeComponent {
    void inject(SomeObject object);

    @Component.Builder
    interface Builder {
        @BindsInstance
        Builder someParameter(SomeParameter someParameter);
        Builder singletonComponent(SingletonComponent component);
        SomeComponent build();
    }
}
```

It would be nice if the setter for `singletonComponent` and the `build` method was optional making it like this:
```java
@Component(dependencies = SingletonComponent.class, modules = SomeModule.class)
public interface SomeComponent {
    void inject(SomeObject object);

    @Component.Builder
    interface Builder {
        @BindsInstance
        Builder someParameter(SomeParameter someParameter);
    }
}
```

The `DaggerSomeComponent.builder()` could just return the concrete type rather than the interface type. I understand there are reasons for having the builder interface be complete but it's would help reduce the boilerplate when using `@BindsInstance`

**Comment by ronshapiro** [comment]
If you'd like, you can choose to write a code generator that generates the base implementation for your builder, and then you can extend that interface. We choose to generate as little API as possible (currently, just the DaggerFoo *.builder()* method, so this isn't something that makes sense inside Dagger proper.

**Comment by ansman** [comment]
But if you omit the builder it already generated methods for the dependency modules
