### ISSUE TITLE
@ContributesAndroidInjector module for a BaseActivity

### ISSUE THREAD

**Issue by vhnguyenmingle** [google/dagger#851]
I am using the dagger2 android injector helper classes follow this guide https://google.github.io/dagger//android.html. However, When I use @ContributesAndroidInjector for building a component for **BaseActivity (abstract class)**  to provide some object: activity context, FragmentManager... I call **AndroidInjection.inject(this);** on **HomeActivity (extends BaseActivity)**, this error is showed below:
**Error:(22, 8) error: [dagger.android.AndroidInjector.inject(T)] com.mingle.market.ui.base.views.BaseActivity cannot be provided without an @Provides-annotated method. This type supports members injection but cannot be implicitly provided.**
Have @ContributesAndroidInjector support for this?
//Builder 
@Module
public abstract class BuilderModule {

    @PerActivity
    @ContributesAndroidInjector(modules = {ViewModelModule.class, ActivityModule.class})
    abstract HomeActivity bindHomeActivity();

    @PerActivity
    @ContributesAndroidInjector(modules = {ViewModelModule.class, ActivityModule.class})
    abstract SplashScreenActivity bindSplashScreenActivity();
}

@Module
public class ActivityModule {

    @Provides
    @PerActivity
    @ActivityContext
    Context provideActivityContext(BaseActivity activity) {
        return activity;
    }

    @Provides
    @PerActivity
    @ActivityFragmentManager
    FragmentManager provideFragmentManager(BaseActivity activity) {
        return activity.getSupportFragmentManager();
    }

    @Provides
    @PerActivity
    Navigator provideNavigator(BaseActivity activity) {
        return new ActivityNavigator(activity);
    }
}

**Comment by JonathanMerritt** [comment]
Your not providing/binding your 'BaseActivity'. You'll have to do that for each 'Activity' as far as I can figure out.

**Comment by ronshapiro** [comment]
This appears to be a question - please use StackOverflow with the `dagger-2` tag instead, as that is a better forum for questions.
