### ISSUE TITLE
Missing bindings on generated _MembersInjector

### ISSUE THREAD

**Issue by emarc-m** [google/dagger#852]
I'm getting an Error when compiling:

`Error:(338, 35) error: method create in class EditView_MembersInjector cannot be applied to given types;
required: Provider<Presenter>
found: Provider<ViewPresenter>,Provider<Presenter>
reason: actual and formal argument lists differ in length`

I think the reason for this is that I have the class inheritance setup as such:

1. A extends B, B extends C
2. B does not have any injected fields
3. A and C has injected fields

I saw this comment from: https://github.com/google/dagger/issues/489

> First, we try to avoid spooky action at a distance. Say you have A extends B extends C. If C has an @Injected field and that's the only field that is injected, it would be potentially surprising and hard to manage if a change to a field on C suddenly breaks components that request members injection on A. The distance between the code that changes and the error is too great. Totally fine for a warning though, IMO.

Is this type of inherited injection not supported?

**Comment by emarc-m** [comment]
@ronshapiro Please see:
https://github.com/ximity-oss/dagger-mvp, branch: inheritance_error

Sorry I forgot to mention the version. It's 2.11.

**Comment by ronshapiro** [comment]
I'm trying to reproduce, but I'm having trouble. This compiles for me:

```java
class Playground {
  static class T1 { @Inject T1() {} }
  static class T2 { @Inject T2() {} }
  static class T3 { @Inject T3() {} }
  static class T4 { @Inject T4() {} }

  abstract class A {
    @Inject T1 t1;
    @Inject T2 t2;
  }

  abstract class B extends A {}

  class C extends B {
    @Inject T3 t3;
    @Inject T4 t4;
  }

  @Component
  interface Comp {
    void inject(C c);
  }
}
```
