### ISSUE TITLE
Return types should be specifically mentioned in kotlin

### ISSUE THREAD

**Issue by mkodekar** [google/dagger#856]
with reference to this [gist](https://gist.github.com/mkodekar/bdfdfe38098728e90098461ee3913a30) of mine which does not compile, Return  types have to explicitly mentioned for the functions or the lambdas in order to make dagger graph compile and work, well i hope somehow future version of dagger2 address this issue / include this language feature to dagger

**Comment by JakeWharton** [comment]
Are you intending to be returning `Function` types from those expression body providers? Because that looks like your problem, not anything to do with Dagger.

**Comment by mkodekar** [comment]
Actually it return types and not just types i am intending not use return types and just call functions and lambdas directly and the gradle console just goes bam on the httplogginginterceptor

**Comment by JakeWharton** [comment]
No, the logging interceptor provider and the OkHttp client provider return zero-argument functions since you're using the expression body syntax combined with the lambda syntax.

**Comment by mkodekar** [comment]
okay it means the return type is something like () -> OkHttpClient not what is actually meant to be

**Comment by ronshapiro** [comment]
Please move this to StackOverflow
This appears to be a question - please use StackOverflow with the `dagger-2` tag instead, as that is a better forum for questions.
