### ISSUE TITLE
Dagger does not generate DaggerClasses after migrate to gradle 3.0

### ISSUE THREAD

**Issue by bobekos** [google/dagger#857]
Hi everyone,

i have migrate to the newest Version of Android Studio and gradle:

Android Studio 3.0 Beta 3
gradle 3.0.0-beta3

Now i can't rebuild my dagger project. Its simply doesn't generate the dagger classes. My app.gradle entry:

`final DAGGER = '2.11'
annotationProcessor "com.google.dagger:dagger-compiler:$DAGGER"
implementation "com.google.dagger:dagger:$DAGGER"`

I have also enabled the annotation processing under -> other settings -> compiler -> Annotation Processors and modify my .idea/compiler.xml file:

`<annotationProcessing>
      <profile default="true" name="Default" enabled="true">
        <processorPath useClasspath="true" />
      </profile>
    </annotationProcessing>`

Still the same issue. Have already someone migrate to the newest gradle and can give me some tipps?

**Comment by rafagcamargo** [comment]
Hello @bobekos have you figured this issue? I'm facing same challenge.

Using dagger 2.11, everything worked fine before migration.

**Comment by heralds25** [comment]
Please share fix code for this issue i have a same problem. Thanks in advance
