### ISSUE TITLE
membersInjector do not generate when i use javac command to compile some java files

### ISSUE THREAD

**Issue by dunwen** [google/dagger#863]
i user javac command to compile some java files.
all dagger files are generated but expect of xx_membersInjector.
i use it for an android increase build.

when i compile the whole project, dagger works well !

could u tell me which situation can cause this type of files do not be generated if you know the reasaon?

sorry for my poor English....
the command look like this:  >> i am sure my command is correct
```
javac -encoding UTF-8 -g -target 1.7 -source 1.7 -cp some android library:  the file witch need compile: the files which relate to the dagger 
```

**Comment by ronshapiro** [comment]
This appears to be a question - please use StackOverflow with the `dagger-2` tag instead, as that is a better forum for questions.
