### ISSUE TITLE
What happened to the GraphViz output?

### ISSUE THREAD

**Issue by paul-hammant** [google/dagger#865]
Ref: https://github.com/google/dagger/commit/fafc8984e5975718e48fac0e5028b32e67399035

I can't see the classes in HEAD of Dagger2 :( or things they may have been renamed to?

We had a Monitor implmentation for [PicoContainer ten years ago](https://github.com/picocontainer/PicoContainer2/blob/master/pico/gems/src/java/org/picocontainer/gems/monitors/DotDependencyGraphComponentMonitor.java) that spat out DOT graphs from run-time usage (injections), I was going to ask for the feature to be added to Dagger2, but see that it was previously by Jesse.  Super useful!

**Comment by JakeWharton** [comment]
This will likely come via https://github.com/google/dagger/issues/773#issuecomment-309063073 instead of implemented directly inside Dagger.
