### ISSUE TITLE
Feature request: add optional type parameter to @IntoSet

### ISSUE THREAD

**Issue by chrisalice** [google/dagger#868]
I often want to bind a type into a set _and_ bind it explicitly under its own type. A good example is services: they need to go into a service set to be lifecycle managed, but also be bound by their own type so other code can use them. Adding a second provider method just to do that mapping is a lot of boilerplate to maintain. I'd like to be able to pass the type parameter into `@IntoSet` instead, e.g.

```
    @Provides
    @IntoSet(Service.class)
    public MyService provideMyService(...) {
        ...
    }
```

Generics complicate this, but the solution space is limited. For instance, given:

```
    @Provides
    @IntoSet(Supplier.class)  // Generic! MySupplier implements Supplier<Integer>
    public MySupplier provideMySupplier(...) {
        ...
    }
```

1) Error
2) Multibind to `Supplier<?>`
3) Multibind to `Supplier<Integer>`
4) Multibind to _both_ `Supplier<Integer>` _and_ `Supplier<?>`

**Comment by ronshapiro** [comment]
I don't think this is something we're going to adopt - maybe you want to consider generating your modules if this is something that you do a lot?

**Comment by ronshapiro** [comment]
Maybe this fits under #869
