### ISSUE TITLE
Examples don't compile

### ISSUE THREAD

**Issue by imbeyondboredom** [google/dagger#87]
I know you guys are still in the process of making the examples, but at this point they don't work at all. One such example is that https://github.com/google/dagger/blob/master/examples/android-activity-graphs/src/main/java/com/example/dagger/activitygraphs/AbstractActivityComponent.java has a different class name than the file.

This makes determining how everything is supposed to work fairly difficult if you don't already understand the intricacies of the Dagger2 implementation.

**Comment by cgruber** [comment]
Largely addressed in #93 and #145
