### ISSUE TITLE
Add support for Bazel on README.md

### ISSUE THREAD

**Issue by jaredsburrows** [google/dagger#871]
You have added support for Maven and Gradle, let's add support for Bazel as well :)
 - https://github.com/google/dagger#maven
 - https://github.com/google/dagger#java-gradle
 - https://github.com/google/dagger#android-gradle

**Comment by jaredsburrows** [comment]
@ronshapiro Can we add docs for this?

**Comment by StephenAmar** [comment]
Any news regarding bazel support?

**Comment by ensonic** [comment]
FYI: a port of the example is here:
https://github.com/simonhorlick/bazel-dagger-example
maybe that can be incorporated too.

**Comment by jaredsburrows** [comment]
@ronshapiro Thanks for adding this in the docs.

@ensonic Maybe you can update your code example with @ronshapiro's build documentation to test it out.

**Comment by ensonic** [comment]
@jaredsburrows the bazel-dagger-example is not mine, but I'll ask the owner.
