### ISSUE TITLE
Are runtime bindings frowned upon now?

### ISSUE THREAD

**Issue by cxzhang2** [google/dagger#875]
I've always found dynamic bindings practical though perhaps not in line with the true spirit of DI.  First time reading Dagger 2 doc I was pleasantly surprised to see @BindsInstance supported because it seemed to be a nod towards usage of dynamic bindings.  But now the new Dagger Android package seems very opinionated against them -- there isn't a way to modify the graph prior to calling AndroidInjection.inject(this).  Just wondering if I'm missing something.  Thanks!

**Comment by JakeWharton** [comment]
`@BindsInstance` is only syntactic shorthand for a concept that has always existed: modules that take constructor parameters and supply those references into the graph. The shape of the graph via the type system is still rigid and compile-time validated.

Do you have a motivating example of what you're trying to achieve?

**Comment by cxzhang2** [comment]
@JakeWharton right the shape the graph is locked in at compile time, but the contents aren't if I'm the one building the graph.  For example:

```
SomeActivity {
  onCreate(){
    //fetch someData and someEndpoint from getArguments()
    myApp()
      .getAppComponent()
      .someActivityComponentBuilder()
      .someRuntimeData(someData)
      .someEndpoint(someEndpoint)
      .build()
      .inject(this);
  }
} 
```

Now I can use constructor injection on my presenter / model and @Inject someData into my presenter and @Inject someEndpoint into my model.  But with AndroidInjector I can only inject().

**Comment by JakeWharton** [comment]
```java
@Module
abstract class SomeActivityModule {
  @Provides static RuntimeData runtimeData(SomeActivity activity) {
    return activity.someData;
  }
  @Provides static Endpoint endpoint(SomeActivity activity) {
    return activity.someEndpoint;
  }
}
```
then `includes = SomeActivityModule.class`.

**Comment by cxzhang2** [comment]
Oooh fancy.  Thank you!
