### ISSUE TITLE
Swapping implementations according to module hierarchy 

### ISSUE THREAD

**Issue by nocotom** [google/dagger#877]
Hello,
it would be useful to add an enhancement that allows swaping implementations according to module hierarchy. For example the module **A** defines default implementations and there are two child modules **B1** and **B2** that could swap the default implementations.

```
@Module
abstract class AModule {
  @Binds
  abstract Bird birdBind(DefaultBird bird);
}
```

```
@Module(includes = AModule.class)
abstract class B1Module {
  @Binds
  abstract Bird birdBind(Eagle eagle);
}
```

```
@Module(includes = AModule.class)
abstract class B2Module {
  @Binds
  abstract Bird birdBind(Hawk hawk);
}
```

I know that I can use **Named** annotation or create my own, but when libraries are separated and independent I cannot achieve this functionality. Especially, when at **A** level library there is a class that requires **Bird** interface and child libraries cannot change provided implementation.

**Comment by ronshapiro** [comment]
You can use [optional bindings](https://google.github.io/dagger/users-guide#optional-bindings) for this.

**Comment by tbroyer** [comment]
Or, **A** could provide a module that does **not** bind `Bird`, and another module that binds it `DefaultBird`. Then you can choose to either use the former with either `B1Module` or `B2Module` to have `Eagle`s or `Hawk`s respectively, or the latter to have `DefaultBird`s. It's **A**'s responsibility to provide the flexibility.

**Comment by nocotom** [comment]
@ronshapiro this solution still does not allows me to swap implementations. In our scenario, we have third level library and it hard to predict whitch implementation will be swaped in the future. The optional bindings can be in two states: exist and not exist, but it would be useful to achieve the **last defined**.

@tbroyer that's right, we've already workaround this problem as You mentioned. But there is a problem when **A** module defines eg. 10 bindings and has three childs: **B1**, **B2**, **B3**. When the **B1** module wants to swap only one implementation it forces changes in the **A**, **B2**, and **B3** modules and recompiling of all dependencies is requred.

In the **Guice** implementation of IoC this is a default behavior: latest defined binding will be injected.
