### ISSUE TITLE
More examples (Servlets, Jersey)

### ISSUE THREAD

**Issue by husayt** [google/dagger#89]
Would be really useful to get more realistic examples, especially for webframeworks.

Has anyone attempted to get Dagger2 working with Jersey?

**Comment by cgruber** [comment]
Our focus has been on Android and core functionality.  That said, we want more examples, and would take contributions, provisionally.  Ultimately we have plans for more robust integrations, but not in a 2.0 timeline.

**Comment by ronshapiro** [comment]
We'd gladly accept contributions with more examples (preferably from people that have experience with these frameworks since we don't)!
