### ISSUE TITLE
Some times initalizieing faild

### ISSUE THREAD

**Issue by skauss** [google/dagger#893]
Hi,
we use Dagger2 Version 2.11. In the Google Play Console I found about 200 crashes where Dagger is not ready.
Our code looks like  
`
  public enum Injector {
    INSTANCE;

    private ApplicationComponent applicationComponent;
    public void initializeApplicationComponent(Context applicationContext) {
        this.applicationComponent = DaggerApplicationComponent.builder()
                .applicationModule(new ApplicationModule(applicationContext))
                .build();
    }

    public ApplicationComponent getApplicationComponent() {
        return applicationComponent;
    }
}
`

OurApplication.java

`

public class OurApplication extends MultiDexApplication {
   @Override
    public void onCreate() {
        super.onCreate();

       // setup the object graph for dagger
        if ( Injector.INSTANCE.getApplicationComponent() == null ) {
            Injector.INSTANCE.initializeApplicationComponent(this);
   }
.....
}
...
`

Our StartActivity.java

`
public class StartActivity extends Activity {
...

    @Override
    protected void onStart() {
        super.onStart();
        // Dagger initialize all component in the case we inject the first component
        Injector.INSTANCE.getApplicationComponent().inject(this);

        setupSplashScreen();
...

}
`
one 200 of 100000 sessions the Injector.INSTANCE.getApplicationComponent() is null and I have no idea why ?

50% of the 200 crashes are on Honor 5C  and P9 (HWEVA) 
15% of the 200 crashes are on Galaxy A5

Any idea
Regards

**Comment by ronshapiro** [comment]
This appears to be a question - please use StackOverflow with the `dagger-2` tag instead, as that is a better forum for questions.

**Comment by skauss** [comment]
Hi,
I found a Issue https://github.com/google/dagger/issues/748 which has the same problem.

It looks like we can't depend on that android.app.Application is called before the StartActivity.
There are some Android 7.x phone out (Samsung, Honor 5C, P9) where the Application isn't started (1 of 10000 App start's).
I guess this happens in case of "External In-App-Links", "Push Receiver", "AppWidgetProvider"...
