### ISSUE TITLE
Inlined methods are too big for javac

### ISSUE THREAD

**Issue by Mauin** [google/dagger#895]
I just tried updating Dagger from v2.11 to v2.12 and ran into this problem. Due to the new inlining into the generated Component classes it seems like Dagger 2.12 is able to generate methods that are too big for `javac`.

During compilation I'm seeing `error: code too large` errors failing the build.

This seems to indicate that methods Dagger is generating for the Component class are surpassing a limit of 64K bytecode. When looking at the generated class I can see that methods can get very big (>5k lines) before compilation fails and leaves the file truncated and unfinished.

Now granted this is a result of having a huge ApplicationComponent with tons of dependencies, but breaks the build for such projects on v2.12.

**Comment by ronshapiro** [comment]
hm, I'm surprised we haven't seen this at all inside Google yet, where we have some gargantuan components.

Can you do me a favor - try passing "-Adagger.experimentalAndroidMode=ENABLED" to `javac` and see if that passes? 

I don't recommend actually building your code like this as that mode is not ready, but it may help detect the issue.

**Comment by Mauin** [comment]
Running with `-Adagger.experimentalAndroidMode=ENABLED` provides a bunch of errors like the following in the Component class:

```
error: incompatible types: Lazy<Object> cannot be converted to Lazy<SomeClass>
error: incompatible types: Provider<Object> cannot be converted to Provider<SomeOtherClass>
```

The build fails because of that and doesn't get any further. But looking at the generated `DaggerComponent` class the code looks a lot more normal and the class is much, much shorter than the one that was generated by plain Dagger v2.12.

**Comment by ronshapiro** [comment]
Ok - I'll take a look at what we can do here. Sorry you're running into this issue!

**Comment by Mauin** [comment]
Thanks for taking a look. Let me know if I can provide any more details that might help debug this.

**Comment by ronshapiro** [comment]
This was fixed in https://github.com/google/dagger/commit/3a3ada223cf1d6a7f570a5bff626e4cdfabfbb98

**Comment by Mauin** [comment]
Awesome, I'll test this with the next Dagger release and let you know how it goes.

**Comment by Mauin** [comment]
Just checked with v2.13 and that seems to solve it. Thanks for the help!

**Comment by ronshapiro** [comment]
Great!
