### ISSUE TITLE
Compilation on Windows

### ISSUE THREAD

**Issue by nguyentruongtho** [google/dagger#90]
Is there any special reason for using different version of `auto-service` [1.0-rc1](https://github.com/google/dagger/blob/master/pom.xml#L46-L48) because I get compilation error on Windows.

```
[ERROR] FATAL ERROR: java.lang.IllegalArgumentException: Invalid relative name: META-INF\services\javax.annotation.processing.Processor
```

The reason is `auto-service rc1` does not have following fix https://github.com/google/auto/commit/4ccfabfe6618ed7f9bf85d812bbea20c868200e2 which is almost a year ago. The fix is to use `1.0-SNAPSHOT`.

**Comment by cgruber** [comment]
I'll check if 1.0-rc2 has this fix, and if so bump to that.  Otherwise, I'll make sure we release auto-service at 1.0 prior to dagger 2.0 to get this working.

**Comment by cgruber** [comment]
Should be bumped to auto-service-1.0-rc2 in #145

**Comment by nguyentruongtho** [comment]
:+1:

**Comment by cgruber** [comment]
I'm going to close this, but please do test the snapshot.  Or the release, which is imminent. :)
