### ISSUE TITLE
Dagger 2.12 and proguard 

### ISSUE THREAD

**Issue by sebigansca** [google/dagger#904]
Hi, 

I have an error after switching from Dagger 2.5 to 2.12 when using proguard on my release build.

DaggerGraph.java:662: error: cannot find symbol
    ReportingService_MembersInjector.injectA(instance, provideDataLayerProvider.get());

I have an Android Library that is compiled and obfuscated and an Android App that includes that Library. 

The graph is generated using components from both modules. 

Thanks

PS. With Dagger 2.5 it is working without problems.

**Comment by ronshapiro** [comment]
It sounds like you need to recompile the library with 2.12 as well.

**Comment by sebigansca** [comment]
Hi, 

Is not that I am recompiling the Library as well. 

The debug build is working well as I do not have activated proguard there. 
Only on release build with proguard I have this issue. 

I think this should be reopened!

**Comment by sebigansca** [comment]
It looks like the package private members were obfuscated in the Library and when Graph was generated was using that names and trying to find the inject methods in the Library. 

I suppose before 2.12 (2.11 was also working) the inject methods were generated earlier in the flow and were not affected by the obfuscation of the members.
