### ISSUE TITLE
Can a activity exist multiple component

### ISSUE THREAD

**Issue by lizhifeng-sky** [google/dagger#906]

**Comment by lizhifeng-sky** [comment]
@dberlin

**Comment by ronshapiro** [comment]
Can you elaborate a bit more? Your question isn't clear

**Comment by lizhifeng-sky** [comment]
public class MainActivity extends AppCompatActivity {
    @Inject
    Person person;
    @Inject
    Student student;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
//        DaggerStudentComponent.create().inject(this);
//        DaggerPersonComponent.create().inject(this);
    }
}

**Comment by lizhifeng-sky** [comment]
is that enough？

**Comment by lizhifeng-sky** [comment]
There are more codes to reproduce, and if not enough, I can write all of the code
Can you make sense of what I'm saying? I translate with a translation tool

**Comment by ronshapiro** [comment]
This is probably better suited for StackOverflow with the `dagger-2` tag instead, as that is a better forum for questions.
