### ISSUE TITLE
Update dependency handlers in the documentation and internals

### ISSUE THREAD

**Issue by heinrichreimer** [google/dagger#914]
The `compile` dependency handler is now deprecated and should be replaced with `implementation` or `api`, depending on whether or not the sources should be visible to modules depending on the dependency.
This means the documentation should replace `compile` with `implementation` and internal dependencies from the dagger modules should have `api` if they're part of the public API, or `implementation` if they're only used by dagger internally and aren't part of the public API.

**Comment by ronshapiro** [comment]
Is this something gradle related? If so, do you mind offering up a PR? It's been a little while since any of us have been involved with gradle related stuff.

**Comment by ronshapiro** [comment]
Let's converge on #1130
