### ISSUE TITLE
when inject activity lint warning ```result of inject not used```

### ISSUE THREAD

**Issue by Axrorxoja** [google/dagger#917]
On dagger 2.1.2 when injecting activity/fragment android studio lint warning 

> result of inject not used

> Some methods have no side effects, an calling them without doing something without the result is suspicious
dagger=2.1.2
android studio 3.1 canary

**Comment by JonathanMerritt** [comment]
I believe this is Gradle related. The latest version.

Downgraded AS and Gradle to temporarily fix. Only help I can give unfortunately.

**Comment by ronshapiro** [comment]
Are you using `@CheckReturnValue` on your package?

**Comment by JonathanMerritt** [comment]
@ronshapiro No, I haven't. I didn't even know it existed till now. :bulb:

However, I'll look it over, try it out and report back.

Thanks for the tip.

**Comment by ronshapiro** [comment]
I think IntelliJ doesn't recognize `com.google.errorprone.annotations.CanIgnoreReturnValue` which is usually how this comes up. 

https://youtrack.jetbrains.com/issue/IDEA-158576 claims that this is supported, but I don't think I've seen that in action.

**Comment by JonathanMerritt** [comment]
Haven't had a chance to test any of this yet. Nothing needed in the recent Android Studios that forced me too.

@ronshapiro Can you clarify, do you mean using the 
com.google.errorprone.annotations.CanIgnoreReturnValue annotation will solve the warnings and the ensuing errors? Or just the warnings?

I did attempt to update Gradle on my older Android Studio, and the warning/errors still occurred. So idk if my issue is related to an intelliJ issue. Though I could be wrong. Reverting the Gradle cleared the warnings and errors however.

**Comment by tnorbye** [comment]
This might be https://issuetracker.google.com/69344103 . If somebody can help me reproduce it, I'll try to fix it in Android Lint ASAP.

**Comment by JonathanMerritt** [comment]
@tnorbye A little late. Sorry. Though from that linked issue it seems like they (you?) already have a patch ready for it. So that's pretty cool, thanks.
