### ISSUE TITLE
@Module(subcomponents = {}) usecase?

### ISSUE THREAD

**Issue by bnvinay92** [google/dagger#919]
Removing the `subcomponents` attribute from my `@Module` annotation does not break anything. I can still declare Subcomponent builders in my parent component. The documentation suggests otherwise: https://google.github.io/dagger/subcomponents.html. What is the usecase of this attribute?

**Comment by netdpb** [comment]
[Later](https://google.github.io/dagger/subcomponents.html#defining-subcomponents-with-abstract-factory-methods) in that document, we do mention that the old way of installing subcomponents (with an abstract method that returns either the subcomponent or its builder) still works. The benefit to using the `subcomponents` attribute is that if there is no such abstract method on the component, then Dagger can completely eliminate unused subcomponents.
