### ISSUE TITLE
Reconstruct component in runtime and reinject dependencies

### ISSUE THREAD

**Issue by sergevalevich** [google/dagger#920]
Hi, guys!
I have a subcomponent(**componentA**) in the android app which has it's own scope. 
**componentA** gets constructed based on contents of **ObjectA** which is fetched from some kind of storage.
In Fragments which are connected to the scope of **componentA** I call **componentA.inject(this)** in onCreate() method.
The problem is, that now  every time application returns from background, if  **ObjectA** has expired,
I have to fetch **ObjectA** again and construct **componentA** and some how reinject dependencies 
provided by **componentA**
which has already been injected in onCreate()  in the same Fragment.
Dependencies should be also updated for the fragments in backstack when the user returns back to the Fragment.
Do you have any mechanism to achieve that?
Thanks!

**Comment by ronshapiro** [comment]
I encourage you to look at google.github.io/dagger/android, which should handle your use case. Otherwise, StackOverflow is a better place to ask questions like this.
