### ISSUE TITLE
gradle:3.0.0 java.lang.NoClassDefFoundError: dagger/Provides

### ISSUE THREAD

**Issue by devzwy** [google/dagger#923]
Error:Execution failed for task ':MvpTools:compileDebugJavaWithJavac'.
> java.lang.NoClassDefFoundError: dagger/Provides

**Comment by JakeWharton** [comment]
How can we reproduce this problem? This is not enough information to be actionable.

**Comment by liyongyan** [comment]
Unable to generate DaggerComponent

**Comment by ronshapiro** [comment]
This appears to be a question - please use StackOverflow with the `dagger-2` tag instead, as that is a better forum for questions.

**Comment by bayshier** [comment]
Error:Execution failed for task ':order:compileDebugJavaWithJavac'.
> java.lang.NoClassDefFoundError: dagger/Provides
