### ISSUE TITLE
AS 3.0 gradle:3.0.0 build error

### ISSUE THREAD

**Issue by liyongyan** [google/dagger#924]
Error:Execution failed for task ':app:compileDebugJavaWithJavac'.
> java.lang.NoClassDefFoundError: dagger/Provides

**Comment by JakeWharton** [comment]
Dupe of #923 and not enough information to diagnose a problem anyway.

**Comment by bayshier** [comment]
Error:Execution failed for task ':order:compileDebugJavaWithJavac'.
> java.lang.NoClassDefFoundError: dagger/Subcomponent

**Comment by bayshier** [comment]
Error:Execution failed for task ':login:compileDebugJavaWithJavac'.
> java.lang.NoClassDefFoundError: dagger/Provides
