### ISSUE TITLE
@Multibinds Map doesn't generate Map<K, Provider<T>>

### ISSUE THREAD

**Issue by 51systems** [google/dagger#926]
Using dagger 2.12 the following code:
```
    @Multibinds
    abstract Map<Integer, DatabaseMigration> migrations();

    @Provides
    @Singleton
    static MigrationManagerBase providesMigrationManager(Map<Long, Provider<DatabaseMigration>> migrations) {
        return new DaggerMigrationManager(migrations);
    }
```
Produces the error: `java.util.Map<java.lang.Long,javax.inject.Provider<run.bios.realm.migration.DatabaseMigration>> cannot be provided without an @Provides-annotated method`

However, If I add the first migration:
```
    @Provides
    @IntoMap
    @LongKey(1) //schema version
    static DatabaseMigration migration1() {
        return null;
    }
```

Everything compiles ok. It seems that the @Multibinds doesn't generate the `Map<Long, Provider<DatabaseMigration>>`.

**Comment by ronshapiro** [comment]
Your `@Multibinds` method is keyed on `Integer`s, not `Long`s.
