### ISSUE TITLE
Question: How to provide default implementation?

### ISSUE THREAD

**Issue by vovkab** [google/dagger#929]
Hello

I'm writing an android library and I would like to provide default implementation in my modules, to avoid breaking clients every time I'm adding a new dependency.

Probably I could use `BindsOptionalOf` but this will only return `Optional` and not default implementation that I could provide.

Is there any good way to do this?

**Comment by ronshapiro** [comment]
You're on the right track.

```java
@Module
interface ModWithDefaults {
  @BindsOptionalOf @Custom Foo optionalFoo();
  @Provides
  static Foo provideFoo(Optional<Foo> customFoo, @Default Foo defaultFoo) {
    return customFoo.orElse(defaultFoo);
  }
}
```

**Comment by juanchosaravia** [comment]
@ronshapiro what are @Custom and @Default annotations? I don't find it in Dagger 2 lib.

**Comment by ronshapiro** [comment]
They're custom `@Qualifier`s that you can write.

**Comment by juanchosaravia** [comment]
Do you have any full example using custom qualifiers? I'm not finding how you connect those qualifiers with the impl. For example the @Default one, I assume there is a provides with this @Default qualifier in another place or a class annotated with that?
