### ISSUE TITLE
andriod activity context

### ISSUE THREAD

**Issue by kingning1** [google/dagger#931]
**module**
`
@Module(subcomponents = ContentActivityComponent.class)
public abstract class ContentActivityModule {

    /**
     * sadas
     *
     * @param builder
     * @return
     */
    @Binds
    @IntoMap
    @ActivityKey(ContentActivity.class)
    abstract AndroidInjector.Factory<? extends Activity> bind(ContentActivityComponent.Builder builder);

    Context context;

    @Inject
    public ContentActivityModule(ContentActivity activity) {
        this.context = activity;
    }

    @Provides
    public Context context() {
        return context;
    }

    @Provides
    public static RetrofitUtil retrofitUtil() {
        return new RetrofitUtil();
    }

    @Provides
    public static Webservice webservice() {
        return retrofitUtil().getRetrofit().create(Webservice.class);
    }

}

**component**
@ActivityScope
@Subcomponent
public interface ContentActivityComponent extends AndroidInjector<ContentActivity> {

    @Subcomponent.Builder
    abstract class Builder extends AndroidInjector.Builder<ContentActivity> {
       private  Context context;
        @Override
        public void seedInstance(ContentActivity instance) {
            context=instance;
        }

        public Context getContext() {
            return context;
        }
    }
}
`
请教一下，这个activity怎么获取到，我不会弄了

**Comment by ronshapiro** [comment]
This appears to be a question - please use StackOverflow with the `dagger-2` tag instead, as that is a better forum for questions.
