### ISSUE TITLE
Annotating module with scope or qualifier should cause error

### ISSUE THREAD

**Issue by jbarr21** [google/dagger#932]
If someone incorrectly annotates a Module class with a scope or qualifier, then the Dagger compiler should throw an error. Adding this annotation has no effect and an error would help clarify this. Some might incorrectly think that scoping the module class would cause each of the provides methods to inherit that scoping, and an error would help make it more explicit that this is untrue.

Should cause an error:
```java
@MyCustomScope
@Module
class FooModule {
  @Provide Bar provideBar(); // this really has no scope applied
}
```

**Comment by Dunemaster** [comment]
As an alternative, annoting a module should be the same as annotation every @Provides or @Binds method

**Comment by ronshapiro** [comment]
As an update: we have a commit waiting to be submitted - cleaning up internal users and creating an ErrorProne refactoring that anyone should be able to apply to their project. I expect 2.15 to have this.
