### ISSUE TITLE
Feature request: factory method in components for assisted injection

### ISSUE THREAD

**Issue by aartikov** [google/dagger#935]
It is a common case when a class have some dynamic parameters along with usual dependencies. 
For example `articleId` is a dynamic parameter whereas `articleService` is an usual dependency.
```
class ArticlePresenter {
	...
	ArticlePresenter(long articleId, ArticleService articleService) {
		...
	}
}
```
This mixing of parameters and dependencies is known as **Assisted injection**. Dagger 2 does not support this feature now. 

There are three work-around known to me:
1) Use factories (probably generated by third-party libraries).
2) Create a separate component for a class with dynamic parameters.
3) Set dynamic parameters with setters after an object is created.

In my opinion, all of these aproaches are far from ideal. So I propose a new feature "Factory method in components" for support of assisted injection.

Lets allow components to have `getSomething` methods with parameters. Like that:
```
@Component
public interface AppComponent {
	ArticlePresenter getArticlePresenter(long articleId);
}
```

Add `@Param` annotation to specify which constructor arguments are dynamic parameters:
```
@Inject
public ArticlePresenter(@Param long articleId, ArticleService articleService) {
	...
}
```

After that we can request objects from the component:
```
ArticlePresenter presenter = appComponent.getArticlePresenter(someId);
```

Of course, this is just an idea not a complete solution. 
What do you think, guys? Will it make Dagger 2 even more awesome?

**Comment by tbroyer** [comment]
Fwiw, Google has Auto Factory for that use case: https://github.com/google/auto/tree/master/factory

```jav
@AutoFactory
public class ArticlePresenter {
  public ArticlePresenter(@Provided long articleId, ArticleService articleService) {
     …
  }
  …
}
```
```java
@Component interface AppComponent {
  ArticlePresenterFactory getArticlePresenterFactory();
}
```
```java
ArticlePresenter presenter = appComponent.getArticlePresenterFactory().create(someId);
```

Better separation of concerns (fwiw, auto-factory work with Guice, Spring, CDI, H2, or whichever JSR-330 implementation you want; the factory generated by auto-factory would be what Dagger would do under the hood anyway), not more nor less typing/boilerplate; how's that “far from ideal”?

**Comment by aartikov** [comment]
@tbroyer I have mentioned this aproach already: "1. Use factories (probably generated by third-party libraries)". And yes, I think it is not ideal. Its drawback is that I don't need a factory at all! I need my presenter to be created. Dagger hides generating of factories under the hood. Why should this factory be an exception? In my opinion, assisted injection should be as straightforward as possible.

**Comment by ronshapiro** [comment]
I've been thinking about this problem a lot, mostly in the context of two concepts:
  1. AutoFactory is an API-generating processor, which is usually less preferred vs. implementation generating.
  2. AutoFactory forces `Provider` objects for each dependency - fine for servers, but bad in client apps.

I think Dagger could provide a nice intermediary and we could design something that was still JSR 330 compatible (and easy to use within Guice, Spring, etc). The Dagger flavor could take advantage of the inlining work we've done recently and be a much lighter weight factory.

The one downside in my current design is the factory would hold an implicit reference back to the component and could be a memory leak. But there's more to think about this. I'll post back when I've thought about it more.

**Comment by ronshapiro** [comment]
@cgdecker is working on something like this

**Comment by ronshapiro** [comment]
`@Component.Factory` will be in 2.22. And @JakeWharton has worked on https://github.com/square/assistedinject which is pretty advanced. That, with `@AutoFactory`, gives 3 options for solving this.
