### ISSUE TITLE
JavaDoc warnings in unused-modules

### ISSUE THREAD

**Issue by yegeniy** [google/dagger#936]
[Wherever `NOOP_BUILDER_METHOD_JAVADOC` is used](
https://github.com/google/dagger/blob/19cc9f4580b41efbba01492a768be86ab97a0d02/java/dagger/internal/codegen/ComponentBuilder.java#L264), generating the javadoc tends to throw warnings about the parameters of the method that the javadoc is added to.

For example, when generating javadocs, with the following user code:

```java
@Component(modules = {Providers.class})
@Singleton
public interface Injector {
...
}
```

the following code is generated:

```java
...
    /**
     * @deprecated This module is declared, but an instance is not used in the component. This
     *     method is a no-op. For more, see https://google.github.io/dagger/unused-modules.
     */
    @Deprecated
    public Builder providers(Providers providers) {
      Preconditions.checkNotNull(providers);
      return this;
    }
...
```

and the following warnings appear:

```
[INFO] --- maven-javadoc-plugin:3.0.0-M1:jar (attach-javadocs) @ sit ---
[INFO] 
2 warnings
[WARNING] Javadoc Warnings
[WARNING] /myapp/target/generated-sources/annotations/myapp/DaggerInjector.java:111: warning: no @param for providers
[WARNING] public Builder providers(Injector.Providers providers) {
[WARNING] ^
[WARNING] /myapp/target/generated-sources/annotations/myapp/DaggerInjector.java:111: warning: no @return
[WARNING] public Builder providers(Injector.Providers providers) {
[WARNING] ^
```

**Comment by ronshapiro** [comment]
Those are bad warnings. I recommend either turning them off, or just the `@Component.Builder` API (which we recommend anyway).

**Comment by yegeniy** [comment]
Agreed with the "bad warnings" bit. Thanks for the reference to @Component.Builder
