### ISSUE TITLE
Java 9 and @Module(includes={OtherModule.class})

### ISSUE THREAD

**Issue by rkapsi** [google/dagger#940]
In an attempt to work around #898 and use Java 9 for my IDE (Eclipse) I've now run into this problem where Dagger 2.12 is saying that one public `@Module` is trying to include a non-public `@Module` even though they're all public.

On further investigation it's not a IDE problem but is happening on the CLI as well as soon as I target JDK 9 (it compiles fine if I target JDK 8).

Please see this project for a repro:

https://github.com/rkapsi/jdk9-dagger-modules

```
$ java -version
openjdk version "9"
OpenJDK Runtime Environment (build 9+181)
OpenJDK 64-Bit Server VM (build 9+181, mixed mode)

$ javac -version
javac 9
```

```java
@Module
public class FooModule {
}

@Module(includes={FooModule.class})
public class BarModule {
}
```

```
This module is public, but it includes non-public (or effectively non-public) modules. Either reduce the visibility of this module or make FooModule public.
```

**Comment by ronshapiro** [comment]
I would have expected https://github.com/google/auto/commit/2c035ce5172a6c4d21d859e2609b57358db02f6f#diff-9119c229dbf20ab7e88dbbe95b525a05 to fix that issue, but apparently it's not working. I'll have to take a closer work, I'm surprised why this is broken

**Comment by ronshapiro** [comment]
I'm going to mark this as obsolete. If it's still happening in 2.22 even after @cgdecker's recent improvements, we can reopen.
