### ISSUE TITLE
Question: How to have implementation of interface repository in other project module in AndroidStudio using Dagger2 and Kotlin

### ISSUE THREAD

**Issue by oksett** [google/dagger#946]
I want to be able to have 2 different reactive implementation of the interface that is getting user location in other project module in AndroidStudio.

So to be specific it can be by using gms, or by just native android LocationManager.

Here is my repository interface:
```
interface RxLocationRepository {

@SuppressLint("MissingPermission")
fun onLocationUpdate(): Observable<Location>

fun stopLocationUpdates()
}
```
So for now, i implement this interface here, in class that is in the same project module in AndroidStudio:
```
class RxLocationRepositoryImpl(val reactiveLocationProvider: ReactiveLocationProvider,
                           val reactiveLocationRequest: LocationRequest,
                           val isUsingLocationNativeApi: Boolean,
                           val locationManager: LocationManager,
                           val geoEventsDistanceMeters: Int,
                           val geoEventsIntervalSeconds: Int
) : RxLocationRepository {


var locationToPopulate: Location = Location(LocationManager.GPS_PROVIDER)
lateinit var mLocationCallbackNativeApi: LocationListener
private val subject: BehaviorSubject<Location> = BehaviorSubject.createDefault(locationToPopulate)
var locationEmitter: Observable<Location> = subject.hide()

init {
    configureEmitter()
}

@SuppressLint("MissingPermission")
private fun configureEmitter(){
    if (!isUsingLocationNativeApi)
      locationEmitter = reactiveLocationProvider.getUpdatedLocation(reactiveLocationRequest)
    else{
      configureNativeLocationEmitter()
    }
}

@SuppressLint("MissingPermission")
private fun configureNativeLocationEmitter() {

    mLocationCallbackNativeApi = object : LocationListener {

        override fun onLocationChanged(location: Location) {
            subject.onNext(location)
        }

        override fun onStatusChanged(provider: String, status: Int, extras: Bundle) {}

        override fun onProviderEnabled(provider: String) {}

        override fun onProviderDisabled(provider: String) {}

    }

    try {
        locationManager.requestLocationUpdates(LocationManager.GPS_PROVIDER,
                (geoEventsIntervalSeconds * 1000).toLong(),
                geoEventsDistanceMeters.toFloat(),
                mLocationCallbackNativeApi,
                Looper.getMainLooper())
    } catch (ignored: IllegalArgumentException) {
        ignored.printStackTrace()
    }

    try {
        locationManager.requestLocationUpdates(LocationManager.NETWORK_PROVIDER,
                (geoEventsIntervalSeconds * 1000).toLong(),
                geoEventsDistanceMeters.toFloat(),
                mLocationCallbackNativeApi,
                Looper.getMainLooper())
    } catch (ignored: IllegalArgumentException) {
        ignored.printStackTrace()
    }
}

@SuppressLint("MissingPermission")
override fun onLocationUpdate(): Observable<Location> {
    return locationEmitter
}

override fun stopLocationUpdates() {
    if(isUsingLocationNativeApi)
    locationManager.removeUpdates(mLocationCallbackNativeApi)
  }
}
```
So everything is fine, but now i want to have the gms implementation of this in different project module(so i don't need to have gms dependencies in the gradle) and also the native implementation to the other module in Android Studio.

The final structure of the project in AndroidStudio will be like location_core, location_gms, location_native.

The location_core must not be aware of location_gms and native, i guess in opposite to them - they will have the dependency to location_core.

So now, i  have just  a LocationClient class, which will provide the Context(in location_core project module in AndroidStudio):
```
class LocationClient @Inject constructor(val nexoLocationManager: NexoLocationManager){
companion object {

    private var locationClient: LocationClient? = null

    fun obtainLocationClient(context: Context): LocationClient{
        val result = locationClient ?:
                DaggerLocationComponent
                        .builder()
                        .context(context)
                        .build()
                        .locationClient()

        locationClient = result
        return result
    }
  }
}
```
It is using some Dagger Component, which provide him all the implementation of different objects. So i want to move this LocationClient or make it abstract in location_core project module and move the implementation of it in each location_gms and location_native project module in AndroidStudio.

So the LocationClient class in each of them will provide the different implementation of this RxRepository. For now in each location_gms and location_native project module i have just implementation class which implements the repository rxLocationRepository(which i move from the implementation written above) on its own way.

The problem is i don't know exactly how to manage all of this with Dagger. Now i am using Dagger like this in my location_core, here is the LocationComponent:
```
@Singleton
@Component(modules = arrayOf(LocationModule::class))
interface LocationComponent{
fun locationClient(): LocationClient

@Component.Builder
interface Builder {
    @BindsInstance
    fun context(context: Context): Builder
    fun build(): LocationComponent
 }

}
```
and its module:
```
@Module
class LocationModule {

//some stuff

    @Provides
@Singleton
fun providesRxLocationRepository(
                                 reactiveLocationProvider: ReactiveLocationProvider,
                                 reactiveLocationRequest: LocationRequest,
                                 @Named("CONFIG_LOCATION_USE_NATIVE_API")isUsingLocationNativeApi: Boolean,
                                 locationManager: LocationManager,
                                 @Named("CONFIG_LOCATION_GEO_EVENTS_DISTANCE_METERS")geoEventsDistanceMeters: Int,
                                 @Named("CONFIG_LOCATION_GEO_EVENTS_INTERVAL_SECONDS")geoEventsIntervalSeconds: Int
): RxLocationRepository = RxLocationRepositoryImpl(
        reactiveLocationProvider,
        reactiveLocationRequest,
        isUsingLocationNativeApi,
        locationManager,
        geoEventsDistanceMeters,
        geoEventsIntervalSeconds)

//some other stuff
}
```

So how to write the actual LocationClient in each of the modules - location_gms and the location_native? How to provide the implementation of the rxLocationRepository which is in each of the location_gms and location_native project modules with Dagger, so that i can just use the interface RxLocationRepository in my location_core module and don't be bother of its implementation, because it will be in each project module?

Of course i must point, that those 3 modules never be together i guess, it will be 2 modules in each build_variant i guess. So i have to get rid of the google services dependency in location_core project module build.gradle.

![project_structure](https://user-images.githubusercontent.com/9077038/32692062-b7f22b22-c711-11e7-85e5-99fbf6ab3d57.png)

**Comment by ronshapiro** [comment]
This appears to be a question - please use StackOverflow with the `dagger-2` tag instead, as that is a better forum for questions.

**Comment by oksett** [comment]
@ronshapiro Thanks,FYI I've done this also
