### ISSUE TITLE
Local Singleton when using @ContributesAndroidInjector

### ISSUE THREAD

**Issue by piveloper** [google/dagger#948]
I have a working Dagger setup using the @ContributesAndroidInjector annotation (https://google.github.io/dagger/android.html).

            Component Application
           /                     \
    Subcomponent DrawerActivity   Subcomponent SubActivity
          |
    Subcomponent DrawerFragment

In SubActivity and DrawerActivity I am using the same repository instance which is marked as @Singleton.

    @Singleton
    @Component(modules = {
            AndroidInjectionModule.class,
            AppModule.class,
            ActivityBuilderModule.class
    })
    public interface AppComponent {
        @Component.Builder
        interface Builder{
            @BindsInstance Builder application(Application application);

            AppComponent build();
        }
        void inject(App app);
    }

    @Module
    public abstract class ActivityBuilderModule {
        @PerActivity
        @ContributesAndroidInjector(modules = {DrawerActivityModule.class, 
        FragmentBuilderModule.class})
        abstract DrawerActivity bindDrawerActivity();
        
        @PerActivity
        @ContributesAndroidInjector(modules = {DrawerActivityModule.class})
        abstract SubActivity bindSubActivity();
    }

    @Module
    public abstract class FragmentBuilderModule {
        @PerFragment
        @ContributesAndroidInjector(modules = DrawerFragmentModule.class)
        abstract DrawerFragment provideDrawerFragment();
    }

    @Singleton
    public class Repository{
        private SomeClass mSomeClass;

        @Inject
        public VehicleRepositoryImpl(SomeClass someClass) {
            mSomeClass = someClass;
        }
    }

    public class App extends Application implements HasActivityInjector{
        @Inject
        DispatchingAndroidInjector<Activity> dispatchingAndroidInjector;

        @Override
        public void onCreate() {
            super.onCreate();
            if (BuildConfig.DEBUG) {
                Timber.plant(new Timber.DebugTree());
            }
            AppComponent component = DaggerAppComponent.builder().application(this)
                    .build();
            component.inject(this);
        }

        @Override
        public AndroidInjector<Activity> activityInjector() {
            return dispatchingAndroidInjector;
        }
    }    

    public class DrawerActivity extends AppCompatActivity implements HasSupportFragmentInjector{
        @Inject
        DispatchingAndroidInjector<Fragment> fragmentDispatchingAndroidInjector;

        @Override
        public AndroidInjector<Fragment> supportFragmentInjector() {
            return fragmentDispatchingAndroidInjector;
        }

        @Override
        protected void onCreate(Bundle savedInstanceState) {
            AndroidInjection.inject(this);
            super.onCreate(savedInstanceState);
        }
    }

    public class DrawerFragment extends Fragment {
        @Inject
        ViewModelFactory mViewModelFactory; //repository gets injected into factory
        
        @Override
        public void onCreate(@Nullable Bundle savedInstanceState) {
            AndroidSupportInjection.inject(this);
            super.onCreate(savedInstanceState);
        }
    }
    
    public class SubActivity extends AppCompatActivity{
        @Inject
        Repository mRepository;

        @Override
        protected void onCreate(Bundle savedInstanceState) {
            AndroidInjection.inject(this);
            super.onCreate(savedInstanceState);
        }
    }

I have now the need to add a user management. This requires a LoginActivity. I don't want the repository to be avaiblable in LoginActivity. So I'd like to create a local singleton scope "UserScope" for DrawerActivity/Subactivity/DrawerFragement

                  Component Application
               /                         \
       @UserScope                       @LoginScope 
       Subcomponent DrawerActivity      SubComponent LoginActivity
          |                        \
    Subcomponent DrawerFragment   Subcomponent SubActivity

How can I achieve this still using the new @ContributesAndroidInjector annotation?

I want it to work like in this blogpost: http://frogermcs.github.io/building-userscope-with-dagger2/

**Comment by ronshapiro** [comment]
This appears to be a question - please use StackOverflow with the `dagger-2` tag instead, as that is a better forum for questions.
