### ISSUE TITLE
@Generated not found

### ISSUE THREAD

**Issue by sockeqwe** [google/dagger#95]
Hi, 
I think it's a problem with my environment (java 1.7.0_51, 64 bit, mac os 10.10), but I'm using Android Studio and tried to setup  a simple android sample application with dagger 2 as dependency injection framework.

My compiler can not resolve the `@Generated` annotation in class path (`import javax.annotation.Generated;`) which is used in all dagger generated classes.

My gradle build file looks like this:
```groovy
compile 'com.google.dagger:dagger:2.0-SNAPSHOT'
provided 'com.google.dagger:dagger-compiler:2.0-SNAPSHOT'
```

Any idea what could be wrong?
Do I have to add the javax annotation dependency to my `build.gradle`?

**Comment by cgruber** [comment]
this is a local project configuration matter. If you're targetting a JVM that doesnt' have it, you need to add it, per the instructions above.

**Comment by mttkay** [comment]
Why Glassfish? Why not the official Java annotations from Oracle?

https://repo1.maven.org/maven2/javax/annotation/javax.annotation-api/1.2/javax.annotation-api-1.2.pom

**Comment by svenjacobs** [comment]
I think the correct dependency which should be added is `javax.annotation:jsr250-api:1.0`. At least this one only contains the annotations from JSR 250.

I added this to my Android Gradle project:

```groove
provided 'javax.annotation:jsr250-api:1.0'
```

**Comment by ronshapiro** [comment]
I just submitted some code (and will be linked to this issue in the next MOE sync) that omits `@Generated` and instead includes a comment about the generation step if `javax.annotation.Generated` is not on the compile-time classpath.

**Comment by ronshapiro** [comment]
The commit which omits @Generated is now synced and should be in a `2.1-SNAPSHOT`

**Comment by rafnogueira** [comment]
Probably this happened because the system JDK_HOME is more upgraded then the JDK that comes with Android Studio

**Comment by RiteshAdulkar** [comment]
I have installed sdkman more here: https://sdkman.io/usage#installdefault, downgraded java version from 11 to 8 and this error did go away. That way it worked for me.
