### ISSUE TITLE
Whether fit the Android Studio 3.0？

### ISSUE THREAD

**Issue by gdky005** [google/dagger#952]
I didn't generate DaggerXXXX test and found the demo, can't run.

`classpath com.android.tools.build:gradle:3.0.0`

`compile com.google.dagger:dagger-android:2.13`
`com.google.dagger:dagger-android-processor:2.13`

**Comment by ronshapiro** [comment]
This appears to be a question - please use StackOverflow with the `dagger-2` tag instead, as that is a better forum for questions.
