### ISSUE TITLE
Support Gradle's upcoming incremental annotation processing feature

### ISSUE THREAD

**Issue by ZakTaccardi** [google/dagger#959]
https://github.com/gradle/incap

Similar to #298

**Comment by ronshapiro** [comment]
I don't see any docs for this, nor any timeline for when/if this is actually happening. Do you have any context on this?

**Comment by gabrielittner** [comment]
> we do not support APs that have a many-to-1 or many-to-many annotation:genfile relationship
https://github.com/gradle/incap/issues/100

That sounds like a limitation that Dagger falls under.

**Comment by ZakTaccardi** [comment]
> I don't see any docs for this, nor any timeline for when/if this is actually happening. Do you have any context on this?

Unfortunately, not really. This is the biggest issue that blocks me from using Dagger. Unfortunately now annotation processing + gradle == no incremental builds which is a huge pain point in the android development experience.

I was hoping somehow the dagger2/gradle team on this could work together to make this happen.

**Comment by ronshapiro** [comment]
Thanks @gabrielittner. In that case, I think it makes sense to close this...

**Comment by JakeWharton** [comment]
The gains to be had from modularization which provides parallelism and compilation avoidance likely will dwarf anything incremental annotation processing could achieve.

**Comment by ZakTaccardi** [comment]
> The gains to be had from modularization which provides parallelism and compilation avoidance likely will dwarf anything incremental annotation processing could achieve.

We should definitely modularize. But it would be nice to have both

**Comment by LuigiPapino** [comment]
I actually got a 50% cut on my clean build time, modularizing the app.
But the process to adapt the dagger components required some effort. Didn't find a way to use properly AndroidInjectors and @Contribute within a feature module.

But definitely worth it for the build speed up.
