### ISSUE TITLE
Dagger documentation page broken?

### ISSUE THREAD

**Issue by liminal** [google/dagger#968]
I'm sorry if it's just me but I've not been able to use the Dagger documentation pages for a few days now.
Nothing is clickable and the styling is off. I thought it might be a browser plugin messing up but it looks like the attached screenshot even in an incognito browser and it looks the same from two different OSes (ubuntu / OS X) in two different offices.

Screenshot is on Google Chrome (Version 63.0.3239.59 (Official Build) beta (64-bit)) on ubuntu 17.10

![screenshot from 2017-12-03 13-46-25](https://user-images.githubusercontent.com/421840/33525495-dfbb9870-d830-11e7-9051-6602a7340367.png)

**Comment by ashdavies** [comment]
I've had this also on Google Chrome Dev build for some time now, its fine for Firefox and Opera though

**Comment by tbroyer** [comment]
In Chrome stable, console shows:

> [Deprecation] Styling master document from stylesheets defined in HTML Imports is deprecated, and is planned to be removed in M65, around March 2018. Please refer to https://goo.gl/EGXzpw for possible migration paths.
> [Deprecation] /deep/ combinator in CSS is deprecated and will be removed in M63, around December 2017. See https://www.chromestatus.com/features/4964279606312960 for more details.
core-header-panel.html:259
> [Deprecation] ::shadow pseudo-element in CSS is deprecated and will be removed in M63, around December 2017. See https://www.chromestatus.com/features/6750456638341120 for more details.
scroll @ core-header-panel.html:259

Hopefully would only need an update of the web components used on the site.

**Comment by TWiStErRob** [comment]
Raised a PR.

**Comment by defio** [comment]
+1

**Comment by murmurmuk** [comment]
There is something wrong on firefox.
Screenshot is on firefox (Version 57.0)
![25551486_1976649785684480_952024399_o](https://user-images.githubusercontent.com/12742205/34110090-922f1ea8-e440-11e7-9e64-0adfb735a2f1.png)

**Comment by TWiStErRob** [comment]
Hmm, @ronshapiro that's probably the first TODO in my PR (Apply polyfills, since platforms.js was removed); at least it's navigable, even if not particularly eye candy :)

**Comment by ronshapiro** [comment]
@murmurmuk can you view the link in #992 and see if that fixes things?

**Comment by ronshapiro** [comment]
Those should be fixed as of https://github.com/google/dagger/commit/1e8cfea5113f48f39aa6e8296eecfa7883d3a162

If not, let me know and I'll reopen!
