### ISSUE TITLE
Component javadoc says abstract classes are ok

### ISSUE THREAD

**Issue by adriancole** [google/dagger#97]
Component says "interface or abstract class", but only interfaces are currently supported. Is this a gap or an intent?

**Comment by cgruber** [comment]
@gk5885 - where did we land on this.  I think they're not ok for now, but we had some plans to enable them.  I think we need to fix the javadoc, or let the abstract classes through.  My vote is no, for 2.0, and just update the javadocs.

**Comment by gk5885** [comment]
And they are!  I just fixed this.  It should get sync'd soon.

**Comment by cgruber** [comment]
#145
