### ISSUE TITLE
DexException: Multiple dex files define FragmentsBuildersModule

### ISSUE THREAD

**Issue by kaserdan** [google/dagger#979]
Hi, 
I am trying to a setup DI using dagger:2.12, dagger-android-support:2.12 just as in [GithubBrowserSample](https://github.com/googlesamples/android-architecture-components/tree/master/GithubBrowserSample). I have a library project with CoreFragment as base class for all Fragments I use. 

```java
@Module
abstract class FragmentsBuildersModule {

    @ContributesAndroidInjector
    internal abstract fun contributeCustomerDetailFragment(): CoreFragment

}
```
``` java
@Module
abstract class CoreActivityModule {

    @ContributesAndroidInjector(modules = arrayOf(FragmentsBuildersModule::class))
    internal abstract fun contributeCoreActivity(): CoreActivity

}
```
```java
@Component(modules = arrayOf(CoreFacadeModule::class, CoreActivityModule::class))
@Singleton
interface CoreAppComponent {

    void inject(CoreApp optifyApp)

}
```

I can't build my application using this library project. I am getting following error:

Error:Error converting bytecode to dex:
Cause: com.android.dex.DexException: Multiple dex files define Lcz/tangosw/core/di/FragmentsBuildersModule;
Error:com.android.dex.DexException: Multiple dex files define Lcz/company/core/di/FragmentsBuildersModule;
Error:	at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:661)
Error:	at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:616)
Error:	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:598)
Error:	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
Error:	at com.android.dx.merge.DexMerger.merge(DexMerger.java:198)
Error:	at com.android.builder.dexing.DexArchiveMergerCallable.call(DexArchiveMergerCallable.java:61)
Error:	at com.android.builder.dexing.DexArchiveMergerCallable.call(DexArchiveMergerCallable.java:36)
Error:	at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424)
Error:	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
Error:	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
Error:	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
Error:	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Error:Execution failed for task ':app:transformDexArchiveWithDexMergerForDebug'.
com.android.build.api.transform.TransformException: com.android.dex.DexException: Multiple dex files define Lcz/company/core/di/FragmentsBuildersModule;

**Comment by ronshapiro** [comment]
This appears to be a question - please use StackOverflow with the `dagger-2` tag instead, as that is a better forum for questions.
