### ISSUE TITLE
How is the lifetime of activity subcomponentens handled?

### ISSUE THREAD

**Issue by wkamir** [google/dagger#985]
According to [this article](https://proandroiddev.com/dagger-2-part-ii-custom-scopes-component-dependencies-subcomponents-697c1fa1cfc) (see last code sample on page) a subcomponent actually has to be destroyed (or rather dereferenced) once its lifetime is over.

As far as I've understood this is all that is really happening when different scopes are required - just subcomponents that live for a short while under a parent component.

How is lifetime of subcomponents (for activities and fragments) handled? I can't seem to find the according code in the dagger.android

Thanks,
Wolfgang

**Comment by JakeWharton** [comment]
That is inaccurate. As long as the reference doesn't leak into something higher up you should never have to explicitly dereference anything nor call any specific function to destroy a component. Once the activity is no longer attached to a GC root the GC will collect it and every object it references (including the component).

**Comment by wkamir** [comment]
Thank you for the Insight!

But is the subcomponent not referenced by the Application or it's parent component in some way? Respectively - does the subcomponent not also hold a reference to the activity?

Or is the subcomponent only referenced by the activity and therefore gets garbage collected with it?

Thanks!

**Comment by JakeWharton** [comment]
The parent component is a factory for subcomponents but does not retain
references to them. The subcomponent has a reference to the activity, yes.
This does not affect the GC's ability to collect both objects at the same
time.

**Comment by wkamir** [comment]
Ok thank you... last question: ... You implied that the subcomponent's lifetime is bound to the activity's component. Does this mean that the activity holds the reference to the component?

In the article (first post) it seems that it is common practice to hold the subcomponent references in the Application class.

**Comment by wkamir** [comment]
ooooh... it's those, isn't it?

```
@Inject DispatchingAndroidInjector<Fragment> supportFragmentInjector;
@Inject DispatchingAndroidInjector<android.app.Fragment> frameworkFragmentInjector;
```
