### ISSUE TITLE
Add integration test which uses latest-built compiler

### ISSUE THREAD

**Issue by ronshapiro** [google/dagger#995]
#994 identified an issue where we forgot to shade the `dagger-spi` artifact. Our tests never found this since they don't use maven. We should have a test that runs `util/install-local-snapshot.sh` and then runs a maven build with the `LOCAL-SNAPSHOT` build.

Either that, or a way in our release script to verify that we are correctly shading everything.

**Comment by ronshapiro** [comment]
This may now be as simple as just:

```
bazel test //...
bazel build //java/dagger/internal/codegen:new_bootstrap_compiler_deploy.jar
cp bazel-bin/java/dagger/internal/codegen/new_bootstrap_compiler_deploy.jar java/dagger/internal/codegen/bootstrap_compiler_deploy.jar
bazel test //...
```

**Comment by bcorso** [comment]
Closing this, since we added these tests a while ago, e.g. https://github.com/google/dagger/blob/master/util/run-local-tests.sh#L16-L33, and also a blaze rule for validation of deps, https://github.com/google/dagger/blob/master/tools/maven.bzl#L226
